#ifndef TESTPARTICLEGENERATOR_GLOBAL_H
#define TESTPARTICLEGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTPARTICLEGENERATOR_LIBRARY)
#  define TESTPARTICLEGENERATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTPARTICLEGENERATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTPARTICLEGENERATOR_GLOBAL_H
