/home/peer23peer/VisionSoilAnalyzer/src/Tests/Soil_Test/Matlab_code/GenBlob.m File Reference
Functions
rgbmat (:,:, 1)
rgbmat (:,:, 2)
rgbmat (:,:, 3)
mask (mask==1)=0
mask (mask > 1)
Variables
function [rgbmat, actualsize, meanlab, meanri]
rmat = uint8((colorrange(2,1) - colorrange(1,1)).*rand(creationsize(1), creationsize(2)) + colorrange(1,1))
gmat = uint8((colorrange(2,2) - colorrange(1,2)).*rand(creationsize(1), creationsize(2)) + colorrange(1,2))
bmat = uint8((colorrange(2,3) - colorrange(1,3)).*rand(creationsize(1), creationsize(2)) + colorrange(1,3))
rgbmat = uint8(zeros(creationsize(1), creationsize(2), 3))
maskcolor = uint8([1])
m = uint8(zeros(creationsize(1), creationsize(2),1))
switch basicshape case Circle shapeInserter = vision.ShapeInserter('Shape', 'Circles', 'BorderColor', 'Custom', 'CustomBorderColor', maskcolor, 'Fill', true, 'FillColor', 'Custom', 'CustomFillColor', maskcolor, 'Opacity', 1)
circle = int32([creationsize(1) / 2, creationsize(2)/2, (min(creationsize) / 2.5)])
mask = step(shapeInserter, m, circle)
rect = int32([creationsize(2) / 10, creationsize(1)/10, creationsize(2) - (2 * (creationsize(2)/10)), creationsize(1) - (2 * (creationsize(1)/10)) ])
case Pentangle end J = imnoise(mask, 'salt & pepper', roughness)
hclosing = vision.MorphologicalClose
strelsize = double(round(min(creationsize)/15))
hclosing Neighborhood = strel('disk', strelsize)
Function Documentation
mask (mask = =1) [pure virtual]
mask (mask , 1)
rgbmat (: , : , 1)
rgbmat (: , : , 2)
rgbmat (: , : , 3)
Variable Documentation
bmat = uint8((colorrange(2,3) - colorrange(1,3)).*rand(creationsize(1), creationsize(2)) + colorrange(1,3))
Definition at line 11 of file GenBlob.m.
circle = int32([creationsize(1) / 2, creationsize(2)/2, (min(creationsize) / 2.5)])
Definition at line 24 of file GenBlob.m.
Referenced by SoilAnalyzer::Sample::PrepImg().
function[rgbmat, actualsize, meanlab, meanri]
Initial value:
= GenBlob(creationsize, basicshape, roughness, colorrange)
%Create a blob with certain characteristics
%creationsize as a 2 vector
%basicshape 'Circle', 'Rectangle' or Pentangle
%roughness 0.1...0.9 amount of distortion
%colorrange 2x3 RGB matrix
roughness = 1 - roughness
Definition at line 1 of file GenBlob.m.
gmat = uint8((colorrange(2,2) - colorrange(1,2)).*rand(creationsize(1), creationsize(2)) + colorrange(1,2))
Definition at line 10 of file GenBlob.m.
hclosing = vision.MorphologicalClose
Definition at line 36 of file GenBlob.m.
case Pentangle end J = imnoise(mask, 'salt & pepper', roughness)
Definition at line 34 of file GenBlob.m.
m = uint8(zeros(creationsize(1), creationsize(2),1))
Definition at line 20 of file GenBlob.m.
Referenced by QCPMarginGroup::commonMargin(), and Vision::ImageProcessing::CopyMat().
mask = step(shapeInserter, m, circle)
Definition at line 25 of file GenBlob.m.
Referenced by BOOST_AUTO_TEST_CASE(), Vision::Segment::GetEdgesEroding(), SoilAnalyzer::Sample::PrepImg(), and SoilMath_Test::testCase_Mat_Stats_Mask().
maskcolor = uint8([1])
Definition at line 18 of file GenBlob.m.
hclosing Neighborhood = strel('disk', strelsize)
Definition at line 38 of file GenBlob.m.
rect = int32([creationsize(2) / 10, creationsize(1)/10, creationsize(2) - (2 * (creationsize(2)/10)), creationsize(1) - (2 * (creationsize(1)/10)) ])
Definition at line 28 of file GenBlob.m.
Referenced by QCPItemRect::anchorPixelPoint(), QCPItemEllipse::anchorPixelPoint(), QCPItemPixmap::anchorPixelPoint(), QCPItemRect::draw(), QCPItemPixmap::draw(), QCustomPlot::QCustomPlot(), QCustomPlot::rescaleAxes(), QCustomPlot::resizeEvent(), QCustomPlot::selectedAxes(), QCPItemRect::selectTest(), QCPItemTracer::selectTest(), QCPAbstractItem::setClipAxisRect(), and QCustomPlot::setViewport().
rgbmat = uint8(zeros(creationsize(1), creationsize(2), 3))
Definition at line 12 of file GenBlob.m.
rmat = uint8((colorrange(2,1) - colorrange(1,1)).*rand(creationsize(1), creationsize(2)) + colorrange(1,1))
Definition at line 9 of file GenBlob.m.
case Rectangle shapeInserter = vision.ShapeInserter('Shape', 'Circles', 'BorderColor', 'Custom', 'CustomBorderColor', maskcolor, 'Fill', true, 'FillColor', 'Custom', 'CustomFillColor', maskcolor, 'Opacity', 1)
Definition at line 23 of file GenBlob.m.
strelsize = double(round(min(creationsize)/15))
Definition at line 37 of file GenBlob.m.