Hardware::GPIO Class Reference
#include <GPIO.h>
Public Types
enum Direction { Input,
Output
 }
enum Value { Low = 0,
High = 1
 }
enum Edge { None,
Rising,
Falling,
Both
 }
Public Member Functions
int WaitForEdge ()
int WaitForEdge (CallbackType callback)
void WaitForEdgeCancel ()
Value GetValue ()
void SetValue (Value value)
Direction GetDirection ()
void SetDirection (Direction direction)
Edge GetEdge ()
void SetEdge (Edge edge)
GPIO (int number)
~GPIO ()
Public Attributes
int number
Private Member Functions
bool isExported (int number, Direction &dir, Edge &edge)
bool ExportPin (int number)
bool UnexportPin (int number)
Direction ReadsDirection (const string &gpiopath)
void WritesDirection (const string &gpiopath, Direction direction)
Edge ReadsEdge (const string &gpiopath)
void WritesEdge (const string &gpiopath, Edge edge)
Value ReadsValue (const string &gpiopath)
void WritesValue (const string &gpiopath, Value value)
Private Attributes
string gpiopath
Direction direction
Edge edge
Friends
void * threadedPollGPIO (void *value)
Additional Inherited Members
Detailed Description
Definition at line 22 of file GPIO.h.
Member Enumeration Documentation
enum Hardware::GPIO::Direction
Enumerator
Input
Output
Definition at line 26 of file GPIO.h.
{ Input, Output };
enum Hardware::GPIO::Edge
Enumerator
None
Rising
Falling
Both
Definition at line 28 of file GPIO.h.
{ None, Rising, Falling, Both };
enum Hardware::GPIO::Value
Enumerator
Low
High
Definition at line 27 of file GPIO.h.
{ Low = 0, High = 1 };
Constructor & Destructor Documentation
Hardware::GPIO::GPIO (int number)
Definition at line 5 of file GPIO.cpp.
References direction, edge, ExportPin(), gpiopath, GPIOS, isExported(), number, ReadsDirection(), and ReadsEdge().
    {
        this->number = number;
        gpiopath = GPIOS + NumberToString<int>(number);
        if (!isExported(number, direction, edge))
        {
            ExportPin(number);
            direction = ReadsDirection(gpiopath);
            edge = ReadsEdge(gpiopath);
        }
        usleep(250000);
    }
Hardware::GPIO::~GPIO ()
Definition at line 20 of file GPIO.cpp.
References number, and UnexportPin().
    {
        UnexportPin(number);
    }
Member Function Documentation
bool Hardware::GPIO::ExportPin (int number) [private]
Definition at line 106 of file GPIO.cpp.
References EXPORT_PIN, and Hardware::BBB::Write().
Referenced by GPIO().
    {
        Write(EXPORT_PIN, NumberToString<int>(number));
        usleep(250000);
    }
GPIO::Direction Hardware::GPIO::GetDirection ()
Definition at line 81 of file GPIO.cpp.
References direction.
{ return direction; }
GPIO::Edge Hardware::GPIO::GetEdge ()
Definition at line 88 of file GPIO.cpp.
References edge.
{ return edge; }
GPIO::Value Hardware::GPIO::GetValue ()
Definition at line 78 of file GPIO.cpp.
References gpiopath, and ReadsValue().
{ return ReadsValue(gpiopath); }
bool Hardware::GPIO::isExported (int number, Direction & dir, Edge & edge) [private]
Definition at line 95 of file GPIO.cpp.
References Hardware::BBB::DirectoryExist(), gpiopath, ReadsDirection(), and ReadsEdge().
Referenced by GPIO().
    {
        // Checks if directory exist and therefore is exported
        if (!DirectoryExist(gpiopath)) { return false; }
        // Reads the data associated with the pin
        dir = ReadsDirection(gpiopath);
        edge = ReadsEdge(gpiopath);
        return true;
    }
GPIO::Direction Hardware::GPIO::ReadsDirection (const string & gpiopath) [private]
Definition at line 118 of file GPIO.cpp.
References DIRECTION, Input, Output, and Hardware::BBB::Read().
Referenced by GPIO(), and isExported().
    {
        if (Read(gpiopath + DIRECTION) == "in") { return
      Input; }
        else { return Output; }
    }
GPIO::Edge Hardware::GPIO::ReadsEdge (const string & gpiopath) [private]
Definition at line 137 of file GPIO.cpp.
References Both, EDGE, Falling, None, Hardware::BBB::Read(), and Rising.
Referenced by GPIO(), and isExported().
    {
        string reader = Read(gpiopath + EDGE);
        if (reader == "none") { return None; }
        else if (reader == "rising") { return Rising; }
        else if (reader == "falling") { return Falling; }
        else { return Both; }
    }
GPIO::Value Hardware::GPIO::ReadsValue (const string & gpiopath) [private]
Definition at line 167 of file GPIO.cpp.
References Hardware::BBB::Read(), and VALUE.
Referenced by GetValue().
    {
        string path(gpiopath + VALUE);
        int res = StringToNumber<int>(Read(path));
        return (Value)res;
    }
void Hardware::GPIO::SetDirection (Direction direction)
Definition at line 82 of file GPIO.cpp.
References direction, gpiopath, and WritesDirection().
Referenced by Hardware::EC12P::EC12P(), and WaitForEdge().
    {
        this->direction = direction;
        WritesDirection(gpiopath, direction);
    }
void Hardware::GPIO::SetEdge (Edge edge)
Definition at line 89 of file GPIO.cpp.
References edge, gpiopath, and WritesEdge().
Referenced by Hardware::EC12P::EC12P().
    {
        this->edge = edge;
        WritesEdge(gpiopath, edge);
    }
void Hardware::GPIO::SetValue (GPIO::Value value)
Definition at line 79 of file GPIO.cpp.
References gpiopath, and WritesValue().
Referenced by Hardware::EC12P::SetPixelColor().
{ WritesValue(gpiopath, value); }
bool Hardware::GPIO::UnexportPin (int number) [private]
Definition at line 112 of file GPIO.cpp.
References UNEXPORT_PIN, and Hardware::BBB::Write().
Referenced by ~GPIO().
    {
        Write(UNEXPORT_PIN, NumberToString<int>(number));
    }
int Hardware::GPIO::WaitForEdge ()
Definition at line 37 of file GPIO.cpp.
References count, direction, gpiopath, i, Input, Output, SetDirection(), and VALUE.
Referenced by Hardware::threadedPollGPIO().
    {
        if (direction == Output) { SetDirection(Input); }
        int fd, i, epollfd, count = 0;
        struct epoll_event ev;
        epollfd = epoll_create(1);
        if (epollfd == -1)
        {
            throw Exception::FailedToCreateGPIOPollingThreadException("GPIO: Failed to create epollfd!");
        }
        if ((fd = open((gpiopath + VALUE).c_str(), O_RDONLY | O_NONBLOCK)) == -1)
        {
            throw Exception::GPIOReadException();
        }
        // read operation | edge triggered | urgent data
        ev.events = EPOLLIN | EPOLLET | EPOLLPRI;
        ev.data.fd = fd;
        if (epoll_ctl(epollfd, EPOLL_CTL_ADD, fd, &ev) == -1)
        {
            throw Exception::FailedToCreateGPIOPollingThreadException("GPIO: Failed to add control
       interface!");
        }
        while (count <= 1)
        {
            i = epoll_wait(epollfd, &ev, 1, -1);
            if (i == -1)
            {
                close(fd);
                return -1;
            }
            else
            {
                count++;
            }
        }
        close(fd);
        return 0;
    }
int Hardware::GPIO::WaitForEdge (CallbackType callback)
Definition at line 25 of file GPIO.cpp.
References Hardware::BBB::callbackFunction, Hardware::BBB::thread, threadedPollGPIO, and Hardware::BBB::threadRunning.
    {
        threadRunning = true;
        callbackFunction = callback;
        if (pthread_create(&this->thread, NULL, &threadedPollGPIO, static_cast<void*>
      (this)))
        {
            threadRunning = false;
            throw Exception::FailedToCreateGPIOPollingThreadException();
        }
        return 0;
    }
void Hardware::GPIO::WaitForEdgeCancel () [inline]
Definition at line 34 of file GPIO.h.
{ this->threadRunning = false; }
void Hardware::GPIO::WritesDirection (const string & gpiopath, Direction direction) [private]
Definition at line 124 of file GPIO.cpp.
References DIRECTION, Input, Output, and Hardware::BBB::Write().
Referenced by SetDirection().
    {
        switch (direction)
        {
        case Hardware::GPIO::Input:
            Write((gpiopath + DIRECTION), "in");
            break;
        case Hardware::GPIO::Output:
            Write((gpiopath + DIRECTION), "out");
            break;
        }
    }
void Hardware::GPIO::WritesEdge (const string & gpiopath, Edge edge) [private]
Definition at line 146 of file GPIO.cpp.
References Both, EDGE, Falling, None, Rising, and Hardware::BBB::Write().
Referenced by SetEdge().
    {
        switch (edge)
        {
        case Hardware::GPIO::None:
            Write((gpiopath + EDGE), "none");
            break;
        case Hardware::GPIO::Rising:
            Write((gpiopath + EDGE), "rising");
            break;
        case Hardware::GPIO::Falling:
            Write((gpiopath + EDGE), "falling");
            break;
        case Hardware::GPIO::Both:
            Write((gpiopath + EDGE), "both");
            break;
        default:
            break;
        }
    }
void Hardware::GPIO::WritesValue (const string & gpiopath, Value value) [private]
Definition at line 174 of file GPIO.cpp.
References VALUE, and Hardware::BBB::Write().
Referenced by SetValue().
    {
        Write(gpiopath + VALUE, NumberToString<int>(value));
    }
Friends And Related Function Documentation
void* threadedPollGPIO (void * value) [friend]
Definition at line 180 of file GPIO.cpp.
Referenced by WaitForEdge().
    {
        GPIO *gpio = static_cast<GPIO*>(value);
        while (gpio->threadRunning)
        {
            gpio->callbackFunction(gpio->WaitForEdge());
            usleep(gpio->debounceTime * 1000);
        }
        return 0;
    }
Member Data Documentation
Direction Hardware::GPIO::direction [private]
Definition at line 50 of file GPIO.h.
Referenced by GetDirection(), GPIO(), SetDirection(), and WaitForEdge().
Edge Hardware::GPIO::edge [private]
Definition at line 51 of file GPIO.h.
Referenced by GetEdge(), GPIO(), and SetEdge().
string Hardware::GPIO::gpiopath [private]
Definition at line 49 of file GPIO.h.
Referenced by GetValue(), GPIO(), isExported(), SetDirection(), SetEdge(), SetValue(), and WaitForEdge().
int Hardware::GPIO::number
Definition at line 30 of file GPIO.h.
Referenced by GPIO(), and ~GPIO().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/GPIO.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/GPIO.cpp