QCPColorScale Class Reference
A color scale for use with color coding data such as QCPColorMap.
#include <qcustomplot.h>
Signals
void dataRangeChanged (QCPRange newRange)
void dataScaleTypeChanged (QCPAxis::ScaleType scaleType)
void gradientChanged (QCPColorGradient newGradient)
Public Member Functions
QCPColorScale (QCustomPlot *parentPlot)
virtual ~QCPColorScale ()
QCPAxis * axis () const
QCPAxis::AxisType type () const
QCPRange dataRange () const
QCPAxis::ScaleType dataScaleType () const
QCPColorGradient gradient () const
QString label () const
int barWidth () const
bool rangeDrag () const
bool rangeZoom () const
void setType (QCPAxis::AxisType type)
Q_SLOT void setDataRange (const QCPRange &dataRange)
Q_SLOT void setDataScaleType (QCPAxis::ScaleType scaleType)
Q_SLOT void setGradient (const QCPColorGradient &gradient)
void setLabel (const QString &str)
void setBarWidth (int width)
void setRangeDrag (bool enabled)
void setRangeZoom (bool enabled)
QList< QCPColorMap * > colorMaps () const
void rescaleDataRange (bool onlyVisibleMaps)
virtual void update (UpdatePhase phase)
Protected Member Functions
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
Protected Attributes
QCPAxis::AxisType mType
QCPRange mDataRange
QCPAxis::ScaleType mDataScaleType
QCPColorGradient mGradient
int mBarWidth
QPointer< QCPColorScaleAxisRectPrivate > mAxisRect
QPointer< QCPAxis > mColorAxis
Friends
class QCPColorScaleAxisRectPrivate
Additional Inherited Members
Detailed Description
A color scale for use with color coding data such as QCPColorMap.
This layout element can be placed on the plot to correlate a color gradient with data values. It is usually used in combination with one or multiple QCPColorMaps.
The color scale can be either horizontal or vertical, as shown in the image above. The orientation and the side where the numbers appear is controlled with setType.
Use QCPColorMap::setColorScale to connect a color map with a color scale. Once they are connected, they share their gradient, data range and data scale type (setGradient, setDataRange, setDataScaleType). Multiple color maps may be associated with a single color scale, to make them all synchronize these properties.
To have finer control over the number display and axis behaviour, you can directly access the axis. See the documentation of QCPAxis for details about configuring axes. For example, if you want to change the number of automatically generated ticks, call
qcpcolorscale-autotickcount
Placing a color scale next to the main axis rect works like with any other layout element:
In this case we have placed it to the right of the default axis rect, so it wasn't necessary to call setType, since QCPAxis::atRight is already the default. The text next to the color scale can be set with setLabel.
For optimum appearance (like in the image above), it may be desirable to line up the axis rect and the borders of the color scale. Use a QCPMarginGroup to achieve this:
qcpcolorscale-margingroup
Color scales are initialized with a non-zero minimum top and bottom margin (setMinimumMargins), because vertical color scales are most common and the minimum top/bottom margin makes sure it keeps some distance to the top/bottom widget border. So if you change to a horizontal color scale by setting setType to QCPAxis::atBottom or QCPAxis::atTop, you might want to also change the minimum margins accordingly, e.g. setMinimumMargins(QMargins(6, 0, 6, 0)).
Definition at line 2729 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPColorScale::QCPColorScale (QCustomPlot * parentPlot) [explicit]
Constructs a new QCPColorScale.
Definition at line 15132 of file qcustomplot.cpp.
References QCPAxis::atRight, setDataRange(), QCPLayoutElement::setMinimumMargins(), and setType().
    : QCPLayoutElement(parentPlot),
      mType(QCPAxis::atTop), // set to atTop such that setType(QCPAxis::atRight)
                             // below doesn't skip work because it thinks it's
                             // already atRight
      mDataScaleType(QCPAxis::stLinear),
      mBarWidth(20),
      mAxisRect(new QCPColorScaleAxisRectPrivate(this)) {
  setMinimumMargins(QMargins(0, 6, 0, 6)); // for default right color scale
                                           // types, keep some room at bottom
                                           // and top (important if no margin
                                           // group is used)
  setType(QCPAxis::atRight);
  setDataRange(QCPRange(0, 6));
}
QCPColorScale::~QCPColorScale () [virtual]
Definition at line 15147 of file qcustomplot.cpp.
References mAxisRect.
{ delete mAxisRect; }
Member Function Documentation
void QCPColorScale::applyDefaultAntialiasingHint (QCPPainter * painter) const [protected], [virtual]
Reimplemented from QCPLayoutElement.
Definition at line 15490 of file qcustomplot.cpp.
References QCPPainter::setAntialiasing().
                                                                          {
  painter->setAntialiasing(false);
}
QCPAxis * QCPColorScale::axis () const [inline]
Returns the internal QCPAxis instance of this color scale. You can access it to alter the appearance and behaviour of the axis. QCPColorScale duplicates some properties in its interface for convenience. Those are setDataRange (QCPAxis::setRange), setDataScaleType (QCPAxis::setScaleType), and the method setLabel (QCPAxis::setLabel). As they each are connected, it does not matter whether you use the method on the QCPColorScale or on its QCPAxis.
If the type of the color scale is changed with setType, the axis returned by this method will change, too, to either the left, right, bottom or top axis, depending on which type was set.
Definition at line 2749 of file qcustomplot.h.
{ return mColorAxis.data(); }
int QCPColorScale::barWidth () const [inline]
Definition at line 2755 of file qcustomplot.h.
{ return mBarWidth; }
QList< QCPColorMap * > QCPColorScale::colorMaps () const
Returns a list of all the color maps associated with this color scale.
Definition at line 15372 of file qcustomplot.cpp.
References i, QCPLayerable::mParentPlot, QCustomPlot::plottable(), and QCustomPlot::plottableCount().
Referenced by rescaleDataRange().
                                                    {
  QList<QCPColorMap *> result;
  for (int i = 0; i < mParentPlot->plottableCount(); ++
      i) {
    if (QCPColorMap *cm =
            qobject_cast<QCPColorMap *>(mParentPlot->plottable(
      i)))
      if (cm->colorScale() == this)
        result.append(cm);
  }
  return result;
}
QCPRange QCPColorScale::dataRange () const [inline]
Definition at line 2751 of file qcustomplot.h.
Referenced by setDataRange().
{ return mDataRange; }
void QCPColorScale::dataRangeChanged (QCPRange newRange) [signal]
This signal is emitted when the data range changes.
See also
setDataRange
Referenced by setDataRange().
QCPAxis::ScaleType QCPColorScale::dataScaleType () const [inline]
Definition at line 2752 of file qcustomplot.h.
{ return mDataScaleType; }
void QCPColorScale::dataScaleTypeChanged (QCPAxis::ScaleType scaleType) [signal]
This signal is emitted when the data scale type changes.
See also
setDataScaleType
Referenced by setDataScaleType().
QCPColorGradient QCPColorScale::gradient () const [inline]
Definition at line 2753 of file qcustomplot.h.
Referenced by setGradient().
{ return mGradient; }
void QCPColorScale::gradientChanged (QCPColorGradient newGradient) [signal]
This signal is emitted when the gradient changes.
See also
setGradient
Referenced by setGradient().
QString QCPColorScale::label () const
Definition at line 15150 of file qcustomplot.cpp.
References mColorAxis.
                                   {
  if (!mColorAxis) {
    qDebug() << Q_FUNC_INFO << "internal color axis undefined";
    return QString();
  }
  return mColorAxis.data()->label();
}
void QCPColorScale::mouseMoveEvent (QMouseEvent * event) [protected], [virtual]
This event is called, if the mouse is moved inside the outer rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 15504 of file qcustomplot.cpp.
References mAxisRect.
                                                     {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  mAxisRect.data()->mouseMoveEvent(event);
}
void QCPColorScale::mousePressEvent (QMouseEvent * event) [protected], [virtual]
This event is called, if the mouse was pressed while being inside the outer rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 15495 of file qcustomplot.cpp.
References mAxisRect.
                                                      {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  mAxisRect.data()->mousePressEvent(event);
}
void QCPColorScale::mouseReleaseEvent (QMouseEvent * event) [protected], [virtual]
This event is called, if the mouse was previously pressed inside the outer rect of this layout element and is now released.
Reimplemented from QCPLayoutElement.
Definition at line 15513 of file qcustomplot.cpp.
References mAxisRect.
                                                        {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  mAxisRect.data()->mouseReleaseEvent(event);
}
bool QCPColorScale::rangeDrag () const
Definition at line 15160 of file qcustomplot.cpp.
References mAxisRect, mType, and QCPAxis::orientation().
                                    {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return false;
  }
  return mAxisRect.data()->rangeDrag().testFlag(QCPAxis::orientation(
      mType)) &&
         mAxisRect.data()->rangeDragAxis(QCPAxis::orientation(
      mType)) &&
         mAxisRect.data()
                 ->rangeDragAxis(QCPAxis::orientation(mType))
                 ->orientation() == QCPAxis::orientation(
      mType);
}
bool QCPColorScale::rangeZoom () const
Definition at line 15174 of file qcustomplot.cpp.
References mAxisRect, mType, and QCPAxis::orientation().
                                    {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return false;
  }
  return mAxisRect.data()->rangeZoom().testFlag(QCPAxis::orientation(
      mType)) &&
         mAxisRect.data()->rangeZoomAxis(QCPAxis::orientation(
      mType)) &&
         mAxisRect.data()
                 ->rangeZoomAxis(QCPAxis::orientation(mType))
                 ->orientation() == QCPAxis::orientation(
      mType);
}
void QCPColorScale::rescaleDataRange (bool onlyVisibleMaps)
Changes the data range such that all color maps associated with this color scale are fully mapped to the gradient in the data dimension.
See also
setDataRange
Definition at line 15390 of file qcustomplot.cpp.
References colorMaps(), QCPRange::expand(), i, QCPRange::lower, mDataRange, mDataScaleType, setDataRange(), QCPRange::size(), QCPAxis::stLinear, QCPAxis::stLogarithmic, QCPRange::upper, and QCPRange::validRange().
                                                         {
  QList<QCPColorMap *> maps = colorMaps();
  QCPRange newRange;
  bool haveRange = false;
  int sign = 0; // TODO: should change this to QCPAbstractPlottable::SignDomain
                // later (currently is protected, maybe move to QCP namespace)
  if (mDataScaleType == QCPAxis::stLogarithmic)
    sign = (mDataRange.upper < 0 ? -1 : 1);
  for (int i = 0; i < maps.size(); ++i) {
    if (!maps.at(i)->realVisibility() && onlyVisibleMaps)
      continue;
    QCPRange mapRange;
    if (maps.at(i)->colorScale() == this) {
      bool currentFoundRange = true;
      mapRange = maps.at(i)->data()->dataBounds();
      if (sign == 1) {
        if (mapRange.lower <= 0 && mapRange.upper > 0)
          mapRange.lower = mapRange.upper * 1e-3;
        else if (mapRange.lower <= 0 && mapRange.upper <= 0)
          currentFoundRange = false;
      } else if (sign == -1) {
        if (mapRange.upper >= 0 && mapRange.lower < 0)
          mapRange.upper = mapRange.lower * 1e-3;
        else if (mapRange.upper >= 0 && mapRange.lower >= 0)
          currentFoundRange = false;
      }
      if (currentFoundRange) {
        if (!haveRange)
          newRange = mapRange;
        else
          newRange.expand(mapRange);
        haveRange = true;
      }
    }
  }
  if (haveRange) {
    if (!QCPRange::validRange(newRange)) // likely due to range being zero
                                         // (plottable has only constant data in
                                         // this dimension), shift current range
                                         // to at least center the data
    {
      double center = (newRange.lower + newRange.upper) *
                      0.5; // upper and lower should be equal anyway, but just
                           // to make sure, incase validRange returned false for
                           // other reason
      if (mDataScaleType == QCPAxis::stLinear) {
        newRange.lower = center - mDataRange.size() / 2.0;
        newRange.upper = center + mDataRange.size() / 2.0;
      } else // mScaleType == stLogarithmic
      {
        newRange.lower = center / qSqrt(mDataRange.upper /
      mDataRange.lower);
        newRange.upper = center * qSqrt(mDataRange.upper /
      mDataRange.lower);
      }
    }
    setDataRange(newRange);
  }
}
void QCPColorScale::setBarWidth (int width)
Sets the width (or height, for horizontal color scales) the bar where the gradient is displayed will have.
Definition at line 15330 of file qcustomplot.cpp.
References mBarWidth.
{ mBarWidth = width; }
void QCPColorScale::setDataRange (const QCPRange & dataRange)
Sets the range spanned by the color gradient and that is shown by the axis in the color scale.
It is equivalent to calling QCPColorMap::setDataRange on any of the connected color maps. It is also equivalent to directly accessing the axis and setting its range with QCPAxis::setRange.
See also
setDataScaleType, setGradient, rescaleDataRange
Definition at line 15260 of file qcustomplot.cpp.
References dataRange(), dataRangeChanged(), QCPRange::lower, mColorAxis, mDataRange, and QCPRange::upper.
Referenced by QCPColorScale(), rescaleDataRange(), setDataScaleType(), and setType().
                                                          {
  if (mDataRange.lower != dataRange.lower ||
      mDataRange.upper != dataRange.upper) {
    mDataRange = dataRange;
    if (mColorAxis)
      mColorAxis.data()->setRange(mDataRange);
    emit dataRangeChanged(mDataRange);
  }
}
void QCPColorScale::setDataScaleType (QCPAxis::ScaleType scaleType)
Sets the scale type of the color scale, i.e. whether values are linearly associated with colors or logarithmically.
It is equivalent to calling QCPColorMap::setDataScaleType on any of the connected color maps. It is also equivalent to directly accessing the axis and setting its scale type with QCPAxis::setScaleType.
See also
setDataRange, setGradient
Definition at line 15283 of file qcustomplot.cpp.
References dataScaleTypeChanged(), mColorAxis, mDataRange, mDataScaleType, QCPRange::sanitizedForLogScale(), setDataRange(), and QCPAxis::stLogarithmic.
Referenced by setType().
                                                               {
  if (mDataScaleType != scaleType) {
    mDataScaleType = scaleType;
    if (mColorAxis)
      mColorAxis.data()->setScaleType(mDataScaleType);
    if (mDataScaleType == QCPAxis::stLogarithmic)
      setDataRange(mDataRange.sanitizedForLogScale());
    emit dataScaleTypeChanged(mDataScaleType);
  }
}
void QCPColorScale::setGradient (const QCPColorGradient & gradient)
Sets the color gradient that will be used to represent data values.
It is equivalent to calling QCPColorMap::setGradient on any of the connected color maps.
See also
setDataRange, setDataScaleType
Definition at line 15302 of file qcustomplot.cpp.
References gradient(), gradientChanged(), mAxisRect, and mGradient.
                                                                {
  if (mGradient != gradient) {
    mGradient = gradient;
    if (mAxisRect)
      mAxisRect.data()->mGradientImageInvalidated = true;
    emit gradientChanged(mGradient);
  }
}
void QCPColorScale::setLabel (const QString & str)
Sets the axis label of the color scale. This is equivalent to calling QCPAxis::setLabel on the internal axis.
Definition at line 15316 of file qcustomplot.cpp.
References mColorAxis.
                                               {
  if (!mColorAxis) {
    qDebug() << Q_FUNC_INFO << "internal color axis undefined";
    return;
  }
  mColorAxis.data()->setLabel(str);
}
void QCPColorScale::setRangeDrag (bool enabled)
Sets whether the user can drag the data range (setDataRange).
Note that QCP::iRangeDrag must be in the QCustomPlot's interactions (QCustomPlot::setInteractions) to allow range dragging.
Definition at line 15338 of file qcustomplot.cpp.
References mAxisRect, mType, and QCPAxis::orientation().
                                             {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  if (enabled)
    mAxisRect.data()->setRangeDrag(QCPAxis::orientation(
      mType));
  else
    mAxisRect.data()->setRangeDrag(0);
}
void QCPColorScale::setRangeZoom (bool enabled)
Sets whether the user can zoom the data range (setDataRange) by scrolling the mouse wheel.
Note that QCP::iRangeZoom must be in the QCustomPlot's interactions (QCustomPlot::setInteractions) to allow range dragging.
Definition at line 15357 of file qcustomplot.cpp.
References mAxisRect, mType, and QCPAxis::orientation().
                                             {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  if (enabled)
    mAxisRect.data()->setRangeZoom(QCPAxis::orientation(
      mType));
  else
    mAxisRect.data()->setRangeZoom(0);
}
void QCPColorScale::setType (QCPAxis::AxisType type)
Sets at which side of the color scale the axis is placed, and thus also its orientation.
Note that after setting type to a different value, the axis returned by axis() will be a different one. The new axis will adopt the following properties from the previous axis: The range, scale type, log base and label.
Definition at line 15197 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, mAxisRect, mColorAxis, mType, QCPAxis::orientation(), setDataRange(), setDataScaleType(), and type().
Referenced by QCPColorScale().
                                                {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  if (mType != type) {
    mType = type;
    QCPRange rangeTransfer(0, 6);
    double logBaseTransfer = 10;
    QString labelTransfer;
    // revert some settings on old axis:
    if (mColorAxis) {
      rangeTransfer = mColorAxis.data()->range();
      labelTransfer = mColorAxis.data()->label();
      logBaseTransfer = mColorAxis.data()->scaleLogBase();
      mColorAxis.data()->setLabel(QString());
      disconnect(mColorAxis.data(), SIGNAL(rangeChanged(QCPRange)), this,
                 SLOT(setDataRange(QCPRange)));
      disconnect(mColorAxis.data(),
                 SIGNAL(scaleTypeChanged(QCPAxis::ScaleType)), this,
                 SLOT(setDataScaleType(QCPAxis::ScaleType)));
    }
    QList<QCPAxis::AxisType> allAxisTypes =
        QList<QCPAxis::AxisType>() << QCPAxis::atLeft <<
      QCPAxis::atRight
                                   << QCPAxis::atBottom <<
      QCPAxis::atTop;
    foreach (QCPAxis::AxisType atype, allAxisTypes) {
      mAxisRect.data()->axis(atype)->setTicks(atype == mType);
      mAxisRect.data()->axis(atype)->setTickLabels(atype == mType);
    }
    // set new mColorAxis pointer:
    mColorAxis = mAxisRect.data()->axis(mType);
    // transfer settings to new axis:
    mColorAxis.data()->setRange(rangeTransfer); // transfer range of old axis to
                                                // new one (necessary if axis
                                                // changes from vertical to
                                                // horizontal or vice versa)
    mColorAxis.data()->setLabel(labelTransfer);
    mColorAxis.data()->setScaleLogBase(
        logBaseTransfer); // scaleType is synchronized among axes in realtime
                          // via signals (connected in QCPColorScale ctor), so
                          // we only need to take care of log base here
    connect(mColorAxis.data(), SIGNAL(rangeChanged(QCPRange)), this,
            SLOT(setDataRange(QCPRange)));
    connect(mColorAxis.data(), SIGNAL(scaleTypeChanged(
      QCPAxis::ScaleType)),
            this, SLOT(setDataScaleType(QCPAxis::ScaleType)));
    mAxisRect.data()->setRangeDragAxes(
        QCPAxis::orientation(mType) == Qt::Horizontal ?
      mColorAxis.data() : 0,
        QCPAxis::orientation(mType) == Qt::Vertical ?
      mColorAxis.data() : 0);
  }
}
QCPAxis::AxisType QCPColorScale::type () const [inline]
Definition at line 2750 of file qcustomplot.h.
Referenced by QCPColorScaleAxisRectPrivate::draw(), and setType().
{ return mType; }
void QCPColorScale::update (UpdatePhase phase) [virtual]
Updates the layout element and sub-elements. This function is automatically called before every replot by the parent layout element. It is called multiple times, once for every UpdatePhase. The phases are run through in the order of the enum values. For details about what happens at the different phases, see the documentation of UpdatePhase.
Layout elements that have child elements should call the update method of their child elements, and pass the current phase unchanged.
The default implementation executes the automatic margin mechanism in the upMargins phase. Subclasses should make sure to call the base class implementation.
Reimplemented from QCPLayoutElement.
Definition at line 15449 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atTop, QCPLayoutElement::margins(), mAxisRect, mBarWidth, mType, QCPLayoutElement::rect(), QCPLayoutElement::setMaximumSize(), QCPLayoutElement::setMinimumSize(), QCPLayoutElement::update(), QCPLayoutElement::upLayout, and QCPLayoutElement::upMargins.
                                            {
  QCPLayoutElement::update(phase);
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  mAxisRect.data()->update(phase);
  switch (phase) {
  case upMargins: {
    if (mType == QCPAxis::atBottom || mType ==
      QCPAxis::atTop) {
      setMaximumSize(QWIDGETSIZE_MAX, mBarWidth +
                                          mAxisRect.data()->margins().top() +
                                          mAxisRect.data()->margins().bottom() +
                                          margins().top() + margins().bottom());
      setMinimumSize(0, mBarWidth + mAxisRect.data()->margins().top() +
                            mAxisRect.data()->margins().bottom() +
                            margins().top() + margins().bottom());
    } else {
      setMaximumSize(mBarWidth + mAxisRect.data()->margins().left() +
                         mAxisRect.data()->margins().right() +
                         margins().left() + margins().right(),
                     QWIDGETSIZE_MAX);
      setMinimumSize(mBarWidth + mAxisRect.data()->margins().left() +
                         mAxisRect.data()->margins().right() +
                         margins().left() + margins().right(),
                     0);
    }
    break;
  }
  case upLayout: {
    mAxisRect.data()->setOuterRect(rect());
    break;
  }
  default:
    break;
  }
}
void QCPColorScale::wheelEvent (QWheelEvent * event) [protected], [virtual]
This event is called, if the mouse wheel is scrolled while the cursor is inside the rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 15522 of file qcustomplot.cpp.
References mAxisRect.
                                                 {
  if (!mAxisRect) {
    qDebug() << Q_FUNC_INFO << "internal axis rect was deleted";
    return;
  }
  mAxisRect.data()->wheelEvent(event);
}
Friends And Related Function Documentation
friend class QCPColorScaleAxisRectPrivate [friend]
Definition at line 2804 of file qcustomplot.h.
Member Data Documentation
QPointer<QCPColorScaleAxisRectPrivate> QCPColorScale::mAxisRect [protected]
Definition at line 2790 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), rangeDrag(), rangeZoom(), setGradient(), setRangeDrag(), setRangeZoom(), setType(), update(), wheelEvent(), and ~QCPColorScale().
int QCPColorScale::mBarWidth [protected]
Definition at line 2787 of file qcustomplot.h.
Referenced by setBarWidth(), and update().
QPointer<QCPAxis> QCPColorScale::mColorAxis [protected]
Definition at line 2791 of file qcustomplot.h.
Referenced by QCPColorScaleAxisRectPrivate::draw(), label(), setDataRange(), setDataScaleType(), setLabel(), and setType().
QCPRange QCPColorScale::mDataRange [protected]
Definition at line 2784 of file qcustomplot.h.
Referenced by rescaleDataRange(), setDataRange(), and setDataScaleType().
QCPAxis::ScaleType QCPColorScale::mDataScaleType [protected]
Definition at line 2785 of file qcustomplot.h.
Referenced by rescaleDataRange(), and setDataScaleType().
QCPColorGradient QCPColorScale::mGradient [protected]
Definition at line 2786 of file qcustomplot.h.
Referenced by setGradient(), and QCPColorScaleAxisRectPrivate::updateGradientImage().
QCPAxis::AxisType QCPColorScale::mType [protected]
Definition at line 2783 of file qcustomplot.h.
Referenced by rangeDrag(), rangeZoom(), setRangeDrag(), setRangeZoom(), setType(), update(), and QCPColorScaleAxisRectPrivate::updateGradientImage().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp