SoilAnalyzer::Particle Class Reference
#include <Particle.h>
Public Member Functions
Particle ()
~Particle ()
void Save (std::string &filename)
void Load (std::string &filename)
SoilAnalyzer::AnalysisResults Analyze (SoilMath::NN &nn)
Public Attributes
ParticleAnalysisResults Analysis
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Detailed Description
Definition at line 11 of file Particle.h.
Constructor & Destructor Documentation
SoilAnalyzer::Particle::Particle ()
Definition at line 5 of file Particle.cpp.
    {
    }
SoilAnalyzer::Particle::~Particle ()
Definition at line 10 of file Particle.cpp.
    {
    }
Member Function Documentation
SoilAnalyzer::AnalysisResults SoilAnalyzer::Particle::Analyze (SoilMath::NN & nn)
Definition at line 28 of file Particle.cpp.
References Analysis, SoilAnalyzer::ParticleAnalysisResults::Analyzed, SoilAnalyzer::Soil::BW, ShapeClassification::Category, SoilAnalyzer::Soil::Edge, Vision::ImageProcessing::extractChannel(), FFT_DESCRIPTORS, ShapeClassification::FFT_descriptors, SoilMath::FFT::GetDescriptors(), i, SoilAnalyzer::Soil::LAB, SoilAnalyzer::AnalysisResults::LAB_Stat, MIN_EDGE_PIXELS, n, Predict_struct::OutputNeurons, SoilMath::NN::Predict(), SoilAnalyzer::Soil::RGB, SoilAnalyzer::AnalysisResults::RGB_Stat, SoilAnalyzer::Soil::RI, SoilAnalyzer::AnalysisResults::RI_Stat, SoilAnalyzer::ParticleAnalysisResults::Shape, and SoilAnalyzer::ParticleAnalysisResults::SmallParticle.
    {
        if (Analysis.Analyzed) { return Analysis; }
        // Calc the LAB stats
        std::vector<cv::Mat> lab = Vision::ImageProcessing::extractChannel
      (LAB);
        for_each(lab.begin(), lab.end(), [&](cv::Mat &M)
        {
            Analysis.LAB_Stat.push_back(floatStat_t((float *)
      M.data, M.rows, M.cols));
        });
        // Calc the RGB stats
        std::vector<cv::Mat> rgb = Vision::ImageProcessing::extractChannel
      (RGB);
        for_each(lab.begin(), lab.end(), [&](cv::Mat &M)
        {
            Analysis.RGB_Stat.push_back(ucharStat_t((
      uchar *)M.data, M.rows, M.cols));
        });
        // Calc the Redness Index stats
        Analysis.RI_Stat = floatStat_t((float *)RI.data,
      RI.rows, RI.cols);
        // Calc the area
        for_each(BW.data, BW.data + (BW.rows * BW.cols), [&](uchar P) {Analysis.Area += P; });
        // Calc the edge area
        uint32_t edgeArea = 0;
        for_each(Edge.data, Edge.data + (Edge.rows * Edge.cols), [&](
      uchar P) {edgeArea += P; });
        if (edgeArea >= MIN_EDGE_PIXELS) { Analysis.
      SmallParticle = false; }
        else { Analysis.SmallParticle = true; }
        // Determine the shape Classifiation, but only for pixels that are big enough
        if (!Analysis.SmallParticle)
        {
            // Calculate the FFT Descriptors
            SoilMath::FFT fft;
            Analysis.Shape.FFT_descriptors = fft.
      GetDescriptors(Edge);
            if (Analysis.Shape.FFT_descriptors.size() >=
      FFT_DESCRIPTORS)
            {
                Analysis.Shape.FFT_descriptors.erase(
      Analysis.Shape.FFT_descriptors.begin() +
      FFT_DESCRIPTORS, Analysis.Shape.FFT_descriptors.end());
            }
            else
            {
                while (Analysis.Shape.FFT_descriptors.size() <
      FFT_DESCRIPTORS)
                {
                    Analysis.Shape.FFT_descriptors.push_back(
      Complex_t(0, 0));
                }
            }
            Predict_t sp = nn.Predict(Analysis.Shape.
      FFT_descriptors);
            uchar i = 0;
            float maxValue = 0.0;
            for_each(sp.OutputNeurons.begin(), sp.OutputNeurons.end(), [&](float
      &n)
            {
                if (n > maxValue)
                {
                    Analysis.Shape.Category = i;
                    maxValue = n;
                }
                i++;
            });
        }
        Analysis.Analyzed = true;
        return Analysis;
    }
void SoilAnalyzer::Particle::Load (std::string & filename)
Definition at line 21 of file Particle.cpp.
    {
        std::ifstream ifs(filename.c_str());
        boost::archive::binary_iarchive ia(ifs);
        ia >> BOOST_SERIALIZATION_NVP(*this);
    }
void SoilAnalyzer::Particle::Save (std::string & filename)
Definition at line 14 of file Particle.cpp.
    {
        std::ofstream ofs(filename.c_str());
        boost::archive::binary_oarchive oa(ofs);
        oa << BOOST_SERIALIZATION_NVP(*this);
    }
template<class Archive > void SoilAnalyzer::Particle::serialize (Archive & ar, const unsigned int version) [inline], [private]
Definition at line 27 of file Particle.h.
References Analysis.
        {
            ar & BOOST_SERIALIZATION_BASE_OBJECT_NVP(Soil);
            ar & Analysis;
        }
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 25 of file Particle.h.
Member Data Documentation
ParticleAnalysisResults SoilAnalyzer::Particle::Analysis
Definition at line 21 of file Particle.h.
Referenced by Analyze(), and serialize().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/Soil/Particle.h
/home/peer23peer/VisionSoilAnalyzer/src/Soil/Particle.cpp