QParticleDisplay Class Reference
#include <qparticledisplay.h>
Public Slots
void setSelectedParticle (int newValue)
Signals
void particleChanged (int newValue)
void shapeClassificationChanged (int newValue)
void particleDeleted ()
Public Member Functions
QParticleDisplay (QWidget *parent=0)
~QParticleDisplay ()
void SetSample (SoilAnalyzer::Sample *sample)
void wheelEvent (QWheelEvent *event)
void next ()
Public Attributes
SoilAnalyzer::Particle * SelectedParticle
Private Slots
void on_selectedParticleChangedWidget (int value)
void on_selectedParticleChangedSlider (int value)
void on_pushButton_delete_clicked ()
Private Member Functions
QImage ConvertParticleToQImage (SoilAnalyzer::Particle *particle)
Private Attributes
Ui::QParticleDisplay * ui
SoilAnalyzer::Sample * Sample
QVector< QImage > images
bool dontDoIt = false
Detailed Description
Definition at line 21 of file qparticledisplay.h.
Constructor & Destructor Documentation
QParticleDisplay::QParticleDisplay (QWidget * parent = 0) [explicit]
Definition at line 11 of file qparticledisplay.cpp.
References on_selectedParticleChangedSlider(), on_selectedParticleChangedWidget(), and ui.
QParticleDisplay::~QParticleDisplay ()
Definition at line 22 of file qparticledisplay.cpp.
References ui.
Member Function Documentation
QImage QParticleDisplay::ConvertParticleToQImage (SoilAnalyzer::Particle * particle) [private]
Definition at line 50 of file qparticledisplay.cpp.
References SoilAnalyzer::Particle::BW, and SoilAnalyzer::Particle::RGB.
Referenced by SetSample().
void QParticleDisplay::next ()
Definition at line 150 of file qparticledisplay.cpp.
References on_selectedParticleChangedWidget(), and ui.
void QParticleDisplay::on_pushButton_delete_clicked () [private], [slot]
Definition at line 96 of file qparticledisplay.cpp.
References SoilAnalyzer::Sample::ChangesSinceLastSave, SoilAnalyzer::Sample::ColorChange, SoilAnalyzer::Sample::ParticleChangedStateAngularity, SoilAnalyzer::Sample::ParticleChangedStatePSD, SoilAnalyzer::Sample::ParticleChangedStateRoundness, particleDeleted(), SoilAnalyzer::Sample::ParticlePopulation, Sample, SelectedParticle, and ui.
void QParticleDisplay::on_selectedParticleChangedSlider (int value) [private], [slot]
Definition at line 124 of file qparticledisplay.cpp.
References Predict_struct::Category, SoilAnalyzer::Particle::Classification, dontDoIt, SoilAnalyzer::Particle::GetSiDiameter(), particleChanged(), SoilAnalyzer::Sample::ParticlePopulation, Sample, SelectedParticle, shapeClassificationChanged(), and ui.
Referenced by QParticleDisplay(), and SetSample().
void QParticleDisplay::on_selectedParticleChangedWidget (int value) [private], [slot]
Definition at line 110 of file qparticledisplay.cpp.
References Predict_struct::Category, SoilAnalyzer::Particle::Classification, dontDoIt, SoilAnalyzer::Particle::GetSiDiameter(), particleChanged(), SoilAnalyzer::Sample::ParticlePopulation, Sample, SelectedParticle, shapeClassificationChanged(), and ui.
Referenced by next(), QParticleDisplay(), and wheelEvent().
void QParticleDisplay::particleChanged (int newValue) [signal]
Referenced by on_selectedParticleChangedSlider(), and on_selectedParticleChangedWidget().
void QParticleDisplay::particleDeleted () [signal]
Referenced by on_pushButton_delete_clicked().
void QParticleDisplay::SetSample (SoilAnalyzer::Sample * sample)
Definition at line 35 of file qparticledisplay.cpp.
References ConvertParticleToQImage(), images, on_selectedParticleChangedSlider(), SoilAnalyzer::Sample::ParticlePopulation, Sample, SelectedParticle, and ui.
void QParticleDisplay::setSelectedParticle (int newValue) [slot]
Definition at line 30 of file qparticledisplay.cpp.
References ui.
void QParticleDisplay::shapeClassificationChanged (int newValue) [signal]
Referenced by on_selectedParticleChangedSlider(), and on_selectedParticleChangedWidget().
void QParticleDisplay::wheelEvent (QWheelEvent * event)
Definition at line 138 of file qparticledisplay.cpp.
References on_selectedParticleChangedWidget(), and ui.
Member Data Documentation
bool QParticleDisplay::dontDoIt = false [private]
Definition at line 51 of file qparticledisplay.h.
Referenced by on_selectedParticleChangedSlider(), and on_selectedParticleChangedWidget().
QVector<QImage> QParticleDisplay::images [private]
Definition at line 49 of file qparticledisplay.h.
Referenced by SetSample().
SoilAnalyzer::Sample* QParticleDisplay::Sample [private]
Definition at line 48 of file qparticledisplay.h.
Referenced by on_pushButton_delete_clicked(), on_selectedParticleChangedSlider(), on_selectedParticleChangedWidget(), and SetSample().
SoilAnalyzer::Particle* QParticleDisplay::SelectedParticle
Definition at line 29 of file qparticledisplay.h.
Referenced by on_pushButton_delete_clicked(), on_selectedParticleChangedSlider(), on_selectedParticleChangedWidget(), and SetSample().
Ui::QParticleDisplay* QParticleDisplay::ui [private]
Definition at line 47 of file qparticledisplay.h.
Referenced by next(), on_pushButton_delete_clicked(), on_selectedParticleChangedSlider(), on_selectedParticleChangedWidget(), QParticleDisplay(), SetSample(), setSelectedParticle(), wheelEvent(), and ~QParticleDisplay().
The documentation for this class was generated from the following files:
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/QParticleDisplay/qparticledisplay.h
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/QParticleDisplay/qparticledisplay.cpp