QCPColorMapData Class Reference
Holds the two-dimensional data of a QCPColorMap plottable.
#include <qcustomplot.h>
Public Member Functions
QCPColorMapData (int keySize, int valueSize, const QCPRange &keyRange, const QCPRange &valueRange)
~QCPColorMapData ()
QCPColorMapData (const QCPColorMapData &other)
QCPColorMapData & operator= (const QCPColorMapData &other)
int keySize () const
int valueSize () const
QCPRange keyRange () const
QCPRange valueRange () const
QCPRange dataBounds () const
double data (double key, double value)
double cell (int keyIndex, int valueIndex)
void setSize (int keySize, int valueSize)
void setKeySize (int keySize)
void setValueSize (int valueSize)
void setRange (const QCPRange &keyRange, const QCPRange &valueRange)
void setKeyRange (const QCPRange &keyRange)
void setValueRange (const QCPRange &valueRange)
void setData (double key, double value, double z)
void setCell (int keyIndex, int valueIndex, double z)
void recalculateDataBounds ()
void clear ()
void fill (double z)
bool isEmpty () const
void coordToCell (double key, double value, int *keyIndex, int *valueIndex) const
void cellToCoord (int keyIndex, int valueIndex, double *key, double *value) const
Protected Attributes
int mKeySize
int mValueSize
QCPRange mKeyRange
QCPRange mValueRange
bool mIsEmpty
double * mData
QCPRange mDataBounds
bool mDataModified
Friends
class QCPColorMap
Detailed Description
Holds the two-dimensional data of a QCPColorMap plottable.
This class is a data storage for QCPColorMap. It holds a two-dimensional array, which QCPColorMap then displays as a 2D image in the plot, where the array values are represented by a color, depending on the value.
The size of the array can be controlled via setSize (or setKeySize, setValueSize). Which plot coordinates these cells correspond to can be configured with setRange (or setKeyRange, setValueRange).
The data cells can be accessed in two ways: They can be directly addressed by an integer index with setCell. This is the fastest method. Alternatively, they can be addressed by their plot coordinate with setData. plot coordinate to cell index transformations and vice versa are provided by the functions coordToCell and cellToCoord.
This class also buffers the minimum and maximum values that are in the data set, to provide QCPColorMap::rescaleDataRange with the necessary information quickly. Setting a cell to a value that is greater than the current maximum increases this maximum to the new value. However, setting the cell that currently holds the maximum value to a smaller value doesn't decrease the maximum again, because finding the true new maximum would require going through the entire data array, which might be time consuming. The same holds for the data minimum. This functionality is given by recalculateDataBounds, such that you can decide when it is sensible to find the true current minimum and maximum. The method QCPColorMap::rescaleDataRange offers a convenience parameter recalculateDataBounds which may be set to true to automatically call recalculateDataBounds internally.
Definition at line 3431 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPColorMapData::QCPColorMapData (int keySize, int valueSize, const QCPRange & keyRange, const QCPRange & valueRange)
Constructs a new QCPColorMapData instance. The instance has keySize cells in the key direction and valueSize cells in the value direction. These cells will be displayed by the QCPColorMap at the coordinates keyRange and valueRange.
See also
setSize, setKeySize, setValueSize, setRange, setKeyRange, setValueRange
Definition at line 21834 of file qcustomplot.cpp.
References fill(), and setSize().
    : mKeySize(0), mValueSize(0), mKeyRange(keyRange),
      mValueRange(valueRange),
      mIsEmpty(true), mData(0), mDataModified(true) {
  setSize(keySize, valueSize);
  fill(0);
}
QCPColorMapData::~QCPColorMapData ()
Definition at line 21843 of file qcustomplot.cpp.
References mData.
                                  {
  if (mData)
    delete[] mData;
}
QCPColorMapData::QCPColorMapData (const QCPColorMapData & other)
Constructs a new QCPColorMapData instance copying the data and range of other.
Definition at line 21852 of file qcustomplot.cpp.
    : mKeySize(0), mValueSize(0), mIsEmpty(true),
      mData(0),
      mDataModified(true) {
  *this = other;
}
Member Function Documentation
double QCPColorMapData::cell (int keyIndex, int valueIndex)
Definition at line 21892 of file qcustomplot.cpp.
References mData, mKeySize, and mValueSize.
                                                         {
  if (keyIndex >= 0 && keyIndex < mKeySize && valueIndex >= 0 &&
      valueIndex < mValueSize)
    return mData[valueIndex * mKeySize + keyIndex];
  else
    return 0;
}
void QCPColorMapData::cellToCoord (int keyIndex, int valueIndex, double * key, double * value) const
Transforms cell indices given by keyIndex and valueIndex to cell indices of this QCPColorMapData instance. The resulting coordinates are returned via the output parameters key and value.
If you are only interested in a key or value coordinate, you may pass 0 as key or value.
Note
The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::cellToCoord method as it uses a linear transformation to determine the cell index.
See also
coordToCell, QCPAxis::pixelToCoord
Definition at line 22203 of file qcustomplot.cpp.
References QCPRange::lower, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
                                                       {
  if (key)
    *key = keyIndex / (double)(mKeySize - 1) *
               (mKeyRange.upper - mKeyRange.lower) +
           mKeyRange.lower;
  if (value)
    *value = valueIndex / (double)(mValueSize - 1) *
                 (mValueRange.upper - mValueRange.
      lower) +
             mValueRange.lower;
}
void QCPColorMapData::clear ()
Frees the internal data memory.
This is equivalent to calling setSize(0, 0).
Definition at line 22132 of file qcustomplot.cpp.
References setSize().
Referenced by QCPColorMap::clearData().
{ setSize(0, 0); }
void QCPColorMapData::coordToCell (double key, double value, int * keyIndex, int * valueIndex) const
Transforms plot coordinates given by key and value to cell indices of this QCPColorMapData instance. The resulting cell indices are returned via the output parameters keyIndex and valueIndex.
The retrieved key/value cell indices can then be used for example with setCell.
If you are only interested in a key or value index, you may pass 0 as valueIndex or keyIndex.
Note
The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::coordToCell method as it uses a linear transformation to determine the cell index.
See also
cellToCoord, QCPAxis::coordToPixel
Definition at line 22169 of file qcustomplot.cpp.
References QCPRange::lower, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
                                                         {
  if (keyIndex)
    *keyIndex = (key - mKeyRange.lower) / (mKeyRange.
      upper - mKeyRange.lower) *
                    (mKeySize - 1) +
                0.5;
  if (valueIndex)
    *valueIndex = (value - mValueRange.lower) /
                      (mValueRange.upper - mValueRange.
      lower) *
                      (mValueSize - 1) +
                  0.5;
}
double QCPColorMapData::data (double key, double value)
Definition at line 21876 of file qcustomplot.cpp.
References QCPRange::lower, mData, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
                                                     {
  int keyCell = (key - mKeyRange.lower) / (mKeyRange.
      upper - mKeyRange.lower) *
                    (mKeySize - 1) +
                0.5;
  int valueCell = (value - mValueRange.lower) /
                      (mValueRange.upper - mValueRange.
      lower) *
                      (mValueSize - 1) +
                  0.5;
  if (keyCell >= 0 && keyCell < mKeySize && valueCell >= 0 &&
      valueCell < mValueSize)
    return mData[valueCell * mKeySize + keyCell];
  else
    return 0;
}
QCPRange QCPColorMapData::dataBounds () const [inline]
Definition at line 3444 of file qcustomplot.h.
Referenced by QCPColorMap::rescaleDataRange().
{ return mDataBounds; }
void QCPColorMapData::fill (double z)
Sets all cells to the value z.
Definition at line 22137 of file qcustomplot.cpp.
References i, mData, mDataBounds, mDataModified, mKeySize, and mValueSize.
Referenced by QCPColorMapData(), and setSize().
                                   {
  const int dataCount = mValueSize * mKeySize;
  for (int i = 0; i < dataCount; ++i)
    mData[i] = z;
  mDataBounds = QCPRange(z, z);
  mDataModified = true;
}
bool QCPColorMapData::isEmpty () const [inline]
Returns whether this instance carries no data. This is equivalent to having a size where at least one of the dimensions is 0 (see setSize).
Definition at line 3462 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), QCPColorMap::updateLegendIcon(), and QCPColorMap::updateMapImage().
{ return mIsEmpty; }
QCPRange QCPColorMapData::keyRange () const [inline]
Definition at line 3442 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), QCPColorMap::getKeyRange(), operator=(), QCPColorMap::selectTest(), and setKeyRange().
{ return mKeyRange; }
int QCPColorMapData::keySize () const [inline]
Definition at line 3440 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), operator=(), setSize(), and QCPColorMap::updateMapImage().
{ return mKeySize; }
QCPColorMapData & QCPColorMapData::operator= (const QCPColorMapData & other)
Overwrites this color map data instance with the data stored in other.
Definition at line 21861 of file qcustomplot.cpp.
References keyRange(), keySize(), mData, mDataBounds, mDataModified, mIsEmpty, setRange(), setSize(), valueRange(), and valueSize().
                                                                        {
  if (&other != this) {
    const int keySize = other.keySize();
    const int valueSize = other.valueSize();
    setSize(keySize, valueSize);
    setRange(other.keyRange(), other.valueRange());
    if (!mIsEmpty)
      memcpy(mData, other.mData, sizeof(mData[0]) * keySize * valueSize);
    mDataBounds = other.mDataBounds;
    mDataModified = true;
  }
  return *this;
}
void QCPColorMapData::recalculateDataBounds ()
Goes through the data and updates the buffered minimum and maximum data values.
Calling this method is only advised if you are about to call QCPColorMap::rescaleDataRange and can not guarantee that the cells holding the maximum or minimum data haven't been overwritten with a smaller or larger value respectively, since the buffered maximum/minimum values have been updated the last time. Why this is the case is explained in the class description (QCPColorMapData).
Note that the method QCPColorMap::rescaleDataRange provides a parameter recalculateDataBounds for convenience. Setting this to true will call this method for you, before doing the rescale.
Definition at line 22111 of file qcustomplot.cpp.
References i, QCPRange::lower, mData, mDataBounds, mKeySize, mValueSize, and QCPRange::upper.
Referenced by QCPColorMap::rescaleDataRange().
                                            {
  if (mKeySize > 0 && mValueSize > 0) {
    double minHeight = mData[0];
    double maxHeight = mData[0];
    const int dataCount = mValueSize * mKeySize;
    for (int i = 0; i < dataCount; ++i) {
      if (mData[i] > maxHeight)
        maxHeight = mData[i];
      if (mData[i] < minHeight)
        minHeight = mData[i];
    }
    mDataBounds.lower = minHeight;
    mDataBounds.upper = maxHeight;
  }
}
void QCPColorMapData::setCell (int keyIndex, int valueIndex, double z)
Sets the data of the cell with indices keyIndex and valueIndex to z. The indices enumerate the cells starting from zero, up to the map's size-1 in the respective dimension (see setSize).
In the standard plot configuration (horizontal key axis and vertical value axis, both not range-reversed), the cell with indices (0, 0) is in the bottom left corner and the cell with indices (keySize-1, valueSize-1) is in the top right corner of the color map.
See also
setData, setSize
Definition at line 22079 of file qcustomplot.cpp.
References QCPRange::lower, mData, mDataBounds, mDataModified, mKeySize, mValueSize, and QCPRange::upper.
                                                                    {
  if (keyIndex >= 0 && keyIndex < mKeySize && valueIndex >= 0 &&
      valueIndex < mValueSize) {
    mData[valueIndex * mKeySize + keyIndex] = z;
    if (z < mDataBounds.lower)
      mDataBounds.lower = z;
    if (z > mDataBounds.upper)
      mDataBounds.upper = z;
    mDataModified = true;
  }
}
void QCPColorMapData::setData (double key, double value, double z)
Sets the data of the cell, which lies at the plot coordinates given by key and value, to z.
Note
The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::setData method as it uses a linear transformation to determine the cell index. Rather directly access the cell index with QCPColorMapData::setCell.
See also
setCell, setRange
Definition at line 22045 of file qcustomplot.cpp.
References QCPRange::lower, mData, mDataBounds, mDataModified, mKeyRange, mKeySize, mValueRange, mValueSize, and QCPRange::upper.
                                                                {
  int keyCell = (key - mKeyRange.lower) / (mKeyRange.
      upper - mKeyRange.lower) *
                    (mKeySize - 1) +
                0.5;
  int valueCell = (value - mValueRange.lower) /
                      (mValueRange.upper - mValueRange.
      lower) *
                      (mValueSize - 1) +
                  0.5;
  if (keyCell >= 0 && keyCell < mKeySize && valueCell >= 0 &&
      valueCell < mValueSize) {
    mData[valueCell * mKeySize + keyCell] = z;
    if (z < mDataBounds.lower)
      mDataBounds.lower = z;
    if (z > mDataBounds.upper)
      mDataBounds.upper = z;
    mDataModified = true;
  }
}
void QCPColorMapData::setKeyRange (const QCPRange & keyRange)
Sets the coordinate range the data shall be distributed over in the key dimension. Together with the value range, This defines the rectangular area covered by the color map in plot coordinates.
The outer cells will be centered on the range boundaries given to this function. For example, if the key size (setKeySize) is 3 and keyRange is set to QCPRange(2, 3) there will be cells centered on the key coordinates 2, 2.5 and 3.
See also
setRange, setValueRange, setSize
Definition at line 22007 of file qcustomplot.cpp.
References keyRange(), and mKeyRange.
Referenced by setRange().
                                                          {
  mKeyRange = keyRange;
}
void QCPColorMapData::setKeySize (int keySize)
Resizes the data array to have keySize cells in the key dimension.
The current data is discarded and the map cells are set to 0, unless the map had already the requested size.
Setting keySize to zero frees the internal data array and isEmpty returns true.
See also
setKeyRange, setSize, setValueSize
Definition at line 21956 of file qcustomplot.cpp.
References mValueSize, and setSize().
{ setSize(keySize, mValueSize); }
void QCPColorMapData::setRange (const QCPRange & keyRange, const QCPRange & valueRange)
Sets the coordinate ranges the data shall be distributed over. This defines the rectangular area covered by the color map in plot coordinates.
The outer cells will be centered on the range boundaries given to this function. For example, if the key size (setKeySize) is 3 and keyRange is set to QCPRange(2, 3) there will be cells centered on the key coordinates 2, 2.5 and 3.
See also
setSize
Definition at line 21987 of file qcustomplot.cpp.
References setKeyRange(), and setValueRange().
Referenced by operator=().
                                                           {
  setKeyRange(keyRange);
  setValueRange(valueRange);
}
void QCPColorMapData::setSize (int keySize, int valueSize)
Resizes the data array to have keySize cells in the key dimension and valueSize cells in the value dimension.
The current data is discarded and the map cells are set to 0, unless the map had already the requested size.
Setting at least one of keySize or valueSize to zero frees the internal data array and isEmpty returns true.
See also
setRange, setKeySize, setValueSize
Definition at line 21915 of file qcustomplot.cpp.
References fill(), keySize(), mData, mDataModified, mIsEmpty, mKeySize, mValueSize, and valueSize().
Referenced by clear(), operator=(), QCPColorMapData(), setKeySize(), and setValueSize().
                                                        {
  if (keySize != mKeySize || valueSize != mValueSize) {
    mKeySize = keySize;
    mValueSize = valueSize;
    if (mData)
      delete[] mData;
    mIsEmpty = mKeySize == 0 || mValueSize == 0;
    if (!mIsEmpty) {
#ifdef __EXCEPTIONS
      try { // 2D arrays get memory intensive fast. So if the allocation fails,
            // at least output debug message
#endif
        mData = new double[mKeySize * mValueSize];
#ifdef __EXCEPTIONS
      } catch (...) {
        mData = 0;
      }
#endif
      if (mData)
        fill(0);
      else
        qDebug() << Q_FUNC_INFO << "out of memory for data dimensions "
                 << mKeySize << "*" << mValueSize;
    } else
      mData = 0;
    mDataModified = true;
  }
}
void QCPColorMapData::setValueRange (const QCPRange & valueRange)
Sets the coordinate range the data shall be distributed over in the value dimension. Together with the key range, This defines the rectangular area covered by the color map in plot coordinates.
The outer cells will be centered on the range boundaries given to this function. For example, if the value size (setValueSize) is 3 and valueRange is set to QCPRange(2, 3) there will be cells centered on the value coordinates 2, 2.5 and 3.
See also
setRange, setKeyRange, setSize
Definition at line 22025 of file qcustomplot.cpp.
References mValueRange, and valueRange().
Referenced by setRange().
                                                              {
  mValueRange = valueRange;
}
void QCPColorMapData::setValueSize (int valueSize)
Resizes the data array to have valueSize cells in the value dimension.
The current data is discarded and the map cells are set to 0, unless the map had already the requested size.
Setting valueSize to zero frees the internal data array and isEmpty returns true.
See also
setValueRange, setSize, setKeySize
Definition at line 21970 of file qcustomplot.cpp.
References mKeySize, and setSize().
                                                {
  setSize(mKeySize, valueSize);
}
QCPRange QCPColorMapData::valueRange () const [inline]
Definition at line 3443 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), QCPColorMap::getValueRange(), operator=(), QCPColorMap::selectTest(), and setValueRange().
{ return mValueRange; }
int QCPColorMapData::valueSize () const [inline]
Definition at line 3441 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), operator=(), setSize(), and QCPColorMap::updateMapImage().
{ return mValueSize; }
Friends And Related Function Documentation
friend class QCPColorMap [friend]
Definition at line 3478 of file qcustomplot.h.
Member Data Documentation
double* QCPColorMapData::mData [protected]
Definition at line 3474 of file qcustomplot.h.
Referenced by cell(), data(), fill(), operator=(), recalculateDataBounds(), setCell(), setData(), setSize(), QCPColorMap::updateMapImage(), and ~QCPColorMapData().
QCPRange QCPColorMapData::mDataBounds [protected]
Definition at line 3475 of file qcustomplot.h.
Referenced by fill(), operator=(), recalculateDataBounds(), setCell(), and setData().
bool QCPColorMapData::mDataModified [protected]
Definition at line 3476 of file qcustomplot.h.
Referenced by QCPColorMap::draw(), fill(), operator=(), setCell(), setData(), setSize(), and QCPColorMap::updateMapImage().
bool QCPColorMapData::mIsEmpty [protected]
Definition at line 3472 of file qcustomplot.h.
Referenced by operator=(), and setSize().
QCPRange QCPColorMapData::mKeyRange [protected]
Definition at line 3471 of file qcustomplot.h.
Referenced by cellToCoord(), coordToCell(), data(), setData(), and setKeyRange().
int QCPColorMapData::mKeySize [protected]
Definition at line 3470 of file qcustomplot.h.
Referenced by cell(), cellToCoord(), coordToCell(), data(), fill(), recalculateDataBounds(), setCell(), setData(), setSize(), and setValueSize().
QCPRange QCPColorMapData::mValueRange [protected]
Definition at line 3471 of file qcustomplot.h.
Referenced by cellToCoord(), coordToCell(), data(), setData(), and setValueRange().
int QCPColorMapData::mValueSize [protected]
Definition at line 3470 of file qcustomplot.h.
Referenced by cell(), cellToCoord(), coordToCell(), data(), fill(), recalculateDataBounds(), setCell(), setData(), setKeySize(), and setSize().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp