Vision::MorphologicalFilter Class Reference
#include <MorphologicalFilter.h>
Public Types
enum FilterType {
*
OPEN,
CLOSE,
ERODE,
DILATE,
*
NONE
 }
Public Member Functions
MorphologicalFilter ()
MorphologicalFilter (FilterType filtertype)
MorphologicalFilter (const Mat &src, FilterType filtertype=FilterType::NONE)
MorphologicalFilter (const MorphologicalFilter &rhs)
~MorphologicalFilter ()
MorphologicalFilter & operator= (MorphologicalFilter &rhs)
void Dilation (const Mat &mask, bool chain=false)
void Erosion (const Mat &mask, bool chain=false)
void Close (const Mat &mask, bool chain=false)
void Open (const Mat &mask, bool chain=false)
Private Member Functions
void Filter (const Mat &mask, bool chain, uchar startVal, uchar newVal, uchar switchVal)
Additional Inherited Members
Detailed Description
Definition at line 8 of file MorphologicalFilter.h.
Member Enumeration Documentation
enum Vision::MorphologicalFilter::FilterType
Enumerator
OPEN
CLOSE
ERODE
DILATE
NONE
Definition at line 13 of file MorphologicalFilter.h.
        {
            OPEN,
            CLOSE,
            ERODE,
            DILATE,
            NONE
        };
Constructor & Destructor Documentation
Vision::MorphologicalFilter::MorphologicalFilter ()
Definition at line 5 of file MorphologicalFilter.cpp.
{ }
Vision::MorphologicalFilter::MorphologicalFilter (FilterType filtertype)
Definition at line 7 of file MorphologicalFilter.cpp.
References Close(), Dilation(), Erosion(), Open(), and Vision::ImageProcessing::OriginalImg.
    {
        switch (filtertype)
        {
             case FilterType::OPEN:
                  Open(OriginalImg);
                break;
             case FilterType::CLOSE:
                  Close(OriginalImg);
                 break;
             case FilterType::ERODE:
                  Erosion(OriginalImg);
                 break;
             case FilterType::DILATE:
                  Dilation(OriginalImg);
                 break;
            case FilterType::NONE:
                break;
        }
    }
Vision::MorphologicalFilter::MorphologicalFilter (const Mat & src, FilterType filtertype = FilterType::NONE)
Definition at line 28 of file MorphologicalFilter.cpp.
References Close(), Dilation(), Erosion(), Open(), Vision::ImageProcessing::OriginalImg, and Vision::ImageProcessing::ProcessedImg.
    {
        OriginalImg = src;
        ProcessedImg.create(OriginalImg.size(), CV_8UC1);
        switch (filtertype)
        {
             case FilterType::OPEN:
                  Open(OriginalImg);
                break;
             case FilterType::CLOSE:
                  Close(OriginalImg);
                 break;
             case FilterType::ERODE:
                  Erosion(OriginalImg);
                 break;
             case FilterType::DILATE:
                  Dilation(OriginalImg);
                 break;
            case FilterType::NONE:
                break;
        }
    }
Vision::MorphologicalFilter::MorphologicalFilter (const MorphologicalFilter & rhs)
Definition at line 51 of file MorphologicalFilter.cpp.
References Vision::ImageProcessing::OriginalImg, Vision::ImageProcessing::ProcessedImg, and Vision::ImageProcessing::TempImg.
    {
        this->OriginalImg = rhs.OriginalImg;
        this->ProcessedImg = rhs.ProcessedImg;
        this->TempImg = rhs.ProcessedImg;
    }
Vision::MorphologicalFilter::~MorphologicalFilter ()
Definition at line 58 of file MorphologicalFilter.cpp.
{}
Member Function Documentation
void Vision::MorphologicalFilter::Close (const Mat & mask, bool chain = false)
Definition at line 77 of file MorphologicalFilter.cpp.
References Dilation(), and Erosion().
Referenced by BOOST_AUTO_TEST_CASE(), MorphologicalFilter(), and SoilAnalyzer::Sample::PrepImg().
    {
        Dilation(mask, chain);
        Erosion(mask, true);
    }
void Vision::MorphologicalFilter::Dilation (const Mat & mask, bool chain = false)
Definition at line 83 of file MorphologicalFilter.cpp.
References Filter().
Referenced by BOOST_AUTO_TEST_CASE(), Close(), MorphologicalFilter(), Open(), and SoilAnalyzer::Sample::PrepImg().
    {
        Filter(mask, chain, 0, 1, 1);
    }
void Vision::MorphologicalFilter::Erosion (const Mat & mask, bool chain = false)
Definition at line 88 of file MorphologicalFilter.cpp.
References Filter().
Referenced by BOOST_AUTO_TEST_CASE(), Close(), Vision::Segment::GetEdgesEroding(), MorphologicalFilter(), Open(), and SoilAnalyzer::Sample::PrepImg().
    {
        Filter(mask, chain, 1, 0, 0);
    }
void Vision::MorphologicalFilter::Filter (const Mat & mask, bool chain, uchar startVal, uchar newVal, uchar switchVal) [private]
Definition at line 93 of file MorphologicalFilter.cpp.
References c, EMPTY_CHECK, Vision::ImageProcessing::GetNRow(), i, Vision::ImageProcessing::OriginalImg, Vision::ImageProcessing::ProcessedImg, and SHOW_DEBUG_IMG.
Referenced by Dilation(), and Erosion().
    {
        // Exception handling
        CV_Assert(OriginalImg.depth() != sizeof(uchar));
        EMPTY_CHECK(OriginalImg);
        if (mask.cols % 2 == 0 || mask.cols < 3) { throw Exception::WrongKernelSizeException("Wrong
       Kernelsize columns!"); }
        if (mask.rows % 2 == 0 || mask.rows < 3) { throw Exception::WrongKernelSizeException("Wrong
       Kernelsize rows!"); }
        uint32_t hKsizeCol = (mask.cols / 2);
        uint32_t hKsizeRow = (mask.rows / 2);
        // make Pointers
        Mat workOrigImg(ProcessedImg.rows + mask.rows,
      ProcessedImg.cols + mask.cols, CV_8UC1);
        workOrigImg.setTo(0);
        if (chain)
        {
            ProcessedImg.copyTo(workOrigImg(cv::Rect(hKsizeCol, hKsizeRow,
      ProcessedImg.cols, ProcessedImg.rows)));
            //workOrigImg(cv::Rect(hKsizeCol, hKsizeRow, ProcessedImg.cols, ProcessedImg.rows)) =
       ProcessedImg.clone();
        }
        else
        {
            OriginalImg.copyTo(workOrigImg(cv::Rect(hKsizeCol, hKsizeRow,
      ProcessedImg.cols, ProcessedImg.rows)));
            //workOrigImg(cv::Rect(hKsizeCol, hKsizeRow, ProcessedImg.cols, ProcessedImg.rows)) =
       OriginalImg.clone();
        }
        uchar *O = workOrigImg.data;
        Mat workProcImg(ProcessedImg.rows + mask.rows,
      ProcessedImg.cols + mask.cols, CV_8UC1);
        uchar *P = workProcImg.data;
        // Init the relevant data
        uint32_t nData = OriginalImg.cols * OriginalImg.rows;
        uint32_t nWData = workProcImg.cols * workProcImg.rows;
        uint32_t nWStart = (hKsizeRow * workProcImg.cols) + hKsizeRow;
        uint32_t nWEnd = nWData - hKsizeCol - hKsizeRow * workProcImg.cols - 1;
        uchar *nRow = GetNRow(nWData, hKsizeCol, workProcImg.cols, workProcImg.rows);
        int MaskPixel = 0, OPixel = 0;
        workProcImg.setTo(0);
        if (startVal != 0) { workProcImg(cv::Rect(hKsizeCol, hKsizeRow,
      ProcessedImg.cols, ProcessedImg.rows)).setTo(startVal); }
        SHOW_DEBUG_IMG(workOrigImg, uchar, 255, "workOrigImg Filter!", false);
        SHOW_DEBUG_IMG(mask, uchar, 255, "Filter mask", true);
        for (uint32_t i = nWStart; i < nWEnd; i++)
        {
            // Checks if pixel isn't a border pixel and progresses to the new row
            if (nRow[i] == 1) { i += mask.cols; }
            for (uint32_t r = 0; r < mask.rows; r++)
            {
                for (uint32_t c = 0; c < mask.cols; c++)
                {
                    MaskPixel = c + r * mask.cols;
                    OPixel = i - hKsizeCol + c + (r - hKsizeRow) * workProcImg.cols;
                    if (mask.data[MaskPixel] == 1 && O[OPixel] == switchVal)
                    {
                        P[i] = newVal;
                        c = mask.cols;
                        r = mask.rows;
                    }
                }
            }
        }
        delete[] nRow;
        SHOW_DEBUG_IMG(workProcImg, uchar, 255, "workProcImg Filter!", true);
        ProcessedImg = workProcImg(Rect(hKsizeCol, hKsizeRow,
      ProcessedImg.cols, ProcessedImg.rows)).clone();
        SHOW_DEBUG_IMG(ProcessedImg, uchar, 255, "Processed Image Filter!",
      true);
    }
void Vision::MorphologicalFilter::Open (const Mat & mask, bool chain = false)
Definition at line 71 of file MorphologicalFilter.cpp.
References Dilation(), and Erosion().
Referenced by BOOST_AUTO_TEST_CASE(), MorphologicalFilter(), and SoilAnalyzer::Sample::PrepImg().
    {
        Erosion(mask, chain);
        Dilation(mask, true);
    }
MorphologicalFilter & Vision::MorphologicalFilter::operator= (MorphologicalFilter & rhs)
Definition at line 60 of file MorphologicalFilter.cpp.
References Vision::ImageProcessing::OriginalImg, Vision::ImageProcessing::ProcessedImg, and Vision::ImageProcessing::TempImg.
    {
        if (&rhs != this)
        {
            this->OriginalImg = rhs.OriginalImg;
            this->ProcessedImg = rhs.ProcessedImg;
            this->TempImg = rhs.TempImg;
        }
        return *this;
    }
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilVision/MorphologicalFilter.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilVision/MorphologicalFilter.cpp