QCPItemText Class Reference
A text label.
#include <qcustomplot.h>
Public Member Functions
QCPItemText (QCustomPlot *parentPlot)
virtual ~QCPItemText ()
QColor color () const
QColor selectedColor () const
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
QFont font () const
QFont selectedFont () const
QString text () const
Qt::Alignment positionAlignment () const
Qt::Alignment textAlignment () const
double rotation () const
QMargins padding () const
void setColor (const QColor &color)
void setSelectedColor (const QColor &color)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setFont (const QFont &font)
void setSelectedFont (const QFont &font)
void setText (const QString &text)
void setPositionAlignment (Qt::Alignment alignment)
void setTextAlignment (Qt::Alignment alignment)
void setRotation (double degrees)
void setPadding (const QMargins &padding)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Attributes
QCPItemPosition *const position
QCPItemAnchor *const topLeft
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottomRight
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
*
aiTopLeft,
aiTop,
aiTopRight,
aiRight,
*
aiBottomRight,
aiBottom,
aiBottomLeft,
aiLeft
 }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPointF getTextDrawPoint (const QPointF &pos, const QRectF &rect, Qt::Alignment positionAlignment) const
QFont mainFont () const
QColor mainColor () const
QPen mainPen () const
QBrush mainBrush () const
Protected Attributes
QColor mColor
QColor mSelectedColor
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
QFont mFont
QFont mSelectedFont
QString mText
Qt::Alignment mPositionAlignment
Qt::Alignment mTextAlignment
double mRotation
QMargins mPadding
Additional Inherited Members
Detailed Description
A text label.
 Its position is defined by the member position and the setting of setPositionAlignment. The latter controls which part of the text rect shall be aligned with position.
The text alignment itself (i.e. left, center, right) can be controlled with setTextAlignment.
The text may be rotated around the position point with setRotation.
Definition at line 3421 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemText::AnchorIndex [protected]
Enumerator
aiTopLeft
aiTop
aiTopRight
aiRight
aiBottomRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 3487 of file qcustomplot.h.
{aiTopLeft, aiTop, aiTopRight, aiRight,
      aiBottomRight, aiBottom, aiBottomLeft, aiLeft};
Constructor & Destructor Documentation
QCPItemText::QCPItemText (QCustomPlot * parentPlot)
Creates a text item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 22192 of file qcustomplot.cpp.
References position, setBrush(), setColor(), QCPItemPosition::setCoords(), setPen(), setPositionAlignment(), setRotation(), setSelectedBrush(), setSelectedColor(), setSelectedPen(), setText(), and setTextAlignment().
                                                :
  QCPAbstractItem(parentPlot),
  position(createPosition(QLatin1String("position"))),
  topLeft(createAnchor(QLatin1String("topLeft"), aiTopLeft)),
  top(createAnchor(QLatin1String("top"), aiTop)),
  topRight(createAnchor(QLatin1String("topRight"),
      aiTopRight)),
  right(createAnchor(QLatin1String("right"), aiRight)),
  bottomRight(createAnchor(QLatin1String("bottomRight"),
      aiBottomRight)),
  bottom(createAnchor(QLatin1String("bottom"), aiBottom)),
  bottomLeft(createAnchor(QLatin1String("bottomLeft"),
      aiBottomLeft)),
  left(createAnchor(QLatin1String("left"), aiLeft))
{
  position->setCoords(0, 0);
  
  setRotation(0);
  setTextAlignment(Qt::AlignTop|Qt::AlignHCenter);
  setPositionAlignment(Qt::AlignCenter);
  setText(QLatin1String("text"));
  
  setPen(Qt::NoPen);
  setSelectedPen(Qt::NoPen);
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
  setColor(Qt::black);
  setSelectedColor(Qt::blue);
}
QCPItemText::~QCPItemText () [virtual]
Definition at line 22219 of file qcustomplot.cpp.
{
}
Member Function Documentation
QPointF QCPItemText::anchorPixelPoint (int anchorId) const [protected], [virtual]
Reimplemented from QCPAbstractItem.
Definition at line 22414 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiBottomRight, aiLeft, aiRight, aiTop, aiTopLeft, aiTopRight, getTextDrawPoint(), mainFont(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPoint(), and position.
{
  // get actual rect points (pretty much copied from draw function):
  QPointF pos(position->pixelPoint());
  QTransform transform;
  transform.translate(pos.x(), pos.y());
  if (!qFuzzyIsNull(mRotation))
    transform.rotate(mRotation);
  QFontMetrics fontMetrics(mainFont());
  QRect textRect = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip|
      mTextAlignment, mText);
  QRectF textBoxRect = textRect.adjusted(-mPadding.left(), -mPadding.top(),
      mPadding.right(), mPadding.bottom());
  QPointF textPos = getTextDrawPoint(QPointF(0, 0), textBoxRect,
      mPositionAlignment); // 0, 0 because the transform does the translation
  textBoxRect.moveTopLeft(textPos.toPoint());
  QPolygonF rectPoly = transform.map(QPolygonF(textBoxRect));
  
  switch (anchorId)
  {
    case aiTopLeft: return rectPoly.at(0);
    case aiTop: return (rectPoly.at(0)+rectPoly.at(1))*0.5;
    case aiTopRight: return rectPoly.at(1);
    case aiRight: return (rectPoly.at(1)+rectPoly.at(2))*0.5;
    case aiBottomRight: return rectPoly.at(2);
    case aiBottom: return (rectPoly.at(2)+rectPoly.at(3))*0.5;
    case aiBottomLeft: return rectPoly.at(3);
    case aiLeft: return (rectPoly.at(3)+rectPoly.at(0))*0.5;
  }
  
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
QBrush QCPItemText::brush () const [inline]
Definition at line 3448 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
QColor QCPItemText::color () const [inline]
Definition at line 3444 of file qcustomplot.h.
Referenced by draw(), setColor(), and setSelectedColor().
{ return mColor; }
void QCPItemText::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractItem.
Definition at line 22382 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), color(), getTextDrawPoint(), mainBrush(), mainColor(), mainFont(), mainPen(), mPadding, mPositionAlignment, mRotation, mText, mTextAlignment, QCPItemPosition::pixelPoint(), position, and QCPPainter::setPen().
{
  QPointF pos(position->pixelPoint());
  QTransform transform = painter->transform();
  transform.translate(pos.x(), pos.y());
  if (!qFuzzyIsNull(mRotation))
    transform.rotate(mRotation);
  painter->setFont(mainFont());
  QRect textRect = painter->fontMetrics().boundingRect(0, 0, 0, 0, Qt::TextDontClip|
      mTextAlignment, mText);
  QRect textBoxRect = textRect.adjusted(-mPadding.left(), -mPadding.top(),
      mPadding.right(), mPadding.bottom());
  QPointF textPos = getTextDrawPoint(QPointF(0, 0), textBoxRect,
      mPositionAlignment); // 0, 0 because the transform does the translation
  textRect.moveTopLeft(textPos.toPoint()+QPoint(mPadding.left(),
      mPadding.top()));
  textBoxRect.moveTopLeft(textPos.toPoint());
  double clipPad = mainPen().widthF();
  QRect boundingRect = textBoxRect.adjusted(-clipPad, -clipPad, clipPad, clipPad);
  if (transform.mapRect(boundingRect).intersects(painter->transform().mapRect(
      clipRect())))
  {
    painter->setTransform(transform);
    if ((mainBrush().style() != Qt::NoBrush && mainBrush().
      color().alpha() != 0) ||
        (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0))
    {
      painter->setPen(mainPen());
      painter->setBrush(mainBrush());
      painter->drawRect(textBoxRect);
    }
    painter->setBrush(Qt::NoBrush);
    painter->setPen(QPen(mainColor()));
    painter->drawText(textRect, Qt::TextDontClip|mTextAlignment,
      mText);
  }
}
QFont QCPItemText::font () const [inline]
Definition at line 3450 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
{ return mFont; }
QPointF QCPItemText::getTextDrawPoint (const QPointF & pos, const QRectF & rect, Qt::Alignment positionAlignment) const [protected]
Definition at line 22455 of file qcustomplot.cpp.
Referenced by anchorPixelPoint(), draw(), and selectTest().
{
  if (positionAlignment == 0 || positionAlignment == (Qt::AlignLeft|
      Qt::AlignTop))
    return pos;
  
  QPointF result = pos; // start at top left
  if (positionAlignment.testFlag(Qt::AlignHCenter))
    result.rx() -= rect.width()/2.0;
  else if (positionAlignment.testFlag(Qt::AlignRight))
    result.rx() -= rect.width();
  if (positionAlignment.testFlag(Qt::AlignVCenter))
    result.ry() -= rect.height()/2.0;
  else if (positionAlignment.testFlag(Qt::AlignBottom))
    result.ry() -= rect.height();
  return result;
}
QBrush QCPItemText::mainBrush () const [protected]
Definition at line 22507 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
{
  return mSelected ? mSelectedBrush : mBrush;
}
QColor QCPItemText::mainColor () const [protected]
Definition at line 22487 of file qcustomplot.cpp.
References mColor, QCPAbstractItem::mSelected, and mSelectedColor.
Referenced by draw().
{
  return mSelected ? mSelectedColor : mColor;
}
QFont QCPItemText::mainFont () const [protected]
Definition at line 22477 of file qcustomplot.cpp.
References mFont, QCPAbstractItem::mSelected, and mSelectedFont.
Referenced by anchorPixelPoint(), and draw().
{
  return mSelected ? mSelectedFont : mFont;
}
QPen QCPItemText::mainPen () const [protected]
Definition at line 22497 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{
  return mSelected ? mSelectedPen : mPen;
}
QMargins QCPItemText::padding () const [inline]
Definition at line 3456 of file qcustomplot.h.
Referenced by setPadding().
{ return mPadding; }
QPen QCPItemText::pen () const [inline]
Definition at line 3446 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
Qt::Alignment QCPItemText::positionAlignment () const [inline]
Definition at line 3453 of file qcustomplot.h.
{ return mPositionAlignment; }
double QCPItemText::rotation () const [inline]
Definition at line 3455 of file qcustomplot.h.
{ return mRotation; }
QBrush QCPItemText::selectedBrush () const [inline]
Definition at line 3449 of file qcustomplot.h.
{ return mSelectedBrush; }
QColor QCPItemText::selectedColor () const [inline]
Definition at line 3445 of file qcustomplot.h.
{ return mSelectedColor; }
QFont QCPItemText::selectedFont () const [inline]
Definition at line 3451 of file qcustomplot.h.
{ return mSelectedFont; }
QPen QCPItemText::selectedPen () const [inline]
Definition at line 3447 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemText::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 22358 of file qcustomplot.cpp.
References getTextDrawPoint(), mFont, mPadding, mPositionAlignment, mRotation, QCPAbstractItem::mSelectable, mText, mTextAlignment, QCPItemPosition::pixelPoint(), position, and QCPAbstractItem::rectSelectTest().
{
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  
  // The rect may be rotated, so we transform the actual clicked pos to the rotated
  // coordinate system, so we can use the normal rectSelectTest function for non-rotated rects:
  QPointF positionPixels(position->pixelPoint());
  QTransform inputTransform;
  inputTransform.translate(positionPixels.x(), positionPixels.y());
  inputTransform.rotate(-mRotation);
  inputTransform.translate(-positionPixels.x(), -positionPixels.y());
  QPointF rotatedPos = inputTransform.map(pos);
  QFontMetrics fontMetrics(mFont);
  QRect textRect = fontMetrics.boundingRect(0, 0, 0, 0, Qt::TextDontClip|
      mTextAlignment, mText);
  QRect textBoxRect = textRect.adjusted(-mPadding.left(), -mPadding.
      top(), mPadding.right(), mPadding.bottom());
  QPointF textPos = getTextDrawPoint(positionPixels, textBoxRect,
      mPositionAlignment);
  textBoxRect.moveTopLeft(textPos.toPoint());
  return rectSelectTest(textBoxRect, rotatedPos, true);
}
void QCPItemText::setBrush (const QBrush & brush)
Sets the brush that will be used do fill the background of the text. To disable the background, set brush to Qt::NoBrush.
See also
setSelectedBrush, setPen, setPadding
Definition at line 22267 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemText().
{
  mBrush = brush;
}
void QCPItemText::setColor (const QColor & color)
Sets the color of the text.
Definition at line 22226 of file qcustomplot.cpp.
References color(), and mColor.
Referenced by QCPItemText().
{
  mColor = color;
}
void QCPItemText::setFont (const QFont & font)
Sets the font of the text.
See also
setSelectedFont, setColor
Definition at line 22288 of file qcustomplot.cpp.
References font(), and mFont.
{
  mFont = font;
}
void QCPItemText::setPadding (const QMargins & padding)
Sets the distance between the border of the text rectangle and the text. The appearance (and visibility) of the text rectangle can be controlled with setPen and setBrush.
Definition at line 22352 of file qcustomplot.cpp.
References mPadding, and padding().
{
  mPadding = padding;
}
void QCPItemText::setPen (const QPen & pen)
Sets the pen that will be used do draw a rectangular border around the text. To disable the border, set pen to Qt::NoPen.
See also
setSelectedPen, setBrush, setPadding
Definition at line 22245 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemText().
{
  mPen = pen;
}
void QCPItemText::setPositionAlignment (Qt::Alignment alignment)
Sets which point of the text rect shall be aligned with position.
Examples:
If alignment is Qt::AlignHCenter | Qt::AlignTop, the text will be positioned such that the top of the text rect will be horizontally centered on position.
If alignment is Qt::AlignLeft | Qt::AlignBottom, position will indicate the bottom left corner of the text rect.
If you want to control the alignment of (multi-lined) text within the text rect, use setTextAlignment.
Definition at line 22326 of file qcustomplot.cpp.
References mPositionAlignment.
Referenced by QCPItemText().
{
  mPositionAlignment = alignment;
}
void QCPItemText::setRotation (double degrees)
Sets the angle in degrees by which the text (and the text rectangle, if visible) will be rotated around position.
Definition at line 22343 of file qcustomplot.cpp.
References mRotation.
Referenced by QCPItemText().
{
  mRotation = degrees;
}
void QCPItemText::setSelectedBrush (const QBrush & brush)
Sets the brush that will be used do fill the background of the text, when the item is selected. To disable the background, set brush to Qt::NoBrush.
See also
setBrush
Definition at line 22278 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemText().
{
  mSelectedBrush = brush;
}
void QCPItemText::setSelectedColor (const QColor & color)
Sets the color of the text that will be used when the item is selected.
Definition at line 22234 of file qcustomplot.cpp.
References color(), and mSelectedColor.
Referenced by QCPItemText().
{
  mSelectedColor = color;
}
void QCPItemText::setSelectedFont (const QFont & font)
Sets the font of the text that will be used when the item is selected.
See also
setFont
Definition at line 22298 of file qcustomplot.cpp.
References font(), and mSelectedFont.
{
  mSelectedFont = font;
}
void QCPItemText::setSelectedPen (const QPen & pen)
Sets the pen that will be used do draw a rectangular border around the text, when the item is selected. To disable the border, set pen to Qt::NoPen.
See also
setPen
Definition at line 22256 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemText().
{
  mSelectedPen = pen;
}
void QCPItemText::setText (const QString & text)
Sets the text that will be displayed. Multi-line texts are supported by inserting a line break character, e.g. '
'.
See also
setFont, setColor, setTextAlignment
Definition at line 22309 of file qcustomplot.cpp.
References mText, and text().
Referenced by QCPItemText().
{
  mText = text;
}
void QCPItemText::setTextAlignment (Qt::Alignment alignment)
Controls how (multi-lined) text is aligned inside the text rect (typically Qt::AlignLeft, Qt::AlignCenter or Qt::AlignRight).
Definition at line 22334 of file qcustomplot.cpp.
References mTextAlignment.
Referenced by QCPItemText().
{
  mTextAlignment = alignment;
}
QString QCPItemText::text () const [inline]
Definition at line 3452 of file qcustomplot.h.
Referenced by setText().
{ return mText; }
Qt::Alignment QCPItemText::textAlignment () const [inline]
Definition at line 3454 of file qcustomplot.h.
{ return mTextAlignment; }
Member Data Documentation
QCPItemAnchor* const QCPItemText::bottom
Definition at line 3482 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::bottomLeft
Definition at line 3483 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::bottomRight
Definition at line 3481 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::left
Definition at line 3484 of file qcustomplot.h.
QBrush QCPItemText::mBrush [protected]
Definition at line 3492 of file qcustomplot.h.
Referenced by mainBrush(), and setBrush().
QColor QCPItemText::mColor [protected]
Definition at line 3490 of file qcustomplot.h.
Referenced by mainColor(), and setColor().
QFont QCPItemText::mFont [protected]
Definition at line 3493 of file qcustomplot.h.
Referenced by mainFont(), selectTest(), and setFont().
QMargins QCPItemText::mPadding [protected]
Definition at line 3498 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setPadding().
QPen QCPItemText::mPen [protected]
Definition at line 3491 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
Qt::Alignment QCPItemText::mPositionAlignment [protected]
Definition at line 3495 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setPositionAlignment().
double QCPItemText::mRotation [protected]
Definition at line 3497 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setRotation().
QBrush QCPItemText::mSelectedBrush [protected]
Definition at line 3492 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QColor QCPItemText::mSelectedColor [protected]
Definition at line 3490 of file qcustomplot.h.
Referenced by mainColor(), and setSelectedColor().
QFont QCPItemText::mSelectedFont [protected]
Definition at line 3493 of file qcustomplot.h.
Referenced by mainFont(), and setSelectedFont().
QPen QCPItemText::mSelectedPen [protected]
Definition at line 3491 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QString QCPItemText::mText [protected]
Definition at line 3494 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setText().
Qt::Alignment QCPItemText::mTextAlignment [protected]
Definition at line 3496 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setTextAlignment().
QCPItemPosition* const QCPItemText::position
Definition at line 3476 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemText(), and selectTest().
QCPItemAnchor* const QCPItemText::right
Definition at line 3480 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::top
Definition at line 3478 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::topLeft
Definition at line 3477 of file qcustomplot.h.
QCPItemAnchor* const QCPItemText::topRight
Definition at line 3479 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp