SoilMath::NN Class Reference
The Neural Network class.
#include <NN.h>
Public Member Functions
NN (uint32_t inputneurons, uint32_t hiddenneurons, uint32_t outputneurons)
NN constructor for the Neural Net.
NN ()
NN constructor for the Neural Net.
virtual ~NN ()
~NN virtual deconstructor for the Neural Net
Predict_t Predict (ComplexVect_t input)
Predict The prediction function.
void SetInputWeights (Weight_t value)
SetInputWeights a function to set the input weights.
void SetHiddenWeights (Weight_t value)
SetHiddenWeights a function to set the hidden weights.
void SetBeta (float value)
SetBeta a function to set the beta value.
void Learn (InputLearnVector_t input, OutputLearnVector_t cat, uint32_t noOfDescriptorsUsed)
Learn the learning function.
void SaveState (string filename)
SaveState Serialize and save the values of the Neural Net to disk.
void LoadState (string filename)
LoadState Loads the previouse saved Neural Net from disk.
Static Public Member Functions
static Predict_t PredictLearn (ComplexVect_t input, Weight_t inputweights, Weight_t hiddenweights, uint32_t inputneurons, uint32_t hiddenneurons, uint32_t outputneurons)
PredictLearn a static function used in learning of the weights.
Public Attributes
Weight_t iWeights
Weight_t hWeights
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
serialization function
Private Attributes
std::vector< float > iNeurons
std::vector< float > hNeurons
std::vector< float > oNeurons
uint32_t hiddenNeurons
uint32_t inputNeurons
uint32_t outputNeurons
float beta
bool studied
Friends
class boost::serialization::access
Detailed Description
The Neural Network class.
This class is used to make prediction on large data set. Using self learning algoritmes
Definition at line 30 of file NN.h.
Constructor & Destructor Documentation
SoilMath::NN::NN (uint32_t inputneurons, uint32_t hiddenneurons, uint32_t outputneurons)
NN constructor for the Neural Net.
Parameters
inputneurons number of input neurons
hiddenneurons number of hidden neurons
outputneurons number of output neurons
Definition at line 13 of file NN.cpp.
References beta, hiddenNeurons, hNeurons, iNeurons, inputNeurons, oNeurons, and outputNeurons.
                                                                            {
  // Set the number of neurons in the network
  inputNeurons = inputneurons;
  hiddenNeurons = hiddenneurons;
  outputNeurons = outputneurons;
  // Reserve the vector space
  iNeurons.reserve(inputNeurons + 1); // input neurons + bias
  hNeurons.reserve(hiddenNeurons + 1); // hidden neurons + bias
  oNeurons.reserve(outputNeurons); // output neurons
  beta = 0.666;
}
SoilMath::NN::NN ()
NN constructor for the Neural Net.
Definition at line 11 of file NN.cpp.
References beta.
{ beta = 0.666; }
SoilMath::NN::~NN () [virtual]
~NN virtual deconstructor for the Neural Net
Definition at line 26 of file NN.cpp.
{}
Member Function Documentation
void SoilMath::NN::Learn (InputLearnVector_t input, OutputLearnVector_t cat, uint32_t noOfDescriptorsUsed)
Learn the learning function.
Parameters
input a vector of vectors with complex input values
cat a vector of vectors with the know output values
noOfDescriptorsUsed the total number of descriptos which should be used
Definition at line 100 of file NN.cpp.
References SoilMath::GA::Evolve(), hiddenNeurons, hWeights, inputNeurons, iWeights, outputNeurons, PredictLearn(), and studied.
Referenced by BOOST_AUTO_TEST_CASE().
                                             {
  SoilMath::GA optim(PredictLearn, inputNeurons,
      hiddenNeurons, outputNeurons);
  ComplexVect_t inputTest;
  std::vector<Weight_t> weights;
  Weight_t weight(((inputNeurons + 1) * hiddenNeurons) +
                      ((hiddenNeurons + 1) * outputNeurons),
                  0);
  // loop through each case and adjust the weights
  optim.Evolve(input, weight, MinMaxWeight_t(-50, 50), cat, 1000, 50);
  this->iWeights = Weight_t(
      weight.begin(), weight.begin() + ((inputNeurons + 1) *
      hiddenNeurons));
  this->hWeights = Weight_t(
      weight.begin() + ((inputNeurons + 1) * hiddenNeurons), weight.end());
  studied = true;
}
void SoilMath::NN::LoadState (string filename)
LoadState Loads the previouse saved Neural Net from disk.
Parameters
filename a string indicating the file location and name
Definition at line 28 of file NN.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), BOOST_FIXTURE_TEST_CASE(), VSAGUI::on_actionImport_triggered(), and VSAGUI::VSAGUI().
                                  {
  std::ifstream ifs(filename.c_str());
  boost::archive::xml_iarchive ia(ifs);
  ia >> boost::serialization::make_nvp("NeuralNet", *this);
}
Predict_t SoilMath::NN::Predict (ComplexVect_t input)
Predict The prediction function.
In this function the neural net is setup and the input which are the complex values descriping the contour in the frequency domein serve as input. The absolute value of these im. number because I'm not interrested in the orrientation of the particle but more in the degree of variations.
Parameters
input vector of complex input values, these're the Fourier descriptors
Returns
a real valued vector of the output neurons
Definition at line 49 of file NN.cpp.
References beta, hiddenNeurons, hNeurons, hWeights, i, iNeurons, inputNeurons, iWeights, j, oNeurons, Predict_struct::OutputNeurons, and outputNeurons.
Referenced by SoilAnalyzer::Particle::Analyze(), BOOST_AUTO_TEST_CASE(), and PredictLearn().
                                         {
  if (input.size() != inputNeurons) {
    throw Exception::MathException("Size of input Neurons Exception!");
  }
  iNeurons.clear();
  hNeurons.clear();
  oNeurons.clear();
  // Set the bias in the input and hidden vector to 1 (real number)
  iNeurons.push_back(1.0f);
  hNeurons.push_back(1.0f);
  Predict_t retVal;
  uint32_t wCount = 0;
  // Init the network
  for (uint32_t i = 0; i < inputNeurons; i++) {
    iNeurons.push_back(static_cast<float>(abs(input[i])));
  }
  for (uint32_t i = 0; i < hiddenNeurons; i++) {
    hNeurons.push_back(0.0f);
  }
  for (uint32_t i = 0; i < outputNeurons; i++) {
    oNeurons.push_back(0.0f);
  }
  for (uint32_t i = 1; i < hNeurons.size(); i++) {
    wCount = i - 1;
    for (uint32_t j = 0; j < iNeurons.size(); j++) {
      hNeurons[i] += iNeurons[j] * iWeights[wCount];
      wCount += hNeurons.size() - 1;
    }
    hNeurons[i] = 1 / (1 + pow(2.71828f, (-hNeurons[i] * beta)));
  }
  for (uint32_t i = 0; i < oNeurons.size(); i++) {
    wCount = i;
    for (uint32_t j = 0; j < hNeurons.size(); j++) {
      oNeurons[i] += hNeurons[j] * hWeights[wCount];
      wCount += oNeurons.size();
    }
    oNeurons[i] =
        (2 / (1.0f + pow(2.71828f, (-oNeurons[i] * beta)))) -
        1; // Shift plus scale so the learning function can be calculated
  }
  retVal.OutputNeurons = oNeurons;
  return retVal;
}
Predict_t SoilMath::NN::PredictLearn (ComplexVect_t input, Weight_t inputweights, Weight_t hiddenweights, uint32_t inputneurons, uint32_t hiddenneurons, uint32_t outputneurons) [static]
PredictLearn a static function used in learning of the weights.
It starts a new Neural Network object and passes all the paramaters in to this newly created object. After this the predict function is called and the value is returned. This work around was needed to pass the neural network to the Genetic Algorithm class.
Parameters
input a complex vector of input values
inputweights the input weights
hiddenweights the hidden weights
inputneurons the input neurons
hiddenneurons the hidden neurons
outputneurons the output neurons
Returns
Definition at line 40 of file NN.cpp.
References Predict(), SetHiddenWeights(), and SetInputWeights().
Referenced by Learn().
                                                                           {
  NN neural(inputneurons, hiddenneurons, outputneurons);
  neural.SetInputWeights(inputweights);
  neural.SetHiddenWeights(hiddenweights);
  return neural.Predict(input);
}
void SoilMath::NN::SaveState (string filename)
SaveState Serialize and save the values of the Neural Net to disk.
Save the Neural Net in XML valued text file to disk so that a object can be reconstructed on a latter stadia.
Parameters
filename a string indicating the file location and name
Definition at line 34 of file NN.cpp.
Referenced by BOOST_AUTO_TEST_CASE(), and VSAGUI::on_actionExport_triggered().
                                  {
  std::ofstream ofs(filename.c_str());
  boost::archive::xml_oarchive oa(ofs);
  oa << boost::serialization::make_nvp("NeuralNet", *this);
}
template<class Archive > void SoilMath::NN::serialize (Archive & ar, const unsigned int version) [inline], [private]
serialization function
Parameters
ar the object
version the version of the class
Definition at line 153 of file NN.h.
                                                          {
    ar &BOOST_SERIALIZATION_NVP(inputNeurons);
    ar &BOOST_SERIALIZATION_NVP(hiddenNeurons);
    ar &BOOST_SERIALIZATION_NVP(outputNeurons);
    ar &BOOST_SERIALIZATION_NVP(iWeights);
    ar &BOOST_SERIALIZATION_NVP(hWeights);
    ar &BOOST_SERIALIZATION_NVP(beta);
    ar &BOOST_SERIALIZATION_NVP(studied);
  }
void SoilMath::NN::SetBeta (float value) [inline]
SetBeta a function to set the beta value.
Parameters
value a floating value ussualy between 0.5 and 1.5
Definition at line 96 of file NN.h.
References beta.
{ beta = value; }
void SoilMath::NN::SetHiddenWeights (Weight_t value) [inline]
SetHiddenWeights a function to set the hidden weights.
Parameters
value the real valued vector with the values
Definition at line 90 of file NN.h.
References hWeights.
Referenced by PredictLearn().
{ hWeights = value; }
void SoilMath::NN::SetInputWeights (Weight_t value) [inline]
SetInputWeights a function to set the input weights.
Parameters
value the real valued vector with the values
Definition at line 84 of file NN.h.
References iWeights.
Referenced by PredictLearn().
{ iWeights = value; }
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
a private friend class so the serialization can access all the needed functions
Definition at line 144 of file NN.h.
Member Data Documentation
float SoilMath::NN::beta [private]
the beta value, this indicates the steepness of the sigmoid function
Definition at line 138 of file NN.h.
Referenced by NN(), Predict(), and SetBeta().
uint32_t SoilMath::NN::hiddenNeurons [private]
number of hidden neurons minus bias
Definition at line 135 of file NN.h.
Referenced by Learn(), NN(), and Predict().
std::vector<float> SoilMath::NN::hNeurons [private]
a vector of hidden values, the bias is included and is the first value
Definition at line 131 of file NN.h.
Referenced by NN(), and Predict().
Weight_t SoilMath::NN::hWeights
a vector of real valued floating point hidden weight
Definition at line 124 of file NN.h.
Referenced by BOOST_AUTO_TEST_CASE(), Learn(), Predict(), and SetHiddenWeights().
std::vector<float> SoilMath::NN::iNeurons [private]
a vector of input values, the bias is included, the bias is included and is the first value
Definition at line 127 of file NN.h.
Referenced by NN(), and Predict().
uint32_t SoilMath::NN::inputNeurons [private]
number of input neurons minus bias
Definition at line 136 of file NN.h.
Referenced by Learn(), NN(), and Predict().
Weight_t SoilMath::NN::iWeights
a vector of real valued floating point input weights
Definition at line 123 of file NN.h.
Referenced by BOOST_AUTO_TEST_CASE(), Learn(), Predict(), and SetInputWeights().
std::vector<float> SoilMath::NN::oNeurons [private]
a vector of output values
Definition at line 133 of file NN.h.
Referenced by NN(), and Predict().
uint32_t SoilMath::NN::outputNeurons [private]
number of output neurons
Definition at line 137 of file NN.h.
Referenced by Learn(), NN(), and Predict().
bool SoilMath::NN::studied [private]
Initial value:
=
      false
a value indicating if the weights are a results of a learning curve
Definition at line 141 of file NN.h.
Referenced by Learn().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilMath/NN.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilMath/NN.cpp