QCPItemTracer Class Reference
Item that sticks to QCPGraph data points.
#include <qcustomplot.h>
Public Types
enum TracerStyle {
*
tsNone,
tsPlus,
tsCrosshair,
tsCircle,
*
tsSquare
 }
Public Member Functions
QCPItemTracer (QCustomPlot *parentPlot)
virtual ~QCPItemTracer ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
double size () const
TracerStyle style () const
QCPGraph * graph () const
double graphKey () const
bool interpolating () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
void setSize (double size)
void setStyle (TracerStyle style)
void setGraph (QCPGraph *graph)
void setGraphKey (double key)
void setInterpolating (bool enabled)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
void updatePosition ()
Public Attributes
QCPItemPosition *const position
Protected Member Functions
virtual void draw (QCPPainter *painter)
QPen mainPen () const
QBrush mainBrush () const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
double mSize
TracerStyle mStyle
QCPGraph * mGraph
double mGraphKey
bool mInterpolating
Additional Inherited Members
Detailed Description
Item that sticks to QCPGraph data points.
 anchors, solid blue discs are positions."
The tracer can be connected with a QCPGraph via setGraph. Then it will automatically adopt the coordinate axes of the graph and update its position to be on the graph's data. This means the key stays controllable via setGraphKey, but the value will follow the graph data. If a QCPGraph is connected, note that setting the coordinates of the tracer item directly via position will have no effect because they will be overriden in the next redraw (this is when the coordinate update happens).
If the specified key in setGraphKey is outside the key bounds of the graph, the tracer will stay at the corresponding end of the graph.
With setInterpolating you may specify whether the tracer may only stay exactly on data points or whether it interpolates data points linearly, if given a key that lies between two data points of the graph.
The tracer has different visual styles, see setStyle. It is also possible to make the tracer have no own visual appearance (set the style to tsNone), and just connect other item positions to the tracer position (used as an anchor) via QCPItemPosition::setParentAnchor.
Note
The tracer position is only automatically updated upon redraws. So when the data of the graph changes and immediately afterwards (without a redraw) the a position coordinates of the tracer are retrieved, they will not reflect the updated data of the graph. In this case updatePosition must be called manually, prior to reading the tracer coordinates.
Definition at line 4130 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemTracer::TracerStyle
The different visual appearances a tracer item can have. Some styles size may be controlled with setSize.
See also
setStyle
Enumerator
tsNone
 The tracer is not visible.
tsPlus
 A plus shaped crosshair with limited size.
tsCrosshair
 A plus shaped crosshair which spans the complete axis rect.
tsCircle
 A circle.
tsSquare
 A square.
Definition at line 4150 of file qcustomplot.h.
                   {
    tsNone
    ,
    tsPlus
    ,
    tsCrosshair
    ,
    tsCircle
    ,
    tsSquare
  };
Constructor & Destructor Documentation
QCPItemTracer::QCPItemTracer (QCustomPlot * parentPlot)
Creates a tracer item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 25511 of file qcustomplot.cpp.
References position, setBrush(), QCPItemPosition::setCoords(), setGraphKey(), setInterpolating(), setPen(), setSelectedBrush(), setSelectedPen(), setSize(), setStyle(), and tsCrosshair.
    : QCPAbstractItem(parentPlot),
      position(createPosition(QLatin1String("position"))),
      mGraph(0) {
  position->setCoords(0, 0);
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue, 2));
  setStyle(tsCrosshair);
  setSize(6);
  setInterpolating(false);
  setGraphKey(0);
}
QCPItemTracer::~QCPItemTracer () [virtual]
Definition at line 25526 of file qcustomplot.cpp.
{}
Member Function Documentation
QBrush QCPItemTracer::brush () const [inline]
Definition at line 4169 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
void QCPItemTracer::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractItem.
Definition at line 25697 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPPainter::drawLine(), mainBrush(), mainPen(), mSize, mStyle, QCPItemPosition::pixelPoint(), position, QCPPainter::setPen(), tsCircle, tsCrosshair, tsNone, tsPlus, tsSquare, and updatePosition().
                                            {
  updatePosition();
  if (mStyle == tsNone)
    return;
  painter->setPen(mainPen());
  painter->setBrush(mainBrush());
  QPointF center(position->pixelPoint());
  double w = mSize / 2.0;
  QRect clip = clipRect();
  switch (mStyle) {
  case tsNone:
    return;
  case tsPlus: {
    if (clip.intersects(
            QRectF(center - QPointF(w, w), center + QPointF(w, w)).toRect())) {
      painter->drawLine(
          QLineF(center + QPointF(-w, 0), center + QPointF(w, 0)));
      painter->drawLine(
          QLineF(center + QPointF(0, -w), center + QPointF(0, w)));
    }
    break;
  }
  case tsCrosshair: {
    if (center.y() > clip.top() && center.y() < clip.bottom())
      painter->drawLine(
          QLineF(clip.left(), center.y(), clip.right(), center.y()));
    if (center.x() > clip.left() && center.x() < clip.right())
      painter->drawLine(
          QLineF(center.x(), clip.top(), center.x(), clip.bottom()));
    break;
  }
  case tsCircle: {
    if (clip.intersects(
            QRectF(center - QPointF(w, w), center + QPointF(w, w)).toRect()))
      painter->drawEllipse(center, w, w);
    break;
  }
  case tsSquare: {
    if (clip.intersects(
            QRectF(center - QPointF(w, w), center + QPointF(w, w)).toRect()))
      painter->drawRect(QRectF(center - QPointF(w, w), center + QPointF(w, w)));
    break;
  }
  }
}
QCPGraph* QCPItemTracer::graph () const [inline]
Definition at line 4173 of file qcustomplot.h.
Referenced by setGraph().
{ return mGraph; }
double QCPItemTracer::graphKey () const [inline]
Definition at line 4174 of file qcustomplot.h.
{ return mGraphKey; }
bool QCPItemTracer::interpolating () const [inline]
Definition at line 4175 of file qcustomplot.h.
{ return mInterpolating; }
QBrush QCPItemTracer::mainBrush () const [protected]
Definition at line 25820 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
                                      {
  return mSelected ? mSelectedBrush : mBrush;
}
QPen QCPItemTracer::mainPen () const [protected]
Definition at line 25812 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{ return mSelected ? mSelectedPen : mPen; }
QPen QCPItemTracer::pen () const [inline]
Definition at line 4167 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QBrush QCPItemTracer::selectedBrush () const [inline]
Definition at line 4170 of file qcustomplot.h.
{ return mSelectedBrush; }
QPen QCPItemTracer::selectedPen () const [inline]
Definition at line 4168 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemTracer::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 25639 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), QCPAbstractItem::distSqrToLine(), mBrush, QCPLayerable::mParentPlot, QCPAbstractItem::mSelectable, mSize, mStyle, QCPItemPosition::pixelPoint(), position, rect, QCPAbstractItem::rectSelectTest(), QCustomPlot::selectionTolerance(), tsCircle, tsCrosshair, tsNone, tsPlus, and tsSquare.
                                                          {
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  QPointF center(position->pixelPoint());
  double w = mSize / 2.0;
  QRect clip = clipRect();
  switch (mStyle) {
  case tsNone:
    return -1;
  case tsPlus: {
    if (clipRect().intersects(
            QRectF(center - QPointF(w, w), center + QPointF(w, w)).toRect()))
      return qSqrt(qMin(
          distSqrToLine(center + QPointF(-w, 0), center + QPointF(w, 0), pos),
          distSqrToLine(center + QPointF(0, -w), center + QPointF(0, w), pos)));
    break;
  }
  case tsCrosshair: {
    return qSqrt(qMin(distSqrToLine(QPointF(clip.left(), center.y()),
                                    QPointF(clip.right(), center.y()), pos),
                      distSqrToLine(QPointF(center.x(), clip.top()),
                                    QPointF(center.x(), clip.bottom()), pos)));
  }
  case tsCircle: {
    if (clip.intersects(
            QRectF(center - QPointF(w, w), center + QPointF(w, w)).toRect())) {
      // distance to border:
      double centerDist = QVector2D(center - pos).length();
      double circleLine = w;
      double result = qAbs(centerDist - circleLine);
      // filled ellipse, allow click inside to count as hit:
      if (result > mParentPlot->selectionTolerance() * 0.99 &&
          mBrush.style() != Qt::NoBrush && mBrush.color().alpha() != 0) {
        if (centerDist <= circleLine)
          result = mParentPlot->selectionTolerance() * 0.99;
      }
      return result;
    }
    break;
  }
  case tsSquare: {
    if (clip.intersects(
            QRectF(center - QPointF(w, w), center + QPointF(w, w)).toRect())) {
      QRectF rect = QRectF(center - QPointF(w, w), center + QPointF(w, w));
      bool filledRect =
          mBrush.style() != Qt::NoBrush && mBrush.color().alpha() != 0;
      return rectSelectTest(rect, pos, filledRect);
    }
    break;
  }
  }
  return -1;
}
void QCPItemTracer::setBrush (const QBrush & brush)
Sets the brush that will be used to draw any fills of the tracer
See also
setSelectedBrush, setPen
Definition at line 25547 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemTracer().
{ mBrush = brush; }
void QCPItemTracer::setGraph (QCPGraph * graph)
Sets the QCPGraph this tracer sticks to. The tracer position will be set to type QCPItemPosition::ptPlotCoords and the axes will be set to the axes of graph.
To free the tracer from any graph, set graph to 0. The tracer position can then be placed freely like any other item position. This is the state the tracer will assume when its graph gets deleted while still attached to it.
See also
setGraphKey
Definition at line 25591 of file qcustomplot.cpp.
References graph(), QCPAbstractPlottable::keyAxis(), mGraph, QCPLayerable::mParentPlot, QCPLayerable::parentPlot(), position, QCPItemPosition::ptPlotCoords, QCPItemPosition::setAxes(), QCPItemPosition::setType(), updatePosition(), and QCPAbstractPlottable::valueAxis().
                                            {
  if (graph) {
    if (graph->parentPlot() == mParentPlot) {
      position->setType(QCPItemPosition::ptPlotCoords);
      position->setAxes(graph->keyAxis(), graph->valueAxis());
      mGraph = graph;
      updatePosition();
    } else
      qDebug() << Q_FUNC_INFO
               << "graph isn't in same QCustomPlot instance as this item";
  } else {
    mGraph = 0;
  }
}
void QCPItemTracer::setGraphKey (double key)
Sets the key of the graph's data point the tracer will be positioned at. This is the only free coordinate of a tracer when attached to a graph.
Depending on setInterpolating, the tracer will be either positioned on the data point closest to key, or will stay exactly at key and interpolate the value linearly.
See also
setGraph, setInterpolating
Definition at line 25618 of file qcustomplot.cpp.
References mGraphKey.
Referenced by QCPItemTracer().
{ mGraphKey = key; }
void QCPItemTracer::setInterpolating (bool enabled)
Sets whether the value of the graph's data points shall be interpolated, when positioning the tracer.
If enabled is set to false and a key is given with setGraphKey, the tracer is placed on the data point of the graph which is closest to the key, but which is not necessarily exactly there. If enabled is true, the tracer will be positioned exactly at the specified key, and the appropriate value will be interpolated from the graph's data points linearly.
See also
setGraph, setGraphKey
Definition at line 25636 of file qcustomplot.cpp.
References mInterpolating.
Referenced by QCPItemTracer().
{ mInterpolating = enabled; }
void QCPItemTracer::setPen (const QPen & pen)
Sets the pen that will be used to draw the line of the tracer
See also
setSelectedPen, setBrush
Definition at line 25533 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemTracer().
{ mPen = pen; }
void QCPItemTracer::setSelectedBrush (const QBrush & brush)
Sets the brush that will be used to draw any fills of the tracer, when selected.
See also
setBrush, setSelected
Definition at line 25555 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemTracer().
                                                        {
  mSelectedBrush = brush;
}
void QCPItemTracer::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line of the tracer when selected
See also
setPen, setSelected
Definition at line 25540 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemTracer().
{ mSelectedPen = pen; }
void QCPItemTracer::setSize (double size)
Sets the size of the tracer in pixels, if the style supports setting a size (e.g. tsSquare does, tsCrosshair does not).
Definition at line 25564 of file qcustomplot.cpp.
References mSize, and size().
Referenced by QCPItemTracer().
{ mSize = size; }
void QCPItemTracer::setStyle (QCPItemTracer::TracerStyle style)
Sets the style/visual appearance of the tracer.
If you only want to use the tracer position as an anchor for other items, set style to tsNone.
Definition at line 25573 of file qcustomplot.cpp.
References mStyle, and style().
Referenced by QCPItemTracer().
                                                           {
  mStyle = style;
}
double QCPItemTracer::size () const [inline]
Definition at line 4171 of file qcustomplot.h.
Referenced by setSize().
{ return mSize; }
TracerStyle QCPItemTracer::style () const [inline]
Definition at line 4172 of file qcustomplot.h.
Referenced by setStyle().
{ return mStyle; }
void QCPItemTracer::updatePosition ()
If the tracer is connected with a graph (setGraph), this function updates the tracer's position to reside on the graph data, depending on the configured key (setGraphKey).
It is called automatically on every redraw and normally doesn't need to be called manually. One exception is when you want to read the tracer coordinates via position and are not sure that the graph's data (or the tracer key with setGraphKey) hasn't changed since the last redraw. In that situation, call this function before accessing position, to make sure you don't get out-of-date coordinates.
If there is no graph set on this tracer, this function does nothing.
Definition at line 25762 of file qcustomplot.cpp.
References QCPGraph::data(), QCustomPlot::hasPlottable(), mGraph, mGraphKey, mInterpolating, QCPLayerable::mParentPlot, position, and QCPItemPosition::setCoords().
Referenced by draw(), and setGraph().
                                   {
  if (mGraph) {
    if (mParentPlot->hasPlottable(mGraph)) {
      if (mGraph->data()->size() > 1) {
        QCPDataMap::const_iterator first = mGraph->data()->constBegin();
        QCPDataMap::const_iterator last = mGraph->data()->constEnd() - 1;
        if (mGraphKey < first.key())
          position->setCoords(first.key(), first.value().value);
        else if (mGraphKey > last.key())
          position->setCoords(last.key(), last.value().value);
        else {
          QCPDataMap::const_iterator it = mGraph->data()->lowerBound(
      mGraphKey);
          if (it != first) // mGraphKey is somewhere between iterators
          {
            QCPDataMap::const_iterator prevIt = it - 1;
            if (mInterpolating) {
              // interpolate between iterators around mGraphKey:
              double slope = 0;
              if (!qFuzzyCompare((double)it.key(), (double)prevIt.key()))
                slope = (it.value().value - prevIt.value().value) /
                        (it.key() - prevIt.key());
              position->setCoords(mGraphKey,
                                  (mGraphKey - prevIt.key()) * slope +
                                      prevIt.value().value);
            } else {
              // find iterator with key closest to mGraphKey:
              if (mGraphKey < (prevIt.key() + it.key()) * 0.5)
                it = prevIt;
              position->setCoords(it.key(), it.value().value);
            }
          } else // mGraphKey is exactly on first iterator
            position->setCoords(it.key(), it.value().value);
        }
      } else if (mGraph->data()->size() == 1) {
        QCPDataMap::const_iterator it = mGraph->data()->constBegin();
        position->setCoords(it.key(), it.value().value);
      } else
        qDebug() << Q_FUNC_INFO << "graph has no data";
    } else
      qDebug() << Q_FUNC_INFO
               << "graph not contained in QCustomPlot instance (anymore)";
  }
}
Member Data Documentation
QBrush QCPItemTracer::mBrush [protected]
Definition at line 4200 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
QCPGraph* QCPItemTracer::mGraph [protected]
Definition at line 4203 of file qcustomplot.h.
Referenced by setGraph(), and updatePosition().
double QCPItemTracer::mGraphKey [protected]
Definition at line 4204 of file qcustomplot.h.
Referenced by setGraphKey(), and updatePosition().
bool QCPItemTracer::mInterpolating [protected]
Definition at line 4205 of file qcustomplot.h.
Referenced by setInterpolating(), and updatePosition().
QPen QCPItemTracer::mPen [protected]
Definition at line 4199 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QBrush QCPItemTracer::mSelectedBrush [protected]
Definition at line 4200 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QPen QCPItemTracer::mSelectedPen [protected]
Definition at line 4199 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
double QCPItemTracer::mSize [protected]
Definition at line 4201 of file qcustomplot.h.
Referenced by draw(), selectTest(), and setSize().
TracerStyle QCPItemTracer::mStyle [protected]
Definition at line 4202 of file qcustomplot.h.
Referenced by draw(), selectTest(), and setStyle().
QCPItemPosition* const QCPItemTracer::position
Definition at line 4195 of file qcustomplot.h.
Referenced by draw(), QCPItemTracer(), selectTest(), setGraph(), and updatePosition().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp