QCPAxis Class Reference
Manages a single axis inside a QCustomPlot.
#include <qcustomplot.h>
Public Types
enum AxisType { atLeft = 0x01,
atRight = 0x02,
atTop = 0x04,
atBottom = 0x08
 }
enum LabelType { ltNumber,
ltDateTime
 }
enum LabelSide { lsInside,
lsOutside
 }
enum ScaleType { stLinear,
stLogarithmic
 }
enum SelectablePart { spNone = 0,
spAxis = 0x001,
spTickLabels = 0x002,
spAxisLabel = 0x004
 }
Signals
void ticksRequest ()
void rangeChanged (const QCPRange &newRange)
void rangeChanged (const QCPRange &newRange, const QCPRange &oldRange)
void scaleTypeChanged (QCPAxis::ScaleType scaleType)
void selectionChanged (const QCPAxis::SelectableParts &parts)
void selectableChanged (const QCPAxis::SelectableParts &parts)
Public Member Functions
QCPAxis (QCPAxisRect *parent, AxisType type)
virtual ~QCPAxis ()
AxisType axisType () const
QCPAxisRect * axisRect () const
ScaleType scaleType () const
double scaleLogBase () const
const QCPRange range () const
bool rangeReversed () const
bool autoTicks () const
int autoTickCount () const
bool autoTickLabels () const
bool autoTickStep () const
bool autoSubTicks () const
bool ticks () const
bool tickLabels () const
int tickLabelPadding () const
LabelType tickLabelType () const
QFont tickLabelFont () const
QColor tickLabelColor () const
double tickLabelRotation () const
LabelSide tickLabelSide () const
QString dateTimeFormat () const
Qt::TimeSpec dateTimeSpec () const
QString numberFormat () const
int numberPrecision () const
double tickStep () const
QVector< double > tickVector () const
QVector< QString > tickVectorLabels () const
int tickLengthIn () const
int tickLengthOut () const
int subTickCount () const
int subTickLengthIn () const
int subTickLengthOut () const
QPen basePen () const
QPen tickPen () const
QPen subTickPen () const
QFont labelFont () const
QColor labelColor () const
QString label () const
int labelPadding () const
int padding () const
int offset () const
SelectableParts selectedParts () const
SelectableParts selectableParts () const
QFont selectedTickLabelFont () const
QFont selectedLabelFont () const
QColor selectedTickLabelColor () const
QColor selectedLabelColor () const
QPen selectedBasePen () const
QPen selectedTickPen () const
QPen selectedSubTickPen () const
QCPLineEnding lowerEnding () const
QCPLineEnding upperEnding () const
QCPGrid * grid () const
Q_SLOT void setScaleType (QCPAxis::ScaleType type)
void setScaleLogBase (double base)
Q_SLOT void setRange (const QCPRange &range)
void setRange (double lower, double upper)
void setRange (double position, double size, Qt::AlignmentFlag alignment)
void setRangeLower (double lower)
void setRangeUpper (double upper)
void setRangeReversed (bool reversed)
void setAutoTicks (bool on)
void setAutoTickCount (int approximateCount)
void setAutoTickLabels (bool on)
void setAutoTickStep (bool on)
void setAutoSubTicks (bool on)
void setTicks (bool show)
void setTickLabels (bool show)
void setTickLabelPadding (int padding)
void setTickLabelType (LabelType type)
void setTickLabelFont (const QFont &font)
void setTickLabelColor (const QColor &color)
void setTickLabelRotation (double degrees)
void setTickLabelSide (LabelSide side)
void setDateTimeFormat (const QString &format)
void setDateTimeSpec (const Qt::TimeSpec &timeSpec)
void setNumberFormat (const QString &formatCode)
void setNumberPrecision (int precision)
void setTickStep (double step)
void setTickVector (const QVector< double > &vec)
void setTickVectorLabels (const QVector< QString > &vec)
void setTickLength (int inside, int outside=0)
void setTickLengthIn (int inside)
void setTickLengthOut (int outside)
void setSubTickCount (int count)
void setSubTickLength (int inside, int outside=0)
void setSubTickLengthIn (int inside)
void setSubTickLengthOut (int outside)
void setBasePen (const QPen &pen)
void setTickPen (const QPen &pen)
void setSubTickPen (const QPen &pen)
void setLabelFont (const QFont &font)
void setLabelColor (const QColor &color)
void setLabel (const QString &str)
void setLabelPadding (int padding)
void setPadding (int padding)
void setOffset (int offset)
void setSelectedTickLabelFont (const QFont &font)
void setSelectedLabelFont (const QFont &font)
void setSelectedTickLabelColor (const QColor &color)
void setSelectedLabelColor (const QColor &color)
void setSelectedBasePen (const QPen &pen)
void setSelectedTickPen (const QPen &pen)
void setSelectedSubTickPen (const QPen &pen)
Q_SLOT void setSelectableParts (const QCPAxis::SelectableParts &selectableParts)
Q_SLOT void setSelectedParts (const QCPAxis::SelectableParts &selectedParts)
void setLowerEnding (const QCPLineEnding &ending)
void setUpperEnding (const QCPLineEnding &ending)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Qt::Orientation orientation () const
void moveRange (double diff)
void scaleRange (double factor, double center)
void setScaleRatio (const QCPAxis *otherAxis, double ratio=1.0)
void rescale (bool onlyVisiblePlottables=false)
double pixelToCoord (double value) const
double coordToPixel (double value) const
SelectablePart getPartAt (const QPointF &pos) const
QList< QCPAbstractPlottable * > plottables () const
QList< QCPGraph * > graphs () const
QList< QCPAbstractItem * > items () const
Static Public Member Functions
static AxisType marginSideToAxisType (QCP::MarginSide side)
static Qt::Orientation orientation (AxisType type)
static AxisType opposite (AxisType type)
Protected Member Functions
virtual void setupTickVectors ()
virtual void generateAutoTicks ()
virtual int calculateAutoSubTickCount (double tickStep) const
virtual int calculateMargin ()
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual QCP::Interaction selectionCategory () const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
void visibleTickBounds (int &lowIndex, int &highIndex) const
double baseLog (double value) const
double basePow (double value) const
QPen getBasePen () const
QPen getTickPen () const
QPen getSubTickPen () const
QFont getTickLabelFont () const
QFont getLabelFont () const
QColor getTickLabelColor () const
QColor getLabelColor () const
Protected Attributes
AxisType mAxisType
QCPAxisRect * mAxisRect
int mPadding
Qt::Orientation mOrientation
SelectableParts mSelectableParts
SelectableParts mSelectedParts
QPen mBasePen
QPen mSelectedBasePen
QString mLabel
QFont mLabelFont
QFont mSelectedLabelFont
QColor mLabelColor
QColor mSelectedLabelColor
bool mTickLabels
bool mAutoTickLabels
LabelType mTickLabelType
QFont mTickLabelFont
QFont mSelectedTickLabelFont
QColor mTickLabelColor
QColor mSelectedTickLabelColor
QString mDateTimeFormat
Qt::TimeSpec mDateTimeSpec
int mNumberPrecision
QLatin1Char mNumberFormatChar
bool mNumberBeautifulPowers
bool mTicks
double mTickStep
int mSubTickCount
int mAutoTickCount
bool mAutoTicks
bool mAutoTickStep
bool mAutoSubTicks
QPen mTickPen
QPen mSelectedTickPen
QPen mSubTickPen
QPen mSelectedSubTickPen
QCPRange mRange
bool mRangeReversed
ScaleType mScaleType
double mScaleLogBase
double mScaleLogBaseLogInv
QCPGrid * mGrid
QCPAxisPainterPrivate * mAxisPainter
int mLowestVisibleTick
int mHighestVisibleTick
QVector< double > mTickVector
QVector< QString > mTickVectorLabels
QVector< double > mSubTickVector
bool mCachedMarginValid
int mCachedMargin
Friends
class QCustomPlot
class QCPGrid
class QCPAxisRect
Detailed Description
Manages a single axis inside a QCustomPlot.
Usually doesn't need to be instantiated externally. Access QCustomPlot's default four axes via QCustomPlot::xAxis (bottom), QCustomPlot::yAxis (left), QCustomPlot::xAxis2 (top) and QCustomPlot::yAxis2 (right).
Axes are always part of an axis rect, see QCPAxisRect.
Naming convention of axis parts
Overview of the spacings and paddings that define the geometry of an axis. The dashed gray line on the left represents the QCustomPlot widget border.
Definition at line 1137 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPAxis::AxisType
Defines at which side of the axis rect the axis will appear. This also affects how the tick marks are drawn, on which side the labels are placed etc.
Enumerator
atLeft
 0x01 Axis is vertical and on the left side of the axis rect
atRight
 0x02 Axis is vertical and on the right side of the axis rect
atTop
 0x04 Axis is horizontal and on the top side of the axis rect
atBottom
 0x08 Axis is horizontal and on the bottom side of the axis rect
Definition at line 1211 of file qcustomplot.h.
                {
    atLeft = 0x01
    ,
    atRight = 0x02
    ,
    atTop = 0x04
    ,
    atBottom = 0x08
  };
enum QCPAxis::LabelSide
Defines on which side of the axis the tick labels (numbers) shall appear.
See also
setTickLabelSide
Enumerator
lsInside
 Tick labels will be displayed inside the axis rect and clipped to the inner axis rect
lsOutside
 Tick labels will be displayed outside the axis rect.
Definition at line 1247 of file qcustomplot.h.
                 {
    lsInside
    ,
    lsOutside
  };
enum QCPAxis::LabelType
When automatic tick label generation is enabled (setAutoTickLabels), defines how the coordinate of the tick is interpreted, i.e. translated into a string.
See also
setTickLabelType
Enumerator
ltNumber
 Tick coordinate is regarded as normal number and will be displayed as such. (see setNumberFormat)
ltDateTime
 Tick coordinate is regarded as a date/time (seconds since 1970-01-01T00:00:00 UTC) and will be displayed and formatted as such. (for details, see setDateTimeFormat)
Definition at line 1233 of file qcustomplot.h.
                 {
    ltNumber
    ,
    ltDateTime
  };
enum QCPAxis::ScaleType
Defines the scale of an axis.
See also
setScaleType
Enumerator
stLinear
 Linear scaling.
stLogarithmic
 Logarithmic scaling with correspondingly transformed plots and (major) tick marks at every base power (see setScaleLogBase).
Definition at line 1258 of file qcustomplot.h.
                 {
    stLinear
    ,
    stLogarithmic
  };
enum QCPAxis::SelectablePart
Defines the selectable parts of an axis.
See also
setSelectableParts, setSelectedParts
Enumerator
spNone
 None of the selectable parts.
spAxis
 The axis backbone and tick marks.
spTickLabels
 Tick labels (numbers) of this axis (as a whole, not individually)
spAxisLabel
 The axis label.
Definition at line 1270 of file qcustomplot.h.
                      {
    spNone = 0
    ,
    spAxis = 0x001
    ,
    spTickLabels = 0x002
    ,
    spAxisLabel = 0x004
  };
Constructor & Destructor Documentation
QCPAxis::QCPAxis (QCPAxisRect * parent, AxisType type) [explicit]
Constructs an Axis instance of Type type for the axis rect parent.
Usually it isn't necessary to instantiate axes directly, because you can let QCustomPlot create them for you with QCPAxisRect::addAxis. If you want to use own QCPAxis-subclasses however, create them manually and then inject them also via QCPAxisRect::addAxis.
Definition at line 4308 of file qcustomplot.cpp.
References atBottom, atLeft, atRight, atTop, QCustomPlot::currentLayer(), mGrid, QCPLayerable::mParentPlot, QCPLayerable::setAntialiased(), setLabelPadding(), QCPLayerable::setLayer(), setTickLabelPadding(), and QCPLayerable::setVisible().
    : QCPLayerable(parent->parentPlot(), QString(), parent),
      // axis base:
      mAxisType(type), mAxisRect(parent), mPadding(5),
      mOrientation(orientation(type)),
      mSelectableParts(spAxis | spTickLabels |
      spAxisLabel),
      mSelectedParts(spNone),
      mBasePen(QPen(Qt::black, 0, Qt::SolidLine, Qt::SquareCap)),
      mSelectedBasePen(QPen(Qt::blue, 2)),
      // axis label:
      mLabel(), mLabelFont(mParentPlot->font()),
      mSelectedLabelFont(
          QFont(mLabelFont.family(), mLabelFont.pointSize(), QFont::Bold)),
      mLabelColor(Qt::black), mSelectedLabelColor(Qt::blue),
      // tick labels:
      mTickLabels(true), mAutoTickLabels(true),
      mTickLabelType(ltNumber),
      mTickLabelFont(mParentPlot->font()),
      mSelectedTickLabelFont(QFont(mTickLabelFont.family(),
                                   mTickLabelFont.pointSize(), QFont::Bold)),
      mTickLabelColor(Qt::black), mSelectedTickLabelColor(Qt::blue),
      mDateTimeFormat(QLatin1String("hh:mm:ss\ndd.MM.yy")),
      mDateTimeSpec(Qt::LocalTime), mNumberPrecision(6),
      mNumberFormatChar('g'),
      mNumberBeautifulPowers(true),
      // ticks and subticks:
      mTicks(true), mTickStep(1), mSubTickCount(4),
      mAutoTickCount(6),
      mAutoTicks(true), mAutoTickStep(true),
      mAutoSubTicks(true),
      mTickPen(QPen(Qt::black, 0, Qt::SolidLine, Qt::SquareCap)),
      mSelectedTickPen(QPen(Qt::blue, 2)),
      mSubTickPen(QPen(Qt::black, 0, Qt::SolidLine, Qt::SquareCap)),
      mSelectedSubTickPen(QPen(Qt::blue, 2)),
      // scale and range:
      mRange(0, 5), mRangeReversed(false), mScaleType(
      stLinear),
      mScaleLogBase(10), mScaleLogBaseLogInv(1.0 / qLn(
      mScaleLogBase)),
      // internal members:
      mGrid(new QCPGrid(this)),
      mAxisPainter(new QCPAxisPainterPrivate(parent->
      parentPlot())),
      mLowestVisibleTick(0), mHighestVisibleTick(-1),
      mCachedMarginValid(false),
      mCachedMargin(0) {
  mGrid->setVisible(false);
  setAntialiased(false);
  setLayer(mParentPlot->currentLayer()); // it's actually on that layer
       already,
                                         // but we want it in front of the grid,
                                         // so we place it on there again
  if (type == atTop) {
    setTickLabelPadding(3);
    setLabelPadding(6);
  } else if (type == atRight) {
    setTickLabelPadding(7);
    setLabelPadding(12);
  } else if (type == atBottom) {
    setTickLabelPadding(3);
    setLabelPadding(3);
  } else if (type == atLeft) {
    setTickLabelPadding(5);
    setLabelPadding(10);
  }
}
QCPAxis::~QCPAxis () [virtual]
Definition at line 4367 of file qcustomplot.cpp.
References mAxisPainter, and mGrid.
                  {
  delete mAxisPainter;
  delete mGrid; // delete grid here instead of via parent ~QObject for better
                // defined deletion order
}
Member Function Documentation
void QCPAxis::applyDefaultAntialiasingHint (QCPPainter * painter) const [protected], [virtual]
Implements QCPLayerable.
Definition at line 6236 of file qcustomplot.cpp.
References QCP::aeAxes, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
                                                                    {
  applyAntialiasingHint(painter, mAntialiased,
      QCP::aeAxes);
}
bool QCPAxis::autoSubTicks () const [inline]
Definition at line 1297 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mAutoSubTicks; }
int QCPAxis::autoTickCount () const [inline]
Definition at line 1294 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mAutoTickCount; }
bool QCPAxis::autoTickLabels () const [inline]
Definition at line 1295 of file qcustomplot.h.
{ return mAutoTickLabels; }
bool QCPAxis::autoTicks () const [inline]
Definition at line 1293 of file qcustomplot.h.
{ return mAutoTicks; }
bool QCPAxis::autoTickStep () const [inline]
Definition at line 1296 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mAutoTickStep; }
QCPAxisRect* QCPAxis::axisRect () const [inline]
Definition at line 1288 of file qcustomplot.h.
Referenced by QCPAxisRect::addAxis(), QCPBarsGroup::getPixelSpacing(), QCPGraph::lowerFillBasePoint(), QCustomPlot::plottableAt(), setScaleRatio(), and QCPGraph::upperFillBasePoint().
{ return mAxisRect; }
AxisType QCPAxis::axisType () const [inline]
Definition at line 1287 of file qcustomplot.h.
Referenced by QCPAxisRect::addAxis(), QCPGraph::lowerFillBasePoint(), and QCPGraph::upperFillBasePoint().
{ return mAxisType; }
double QCPAxis::baseLog (double value) const [protected]
Definition at line 6360 of file qcustomplot.cpp.
References mScaleLogBaseLogInv.
Referenced by coordToPixel(), and generateAutoTicks().
                                          {
  return qLn(value) * mScaleLogBaseLogInv;
}
QPen QCPAxis::basePen () const [inline]
Definition at line 1318 of file qcustomplot.h.
{ return mBasePen; }
double QCPAxis::basePow (double value) const [protected]
Definition at line 6372 of file qcustomplot.cpp.
References mScaleLogBase.
Referenced by generateAutoTicks().
                                          {
  return qPow(mScaleLogBase, value);
}
int QCPAxis::calculateAutoSubTickCount (double tickStep) const [protected], [virtual]
Definition at line 6105 of file qcustomplot.cpp.
References mSubTickCount.
Referenced by generateAutoTicks().
                                                            {
  int result = mSubTickCount; // default to current setting, if no proper value
                              // can be found
  // get mantissa of tickstep:
  double magnitudeFactor = qPow(
      10.0,
      qFloor(qLn(tickStep) /
             qLn(10.0))); // get magnitude factor e.g. 0.01, 1, 10, 1000 etc.
  double tickStepMantissa = tickStep / magnitudeFactor;
  // separate integer and fractional part of mantissa:
  double epsilon = 0.01;
  double intPartf;
  int intPart;
  double fracPart = modf(tickStepMantissa, &intPartf);
  intPart = intPartf;
  // handle cases with (almost) integer mantissa:
  if (fracPart < epsilon || 1.0 - fracPart < epsilon) {
    if (1.0 - fracPart < epsilon)
      ++intPart;
    switch (intPart) {
    case 1:
      result = 4;
      break; // 1.0 -> 0.2 substep
    case 2:
      result = 3;
      break; // 2.0 -> 0.5 substep
    case 3:
      result = 2;
      break; // 3.0 -> 1.0 substep
    case 4:
      result = 3;
      break; // 4.0 -> 1.0 substep
    case 5:
      result = 4;
      break; // 5.0 -> 1.0 substep
    case 6:
      result = 2;
      break; // 6.0 -> 2.0 substep
    case 7:
      result = 6;
      break; // 7.0 -> 1.0 substep
    case 8:
      result = 3;
      break; // 8.0 -> 2.0 substep
    case 9:
      result = 2;
      break; // 9.0 -> 3.0 substep
    }
  } else {
    // handle cases with significantly fractional mantissa:
    if (qAbs(fracPart - 0.5) < epsilon) // *.5 mantissa
    {
      switch (intPart) {
      case 1:
        result = 2;
        break; // 1.5 -> 0.5 substep
      case 2:
        result = 4;
        break; // 2.5 -> 0.5 substep
      case 3:
        result = 4;
        break; // 3.5 -> 0.7 substep
      case 4:
        result = 2;
        break; // 4.5 -> 1.5 substep
      case 5:
        result = 4;
        break; // 5.5 -> 1.1 substep (won't occur with autoTickStep from here
               // on)
      case 6:
        result = 4;
        break; // 6.5 -> 1.3 substep
      case 7:
        result = 2;
        break; // 7.5 -> 2.5 substep
      case 8:
        result = 4;
        break; // 8.5 -> 1.7 substep
      case 9:
        result = 4;
        break; // 9.5 -> 1.9 substep
      }
    }
    // if mantissa fraction isnt 0.0 or 0.5, don't bother finding good sub tick
    // marks, leave default
  }
  return result;
}
int QCPAxis::calculateMargin () [protected], [virtual]
Definition at line 6469 of file qcustomplot.cpp.
References QCPAxisPainterPrivate::axisRect, coordToPixel(), getLabelFont(), i, QCPAxisPainterPrivate::label, QCPAxisPainterPrivate::labelFont, mAxisPainter, mAxisRect, mAxisType, mCachedMargin, mCachedMarginValid, mLabel, mPadding, QCPLayerable::mParentPlot, mTickLabelFont, mTickLabels, mTicks, mTickVector, mTickVectorLabels, QCPLayerable::mVisible, QCPLayoutElement::rect(), QCPAxisPainterPrivate::size(), QCPAxisPainterPrivate::tickLabelFont, tickLabels(), QCPAxisPainterPrivate::tickLabels, QCPAxisPainterPrivate::tickPositions, QCPAxisPainterPrivate::type, QCustomPlot::viewport(), QCPAxisPainterPrivate::viewportRect, and visibleTickBounds().
                             {
  if (!mVisible) // if not visible, directly return 0, don't cache 0 because we
                 // can't react to setVisible in QCPAxis
    return 0;
  if (mCachedMarginValid)
    return mCachedMargin;
  // run through similar steps as QCPAxis::draw, and caluclate margin needed to
  // fit axis and its labels
  int margin = 0;
  int lowTick, highTick;
  visibleTickBounds(lowTick, highTick);
  QVector<double> tickPositions; // the final coordToPixel transformed vector
                                 // passed to QCPAxisPainter
  QVector<QString> tickLabels; // the final vector passed to QCPAxisPainter
  tickPositions.reserve(highTick - lowTick + 1);
  tickLabels.reserve(highTick - lowTick + 1);
  if (mTicks) {
    for (int i = lowTick; i <= highTick; ++i) {
      tickPositions.append(coordToPixel(mTickVector.at(i)));
      if (mTickLabels)
        tickLabels.append(mTickVectorLabels.at(i));
    }
  }
  // transfer all properties of this axis to QCPAxisPainterPrivate which it
  // needs to calculate the size.
  // Note that some axis painter properties are already set by direct
  // feed-through with QCPAxis setters
  mAxisPainter->type = mAxisType;
  mAxisPainter->labelFont = getLabelFont();
  mAxisPainter->label = mLabel;
  mAxisPainter->tickLabelFont = mTickLabelFont;
  mAxisPainter->axisRect = mAxisRect->rect();
  mAxisPainter->viewportRect = mParentPlot->
      viewport();
  mAxisPainter->tickPositions = tickPositions;
  mAxisPainter->tickLabels = tickLabels;
  margin += mAxisPainter->size();
  margin += mPadding;
  mCachedMargin = margin;
  mCachedMarginValid = true;
  return margin;
}
double QCPAxis::coordToPixel (double value) const
Transforms value, in coordinates of the axis, to pixel coordinates of the QCustomPlot widget.
Definition at line 5673 of file qcustomplot.cpp.
References baseLog(), QCPAxisRect::bottom(), QCPAxisRect::height(), QCPAxisRect::left(), QCPRange::lower, mAxisRect, mRange, mRangeReversed, mScaleType, orientation(), QCPAxisRect::right(), QCPRange::size(), stLinear, QCPAxisRect::top(), QCPRange::upper, and QCPAxisRect::width().
Referenced by calculateMargin(), QCPFinancial::candlestickSelectTest(), QCPAbstractPlottable::coordsToPixels(), draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPGrid::drawGridLines(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPGrid::drawSubGridLines(), QCPBars::getBarPolygon(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPBarsGroup::getPixelSpacing(), QCPGraph::getPreparedData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPFinancial::ohlcSelectTest(), and QCPGraph::upperFillBasePoint().
                                               {
  if (orientation() == Qt::Horizontal) {
    if (mScaleType == stLinear) {
      if (!mRangeReversed)
        return (value - mRange.lower) / mRange.size() *
      mAxisRect->width() +
               mAxisRect->left();
      else
        return (mRange.upper - value) / mRange.size() *
      mAxisRect->width() +
               mAxisRect->left();
    } else // mScaleType == stLogarithmic
    {
      if (value >= 0 && mRange.upper < 0) // invalid value for logarithmic
                                          // scale, just draw it outside visible
                                          // range
        return !mRangeReversed ? mAxisRect->right() + 200
                               : mAxisRect->left() - 200;
      else if (value <= 0 && mRange.upper > 0) // invalid value for logarithmic
                                               // scale, just draw it outside
                                               // visible range
        return !mRangeReversed ? mAxisRect->left() - 200
                               : mAxisRect->right() + 200;
      else {
        if (!mRangeReversed)
          return baseLog(value / mRange.lower) /
                     baseLog(mRange.upper / mRange.lower) *
      mAxisRect->width() +
                 mAxisRect->left();
        else
          return baseLog(mRange.upper / value) /
                     baseLog(mRange.upper / mRange.lower) *
      mAxisRect->width() +
                 mAxisRect->left();
      }
    }
  } else // orientation() == Qt::Vertical
  {
    if (mScaleType == stLinear) {
      if (!mRangeReversed)
        return mAxisRect->bottom() -
               (value - mRange.lower) / mRange.size() *
      mAxisRect->height();
      else
        return mAxisRect->bottom() -
               (mRange.upper - value) / mRange.size() *
      mAxisRect->height();
    } else // mScaleType == stLogarithmic
    {
      if (value >= 0 && mRange.upper < 0) // invalid value for logarithmic
                                          // scale, just draw it outside visible
                                          // range
        return !mRangeReversed ? mAxisRect->top() - 200
                               : mAxisRect->bottom() + 200;
      else if (value <= 0 && mRange.upper > 0) // invalid value for logarithmic
                                               // scale, just draw it outside
                                               // visible range
        return !mRangeReversed ? mAxisRect->bottom() + 200
                               : mAxisRect->top() - 200;
      else {
        if (!mRangeReversed)
          return mAxisRect->bottom() -
                 baseLog(value / mRange.lower) /
                     baseLog(mRange.upper / mRange.lower) *
      mAxisRect->height();
        else
          return mAxisRect->bottom() -
                 baseLog(mRange.upper / value) /
                     baseLog(mRange.upper / mRange.lower) *
      mAxisRect->height();
      }
    }
  }
}
QString QCPAxis::dateTimeFormat () const [inline]
Definition at line 1306 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mDateTimeFormat; }
Qt::TimeSpec QCPAxis::dateTimeSpec () const [inline]
Definition at line 1307 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mDateTimeSpec; }
void QCPAxis::deselectEvent (bool * selectionStateChanged) [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 6213 of file qcustomplot.cpp.
References mSelectableParts, mSelectedParts, and setSelectedParts().
                                                       {
  SelectableParts selBefore = mSelectedParts;
  setSelectedParts(mSelectedParts & ~
      mSelectableParts);
  if (selectionStateChanged)
    *selectionStateChanged = mSelectedParts != selBefore;
}
void QCPAxis::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPLayerable.
Definition at line 6246 of file qcustomplot.cpp.
References QCPAxisPainterPrivate::abbreviateDecimalPowers, QCPAxisPainterPrivate::axisRect, QCPAxisPainterPrivate::basePen, coordToPixel(), QCPAxisPainterPrivate::draw(), getBasePen(), getLabelColor(), getLabelFont(), getSubTickPen(), getTickLabelColor(), getTickLabelFont(), getTickPen(), i, QCPAxisPainterPrivate::label, QCPAxisPainterPrivate::labelColor, QCPAxisPainterPrivate::labelFont, ltNumber, mAutoTickLabels, mAxisPainter, mAxisRect, mAxisType, mHighestVisibleTick, mLabel, mLowestVisibleTick, mNumberBeautifulPowers, QCPLayerable::mParentPlot, mRangeReversed, mScaleType, mSubTickCount, mSubTickVector, mTickLabels, mTickLabelType, mTicks, mTickVector, mTickVectorLabels, QCPLayoutElement::rect(), QCPAxisPainterPrivate::reversedEndings, stLogarithmic, QCPAxisPainterPrivate::substituteExponent, subTickCount(), QCPAxisPainterPrivate::subTickPen, QCPAxisPainterPrivate::subTickPositions, QCPAxisPainterPrivate::tickLabelColor, QCPAxisPainterPrivate::tickLabelFont, tickLabels(), QCPAxisPainterPrivate::tickLabels, QCPAxisPainterPrivate::tickPen, QCPAxisPainterPrivate::tickPositions, QCPAxisPainterPrivate::type, QCustomPlot::viewport(), and QCPAxisPainterPrivate::viewportRect.
                                      {
  const int lowTick = mLowestVisibleTick;
  const int highTick = mHighestVisibleTick;
  QVector<double> subTickPositions; // the final coordToPixel transformed vector
                                    // passed to QCPAxisPainter
  QVector<double> tickPositions; // the final coordToPixel transformed vector
                                    // passed to QCPAxisPainter
  QVector<QString> tickLabels; // the final vector passed to QCPAxisPainter
  tickPositions.reserve(highTick - lowTick + 1);
  tickLabels.reserve(highTick - lowTick + 1);
  subTickPositions.reserve(mSubTickVector.size());
  if (mTicks) {
    for (int i = lowTick; i <= highTick; ++i) {
      tickPositions.append(coordToPixel(mTickVector.at(i)));
      if (mTickLabels)
        tickLabels.append(mTickVectorLabels.at(i));
    }
    if (mSubTickCount > 0) {
      const int subTickCount = mSubTickVector.size();
      for (int i = 0; i < subTickCount; ++i) // no need to check bounds because
                                             // subticks are always only created
                                             // inside current mRange
        subTickPositions.append(coordToPixel(mSubTickVector.at(
      i)));
    }
  }
  // transfer all properties of this axis to QCPAxisPainterPrivate which it
  // needs to draw the axis.
  // Note that some axis painter properties are already set by direct
  // feed-through with QCPAxis setters
  mAxisPainter->type = mAxisType;
  mAxisPainter->basePen = getBasePen();
  mAxisPainter->labelFont = getLabelFont();
  mAxisPainter->labelColor = getLabelColor();
  mAxisPainter->label = mLabel;
  mAxisPainter->substituteExponent =
      mAutoTickLabels && mNumberBeautifulPowers &&
      mTickLabelType == ltNumber;
  mAxisPainter->tickPen = getTickPen();
  mAxisPainter->subTickPen = getSubTickPen();
  mAxisPainter->tickLabelFont = getTickLabelFont();
  mAxisPainter->tickLabelColor = getTickLabelColor();
  mAxisPainter->axisRect = mAxisRect->rect();
  mAxisPainter->viewportRect = mParentPlot->
      viewport();
  mAxisPainter->abbreviateDecimalPowers =
      mScaleType == stLogarithmic;
  mAxisPainter->reversedEndings = mRangeReversed;
  mAxisPainter->tickPositions = tickPositions;
  mAxisPainter->tickLabels = tickLabels;
  mAxisPainter->subTickPositions = subTickPositions;
  mAxisPainter->draw(painter);
}
void QCPAxis::generateAutoTicks () [protected], [virtual]
Definition at line 6005 of file qcustomplot.cpp.
References baseLog(), basePow(), calculateAutoSubTickCount(), i, QCPRange::lower, mAutoSubTicks, mAutoTickCount, mAutoTickStep, mRange, mScaleLogBase, mScaleType, mSubTickCount, mTickStep, mTickVector, QCPRange::size(), stLinear, and QCPRange::upper.
Referenced by setupTickVectors().
                                {
  if (mScaleType == stLinear) {
    if (mAutoTickStep) {
      // Generate tick positions according to linear scaling:
      mTickStep = mRange.size() /
                  (double)(mAutoTickCount + 1e-10); // mAutoTickCount ticks on
                                                    // average, the small
                                                    // addition is to prevent
                                                    // jitter on exact integers
      double magnitudeFactor = qPow(
          10.0,
          qFloor(
              qLn(mTickStep) /
              qLn(10.0))); // get magnitude factor e.g. 0.01, 1, 10, 1000 etc.
      double tickStepMantissa = mTickStep / magnitudeFactor;
      if (tickStepMantissa < 5) {
        // round digit after decimal point to 0.5
        mTickStep = (int)(tickStepMantissa * 2) / 2.0 * magnitudeFactor;
      } else {
        // round to first digit in multiples of 2
        mTickStep = (int)(tickStepMantissa / 2.0) * 2.0 * magnitudeFactor;
      }
    }
    if (mAutoSubTicks)
      mSubTickCount = calculateAutoSubTickCount(
      mTickStep);
    // Generate tick positions according to mTickStep:
    qint64 firstStep = floor(
        mRange.lower /
        mTickStep); // do not use qFloor here, or we'll lose 64 bit precision
    qint64 lastStep = ceil(
        mRange.upper /
        mTickStep); // do not use qCeil here, or we'll lose 64 bit precision
    int tickcount = lastStep - firstStep + 1;
    if (tickcount < 0)
      tickcount = 0;
    mTickVector.resize(tickcount);
    for (int i = 0; i < tickcount; ++i)
      mTickVector[i] = (firstStep + i) * mTickStep;
  } else // mScaleType == stLogarithmic
  {
    // Generate tick positions according to logbase scaling:
    if (mRange.lower > 0 && mRange.upper > 0) // positive range
    {
      double lowerMag = basePow(qFloor(baseLog(mRange.lower)));
      double currentMag = lowerMag;
      mTickVector.clear();
      mTickVector.append(currentMag);
      while (currentMag < mRange.upper && currentMag > 0) // currentMag might be
                                                          // zero for ranges
                                                          // ~1e-300, just
                                                          // cancel in that case
      {
        currentMag *= mScaleLogBase;
        mTickVector.append(currentMag);
      }
    } else if (mRange.lower < 0 && mRange.upper < 0) // negative range
    {
      double lowerMag = -basePow(qCeil(baseLog(-mRange.lower)));
      double currentMag = lowerMag;
      mTickVector.clear();
      mTickVector.append(currentMag);
      while (currentMag < mRange.upper && currentMag < 0) // currentMag might be
                                                          // zero for ranges
                                                          // ~1e-300, just
                                                          // cancel in that case
      {
        currentMag /= mScaleLogBase;
        mTickVector.append(currentMag);
      }
    } else // invalid range for logarithmic scale, because lower and upper have
           // different sign
    {
      mTickVector.clear();
      qDebug() << Q_FUNC_INFO
               << "Invalid range for logarithmic plot: " << mRange.lower << "-"
               << mRange.upper;
    }
  }
}
QPen QCPAxis::getBasePen () const [protected]
Definition at line 6382 of file qcustomplot.cpp.
References mBasePen, mSelectedBasePen, mSelectedParts, and spAxis.
Referenced by draw().
                               {
  return mSelectedParts.testFlag(spAxis) ? mSelectedBasePen :
      mBasePen;
}
QColor QCPAxis::getLabelColor () const [protected]
Definition at line 6444 of file qcustomplot.cpp.
References mLabelColor, mSelectedLabelColor, mSelectedParts, and spAxisLabel.
Referenced by draw().
                                    {
  return mSelectedParts.testFlag(spAxisLabel) ?
      mSelectedLabelColor
                                              : mLabelColor;
}
QFont QCPAxis::getLabelFont () const [protected]
Definition at line 6423 of file qcustomplot.cpp.
References mLabelFont, mSelectedLabelFont, mSelectedParts, and spAxisLabel.
Referenced by calculateMargin(), and draw().
                                  {
  return mSelectedParts.testFlag(spAxisLabel) ?
      mSelectedLabelFont : mLabelFont;
}
QCPAxis::SelectablePart QCPAxis::getPartAt (const QPointF & pos) const
Returns the part of the axis that is hit by pos (in pixels). The return value of this function is independent of the user-selectable parts defined with setSelectableParts. Further, this function does not change the current selection state of the axis.
If the axis is not visible (setVisible), this function always returns spNone.
See also
setSelectedParts, setSelectableParts, QCustomPlot::setInteractions
Definition at line 5752 of file qcustomplot.cpp.
References QCPAxisPainterPrivate::axisSelectionBox(), QCPAxisPainterPrivate::labelSelectionBox(), mAxisPainter, QCPLayerable::mVisible, spAxis, spAxisLabel, spNone, spTickLabels, and QCPAxisPainterPrivate::tickLabelsSelectionBox().
Referenced by selectTest().
                                                                 {
  if (!mVisible)
    return spNone;
  if (mAxisPainter->axisSelectionBox().contains(pos.toPoint()))
    return spAxis;
  else if (mAxisPainter->tickLabelsSelectionBox().contains(pos.toPoint())
      )
    return spTickLabels;
  else if (mAxisPainter->labelSelectionBox().contains(pos.toPoint()))
    return spAxisLabel;
  else
    return spNone;
}
QPen QCPAxis::getSubTickPen () const [protected]
Definition at line 6402 of file qcustomplot.cpp.
References mSelectedParts, mSelectedSubTickPen, mSubTickPen, and spAxis.
Referenced by draw().
                                  {
  return mSelectedParts.testFlag(spAxis) ?
      mSelectedSubTickPen : mSubTickPen;
}
QColor QCPAxis::getTickLabelColor () const [protected]
Definition at line 6433 of file qcustomplot.cpp.
References mSelectedParts, mSelectedTickLabelColor, mTickLabelColor, and spTickLabels.
Referenced by draw().
                                        {
  return mSelectedParts.testFlag(spTickLabels) ?
      mSelectedTickLabelColor
                                               : mTickLabelColor;
}
QFont QCPAxis::getTickLabelFont () const [protected]
Definition at line 6412 of file qcustomplot.cpp.
References mSelectedParts, mSelectedTickLabelFont, mTickLabelFont, and spTickLabels.
Referenced by draw().
                                      {
  return mSelectedParts.testFlag(spTickLabels) ?
      mSelectedTickLabelFont
                                               : mTickLabelFont;
}
QPen QCPAxis::getTickPen () const [protected]
Definition at line 6392 of file qcustomplot.cpp.
References mSelectedParts, mSelectedTickPen, mTickPen, and spAxis.
Referenced by draw().
                               {
  return mSelectedParts.testFlag(spAxis) ? mSelectedTickPen :
      mTickPen;
}
QList< QCPGraph * > QCPAxis::graphs () const
Returns a list of all the graphs that have this axis as key or value axis.
See also
plottables, items
Definition at line 5805 of file qcustomplot.cpp.
References i, QCustomPlot::mGraphs, and QCPLayerable::mParentPlot.
                                        {
  QList<QCPGraph *> result;
  if (!mParentPlot)
    return result;
  for (int i = 0; i < mParentPlot->mGraphs.size(); ++i) {
    if (mParentPlot->mGraphs.at(i)->keyAxis() == this ||
        mParentPlot->mGraphs.at(i)->valueAxis() == this)
      result.append(mParentPlot->mGraphs.at(i));
  }
  return result;
}
QCPGrid * QCPAxis::grid () const [inline]
Returns the QCPGrid instance belonging to this axis. Access it to set details about the way the grid is displayed.
Definition at line 1338 of file qcustomplot.h.
Referenced by QCPAxisRect::QCPAxisRect(), QCPColorScaleAxisRectPrivate::QCPColorScaleAxisRectPrivate(), and QCustomPlot::QCustomPlot().
{ return mGrid; }
QList< QCPAbstractItem * > QCPAxis::items () const
Returns a list of all the items that are associated with this axis. An item is considered associated with an axis if at least one of its positions uses the axis as key or value axis.
See also
plottables, graphs
Definition at line 5826 of file qcustomplot.cpp.
References QCustomPlot::mItems, and QCPLayerable::mParentPlot.
                                              {
  QList<QCPAbstractItem *> result;
  if (!mParentPlot)
    return result;
  for (int itemId = 0; itemId < mParentPlot->mItems.size(); ++itemId) {
    QList<QCPItemPosition *> positions =
        mParentPlot->mItems.at(itemId)->positions();
    for (int posId = 0; posId < positions.size(); ++posId) {
      if (positions.at(posId)->keyAxis() == this ||
          positions.at(posId)->valueAxis() == this) {
        result.append(mParentPlot->mItems.at(itemId));
        break;
      }
    }
  }
  return result;
}
QString QCPAxis::label () const [inline]
Definition at line 1323 of file qcustomplot.h.
{ return mLabel; }
QColor QCPAxis::labelColor () const [inline]
Definition at line 1322 of file qcustomplot.h.
{ return mLabelColor; }
QFont QCPAxis::labelFont () const [inline]
Definition at line 1321 of file qcustomplot.h.
{ return mLabelFont; }
int QCPAxis::labelPadding () const
Definition at line 4411 of file qcustomplot.cpp.
References QCPAxisPainterPrivate::labelPadding, and mAxisPainter.
{ return mAxisPainter->labelPadding; }
QCPLineEnding QCPAxis::lowerEnding () const
Definition at line 4417 of file qcustomplot.cpp.
References QCPAxisPainterPrivate::lowerEnding, and mAxisPainter.
{ return mAxisPainter->lowerEnding; }
QCPAxis::AxisType QCPAxis::marginSideToAxisType (QCP::MarginSide side) [static]
Transforms a margin side to the logically corresponding axis type. (QCP::msLeft to QCPAxis::atLeft, QCP::msRight to QCPAxis::atRight, etc.)
Definition at line 5850 of file qcustomplot.cpp.
References atBottom, atLeft, atRight, atTop, QCP::msBottom, QCP::msLeft, QCP::msRight, and QCP::msTop.
Referenced by QCPAxisRect::calculateAutoMargin().
                                                                {
  switch (side) {
  case QCP::msLeft:
    return atLeft;
  case QCP::msRight:
    return atRight;
  case QCP::msTop:
    return atTop;
  case QCP::msBottom:
    return atBottom;
  default:
    break;
  }
  qDebug() << Q_FUNC_INFO << "Invalid margin side passed:" << (int)side;
  return atLeft;
}
void QCPAxis::moveRange (double diff)
If the scale type (setScaleType) is stLinear, diff is added to the lower and upper bounds of the range. The range is simply moved by diff.
If the scale type is stLogarithmic, the range bounds are multiplied by diff. This corresponds to an apparent `linear` move in logarithmic scaling by a distance of log(diff).
Definition at line 5470 of file qcustomplot.cpp.
References QCPRange::lower, mCachedMarginValid, mRange, mScaleType, rangeChanged(), stLinear, and QCPRange::upper.
                                   {
  QCPRange oldRange = mRange;
  if (mScaleType == stLinear) {
    mRange.lower += diff;
    mRange.upper += diff;
  } else // mScaleType == stLogarithmic
  {
    mRange.lower *= diff;
    mRange.upper *= diff;
  }
  mCachedMarginValid = false;
  emit rangeChanged(mRange);
  emit rangeChanged(mRange, oldRange);
}
QString QCPAxis::numberFormat () const
Definition at line 4387 of file qcustomplot.cpp.
References mAxisPainter, mNumberBeautifulPowers, mNumberFormatChar, and QCPAxisPainterPrivate::numberMultiplyCross.
Referenced by QCPAxisRect::setupFullAxesBox().
                                    {
  QString result;
  result.append(mNumberFormatChar);
  if (mNumberBeautifulPowers) {
    result.append(QLatin1Char('b'));
    if (mAxisPainter->numberMultiplyCross)
      result.append(QLatin1Char('c'));
  }
  return result;
}
int QCPAxis::numberPrecision () const [inline]
Definition at line 1309 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mNumberPrecision; }
int QCPAxis::offset () const
Definition at line 4414 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::offset.
Referenced by setOffset().
{ return mAxisPainter->offset; }
QCPAxis::AxisType QCPAxis::opposite (QCPAxis::AxisType type) [static]
Returns the axis type that describes the opposite axis of an axis with the specified type.
Definition at line 5871 of file qcustomplot.cpp.
References atBottom, atLeft, atRight, and atTop.
                                                      {
  switch (type) {
  case atLeft:
    return atRight;
    break;
  case atRight:
    return atLeft;
    break;
  case atBottom:
    return atTop;
    break;
  case atTop:
    return atBottom;
    break;
  default:
    qDebug() << Q_FUNC_INFO << "invalid axis type";
    return atLeft;
    break;
  }
}
Qt::Orientation QCPAxis::orientation () const [inline]
Returns the orientation of this axis. The axis orientation (horizontal or vertical) is deduced from the axis type (left, top, right or bottom).
See also
orientation(AxisType type)
Definition at line 1403 of file qcustomplot.h.
Referenced by QCPFinancial::candlestickSelectTest(), QCPAbstractPlottable::coordsToPixels(), coordToPixel(), QCPAxisPainterPrivate::draw(), QCPColorMap::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPGrid::drawGridLines(), QCPFinancial::drawOhlcPlot(), QCPGraph::drawScatterPlot(), QCPGrid::drawSubGridLines(), QCPBars::getBarPolygon(), QCPGraph::getChannelFillPolygon(), QCPCurve::getCurveData(), QCPGraph::getImpulsePlotData(), QCPGraph::getLinePlotData(), QCPBarsGroup::getPixelSpacing(), QCPGraph::getPreparedData(), QCPGraph::getStepCenterPlotData(), QCPGraph::getStepLeftPlotData(), QCPGraph::getStepRightPlotData(), QCPGraph::lowerFillBasePoint(), QCPFinancial::ohlcSelectTest(), QCPAbstractPlottable::pixelsToCoords(), pixelToCoord(), QCPAxisPainterPrivate::placeTickLabel(), QCPAbstractPlottable::QCPAbstractPlottable(), QCPColorScale::rangeDrag(), QCPColorScale::rangeZoom(), QCPColorScale::setRangeDrag(), QCPColorScale::setRangeZoom(), setScaleRatio(), QCPColorScale::setType(), QCPAxisPainterPrivate::size(), QCPColorMap::updateLegendIcon(), QCPColorMap::updateMapImage(), and QCPGraph::upperFillBasePoint().
{ return mOrientation; }
static Qt::Orientation QCPAxis::orientation (AxisType type) [inline], [static]
Returns the orientation of the specified axis type
See also
orientation()
Definition at line 1416 of file qcustomplot.h.
                                                  {
    return type == atBottom || type == atTop ? Qt::Horizontal : Qt::Vertical;
  }
int QCPAxis::padding () const [inline]
Definition at line 1325 of file qcustomplot.h.
Referenced by setLabelPadding(), setPadding(), and setTickLabelPadding().
{ return mPadding; }
double QCPAxis::pixelToCoord (double value) const
Transforms value, in pixel coordinates of the QCustomPlot widget, to axis coordinates.
Definition at line 5620 of file qcustomplot.cpp.
References QCPAxisRect::bottom(), QCPAxisRect::height(), QCPAxisRect::left(), QCPRange::lower, mAxisRect, mRange, mRangeReversed, mScaleType, orientation(), QCPRange::size(), stLinear, QCPRange::upper, and QCPAxisRect::width().
Referenced by QCPCurve::getCurveData(), QCPGraph::getPreparedData(), and QCPAbstractPlottable::pixelsToCoords().
                                               {
  if (orientation() == Qt::Horizontal) {
    if (mScaleType == stLinear) {
      if (!mRangeReversed)
        return (value - mAxisRect->left()) / (double)mAxisRect->
      width() *
                   mRange.size() +
               mRange.lower;
      else
        return -(value - mAxisRect->left()) / (double)mAxisRect->
      width() *
                   mRange.size() +
               mRange.upper;
    } else // mScaleType == stLogarithmic
    {
      if (!mRangeReversed)
        return qPow(mRange.upper / mRange.lower,
                    (value - mAxisRect->left()) / (double)mAxisRect->
      width()) *
               mRange.lower;
      else
        return qPow(mRange.upper / mRange.lower,
                    (mAxisRect->left() - value) / (double)mAxisRect->
      width()) *
               mRange.upper;
    }
  } else // orientation() == Qt::Vertical
  {
    if (mScaleType == stLinear) {
      if (!mRangeReversed)
        return (mAxisRect->bottom() - value) / (double)mAxisRect->
      height() *
                   mRange.size() +
               mRange.lower;
      else
        return -(mAxisRect->bottom() - value) / (double)mAxisRect->
      height() *
                   mRange.size() +
               mRange.upper;
    } else // mScaleType == stLogarithmic
    {
      if (!mRangeReversed)
        return qPow(mRange.upper / mRange.lower,
                    (mAxisRect->bottom() - value) /
                        (double)mAxisRect->height()) *
               mRange.lower;
      else
        return qPow(mRange.upper / mRange.lower,
                    (value - mAxisRect->bottom()) /
                        (double)mAxisRect->height()) *
               mRange.upper;
    }
  }
}
QList< QCPAbstractPlottable * > QCPAxis::plottables () const
Returns a list of all the plottables that have this axis as key or value axis.
If you are only interested in plottables of type QCPGraph, see graphs.
See also
graphs, items
Definition at line 5787 of file qcustomplot.cpp.
References i, QCPLayerable::mParentPlot, and QCustomPlot::mPlottables.
Referenced by rescale().
                                                        {
  QList<QCPAbstractPlottable *> result;
  if (!mParentPlot)
    return result;
  for (int i = 0; i < mParentPlot->mPlottables.size(); ++
      i) {
    if (mParentPlot->mPlottables.at(i)->keyAxis() == this ||
        mParentPlot->mPlottables.at(i)->valueAxis() == this)
      result.append(mParentPlot->mPlottables.at(i));
  }
  return result;
}
const QCPRange QCPAxis::range () const [inline]
Definition at line 1291 of file qcustomplot.h.
Referenced by QCPGrid::drawGridLines(), QCPCurve::getCurveData(), QCPGraph::getPreparedData(), QCPGraph::lowerFillBasePoint(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), setScaleRatio(), QCPAxisRect::setupFullAxesBox(), and QCPGraph::upperFillBasePoint().
{ return mRange; }
void QCPAxis::rangeChanged (const QCPRange & newRange) [signal]
This signal is emitted when the range of this axis has changed. You can connect it to the setRange slot of another axis to communicate the new range to the other axis, in order for it to be synchronized.
You may also manipulate/correct the range with setRange in a slot connected to this signal. This is useful if for example a maximum range span shall not be exceeded, or if the lower/upper range shouldn't go beyond certain values. For example, the following slot would limit the x axis to only positive ranges:
if (newRange.lower < 0)
  plot->xAxis->setRange(0, newRange.size());
Referenced by moveRange(), scaleRange(), setRange(), setRangeLower(), and setRangeUpper().
void QCPAxis::rangeChanged (const QCPRange & newRange, const QCPRange & oldRange) [signal]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Additionally to the new range, this signal also provides the previous range held by the axis as oldRange.
bool QCPAxis::rangeReversed () const [inline]
Definition at line 1292 of file qcustomplot.h.
Referenced by QCPGraph::drawError(), QCPCurve::getCurveData(), QCPGraph::getPreparedData(), QCPGraph::lowerFillBasePoint(), QCPAxisRect::setupFullAxesBox(), and QCPGraph::upperFillBasePoint().
{ return mRangeReversed; }
void QCPAxis::rescale (bool onlyVisiblePlottables = false)
Changes the axis range such that all plottables associated with this axis are fully visible in that dimension.
See also
QCPAbstractPlottable::rescaleAxes, QCustomPlot::rescaleAxes
Definition at line 5567 of file qcustomplot.cpp.
References QCPRange::expand(), i, QCPRange::lower, mRange, mScaleType, plottables(), QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, setRange(), QCPRange::size(), stLinear, stLogarithmic, QCPRange::upper, and QCPRange::validRange().
Referenced by QCustomPlot::rescaleAxes().
                                                {
  QList<QCPAbstractPlottable *> p = plottables();
  QCPRange newRange;
  bool haveRange = false;
  for (int i = 0; i < p.size(); ++i) {
    if (!p.at(i)->realVisibility() && onlyVisiblePlottables)
      continue;
    QCPRange plottableRange;
    bool currentFoundRange;
    QCPAbstractPlottable::SignDomain signDomain =
      QCPAbstractPlottable::sdBoth;
    if (mScaleType == stLogarithmic)
      signDomain = (mRange.upper < 0 ?
      QCPAbstractPlottable::sdNegative
                                     : QCPAbstractPlottable::sdPositive);
    if (p.at(i)->keyAxis() == this)
      plottableRange = p.at(i)->getKeyRange(currentFoundRange, signDomain);
    else
      plottableRange = p.at(i)->getValueRange(currentFoundRange, signDomain);
    if (currentFoundRange) {
      if (!haveRange)
        newRange = plottableRange;
      else
        newRange.expand(plottableRange);
      haveRange = true;
    }
  }
  if (haveRange) {
    if (!QCPRange::validRange(newRange)) // likely due to range being zero
                                         // (plottable has only constant data in
                                         // this axis dimension), shift current
                                         // range to at least center the
                                         // plottable
    {
      double center = (newRange.lower + newRange.upper) *
                      0.5; // upper and lower should be equal anyway, but just
                           // to make sure, incase validRange returned false for
                           // other reason
      if (mScaleType == stLinear) {
        newRange.lower = center - mRange.size() / 2.0;
        newRange.upper = center + mRange.size() / 2.0;
      } else // mScaleType == stLogarithmic
      {
        newRange.lower = center / qSqrt(mRange.upper / mRange.
      lower);
        newRange.upper = center * qSqrt(mRange.upper / mRange.
      lower);
      }
    }
    setRange(newRange);
  }
}
double QCPAxis::scaleLogBase () const [inline]
Definition at line 1290 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mScaleLogBase; }
void QCPAxis::scaleRange (double factor, double center)
Scales the range of this axis by factor around the coordinate center. For example, if factor is 2.0, center is 1.0, then the axis range will double its size, and the point at coordinate 1.0 won't have changed its position in the QCustomPlot widget (i.e. coordinates around 1.0 will have moved symmetrically closer to 1.0).
Definition at line 5494 of file qcustomplot.cpp.
References QCPRange::lower, mCachedMarginValid, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), stLinear, QCPRange::upper, and QCPRange::validRange().
                                                     {
  QCPRange oldRange = mRange;
  if (mScaleType == stLinear) {
    QCPRange newRange;
    newRange.lower = (mRange.lower - center) * factor + center;
    newRange.upper = (mRange.upper - center) * factor + center;
    if (QCPRange::validRange(newRange))
      mRange = newRange.sanitizedForLinScale();
  } else // mScaleType == stLogarithmic
  {
    if ((mRange.upper < 0 && center < 0) ||
        (mRange.upper > 0 &&
         center > 0)) // make sure center has same sign as range
    {
      QCPRange newRange;
      newRange.lower = qPow(mRange.lower / center, factor) * center;
      newRange.upper = qPow(mRange.upper / center, factor) * center;
      if (QCPRange::validRange(newRange))
        mRange = newRange.sanitizedForLogScale();
    } else
      qDebug() << Q_FUNC_INFO
               << "Center of scaling operation doesn't lie in same logarithmic "
                  "sign domain as range:" << center;
  }
  mCachedMarginValid = false;
  emit rangeChanged(mRange);
  emit rangeChanged(mRange, oldRange);
}
ScaleType QCPAxis::scaleType () const [inline]
Definition at line 1289 of file qcustomplot.h.
Referenced by QCPGraph::getPreparedData(), QCPGraph::lowerFillBasePoint(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), QCPAxisRect::setupFullAxesBox(), and QCPGraph::upperFillBasePoint().
{ return mScaleType; }
void QCPAxis::scaleTypeChanged (QCPAxis::ScaleType scaleType) [signal]
This signal is emitted when the scale type changes, by calls to setScaleType
Referenced by setScaleType().
void QCPAxis::selectableChanged (const QCPAxis::SelectableParts & parts) [signal]
This signal is emitted when the selectability changes, by calls to setSelectableParts
Referenced by setSelectableParts().
SelectableParts QCPAxis::selectableParts () const [inline]
Definition at line 1328 of file qcustomplot.h.
Referenced by QCPColorScaleAxisRectPrivate::axisSelectableChanged(), and QCPColorScaleAxisRectPrivate::axisSelectionChanged().
{ return mSelectableParts; }
QPen QCPAxis::selectedBasePen () const [inline]
Definition at line 1333 of file qcustomplot.h.
{ return mSelectedBasePen; }
QColor QCPAxis::selectedLabelColor () const [inline]
Definition at line 1332 of file qcustomplot.h.
{ return mSelectedLabelColor; }
QFont QCPAxis::selectedLabelFont () const [inline]
Definition at line 1330 of file qcustomplot.h.
{ return mSelectedLabelFont; }
SelectableParts QCPAxis::selectedParts () const [inline]
Definition at line 1327 of file qcustomplot.h.
Referenced by QCustomPlot::selectedAxes().
{ return mSelectedParts; }
QPen QCPAxis::selectedSubTickPen () const [inline]
Definition at line 1335 of file qcustomplot.h.
{ return mSelectedSubTickPen; }
QColor QCPAxis::selectedTickLabelColor () const [inline]
Definition at line 1331 of file qcustomplot.h.
{ return mSelectedTickLabelColor; }
QFont QCPAxis::selectedTickLabelFont () const [inline]
Definition at line 1329 of file qcustomplot.h.
{ return mSelectedTickLabelFont; }
QPen QCPAxis::selectedTickPen () const [inline]
Definition at line 1334 of file qcustomplot.h.
{ return mSelectedTickPen; }
void QCPAxis::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 6199 of file qcustomplot.cpp.
References mSelectableParts, mSelectedParts, and setSelectedParts().
                                                       {
  Q_UNUSED(event)
  SelectablePart part = details.value<SelectablePart>();
  if (mSelectableParts.testFlag(part)) {
    SelectableParts selBefore = mSelectedParts;
    setSelectedParts(additive ? mSelectedParts ^ part : part);
    if (selectionStateChanged)
      *selectionStateChanged = mSelectedParts != selBefore;
  }
}
QCP::Interaction QCPAxis::selectionCategory () const [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 6516 of file qcustomplot.cpp.
References QCP::iSelectAxes.
{ return QCP::iSelectAxes; }
void QCPAxis::selectionChanged (const QCPAxis::SelectableParts & parts) [signal]
This signal is emitted when the selection state of this axis has changed, either by user interaction or by a direct call to setSelectedParts.
Referenced by setSelectedParts().
double QCPAxis::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented from QCPLayerable.
Definition at line 5767 of file qcustomplot.cpp.
References getPartAt(), QCPLayerable::mParentPlot, mSelectableParts, QCustomPlot::selectionTolerance(), and spNone.
                                                    {
  if (!mParentPlot)
    return -1;
  SelectablePart part = getPartAt(pos);
  if ((onlySelectable && !mSelectableParts.testFlag(part)) || part ==
      spNone)
    return -1;
  if (details)
    details->setValue(part);
  return mParentPlot->selectionTolerance() * 0.99;
}
void QCPAxis::setAutoSubTicks (bool on)
Sets whether the number of sub ticks in one tick interval is determined automatically. This works, as long as the tick step mantissa is a multiple of 0.5. When setAutoTickStep is enabled, this is always the case.
When on is set to false, you may set the sub tick count with setSubTickCount manually.
See also
setAutoTickCount, setAutoTicks, setAutoTickStep
Definition at line 4778 of file qcustomplot.cpp.
References mAutoSubTicks, and mCachedMarginValid.
Referenced by QCPAxisRect::setupFullAxesBox().
                                     {
  if (mAutoSubTicks != on) {
    mAutoSubTicks = on;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setAutoTickCount (int approximateCount)
When setAutoTickStep is true, approximateCount determines how many ticks should be generated in the visible range, approximately.
It's not guaranteed that this number of ticks is met exactly, but approximately within a tolerance of about two.
Only values greater than zero are accepted as approximateCount.
See also
setAutoTickStep, setAutoTicks, setAutoSubTicks
Definition at line 4703 of file qcustomplot.cpp.
References mAutoTickCount, and mCachedMarginValid.
Referenced by QCPAxisRect::setupFullAxesBox().
                                                   {
  if (mAutoTickCount != approximateCount) {
    if (approximateCount > 0) {
      mAutoTickCount = approximateCount;
      mCachedMarginValid = false;
    } else
      qDebug() << Q_FUNC_INFO << "approximateCount must be greater than zero:"
               << approximateCount;
  }
}
void QCPAxis::setAutoTickLabels (bool on)
Sets whether the tick labels are generated automatically. Depending on the tick label type (ltNumber or ltDateTime), the labels will either show the coordinate as floating point number (setNumberFormat), or a date/time formatted according to setDateTimeFormat.
If on is set to false, you should provide the tick labels via setTickVectorLabels. This is usually used in a combination with setAutoTicks set to false for complete control over tick positions and labels, e.g. when the ticks should be at multiples of pi and show `2pi`, `3pi` etc. as tick labels.
If you need dynamically calculated tick vectors (and possibly tick label vectors), set the vectors in a slot connected to the ticksRequest signal.
See also
setAutoTicks
Definition at line 4736 of file qcustomplot.cpp.
References mAutoTickLabels, and mCachedMarginValid.
                                       {
  if (mAutoTickLabels != on) {
    mAutoTickLabels = on;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setAutoTicks (bool on)
Sets whether the tick positions should be calculated automatically (either from an automatically generated tick step or a tick step provided manually via setTickStep, see setAutoTickStep).
If on is set to false, you must provide the tick positions manually via setTickVector. For these manual ticks you may let QCPAxis generate the appropriate labels automatically by leaving setAutoTickLabels set to true. If you also wish to control the displayed labels manually, set setAutoTickLabels to false and provide the label strings with setTickVectorLabels.
If you need dynamically calculated tick vectors (and possibly tick label vectors), set the vectors in a slot connected to the ticksRequest signal.
See also
setAutoTickLabels, setAutoSubTicks, setAutoTickCount, setAutoTickStep
Definition at line 4683 of file qcustomplot.cpp.
References mAutoTicks, and mCachedMarginValid.
                                  {
  if (mAutoTicks != on) {
    mAutoTicks = on;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setAutoTickStep (bool on)
Sets whether the tick step, i.e. the interval between two (major) ticks, is calculated automatically. If on is set to true, the axis finds a tick step that is reasonable for human readable plots.
The number of ticks the algorithm aims for within the visible range can be specified with setAutoTickCount.
If on is set to false, you may set the tick step manually with setTickStep.
See also
setAutoTicks, setAutoSubTicks, setAutoTickCount
Definition at line 4759 of file qcustomplot.cpp.
References mAutoTickStep, and mCachedMarginValid.
Referenced by QCPAxisRect::setupFullAxesBox().
                                     {
  if (mAutoTickStep != on) {
    mAutoTickStep = on;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setBasePen (const QPen & pen)
Sets the pen, the axis base line is drawn with.
See also
setTickPen, setSubTickPen
Definition at line 5261 of file qcustomplot.cpp.
References mBasePen.
{ mBasePen = pen; }
void QCPAxis::setDateTimeFormat (const QString & format)
Sets the format in which dates and times are displayed as tick labels, if setTickLabelType is ltDateTime. for details about the format string, see the documentation of QDateTime::toString().
Newlines can be inserted with `\n`.
See also
setDateTimeSpec
Definition at line 4930 of file qcustomplot.cpp.
References mCachedMarginValid, and mDateTimeFormat.
Referenced by QCPAxisRect::setupFullAxesBox().
                                                     {
  if (mDateTimeFormat != format) {
    mDateTimeFormat = format;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setDateTimeSpec (const Qt::TimeSpec & timeSpec)
Sets the time spec that is used for the date time values when setTickLabelType is ltDateTime.
The default value of QDateTime objects (and also QCustomPlot) is Qt::LocalTime. However, if the date time values passed to QCustomPlot are given in the UTC spec, set timeSpec to Qt::UTC to get the correct axis labels.
See also
setDateTimeFormat
Definition at line 4950 of file qcustomplot.cpp.
References mDateTimeSpec.
Referenced by QCPAxisRect::setupFullAxesBox().
                                                        {
  mDateTimeSpec = timeSpec;
}
void QCPAxis::setLabel (const QString & str)
Sets the text of the axis label that will be shown below/above or next to the axis, depending on its orientation. To disable axis labels, pass an empty string as str.
Definition at line 5301 of file qcustomplot.cpp.
References mCachedMarginValid, and mLabel.
                                         {
  if (mLabel != str) {
    mLabel = str;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setLabelColor (const QColor & color)
Sets the color of the axis label.
See also
setLabelFont
Definition at line 5294 of file qcustomplot.cpp.
References mLabelColor.
{ mLabelColor = color; }
void QCPAxis::setLabelFont (const QFont & font)
Sets the font of the axis label.
See also
setLabelColor
Definition at line 5282 of file qcustomplot.cpp.
References mCachedMarginValid, and mLabelFont.
                                            {
  if (mLabelFont != font) {
    mLabelFont = font;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setLabelPadding (int padding)
Sets the distance between the tick labels and the axis label.
See also
setTickLabelPadding, setPadding
Definition at line 5313 of file qcustomplot.cpp.
References QCPAxisPainterPrivate::labelPadding, mAxisPainter, mCachedMarginValid, and padding().
Referenced by QCPAxis().
                                         {
  if (mAxisPainter->labelPadding != padding) {
    mAxisPainter->labelPadding = padding;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setLowerEnding (const QCPLineEnding & ending)
Sets the style for the lower axis ending. See the documentation of QCPLineEnding for available styles.
For horizontal axes, this method refers to the left ending, for vertical axes the bottom ending. Note that this meaning does not change when the axis range is reversed with setRangeReversed.
See also
setUpperEnding
Definition at line 5439 of file qcustomplot.cpp.
References QCPAxisPainterPrivate::lowerEnding, and mAxisPainter.
Referenced by QCPAxisRect::addAxis().
                                                        {
  mAxisPainter->lowerEnding = ending;
}
void QCPAxis::setNumberFormat (const QString & formatCode)
Sets the number format for the numbers drawn as tick labels (if tick label type is ltNumber). This formatCode is an extended version of the format code used e.g. by QString::number() and QLocale::toString(). For reference about that, see the `Argument Formats` section in the detailed description of the QString class. formatCode is a string of one, two or three characters. The first character is identical to the normal format code used by Qt. In short, this means: 'e'/'E' scientific format, 'f' fixed format, 'g'/'G' scientific or fixed, whichever is shorter.
The second and third characters are optional and specific to QCustomPlot:
If the first char was 'e' or 'g', numbers are/might be displayed in the scientific format, e.g. `5.5e9`, which is ugly in a plot. So when the second char of formatCode is set to 'b' (for `beautiful`), those exponential numbers are formatted in a more natural way, i.e. `5.5
[multiplication sign] 10 [superscript] 9`. By default, the multiplication sign is a centered dot. If instead a cross should be shown (as is usual in the USA), the third char of formatCode can be set to 'c'. The inserted multiplication signs are the UTF-8 characters 215 (0xD7) for the cross and 183 (0xB7) for the dot.
If the scale type (setScaleType) is stLogarithmic and the formatCode uses the 'b' option (beautifully typeset decimal powers), the display usually is "1 [multiplication sign] 10 [superscript] n`, which looks unnatural for logarithmic scaling (the `1 [multiplication sign]" part). To only display the decimal power, set the number precision to zero with setNumberPrecision.
Examples for formatCode:
g normal format code behaviour. If number is small, fixed format is used, if number is large, normal scientific format is used
gb If number is small, fixed format is used, if number is large, scientific format is used with beautifully typeset decimal powers and a dot as multiplication sign
ebc All numbers are in scientific format with beautifully typeset decimal power and a cross as multiplication sign
fb illegal format code, since fixed format doesn't support (or need) beautifully typeset decimal powers. Format code will be reduced to 'f'.
hello illegal format code, since first char is not 'e', 'E', 'f', 'g' or 'G'. Current format code will not be changed.
Definition at line 5011 of file qcustomplot.cpp.
References mAxisPainter, mCachedMarginValid, mNumberBeautifulPowers, mNumberFormatChar, and QCPAxisPainterPrivate::numberMultiplyCross.
Referenced by QCPAxisRect::setupFullAxesBox().
                                                       {
  if (formatCode.isEmpty()) {
    qDebug() << Q_FUNC_INFO << "Passed formatCode is empty";
    return;
  }
  mCachedMarginValid = false;
  // interpret first char as number format char:
  QString allowedFormatChars(QLatin1String("eEfgG"));
  if (allowedFormatChars.contains(formatCode.at(0))) {
    mNumberFormatChar = QLatin1Char(formatCode.at(0).toLatin1());
  } else {
    qDebug() << Q_FUNC_INFO
             << "Invalid number format code (first char not in 'eEfgG'):"
             << formatCode;
    return;
  }
  if (formatCode.length() < 2) {
    mNumberBeautifulPowers = false;
    mAxisPainter->numberMultiplyCross = false;
    return;
  }
  // interpret second char as indicator for beautiful decimal powers:
  if (formatCode.at(1) == QLatin1Char('b') &&
      (mNumberFormatChar == QLatin1Char('e') ||
       mNumberFormatChar == QLatin1Char('g'))) {
    mNumberBeautifulPowers = true;
  } else {
    qDebug() << Q_FUNC_INFO
             << "Invalid number format code (second char not 'b' or first char "
                "neither 'e' nor 'g'):" << formatCode;
    return;
  }
  if (formatCode.length() < 3) {
    mAxisPainter->numberMultiplyCross = false;
    return;
  }
  // interpret third char as indicator for dot or cross multiplication symbol:
  if (formatCode.at(2) == QLatin1Char('c')) {
    mAxisPainter->numberMultiplyCross = true;
  } else if (formatCode.at(2) == QLatin1Char('d')) {
    mAxisPainter->numberMultiplyCross = false;
  } else {
    qDebug() << Q_FUNC_INFO
             << "Invalid number format code (third char neither 'c' nor 'd'):"
             << formatCode;
    return;
  }
}
void QCPAxis::setNumberPrecision (int precision)
Sets the precision of the tick label numbers. See QLocale::toString(double i, char f, int prec) for details. The effect of precisions are most notably for number Formats starting with 'e', see setNumberFormat
If the scale type (setScaleType) is stLogarithmic and the number format (setNumberFormat) uses the 'b' format code (beautifully typeset decimal powers), the display usually is `1 [multiplication sign] 10 [superscript] n`, which looks unnatural for logarithmic scaling (the redundant `1 [multiplication sign]` part). To only display the decimal power `10
[superscript] n`, set precision to zero.
Definition at line 5080 of file qcustomplot.cpp.
References mCachedMarginValid, and mNumberPrecision.
Referenced by QCPAxisRect::setupFullAxesBox().
                                              {
  if (mNumberPrecision != precision) {
    mNumberPrecision = precision;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setOffset (int offset)
Sets the offset the axis has to its axis rect side.
If an axis rect side has multiple axes and automatic margin calculation is enabled for that side, only the offset of the inner most axis has meaning (even if it is set to be invisible). The offset of the other, outer axes is controlled automatically, to place them at appropriate positions.
Definition at line 5350 of file qcustomplot.cpp.
References mAxisPainter, offset(), and QCPAxisPainterPrivate::offset.
{ mAxisPainter->offset = offset; }
void QCPAxis::setPadding (int padding)
Sets the padding of the axis.
When QCPAxisRect::setAutoMargins is enabled, the padding is the additional outer most space, that is left blank.
The axis padding has no meaning if QCPAxisRect::setAutoMargins is disabled.
See also
setLabelPadding, setTickLabelPadding
Definition at line 5332 of file qcustomplot.cpp.
References mCachedMarginValid, mPadding, and padding().
Referenced by QCPColorScaleAxisRectPrivate::QCPColorScaleAxisRectPrivate().
                                    {
  if (mPadding != padding) {
    mPadding = padding;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setRange (const QCPRange & range)
Sets the range of the axis.
This slot may be connected with the rangeChanged signal of another axis so this axis is always synchronized with the other axis range, when it changes.
To invert the direction of an axis, use setRangeReversed.
Definition at line 4483 of file qcustomplot.cpp.
References QCPRange::lower, mCachedMarginValid, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), stLogarithmic, QCPRange::upper, and QCPRange::validRange().
Referenced by rescale(), QCPAbstractPlottable::rescaleKeyAxis(), QCPGraph::rescaleKeyAxis(), QCPAbstractPlottable::rescaleValueAxis(), QCPGraph::rescaleValueAxis(), setRange(), setScaleRatio(), setScaleType(), and QCPAxisRect::setupFullAxesBox().
                                            {
  if (range.lower == mRange.lower && range.upper == mRange.
      upper)
    return;
  if (!QCPRange::validRange(range))
    return;
  QCPRange oldRange = mRange;
  if (mScaleType == stLogarithmic) {
    mRange = range.sanitizedForLogScale();
  } else {
    mRange = range.sanitizedForLinScale();
  }
  mCachedMarginValid = false;
  emit rangeChanged(mRange);
  emit rangeChanged(mRange, oldRange);
}
void QCPAxis::setRange (double lower, double upper)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the lower and upper bound of the axis range.
To invert the direction of an axis, use setRangeReversed.
There is also a slot to set a range, see setRange(const QCPRange &range).
Definition at line 4557 of file qcustomplot.cpp.
References QCPRange::lower, mCachedMarginValid, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), stLogarithmic, QCPRange::upper, and QCPRange::validRange().
                                                 {
  if (lower == mRange.lower && upper == mRange.upper)
    return;
  if (!QCPRange::validRange(lower, upper))
    return;
  QCPRange oldRange = mRange;
  mRange.lower = lower;
  mRange.upper = upper;
  if (mScaleType == stLogarithmic) {
    mRange = mRange.sanitizedForLogScale();
  } else {
    mRange = mRange.sanitizedForLinScale();
  }
  mCachedMarginValid = false;
  emit rangeChanged(mRange);
  emit rangeChanged(mRange, oldRange);
}
void QCPAxis::setRange (double position, double size, Qt::AlignmentFlag alignment)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the range of the axis.
The position coordinate indicates together with the alignment parameter, where the new range will be positioned. size defines the size of the new axis range. alignment may be Qt::AlignLeft, Qt::AlignRight or Qt::AlignCenter. This will cause the left border, right border, or center of the range to be aligned with position. Any other values of alignment will default to Qt::AlignCenter.
Definition at line 4591 of file qcustomplot.cpp.
References setRange().
                                                  {
  if (alignment == Qt::AlignLeft)
    setRange(position, position + size);
  else if (alignment == Qt::AlignRight)
    setRange(position - size, position);
  else // alignment == Qt::AlignCenter
    setRange(position - size / 2.0, position + size / 2.0);
}
void QCPAxis::setRangeLower (double lower)
Sets the lower bound of the axis range. The upper bound is not changed.
See also
setRange
Definition at line 4605 of file qcustomplot.cpp.
References QCPRange::lower, mCachedMarginValid, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), and stLogarithmic.
                                        {
  if (mRange.lower == lower)
    return;
  QCPRange oldRange = mRange;
  mRange.lower = lower;
  if (mScaleType == stLogarithmic) {
    mRange = mRange.sanitizedForLogScale();
  } else {
    mRange = mRange.sanitizedForLinScale();
  }
  mCachedMarginValid = false;
  emit rangeChanged(mRange);
  emit rangeChanged(mRange, oldRange);
}
void QCPAxis::setRangeReversed (bool reversed)
Sets whether the axis range (direction) is displayed reversed. Normally, the values on horizontal axes increase left to right, on vertical axes bottom to top. When reversed is set to true, the direction of increasing values is inverted.
Note that the range and data interface stays the same for reversed axes, e.g. the lower part of the setRange interface will still reference the mathematically smaller number than the upper part.
Definition at line 4654 of file qcustomplot.cpp.
References mCachedMarginValid, and mRangeReversed.
Referenced by QCPAxisRect::setupFullAxesBox().
                                            {
  if (mRangeReversed != reversed) {
    mRangeReversed = reversed;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setRangeUpper (double upper)
Sets the upper bound of the axis range. The lower bound is not changed.
See also
setRange
Definition at line 4625 of file qcustomplot.cpp.
References mCachedMarginValid, mRange, mScaleType, rangeChanged(), QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), stLogarithmic, and QCPRange::upper.
                                        {
  if (mRange.upper == upper)
    return;
  QCPRange oldRange = mRange;
  mRange.upper = upper;
  if (mScaleType == stLogarithmic) {
    mRange = mRange.sanitizedForLogScale();
  } else {
    mRange = mRange.sanitizedForLinScale();
  }
  mCachedMarginValid = false;
  emit rangeChanged(mRange);
  emit rangeChanged(mRange, oldRange);
}
void QCPAxis::setScaleLogBase (double base)
If setScaleType is set to stLogarithmic, base will be the logarithm base of the scaling. In logarithmic axis scaling, major tick marks appear at all powers of base.
Properties like tick step (setTickStep) don't apply in logarithmic scaling. If you wish a decimal base but less major ticks, consider choosing base 100, 1000 or even higher.
Definition at line 4463 of file qcustomplot.cpp.
References mCachedMarginValid, mScaleLogBase, and mScaleLogBaseLogInv.
Referenced by QCPAxisRect::setupFullAxesBox().
                                         {
  if (base > 1) {
    mScaleLogBase = base;
    mScaleLogBaseLogInv =
        1.0 / qLn(mScaleLogBase); // buffer for faster baseLog() calculation
    mCachedMarginValid = false;
  } else
    qDebug() << Q_FUNC_INFO
             << "Invalid logarithmic scale base (must be greater 1):" << base;
}
void QCPAxis::setScaleRatio (const QCPAxis * otherAxis, double ratio = 1.0)
Scales the range of this axis to have a certain scale ratio to otherAxis. The scaling will be done around the center of the current axis range.
For example, if ratio is 1, this axis is the yAxis and otherAxis is xAxis, graphs plotted with those axes will appear in a 1:1 aspect ratio, independent of the aspect ratio the axis rect has.
This is an operation that changes the range of this axis once, it doesn't fix the scale ratio indefinitely. Note that calling this function in the constructor of the QCustomPlot's parent won't have the desired effect, since the widget dimensions aren't defined yet, and a resizeEvent will follow.
Definition at line 5542 of file qcustomplot.cpp.
References axisRect(), QCPAxisRect::height(), orientation(), range(), setRange(), QCPRange::size(), and QCPAxisRect::width().
                                                                  {
  int otherPixelSize, ownPixelSize;
  if (otherAxis->orientation() == Qt::Horizontal)
    otherPixelSize = otherAxis->axisRect()->width();
  else
    otherPixelSize = otherAxis->axisRect()->height();
  if (orientation() == Qt::Horizontal)
    ownPixelSize = axisRect()->width();
  else
    ownPixelSize = axisRect()->height();
  double newRangeSize =
      ratio * otherAxis->range().size() * ownPixelSize / (double)otherPixelSize;
  setRange(range().center(), newRangeSize, Qt::AlignCenter);
}
void QCPAxis::setScaleType (QCPAxis::ScaleType type)
Sets whether the axis uses a linear scale or a logarithmic scale. If type is set to stLogarithmic, the logarithm base can be set with setScaleLogBase. In logarithmic axis scaling, major tick marks appear at all powers of the logarithm base. Properties like tick step (setTickStep) don't apply in logarithmic scaling. If you wish a decimal base but less major ticks, consider choosing a logarithm base of 100, 1000 or even higher.
If type is stLogarithmic and the number format (setNumberFormat) uses the 'b' option (beautifully typeset decimal powers), the display usually is "1 [multiplication sign] 10 [superscript] n`, which looks unnatural for logarithmic scaling (the `1 [multiplication sign]" part). To only display the decimal power, set the number precision to zero with setNumberPrecision.
Definition at line 4443 of file qcustomplot.cpp.
References mCachedMarginValid, mRange, mScaleType, QCPRange::sanitizedForLogScale(), scaleTypeChanged(), setRange(), and stLogarithmic.
Referenced by QCPAxisRect::setupFullAxesBox().
                                                {
  if (mScaleType != type) {
    mScaleType = type;
    if (mScaleType == stLogarithmic)
      setRange(mRange.sanitizedForLogScale());
    mCachedMarginValid = false;
    emit scaleTypeChanged(mScaleType);
  }
}
void QCPAxis::setSelectableParts (const QCPAxis::SelectableParts & selectableParts)
Sets whether the user can (de-)select the parts in selectable by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains iSelectAxes.)
However, even when selectable is set to a value not allowing the selection of a specific part, it is still possible to set the selection of this part manually, by calling setSelectedParts directly.
See also
SelectablePart, setSelectedParts
Definition at line 4513 of file qcustomplot.cpp.
References mSelectableParts, and selectableChanged().
Referenced by QCPColorScaleAxisRectPrivate::axisSelectableChanged().
                                                                  {
  if (mSelectableParts != selectable) {
    mSelectableParts = selectable;
    emit selectableChanged(mSelectableParts);
  }
}
void QCPAxis::setSelectedBasePen (const QPen & pen)
Sets the pen that is used to draw the axis base line when selected.
See also
setBasePen, setSelectableParts, setSelectedParts, QCustomPlot::setInteractions
Definition at line 5406 of file qcustomplot.cpp.
References mSelectedBasePen.
{ mSelectedBasePen = pen; }
void QCPAxis::setSelectedLabelColor (const QColor & color)
Sets the color that is used for the axis label when it is selected.
See also
setLabelColor, setSelectableParts, setSelectedParts, QCustomPlot::setInteractions
Definition at line 5396 of file qcustomplot.cpp.
References mSelectedLabelColor.
                                                       {
  mSelectedLabelColor = color;
}
void QCPAxis::setSelectedLabelFont (const QFont & font)
Sets the font that is used for the axis label when it is selected.
See also
setLabelFont, setSelectableParts, setSelectedParts, QCustomPlot::setInteractions
Definition at line 5372 of file qcustomplot.cpp.
References mSelectedLabelFont.
                                                    {
  mSelectedLabelFont = font;
  // don't set mCachedMarginValid to false here because margin calculation is
  // always done with non-selected fonts
}
void QCPAxis::setSelectedParts (const QCPAxis::SelectableParts & selectedParts)
Sets the selected state of the respective axis parts described by SelectablePart. When a part is selected, it uses a different pen/font.
The entire selection mechanism for axes is handled automatically when QCustomPlot::setInteractions contains iSelectAxes. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state of a part, independent of the setSelectableParts setting.
emits the selectionChanged signal when selected is different from the previous selection state.
See also
SelectablePart, setSelectableParts, selectTest, setSelectedBasePen, setSelectedTickPen, setSelectedSubTickPen, setSelectedTickLabelFont, setSelectedLabelFont, setSelectedTickLabelColor, setSelectedLabelColor
Definition at line 4541 of file qcustomplot.cpp.
References mSelectedParts, and selectionChanged().
Referenced by QCPColorScaleAxisRectPrivate::axisSelectionChanged(), deselectEvent(), and selectEvent().
                                                              {
  if (mSelectedParts != selected) {
    mSelectedParts = selected;
    emit selectionChanged(mSelectedParts);
  }
}
void QCPAxis::setSelectedSubTickPen (const QPen & pen)
Sets the pen that is used to draw the subticks when selected.
See also
setSubTickPen, setSelectableParts, setSelectedParts, QCustomPlot::setInteractions
Definition at line 5422 of file qcustomplot.cpp.
References mSelectedSubTickPen.
                                                   {
  mSelectedSubTickPen = pen;
}
void QCPAxis::setSelectedTickLabelColor (const QColor & color)
Sets the color that is used for tick labels when they are selected.
See also
setTickLabelColor, setSelectableParts, setSelectedParts, QCustomPlot::setInteractions
Definition at line 5384 of file qcustomplot.cpp.
References mSelectedTickLabelColor.
                                                           {
  if (color != mSelectedTickLabelColor) {
    mSelectedTickLabelColor = color;
  }
}
void QCPAxis::setSelectedTickLabelFont (const QFont & font)
Sets the font that is used for tick labels when they are selected.
See also
setTickLabelFont, setSelectableParts, setSelectedParts, QCustomPlot::setInteractions
Definition at line 5358 of file qcustomplot.cpp.
References mSelectedTickLabelFont.
                                                        {
  if (font != mSelectedTickLabelFont) {
    mSelectedTickLabelFont = font;
    // don't set mCachedMarginValid to false here because margin calculation is
    // always done with non-selected fonts
  }
}
void QCPAxis::setSelectedTickPen (const QPen & pen)
Sets the pen that is used to draw the (major) ticks when selected.
See also
setTickPen, setSelectableParts, setSelectedParts, QCustomPlot::setInteractions
Definition at line 5414 of file qcustomplot.cpp.
References mSelectedTickPen.
{ mSelectedTickPen = pen; }
void QCPAxis::setSubTickCount (int count)
Sets the number of sub ticks in one (major) tick step. A sub tick count of three for example, divides the tick intervals in four sub intervals.
By default, the number of sub ticks is chosen automatically in a reasonable manner as long as the mantissa of the tick step is a multiple of 0.5. When setAutoTickStep is enabled, this is always the case.
If you want to disable automatic sub tick count and use this function to set the count manually, see setAutoSubTicks.
Definition at line 5209 of file qcustomplot.cpp.
References count, and mSubTickCount.
Referenced by QCPAxisRect::setupFullAxesBox().
{ mSubTickCount = count; }
void QCPAxis::setSubTickLength (int inside, int outside = 0)
Sets the length of the subticks in pixels. inside is the length the subticks will reach inside the plot and outside is the length they will reach outside the plot. If outside is greater than zero, the tick labels and axis label will increase their distance to the axis accordingly, so they won't collide with the ticks.
See also
setTickLength, setSubTickLengthIn, setSubTickLengthOut
Definition at line 5222 of file qcustomplot.cpp.
References setSubTickLengthIn(), and setSubTickLengthOut().
                                                      {
  setSubTickLengthIn(inside);
  setSubTickLengthOut(outside);
}
void QCPAxis::setSubTickLengthIn (int inside)
Sets the length of the inward subticks in pixels. inside is the length the subticks will reach inside the plot.
See also
setSubTickLengthOut, setSubTickLength, setTickLength
Definition at line 5234 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::subTickLengthIn.
Referenced by setSubTickLength().
                                           {
  if (mAxisPainter->subTickLengthIn != inside) {
    mAxisPainter->subTickLengthIn = inside;
  }
}
void QCPAxis::setSubTickLengthOut (int outside)
Sets the length of the outward subticks in pixels. outside is the length the subticks will reach outside the plot. If outside is greater than zero, the tick labels will increase their distance to the axis accordingly, so they won't collide with the ticks.
See also
setSubTickLengthIn, setSubTickLength, setTickLength
Definition at line 5249 of file qcustomplot.cpp.
References mAxisPainter, mCachedMarginValid, and QCPAxisPainterPrivate::subTickLengthOut.
Referenced by setSubTickLength().
                                             {
  if (mAxisPainter->subTickLengthOut != outside) {
    mAxisPainter->subTickLengthOut = outside;
    mCachedMarginValid = false; // only outside tick length can change margin
  }
}
void QCPAxis::setSubTickPen (const QPen & pen)
Sets the pen, subtick marks will be drawn with.
See also
setSubTickCount, setSubTickLength, setBasePen
Definition at line 5275 of file qcustomplot.cpp.
References mSubTickPen.
{ mSubTickPen = pen; }
void QCPAxis::setTickLabelColor (const QColor & color)
Sets the color of the tick labels.
See also
setTickLabels, setTickLabelFont
Definition at line 4878 of file qcustomplot.cpp.
References mCachedMarginValid, and mTickLabelColor.
                                                   {
  if (color != mTickLabelColor) {
    mTickLabelColor = color;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickLabelFont (const QFont & font)
Sets the font of the tick labels.
See also
setTickLabels, setTickLabelColor
Definition at line 4866 of file qcustomplot.cpp.
References mCachedMarginValid, and mTickLabelFont.
                                                {
  if (font != mTickLabelFont) {
    mTickLabelFont = font;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickLabelPadding (int padding)
Sets the distance between the axis base line (including any outward ticks) and the tick labels.
See also
setLabelPadding, setPadding
Definition at line 4815 of file qcustomplot.cpp.
References mAxisPainter, mCachedMarginValid, padding(), and QCPAxisPainterPrivate::tickLabelPadding.
Referenced by QCPAxis().
                                             {
  if (mAxisPainter->tickLabelPadding != padding) {
    mAxisPainter->tickLabelPadding = padding;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickLabelRotation (double degrees)
Sets the rotation of the tick labels. If degrees is zero, the labels are drawn normally. Else, the tick labels are drawn rotated by degrees clockwise. The specified angle is bound to values from -90 to 90 degrees.
If degrees is exactly -90, 0 or 90, the tick labels are centered on the tick coordinate. For other angles, the label is drawn with an offset such that it seems to point toward or away from the tick mark.
Definition at line 4898 of file qcustomplot.cpp.
References mAxisPainter, mCachedMarginValid, and QCPAxisPainterPrivate::tickLabelRotation.
                                                 {
  if (!qFuzzyIsNull(degrees - mAxisPainter->tickLabelRotation)) {
    mAxisPainter->tickLabelRotation = qBound(-90.0, degrees, 90.0);
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickLabels (bool show)
Sets whether tick labels are displayed. Tick labels are the numbers drawn next to tick marks.
Definition at line 4803 of file qcustomplot.cpp.
References mCachedMarginValid, and mTickLabels.
Referenced by QCPAxisRect::setupFullAxesBox().
                                     {
  if (mTickLabels != show) {
    mTickLabels = show;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickLabelSide (LabelSide side)
Sets whether the tick labels (numbers) shall appear inside or outside the axis rect.
The usual and default setting is lsOutside. Very compact plots sometimes require tick labels to be inside the axis rect, to save space. If side is set to lsInside, the tick labels appear on the inside are additionally clipped to the axis rect.
Definition at line 4915 of file qcustomplot.cpp.
References mAxisPainter, mCachedMarginValid, and QCPAxisPainterPrivate::tickLabelSide.
                                             {
  mAxisPainter->tickLabelSide = side;
  mCachedMarginValid = false;
}
void QCPAxis::setTickLabelType (LabelType type)
Sets whether the tick labels display numbers or dates/times.
If type is set to ltNumber, the format specifications of setNumberFormat apply.
If type is set to ltDateTime, the format specifications of setDateTimeFormat apply.
In QCustomPlot, date/time coordinates are double numbers representing the seconds since 1970-01-01T00:00:00 UTC. This format can be retrieved from QDateTime objects with the QDateTime::toTime_t() function. Since this only gives a resolution of one second, there is also the QDateTime::toMSecsSinceEpoch() function which returns the timespan described above in milliseconds. Divide its return value by 1000.0 to get a value with the format needed for date/time plotting, with a resolution of one millisecond.
Using the toMSecsSinceEpoch function allows dates that go back to 2nd January 4713 B.C. (represented by a negative number), unlike the toTime_t function, which works with unsigned integers and thus only goes back to 1st January 1970. So both for range and accuracy, use of toMSecsSinceEpoch()/1000.0 should be preferred as key coordinate for date/time axes.
See also
setTickLabels
Definition at line 4854 of file qcustomplot.cpp.
References mCachedMarginValid, and mTickLabelType.
Referenced by QCPAxisRect::setupFullAxesBox().
                                             {
  if (mTickLabelType != type) {
    mTickLabelType = type;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickLength (int inside, int outside = 0)
Sets the length of the ticks in pixels. inside is the length the ticks will reach inside the plot and outside is the length they will reach outside the plot. If outside is greater than zero, the tick labels and axis label will increase their distance to the axis accordingly, so they won't collide with the ticks.
See also
setSubTickLength, setTickLengthIn, setTickLengthOut
Definition at line 5159 of file qcustomplot.cpp.
References setTickLengthIn(), and setTickLengthOut().
                                                   {
  setTickLengthIn(inside);
  setTickLengthOut(outside);
}
void QCPAxis::setTickLengthIn (int inside)
Sets the length of the inward ticks in pixels. inside is the length the ticks will reach inside the plot.
See also
setTickLengthOut, setTickLength, setSubTickLength
Definition at line 5171 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::tickLengthIn.
Referenced by setTickLength().
                                        {
  if (mAxisPainter->tickLengthIn != inside) {
    mAxisPainter->tickLengthIn = inside;
  }
}
void QCPAxis::setTickLengthOut (int outside)
Sets the length of the outward ticks in pixels. outside is the length the ticks will reach outside the plot. If outside is greater than zero, the tick labels and axis label will increase their distance to the axis accordingly, so they won't collide with the ticks.
See also
setTickLengthIn, setTickLength, setSubTickLength
Definition at line 5187 of file qcustomplot.cpp.
References mAxisPainter, mCachedMarginValid, and QCPAxisPainterPrivate::tickLengthOut.
Referenced by setTickLength().
                                          {
  if (mAxisPainter->tickLengthOut != outside) {
    mAxisPainter->tickLengthOut = outside;
    mCachedMarginValid = false; // only outside tick length can change margin
  }
}
void QCPAxis::setTickPen (const QPen & pen)
Sets the pen, tick marks will be drawn with.
See also
setTickLength, setBasePen
Definition at line 5268 of file qcustomplot.cpp.
References mTickPen.
{ mTickPen = pen; }
void QCPAxis::setTicks (bool show)
Sets whether tick marks are displayed.
Note that setting show to false does not imply that tick labels are invisible, too. To achieve that, see setTickLabels.
Definition at line 4792 of file qcustomplot.cpp.
References mCachedMarginValid, and mTicks.
Referenced by QCPAxisRect::setupFullAxesBox().
                                {
  if (mTicks != show) {
    mTicks = show;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickStep (double step)
If setAutoTickStep is set to false, use this function to set the tick step manually. The tick step is the interval between (major) ticks, in plot coordinates.
See also
setSubTickCount
Definition at line 5093 of file qcustomplot.cpp.
References mCachedMarginValid, and mTickStep.
Referenced by QCPAxisRect::setupFullAxesBox().
                                     {
  if (mTickStep != step) {
    mTickStep = step;
    mCachedMarginValid = false;
  }
}
void QCPAxis::setTickVector (const QVector< double > & vec)
If you want full control over what ticks (and possibly labels) the axes show, this function is used to set the coordinates at which ticks will appear.setAutoTicks must be disabled, else the provided tick vector will be overwritten with automatically generated tick coordinates upon replot. The labels of the ticks can be generated automatically when setAutoTickLabels is left enabled. If it is disabled, you can set the labels manually with setTickVectorLabels.
vec is a vector containing the positions of the ticks, in plot coordinates.
Warning
vec must be sorted in ascending order, no additional checks are made to ensure this.
See also
setTickVectorLabels
Definition at line 5119 of file qcustomplot.cpp.
References mCachedMarginValid, and mTickVector.
                                                      {
  // don't check whether mTickVector != vec here, because it takes longer than
  // we would save
  mTickVector = vec;
  mCachedMarginValid = false;
}
void QCPAxis::setTickVectorLabels (const QVector< QString > & vec)
If you want full control over what ticks and labels the axes show, this function is used to set a number of QStrings that will be displayed at the tick positions which you need to provide with setTickVector. These two vectors should have the same size. (Note that you need to disable setAutoTicks and setAutoTickLabels first.)
vec is a vector containing the labels of the ticks. The entries correspond to the respective indices in the tick vector, passed via setTickVector.
See also
setTickVector
Definition at line 5141 of file qcustomplot.cpp.
References mCachedMarginValid, and mTickVectorLabels.
                                                             {
  // don't check whether mTickVectorLabels != vec here, because it takes longer
  // than we would save
  mTickVectorLabels = vec;
  mCachedMarginValid = false;
}
void QCPAxis::setUpperEnding (const QCPLineEnding & ending)
Sets the style for the upper axis ending. See the documentation of QCPLineEnding for available styles.
For horizontal axes, this method refers to the right ending, for vertical axes the top ending. Note that this meaning does not change when the axis range is reversed with setRangeReversed.
See also
setLowerEnding
Definition at line 5456 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::upperEnding.
Referenced by QCPAxisRect::addAxis().
                                                        {
  mAxisPainter->upperEnding = ending;
}
void QCPAxis::setupTickVectors () [protected], [virtual]
Definition at line 5903 of file qcustomplot.cpp.
References generateAutoTicks(), i, QCPRange::lower, ltDateTime, ltNumber, mAutoTickLabels, mAutoTicks, mDateTimeFormat, mDateTimeSpec, mGrid, mHighestVisibleTick, mLowestVisibleTick, mNumberFormatChar, mNumberPrecision, QCPLayerable::mParentPlot, mRange, mSubTickCount, mSubTickVector, mTickLabels, mTickLabelType, mTicks, mTickVector, mTickVectorLabels, QCPRange::size(), ticksRequest(), QCPRange::upper, QCPLayerable::visible(), and visibleTickBounds().
                               {
  if (!mParentPlot)
    return;
  if ((!mTicks && !mTickLabels && !mGrid->visible()) ||
      mRange.size() <= 0)
    return;
  // fill tick vectors, either by auto generating or by notifying user to fill
  // the vectors himself
  if (mAutoTicks) {
    generateAutoTicks();
  } else {
    emit ticksRequest();
  }
  visibleTickBounds(mLowestVisibleTick,
      mHighestVisibleTick);
  if (mTickVector.isEmpty()) {
    mSubTickVector.clear();
    return;
  }
  // generate subticks between ticks:
  mSubTickVector.resize((mTickVector.size() - 1) *
      mSubTickCount);
  if (mSubTickCount > 0) {
    double subTickStep = 0;
    double subTickPosition = 0;
    int subTickIndex = 0;
    bool done = false;
    int lowTick =
        mLowestVisibleTick > 0 ? mLowestVisibleTick - 1 :
      mLowestVisibleTick;
    int highTick = mHighestVisibleTick < mTickVector.size() - 1
                       ? mHighestVisibleTick + 1
                       : mHighestVisibleTick;
    for (int i = lowTick + 1; i <= highTick; ++i) {
      subTickStep = (mTickVector.at(i) - mTickVector.at(i - 1)) /
                    (double)(mSubTickCount + 1);
      for (int k = 1; k <= mSubTickCount; ++k) {
        subTickPosition = mTickVector.at(i - 1) + k * subTickStep;
        if (subTickPosition < mRange.lower)
          continue;
        if (subTickPosition > mRange.upper) {
          done = true;
          break;
        }
        mSubTickVector[subTickIndex] = subTickPosition;
        subTickIndex++;
      }
      if (done)
        break;
    }
    mSubTickVector.resize(subTickIndex);
  }
  // generate tick labels according to tick positions:
  if (mAutoTickLabels) {
    int vecsize = mTickVector.size();
    mTickVectorLabels.resize(vecsize);
    if (mTickLabelType == ltNumber) {
      for (int i = mLowestVisibleTick; i <=
      mHighestVisibleTick; ++i)
        mTickVectorLabels[i] = mParentPlot->locale().toString(
            mTickVector.at(i), mNumberFormatChar.toLatin1(),
      mNumberPrecision);
    } else if (mTickLabelType == ltDateTime) {
      for (int i = mLowestVisibleTick; i <=
      mHighestVisibleTick; ++i) {
#if QT_VERSION < QT_VERSION_CHECK(4, 7, 0) // use fromMSecsSinceEpoch function
                                           // if available, to gain sub-second
                                           // accuracy on tick labels (e.g. for
                                           // format "hh:mm:ss:zzz")
        mTickVectorLabels[i] = mParentPlot->locale().toString(
            QDateTime::fromTime_t(mTickVector.at(i)).toTimeSpec(
      mDateTimeSpec),
            mDateTimeFormat);
#else
        mTickVectorLabels[i] = mParentPlot->locale().toString(
            QDateTime::fromMSecsSinceEpoch(mTickVector.at(i) * 1000)
                .toTimeSpec(mDateTimeSpec),
            mDateTimeFormat);
#endif
      }
    }
  } else // mAutoTickLabels == false
  {
    if (mAutoTicks) // ticks generated automatically, but not ticklabels, so
                    // emit ticksRequest here for labels
    {
      emit ticksRequest();
    }
    // make sure provided tick label vector has correct (minimal) length:
    if (mTickVectorLabels.size() < mTickVector.size())
      mTickVectorLabels.resize(mTickVector.size());
  }
}
int QCPAxis::subTickCount () const [inline]
Definition at line 1315 of file qcustomplot.h.
Referenced by draw(), and QCPAxisRect::setupFullAxesBox().
{ return mSubTickCount; }
int QCPAxis::subTickLengthIn () const
Definition at line 4405 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::subTickLengthIn.
{ return mAxisPainter->subTickLengthIn; }
int QCPAxis::subTickLengthOut () const
Definition at line 4408 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::subTickLengthOut.
{ return mAxisPainter->subTickLengthOut; }
QPen QCPAxis::subTickPen () const [inline]
Definition at line 1320 of file qcustomplot.h.
{ return mSubTickPen; }
QColor QCPAxis::tickLabelColor () const [inline]
Definition at line 1303 of file qcustomplot.h.
{ return mTickLabelColor; }
QFont QCPAxis::tickLabelFont () const [inline]
Definition at line 1302 of file qcustomplot.h.
{ return mTickLabelFont; }
int QCPAxis::tickLabelPadding () const
Definition at line 4374 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::tickLabelPadding.
{ return mAxisPainter->tickLabelPadding; }
double QCPAxis::tickLabelRotation () const
Definition at line 4377 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::tickLabelRotation.
                                        {
  return mAxisPainter->tickLabelRotation;
}
bool QCPAxis::tickLabels () const [inline]
Definition at line 1299 of file qcustomplot.h.
Referenced by calculateMargin(), and draw().
{ return mTickLabels; }
QCPAxis::LabelSide QCPAxis::tickLabelSide () const
Definition at line 4382 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::tickLabelSide.
                                              {
  return mAxisPainter->tickLabelSide;
}
LabelType QCPAxis::tickLabelType () const [inline]
Definition at line 1301 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mTickLabelType; }
int QCPAxis::tickLengthIn () const
Definition at line 4399 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::tickLengthIn.
{ return mAxisPainter->tickLengthIn; }
int QCPAxis::tickLengthOut () const
Definition at line 4402 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::tickLengthOut.
{ return mAxisPainter->tickLengthOut; }
QPen QCPAxis::tickPen () const [inline]
Definition at line 1319 of file qcustomplot.h.
{ return mTickPen; }
bool QCPAxis::ticks () const [inline]
Definition at line 1298 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mTicks; }
void QCPAxis::ticksRequest () [signal]
This signal is emitted when setAutoTicks is false and the axis is about to generate tick labels for a replot.
Modifying the tick positions can be done with setTickVector. If you also want to control the tick labels, set setAutoTickLabels to false and also provide the labels with setTickVectorLabels.
If you only want static ticks you probably don't need this signal, since you can just set the tick vector (and possibly tick label vector) once. However, if you want to provide ticks (and maybe labels) dynamically, e.g. depending on the current axis range, connect a slot to this signal and set the vector/vectors there.
Referenced by setupTickVectors().
double QCPAxis::tickStep () const [inline]
Definition at line 1310 of file qcustomplot.h.
Referenced by QCPAxisRect::setupFullAxesBox().
{ return mTickStep; }
QVector<double> QCPAxis::tickVector () const [inline]
Definition at line 1311 of file qcustomplot.h.
{ return mTickVector; }
QVector<QString> QCPAxis::tickVectorLabels () const [inline]
Definition at line 1312 of file qcustomplot.h.
{ return mTickVectorLabels; }
QCPLineEnding QCPAxis::upperEnding () const
Definition at line 4420 of file qcustomplot.cpp.
References mAxisPainter, and QCPAxisPainterPrivate::upperEnding.
{ return mAxisPainter->upperEnding; }
void QCPAxis::visibleTickBounds (int & lowIndex, int & highIndex) const [protected]
Definition at line 6323 of file qcustomplot.cpp.
References i, QCPRange::lower, mRange, mTickVector, and QCPRange::upper.
Referenced by calculateMargin(), and setupTickVectors().
                                                                   {
  bool lowFound = false;
  bool highFound = false;
  lowIndex = 0;
  highIndex = -1;
  for (int i = 0; i < mTickVector.size(); ++i) {
    if (mTickVector.at(i) >= mRange.lower) {
      lowFound = true;
      lowIndex = i;
      break;
    }
  }
  for (int i = mTickVector.size() - 1; i >= 0; --i) {
    if (mTickVector.at(i) <= mRange.upper) {
      highFound = true;
      highIndex = i;
      break;
    }
  }
  if (!lowFound && highFound)
    lowIndex = highIndex + 1;
  else if (lowFound && !highFound)
    highIndex = lowIndex - 1;
}
Friends And Related Function Documentation
friend class QCPAxisRect [friend]
Definition at line 1516 of file qcustomplot.h.
friend class QCPGrid [friend]
Definition at line 1515 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 1514 of file qcustomplot.h.
Member Data Documentation
bool QCPAxis::mAutoSubTicks [protected]
Definition at line 1462 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setAutoSubTicks().
int QCPAxis::mAutoTickCount [protected]
Definition at line 1461 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setAutoTickCount().
bool QCPAxis::mAutoTickLabels [protected]
Definition at line 1447 of file qcustomplot.h.
Referenced by draw(), setAutoTickLabels(), and setupTickVectors().
bool QCPAxis::mAutoTicks [protected]
Definition at line 1462 of file qcustomplot.h.
Referenced by setAutoTicks(), and setupTickVectors().
bool QCPAxis::mAutoTickStep [protected]
Definition at line 1462 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setAutoTickStep().
QCPAxisPainterPrivate* QCPAxis::mAxisPainter [protected]
Definition at line 1475 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), getPartAt(), labelPadding(), lowerEnding(), numberFormat(), offset(), setLabelPadding(), setLowerEnding(), setNumberFormat(), setOffset(), setSubTickLengthIn(), setSubTickLengthOut(), setTickLabelPadding(), setTickLabelRotation(), setTickLabelSide(), setTickLengthIn(), setTickLengthOut(), setUpperEnding(), subTickLengthIn(), subTickLengthOut(), tickLabelPadding(), tickLabelRotation(), tickLabelSide(), tickLengthIn(), tickLengthOut(), upperEnding(), and ~QCPAxis().
QCPAxisRect* QCPAxis::mAxisRect [protected]
Definition at line 1433 of file qcustomplot.h.
Referenced by calculateMargin(), coordToPixel(), draw(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), and pixelToCoord().
AxisType QCPAxis::mAxisType [protected]
Definition at line 1432 of file qcustomplot.h.
Referenced by calculateMargin(), and draw().
QPen QCPAxis::mBasePen [protected]
Definition at line 1438 of file qcustomplot.h.
Referenced by getBasePen(), and setBasePen().
int QCPAxis::mCachedMargin [protected]
Definition at line 1481 of file qcustomplot.h.
Referenced by calculateMargin().
bool QCPAxis::mCachedMarginValid [protected]
Definition at line 1480 of file qcustomplot.h.
Referenced by calculateMargin(), moveRange(), scaleRange(), setAutoSubTicks(), setAutoTickCount(), setAutoTickLabels(), setAutoTicks(), setAutoTickStep(), setDateTimeFormat(), setLabel(), setLabelFont(), setLabelPadding(), setNumberFormat(), setNumberPrecision(), setPadding(), setRange(), setRangeLower(), setRangeReversed(), setRangeUpper(), setScaleLogBase(), setScaleType(), setSubTickLengthOut(), setTickLabelColor(), setTickLabelFont(), setTickLabelPadding(), setTickLabelRotation(), setTickLabels(), setTickLabelSide(), setTickLabelType(), setTickLengthOut(), setTicks(), setTickStep(), setTickVector(), and setTickVectorLabels().
QString QCPAxis::mDateTimeFormat [protected]
Definition at line 1452 of file qcustomplot.h.
Referenced by setDateTimeFormat(), and setupTickVectors().
Qt::TimeSpec QCPAxis::mDateTimeSpec [protected]
Definition at line 1453 of file qcustomplot.h.
Referenced by setDateTimeSpec(), and setupTickVectors().
QCPGrid* QCPAxis::mGrid [protected]
Definition at line 1474 of file qcustomplot.h.
Referenced by QCPAxis(), setupTickVectors(), and ~QCPAxis().
int QCPAxis::mHighestVisibleTick [protected]
Definition at line 1476 of file qcustomplot.h.
Referenced by draw(), QCPGrid::drawGridLines(), and setupTickVectors().
QString QCPAxis::mLabel [protected]
Definition at line 1442 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), and setLabel().
QColor QCPAxis::mLabelColor [protected]
Definition at line 1444 of file qcustomplot.h.
Referenced by getLabelColor(), and setLabelColor().
QFont QCPAxis::mLabelFont [protected]
Definition at line 1443 of file qcustomplot.h.
Referenced by getLabelFont(), and setLabelFont().
int QCPAxis::mLowestVisibleTick [protected]
Definition at line 1476 of file qcustomplot.h.
Referenced by draw(), QCPGrid::drawGridLines(), and setupTickVectors().
bool QCPAxis::mNumberBeautifulPowers [protected]
Definition at line 1456 of file qcustomplot.h.
Referenced by draw(), numberFormat(), and setNumberFormat().
QLatin1Char QCPAxis::mNumberFormatChar [protected]
Definition at line 1455 of file qcustomplot.h.
Referenced by numberFormat(), setNumberFormat(), and setupTickVectors().
int QCPAxis::mNumberPrecision [protected]
Definition at line 1454 of file qcustomplot.h.
Referenced by setNumberPrecision(), and setupTickVectors().
Qt::Orientation QCPAxis::mOrientation [protected]
Definition at line 1436 of file qcustomplot.h.
int QCPAxis::mPadding [protected]
Definition at line 1435 of file qcustomplot.h.
Referenced by calculateMargin(), and setPadding().
QCPRange QCPAxis::mRange [protected]
Definition at line 1468 of file qcustomplot.h.
Referenced by coordToPixel(), QCPGrid::drawGridLines(), generateAutoTicks(), moveRange(), pixelToCoord(), rescale(), scaleRange(), setRange(), setRangeLower(), setRangeUpper(), setScaleType(), setupTickVectors(), and visibleTickBounds().
bool QCPAxis::mRangeReversed [protected]
Definition at line 1469 of file qcustomplot.h.
Referenced by coordToPixel(), draw(), pixelToCoord(), and setRangeReversed().
double QCPAxis::mScaleLogBase [protected]
Definition at line 1471 of file qcustomplot.h.
Referenced by basePow(), generateAutoTicks(), and setScaleLogBase().
double QCPAxis::mScaleLogBaseLogInv [protected]
Definition at line 1471 of file qcustomplot.h.
Referenced by baseLog(), and setScaleLogBase().
ScaleType QCPAxis::mScaleType [protected]
Definition at line 1470 of file qcustomplot.h.
Referenced by coordToPixel(), draw(), generateAutoTicks(), moveRange(), pixelToCoord(), rescale(), scaleRange(), setRange(), setRangeLower(), setRangeUpper(), and setScaleType().
SelectableParts QCPAxis::mSelectableParts [protected]
Definition at line 1437 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), selectTest(), and setSelectableParts().
QPen QCPAxis::mSelectedBasePen [protected]
Definition at line 1438 of file qcustomplot.h.
Referenced by getBasePen(), and setSelectedBasePen().
QColor QCPAxis::mSelectedLabelColor [protected]
Definition at line 1444 of file qcustomplot.h.
Referenced by getLabelColor(), and setSelectedLabelColor().
QFont QCPAxis::mSelectedLabelFont [protected]
Definition at line 1443 of file qcustomplot.h.
Referenced by getLabelFont(), and setSelectedLabelFont().
SelectableParts QCPAxis::mSelectedParts [protected]
Definition at line 1437 of file qcustomplot.h.
Referenced by deselectEvent(), getBasePen(), getLabelColor(), getLabelFont(), getSubTickPen(), getTickLabelColor(), getTickLabelFont(), getTickPen(), selectEvent(), and setSelectedParts().
QPen QCPAxis::mSelectedSubTickPen [protected]
Definition at line 1466 of file qcustomplot.h.
Referenced by getSubTickPen(), and setSelectedSubTickPen().
QColor QCPAxis::mSelectedTickLabelColor [protected]
Definition at line 1451 of file qcustomplot.h.
Referenced by getTickLabelColor(), and setSelectedTickLabelColor().
QFont QCPAxis::mSelectedTickLabelFont [protected]
Definition at line 1450 of file qcustomplot.h.
Referenced by getTickLabelFont(), and setSelectedTickLabelFont().
QPen QCPAxis::mSelectedTickPen [protected]
Definition at line 1465 of file qcustomplot.h.
Referenced by getTickPen(), and setSelectedTickPen().
int QCPAxis::mSubTickCount [protected]
Definition at line 1461 of file qcustomplot.h.
Referenced by calculateAutoSubTickCount(), draw(), generateAutoTicks(), setSubTickCount(), and setupTickVectors().
QPen QCPAxis::mSubTickPen [protected]
Definition at line 1466 of file qcustomplot.h.
Referenced by getSubTickPen(), and setSubTickPen().
QVector<double> QCPAxis::mSubTickVector [protected]
Definition at line 1479 of file qcustomplot.h.
Referenced by draw(), QCPGrid::drawSubGridLines(), and setupTickVectors().
QColor QCPAxis::mTickLabelColor [protected]
Definition at line 1451 of file qcustomplot.h.
Referenced by getTickLabelColor(), and setTickLabelColor().
QFont QCPAxis::mTickLabelFont [protected]
Definition at line 1450 of file qcustomplot.h.
Referenced by calculateMargin(), getTickLabelFont(), and setTickLabelFont().
bool QCPAxis::mTickLabels [protected]
Definition at line 1447 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), setTickLabels(), and setupTickVectors().
LabelType QCPAxis::mTickLabelType [protected]
Definition at line 1449 of file qcustomplot.h.
Referenced by draw(), setTickLabelType(), and setupTickVectors().
QPen QCPAxis::mTickPen [protected]
Definition at line 1465 of file qcustomplot.h.
Referenced by getTickPen(), and setTickPen().
bool QCPAxis::mTicks [protected]
Definition at line 1459 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), setTicks(), and setupTickVectors().
double QCPAxis::mTickStep [protected]
Definition at line 1460 of file qcustomplot.h.
Referenced by generateAutoTicks(), and setTickStep().
QVector<double> QCPAxis::mTickVector [protected]
Definition at line 1477 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), QCPGrid::drawGridLines(), generateAutoTicks(), setTickVector(), setupTickVectors(), and visibleTickBounds().
QVector<QString> QCPAxis::mTickVectorLabels [protected]
Definition at line 1478 of file qcustomplot.h.
Referenced by calculateMargin(), draw(), setTickVectorLabels(), and setupTickVectors().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp