QCPLayout Class Reference
The abstract base class for layouts.
#include <qcustomplot.h>
Public Member Functions
QCPLayout ()
virtual void update (UpdatePhase phase)
virtual QList< QCPLayoutElement * > elements (bool recursive) const
virtual int elementCount () const =0
virtual QCPLayoutElement * elementAt (int index) const =0
virtual QCPLayoutElement * takeAt (int index)=0
virtual bool take (QCPLayoutElement *element)=0
virtual void simplify ()
bool removeAt (int index)
bool remove (QCPLayoutElement *element)
void clear ()
Protected Member Functions
virtual void updateLayout ()
void sizeConstraintsChanged () const
void adoptElement (QCPLayoutElement *el)
void releaseElement (QCPLayoutElement *el)
QVector< int > getSectionSizes (QVector< int > maxSizes, QVector< int > minSizes, QVector< double > stretchFactors, int totalSize) const
Friends
class QCPLayoutElement
Additional Inherited Members
Detailed Description
The abstract base class for layouts.
This is an abstract base class for layout elements whose main purpose is to define the position and size of other child layout elements. In most cases, layouts don't draw anything themselves (but there are exceptions to this, e.g. QCPLegend).
QCPLayout derives from QCPLayoutElement, and thus can itself be nested in other layouts.
QCPLayout introduces a common interface for accessing and manipulating the child elements. Those functions are most notably elementCount, elementAt, takeAt, take, simplify, removeAt, remove and clear. Individual subclasses may add more functions to this interface which are more specialized to the form of the layout. For example, QCPLayoutGrid adds functions that take row and column indices to access cells of the layout grid more conveniently.
Since this is an abstract base class, you can't instantiate it directly. Rather use one of its subclasses like QCPLayoutGrid or QCPLayoutInset.
For a general introduction to the layout system, see the dedicated documentation page The Layout System.
Definition at line 856 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPLayout::QCPLayout () [explicit]
Creates an instance of QCPLayout and sets default values. Note that since QCPLayout is an abstract base class, it can't be instantiated directly.
Definition at line 2346 of file qcustomplot.cpp.
{}
Member Function Documentation
void QCPLayout::adoptElement (QCPLayoutElement * el) [protected]
Definition at line 2514 of file qcustomplot.cpp.
References QCPLayerable::initializeParentPlot(), QCPLayoutElement::mParentLayout, QCPLayerable::mParentPlot, QCPLayerable::parentPlot(), and QCPLayerable::setParentLayerable().
Referenced by QCPLayoutGrid::addElement(), and QCPLayoutInset::addElement().
                                                 {
  if (el) {
    el->mParentLayout = this;
    el->setParentLayerable(this);
    el->setParent(this);
    if (!el->parentPlot())
      el->initializeParentPlot(mParentPlot);
  } else
    qDebug() << Q_FUNC_INFO << "Null element passed";
}
void QCPLayout::clear ()
Removes and deletes all layout elements in this layout. Finally calls simplify to make sure all empty cells are collapsed.
See also
remove, removeAt
Definition at line 2455 of file qcustomplot.cpp.
References elementAt(), elementCount(), i, removeAt(), and simplify().
Referenced by QCPLayoutGrid::~QCPLayoutGrid(), and QCPLayoutInset::~QCPLayoutInset().
                      {
  for (int i = elementCount() - 1; i >= 0; --i) {
    if (elementAt(i))
      removeAt(i);
  }
  simplify();
}
QCPLayoutElement * QCPLayout::elementAt (int index) const [pure virtual]
Returns the element in the cell with the given index. If index is invalid, returns 0.
Note that even if index is valid, the respective cell may be empty in some layouts (e.g. QCPLayoutGrid), so this function may return 0 in those cases. You may use this function to check whether a cell is empty or not.
See also
elements, elementCount, takeAt
Implemented in QCPLayoutInset, and QCPLayoutGrid.
Referenced by clear(), elements(), and update().
int QCPLayout::elementCount () const [pure virtual]
Returns the number of elements/cells in the layout.
See also
elements, elementAt
Implemented in QCPLayoutInset, and QCPLayoutGrid.
Referenced by clear(), elements(), and update().
QList< QCPLayoutElement * > QCPLayout::elements (bool recursive) const [virtual]
Returns a list of all child elements in this layout element. If recursive is true, all sub-child elements are included in the list, too.
Warning
There may be entries with value 0 in the returned list. (For example, QCPLayoutGrid may have empty cells which yield 0 at the respective index.)
Reimplemented from QCPLayoutElement.
Reimplemented in QCPLayoutGrid.
Definition at line 2374 of file qcustomplot.cpp.
References c, elementAt(), elementCount(), and i.
Referenced by QCPAxisRect::elements().
                                                                  {
  const int c = elementCount();
  QList<QCPLayoutElement *> result;
#if QT_VERSION >= QT_VERSION_CHECK(4, 7, 0)
  result.reserve(c);
#endif
  for (int i = 0; i < c; ++i)
    result.append(elementAt(i));
  if (recursive) {
    for (int i = 0; i < c; ++i) {
      if (result.at(i))
        result << result.at(i)->elements(recursive);
    }
  }
  return result;
}
QVector< int > QCPLayout::getSectionSizes (QVector< int > maxSizes, QVector< int > minSizes, QVector< double > stretchFactors, int totalSize) const [protected]
Definition at line 2593 of file qcustomplot.cpp.
References i.
Referenced by QCPLayoutGrid::updateLayout().
                                                             {
  if (maxSizes.size() != minSizes.size() ||
      minSizes.size() != stretchFactors.size()) {
    qDebug() << Q_FUNC_INFO << "Passed vector sizes aren't equal:" << maxSizes
             << minSizes << stretchFactors;
    return QVector<int>();
  }
  if (stretchFactors.isEmpty())
    return QVector<int>();
  int sectionCount = stretchFactors.size();
  QVector<double> sectionSizes(sectionCount);
  // if provided total size is forced smaller than total minimum size, ignore
  // minimum sizes (squeeze sections):
  int minSizeSum = 0;
  for (int i = 0; i < sectionCount; ++i)
    minSizeSum += minSizes.at(i);
  if (totalSize < minSizeSum) {
    // new stretch factors are minimum sizes and minimum sizes are set to zero:
    for (int i = 0; i < sectionCount; ++i) {
      stretchFactors[i] = minSizes.at(i);
      minSizes[i] = 0;
    }
  }
  QList<int> minimumLockedSections;
  QList<int> unfinishedSections;
  for (int i = 0; i < sectionCount; ++i)
    unfinishedSections.append(i);
  double freeSize = totalSize;
  int outerIterations = 0;
  while (!unfinishedSections.isEmpty() &&
         outerIterations < sectionCount * 2) // the iteration check ist just a
                                             // failsafe in case something
                                             // really strange happens
  {
    ++outerIterations;
    int innerIterations = 0;
    while (!unfinishedSections.isEmpty() &&
           innerIterations < sectionCount * 2) // the iteration check ist just a
                                               // failsafe in case something
                                               // really strange happens
    {
      ++innerIterations;
      // find section that hits its maximum next:
      int nextId = -1;
      double nextMax = 1e12;
      for (int i = 0; i < unfinishedSections.size(); ++i) {
        int secId = unfinishedSections.at(i);
        double hitsMaxAt = (maxSizes.at(secId) - sectionSizes.at(secId)) /
                           stretchFactors.at(secId);
        if (hitsMaxAt < nextMax) {
          nextMax = hitsMaxAt;
          nextId = secId;
        }
      }
      // check if that maximum is actually within the bounds of the total size
      // (i.e. can we stretch all remaining sections so far that the found
      // section
      // actually hits its maximum, without exceeding the total size when we add
      // up all sections)
      double stretchFactorSum = 0;
      for (int i = 0; i < unfinishedSections.size(); ++i)
        stretchFactorSum += stretchFactors.at(unfinishedSections.at(i));
      double nextMaxLimit = freeSize / stretchFactorSum;
      if (nextMax < nextMaxLimit) // next maximum is actually hit, move forward
                                  // to that point and fix the size of that
                                  // section
      {
        for (int i = 0; i < unfinishedSections.size(); ++i) {
          sectionSizes[unfinishedSections.at(i)] +=
              nextMax *
              stretchFactors.at(
                  unfinishedSections.at(i)); // increment all sections
          freeSize -= nextMax * stretchFactors.at(unfinishedSections.at(i));
        }
        unfinishedSections.removeOne(nextId); // exclude the section that is now
                                              // at maximum from further changes
      } else // next maximum isn't hit, just distribute rest of free space on
             // remaining sections
      {
        for (int i = 0; i < unfinishedSections.size(); ++i)
          sectionSizes[unfinishedSections.at(i)] +=
              nextMaxLimit *
              stretchFactors.at(
                  unfinishedSections.at(i)); // increment all sections
        unfinishedSections.clear();
      }
    }
    if (innerIterations == sectionCount * 2)
      qDebug() << Q_FUNC_INFO
               << "Exceeded maximum expected inner iteration count, layouting "
                  "aborted. Input was:" << maxSizes << minSizes
               << stretchFactors << totalSize;
    // now check whether the resulting section sizes violate minimum
    // restrictions:
    bool foundMinimumViolation = false;
    for (int i = 0; i < sectionSizes.size(); ++i) {
      if (minimumLockedSections.contains(i))
        continue;
      if (sectionSizes.at(i) < minSizes.at(i)) // section violates minimum
      {
        sectionSizes[i] = minSizes.at(i); // set it to minimum
        foundMinimumViolation =
            true; // make sure we repeat the whole optimization process
        minimumLockedSections.append(i);
      }
    }
    if (foundMinimumViolation) {
      freeSize = totalSize;
      for (int i = 0; i < sectionCount; ++i) {
        if (!minimumLockedSections.contains(i)) // only put sections that
                                                // haven't hit their minimum
                                                // back into the pool
          unfinishedSections.append(i);
        else
          freeSize -= sectionSizes.at(i); // remove size of minimum locked
                                          // sections from available space in
                                          // next round
      }
      // reset all section sizes to zero that are in unfinished sections (all
      // others have been set to their minimum):
      for (int i = 0; i < unfinishedSections.size(); ++i)
        sectionSizes[unfinishedSections.at(i)] = 0;
    }
  }
  if (outerIterations == sectionCount * 2)
    qDebug() << Q_FUNC_INFO
             << "Exceeded maximum expected outer iteration count, layouting "
                "aborted. Input was:" << maxSizes << minSizes << stretchFactors
             << totalSize;
  QVector<int> result(sectionCount);
  for (int i = 0; i < sectionCount; ++i)
    result[i] = qRound(sectionSizes.at(i));
  return result;
}
void QCPLayout::releaseElement (QCPLayoutElement * el) [protected]
Definition at line 2539 of file qcustomplot.cpp.
References QCPLayoutElement::mParentLayout, QCPLayerable::mParentPlot, and QCPLayerable::setParentLayerable().
Referenced by QCPLayoutGrid::takeAt(), and QCPLayoutInset::takeAt().
                                                   {
  if (el) {
    el->mParentLayout = 0;
    el->setParentLayerable(0);
    el->setParent(mParentPlot);
    // Note: Don't initializeParentPlot(0) here, because layout element will
    // stay in same parent plot
  } else
    qDebug() << Q_FUNC_INFO << "Null element passed";
}
bool QCPLayout::remove (QCPLayoutElement * element)
Removes and deletes the provided element. Returns true on success. If element is not in the layout, returns false.
This function internally uses takeAt to remove the element from the layout and then deletes the element. Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify.
See also
removeAt, take
Definition at line 2440 of file qcustomplot.cpp.
References take().
                                                {
  if (take(element)) {
    delete element;
    return true;
  } else
    return false;
}
bool QCPLayout::removeAt (int index)
Removes and deletes the element at the provided index. Returns true on success. If index is invalid or points to an empty cell, returns false.
This function internally uses takeAt to remove the element from the layout and then deletes the returned element. Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify.
See also
remove, takeAt
Definition at line 2417 of file qcustomplot.cpp.
References takeAt().
Referenced by clear(), and QCPLayoutGrid::simplify().
                                  {
  if (QCPLayoutElement *el = takeAt(index)) {
    delete el;
    return true;
  } else
    return false;
}
void QCPLayout::simplify () [virtual]
Simplifies the layout by collapsing empty cells. The exact behavior depends on subclasses, the default implementation does nothing.
Not all layouts need simplification. For example, QCPLayoutInset doesn't use explicit simplification while QCPLayoutGrid does.
Reimplemented in QCPLayoutInset, and QCPLayoutGrid.
Definition at line 2400 of file qcustomplot.cpp.
Referenced by clear().
{}
void QCPLayout::sizeConstraintsChanged () const [protected]
Subclasses call this method to report changed (minimum/maximum) size constraints.
If the parent of this layout is again a QCPLayout, forwards the call to the parent's sizeConstraintsChanged. If the parent is a QWidget (i.e. is the QCustomPlot::plotLayout of QCustomPlot), calls QWidget::updateGeometry, so if the QCustomPlot widget is inside a Qt QLayout, it may update itself and resize cells accordingly.
Definition at line 2475 of file qcustomplot.cpp.
Referenced by QCPLayoutElement::setMaximumSize(), and QCPLayoutElement::setMinimumSize().
                                             {
  if (QWidget *w = qobject_cast<QWidget *>(parent()))
    w->updateGeometry();
  else if (QCPLayout *l = qobject_cast<QCPLayout *>(parent()))
    l->sizeConstraintsChanged();
}
bool QCPLayout::take (QCPLayoutElement * element) [pure virtual]
Removes the specified element from the layout and returns true on success.
If the element isn't in this layout, returns false.
Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify.
See also
takeAt
Implemented in QCPLayoutInset, and QCPLayoutGrid.
Referenced by QCPLayoutGrid::addElement(), QCPLayoutInset::addElement(), remove(), and QCPLayoutElement::~QCPLayoutElement().
QCPLayoutElement * QCPLayout::takeAt (int index) [pure virtual]
Removes the element with the given index from the layout and returns it.
If the index is invalid or the cell with that index is empty, returns 0.
Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify.
See also
elementAt, take
Implemented in QCPLayoutInset, and QCPLayoutGrid.
Referenced by removeAt().
void QCPLayout::update (UpdatePhase phase) [virtual]
First calls the QCPLayoutElement::update base class implementation to update the margins on this layout.
Then calls updateLayout which subclasses reimplement to reposition and resize their cells.
Finally, update is called on all child elements.
Reimplemented from QCPLayoutElement.
Definition at line 2358 of file qcustomplot.cpp.
References elementAt(), elementCount(), i, QCPLayoutElement::update(), updateLayout(), and QCPLayoutElement::upLayout.
Referenced by QCustomPlot::draw(), and QCPAxisRect::update().
                                        {
  QCPLayoutElement::update(phase);
  // set child element rects according to layout:
  if (phase == upLayout)
    updateLayout();
  // propagate update call to child elements:
  const int elCount = elementCount();
  for (int i = 0; i < elCount; ++i) {
    if (QCPLayoutElement *el = elementAt(i))
      el->update(phase);
  }
}
void QCPLayout::updateLayout () [protected], [virtual]
Reimplemented in QCPLayoutInset, and QCPLayoutGrid.
Definition at line 2497 of file qcustomplot.cpp.
Referenced by update().
{}
Friends And Related Function Documentation
friend class QCPLayoutElement [friend]
Definition at line 891 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp