Vision::Conversion Class Reference
#include <Conversion.h>
Public Types
enum ColorSpace {
*
CIE_lab,
CIE_XYZ,
RI,
RGB,
*
Intensity,
None
 }
Public Member Functions
Conversion ()
Conversion (const Mat &src)
Conversion (const Conversion &rhs)
~Conversion ()
Conversion & operator= (Conversion rhs)
void Convert (ColorSpace convertFrom, ColorSpace convertTo, bool chain=false)
void Convert (const Mat &src, Mat &dst, ColorSpace convertFrom, ColorSpace convertTo, bool chain=false)
Public Attributes
ColorSpace OriginalColorSpace
ColorSpace ProcessedColorSpace
Private Member Functions
void Lab2RI (float *O, float *P, int nData)
void RGB2XYZ (uchar *O, float *P, int nData)
void XYZ2Lab (float *O, float *P, int nData)
void RGB2Intensity (uchar *O, uchar *P, int nData)
float f_xyz2lab (float t)
Private Attributes
float XYZmat [3][3]
float whitePoint [3] = { 0.9504, 1.0000, 1.0889 }
Additional Inherited Members
Detailed Description
Definition at line 7 of file Conversion.h.
Member Enumeration Documentation
enum Vision::Conversion::ColorSpace
Enumerator which indicates the colorspace used
Enumerator
CIE_lab
 CIE La*b* colorspace
CIE_XYZ
 CIE XYZ colorspace
RI
 Redness Index colorspace
RGB
 RGB colorspace
Intensity
 Grayscale colorspace
None
 none
Definition at line 12 of file Conversion.h.
        {
            CIE_lab,
            CIE_XYZ,
            RI,
            RGB,
            Intensity,
            None
        };
Constructor & Destructor Documentation
Conversion::Conversion ()
Constructor of the class
Definition at line 8 of file Conversion.cpp.
References None, OriginalColorSpace, and ProcessedColorSpace.
    {
        OriginalColorSpace = None;
        ProcessedColorSpace = None;
    }
Conversion::Conversion (const Mat & src)
Constructor of the class
Parameters
src a cv::Mat object which is the source image
Definition at line 17 of file Conversion.cpp.
References None, OriginalColorSpace, Vision::ImageProcessing::OriginalImg, and ProcessedColorSpace.
    {
        OriginalColorSpace = None;
        ProcessedColorSpace = None;
        OriginalImg = src;
    }
Conversion::Conversion (const Conversion & rhs)
Copy constructor
Definition at line 25 of file Conversion.cpp.
References OriginalColorSpace, Vision::ImageProcessing::OriginalImg, ProcessedColorSpace, Vision::ImageProcessing::ProcessedImg, and Vision::ImageProcessing::TempImg.
    {
        this->OriginalColorSpace = rhs.OriginalColorSpace;
        this->OriginalImg = rhs.OriginalImg;
        this->ProcessedColorSpace = rhs.ProcessedColorSpace;
        this->ProcessedImg = rhs.ProcessedImg;
        this->TempImg = rhs.TempImg;
    }
Conversion::~Conversion ()
De-constructor of the class
Definition at line 35 of file Conversion.cpp.
{ }
Member Function Documentation
void Conversion::Convert (ColorSpace convertFrom, ColorSpace convertTo, bool chain = false)
Convert the source image from one colorspace to a destination colorspace posibilities are:
RGB 2 Intensity
RGB 2 XYZ
RGB 2 Lab
RGB 2 Redness Index
XYZ 2 Lab
XYZ 2 Redness Index
Lab 2 Redness Index
Parameters
convertFrom the starting colorspace
convertTo the destination colorspace
chain use the results from the previous operation default value = false;
Definition at line 84 of file Conversion.cpp.
References CHAIN_PROCESS, CIE_lab, CIE_XYZ, Vision::ImageProcessing::currentProg, EMPTY_CHECK, Intensity, Lab2RI(), OriginalColorSpace, Vision::ImageProcessing::OriginalImg, ProcessedColorSpace, Vision::ImageProcessing::ProcessedImg, Vision::ImageProcessing::prog_sig, Vision::ImageProcessing::ProgStep, RGB, RGB2Intensity(), RGB2XYZ(), RI, and XYZ2Lab().
Referenced by BOOST_FIXTURE_TEST_CASE(), Convert(), and SoilAnalyzer::Sample::PrepImg().
    {
        OriginalColorSpace = convertFrom;
        ProcessedColorSpace = convertTo;
        // Exception handling
        EMPTY_CHECK(OriginalImg);
        currentProg = 0.;
        prog_sig(currentProg, "Converting colorspace");
        int nData = OriginalImg.rows * OriginalImg.cols;
        //uint32_t i, j;
        if (convertFrom == RGB && convertTo == Intensity) // RGB 2 Intensity
        {
            ProcessedImg.create(OriginalImg.size(), CV_8UC1);
            uchar *P = ProcessedImg.data;
            uchar *O;
            CHAIN_PROCESS(chain, O, uchar);
            prog_sig(currentProg, "RGB 2 Intensity conversion");
            RGB2Intensity(O, P, nData);
            currentProg += ProgStep;
            prog_sig(currentProg, "RGB 2 Intensity conversion Finished");
        }
        else if (convertFrom == RGB && convertTo == CIE_XYZ) // RGB 2 XYZ
        {
            ProcessedImg.create(OriginalImg.size(), CV_32FC3);
            float *P = (float *)ProcessedImg.data;
            uchar *O;
            CHAIN_PROCESS(chain, O, uchar);
            prog_sig(currentProg, "RGB 2 CIE XYZ conversion");
            RGB2XYZ(O, P, nData);
            currentProg += ProgStep;
            prog_sig(currentProg, "RGB 2 CIE XYZ conversion Finished");
        }
        else if (convertFrom == RGB && convertTo == CIE_lab) // RGB 2 Lab
        {
            ProcessedImg.create(OriginalImg.size(), CV_32FC3);
            float *P = (float *)ProcessedImg.data;
            uchar *O;
            CHAIN_PROCESS(chain, O, uchar);
            prog_sig(currentProg, "RGB 2 CIE XYZ conversion");
            RGB2XYZ(O, P, nData);
            currentProg += ProgStep;
            prog_sig(currentProg, "RGB 2 CIE XYZ conversion Finished");
            Convert(CIE_XYZ, CIE_lab, true);
        }
        else if (convertFrom == RGB && convertTo == RI) // RGB 2 RI
        {
            ProcessedImg.create(OriginalImg.size(), CV_32FC3);
            float *P = (float *)ProcessedImg.data;
            uchar *O;
            CHAIN_PROCESS(chain, O, uchar);
            prog_sig(currentProg, "RGB 2 CIE XYZ conversion");
            RGB2XYZ(O, P, nData);
            currentProg += ProgStep;
            prog_sig(currentProg, "RGB 2 CIE XYZ conversion Finished");
            Convert(CIE_XYZ, CIE_lab, true);
            Convert(CIE_lab, RI, true);
        }
        else if (convertFrom == CIE_XYZ && convertTo == CIE_lab) // XYZ 2 Lab
        {
            ProcessedImg.create(OriginalImg.size(), CV_32FC3);
            float *P = (float *)ProcessedImg.data;
            float *O;
            CHAIN_PROCESS(chain, O, float);
            prog_sig(currentProg, "CIE XYZ 2 CIE La*b* conversion");
            XYZ2Lab(O, P, nData);
            currentProg += ProgStep;
            prog_sig(currentProg, "CIE XYZ 2 CIE La*b* conversion Finished");
        }
        else if (convertFrom == CIE_XYZ && convertTo == RI) // XYZ 2 RI
        {
            ProcessedImg.create(OriginalImg.size(), CV_32FC3);
            float *P = (float *)ProcessedImg.data;
            float *O;
            CHAIN_PROCESS(chain, O, float);
            prog_sig(currentProg, "CIE XYZ 2 CIE La*b* conversion");
            XYZ2Lab(O, P, nData);
            currentProg += ProgStep;
            prog_sig(currentProg, "CIE XYZ 2 CIE La*b* conversion Finished");
            Convert(CIE_lab, RI, true);
        }
        else if (convertFrom == CIE_lab && convertTo == RI) // Lab 2 RI
        {
            ProcessedImg.create(OriginalImg.size(), CV_32FC1);
            float *P = (float *)ProcessedImg.data;
            float *O;
            CHAIN_PROCESS(chain, O, float);
            prog_sig(currentProg, "CIE La*b* 2 Redness Index conversion");
            Lab2RI(O, P, nData * 3);
            currentProg += ProgStep;
            prog_sig(currentProg, "CIE La*b* 2 Redness Index conversion Finsihed");
        }
        else { throw Exception::ConversionNotSupportedException(); }
    }
void Conversion::Convert (const Mat & src, Mat & dst, ColorSpace convertFrom, ColorSpace convertTo, bool chain = false)
Convert the source image from one colorspace to a destination colorspace
RGB 2 Intensity
RGB 2 XYZ
RGB 2 Lab
RGB 2 Redness Index
XYZ 2 Lab
XYZ 2 Redness Index
Lab 2 Redness Index
Parameters
src a cv::Mat object which is the source image
dst a cv::Mat object which is the destination image
convertFrom the starting colorspace
convertTo the destination colorspace
chain use the results from the previous operation default value = false;
Definition at line 65 of file Conversion.cpp.
References Convert(), Vision::ImageProcessing::OriginalImg, and Vision::ImageProcessing::ProcessedImg.
    {
        OriginalImg = src;
        Convert(convertFrom, convertTo, chain);
        dst = ProcessedImg;
    }
float Conversion::f_xyz2lab (float t) [inline], [private]
Definition at line 257 of file Conversion.cpp.
Referenced by XYZ2Lab().
    {
        if (t > 0.008856) { return pow(t, 0.3333333333f); }
        return 7.787 * t + 0.137931034482759f;
    }
void Conversion::Lab2RI (float * O, float * P, int nData) [private]
Conversion from CIE La*b* to Redness Index
Parameters
O a uchar pointer to the source image
P a uchar pointer to the destination image
nData an int indicating the total number of pixels
Definition at line 268 of file Conversion.cpp.
References i, and j.
Referenced by Convert().
    {
        uint32_t i = 0;
        uint32_t j = 0;
        float L, a, b;
        for (uint32_t i = 0; i < nData; i += 3)
        {
            L = *(O + i);
            a = *(O + i + 1);
            b = *(O + i + 2);
            P[j++] = (L * (pow((pow(a, 2.0f) + pow(b, 2.0f)), 0.5f) * (pow(10, 8.2f)))) / (b * pow(L, 6.0f)
      );
        }
    }
Conversion & Conversion::operator= (Conversion rhs)
Assignment operator
Definition at line 38 of file Conversion.cpp.
References OriginalColorSpace, Vision::ImageProcessing::OriginalImg, ProcessedColorSpace, Vision::ImageProcessing::ProcessedImg, and Vision::ImageProcessing::TempImg.
    {
        if (&rhs != this)
        {
            this->OriginalColorSpace = rhs.OriginalColorSpace;
            this->OriginalImg = rhs.OriginalImg;
            this->ProcessedColorSpace = rhs.ProcessedColorSpace;
            this->ProcessedImg = rhs.ProcessedImg;
            this->TempImg = rhs.TempImg;
        }
        return *this;
    }
void Conversion::RGB2Intensity (uchar * O, uchar * P, int nData) [private]
Conversion from RGB to Intensity
Parameters
O a uchar pointer to the source image
P a uchar pointer to the destination image
nData an int indicating the total number of pixels
Definition at line 193 of file Conversion.cpp.
References i, and j.
Referenced by Convert().
    {
        uint32_t i;
        uint32_t j;
        i = 0;
        j = 0;
        while (j < nData)
        {
            P[j++] = (*(O + i + 2) * 0.2126 + *(O + i + 1) * 0.7152 + *(O + i) * 0.0722); // Grey value
            i += 3;
        }
    }
void Conversion::RGB2XYZ (uchar * O, float * P, int nData) [private]
Conversion from RGB to CIE XYZ
Parameters
O a uchar pointer to the source image
P a uchar pointer to the destination image
nData an int indicating the total number of pixels
Definition at line 211 of file Conversion.cpp.
References i, Vision::ImageProcessing::OriginalImg, and XYZmat.
Referenced by Convert().
    {
        uint32_t i = 0;
        uint32_t endData = nData * OriginalImg.step.buf[1];
        float R, G, B;
        for (uint32_t i = 0; i < endData; i += OriginalImg.step.buf[1])
        {
            R = static_cast<float>(*(O + i + 2) / 255.0f);
            B = static_cast<float>(*(O + i + 1) / 255.0f);
            G = static_cast<float>(*(O + i) / 255.0f);
            P[i] = (XYZmat[0][0] * R) + (XYZmat[0][1] * B) + (
      XYZmat[0][2] * G); //X
            P[i + 1] = (XYZmat[1][0] * R) + (XYZmat[1][1] * B) + (
      XYZmat[1][2] * G); //Y
            P[i + 2] = (XYZmat[2][0] * R) + (XYZmat[2][1] * B) + (
      XYZmat[2][2] * G); //Z
        }
    }
void Conversion::XYZ2Lab (float * O, float * P, int nData) [private]
Conversion from CIE XYZ to CIE La*b*
Parameters
O a uchar pointer to the source image
P a uchar pointer to the destination image
nData an int indicating the total number of pixels
Definition at line 232 of file Conversion.cpp.
References f_xyz2lab(), i, and whitePoint.
Referenced by Convert().
    {
        uint32_t i = 0;
        uint32_t endData = nData * 3;
        float yy0, xx0, zz0;
        for (size_t i = 0; i < endData; i += 3)
        {
            xx0 = *(O + i) / whitePoint[0];
            yy0 = *(O + i + 1) / whitePoint[1];
            zz0 = *(O + i + 2) / whitePoint[2];
            if (yy0 > 0.008856)
            {
                P[i] = (116 * pow(yy0, 0.333f)) - 16; // L
            }
            else
            {
                P[i] = 903.3 * yy0; // L
            }
            P[i + 1] = 500 * (f_xyz2lab(xx0) - f_xyz2lab(yy0));
            P[i + 2] = 200 * (f_xyz2lab(yy0) - f_xyz2lab(zz0));
        }
    }
Member Data Documentation
ColorSpace Vision::Conversion::OriginalColorSpace
The original colorspace
Definition at line 21 of file Conversion.h.
Referenced by Conversion(), Convert(), and operator=().
ColorSpace Vision::Conversion::ProcessedColorSpace
The destination colorspace
Definition at line 22 of file Conversion.h.
Referenced by Conversion(), Convert(), and operator=().
float Vision::Conversion::whitePoint[3] = { 0.9504, 1.0000, 1.0889 } [private]
Natural whitepoint in XYZ colorspace D65 according to Matlab
Definition at line 45 of file Conversion.h.
Referenced by XYZ2Lab().
float Vision::Conversion::XYZmat[3][3] [private]
Initial value:
=
        {
            { 0.412453, 0.357580, 0.180423 },
            {0.212671, 0.715160, 0.072169 },
            {0.019334, 0.119194, 0.950227 }
        }
< Conversion matrix used in the conversion between RGB and CIE XYZ
Definition at line 38 of file Conversion.h.
Referenced by RGB2XYZ().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilVision/Conversion.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilVision/Conversion.cpp