QCPPlottableLegendItem Class Reference
A legend item representing a plottable with an icon and the plottable name.
#include <qcustomplot.h>
Public Member Functions
QCPPlottableLegendItem (QCPLegend *parent, QCPAbstractPlottable *plottable)
QCPAbstractPlottable * plottable ()
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QSize minimumSizeHint () const
QPen getIconBorderPen () const
QColor getTextColor () const
QFont getFont () const
Protected Attributes
QCPAbstractPlottable * mPlottable
Additional Inherited Members
Detailed Description
A legend item representing a plottable with an icon and the plottable name.
This is the standard legend item for plottables. It displays an icon of the plottable next to the plottable name. The icon is drawn by the respective plottable itself (QCPAbstractPlottable::drawLegendIcon), and tries to give an intuitive symbol for the plottable. For example, the QCPGraph draws a centered horizontal line and/or a single scatter point in the middle.
Legend items of this type are always associated with one plottable (retrievable via the plottable() function and settable with the constructor). You may change the font of the plottable name with setFont. Icon padding and border pen is taken from the parent QCPLegend, see QCPLegend::setIconBorderPen and QCPLegend::setIconTextPadding.
The function QCPAbstractPlottable::addToLegend/QCPAbstractPlottable::removeFromLegend creates/removes legend items of this type in the default implementation. However, these functions may be reimplemented such that a different kind of legend item (e.g a direct subclass of QCPAbstractLegendItem) is used for that plottable.
Since QCPLegend is based on QCPLayoutGrid, a legend item itself is just a subclass of QCPLayoutElement. While it could be added to a legend (or any other layout) via the normal layout interface, QCPLegend has specialized functions for handling legend items conveniently, see the documentation of QCPLegend.
Definition at line 2475 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPPlottableLegendItem::QCPPlottableLegendItem (QCPLegend * parent, QCPAbstractPlottable * plottable)
Creates a new legend item associated with plottable.
Once it's created, it can be added to the legend via QCPLegend::addItem.
A more convenient way of adding/removing a plottable to/from the legend is via the functions QCPAbstractPlottable::addToLegend and QCPAbstractPlottable::removeFromLegend.
Definition at line 14112 of file qcustomplot.cpp.
    : QCPAbstractLegendItem(parent), mPlottable(plottable) {}
Member Function Documentation
void QCPPlottableLegendItem::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractLegendItem.
Definition at line 14155 of file qcustomplot.cpp.
References QCPAbstractPlottable::drawLegendIcon(), getFont(), getIconBorderPen(), getTextColor(), QCPLegend::iconSize(), QCPLegend::iconTextPadding(), QCPAbstractLegendItem::mParentLegend, mPlottable, QCPLayoutElement::mRect, QCPAbstractPlottable::name(), QCPPainter::restore(), QCPPainter::save(), and QCPPainter::setPen().
                                                     {
  if (!mPlottable)
    return;
  painter->setFont(getFont());
  painter->setPen(QPen(getTextColor()));
  QSizeF iconSize = mParentLegend->iconSize();
  QRectF textRect = painter->fontMetrics().boundingRect(
      0, 0, 0, iconSize.height(), Qt::TextDontClip, mPlottable->name());
  QRectF iconRect(mRect.topLeft(), iconSize);
  int textHeight = qMax(textRect.height(),
                        iconSize.height()); // if text has smaller height than
                                            // icon, center text vertically in
                                            // icon height, else align tops
  painter->drawText(mRect.x() + iconSize.width() +
                        mParentLegend->iconTextPadding(),
                    mRect.y(), textRect.width(), textHeight, Qt::TextDontClip,
                    mPlottable->name());
  // draw icon:
  painter->save();
  painter->setClipRect(iconRect, Qt::IntersectClip);
  mPlottable->drawLegendIcon(painter, iconRect);
  painter->restore();
  // draw icon border:
  if (getIconBorderPen().style() != Qt::NoPen) {
    painter->setPen(getIconBorderPen());
    painter->setBrush(Qt::NoBrush);
    painter->drawRect(iconRect);
  }
}
QFont QCPPlottableLegendItem::getFont () const [protected]
Definition at line 14143 of file qcustomplot.cpp.
References QCPAbstractLegendItem::mFont, QCPAbstractLegendItem::mSelected, and QCPAbstractLegendItem::mSelectedFont.
Referenced by draw(), and minimumSizeHint().
                                            {
  return mSelected ? mSelectedFont : mFont;
}
QPen QCPPlottableLegendItem::getIconBorderPen () const [protected]
Definition at line 14122 of file qcustomplot.cpp.
References QCPLegend::iconBorderPen(), QCPAbstractLegendItem::mParentLegend, QCPAbstractLegendItem::mSelected, and QCPLegend::selectedIconBorderPen().
Referenced by draw().
                                                    {
  return mSelected ? mParentLegend->selectedIconBorderPen()
                   : mParentLegend->iconBorderPen();
}
QColor QCPPlottableLegendItem::getTextColor () const [protected]
Definition at line 14133 of file qcustomplot.cpp.
References QCPAbstractLegendItem::mSelected, QCPAbstractLegendItem::mSelectedTextColor, and QCPAbstractLegendItem::mTextColor.
Referenced by draw().
                                                  {
  return mSelected ? mSelectedTextColor : mTextColor;
}
QSize QCPPlottableLegendItem::minimumSizeHint () const [protected], [virtual]
Returns the minimum size this layout element (the inner rect) may be compressed to.
if a minimum size (setMinimumSize) was not set manually, parent layouts consult this function to determine the minimum allowed size of this layout element. (A manual minimum size is considered set if it is non-zero.)
Reimplemented from QCPLayoutElement.
Definition at line 14191 of file qcustomplot.cpp.
References getFont(), QCPLegend::iconSize(), QCPLegend::iconTextPadding(), QCPLayoutElement::mMargins, QCPAbstractLegendItem::mParentLegend, mPlottable, and QCPAbstractPlottable::name().
                                                    {
  if (!mPlottable)
    return QSize();
  QSize result(0, 0);
  QRect textRect;
  QFontMetrics fontMetrics(getFont());
  QSize iconSize = mParentLegend->iconSize();
  textRect = fontMetrics.boundingRect(0, 0, 0, iconSize.height(),
                                      Qt::TextDontClip, mPlottable->
      name());
  result.setWidth(iconSize.width() + mParentLegend->iconTextPadding() +
                  textRect.width() + mMargins.left() + mMargins.right());
  result.setHeight(qMax(textRect.height(), iconSize.height()) + mMargins.top() +
                   mMargins.bottom());
  return result;
}
QCPAbstractPlottable* QCPPlottableLegendItem::plottable () [inline]
Definition at line 2481 of file qcustomplot.h.
{ return mPlottable; }
Member Data Documentation
QCPAbstractPlottable* QCPPlottableLegendItem::mPlottable [protected]
Definition at line 2485 of file qcustomplot.h.
Referenced by draw(), and minimumSizeHint().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp