QCPAxisRect Class Reference
Holds multiple axes and arranges them in a rectangular shape.
#include <qcustomplot.h>
Public Member Functions
QCPAxisRect (QCustomPlot *parentPlot, bool setupDefaultAxes=true)
virtual ~QCPAxisRect ()
QPixmap background () const
bool backgroundScaled () const
Qt::AspectRatioMode backgroundScaledMode () const
Qt::Orientations rangeDrag () const
Qt::Orientations rangeZoom () const
QCPAxis * rangeDragAxis (Qt::Orientation orientation)
QCPAxis * rangeZoomAxis (Qt::Orientation orientation)
double rangeZoomFactor (Qt::Orientation orientation)
void setBackground (const QPixmap &pm)
void setBackground (const QPixmap &pm, bool scaled, Qt::AspectRatioMode mode=Qt::KeepAspectRatioByExpanding)
void setBackground (const QBrush &brush)
void setBackgroundScaled (bool scaled)
void setBackgroundScaledMode (Qt::AspectRatioMode mode)
void setRangeDrag (Qt::Orientations orientations)
void setRangeZoom (Qt::Orientations orientations)
void setRangeDragAxes (QCPAxis *horizontal, QCPAxis *vertical)
void setRangeZoomAxes (QCPAxis *horizontal, QCPAxis *vertical)
void setRangeZoomFactor (double horizontalFactor, double verticalFactor)
void setRangeZoomFactor (double factor)
int axisCount (QCPAxis::AxisType type) const
QCPAxis * axis (QCPAxis::AxisType type, int index=0) const
QList< QCPAxis * > axes (QCPAxis::AxisTypes types) const
QList< QCPAxis * > axes () const
QCPAxis * addAxis (QCPAxis::AxisType type, QCPAxis *axis=0)
QList< QCPAxis * > addAxes (QCPAxis::AxisTypes types)
bool removeAxis (QCPAxis *axis)
QCPLayoutInset * insetLayout () const
void setupFullAxesBox (bool connectRanges=false)
QList< QCPAbstractPlottable * > plottables () const
QList< QCPGraph * > graphs () const
QList< QCPAbstractItem * > items () const
int left () const
int right () const
int top () const
int bottom () const
int width () const
int height () const
QSize size () const
QPoint topLeft () const
QPoint topRight () const
QPoint bottomLeft () const
QPoint bottomRight () const
QPoint center () const
virtual void update (UpdatePhase phase)
virtual QList< QCPLayoutElement * > elements (bool recursive) const
Protected Member Functions
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual int calculateAutoMargin (QCP::MarginSide side)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseMoveEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *event)
void drawBackground (QCPPainter *painter)
void updateAxesOffset (QCPAxis::AxisType type)
Protected Attributes
QBrush mBackgroundBrush
QPixmap mBackgroundPixmap
QPixmap mScaledBackgroundPixmap
bool mBackgroundScaled
Qt::AspectRatioMode mBackgroundScaledMode
QCPLayoutInset * mInsetLayout
Qt::Orientations mRangeDrag
Qt::Orientations mRangeZoom
QPointer< QCPAxis > mRangeDragHorzAxis
QPointer< QCPAxis > mRangeDragVertAxis
QPointer< QCPAxis > mRangeZoomHorzAxis
QPointer< QCPAxis > mRangeZoomVertAxis
double mRangeZoomFactorHorz
double mRangeZoomFactorVert
QCPRange mDragStartHorzRange
QCPRange mDragStartVertRange
QCP::AntialiasedElements mAADragBackup
QCP::AntialiasedElements mNotAADragBackup
QPoint mDragStart
bool mDragging
QHash< QCPAxis::AxisType, QList< QCPAxis * > > mAxes
Friends
class QCustomPlot
Additional Inherited Members
Detailed Description
Holds multiple axes and arranges them in a rectangular shape.
This class represents an axis rect, a rectangular area that is bounded on all sides with an arbitrary number of axes.
Initially QCustomPlot has one axis rect, accessible via QCustomPlot::axisRect(). However, the layout system allows to have multiple axis rects, e.g. arranged in a grid layout (QCustomPlot::plotLayout).
By default, QCPAxisRect comes with four axes, at bottom, top, left and right. They can be accessed via axis by providing the respective axis type (QCPAxis::AxisType) and index. If you need all axes in the axis rect, use axes. The top and right axes are set to be invisible initially (QCPAxis::setVisible). To add more axes to a side, use addAxis or addAxes. To remove an axis, use removeAxis.
The axis rect layerable itself only draws a background pixmap or color, if specified (setBackground). It is placed on the `background` layer initially (see QCPLayer for an explanation of the QCustomPlot layer system). The axes that are held by the axis rect can be placed on other layers, independently of the axis rect.
Every axis rect has a child layout of type QCPLayoutInset. It is accessible via insetLayout and can be used to have other layout elements (or even other layouts with multiple elements) hovering inside the axis rect.
If an axis rect is clicked and dragged, it processes this by moving certain axis ranges. The behaviour can be controlled with setRangeDrag and setRangeDragAxes. If the mouse wheel is scrolled while the cursor is on the axis rect, certain axes are scaled. This is controllable via setRangeZoom, setRangeZoomAxes and setRangeZoomFactor. These interactions are only enabled if QCustomPlot::setInteractions contains QCP::iRangeDrag and QCP::iRangeZoom.
Overview of the spacings and paddings that define the geometry of an axis. The dashed line on the far left indicates the viewport/widget border.
Definition at line 2294 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAxisRect::QCPAxisRect (QCustomPlot * parentPlot, bool setupDefaultAxes = true) [explicit]
Creates a QCPAxisRect instance and sets default values. An axis is added for each of the four sides, the top and right axes are set invisible initially.
Definition at line 12945 of file qcustomplot.cpp.
References addAxis(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::grid(), QCPLayerable::initializeParentPlot(), mAxes, mInsetLayout, QCPLayerable::mParentPlot, QCPLayoutElement::setMinimumMargins(), QCPLayoutElement::setMinimumSize(), QCPLayerable::setParentLayerable(), setRangeDragAxes(), setRangeZoomAxes(), QCPLayerable::setVisible(), and QCPGrid::setZeroLinePen().
    : QCPLayoutElement(parentPlot), mBackgroundBrush(Qt::NoBrush),
      mBackgroundScaled(true),
      mBackgroundScaledMode(Qt::KeepAspectRatioByExpanding),
      mInsetLayout(new QCPLayoutInset),
      mRangeDrag(Qt::Horizontal | Qt::Vertical),
      mRangeZoom(Qt::Horizontal | Qt::Vertical), mRangeZoomFactorHorz(0.85),
      mRangeZoomFactorVert(0.85), mDragging(false) {
  mInsetLayout->initializeParentPlot(mParentPlot);
  mInsetLayout->setParentLayerable(this);
  mInsetLayout->setParent(this);
  setMinimumSize(50, 50);
  setMinimumMargins(QMargins(15, 15, 15, 15));
  mAxes.insert(QCPAxis::atLeft, QList<QCPAxis *>());
  mAxes.insert(QCPAxis::atRight, QList<QCPAxis *>());
  mAxes.insert(QCPAxis::atTop, QList<QCPAxis *>());
  mAxes.insert(QCPAxis::atBottom, QList<QCPAxis *>());
  if (setupDefaultAxes) {
    QCPAxis *xAxis = addAxis(QCPAxis::atBottom);
    QCPAxis *yAxis = addAxis(QCPAxis::atLeft);
    QCPAxis *xAxis2 = addAxis(QCPAxis::atTop);
    QCPAxis *yAxis2 = addAxis(QCPAxis::atRight);
    setRangeDragAxes(xAxis, yAxis);
    setRangeZoomAxes(xAxis, yAxis);
    xAxis2->setVisible(false);
    yAxis2->setVisible(false);
    xAxis->grid()->setVisible(true);
    yAxis->grid()->setVisible(true);
    xAxis2->grid()->setVisible(false);
    yAxis2->grid()->setVisible(false);
    xAxis2->grid()->setZeroLinePen(Qt::NoPen);
    yAxis2->grid()->setZeroLinePen(Qt::NoPen);
    xAxis2->grid()->setVisible(false);
    yAxis2->grid()->setVisible(false);
  }
}
QCPAxisRect::~QCPAxisRect () [virtual]
Definition at line 12984 of file qcustomplot.cpp.
References axes(), i, mInsetLayout, and removeAxis().
                          {
  delete mInsetLayout;
  mInsetLayout = 0;
  QList<QCPAxis *> axesList = axes();
  for (int i = 0; i < axesList.size(); ++i)
    removeAxis(axesList.at(i));
}
Member Function Documentation
QList< QCPAxis * > QCPAxisRect::addAxes (QCPAxis::AxisTypes types)
Adds a new axis with addAxis to each axis rect side specified in types. This may be an or-combination of QCPAxis::AxisType, so axes can be added to multiple sides at once.
Returns a list of the added axes.
See also
addAxis, setupFullAxesBox
Definition at line 13127 of file qcustomplot.cpp.
References addAxis(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, and QCPAxis::atTop.
                                                            {
  QList<QCPAxis *> result;
  if (types.testFlag(QCPAxis::atLeft))
    result << addAxis(QCPAxis::atLeft);
  if (types.testFlag(QCPAxis::atRight))
    result << addAxis(QCPAxis::atRight);
  if (types.testFlag(QCPAxis::atTop))
    result << addAxis(QCPAxis::atTop);
  if (types.testFlag(QCPAxis::atBottom))
    result << addAxis(QCPAxis::atBottom);
  return result;
}
QCPAxis * QCPAxisRect::addAxis (QCPAxis::AxisType type, QCPAxis * axis = 0)
Adds a new axis to the axis rect side specified with type, and returns it. If axis is 0, a new QCPAxis instance is created internally.
You may inject QCPAxis instances (or sublasses of QCPAxis) by setting axis to an axis that was previously created outside QCustomPlot. It is important to note that QCustomPlot takes ownership of the axis, so you may not delete it afterwards. Further, the axis must have been created with this axis rect as parent and with the same axis type as specified in type. If this is not the case, a debug output is generated, the axis is not added, and the method returns 0.
This method can not be used to move axis between axis rects. The same axis instance must not be added multiple times to the same or different axis rects.
If an axis rect side already contains one or more axes, the lower and upper endings of the new axis (QCPAxis::setLowerEnding, QCPAxis::setUpperEnding) are set to QCPLineEnding::esHalfBar.
See also
addAxes, setupFullAxesBox
Definition at line 13082 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atRight, axes(), axis(), QCPAxis::axisRect(), QCPAxis::axisType(), QCPLineEnding::esHalfBar, mAxes, QCPAxis::setLowerEnding(), QCPAxis::setUpperEnding(), and size().
Referenced by addAxes(), QCPAxisRect(), and setupFullAxesBox().
                                                                 {
  QCPAxis *newAxis = axis;
  if (!newAxis) {
    newAxis = new QCPAxis(this, type);
  } else // user provided existing axis instance, do some sanity checks
  {
    if (newAxis->axisType() != type) {
      qDebug() << Q_FUNC_INFO << "passed axis has different axis type than "
                                 "specified in type parameter";
      return 0;
    }
    if (newAxis->axisRect() != this) {
      qDebug() << Q_FUNC_INFO
               << "passed axis doesn't have this axis rect as parent axis rect";
      return 0;
    }
    if (axes().contains(newAxis)) {
      qDebug() << Q_FUNC_INFO
               << "passed axis is already owned by this axis rect";
      return 0;
    }
  }
  if (mAxes[type].size() > 0) // multiple axes on one side, add half-bar axis
                              // ending to additional axes with offset
  {
    bool invert = (type == QCPAxis::atRight) || (type ==
      QCPAxis::atBottom);
    newAxis->setLowerEnding(
        QCPLineEnding(QCPLineEnding::esHalfBar, 6, 10, !invert));
    newAxis->setUpperEnding(
        QCPLineEnding(QCPLineEnding::esHalfBar, 6, 10, invert));
  }
  mAxes[type].append(newAxis);
  return newAxis;
}
void QCPAxisRect::applyDefaultAntialiasingHint (QCPPainter * painter) const [protected], [virtual]
Reimplemented from QCPLayoutElement.
Definition at line 13394 of file qcustomplot.cpp.
References QCPPainter::setAntialiasing().
                                                                        {
  painter->setAntialiasing(false);
}
QList< QCPAxis * > QCPAxisRect::axes (QCPAxis::AxisTypes types) const
Returns all axes on the axis rect sides specified with types.
types may be a single QCPAxis::AxisType or an or-combination, to get the axes of multiple sides.
See also
axis
Definition at line 13027 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, and mAxes.
Referenced by QCustomPlot::rescaleAxes(), and QCustomPlot::selectedAxes().
                                                               {
  QList<QCPAxis *> result;
  if (types.testFlag(QCPAxis::atLeft))
    result << mAxes.value(QCPAxis::atLeft);
  if (types.testFlag(QCPAxis::atRight))
    result << mAxes.value(QCPAxis::atRight);
  if (types.testFlag(QCPAxis::atTop))
    result << mAxes.value(QCPAxis::atTop);
  if (types.testFlag(QCPAxis::atBottom))
    result << mAxes.value(QCPAxis::atBottom);
  return result;
}
QList< QCPAxis * > QCPAxisRect::axes () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns all axes of this axis rect.
Definition at line 13044 of file qcustomplot.cpp.
References mAxes.
Referenced by addAxis(), update(), and ~QCPAxisRect().
                                         {
  QList<QCPAxis *> result;
  QHashIterator<QCPAxis::AxisType, QList<QCPAxis *>> it(mAxes);
  while (it.hasNext()) {
    it.next();
    result << it.value();
  }
  return result;
}
QCPAxis * QCPAxisRect::axis (QCPAxis::AxisType type, int index = 0) const
Returns the axis with the given index on the axis rect side specified with type.
See also
axisCount, axes
Definition at line 13008 of file qcustomplot.cpp.
References mAxes.
Referenced by addAxis(), QCPColorScaleAxisRectPrivate::axisSelectableChanged(), QCPColorScaleAxisRectPrivate::axisSelectionChanged(), QCPColorScaleAxisRectPrivate::QCPColorScaleAxisRectPrivate(), QCustomPlot::QCustomPlot(), removeAxis(), and setupFullAxesBox().
                                                                {
  QList<QCPAxis *> ax(mAxes.value(type));
  if (index >= 0 && index < ax.size()) {
    return ax.at(index);
  } else {
    qDebug() << Q_FUNC_INFO << "Axis index out of bounds:" << index;
    return 0;
  }
}
int QCPAxisRect::axisCount (QCPAxis::AxisType type) const
Returns the number of axes on the axis rect side specified with type.
See also
axis
Definition at line 12998 of file qcustomplot.cpp.
References mAxes.
Referenced by setupFullAxesBox().
                                                     {
  return mAxes.value(type).size();
}
QPixmap QCPAxisRect::background () const [inline]
Definition at line 2310 of file qcustomplot.h.
{ return mBackgroundPixmap; }
bool QCPAxisRect::backgroundScaled () const [inline]
Definition at line 2311 of file qcustomplot.h.
{ return mBackgroundScaled; }
Qt::AspectRatioMode QCPAxisRect::backgroundScaledMode () const [inline]
Definition at line 2312 of file qcustomplot.h.
                                                 {
    return mBackgroundScaledMode;
  }
int QCPAxisRect::bottom () const [inline]
Returns the pixel position of the bottom border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2354 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), QCPAxis::pixelToCoord(), and QCPGraph::upperFillBasePoint().
{ return mRect.bottom(); }
QPoint QCPAxisRect::bottomLeft () const [inline]
Returns the bottom left corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2360 of file qcustomplot.h.
{ return mRect.bottomLeft(); }
QPoint QCPAxisRect::bottomRight () const [inline]
Returns the bottom right corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2361 of file qcustomplot.h.
{ return mRect.bottomRight(); }
int QCPAxisRect::calculateAutoMargin (QCP::MarginSide side) [protected], [virtual]
Reimplemented from QCPLayoutElement.
Definition at line 13720 of file qcustomplot.cpp.
References QCPAxis::marginSideToAxisType(), QCPLayoutElement::mAutoMargins, mAxes, and updateAxesOffset().
                                                       {
  if (!mAutoMargins.testFlag(side))
    qDebug() << Q_FUNC_INFO
             << "Called with side that isn't specified as auto margin";
  updateAxesOffset(QCPAxis::marginSideToAxisType(side));
  // note: only need to look at the last (outer most) axis to determine the
  // total margin, due to updateAxisOffset call
  const QList<QCPAxis *> axesList =
      mAxes.value(QCPAxis::marginSideToAxisType(side));
  if (axesList.size() > 0)
    return axesList.last()->offset() + axesList.last()->calculateMargin();
  else
    return 0;
}
QPoint QCPAxisRect::center () const [inline]
Returns the center of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2362 of file qcustomplot.h.
{ return mRect.center(); }
void QCPAxisRect::draw (QCPPainter * painter) [protected], [virtual]
Reimplemented from QCPLayoutElement.
Reimplemented in QCPColorScaleAxisRectPrivate.
Definition at line 13399 of file qcustomplot.cpp.
References drawBackground().
Referenced by QCPColorScaleAxisRectPrivate::draw().
{ drawBackground(painter); }
void QCPAxisRect::drawBackground (QCPPainter * painter) [protected]
Definition at line 13655 of file qcustomplot.cpp.
References mBackgroundBrush, mBackgroundPixmap, mBackgroundScaled, mBackgroundScaledMode, QCPLayoutElement::mRect, and mScaledBackgroundPixmap.
Referenced by draw().
                                                    {
  // draw background fill:
  if (mBackgroundBrush != Qt::NoBrush)
    painter->fillRect(mRect, mBackgroundBrush);
  // draw background pixmap (on top of fill, if brush specified):
  if (!mBackgroundPixmap.isNull()) {
    if (mBackgroundScaled) {
      // check whether mScaledBackground needs to be updated:
      QSize scaledSize(mBackgroundPixmap.size());
      scaledSize.scale(mRect.size(), mBackgroundScaledMode);
      if (mScaledBackgroundPixmap.size() != scaledSize)
        mScaledBackgroundPixmap = mBackgroundPixmap.scaled(
            mRect.size(), mBackgroundScaledMode, Qt::SmoothTransformation);
      painter->drawPixmap(mRect.topLeft() + QPoint(0, -1),
                          mScaledBackgroundPixmap,
                          QRect(0, 0, mRect.width(), mRect.height()) &
                              mScaledBackgroundPixmap.rect());
    } else {
      painter->drawPixmap(mRect.topLeft() + QPoint(0, -1),
      mBackgroundPixmap,
                          QRect(0, 0, mRect.width(), mRect.height()));
    }
  }
}
QList< QCPLayoutElement * > QCPAxisRect::elements (bool recursive) const [virtual]
Returns a list of all child elements in this layout element. If recursive is true, all sub-child elements are included in the list, too.
Warning
There may be entries with value 0 in the returned list. (For example, QCPLayoutGrid may have empty cells which yield 0 at the respective index.)
Reimplemented from QCPLayoutElement.
Definition at line 13383 of file qcustomplot.cpp.
References QCPLayout::elements(), and mInsetLayout.
                                                                    {
  QList<QCPLayoutElement *> result;
  if (mInsetLayout) {
    result << mInsetLayout;
    if (recursive)
      result << mInsetLayout->elements(recursive);
  }
  return result;
}
QList< QCPGraph * > QCPAxisRect::graphs () const
Returns a list of all the graphs that are associated with this axis rect.
A graph is considered associated with an axis rect if its key or value axis (or both) is in this axis rect.
See also
plottables, items
Definition at line 13300 of file qcustomplot.cpp.
References i, QCustomPlot::mGraphs, and QCPLayerable::mParentPlot.
                                            {
  // Note: don't append all QCPAxis::graphs() into a list, because we might get
  // duplicate entries
  QList<QCPGraph *> result;
  for (int i = 0; i < mParentPlot->mGraphs.size(); ++i) {
    if (mParentPlot->mGraphs.at(i)->keyAxis()->axisRect() == this ||
        mParentPlot->mGraphs.at(i)->valueAxis()->axisRect() == this)
      result.append(mParentPlot->mGraphs.at(i));
  }
  return result;
}
int QCPAxisRect::height () const [inline]
Returns the pixel height of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2356 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPBarsGroup::getPixelSpacing(), QCPAxis::pixelToCoord(), and QCPAxis::setScaleRatio().
{ return mRect.height(); }
QCPLayoutInset * QCPAxisRect::insetLayout () const [inline]
Returns the inset layout of this axis rect. It can be used to place other layout elements (or even layouts with multiple other elements) inside/on top of an axis rect.
See also
QCPLayoutInset
Definition at line 2343 of file qcustomplot.h.
Referenced by QCustomPlot::QCustomPlot().
{ return mInsetLayout; }
QList< QCPAbstractItem * > QCPAxisRect::items () const
Returns a list of all the items that are associated with this axis rect.
An item is considered associated with an axis rect if any of its positions has key or value axis set to an axis that is in this axis rect, or if any of its positions has QCPItemPosition::setAxisRect set to the axis rect, or if the clip axis rect (QCPAbstractItem::setClipAxisRect) is set to this axis rect.
See also
plottables, graphs
Definition at line 13324 of file qcustomplot.cpp.
References QCustomPlot::mItems, and QCPLayerable::mParentPlot.
                                                  {
  // Note: don't just append all QCPAxis::items() into a list, because we might
  // get duplicate entries
  // and miss those items that have this axis rect as clipAxisRect.
  QList<QCPAbstractItem *> result;
  for (int itemId = 0; itemId < mParentPlot->mItems.size(); ++itemId) {
    if (mParentPlot->mItems.at(itemId)->clipAxisRect() == this) {
      result.append(mParentPlot->mItems.at(itemId));
      continue;
    }
    QList<QCPItemPosition *> positions =
        mParentPlot->mItems.at(itemId)->positions();
    for (int posId = 0; posId < positions.size(); ++posId) {
      if (positions.at(posId)->axisRect() == this ||
          positions.at(posId)->keyAxis()->axisRect() == this ||
          positions.at(posId)->valueAxis()->axisRect() == this) {
        result.append(mParentPlot->mItems.at(itemId));
        break;
      }
    }
  }
  return result;
}
int QCPAxisRect::left () const [inline]
Returns the pixel position of the left border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2351 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), QCPAxis::pixelToCoord(), and QCPGraph::upperFillBasePoint().
{ return mRect.left(); }
void QCPAxisRect::mouseMoveEvent (QMouseEvent * event) [protected], [virtual]
This event is called, if the mouse is moved inside the outer rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 13781 of file qcustomplot.cpp.
References QCP::aeAll, QCustomPlot::interactions(), QCP::iRangeDrag, QCPRange::lower, mDragging, mDragStart, mDragStartHorzRange, mDragStartVertRange, QCPLayerable::mParentPlot, mRangeDrag, mRangeDragHorzAxis, mRangeDragVertAxis, QCustomPlot::noAntialiasingOnDrag(), QCustomPlot::replot(), QCustomPlot::setNotAntialiasedElements(), QCPAxis::stLinear, QCPAxis::stLogarithmic, and QCPRange::upper.
                                                   {
  // Mouse range dragging interaction:
  if (mDragging && mParentPlot->interactions().testFlag(
      QCP::iRangeDrag)) {
    if (mRangeDrag.testFlag(Qt::Horizontal)) {
      if (QCPAxis *rangeDragHorzAxis = mRangeDragHorzAxis.data()) {
        if (rangeDragHorzAxis->mScaleType == QCPAxis::stLinear) {
          double diff = rangeDragHorzAxis->pixelToCoord(mDragStart.x()) -
                        rangeDragHorzAxis->pixelToCoord(event->pos().x());
          rangeDragHorzAxis->setRange(mDragStartHorzRange.
      lower + diff,
                                      mDragStartHorzRange.
      upper + diff);
        } else if (rangeDragHorzAxis->mScaleType == QCPAxis::stLogarithmic) {
          double diff = rangeDragHorzAxis->pixelToCoord(mDragStart.x()) /
                        rangeDragHorzAxis->pixelToCoord(event->pos().x());
          rangeDragHorzAxis->setRange(mDragStartHorzRange.
      lower * diff,
                                      mDragStartHorzRange.
      upper * diff);
        }
      }
    }
    if (mRangeDrag.testFlag(Qt::Vertical)) {
      if (QCPAxis *rangeDragVertAxis = mRangeDragVertAxis.data()) {
        if (rangeDragVertAxis->mScaleType == QCPAxis::stLinear) {
          double diff = rangeDragVertAxis->pixelToCoord(mDragStart.y()) -
                        rangeDragVertAxis->pixelToCoord(event->pos().y());
          rangeDragVertAxis->setRange(mDragStartVertRange.
      lower + diff,
                                      mDragStartVertRange.
      upper + diff);
        } else if (rangeDragVertAxis->mScaleType == QCPAxis::stLogarithmic) {
          double diff = rangeDragVertAxis->pixelToCoord(mDragStart.y()) /
                        rangeDragVertAxis->pixelToCoord(event->pos().y());
          rangeDragVertAxis->setRange(mDragStartVertRange.
      lower * diff,
                                      mDragStartVertRange.
      upper * diff);
        }
      }
    }
    if (mRangeDrag !=
        0) // if either vertical or horizontal drag was enabled, do a replot
    {
      if (mParentPlot->noAntialiasingOnDrag())
        mParentPlot->setNotAntialiasedElements(
      QCP::aeAll);
      mParentPlot->replot();
    }
  }
}
void QCPAxisRect::mousePressEvent (QMouseEvent * event) [protected], [virtual]
This event is called, if the mouse was pressed while being inside the outer rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 13751 of file qcustomplot.cpp.
References QCustomPlot::antialiasedElements(), QCustomPlot::interactions(), QCP::iRangeDrag, mAADragBackup, mDragging, mDragStart, mDragStartHorzRange, mDragStartVertRange, mNotAADragBackup, QCPLayerable::mParentPlot, mRangeDragHorzAxis, mRangeDragVertAxis, QCustomPlot::noAntialiasingOnDrag(), and QCustomPlot::notAntialiasedElements().
                                                    {
  mDragStart = event->pos(); // need this even when not LeftButton is pressed,
                             // to determine in releaseEvent whether it was a
                             // full click (no position change between press and
                             // release)
  if (event->buttons() & Qt::LeftButton) {
    mDragging = true;
    // initialize antialiasing backup in case we start dragging:
    if (mParentPlot->noAntialiasingOnDrag()) {
      mAADragBackup = mParentPlot->antialiasedElements();
      mNotAADragBackup = mParentPlot->
      notAntialiasedElements();
    }
    // Mouse range dragging interaction:
    if (mParentPlot->interactions().testFlag(
      QCP::iRangeDrag)) {
      if (mRangeDragHorzAxis)
        mDragStartHorzRange = mRangeDragHorzAxis.data()->range();
      if (mRangeDragVertAxis)
        mDragStartVertRange = mRangeDragVertAxis.data()->range();
    }
  }
}
void QCPAxisRect::mouseReleaseEvent (QMouseEvent * event) [protected], [virtual]
This event is called, if the mouse was previously pressed inside the outer rect of this layout element and is now released.
Reimplemented from QCPLayoutElement.
Definition at line 13825 of file qcustomplot.cpp.
References mAADragBackup, mDragging, mNotAADragBackup, QCPLayerable::mParentPlot, QCustomPlot::noAntialiasingOnDrag(), QCustomPlot::setAntialiasedElements(), and QCustomPlot::setNotAntialiasedElements().
                                                      {
  Q_UNUSED(event)
  mDragging = false;
  if (mParentPlot->noAntialiasingOnDrag()) {
    mParentPlot->setAntialiasedElements(
      mAADragBackup);
    mParentPlot->setNotAntialiasedElements(
      mNotAADragBackup);
  }
}
QList< QCPAbstractPlottable * > QCPAxisRect::plottables () const
Returns a list of all the plottables that are associated with this axis rect.
A plottable is considered associated with an axis rect if its key or value axis (or both) is in this axis rect.
See also
graphs, items
Definition at line 13279 of file qcustomplot.cpp.
References i, QCPLayerable::mParentPlot, and QCustomPlot::mPlottables.
                                                            {
  // Note: don't append all QCPAxis::plottables() into a list, because we might
  // get duplicate entries
  QList<QCPAbstractPlottable *> result;
  for (int i = 0; i < mParentPlot->mPlottables.size(); ++
      i) {
    if (mParentPlot->mPlottables.at(i)->keyAxis()->axisRect() == this ||
        mParentPlot->mPlottables.at(i)->valueAxis()->axisRect() == this)
      result.append(mParentPlot->mPlottables.at(i));
  }
  return result;
}
Qt::Orientations QCPAxisRect::rangeDrag () const [inline]
Definition at line 2315 of file qcustomplot.h.
{ return mRangeDrag; }
QCPAxis * QCPAxisRect::rangeDragAxis (Qt::Orientation orientation)
Returns the range drag axis of the orientation provided.
See also
setRangeDragAxes
Definition at line 13499 of file qcustomplot.cpp.
References mRangeDragHorzAxis, and mRangeDragVertAxis.
                                                             {
  return (orientation == Qt::Horizontal ? mRangeDragHorzAxis.data()
                                        : mRangeDragVertAxis.data());
}
Qt::Orientations QCPAxisRect::rangeZoom () const [inline]
Definition at line 2316 of file qcustomplot.h.
{ return mRangeZoom; }
QCPAxis * QCPAxisRect::rangeZoomAxis (Qt::Orientation orientation)
Returns the range zoom axis of the orientation provided.
See also
setRangeZoomAxes
Definition at line 13509 of file qcustomplot.cpp.
References mRangeZoomHorzAxis, and mRangeZoomVertAxis.
                                                             {
  return (orientation == Qt::Horizontal ? mRangeZoomHorzAxis.data()
                                        : mRangeZoomVertAxis.data());
}
double QCPAxisRect::rangeZoomFactor (Qt::Orientation orientation)
Returns the range zoom factor of the orientation provided.
See also
setRangeZoomFactor
Definition at line 13519 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
                                                             {
  return (orientation == Qt::Horizontal ? mRangeZoomFactorHorz
                                        : mRangeZoomFactorVert);
}
bool QCPAxisRect::removeAxis (QCPAxis * axis)
Removes the specified axis from the axis rect and deletes it.
Returns true on success, i.e. if axis was a valid axis in this axis rect.
See also
addAxis
Definition at line 13147 of file qcustomplot.cpp.
References axis(), QCustomPlot::axisRemoved(), mAxes, and QCPLayerable::parentPlot().
Referenced by ~QCPAxisRect().
                                          {
  // don't access axis->axisType() to provide safety when axis is an invalid
  // pointer, rather go through all axis containers:
  QHashIterator<QCPAxis::AxisType, QList<QCPAxis *>> it(mAxes);
  while (it.hasNext()) {
    it.next();
    if (it.value().contains(axis)) {
      mAxes[it.key()].removeOne(axis);
      if (qobject_cast<QCustomPlot *>(
              parentPlot())) // make sure this isn't called from QObject dtor
                             // when QCustomPlot is already destructed (happens
                             // when the axis rect is not in any layout and thus
                             // QObject-child of QCustomPlot)
        parentPlot()->axisRemoved(axis);
      delete axis;
      return true;
    }
  }
  qDebug() << Q_FUNC_INFO
           << "Axis isn't in axis rect:" << reinterpret_cast<quintptr>(axis);
  return false;
}
int QCPAxisRect::right () const [inline]
Returns the pixel position of the right border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2352 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), and QCPGraph::upperFillBasePoint().
{ return mRect.right(); }
void QCPAxisRect::setBackground (const QPixmap & pm)
Sets pm as the axis background pixmap. The axis background pixmap will be drawn inside the axis rect. Since axis rects place themselves on the `background` layer by default, the axis rect backgrounds are usually drawn below everything else.
For cases where the provided pixmap doesn't have the same size as the axis rect, scaling can be enabled with setBackgroundScaled and the scaling mode (i.e. whether and how the aspect ratio is preserved) can be set with setBackgroundScaledMode. To set all these options in one call, consider using the overloaded version of this function.
Below the pixmap, the axis rect may be optionally filled with a brush, if specified with setBackground(const QBrush &brush).
See also
setBackgroundScaled, setBackgroundScaledMode, setBackground(const QBrush &brush)
Definition at line 13423 of file qcustomplot.cpp.
References mBackgroundPixmap, and mScaledBackgroundPixmap.
                                                 {
  mBackgroundPixmap = pm;
  mScaledBackgroundPixmap = QPixmap();
}
void QCPAxisRect::setBackground (const QPixmap & pm, bool scaled, Qt::AspectRatioMode mode = Qt::KeepAspectRatioByExpanding)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows setting the background pixmap of the axis rect, whether it shall be scaled and how it shall be scaled in one call.
See also
setBackground(const QPixmap &pm), setBackgroundScaled, setBackgroundScaledMode
Definition at line 13457 of file qcustomplot.cpp.
References mBackgroundPixmap, mBackgroundScaled, mBackgroundScaledMode, and mScaledBackgroundPixmap.
                                                        {
  mBackgroundPixmap = pm;
  mScaledBackgroundPixmap = QPixmap();
  mBackgroundScaled = scaled;
  mBackgroundScaledMode = mode;
}
void QCPAxisRect::setBackground (const QBrush & brush)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets brush as the background brush. The axis rect background will be filled with this brush. Since axis rects place themselves on the `background` layer by default, the axis rect backgrounds are usually drawn below everything else.
The brush will be drawn before (under) any background pixmap, which may be specified with setBackground(const QPixmap &pm).
To disable drawing of a background brush, set brush to Qt::NoBrush.
See also
setBackground(const QPixmap &pm)
Definition at line 13444 of file qcustomplot.cpp.
References mBackgroundBrush.
                                                   {
  mBackgroundBrush = brush;
}
void QCPAxisRect::setBackgroundScaled (bool scaled)
Sets whether the axis background pixmap shall be scaled to fit the axis rect or not. If scaled is set to true, you may control whether and how the aspect ratio of the original pixmap is preserved with setBackgroundScaledMode.
Note that the scaled version of the original pixmap is buffered, so there is no performance penalty on replots. (Except when the axis rect dimensions are changed continuously.)
See also
setBackground, setBackgroundScaledMode
Definition at line 13479 of file qcustomplot.cpp.
References mBackgroundScaled.
                                                 {
  mBackgroundScaled = scaled;
}
void QCPAxisRect::setBackgroundScaledMode (Qt::AspectRatioMode mode)
If scaling of the axis background pixmap is enabled (setBackgroundScaled), use this function to define whether and how the aspect ratio of the original pixmap passed to setBackground is preserved.
See also
setBackground, setBackgroundScaled
Definition at line 13490 of file qcustomplot.cpp.
References mBackgroundScaledMode.
                                                                {
  mBackgroundScaledMode = mode;
}
void QCPAxisRect::setRangeDrag (Qt::Orientations orientations)
Sets which axis orientation may be range dragged by the user with mouse interaction. What orientation corresponds to which specific axis can be set with setRangeDragAxes(QCPAxis *horizontal, QCPAxis *vertical). By default, the horizontal axis is the bottom axis (xAxis) and the vertical axis is the left axis (yAxis).
To disable range dragging entirely, pass 0 as orientations or remove QCP::iRangeDrag from QCustomPlot::setInteractions. To enable range dragging for both directions, pass Qt::Horizontal | Qt::Vertical as orientations.
In addition to setting orientations to a non-zero value, make sure QCustomPlot::setInteractions contains QCP::iRangeDrag to enable the range dragging interaction.
See also
setRangeZoom, setRangeDragAxes, QCustomPlot::setNoAntialiasingOnDrag
Definition at line 13544 of file qcustomplot.cpp.
References mRangeDrag.
                                                          {
  mRangeDrag = orientations;
}
void QCPAxisRect::setRangeDragAxes (QCPAxis * horizontal, QCPAxis * vertical)
Sets the axes whose range will be dragged when setRangeDrag enables mouse range dragging on the QCustomPlot widget.
See also
setRangeZoomAxes
Definition at line 13580 of file qcustomplot.cpp.
References mRangeDragHorzAxis, and mRangeDragVertAxis.
Referenced by QCPAxisRect().
                                                                         {
  mRangeDragHorzAxis = horizontal;
  mRangeDragVertAxis = vertical;
}
void QCPAxisRect::setRangeZoom (Qt::Orientations orientations)
Sets which axis orientation may be zoomed by the user with the mouse wheel. What orientation corresponds to which specific axis can be set with setRangeZoomAxes(QCPAxis *horizontal, QCPAxis *vertical). By default, the horizontal axis is the bottom axis (xAxis) and the vertical axis is the left axis (yAxis).
To disable range zooming entirely, pass 0 as orientations or remove QCP::iRangeZoom from QCustomPlot::setInteractions. To enable range zooming for both directions, pass Qt::Horizontal | Qt::Vertical as orientations.
In addition to setting orientations to a non-zero value, make sure QCustomPlot::setInteractions contains QCP::iRangeZoom to enable the range zooming interaction.
See also
setRangeZoomFactor, setRangeZoomAxes, setRangeDrag
Definition at line 13569 of file qcustomplot.cpp.
References mRangeZoom.
                                                          {
  mRangeZoom = orientations;
}
void QCPAxisRect::setRangeZoomAxes (QCPAxis * horizontal, QCPAxis * vertical)
Sets the axes whose range will be zoomed when setRangeZoom enables mouse wheel zooming on the QCustomPlot widget. The two axes can be zoomed with different strengths, when different factors are passed to setRangeZoomFactor(double horizontalFactor, double verticalFactor).
See also
setRangeDragAxes
Definition at line 13595 of file qcustomplot.cpp.
References mRangeZoomHorzAxis, and mRangeZoomVertAxis.
Referenced by QCPAxisRect().
                                                                         {
  mRangeZoomHorzAxis = horizontal;
  mRangeZoomVertAxis = vertical;
}
void QCPAxisRect::setRangeZoomFactor (double horizontalFactor, double verticalFactor)
Sets how strong one rotation step of the mouse wheel zooms, when range zoom was activated with setRangeZoom. The two parameters horizontalFactor and verticalFactor provide a way to let the horizontal axis zoom at different rates than the vertical axis. Which axis is horizontal and which is vertical, can be set with setRangeZoomAxes.
When the zoom factor is greater than one, scrolling the mouse wheel backwards (towards the user) will zoom in (make the currently visible range smaller). For zoom factors smaller than one, the same scrolling direction will zoom out.
Definition at line 13615 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
                                                            {
  mRangeZoomFactorHorz = horizontalFactor;
  mRangeZoomFactorVert = verticalFactor;
}
void QCPAxisRect::setRangeZoomFactor (double factor)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets both the horizontal and vertical zoom factor.
Definition at line 13625 of file qcustomplot.cpp.
References mRangeZoomFactorHorz, and mRangeZoomFactorVert.
                                                  {
  mRangeZoomFactorHorz = factor;
  mRangeZoomFactorVert = factor;
}
void QCPAxisRect::setupFullAxesBox (bool connectRanges = false)
Convenience function to create an axis on each side that doesn't have any axes yet and set their visibility to true. Further, the top/right axes are assigned the following properties of the bottom/left axes:
range (QCPAxis::setRange)
range reversed (QCPAxis::setRangeReversed)
scale type (QCPAxis::setScaleType)
scale log base (QCPAxis::setScaleLogBase)
ticks (QCPAxis::setTicks)
auto (major) tick count (QCPAxis::setAutoTickCount)
sub tick count (QCPAxis::setSubTickCount)
auto sub ticks (QCPAxis::setAutoSubTicks)
tick step (QCPAxis::setTickStep)
auto tick step (QCPAxis::setAutoTickStep)
number format (QCPAxis::setNumberFormat)
number precision (QCPAxis::setNumberPrecision)
tick label type (QCPAxis::setTickLabelType)
date time format (QCPAxis::setDateTimeFormat)
date time spec (QCPAxis::setDateTimeSpec)
Tick labels (QCPAxis::setTickLabels) of the right and top axes are set to false.
If connectRanges is true, the rangeChanged signals of the bottom and left axes are connected to the QCPAxis::setRange slots of the top and right axes.
Definition at line 13201 of file qcustomplot.cpp.
References addAxis(), QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::autoSubTicks(), QCPAxis::autoTickCount(), QCPAxis::autoTickStep(), axis(), axisCount(), QCPAxis::dateTimeFormat(), QCPAxis::dateTimeSpec(), QCPAxis::numberFormat(), QCPAxis::numberPrecision(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxis::scaleLogBase(), QCPAxis::scaleType(), QCPAxis::setAutoSubTicks(), QCPAxis::setAutoTickCount(), QCPAxis::setAutoTickStep(), QCPAxis::setDateTimeFormat(), QCPAxis::setDateTimeSpec(), QCPAxis::setNumberFormat(), QCPAxis::setNumberPrecision(), QCPAxis::setRange(), QCPAxis::setRangeReversed(), QCPAxis::setScaleLogBase(), QCPAxis::setScaleType(), QCPAxis::setSubTickCount(), QCPAxis::setTickLabels(), QCPAxis::setTickLabelType(), QCPAxis::setTicks(), QCPAxis::setTickStep(), QCPLayerable::setVisible(), QCPAxis::subTickCount(), QCPAxis::tickLabelType(), QCPAxis::ticks(), and QCPAxis::tickStep().
                                                     {
  QCPAxis *xAxis, *yAxis, *xAxis2, *yAxis2;
  if (axisCount(QCPAxis::atBottom) == 0)
    xAxis = addAxis(QCPAxis::atBottom);
  else
    xAxis = axis(QCPAxis::atBottom);
  if (axisCount(QCPAxis::atLeft) == 0)
    yAxis = addAxis(QCPAxis::atLeft);
  else
    yAxis = axis(QCPAxis::atLeft);
  if (axisCount(QCPAxis::atTop) == 0)
    xAxis2 = addAxis(QCPAxis::atTop);
  else
    xAxis2 = axis(QCPAxis::atTop);
  if (axisCount(QCPAxis::atRight) == 0)
    yAxis2 = addAxis(QCPAxis::atRight);
  else
    yAxis2 = axis(QCPAxis::atRight);
  xAxis->setVisible(true);
  yAxis->setVisible(true);
  xAxis2->setVisible(true);
  yAxis2->setVisible(true);
  xAxis2->setTickLabels(false);
  yAxis2->setTickLabels(false);
  xAxis2->setRange(xAxis->range());
  xAxis2->setRangeReversed(xAxis->rangeReversed());
  xAxis2->setScaleType(xAxis->scaleType());
  xAxis2->setScaleLogBase(xAxis->scaleLogBase());
  xAxis2->setTicks(xAxis->ticks());
  xAxis2->setAutoTickCount(xAxis->autoTickCount());
  xAxis2->setSubTickCount(xAxis->subTickCount());
  xAxis2->setAutoSubTicks(xAxis->autoSubTicks());
  xAxis2->setTickStep(xAxis->tickStep());
  xAxis2->setAutoTickStep(xAxis->autoTickStep());
  xAxis2->setNumberFormat(xAxis->numberFormat());
  xAxis2->setNumberPrecision(xAxis->numberPrecision());
  xAxis2->setTickLabelType(xAxis->tickLabelType());
  xAxis2->setDateTimeFormat(xAxis->dateTimeFormat());
  xAxis2->setDateTimeSpec(xAxis->dateTimeSpec());
  yAxis2->setRange(yAxis->range());
  yAxis2->setRangeReversed(yAxis->rangeReversed());
  yAxis2->setScaleType(yAxis->scaleType());
  yAxis2->setScaleLogBase(yAxis->scaleLogBase());
  yAxis2->setTicks(yAxis->ticks());
  yAxis2->setAutoTickCount(yAxis->autoTickCount());
  yAxis2->setSubTickCount(yAxis->subTickCount());
  yAxis2->setAutoSubTicks(yAxis->autoSubTicks());
  yAxis2->setTickStep(yAxis->tickStep());
  yAxis2->setAutoTickStep(yAxis->autoTickStep());
  yAxis2->setNumberFormat(yAxis->numberFormat());
  yAxis2->setNumberPrecision(yAxis->numberPrecision());
  yAxis2->setTickLabelType(yAxis->tickLabelType());
  yAxis2->setDateTimeFormat(yAxis->dateTimeFormat());
  yAxis2->setDateTimeSpec(yAxis->dateTimeSpec());
  if (connectRanges) {
    connect(xAxis, SIGNAL(rangeChanged(QCPRange)), xAxis2,
            SLOT(setRange(QCPRange)));
    connect(yAxis, SIGNAL(rangeChanged(QCPRange)), yAxis2,
            SLOT(setRange(QCPRange)));
  }
}
QSize QCPAxisRect::size () const [inline]
Returns the pixel size of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2357 of file qcustomplot.h.
Referenced by addAxis().
{ return mRect.size(); }
int QCPAxisRect::top () const [inline]
Returns the pixel position of the top border of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2353 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPGrid::drawGridLines(), QCPGrid::drawSubGridLines(), QCPGraph::lowerFillBasePoint(), and QCPGraph::upperFillBasePoint().
{ return mRect.top(); }
QPoint QCPAxisRect::topLeft () const [inline]
Returns the top left corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2358 of file qcustomplot.h.
{ return mRect.topLeft(); }
QPoint QCPAxisRect::topRight () const [inline]
Returns the top right corner of this axis rect in pixels. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2359 of file qcustomplot.h.
{ return mRect.topRight(); }
void QCPAxisRect::update (UpdatePhase phase) [virtual]
This method is called automatically upon replot and doesn't need to be called by users of QCPAxisRect.
Calls the base class implementation to update the margins (see QCPLayoutElement::update), and finally passes the rect to the inset layout (insetLayout) and calls its QCPInsetLayout::update function.
Reimplemented from QCPLayoutElement.
Definition at line 13359 of file qcustomplot.cpp.
References axes(), i, mInsetLayout, QCPLayoutElement::rect(), QCPLayoutElement::setOuterRect(), QCPLayoutElement::update(), QCPLayout::update(), QCPLayoutElement::upLayout, and QCPLayoutElement::upPreparation.
                                          {
  QCPLayoutElement::update(phase);
  switch (phase) {
  case upPreparation: {
    QList<QCPAxis *> allAxes = axes();
    for (int i = 0; i < allAxes.size(); ++i)
      allAxes.at(i)->setupTickVectors();
    break;
  }
  case upLayout: {
    mInsetLayout->setOuterRect(rect());
    break;
  }
  default:
    break;
  }
  // pass update call on to inset layout (doesn't happen automatically, because
  // QCPAxisRect doesn't derive from QCPLayout):
  mInsetLayout->update(phase);
}
void QCPAxisRect::updateAxesOffset (QCPAxis::AxisType type) [protected]
Definition at line 13693 of file qcustomplot.cpp.
References i, and mAxes.
Referenced by calculateAutoMargin().
                                                       {
  const QList<QCPAxis *> axesList = mAxes.value(type);
  if (axesList.isEmpty())
    return;
  bool isFirstVisible =
      !axesList.first()->visible(); // if the first axis is visible, the second
                                    // axis (which is where the loop starts)
                                    // isn't the first visible axis, so
                                    // initialize with false
  for (int i = 1; i < axesList.size(); ++i) {
    int offset =
        axesList.at(i - 1)->offset() + axesList.at(i - 1)->calculateMargin();
    if (axesList.at(i)->visible()) // only add inner tick length to offset if
                                   // this axis is visible and it's not the
                                   // first visible one (might happen if true
                                   // first axis is invisible)
    {
      if (!isFirstVisible)
        offset += axesList.at(i)->tickLengthIn();
      isFirstVisible = false;
    }
    axesList.at(i)->setOffset(offset);
  }
}
void QCPAxisRect::wheelEvent (QWheelEvent * event) [protected], [virtual]
This event is called, if the mouse wheel is scrolled while the cursor is inside the rect of this layout element.
Reimplemented from QCPLayoutElement.
Definition at line 13857 of file qcustomplot.cpp.
References QCustomPlot::interactions(), QCP::iRangeZoom, QCPLayerable::mParentPlot, mRangeZoom, mRangeZoomFactorHorz, mRangeZoomFactorVert, mRangeZoomHorzAxis, mRangeZoomVertAxis, and QCustomPlot::replot().
                                               {
  // Mouse range zooming interaction:
  if (mParentPlot->interactions().testFlag(
      QCP::iRangeZoom)) {
    if (mRangeZoom != 0) {
      double factor;
      double wheelSteps =
          event->delta() / 120.0; // a single step delta is +/-120 usually
      if (mRangeZoom.testFlag(Qt::Horizontal)) {
        factor = qPow(mRangeZoomFactorHorz, wheelSteps);
        if (mRangeZoomHorzAxis.data())
          mRangeZoomHorzAxis.data()->scaleRange(
              factor,
              mRangeZoomHorzAxis.data()->pixelToCoord(event->pos().x()));
      }
      if (mRangeZoom.testFlag(Qt::Vertical)) {
        factor = qPow(mRangeZoomFactorVert, wheelSteps);
        if (mRangeZoomVertAxis.data())
          mRangeZoomVertAxis.data()->scaleRange(
              factor,
              mRangeZoomVertAxis.data()->pixelToCoord(event->pos().y()));
      }
      mParentPlot->replot();
    }
  }
}
int QCPAxisRect::width () const [inline]
Returns the pixel width of this axis rect. Margins are not taken into account here, so the returned value is with respect to the inner rect.
Definition at line 2355 of file qcustomplot.h.
Referenced by QCPAxis::coordToPixel(), QCPBarsGroup::getPixelSpacing(), QCPAxis::pixelToCoord(), and QCPAxis::setScaleRatio().
{ return mRect.width(); }
Friends And Related Function Documentation
friend class QCustomPlot [friend]
Definition at line 2404 of file qcustomplot.h.
Member Data Documentation
QCP::AntialiasedElements QCPAxisRect::mAADragBackup [protected]
Definition at line 2382 of file qcustomplot.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
QHash<QCPAxis::AxisType, QList<QCPAxis *> > QCPAxisRect::mAxes [protected]
Definition at line 2385 of file qcustomplot.h.
Referenced by addAxis(), axes(), axis(), axisCount(), calculateAutoMargin(), QCPAxisRect(), removeAxis(), and updateAxesOffset().
QBrush QCPAxisRect::mBackgroundBrush [protected]
Definition at line 2370 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
QPixmap QCPAxisRect::mBackgroundPixmap [protected]
Definition at line 2371 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
bool QCPAxisRect::mBackgroundScaled [protected]
Definition at line 2373 of file qcustomplot.h.
Referenced by drawBackground(), setBackground(), and setBackgroundScaled().
Qt::AspectRatioMode QCPAxisRect::mBackgroundScaledMode [protected]
Definition at line 2374 of file qcustomplot.h.
Referenced by drawBackground(), setBackground(), and setBackgroundScaledMode().
bool QCPAxisRect::mDragging [protected]
Definition at line 2384 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPoint QCPAxisRect::mDragStart [protected]
Definition at line 2383 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QCPRange QCPAxisRect::mDragStartHorzRange [protected]
Definition at line 2381 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QCPRange QCPAxisRect::mDragStartVertRange [protected]
Definition at line 2381 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QCPLayoutInset* QCPAxisRect::mInsetLayout [protected]
Definition at line 2375 of file qcustomplot.h.
Referenced by elements(), QCPAxisRect(), update(), and ~QCPAxisRect().
QCP::AntialiasedElements QCPAxisRect::mNotAADragBackup [protected]
Definition at line 2382 of file qcustomplot.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
Qt::Orientations QCPAxisRect::mRangeDrag [protected]
Definition at line 2376 of file qcustomplot.h.
Referenced by mouseMoveEvent(), and setRangeDrag().
QPointer<QCPAxis> QCPAxisRect::mRangeDragHorzAxis [protected]
Definition at line 2377 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mousePressEvent(), rangeDragAxis(), and setRangeDragAxes().
QPointer<QCPAxis> QCPAxisRect::mRangeDragVertAxis [protected]
Definition at line 2377 of file qcustomplot.h.
Referenced by mouseMoveEvent(), mousePressEvent(), rangeDragAxis(), and setRangeDragAxes().
Qt::Orientations QCPAxisRect::mRangeZoom [protected]
Definition at line 2376 of file qcustomplot.h.
Referenced by setRangeZoom(), and wheelEvent().
double QCPAxisRect::mRangeZoomFactorHorz [protected]
Definition at line 2379 of file qcustomplot.h.
Referenced by rangeZoomFactor(), setRangeZoomFactor(), and wheelEvent().
double QCPAxisRect::mRangeZoomFactorVert [protected]
Definition at line 2379 of file qcustomplot.h.
Referenced by rangeZoomFactor(), setRangeZoomFactor(), and wheelEvent().
QPointer<QCPAxis> QCPAxisRect::mRangeZoomHorzAxis [protected]
Definition at line 2377 of file qcustomplot.h.
Referenced by rangeZoomAxis(), setRangeZoomAxes(), and wheelEvent().
QPointer<QCPAxis> QCPAxisRect::mRangeZoomVertAxis [protected]
Definition at line 2377 of file qcustomplot.h.
Referenced by rangeZoomAxis(), setRangeZoomAxes(), and wheelEvent().
QPixmap QCPAxisRect::mScaledBackgroundPixmap [protected]
Definition at line 2372 of file qcustomplot.h.
Referenced by drawBackground(), and setBackground().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp