QCPGrid Class Reference
Responsible for drawing the grid of a QCPAxis.
#include <qcustomplot.h>
Public Member Functions
QCPGrid (QCPAxis *parentAxis)
bool subGridVisible () const
bool antialiasedSubGrid () const
bool antialiasedZeroLine () const
QPen pen () const
QPen subGridPen () const
QPen zeroLinePen () const
void setSubGridVisible (bool visible)
void setAntialiasedSubGrid (bool enabled)
void setAntialiasedZeroLine (bool enabled)
void setPen (const QPen &pen)
void setSubGridPen (const QPen &pen)
void setZeroLinePen (const QPen &pen)
Protected Member Functions
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
void drawGridLines (QCPPainter *painter) const
void drawSubGridLines (QCPPainter *painter) const
Protected Attributes
bool mSubGridVisible
bool mAntialiasedSubGrid
bool mAntialiasedZeroLine
QPen mPen
QPen mSubGridPen
QPen mZeroLinePen
QCPAxis * mParentAxis
Friends
class QCPAxis
Additional Inherited Members
Detailed Description
Responsible for drawing the grid of a QCPAxis.
This class is tightly bound to QCPAxis. Every axis owns a grid instance and uses it to draw the grid lines, sub grid lines and zero-line. You can interact with the grid of an axis via QCPAxis::grid. Normally, you don't need to create an instance of QCPGrid yourself.
The axis and grid drawing was split into two classes to allow them to be placed on different layers (both QCPAxis and QCPGrid inherit from QCPLayerable). Thus it is possible to have the grid in the background and the axes in the foreground, and any plottables/items in between. This described situation is the default setup, see the QCPLayer documentation.
Definition at line 1087 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPGrid::QCPGrid (QCPAxis * parentAxis)
Creates a QCPGrid instance and sets default values.
You shouldn't instantiate grids on their own, since every QCPAxis brings its own QCPGrid.
Definition at line 3974 of file qcustomplot.cpp.
References QCPLayerable::setAntialiased(), setAntialiasedSubGrid(), setAntialiasedZeroLine(), setPen(), setSubGridPen(), setSubGridVisible(), and setZeroLinePen().
    : QCPLayerable(parentAxis->parentPlot(), QString(), parentAxis),
      mParentAxis(parentAxis) {
  // warning: this is called in QCPAxis constructor, so parentAxis members
  // should not be accessed/called
  setParent(parentAxis);
  setPen(QPen(QColor(200, 200, 200), 0, Qt::DotLine));
  setSubGridPen(QPen(QColor(220, 220, 220), 0, Qt::DotLine));
  setZeroLinePen(QPen(QColor(200, 200, 200), 0, Qt::SolidLine));
  setSubGridVisible(false);
  setAntialiased(false);
  setAntialiasedSubGrid(false);
  setAntialiasedZeroLine(false);
}
Member Function Documentation
bool QCPGrid::antialiasedSubGrid () const [inline]
Definition at line 1104 of file qcustomplot.h.
{ return mAntialiasedSubGrid; }
bool QCPGrid::antialiasedZeroLine () const [inline]
Definition at line 1105 of file qcustomplot.h.
{ return mAntialiasedZeroLine; }
void QCPGrid::applyDefaultAntialiasingHint (QCPPainter * painter) const [protected], [virtual]
Implements QCPLayerable.
Definition at line 4046 of file qcustomplot.cpp.
References QCP::aeGrid, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
Referenced by drawGridLines().
                                                                    {
  applyAntialiasingHint(painter, mAntialiased,
      QCP::aeGrid);
}
void QCPGrid::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPLayerable.
Definition at line 4057 of file qcustomplot.cpp.
References drawGridLines(), drawSubGridLines(), mParentAxis, and mSubGridVisible.
                                      {
  if (!mParentAxis) {
    qDebug() << Q_FUNC_INFO << "invalid parent axis";
    return;
  }
  if (mSubGridVisible)
    drawSubGridLines(painter);
  drawGridLines(painter);
}
void QCPGrid::drawGridLines (QCPPainter * painter) const [protected]
Definition at line 4074 of file qcustomplot.cpp.
References QCP::aeZeroLine, QCPLayerable::applyAntialiasingHint(), applyDefaultAntialiasingHint(), QCPAxisRect::bottom(), QCPAxis::coordToPixel(), QCPPainter::drawLine(), i, QCPAxisRect::left(), QCPRange::lower, mAntialiasedZeroLine, QCPAxis::mAxisRect, QCPAxis::mHighestVisibleTick, QCPAxis::mLowestVisibleTick, mParentAxis, mPen, QCPAxis::mRange, QCPAxis::mTickVector, mZeroLinePen, QCPAxis::orientation(), QCPAxis::range(), QCPAxisRect::right(), QCPPainter::setPen(), QCPRange::size(), QCPAxisRect::top(), and QCPRange::upper.
Referenced by draw().
                                                     {
  if (!mParentAxis) {
    qDebug() << Q_FUNC_INFO << "invalid parent axis";
    return;
  }
  int lowTick = mParentAxis->mLowestVisibleTick;
  int highTick = mParentAxis->mHighestVisibleTick;
  double t; // helper variable, result of coordinate-to-pixel transforms
  if (mParentAxis->orientation() == Qt::Horizontal) {
    // draw zeroline:
    int zeroLineIndex = -1;
    if (mZeroLinePen.style() != Qt::NoPen && mParentAxis->
      mRange.lower < 0 &&
        mParentAxis->mRange.upper > 0) {
      applyAntialiasingHint(painter, mAntialiasedZeroLine,
      QCP::aeZeroLine);
      painter->setPen(mZeroLinePen);
      double epsilon =
          mParentAxis->range().size() * 1E-6; // for comparing double to zero
      for (int i = lowTick; i <= highTick; ++i) {
        if (qAbs(mParentAxis->mTickVector.at(i)) < epsilon) {
          zeroLineIndex = i;
          t = mParentAxis->coordToPixel(mParentAxis->
      mTickVector.at(i)); // x
          painter->drawLine(QLineF(t, mParentAxis->mAxisRect->
      bottom(), t,
                                   mParentAxis->mAxisRect->
      top()));
          break;
        }
      }
    }
    // draw grid lines:
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    for (int i = lowTick; i <= highTick; ++i) {
      if (i == zeroLineIndex)
        continue; // don't draw a gridline on top of the zeroline
      t = mParentAxis->coordToPixel(mParentAxis->
      mTickVector.at(i)); // x
      painter->drawLine(QLineF(t, mParentAxis->mAxisRect->
      bottom(), t,
                               mParentAxis->mAxisRect->top()));
    }
  } else {
    // draw zeroline:
    int zeroLineIndex = -1;
    if (mZeroLinePen.style() != Qt::NoPen && mParentAxis->
      mRange.lower < 0 &&
        mParentAxis->mRange.upper > 0) {
      applyAntialiasingHint(painter, mAntialiasedZeroLine,
      QCP::aeZeroLine);
      painter->setPen(mZeroLinePen);
      double epsilon =
          mParentAxis->mRange.size() * 1E-6; // for comparing double to zero
      for (int i = lowTick; i <= highTick; ++i) {
        if (qAbs(mParentAxis->mTickVector.at(i)) < epsilon) {
          zeroLineIndex = i;
          t = mParentAxis->coordToPixel(mParentAxis->
      mTickVector.at(i)); // y
          painter->drawLine(QLineF(mParentAxis->mAxisRect->
      left(), t,
                                   mParentAxis->mAxisRect->
      right(), t));
          break;
        }
      }
    }
    // draw grid lines:
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    for (int i = lowTick; i <= highTick; ++i) {
      if (i == zeroLineIndex)
        continue; // don't draw a gridline on top of the zeroline
      t = mParentAxis->coordToPixel(mParentAxis->
      mTickVector.at(i)); // y
      painter->drawLine(QLineF(mParentAxis->mAxisRect->
      left(), t,
                               mParentAxis->mAxisRect->right(), t));
    }
  }
}
void QCPGrid::drawSubGridLines (QCPPainter * painter) const [protected]
Definition at line 4150 of file qcustomplot.cpp.
References QCP::aeSubGrid, QCPLayerable::applyAntialiasingHint(), QCPAxisRect::bottom(), QCPAxis::coordToPixel(), QCPPainter::drawLine(), i, QCPAxisRect::left(), mAntialiasedSubGrid, QCPAxis::mAxisRect, mParentAxis, mSubGridPen, QCPAxis::mSubTickVector, QCPAxis::orientation(), QCPAxisRect::right(), QCPPainter::setPen(), and QCPAxisRect::top().
Referenced by draw().
                                                        {
  if (!mParentAxis) {
    qDebug() << Q_FUNC_INFO << "invalid parent axis";
    return;
  }
  applyAntialiasingHint(painter, mAntialiasedSubGrid,
      QCP::aeSubGrid);
  double t; // helper variable, result of coordinate-to-pixel transforms
  painter->setPen(mSubGridPen);
  if (mParentAxis->orientation() == Qt::Horizontal) {
    for (int i = 0; i < mParentAxis->mSubTickVector.size(); ++
      i) {
      t = mParentAxis->coordToPixel(mParentAxis->
      mSubTickVector.at(i)); // x
      painter->drawLine(QLineF(t, mParentAxis->mAxisRect->
      bottom(), t,
                               mParentAxis->mAxisRect->top()));
    }
  } else {
    for (int i = 0; i < mParentAxis->mSubTickVector.size(); ++
      i) {
      t = mParentAxis->coordToPixel(mParentAxis->
      mSubTickVector.at(i)); // y
      painter->drawLine(QLineF(mParentAxis->mAxisRect->
      left(), t,
                               mParentAxis->mAxisRect->right(), t));
    }
  }
}
QPen QCPGrid::pen () const [inline]
Definition at line 1106 of file qcustomplot.h.
Referenced by setPen(), setSubGridPen(), and setZeroLinePen().
{ return mPen; }
void QCPGrid::setAntialiasedSubGrid (bool enabled)
Sets whether sub grid lines are drawn antialiased.
Definition at line 3999 of file qcustomplot.cpp.
References mAntialiasedSubGrid.
Referenced by QCPGrid().
                                                {
  mAntialiasedSubGrid = enabled;
}
void QCPGrid::setAntialiasedZeroLine (bool enabled)
Sets whether zero lines are drawn antialiased.
Definition at line 4006 of file qcustomplot.cpp.
References mAntialiasedZeroLine.
Referenced by QCPGrid().
                                                 {
  mAntialiasedZeroLine = enabled;
}
void QCPGrid::setPen (const QPen & pen)
Sets the pen with which (major) grid lines are drawn.
Definition at line 4013 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPGrid().
{ mPen = pen; }
void QCPGrid::setSubGridPen (const QPen & pen)
Sets the pen with which sub grid lines are drawn.
Definition at line 4018 of file qcustomplot.cpp.
References mSubGridPen, and pen().
Referenced by QCPGrid().
{ mSubGridPen = pen; }
void QCPGrid::setSubGridVisible (bool visible)
Sets whether grid lines at sub tick marks are drawn.
See also
setSubGridPen
Definition at line 3994 of file qcustomplot.cpp.
References mSubGridVisible, and QCPLayerable::visible().
Referenced by QCPGrid().
{ mSubGridVisible = visible; }
void QCPGrid::setZeroLinePen (const QPen & pen)
Sets the pen with which zero lines are drawn.
Zero lines are lines at value coordinate 0 which may be drawn with a different pen than other grid lines. To disable zero lines and just draw normal grid lines at zero, set pen to Qt::NoPen.
Definition at line 4028 of file qcustomplot.cpp.
References mZeroLinePen, and pen().
Referenced by QCPAxisRect::QCPAxisRect(), and QCPGrid().
{ mZeroLinePen = pen; }
QPen QCPGrid::subGridPen () const [inline]
Definition at line 1107 of file qcustomplot.h.
{ return mSubGridPen; }
bool QCPGrid::subGridVisible () const [inline]
Definition at line 1103 of file qcustomplot.h.
{ return mSubGridVisible; }
QPen QCPGrid::zeroLinePen () const [inline]
Definition at line 1108 of file qcustomplot.h.
{ return mZeroLinePen; }
Friends And Related Function Documentation
friend class QCPAxis [friend]
Definition at line 1134 of file qcustomplot.h.
Member Data Documentation
bool QCPGrid::mAntialiasedSubGrid [protected]
Definition at line 1121 of file qcustomplot.h.
Referenced by drawSubGridLines(), and setAntialiasedSubGrid().
bool QCPGrid::mAntialiasedZeroLine [protected]
Definition at line 1121 of file qcustomplot.h.
Referenced by drawGridLines(), and setAntialiasedZeroLine().
QCPAxis* QCPGrid::mParentAxis [protected]
Definition at line 1124 of file qcustomplot.h.
Referenced by draw(), drawGridLines(), and drawSubGridLines().
QPen QCPGrid::mPen [protected]
Definition at line 1122 of file qcustomplot.h.
Referenced by drawGridLines(), and setPen().
QPen QCPGrid::mSubGridPen [protected]
Definition at line 1122 of file qcustomplot.h.
Referenced by drawSubGridLines(), and setSubGridPen().
bool QCPGrid::mSubGridVisible [protected]
Definition at line 1120 of file qcustomplot.h.
Referenced by draw(), and setSubGridVisible().
QPen QCPGrid::mZeroLinePen [protected]
Definition at line 1122 of file qcustomplot.h.
Referenced by drawGridLines(), and setZeroLinePen().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp