SoilAnalyzer::Sample Class Reference
The Sample class.
#include <Sample.h>
Public Types
typedef boost::signals2::signal< void(float, std::string)> Progress_t
Public Member Functions
boost::signals2::connection connect_Progress (const Progress_t::slot_type &subscriber)
connect_Progress used to connect the progress signal
Sample (SoilSettings *settings=nullptr)
Sample the constructor.
Sample (const Mat &src, SoilSettings *settings=nullptr)
Sample the constructor.
~Sample ()
The Deconstructor.
void PrepImg (SoilSettings *settings=nullptr)
PrepImg Prep te image for analysis.
void Analyse (SoilMath::NN &nn)
Analyse the RGB image.
void Analyse (const Mat &src, SoilMath::NN &nn)
Analyse the the RGB image.
void Save (string &filename)
Save the SoilSample to disk.
void Load (string &filename)
Load the SoilSample from disk.
Public Attributes
cv::Mat OriginalImage
vector< Particle > Population
AnalysisResults Results
SoilSettings * Settings
bool imgPrepped = false
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
bool AnalysePopVect (const vector< Particle > &population, AnalysisResults &results)
AnalysePopVect analyse the particle population vector.
void SegmentParticles (Vision::Segment::SegmentationType segType=Vision::Segment::Normal)
SegmentParticles.
Private Attributes
Progress_t prog_sig
Friends
class boost::serialization::access
Additional Inherited Members
Detailed Description
The Sample class.
This class represent a single soilsample snapshot it inherents from the class Soil
Definition at line 44 of file Sample.h.
Member Typedef Documentation
typedef boost::signals2::signal<void(float, std::string)> SoilAnalyzer::Sample::Progress_t
A boost signal, used for progress update indicating the progres so far as a float between 0. and 1. and the current progress step as string
Definition at line 47 of file Sample.h.
Constructor & Destructor Documentation
SoilAnalyzer::Sample::Sample (SoilSettings * settings = nullptr)
Sample the constructor.
Parameters
settings a pointer to the an object of the type SoilSettings used to initalize the analyzing settings
Definition at line 11 of file Sample.cpp.
References Settings.
{ Settings = settings; }
SoilAnalyzer::Sample::Sample (const Mat & src, SoilSettings * settings = nullptr)
Sample the constructor.
Parameters
src the source rgb image
settings a pointer to the an object of the type SoilSettings used to initalize the analyzing settings
Definition at line 13 of file Sample.cpp.
References OriginalImage, and Settings.
                                                     {
  Settings = settings;
  OriginalImage = src.clone();
}
SoilAnalyzer::Sample::~Sample ()
The Deconstructor.
Definition at line 18 of file Sample.cpp.
{}
Member Function Documentation
void SoilAnalyzer::Sample::Analyse (SoilMath::NN & nn)
Analyse the RGB image.
Parameters
nn a reference to the neural network used during analyzing
Definition at line 173 of file Sample.cpp.
References imgPrepped, and PrepImg().
Referenced by Analyse(), BOOST_FIXTURE_TEST_CASE(), and VSAGUI::on_AnalyzeButton_clicked().
                                   {
  if (!imgPrepped) {
    PrepImg();
  }
  // Calculate the statistics CIE La*b*
  // vector<Mat> LABextract = Vision::ImageProcessing::extractChannel(LAB);
  // for_each(LABextract.begin(), LABextract.end(), [&](Mat &lab) {
  // Results.LAB_Stat.push_back(floatStat_t((float *)lab.data, lab.rows,
  // lab.cols)); });
  // Calculate the statistics RI
  // Results.RI_Stat = floatStat_t((float *)RI.data, RI.rows, RI.cols);
  // Segment and analyze the particles
  // SegmentParticles();
  // for_each(Population.begin(), Population.end(), [&](Particle &P)
  //{
  // P.Analyze(nn);
  //});
  // Analyze the image
}
void SoilAnalyzer::Sample::Analyse (const Mat & src, SoilMath::NN & nn)
Analyse the the RGB image.
Parameters
src the RGB image with needs to be analysed
nn a reference to the neural network used during analyzing
Definition at line 196 of file Sample.cpp.
References Analyse(), and OriginalImage.
                                                   {
  OriginalImage = src;
  Analyse(nn);
}
bool SoilAnalyzer::Sample::AnalysePopVect (const vector< Particle > & population, AnalysisResults & results) [private]
AnalysePopVect analyse the particle population vector.
Parameters
population a reference to individual particles
results
Returns
Definition at line 201 of file Sample.cpp.
                                                      {
  return true;
}
boost::signals2::connection SoilAnalyzer::Sample::connect_Progress (const Progress_t::slot_type & subscriber)
connect_Progress used to connect the progress signal
Parameters
subscriber a reference to the subscriber
Returns
returns the signal
Definition at line 257 of file Sample.cpp.
References prog_sig.
Referenced by VSAGUI::on_actionLoad_triggered(), VSAGUI::on_actionNew_triggered(), VSAGUI::on_SnapshotButton_clicked(), and VSAGUI::VSAGUI().
                                                              {
  return prog_sig.connect(subscriber);
}
void SoilAnalyzer::Sample::Load (string & filename)
Load the SoilSample from disk.
Parameters
filename where the saved Soilsample can be found
Definition at line 26 of file Sample.cpp.
Referenced by BOOST_FIXTURE_TEST_CASE(), and VSAGUI::on_actionLoad_triggered().
                                  {
  std::ifstream ifs(filename.c_str());
  boost::archive::binary_iarchive ia(ifs);
  ia >> boost::serialization::make_nvp("SoilSample", *this);
}
void SoilAnalyzer::Sample::PrepImg (SoilSettings * settings = nullptr)
PrepImg Prep te image for analysis.
Parameters
settings a pointer to the an object of the type SoilSettings used to initalize the analyzing settings
Definition at line 32 of file Sample.cpp.
References SoilAnalyzer::SoilSettings::adaptContrastKernelSize, Vision::Enhance::AdaptiveContrastStretch(), Vision::Enhance::Blur(), SoilAnalyzer::SoilSettings::blurKernelSize, SoilAnalyzer::Soil::BW, Vision::Conversion::CIE_lab, circle, Vision::MorphologicalFilter::CLOSE, Vision::MorphologicalFilter::Close(), Vision::Conversion::Convert(), Vision::Segment::ConvertToBW(), Vision::ImageProcessing::CopyMat(), Vision::MorphologicalFilter::DILATE, Vision::MorphologicalFilter::Dilation(), SoilAnalyzer::Soil::Edge, Vision::MorphologicalFilter::ERODE, Vision::MorphologicalFilter::Erosion(), SoilAnalyzer::SoilSettings::fillHoles, Vision::Segment::FillHoles(), SoilAnalyzer::SoilSettings::filterMaskSize, Vision::Segment::GetEdgesEroding(), SoilAnalyzer::SoilSettings::ignorePartialBorderParticles, imgPrepped, Vision::Conversion::Intensity, SoilAnalyzer::Soil::Intensity, SoilAnalyzer::Soil::LAB, mask, SoilAnalyzer::SoilSettings::morphFilterType, Vision::MorphologicalFilter::NONE, Vision::MorphologicalFilter::OPEN, Vision::MorphologicalFilter::Open(), SoilAnalyzer::Soil::OptimizedInt, OriginalImage, Vision::ImageProcessing::OriginalImg, Vision::ImageProcessing::ProcessedImg, PROG_INCR, prog_sig, Vision::Segment::RemoveBorderBlobs(), Vision::Conversion::RGB, SoilAnalyzer::Soil::RGB, Vision::Conversion::RI, SoilAnalyzer::Soil::RI, Settings, SHOW_DEBUG_IMG, Vision::Segment::sigma, SoilAnalyzer::SoilSettings::sigmaFactor, Vision::Segment::thresholdOffset, SoilAnalyzer::SoilSettings::thresholdOffsetValue, SoilAnalyzer::SoilSettings::typeOfObjectsSegmented, SoilAnalyzer::SoilSettings::useAdaptiveContrast, and SoilAnalyzer::SoilSettings::useBlur.
Referenced by Analyse(), VSAGUI::on_SegmentButton_clicked(), and VSAGUI::on_verticalSlider_sliderReleased().
                                           {
  // setup the settings
  if (settings == nullptr && Settings == nullptr) {
    Settings = new SoilSettings;
  } else {
    Settings = settings;
  }
  // set up the progress signal
  float currentProg = 0.;
  prog_sig(currentProg, "Starting segmentation");
  uint32_t totalsteps = 5;
  if (Settings->useAdaptiveContrast) {
    totalsteps++;
  }
  if (Settings->useBlur) {
    totalsteps++;
  }
  if (Settings->fillHoles) {
    totalsteps++;
  }
  if (Settings->ignorePartialBorderParticles) {
    totalsteps++;
  }
  if (Settings->morphFilterType !=
      Vision::MorphologicalFilter::NONE) {
    totalsteps++;
  }
  float progstep = 1. / static_cast<float>(totalsteps);
  if (OriginalImage.empty()) {
    throw Exception::AnalysisException("No Image found to analyze!", 1);
  }
  SHOW_DEBUG_IMG(OriginalImage, uchar, 255, "RGB", false);
  // Convert the image to an intensity image and an enhanced Intinsity for
  // better segmentation
  Vision::Conversion RGBConvertor(OriginalImage);
  RGBConvertor.Convert(Vision::Conversion::RGB,
      Vision::Conversion::Intensity);
  PROG_INCR("Converted to intensity");
  Intensity = RGBConvertor.ProcessedImg.clone();
  SHOW_DEBUG_IMG(Intensity, uchar, 255, "Intensity", false);
  // Enhance the image with an Adaptive contrast stretch and/or followed by a
  // blur
  Vision::Enhance IntEnchance(Intensity);
  if (Settings->useAdaptiveContrast) {
    IntEnchance.AdaptiveContrastStretch(Settings->
      adaptContrastKernelSize,
                                        Settings->
      adaptContrastKernelSize);
    PROG_INCR("Adaptive contrast stretch applied");
    if (Settings->useBlur) {
      IntEnchance.Blur(Settings->blurKernelSize, true);
      PROG_INCR("Blur applied");
    }
  } else if (Settings->useBlur) {
    IntEnchance.Blur(Settings->blurKernelSize, false);
    PROG_INCR("Blur applied");
  } else {
    IntEnchance.ProcessedImg = IntEnchance.OriginalImg;
  }
  OptimizedInt =
      IntEnchance.ProcessedImg(cv::Rect(10, 10, OriginalImage.cols - 20,
                                        OriginalImage.rows - 20)).clone();
  SHOW_DEBUG_IMG(OptimizedInt, uchar, 255, "IntEnchance", false);
  // Segment the Dark Objects en fill the holes
  Vision::Segment Segmenter(OptimizedInt);
  Segmenter.sigma = Settings->sigmaFactor;
  Segmenter.thresholdOffset = Settings->thresholdOffsetValue;
  Segmenter.ConvertToBW(Settings->typeOfObjectsSegmented);
  PROG_INCR("Threshold applied");
  if (Settings->fillHoles) {
    Segmenter.FillHoles(true);
    PROG_INCR("Holes filled");
  }
  if (Settings->ignorePartialBorderParticles) {
    Segmenter.RemoveBorderBlobs(1, true);
    PROG_INCR("Border Blobs removed");
  }
  SHOW_DEBUG_IMG(Segmenter.ProcessedImg, uchar, 255, "Segmenter", true);
  // Erode the segmented image and sets the BW image use it to create the NO
  // background RGB
  Vision::MorphologicalFilter Filter(Segmenter.ProcessedImg);
  uint kSize = Settings->filterMaskSize;
  Mat mask = cv::Mat::zeros(kSize, kSize, CV_8UC1);
  circle(mask, Point(kSize / 2, kSize / 2), (kSize / 2) + 1, 1, -1);
  switch (Settings->morphFilterType) {
  case Vision::MorphologicalFilter::CLOSE:
    Filter.Close(mask);
    PROG_INCR("Morphological filer - close applied");
    break;
  case Vision::MorphologicalFilter::DILATE:
    Filter.Dilation(mask);
    PROG_INCR("Morphological filer - dilate applied");
    break;
  case Vision::MorphologicalFilter::ERODE:
    Filter.Erosion(mask);
    PROG_INCR("Morphological filer - erode applied");
    break;
  case Vision::MorphologicalFilter::OPEN:
    Filter.Open(mask);
    PROG_INCR("Morphological filer - open applied");
    break;
  case Vision::MorphologicalFilter::NONE:
    Filter.ProcessedImg = Filter.OriginalImg;
  }
  BW = Filter.ProcessedImg.clone();
  SHOW_DEBUG_IMG(BW, uchar, 255,
                 "BW after segmentation, fill holes and erosion", true);
  RGB = Vision::ImageProcessing::CopyMat<uchar>(
      OriginalImage(cv::Rect(10, 10, OriginalImage.cols - 20,
                             OriginalImage.rows - 20)).clone(),
      BW, CV_8UC1);
  PROG_INCR("RGB masked image generated");
  SHOW_DEBUG_IMG(RGB, uchar, 255, "RGB no Background", false);
  // Create the Edge image
  Vision::Segment Edger(BW);
  Edger.GetEdgesEroding();
  Edge = Edger.ProcessedImg;
  PROG_INCR("Edge filter applied");
  SHOW_DEBUG_IMG(Edge, uchar, 255, "Edge", true);
  // Make the CIE La*b* conversion
  Vision::Conversion RGBnewConvertor(RGB);
  RGBnewConvertor.Convert(Vision::Conversion::RGB,
      Vision::Conversion::CIE_lab);
  LAB = RGBnewConvertor.CopyMat<float>(RGB, BW, CV_32F);
  PROG_INCR("CIE La*b* conversion calculated");
  SHOW_DEBUG_IMG(LAB, float, 1.0, "LAB", true);
  // Create the Redness Index
  Vision::Conversion LABConvertor(LAB);
  LABConvertor.Convert(Vision::Conversion::CIE_lab,
      Vision::Conversion::RI);
  RI = LABConvertor.ProcessedImg;
  PROG_INCR("Redness conversion calculated");
  SHOW_DEBUG_IMG(RI, float, 1.0, "RI", true);
  imgPrepped = true;
}
void SoilAnalyzer::Sample::Save (string & filename)
Save the SoilSample to disk.
Parameters
filename the where to save
Definition at line 20 of file Sample.cpp.
Referenced by BOOST_FIXTURE_TEST_CASE(), and VSAGUI::on_actionSave_triggered().
                                  {
  std::ofstream ofs(filename.c_str());
  boost::archive::binary_oarchive oa(ofs);
  oa << boost::serialization::make_nvp("SoilSample", *this);
}
void SoilAnalyzer::Sample::SegmentParticles (Vision::Segment::SegmentationType segType = Vision::Segment::Normal) [private]
SegmentParticles.
Parameters
segType
Definition at line 206 of file Sample.cpp.
References Vision::Enhance::AdaptiveContrastStretch(), Vision::Segment::BlobList, Vision::Enhance::Blur(), SoilAnalyzer::Soil::BW, Vision::Segment::ConvertToBW(), Vision::Segment::Dark, SoilAnalyzer::Soil::Edge, Vision::Segment::GetBlobList(), Vision::Segment::GetEdgesEroding(), Vision::Segment::GraphMinCut, i, SoilAnalyzer::Soil::Intensity, SoilAnalyzer::Soil::LAB, Vision::Segment::LabNeuralNet, Vision::Segment::LoadOriginalImg(), Vision::Segment::Normal, Population, Vision::ImageProcessing::ProcessedImg, and Vision::Segment::RemoveBorderBlobs().
                                                                   {
  Vision::Enhance Enhancer(Intensity);
  Vision::Segment Segmenter;
  Vision::MorphologicalFilter Eroder;
  switch (segType) {
  case Vision::Segment::Normal:
    // Optimize the intensity image
    Enhancer.Blur(15);
    Enhancer.AdaptiveContrastStretch(5, 0.125, true);
    // Segment the enhance image and remove borderblobs get the edges
    Segmenter.LoadOriginalImg(Enhancer.ProcessedImg);
    Segmenter.ConvertToBW(Vision::Segment::Dark);
    Segmenter.RemoveBorderBlobs(1, true);
    BW = Segmenter.ProcessedImg.clone();
    break;
  case Vision::Segment::LabNeuralNet:
    throw Exception::AnalysisException("Not yet implemented!", 1);
    break;
  case Vision::Segment::GraphMinCut:
    throw Exception::AnalysisException("Not yet implemented!", 1);
    break;
  default:
    break;
  }
  Vision::Segment getEdges(BW);
  getEdges.GetEdgesEroding();
  Edge = getEdges.ProcessedImg;
  // Get the Particlelist
  Segmenter.GetBlobList(true);
  Population.resize(Segmenter.BlobList.size());
  uint32_t i = 0;
  for_each(Population.begin(), Population.end(), [&](Particle &P) {
    P.ID = Segmenter.BlobList[i].Label;
    P.Analysis.Analyzed = false;
    P.BW = Segmenter.BlobList[i].Img.clone();
    cv::Rect ROI = Segmenter.BlobList[i].ROI;
    P.Intensity =
        Vision::Segment::CopyMat<uchar>(Intensity(ROI).clone(), P.BW, CV_8UC1);
    P.LAB = Vision::Segment::CopyMat<float>(LAB(ROI).clone(), P.BW, CV_32FC3);
    P.RGB = Vision::Segment::CopyMat<uchar>(LAB(ROI).clone(), P.BW, CV_8UC3);
    P.RI = Vision::Segment::CopyMat<float>(LAB(ROI).clone(), P.BW, CV_32FC1);
    P.Edge = Vision::Segment::CopyMat<uchar>(Edge(ROI).clone(), P.BW, CV_8UC1);
    i++;
  });
}
template<class Archive > void SoilAnalyzer::Sample::serialize (Archive & ar, const unsigned int version) [inline], [private]
Definition at line 125 of file Sample.h.
                                                          {
    ar &BOOST_SERIALIZATION_BASE_OBJECT_NVP(Soil);
    ar &OriginalImage;
    ar &Population;
    ar &Results;
    ar &Settings;
    ar &imgPrepped;
  }
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 123 of file Sample.h.
Member Data Documentation
bool SoilAnalyzer::Sample::imgPrepped = false
Definition at line 93 of file Sample.h.
Referenced by Analyse(), VSAGUI::on_verticalSlider_sliderReleased(), and PrepImg().
cv::Mat SoilAnalyzer::Sample::OriginalImage
The original image
Definition at line 80 of file Sample.h.
Referenced by Analyse(), BOOST_FIXTURE_TEST_CASE(), VSAGUI::on_actionLoad_triggered(), VSAGUI::on_SnapshotButton_clicked(), PrepImg(), Sample(), and VSAGUI::VSAGUI().
vector<Particle> SoilAnalyzer::Sample::Population
a Vector with original particles
Definition at line 81 of file Sample.h.
Referenced by SegmentParticles().
Progress_t SoilAnalyzer::Sample::prog_sig [private]
The progress signal
Definition at line 121 of file Sample.h.
Referenced by connect_Progress(), and PrepImg().
AnalysisResults SoilAnalyzer::Sample::Results
The analysis results
Definition at line 82 of file Sample.h.
SoilSettings* SoilAnalyzer::Sample::Settings
Initial value:
=
      nullptr
The Settings used to initialize the analyzis
Definition at line 84 of file Sample.h.
Referenced by PrepImg(), and Sample().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/Soil/Sample.h
/home/peer23peer/VisionSoilAnalyzer/src/Soil/Sample.cpp