SoilMath::GA Class Reference
#include <GA.h>
Public Member Functions
GA ()
GA Standard constructor.
GA (NNfunctionType nnfunction, uint32_t inputneurons, uint32_t hiddenneurons, uint32_t outputneurons)
GA Construction with a Neural Network initializers.
~GA ()
GA standard de constructor.
void Evolve (const ComplexVect_t &inputValues, Weight_t &weights, std::vector< Weight_t > &prevWeights, MinMaxWeight_t rangeweights, Predict_t goal, uint32_t maxGenerations=200, uint32_t popSize=30)
Evolve Darwin would be proud!!! This function creates a population and itterates through the generation till the maximum number off itterations has been reached of the error is acceptable.
void Evolve (const InputLearnVector_t &inputValues, Weight_t &weights, MinMaxWeight_t rangeweights, OutputLearnVector_t &goal, uint32_t maxGenerations=200, uint32_t popSize=30)
Evolve Darwin would be proud!!! This function creates a population and itterates through the generation till the maximum number off itterations has been reached of the error is acceptable.
Private Member Functions
Population_t Genesis (const Weight_t &weights, MinMaxWeight_t rangeweights, uint32_t popSize)
Genesis private function which is the spark of live, using a random seed.
void CrossOver (Population_t &pop)
CrossOver a private function where the partners mate with each other The values or PopMember_t are expressed as bits or ar cut at the point CROSSOVER the population members are paired with the nearest neighbor and new members are created pairing the Genome_t of each other at the CROSSOVER point. Afterwards all the top tiers partners are allowed to mate again.
void Mutate (Population_t &pop)
Mutate a private function where individual bits from the Genome_t are mutated at a random uniform distribution event defined by the MUTATIONRATE.
void GrowToAdulthood (Population_t &pop, const ComplexVect_t &inputValues, MinMaxWeight_t rangeweights, Predict_t goal, float &totalFitness)
GrowToAdulthood a private function where the new population members serve as the the input for the Neural Network prediction function. The results are weight against the goal and this weight determine the fitness of the population member.
void GrowToAdulthood (Population_t &pop, const InputLearnVector_t &inputValues, MinMaxWeight_t rangeweights, OutputLearnVector_t &goal, float &totalFitness)
GrowToAdulthood a private function where the new population members serve as the the input for the Neural Network prediction function. The results are weight against the goal and this weight determine the fitness of the population member.
bool SurvivalOfTheFittest (Population_t &pop, float &totalFitness)
SurvivalOfTheFittest a private function where a battle to the death commences The fittest population members have the best chance of survival. Death is instigated with a random uniform distibution. The elite members don't partake in this desctruction The ELITISME rate indicate how many top tier members survive this catastrophic event.
template<typename T >
Genome_t ConvertToGenome (T value, std::pair< T, T > range)
Conversion of the value of type T to Genome_t.
template<typename T >
T ConvertToValue (Genome_t gen, std::pair< T, T > range)
Conversion of the Genome to a value.
Static Private Member Functions
static bool PopMemberSort (PopMember_t i, PopMember_t j)
PopMemberSort a private function where the members are sorted according to there fitness ranking.
Private Attributes
NNfunctionType NNfuction
uint32_t inputneurons
uint32_t hiddenneurons
uint32_t outputneurons
Detailed Description
Definition at line 27 of file GA.h.
Constructor & Destructor Documentation
SoilMath::GA::GA ()
GA Standard constructor.
Definition at line 11 of file GA.cpp.
{}
SoilMath::GA::GA (NNfunctionType nnfunction, uint32_t inputneurons, uint32_t hiddenneurons, uint32_t outputneurons)
GA Construction with a Neural Network initializers.
Parameters
nnfunction the Neural Network prediction function which results will be optimized
inputneurons the number of input neurons in the Neural Network don't count the bias
hiddenneurons the number of hidden neurons in the Neural Network don't count the bias
outputneurons the number of output neurons in the Neural Network
Definition at line 13 of file GA.cpp.
References hiddenneurons, inputneurons, NNfuction, and outputneurons.
                               {
  this->NNfuction = nnfunction;
  this->inputneurons = inputneurons;
  this->hiddenneurons = hiddenneurons;
  this->outputneurons = outputneurons;
}
SoilMath::GA::~GA ()
GA standard de constructor.
Definition at line 21 of file GA.cpp.
{}
Member Function Documentation
template<typename T > Genome_t SoilMath::GA::ConvertToGenome (T value, std::pair< T, T > range) [inline], [private]
Conversion of the value of type T to Genome_t.
Usage: Use ConvertToGenome<Type>(type, range)
Parameters
value The current value wich should be converted to a Genome_t
range the range in which the value should fall, this is to have a Genome_t which utilizes the complete range 0000...n till 1111...n
Definition at line 189 of file GA.h.
                                                                {
    uint32_t intVal = static_cast<uint32_t>(
        (UINT32_MAX * (range.first + value)) / (range.second - range.first));
    Genome_t retVal(intVal);
    return retVal;
  }
template<typename T > T SoilMath::GA::ConvertToValue (Genome_t gen, std::pair< T, T > range) [inline], [private]
Conversion of the Genome to a value.
Usage: use ConvertToValue<Type>(genome, range)
Parameters
gen is the Genome which is to be converted
range is the range in which the value should fall
Definition at line 203 of file GA.h.
                                                             {
    T retVal =
        range.first +
        (((range.second - range.first) * static_cast<T>(gen.to_ulong())) /
         UINT32_MAX);
    return retVal;
  }
void SoilMath::GA::CrossOver (Population_t & pop) [private]
CrossOver a private function where the partners mate with each other The values or PopMember_t are expressed as bits or ar cut at the point CROSSOVER the population members are paired with the nearest neighbor and new members are created pairing the Genome_t of each other at the CROSSOVER point. Afterwards all the top tiers partners are allowed to mate again.
Parameters
pop reference to the population
Definition at line 94 of file GA.cpp.
References CROSSOVER, GENE_MAX, i, j, and PopMemberStruct::weightsGen.
Referenced by Evolve().
                                    {
  Population_t newPop; // create a new population
  PopMember_t newPopMembers[2];
  SplitGenome_t Split[2];
  for (uint32_t i = 0; i < pop.size(); i += 2) {
    for (uint32_t j = 0; j < pop[i].weights.size(); j++) {
      // Split A
      Split[0].first = bitset<CROSSOVER>(
          pop[i].weightsGen[j].to_string().substr(0, CROSSOVER));
      Split[0].second =
          bitset<GENE_MAX - CROSSOVER>(pop[i].weightsGen[j].to_string().substr(
              CROSSOVER, GENE_MAX - CROSSOVER));
      // Split B
      Split[1].first = bitset<CROSSOVER>(
          pop[i + 1].weightsGen[j].to_string().substr(0, CROSSOVER));
      Split[1].second = bitset<GENE_MAX - CROSSOVER>(
          pop[i + 1].weightsGen[j].to_string().substr(CROSSOVER,
                                                      GENE_MAX -
      CROSSOVER));
      // Mate A and B to AB and BA
      newPopMembers[0].weightsGen.push_back(
          Genome_t(Split[0].first.to_string() + Split[1].second.to_string()));
      newPopMembers[1].weightsGen.push_back(
          Genome_t(Split[1].first.to_string() + Split[0].second.to_string()));
    }
    newPop.push_back(newPopMembers[0]);
    newPop.push_back(newPopMembers[1]);
    newPopMembers[0].weightsGen.clear();
    newPopMembers[1].weightsGen.clear();
  }
  // Allow the top tiers population partners to mate again
  uint32_t halfN = pop.size() / 2;
  for (uint32_t i = 0; i < halfN; i++) {
    for (uint32_t j = 0; j < pop[i].weights.size(); j++) {
      Split[0].first = bitset<CROSSOVER>(
          pop[i].weightsGen[j].to_string().substr(0, CROSSOVER));
      Split[0].second =
          bitset<GENE_MAX - CROSSOVER>(pop[i].weightsGen[j].to_string().substr(
              CROSSOVER, GENE_MAX - CROSSOVER));
      Split[1].first = bitset<CROSSOVER>(
          pop[i + 2].weightsGen[j].to_string().substr(0, CROSSOVER));
      Split[1].second = bitset<GENE_MAX - CROSSOVER>(
          pop[i + 2].weightsGen[j].to_string().substr(CROSSOVER,
                                                      GENE_MAX -
      CROSSOVER));
      newPopMembers[0].weightsGen.push_back(
          Genome_t(Split[0].first.to_string() + Split[1].second.to_string()));
      newPopMembers[1].weightsGen.push_back(
          Genome_t(Split[1].first.to_string() + Split[0].second.to_string()));
    }
    newPop.push_back(newPopMembers[0]);
    newPop.push_back(newPopMembers[1]);
    newPopMembers[0].weightsGen.clear();
    newPopMembers[1].weightsGen.clear();
  }
  pop = newPop;
}
void SoilMath::GA::Evolve (const ComplexVect_t & inputValues, Weight_t & weights, std::vector< Weight_t > & prevWeights, MinMaxWeight_t rangeweights, Predict_t goal, uint32_t maxGenerations = 200, uint32_t popSize = 30)
Evolve Darwin would be proud!!! This function creates a population and itterates through the generation till the maximum number off itterations has been reached of the error is acceptable.
Parameters
inputValues complex vector with a reference to the inputvalues
weights reference to the vector of weights which will be optimized
prevWeights pointer to the pevious weight results
rangeweights pointer to the range of weights, currently it doesn't support indivudal ranges this is because of the crossing
goal target value towards the Neural Network prediction function will be optimized
maxGenerations maximum number of itterations default value is 200
popSize maximum number of population, this should be an even number
Definition at line 23 of file GA.cpp.
References CrossOver(), Genesis(), GrowToAdulthood(), i, j, Mutate(), SurvivalOfTheFittest(), PopMemberStruct::weights, and PopMemberStruct::weightsGen.
Referenced by SoilMath::NN::Learn().
                                                                           {
  // Create the population
  uint32_t NOprevPopUsed =
      prevWeights.size() < popSize ? prevWeights.size() : popSize;
  Population_t pop = Genesis(weights, rangeweights, popSize - NOprevPopUsed);
  for (uint32_t i = 0; i < NOprevPopUsed; i++) {
    PopMember_t newMember;
    newMember.weights = prevWeights[i];
    for (uint32_t j = 0; j < newMember.weights.size(); j++) {
      newMember.weightsGen.push_back(
          ConvertToGenome<float>(newMember.weights[j], rangeweights));
    }
    pop.push_back(newMember);
  }
  float totalFitness = 0.0;
  for (uint32_t i = 0; i < maxGenerations; i++) {
    CrossOver(pop);
    Mutate(pop);
    totalFitness = 0.0;
    GrowToAdulthood(pop, inputValues, rangeweights, goal, totalFitness);
    if (SurvivalOfTheFittest(pop, totalFitness)) {
      break;
    }
  }
  weights = pop[0].weights;
}
void SoilMath::GA::Evolve (const InputLearnVector_t & inputValues, Weight_t & weights, MinMaxWeight_t rangeweights, OutputLearnVector_t & goal, uint32_t maxGenerations = 200, uint32_t popSize = 30)
Evolve Darwin would be proud!!! This function creates a population and itterates through the generation till the maximum number off itterations has been reached of the error is acceptable.
Parameters
inputValues complex vector with a reference to the inputvalues
weights reference to the vector of weights which will be optimized
rangeweights reference to the range of weights, currently it doesn't support indivudal ranges this is because of the crossing
goal target value towards the Neural Network prediction function will be optimized
maxGenerations maximum number of itterations default value is 200
popSize maximum number of population, this should be an even number
Definition at line 53 of file GA.cpp.
References CrossOver(), Genesis(), GrowToAdulthood(), i, Mutate(), and SurvivalOfTheFittest().
                                                           {
  // Create the population
  Population_t pop = Genesis(weights, rangeweights, popSize);
  float totalFitness = 0.0;
  for (uint32_t i = 0; i < maxGenerations; i++) {
    CrossOver(pop);
    Mutate(pop);
    totalFitness = 0.0;
    GrowToAdulthood(pop, inputValues, rangeweights, goal, totalFitness);
    if (SurvivalOfTheFittest(pop, totalFitness)) {
      break;
    }
  }
  weights = pop[0].weights;
}
Population_t SoilMath::GA::Genesis (const Weight_t & weights, MinMaxWeight_t rangeweights, uint32_t popSize) [private]
Genesis private function which is the spark of live, using a random seed.
Parameters
weights a reference to the used Weight_t vector
rangeweights pointer to the range of weights, currently it doesn't support indivudal ranges
popSize maximum number of population, this should be an even number
Returns
Definition at line 71 of file GA.cpp.
References I, i, j, PopMemberStruct::weights, and PopMemberStruct::weightsGen.
Referenced by Evolve().
                                           {
  if (popSize < 1)
    return Population_t();
  Population_t pop;
  unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
  std::default_random_engine gen(seed);
  std::uniform_real_distribution<float> dis(rangeweights.first,
                                            rangeweights.second);
  for (uint32_t i = 0; i < popSize; i++) {
    PopMember_t I;
    for (uint32_t j = 0; j < weights.size(); j++) {
      I.weights.push_back(dis(gen));
      I.weightsGen.push_back(
          ConvertToGenome<float>(I.weights[j], rangeweights));
    }
    pop.push_back(I);
  }
  return pop;
}
void SoilMath::GA::GrowToAdulthood (Population_t & pop, const ComplexVect_t & inputValues, MinMaxWeight_t rangeweights, Predict_t goal, float & totalFitness) [private]
GrowToAdulthood a private function where the new population members serve as the the input for the Neural Network prediction function. The results are weight against the goal and this weight determine the fitness of the population member.
Parameters
pop reference to the population
inputValues complex vector with a reference to the inputvalues
rangeweights pointer to the range of weights, currently it doesn't support indivudal ranges
goal a Predict_t type with the expected value
totalFitness a reference to the total population fitness
Definition at line 175 of file GA.cpp.
References hiddenneurons, i, inputneurons, j, NNfuction, Predict_struct::OutputNeurons, and outputneurons.
Referenced by Evolve().
                                              {
  for (uint32_t i = 0; i < pop.size(); i++) {
    for (uint32_t j = 0; j < pop[i].weightsGen.size(); j++) {
      pop[i].weights.push_back(
          ConvertToValue<float>(pop[i].weightsGen[j], rangeweights));
    }
    Weight_t iWeight(pop[i].weights.begin(),
                     pop[i].weights.begin() +
                         ((inputneurons + 1) * hiddenneurons));
    Weight_t hWeight(pop[i].weights.begin() +
                         ((inputneurons + 1) * hiddenneurons),
                     pop[i].weights.end());
    Predict_t results = NNfuction(inputValues, iWeight, hWeight,
      inputneurons,
                                  hiddenneurons, outputneurons);
    for (uint32_t j = 0; j < results.OutputNeurons.size(); j++) {
      pop[i].Fitness -= results.OutputNeurons[j] / goal.OutputNeurons[
      j];
    }
    pop[i].Fitness += results.OutputNeurons.size();
    totalFitness += pop[i].Fitness;
  }
}
void SoilMath::GA::GrowToAdulthood (Population_t & pop, const InputLearnVector_t & inputValues, MinMaxWeight_t rangeweights, OutputLearnVector_t & goal, float & totalFitness) [private]
GrowToAdulthood a private function where the new population members serve as the the input for the Neural Network prediction function. The results are weight against the goal and this weight determine the fitness of the population member.
Parameters
pop reference to the population
inputValues a InputLearnVector_t with a reference to the inputvalues
rangeweights pointer to the range of weights, currently it doesn't support indivudal ranges
goal a Predict_t type with the expected value
totalFitness a reference to the total population fitness
Definition at line 199 of file GA.cpp.
References hiddenneurons, i, inputneurons, j, NNfuction, Predict_struct::OutputNeurons, and outputneurons.
                                              {
  for (uint32_t i = 0; i < pop.size(); i++) {
    for (uint32_t j = 0; j < pop[i].weightsGen.size(); j++) {
      pop[i].weights.push_back(
          ConvertToValue<float>(pop[i].weightsGen[j], rangeweights));
    }
    Weight_t iWeight(pop[i].weights.begin(),
                     pop[i].weights.begin() +
                         ((inputneurons + 1) * hiddenneurons));
    Weight_t hWeight(pop[i].weights.begin() +
                         ((inputneurons + 1) * hiddenneurons),
                     pop[i].weights.end());
    for (uint32_t j = 0; j < inputValues.size(); j++) {
      Predict_t results = NNfuction(inputValues[j], iWeight, hWeight,
                                    inputneurons, hiddenneurons,
      outputneurons);
      for (uint32_t k = 0; k < results.OutputNeurons.size(); k++) {
        pop[i].Fitness -= results.OutputNeurons[k] / goal[j].OutputNeurons[k];
      }
      pop[i].Fitness += results.OutputNeurons.size();
    }
    pop[i].Fitness /= inputValues.size();
    totalFitness += pop[i].Fitness;
  }
}
void SoilMath::GA::Mutate (Population_t & pop) [private]
Mutate a private function where individual bits from the Genome_t are mutated at a random uniform distribution event defined by the MUTATIONRATE.
Parameters
pop reference to the population
Definition at line 157 of file GA.cpp.
References GENE_MAX, i, j, and MUTATIONRATE.
Referenced by Evolve().
                                 {
  unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
  std::default_random_engine gen(seed);
  std::uniform_real_distribution<float> dis(0, 1);
  std::default_random_engine genGen(seed);
  std::uniform_int_distribution<int> disGen(0, (GENE_MAX - 1));
  for (uint32_t i = 0; i < pop.size(); i++) {
    for (uint32_t j = 0; j < pop[i].weightsGen.size(); j++) {
      if (dis(gen) < MUTATIONRATE) {
        pop[i].weightsGen[j][disGen(genGen)].flip();
      }
    }
  }
}
static bool SoilMath::GA::PopMemberSort (PopMember_t i, PopMember_t j) [inline], [static], [private]
PopMemberSort a private function where the members are sorted according to there fitness ranking.
Parameters
i left hand population member
j right hand population member
Returns
true if the left member is closser to the goal as the right member.
Definition at line 177 of file GA.h.
References PopMemberStruct::Fitness.
Referenced by SurvivalOfTheFittest().
                                                          {
    return (i.Fitness < j.Fitness);
  }
bool SoilMath::GA::SurvivalOfTheFittest (Population_t & pop, float & totalFitness) [private]
SurvivalOfTheFittest a private function where a battle to the death commences The fittest population members have the best chance of survival. Death is instigated with a random uniform distibution. The elite members don't partake in this desctruction The ELITISME rate indicate how many top tier members survive this catastrophic event.
Parameters
inputValues a InputLearnVector_t with a reference to the inputvalues
totalFitness a reference to the total population fitness
Returns
Definition at line 227 of file GA.cpp.
References ELITISME, END_ERROR, i, and PopMemberSort().
Referenced by Evolve().
                                                                    {
  bool retVal = false;
  uint32_t decimationCount = pop.size() / 2;
  unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
  std::default_random_engine gen(seed);
  std::sort(pop.begin(), pop.end(), PopMemberSort);
  uint32_t i = ELITISME;
  while (pop.size() > decimationCount) {
    if (i >= pop.size()) {
      i = ELITISME;
    }
    std::uniform_real_distribution<float> dis(0, totalFitness);
    if (dis(gen) < pop[i].Fitness) {
      pop.erase(pop.begin() + i--);
      totalFitness -= pop[i].Fitness;
    }
    i++;
  }
  if (pop[0].Fitness < END_ERROR) {
    retVal = true;
  }
  return retVal;
}
Member Data Documentation
uint32_t SoilMath::GA::hiddenneurons [private]
the total number of hidden neurons
Definition at line 97 of file GA.h.
Referenced by GA(), and GrowToAdulthood().
uint32_t SoilMath::GA::inputneurons [private]
the total number of input neurons
Definition at line 96 of file GA.h.
Referenced by GA(), and GrowToAdulthood().
NNfunctionType SoilMath::GA::NNfuction [private]
The Neural Net work function
Definition at line 95 of file GA.h.
Referenced by GA(), and GrowToAdulthood().
uint32_t SoilMath::GA::outputneurons [private]
the total number of output neurons
Definition at line 98 of file GA.h.
Referenced by GA(), and GrowToAdulthood().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilMath/GA.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilMath/GA.cpp