QCPCurve Class Reference
A plottable representing a parametric curve in a plot.
#include <qcustomplot.h>
Public Types
enum LineStyle { lsNone,
lsLine
 }
Public Member Functions
QCPCurve (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPCurve ()
QCPCurveDataMap * data () const
QCPScatterStyle scatterStyle () const
LineStyle lineStyle () const
void setData (QCPCurveDataMap *data, bool copy=false)
void setData (const QVector< double > &t, const QVector< double > &key, const QVector< double > &value)
void setData (const QVector< double > &key, const QVector< double > &value)
void setScatterStyle (const QCPScatterStyle &style)
void setLineStyle (LineStyle style)
void addData (const QCPCurveDataMap &dataMap)
void addData (const QCPCurveData &data)
void addData (double t, double key, double value)
void addData (double key, double value)
void addData (const QVector< double > &ts, const QVector< double > &keys, const QVector< double > &values)
void removeDataBefore (double t)
void removeDataAfter (double t)
void removeData (double fromt, double tot)
void removeData (double t)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual void drawScatterPlot (QCPPainter *painter, const QVector< QPointF > *pointData) const
void getCurveData (QVector< QPointF > *lineData) const
int getRegion (double x, double y, double rectLeft, double rectTop, double rectRight, double rectBottom) const
QPointF getOptimizedPoint (int prevRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const
QVector< QPointF > getOptimizedCornerPoints (int prevRegion, int currentRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const
bool mayTraverse (int prevRegion, int currentRegion) const
bool getTraverse (double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom, QPointF &crossA, QPointF &crossB) const
void getTraverseCornerPoints (int prevRegion, int currentRegion, double rectLeft, double rectTop, double rectRight, double rectBottom, QVector< QPointF > &beforeTraverse, QVector< QPointF > &afterTraverse) const
double pointDistance (const QPointF &pixelPoint) const
Protected Attributes
QCPCurveDataMap * mData
QCPScatterStyle mScatterStyle
LineStyle mLineStyle
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a parametric curve in a plot.
Unlike QCPGraph, plottables of this type may have multiple points with the same key coordinate, so their visual representation can have loops. This is realized by introducing a third coordinate t, which defines the order of the points described by the other two coordinates x and y.
To plot data, assign it with the setData or addData functions.
Gaps in the curve can be created by adding data points with NaN as key and value (qQNaN() or std::numeric_limits<double>::quiet_NaN()) in between the two data points that shall be separated.
Changing the appearance
The appearance of the curve is determined by the pen and the brush (setPen, setBrush).
Usage
Like all data representing objects in QCustomPlot, the QCPCurve is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance and add it to the customPlot:
and then modify the properties of the newly created plottable, e.g.:
Definition at line 3061 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPCurve::LineStyle
Defines how the curve's line is represented visually in the plot. The line is drawn with the current pen of the curve (setPen).
See also
setLineStyle
Enumerator
lsNone
 No line is drawn between data points (e.g. only scatters)
lsLine
 Data points are connected with a straight line.
Definition at line 3075 of file qcustomplot.h.
                 {
    lsNone
    ,
    lsLine
  };
Constructor & Destructor Documentation
QCPCurve::QCPCurve (QCPAxis * keyAxis, QCPAxis * valueAxis) [explicit]
Constructs a curve which uses keyAxis as its key axis (`x`) and valueAxis as its value axis (`y`). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPCurve can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the graph.
Definition at line 18508 of file qcustomplot.cpp.
References lsLine, QCPAbstractPlottable::mBrush, mData, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectedBrush, QCPAbstractPlottable::mSelectedPen, setLineStyle(), and setScatterStyle().
    : QCPAbstractPlottable(keyAxis, valueAxis) {
  mData = new QCPCurveDataMap;
  mPen.setColor(Qt::blue);
  mPen.setStyle(Qt::SolidLine);
  mBrush.setColor(Qt::blue);
  mBrush.setStyle(Qt::NoBrush);
  mSelectedPen = mPen;
  mSelectedPen.setWidthF(2.5);
  mSelectedPen.setColor(QColor(80, 80, 255)); // lighter than Qt::blue of mPen
  mSelectedBrush = mBrush;
  setScatterStyle(QCPScatterStyle());
  setLineStyle(lsLine);
}
QCPCurve::~QCPCurve () [virtual]
Definition at line 18524 of file qcustomplot.cpp.
References mData.
{ delete mData; }
Member Function Documentation
void QCPCurve::addData (const QCPCurveDataMap & dataMap)
Adds the provided data points in dataMap to the current data.
See also
removeData
Definition at line 18622 of file qcustomplot.cpp.
References mData.
                                                     {
  mData->unite(dataMap);
}
void QCPCurve::addData (const QCPCurveData & data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See also
removeData
Definition at line 18630 of file qcustomplot.cpp.
References mData, and QCPCurveData::t.
                                               {
  mData->insertMulti(data.t, data);
}
void QCPCurve::addData (double t, double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as t, key and value tuple to the current data
See also
removeData
Definition at line 18639 of file qcustomplot.cpp.
References QCPCurveData::key, mData, QCPCurveData::t, and QCPCurveData::value.
                                                         {
  QCPCurveData newData;
  newData.t = t;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.t, newData);
}
void QCPCurve::addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Adds the provided single data point as key and value pair to the current data The t parameter of the data point is set to the t of the last data point plus 1. If there is no last data point, t will be set to 0.
See also
removeData
Definition at line 18657 of file qcustomplot.cpp.
References QCPCurveData::key, mData, QCPCurveData::t, and QCPCurveData::value.
                                               {
  QCPCurveData newData;
  if (!mData->isEmpty())
    newData.t = (mData->constEnd() - 1).key() + 1;
  else
    newData.t = 0;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.t, newData);
}
void QCPCurve::addData (const QVector< double > & ts, const QVector< double > & keys, const QVector< double > & values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as t, key and value tuples to the current data.
See also
removeData
Definition at line 18673 of file qcustomplot.cpp.
References i, mData, n, and QCPCurveData::t.
                                                      {
  int n = ts.size();
  n = qMin(n, keys.size());
  n = qMin(n, values.size());
  QCPCurveData newData;
  for (int i = 0; i < n; ++i) {
    newData.t = ts[i];
    newData.key = keys[i];
    newData.value = values[i];
    mData->insertMulti(newData.t, newData);
  }
}
void QCPCurve::clearData () [virtual]
Removes all data points.
See also
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 18745 of file qcustomplot.cpp.
References mData.
{ mData->clear(); }
QCPCurveDataMap* QCPCurve::data () const [inline]
Definition at line 3084 of file qcustomplot.h.
Referenced by setData().
{ return mData; }
void QCPCurve::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 18765 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPPainter::drawLine(), drawScatterPlot(), getCurveData(), i, QCP::isInvalidData(), QCPScatterStyle::isNone(), lsNone, QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mData, mLineStyle, QCPPainter::modes(), QCPLayerable::mParentPlot, mScatterStyle, QCPAbstractPlottable::name(), QCP::phFastPolylines, QCustomPlot::plottingHints(), QCPPainter::pmNoCaching, QCPPainter::pmVectorized, and QCPPainter::setPen().
                                       {
  if (mData->isEmpty())
    return;
  // allocate line vector:
  QVector<QPointF> *lineData = new QVector<QPointF>;
  // fill with curve data:
  getCurveData(lineData);
// check data validity if flag set:
#ifdef QCUSTOMPLOT_CHECK_DATA
  QCPCurveDataMap::const_iterator it;
  for (it = mData->constBegin(); it != mData->constEnd(); ++it) {
    if (QCP::isInvalidData(it.value().t) ||
        QCP::isInvalidData(it.value().key, it.value().value))
      qDebug() << Q_FUNC_INFO << "Data point at" << it.key() << "invalid."
               << "Plottable name:" << name();
  }
#endif
  // draw curve fill:
  if (mainBrush().style() != Qt::NoBrush && mainBrush().color().alpha() != 0) {
    applyFillAntialiasingHint(painter);
    painter->setPen(Qt::NoPen);
    painter->setBrush(mainBrush());
    painter->drawPolygon(QPolygonF(*lineData));
  }
  // draw curve line:
  if (mLineStyle != lsNone && mainPen().style() != Qt::NoPen &&
      mainPen().color().alpha() != 0) {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mainPen());
    painter->setBrush(Qt::NoBrush);
    // if drawing solid line and not in PDF, use much faster line drawing
    // instead of polyline:
    if (mParentPlot->plottingHints().testFlag(
      QCP::phFastPolylines) &&
        painter->pen().style() == Qt::SolidLine &&
        !painter->modes().testFlag(QCPPainter::pmVectorized) &&
        !painter->modes().testFlag(QCPPainter::pmNoCaching)) {
      int i = 0;
      bool lastIsNan = false;
      const int lineDataSize = lineData->size();
      while (i < lineDataSize &&
             (qIsNaN(lineData->at(i).y()) ||
              qIsNaN(lineData->at(i).x()))) // make sure first point is not NaN
        ++i;
      ++i; // because drawing works in 1 point retrospect
      while (i < lineDataSize) {
        if (!qIsNaN(lineData->at(i).y()) &&
            !qIsNaN(lineData->at(i).x())) // NaNs create a gap in the line
        {
          if (!lastIsNan)
            painter->drawLine(lineData->at(i - 1), lineData->at(i));
          else
            lastIsNan = false;
        } else
          lastIsNan = true;
        ++i;
      }
    } else {
      int segmentStart = 0;
      int i = 0;
      const int lineDataSize = lineData->size();
      while (i < lineDataSize) {
        if (qIsNaN(lineData->at(i).y()) ||
            qIsNaN(lineData->at(i).x())) // NaNs create a gap in the line
        {
          painter->drawPolyline(lineData->constData() + segmentStart,
                                i - segmentStart); // i, because we don't want
                                                   // to include the current NaN
                                                   // point
          segmentStart = i + 1;
        }
        ++i;
      }
      // draw last segment:
      painter->drawPolyline(lineData->constData() + segmentStart,
                            lineDataSize - segmentStart);
    }
  }
  // draw scatters:
  if (!mScatterStyle.isNone())
    drawScatterPlot(painter, lineData);
  // free allocated line data:
  delete lineData;
}
void QCPCurve::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 18857 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPScatterStyle::applyTo(), QCPPainter::drawLine(), QCPScatterStyle::drawShape(), QCPScatterStyle::isNone(), lsNone, QCPAbstractPlottable::mBrush, mLineStyle, QCPAbstractPlottable::mPen, mScatterStyle, QCPScatterStyle::pixmap(), QCPPainter::setPen(), QCPScatterStyle::setPixmap(), QCPScatterStyle::shape(), and QCPScatterStyle::ssPixmap.
                                                                           {
  // draw fill:
  if (mBrush.style() != Qt::NoBrush) {
    applyFillAntialiasingHint(painter);
    painter->fillRect(QRectF(rect.left(), rect.top() + rect.height() / 2.0,
                             rect.width(), rect.height() / 3.0),
                      mBrush);
  }
  // draw line vertically centered:
  if (mLineStyle != lsNone) {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    painter->drawLine(
        QLineF(rect.left(), rect.top() + rect.height() / 2.0, rect.right() + 5,
               rect.top() + rect.height() / 2.0)); // +5 on x2 else last segment
                                                   // is missing from
                                                   // dashed/dotted pens
  }
  // draw scatter symbol:
  if (!mScatterStyle.isNone()) {
    applyScattersAntialiasingHint(painter);
    // scale scatter pixmap if it's too large to fit in legend icon rect:
    if (mScatterStyle.shape() == QCPScatterStyle::ssPixmap &&
        (mScatterStyle.pixmap().size().width() > rect.width() ||
         mScatterStyle.pixmap().size().height() > rect.height())) {
      QCPScatterStyle scaledStyle(mScatterStyle);
      scaledStyle.setPixmap(scaledStyle.pixmap().scaled(
          rect.size().toSize(), Qt::KeepAspectRatio, Qt::SmoothTransformation));
      scaledStyle.applyTo(painter, mPen);
      scaledStyle.drawShape(painter, QRectF(rect).center());
    } else {
      mScatterStyle.applyTo(painter, mPen);
      mScatterStyle.drawShape(painter, QRectF(rect).center());
    }
  }
}
void QCPCurve::drawScatterPlot (QCPPainter * painter, const QVector< QPointF > * pointData) const [protected], [virtual]
Definition at line 18901 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPScatterStyle::applyTo(), QCPScatterStyle::drawShape(), i, QCPAbstractPlottable::mPen, and mScatterStyle.
Referenced by draw().
                                                                        {
  // draw scatter point symbols:
  applyScattersAntialiasingHint(painter);
  mScatterStyle.applyTo(painter, mPen);
  for (int i = 0; i < pointData->size(); ++i)
    if (!qIsNaN(pointData->at(i).x()) && !qIsNaN(pointData->at(i).y()))
      mScatterStyle.drawShape(painter, pointData->at(i));
}
void QCPCurve::getCurveData (QVector< QPointF > * lineData) const [protected]
Definition at line 18931 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), QCPAxis::coordToPixel(), getOptimizedCornerPoints(), getOptimizedPoint(), getRegion(), getTraverse(), getTraverseCornerPoints(), QCPScatterStyle::isNone(), QCPAbstractPlottable::keyAxis(), QCPRange::lower, QCPAbstractPlottable::mainPen(), mayTraverse(), mData, QCPAbstractPlottable::mKeyAxis, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::pixelToCoord(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPScatterStyle::size(), QCPRange::upper, and QCPAbstractPlottable::valueAxis().
Referenced by draw(), and pointDistance().
                                                            {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  // add margins to rect to compensate for stroke width
  double strokeMargin =
      qMax(qreal(1.0),
           qreal(mainPen().widthF() * 0.75)); // stroke radius + 50% safety
  if (!mScatterStyle.isNone())
    strokeMargin = qMax(strokeMargin, mScatterStyle.size());
  double rectLeft = keyAxis->pixelToCoord(
      keyAxis->coordToPixel(keyAxis->range().lower) -
      strokeMargin *
          ((keyAxis->orientation() == Qt::Vertical) != keyAxis->
      rangeReversed()
               ? -1
               : 1));
  double rectRight = keyAxis->pixelToCoord(
      keyAxis->coordToPixel(keyAxis->range().upper) +
      strokeMargin *
          ((keyAxis->orientation() == Qt::Vertical) != keyAxis->
      rangeReversed()
               ? -1
               : 1));
  double rectBottom = valueAxis->pixelToCoord(
      valueAxis->coordToPixel(valueAxis->range().lower) +
      strokeMargin * ((valueAxis->orientation() == Qt::Horizontal) !=
                              valueAxis->rangeReversed()
                          ? -1
                          : 1));
  double rectTop = valueAxis->pixelToCoord(
      valueAxis->coordToPixel(valueAxis->range().upper) -
      strokeMargin * ((valueAxis->orientation() == Qt::Horizontal) !=
                              valueAxis->rangeReversed()
                          ? -1
                          : 1));
  int currentRegion;
  QCPCurveDataMap::const_iterator it = mData->constBegin();
  QCPCurveDataMap::const_iterator prevIt = mData->constEnd() - 1;
  int prevRegion = getRegion(prevIt.value().key, prevIt.value().value, rectLeft,
                             rectTop, rectRight, rectBottom);
  QVector<QPointF> trailingPoints; // points that must be applied after all
                                   // other points (are generated only when
                                   // handling first point to get virtual
                                   // segment between last and first point
                                   // right)
  while (it != mData->constEnd()) {
    currentRegion = getRegion(it.value().key, it.value().value, rectLeft,
                              rectTop, rectRight, rectBottom);
    if (currentRegion != prevRegion) // changed region, possibly need to add
                                     // some optimized edge points or original
                                     // points if entering R
    {
      if (currentRegion !=
          5) // segment doesn't end in R, so it's a candidate for removal
      {
        QPointF crossA, crossB;
        if (prevRegion == 5) // we're coming from R, so add this point optimized
        {
          lineData->append(
              getOptimizedPoint(currentRegion, it.value().key, it.value().value,
                                prevIt.value().key, prevIt.value().value,
                                rectLeft, rectTop, rectRight, rectBottom));
          // in the situations 5->1/7/9/3 the segment may leave R and directly
          // cross through two outer regions. In these cases we need to add an
          // additional corner point
          *lineData << getOptimizedCornerPoints(
              prevRegion, currentRegion, prevIt.value().key,
              prevIt.value().value, it.value().key, it.value().value, rectLeft,
              rectTop, rectRight, rectBottom);
        } else if (mayTraverse(prevRegion, currentRegion) &&
                   getTraverse(prevIt.value().key, prevIt.value().value,
                               it.value().key, it.value().value, rectLeft,
                               rectTop, rectRight, rectBottom, crossA,
                               crossB)) {
          // add the two cross points optimized if segment crosses R and if
          // segment isn't virtual zeroth segment between last and first curve
          // point:
          QVector<QPointF> beforeTraverseCornerPoints,
              afterTraverseCornerPoints;
          getTraverseCornerPoints(prevRegion, currentRegion, rectLeft, rectTop,
                                  rectRight, rectBottom,
                                  beforeTraverseCornerPoints,
                                  afterTraverseCornerPoints);
          if (it != mData->constBegin()) {
            *lineData << beforeTraverseCornerPoints;
            lineData->append(crossA);
            lineData->append(crossB);
            *lineData << afterTraverseCornerPoints;
          } else {
            lineData->append(crossB);
            *lineData << afterTraverseCornerPoints;
            trailingPoints << beforeTraverseCornerPoints << crossA;
          }
        } else // doesn't cross R, line is just moving around in outside
               // regions, so only need to add optimized point(s) at the
               // boundary corner(s)
        {
          *lineData << getOptimizedCornerPoints(
              prevRegion, currentRegion, prevIt.value().key,
              prevIt.value().value, it.value().key, it.value().value, rectLeft,
              rectTop, rectRight, rectBottom);
        }
      } else // segment does end in R, so we add previous point optimized and
             // this point at original position
      {
        if (it == mData->constBegin()) // it is first point in curve and prevIt
                                       // is last one. So save optimized point
                                       // for adding it to the lineData in the
                                       // end
          trailingPoints << getOptimizedPoint(
              prevRegion, prevIt.value().key, prevIt.value().value,
              it.value().key, it.value().value, rectLeft, rectTop, rectRight,
              rectBottom);
        else
          lineData->append(getOptimizedPoint(
              prevRegion, prevIt.value().key, prevIt.value().value,
              it.value().key, it.value().value, rectLeft, rectTop, rectRight,
              rectBottom));
        lineData->append(coordsToPixels(it.value().key, it.value().value));
      }
    } else // region didn't change
    {
      if (currentRegion == 5) // still in R, keep adding original points
      {
        lineData->append(coordsToPixels(it.value().key, it.value().value));
      } else // still outside R, no need to add anything
      {
        // see how this is not doing anything? That's the main optimization...
      }
    }
    prevIt = it;
    prevRegion = currentRegion;
    ++it;
  }
  *lineData << trailingPoints;
}
QCPRange QCPCurve::getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 20081 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
                                                              {
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  double current;
  QCPCurveDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd()) {
    current = it.value().key;
    if (!qIsNaN(current) && !qIsNaN(it.value().value)) {
      if (inSignDomain == sdBoth ||
          (inSignDomain == sdNegative && current < 0) ||
          (inSignDomain == sdPositive && current > 0)) {
        if (current < range.lower || !haveLower) {
          range.lower = current;
          haveLower = true;
        }
        if (current > range.upper || !haveUpper) {
          range.upper = current;
          haveUpper = true;
        }
      }
    }
    ++it;
  }
  foundRange = haveLower && haveUpper;
  return range;
}
QVector< QPointF > QCPCurve::getOptimizedCornerPoints (int prevRegion, int currentRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const [protected]
Definition at line 19283 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels().
Referenced by getCurveData().
                             {
  QVector<QPointF> result;
  switch (prevRegion) {
  case 1: {
    switch (currentRegion) {
    case 2: {
      result << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 4: {
      result << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 3: {
      result << coordsToPixels(rectLeft, rectTop)
             << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 7: {
      result << coordsToPixels(rectLeft, rectTop)
             << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 6: {
      result << coordsToPixels(rectLeft, rectTop)
             << coordsToPixels(rectLeft, rectBottom);
      result.append(result.last());
      break;
    }
    case 8: {
      result << coordsToPixels(rectLeft, rectTop)
             << coordsToPixels(rectRight, rectTop);
      result.append(result.last());
      break;
    }
    case 9: { // in this case we need another distinction of cases: segment may
              // pass below or above rect, requiring either bottom right or top
              // left corner points
      if ((value - prevValue) / (key - prevKey) * (rectLeft - key) + value <
          rectBottom) // segment passes below R
      {
        result << coordsToPixels(rectLeft, rectTop)
               << coordsToPixels(rectLeft, rectBottom);
        result.append(result.last());
        result << coordsToPixels(rectRight, rectBottom);
      } else {
        result << coordsToPixels(rectLeft, rectTop)
               << coordsToPixels(rectRight, rectTop);
        result.append(result.last());
        result << coordsToPixels(rectRight, rectBottom);
      }
      break;
    }
    }
    break;
  }
  case 2: {
    switch (currentRegion) {
    case 1: {
      result << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 3: {
      result << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 4: {
      result << coordsToPixels(rectLeft, rectTop);
      result.append(result.last());
      break;
    }
    case 6: {
      result << coordsToPixels(rectLeft, rectBottom);
      result.append(result.last());
      break;
    }
    case 7: {
      result << coordsToPixels(rectLeft, rectTop);
      result.append(result.last());
      result << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 9: {
      result << coordsToPixels(rectLeft, rectBottom);
      result.append(result.last());
      result << coordsToPixels(rectRight, rectBottom);
      break;
    }
    }
    break;
  }
  case 3: {
    switch (currentRegion) {
    case 2: {
      result << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 6: {
      result << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 1: {
      result << coordsToPixels(rectLeft, rectBottom)
             << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 9: {
      result << coordsToPixels(rectLeft, rectBottom)
             << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 4: {
      result << coordsToPixels(rectLeft, rectBottom)
             << coordsToPixels(rectLeft, rectTop);
      result.append(result.last());
      break;
    }
    case 8: {
      result << coordsToPixels(rectLeft, rectBottom)
             << coordsToPixels(rectRight, rectBottom);
      result.append(result.last());
      break;
    }
    case 7: { // in this case we need another distinction of cases: segment may
              // pass below or above rect, requiring either bottom right or top
              // left corner points
      if ((value - prevValue) / (key - prevKey) * (rectRight - key) + value <
          rectBottom) // segment passes below R
      {
        result << coordsToPixels(rectLeft, rectBottom)
               << coordsToPixels(rectRight, rectBottom);
        result.append(result.last());
        result << coordsToPixels(rectRight, rectTop);
      } else {
        result << coordsToPixels(rectLeft, rectBottom)
               << coordsToPixels(rectLeft, rectTop);
        result.append(result.last());
        result << coordsToPixels(rectRight, rectTop);
      }
      break;
    }
    }
    break;
  }
  case 4: {
    switch (currentRegion) {
    case 1: {
      result << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 7: {
      result << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 2: {
      result << coordsToPixels(rectLeft, rectTop);
      result.append(result.last());
      break;
    }
    case 8: {
      result << coordsToPixels(rectRight, rectTop);
      result.append(result.last());
      break;
    }
    case 3: {
      result << coordsToPixels(rectLeft, rectTop);
      result.append(result.last());
      result << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 9: {
      result << coordsToPixels(rectRight, rectTop);
      result.append(result.last());
      result << coordsToPixels(rectRight, rectBottom);
      break;
    }
    }
    break;
  }
  case 5: {
    switch (currentRegion) {
    case 1: {
      result << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 7: {
      result << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 9: {
      result << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 3: {
      result << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    }
    break;
  }
  case 6: {
    switch (currentRegion) {
    case 3: {
      result << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 9: {
      result << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 2: {
      result << coordsToPixels(rectLeft, rectBottom);
      result.append(result.last());
      break;
    }
    case 8: {
      result << coordsToPixels(rectRight, rectBottom);
      result.append(result.last());
      break;
    }
    case 1: {
      result << coordsToPixels(rectLeft, rectBottom);
      result.append(result.last());
      result << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 7: {
      result << coordsToPixels(rectRight, rectBottom);
      result.append(result.last());
      result << coordsToPixels(rectRight, rectTop);
      break;
    }
    }
    break;
  }
  case 7: {
    switch (currentRegion) {
    case 4: {
      result << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 8: {
      result << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 1: {
      result << coordsToPixels(rectRight, rectTop)
             << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 9: {
      result << coordsToPixels(rectRight, rectTop)
             << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 2: {
      result << coordsToPixels(rectRight, rectTop)
             << coordsToPixels(rectLeft, rectTop);
      result.append(result.last());
      break;
    }
    case 6: {
      result << coordsToPixels(rectRight, rectTop)
             << coordsToPixels(rectRight, rectBottom);
      result.append(result.last());
      break;
    }
    case 3: { // in this case we need another distinction of cases: segment may
              // pass below or above rect, requiring either bottom right or top
              // left corner points
      if ((value - prevValue) / (key - prevKey) * (rectRight - key) + value <
          rectBottom) // segment passes below R
      {
        result << coordsToPixels(rectRight, rectTop)
               << coordsToPixels(rectRight, rectBottom);
        result.append(result.last());
        result << coordsToPixels(rectLeft, rectBottom);
      } else {
        result << coordsToPixels(rectRight, rectTop)
               << coordsToPixels(rectLeft, rectTop);
        result.append(result.last());
        result << coordsToPixels(rectLeft, rectBottom);
      }
      break;
    }
    }
    break;
  }
  case 8: {
    switch (currentRegion) {
    case 7: {
      result << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 9: {
      result << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 4: {
      result << coordsToPixels(rectRight, rectTop);
      result.append(result.last());
      break;
    }
    case 6: {
      result << coordsToPixels(rectRight, rectBottom);
      result.append(result.last());
      break;
    }
    case 1: {
      result << coordsToPixels(rectRight, rectTop);
      result.append(result.last());
      result << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 3: {
      result << coordsToPixels(rectRight, rectBottom);
      result.append(result.last());
      result << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    }
    break;
  }
  case 9: {
    switch (currentRegion) {
    case 6: {
      result << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 8: {
      result << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 3: {
      result << coordsToPixels(rectRight, rectBottom)
             << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 7: {
      result << coordsToPixels(rectRight, rectBottom)
             << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 2: {
      result << coordsToPixels(rectRight, rectBottom)
             << coordsToPixels(rectLeft, rectBottom);
      result.append(result.last());
      break;
    }
    case 4: {
      result << coordsToPixels(rectRight, rectBottom)
             << coordsToPixels(rectRight, rectTop);
      result.append(result.last());
      break;
    }
    case 1: { // in this case we need another distinction of cases: segment may
              // pass below or above rect, requiring either bottom right or top
              // left corner points
      if ((value - prevValue) / (key - prevKey) * (rectLeft - key) + value <
          rectBottom) // segment passes below R
      {
        result << coordsToPixels(rectRight, rectBottom)
               << coordsToPixels(rectLeft, rectBottom);
        result.append(result.last());
        result << coordsToPixels(rectLeft, rectTop);
      } else {
        result << coordsToPixels(rectRight, rectBottom)
               << coordsToPixels(rectRight, rectTop);
        result.append(result.last());
        result << coordsToPixels(rectLeft, rectTop);
      }
      break;
    }
    }
    break;
  }
  }
  return result;
}
QPointF QCPCurve::getOptimizedPoint (int prevRegion, double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom) const [protected]
Definition at line 19143 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels().
Referenced by getCurveData().
                                                                               {
  double intersectKey = rectLeft; // initial value is just fail-safe
  double intersectValue = rectTop; // initial value is just fail-safe
  switch (otherRegion) {
  case 1: // top and left edge
  {
    intersectValue = rectTop;
    intersectKey =
        otherKey +
        (key - otherKey) / (value - otherValue) * (intersectValue - otherValue);
    if (intersectKey < rectLeft ||
        intersectKey > rectRight) // doesn't intersect, so must intersect other:
    {
      intersectKey = rectLeft;
      intersectValue =
          otherValue +
          (value - otherValue) / (key - otherKey) * (intersectKey - otherKey);
    }
    break;
  }
  case 2: // left edge
  {
    intersectKey = rectLeft;
    intersectValue =
        otherValue +
        (value - otherValue) / (key - otherKey) * (intersectKey - otherKey);
    break;
  }
  case 3: // bottom and left edge
  {
    intersectValue = rectBottom;
    intersectKey =
        otherKey +
        (key - otherKey) / (value - otherValue) * (intersectValue - otherValue);
    if (intersectKey < rectLeft ||
        intersectKey > rectRight) // doesn't intersect, so must intersect other:
    {
      intersectKey = rectLeft;
      intersectValue =
          otherValue +
          (value - otherValue) / (key - otherKey) * (intersectKey - otherKey);
    }
    break;
  }
  case 4: // top edge
  {
    intersectValue = rectTop;
    intersectKey =
        otherKey +
        (key - otherKey) / (value - otherValue) * (intersectValue - otherValue);
    break;
  }
  case 5: {
    break; // case 5 shouldn't happen for this function but we add it anyway to
           // prevent potential discontinuity in branch table
  }
  case 6: // bottom edge
  {
    intersectValue = rectBottom;
    intersectKey =
        otherKey +
        (key - otherKey) / (value - otherValue) * (intersectValue - otherValue);
    break;
  }
  case 7: // top and right edge
  {
    intersectValue = rectTop;
    intersectKey =
        otherKey +
        (key - otherKey) / (value - otherValue) * (intersectValue - otherValue);
    if (intersectKey < rectLeft ||
        intersectKey > rectRight) // doesn't intersect, so must intersect other:
    {
      intersectKey = rectRight;
      intersectValue =
          otherValue +
          (value - otherValue) / (key - otherKey) * (intersectKey - otherKey);
    }
    break;
  }
  case 8: // right edge
  {
    intersectKey = rectRight;
    intersectValue =
        otherValue +
        (value - otherValue) / (key - otherKey) * (intersectKey - otherKey);
    break;
  }
  case 9: // bottom and right edge
  {
    intersectValue = rectBottom;
    intersectKey =
        otherKey +
        (key - otherKey) / (value - otherValue) * (intersectValue - otherValue);
    if (intersectKey < rectLeft ||
        intersectKey > rectRight) // doesn't intersect, so must intersect other:
    {
      intersectKey = rectRight;
      intersectValue =
          otherValue +
          (value - otherValue) / (key - otherKey) * (intersectKey - otherKey);
    }
    break;
  }
  }
  return coordsToPixels(intersectKey, intersectValue);
}
int QCPCurve::getRegion (double x, double y, double rectLeft, double rectTop, double rectRight, double rectBottom) const [protected]
Definition at line 19093 of file qcustomplot.cpp.
Referenced by getCurveData().
                                                                   {
  if (x < rectLeft) // region 123
  {
    if (y > rectTop)
      return 1;
    else if (y < rectBottom)
      return 3;
    else
      return 2;
  } else if (x > rectRight) // region 789
  {
    if (y > rectTop)
      return 7;
    else if (y < rectBottom)
      return 9;
    else
      return 8;
  } else // region 456
  {
    if (y > rectTop)
      return 4;
    else if (y < rectBottom)
      return 6;
    else
      return 5;
  }
}
bool QCPCurve::getTraverse (double prevKey, double prevValue, double key, double value, double rectLeft, double rectTop, double rectRight, double rectBottom, QPointF & crossA, QPointF & crossB) const [protected]
Definition at line 19791 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), and i.
Referenced by getCurveData().
                                                  {
  QList<QPointF>
      intersections; // x of QPointF corresponds to key and y to value
  if (qFuzzyIsNull(key - prevKey)) // line is parallel to value axis
  {
    // due to region filter in mayTraverseR(), if line is parallel to value or
    // key axis, R is traversed here
    intersections.append(QPointF(
        key, rectBottom)); // direction will be taken care of at end of method
    intersections.append(QPointF(key, rectTop));
  } else if (qFuzzyIsNull(value - prevValue)) // line is parallel to key axis
  {
    // due to region filter in mayTraverseR(), if line is parallel to value or
    // key axis, R is traversed here
    intersections.append(QPointF(
        rectLeft, value)); // direction will be taken care of at end of method
    intersections.append(QPointF(rectRight, value));
  } else // line is skewed
  {
    double gamma;
    double keyPerValue = (key - prevKey) / (value - prevValue);
    // check top of rect:
    gamma = prevKey + (rectTop - prevValue) * keyPerValue;
    if (gamma >= rectLeft && gamma <= rectRight)
      intersections.append(QPointF(gamma, rectTop));
    // check bottom of rect:
    gamma = prevKey + (rectBottom - prevValue) * keyPerValue;
    if (gamma >= rectLeft && gamma <= rectRight)
      intersections.append(QPointF(gamma, rectBottom));
    double valuePerKey = 1.0 / keyPerValue;
    // check left of rect:
    gamma = prevValue + (rectLeft - prevKey) * valuePerKey;
    if (gamma >= rectBottom && gamma <= rectTop)
      intersections.append(QPointF(rectLeft, gamma));
    // check right of rect:
    gamma = prevValue + (rectRight - prevKey) * valuePerKey;
    if (gamma >= rectBottom && gamma <= rectTop)
      intersections.append(QPointF(rectRight, gamma));
  }
  // handle cases where found points isn't exactly 2:
  if (intersections.size() > 2) {
    // line probably goes through corner of rect, and we got duplicate points
    // there. single out the point pair with greatest distance in between:
    double distSqrMax = 0;
    QPointF pv1, pv2;
    for (int i = 0; i < intersections.size() - 1; ++i) {
      for (int k = i + 1; k < intersections.size(); ++k) {
        QPointF distPoint = intersections.at(i) - intersections.at(k);
        double distSqr =
            distPoint.x() * distPoint.x() + distPoint.y() + distPoint.y();
        if (distSqr > distSqrMax) {
          pv1 = intersections.at(i);
          pv2 = intersections.at(k);
          distSqrMax = distSqr;
        }
      }
    }
    intersections = QList<QPointF>() << pv1 << pv2;
  } else if (intersections.size() != 2) {
    // one or even zero points found (shouldn't happen unless line perfectly
    // tangent to corner), no need to draw segment
    return false;
  }
  // possibly re-sort points so optimized point segment has same direction as
  // original segment:
  if ((key - prevKey) * (intersections.at(1).x() - intersections.at(0).x()) +
          (value - prevValue) *
              (intersections.at(1).y() - intersections.at(0).y()) <
      0) // scalar product of both segments < 0 -> opposite direction
    intersections.move(0, 1);
  crossA = coordsToPixels(intersections.at(0).x(), intersections.at(0).y());
  crossB = coordsToPixels(intersections.at(1).x(), intersections.at(1).y());
  return true;
}
void QCPCurve::getTraverseCornerPoints (int prevRegion, int currentRegion, double rectLeft, double rectTop, double rectRight, double rectBottom, QVector< QPointF > & beforeTraverse, QVector< QPointF > & afterTraverse) const [protected]
Definition at line 19910 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels().
Referenced by getCurveData().
                                                                              {
  switch (prevRegion) {
  case 1: {
    switch (currentRegion) {
    case 6: {
      beforeTraverse << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 9: {
      beforeTraverse << coordsToPixels(rectLeft, rectTop);
      afterTraverse << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 8: {
      beforeTraverse << coordsToPixels(rectLeft, rectTop);
      break;
    }
    }
    break;
  }
  case 2: {
    switch (currentRegion) {
    case 7: {
      afterTraverse << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 9: {
      afterTraverse << coordsToPixels(rectRight, rectBottom);
      break;
    }
    }
    break;
  }
  case 3: {
    switch (currentRegion) {
    case 4: {
      beforeTraverse << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 7: {
      beforeTraverse << coordsToPixels(rectLeft, rectBottom);
      afterTraverse << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 8: {
      beforeTraverse << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    }
    break;
  }
  case 4: {
    switch (currentRegion) {
    case 3: {
      afterTraverse << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 9: {
      afterTraverse << coordsToPixels(rectRight, rectBottom);
      break;
    }
    }
    break;
  }
  case 5: {
    break;
  } // shouldn't happen because this method only handles full traverses
  case 6: {
    switch (currentRegion) {
    case 1: {
      afterTraverse << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 7: {
      afterTraverse << coordsToPixels(rectRight, rectTop);
      break;
    }
    }
    break;
  }
  case 7: {
    switch (currentRegion) {
    case 2: {
      beforeTraverse << coordsToPixels(rectRight, rectTop);
      break;
    }
    case 3: {
      beforeTraverse << coordsToPixels(rectRight, rectTop);
      afterTraverse << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    case 6: {
      beforeTraverse << coordsToPixels(rectRight, rectTop);
      break;
    }
    }
    break;
  }
  case 8: {
    switch (currentRegion) {
    case 1: {
      afterTraverse << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 3: {
      afterTraverse << coordsToPixels(rectLeft, rectBottom);
      break;
    }
    }
    break;
  }
  case 9: {
    switch (currentRegion) {
    case 2: {
      beforeTraverse << coordsToPixels(rectRight, rectBottom);
      break;
    }
    case 1: {
      beforeTraverse << coordsToPixels(rectRight, rectBottom);
      afterTraverse << coordsToPixels(rectLeft, rectTop);
      break;
    }
    case 4: {
      beforeTraverse << coordsToPixels(rectRight, rectBottom);
      break;
    }
    }
    break;
  }
  }
}
QCPRange QCPCurve::getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 20114 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
                                                                {
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  double current;
  QCPCurveDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd()) {
    current = it.value().value;
    if (!qIsNaN(current) && !qIsNaN(it.value().key)) {
      if (inSignDomain == sdBoth ||
          (inSignDomain == sdNegative && current < 0) ||
          (inSignDomain == sdPositive && current > 0)) {
        if (current < range.lower || !haveLower) {
          range.lower = current;
          haveLower = true;
        }
        if (current > range.upper || !haveUpper) {
          range.upper = current;
          haveUpper = true;
        }
      }
    }
    ++it;
  }
  foundRange = haveLower && haveUpper;
  return range;
}
LineStyle QCPCurve::lineStyle () const [inline]
Definition at line 3086 of file qcustomplot.h.
{ return mLineStyle; }
bool QCPCurve::mayTraverse (int prevRegion, int currentRegion) const [protected]
Definition at line 19683 of file qcustomplot.cpp.
Referenced by getCurveData().
                                                                  {
  switch (prevRegion) {
  case 1: {
    switch (currentRegion) {
    case 4:
    case 7:
    case 2:
    case 3:
      return false;
    default:
      return true;
    }
  }
  case 2: {
    switch (currentRegion) {
    case 1:
    case 3:
      return false;
    default:
      return true;
    }
  }
  case 3: {
    switch (currentRegion) {
    case 1:
    case 2:
    case 6:
    case 9:
      return false;
    default:
      return true;
    }
  }
  case 4: {
    switch (currentRegion) {
    case 1:
    case 7:
      return false;
    default:
      return true;
    }
  }
  case 5:
    return false; // should never occur
  case 6: {
    switch (currentRegion) {
    case 3:
    case 9:
      return false;
    default:
      return true;
    }
  }
  case 7: {
    switch (currentRegion) {
    case 1:
    case 4:
    case 8:
    case 9:
      return false;
    default:
      return true;
    }
  }
  case 8: {
    switch (currentRegion) {
    case 7:
    case 9:
      return false;
    default:
      return true;
    }
  }
  case 9: {
    switch (currentRegion) {
    case 3:
    case 6:
    case 8:
    case 7:
      return false;
    default:
      return true;
    }
  }
  default:
    return true;
  }
}
double QCPCurve::pointDistance (const QPointF & pixelPoint) const [protected]
Definition at line 20054 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::distSqrToLine(), getCurveData(), i, mData, and QCPAbstractPlottable::mName.
Referenced by selectTest().
                                                              {
  if (mData->isEmpty()) {
    qDebug() << Q_FUNC_INFO << "requested point distance on curve" << mName
             << "without data";
    return 500;
  }
  if (mData->size() == 1) {
    QPointF dataPoint = coordsToPixels(mData->constBegin().key(),
                                       mData->constBegin().value().value);
    return QVector2D(dataPoint - pixelPoint).length();
  }
  // calculate minimum distance to line segments:
  QVector<QPointF> *lineData = new QVector<QPointF>;
  getCurveData(lineData);
  double minDistSqr = std::numeric_limits<double>::max();
  for (int i = 0; i < lineData->size() - 1; ++i) {
    double currentDistSqr =
        distSqrToLine(lineData->at(i), lineData->at(i + 1), pixelPoint);
    if (currentDistSqr < minDistSqr)
      minDistSqr = currentDistSqr;
  }
  delete lineData;
  return qSqrt(minDistSqr);
}
void QCPCurve::removeData (double fromt, double tot)
Removes all data points with curve parameter t between fromt and tot. if fromt is greater or equal to tot, the function does nothing. To remove a single data point with known t, use removeData(double t).
See also
addData, clearData
Definition at line 18718 of file qcustomplot.cpp.
References mData.
                                                  {
  if (fromt >= tot || mData->isEmpty())
    return;
  QCPCurveDataMap::iterator it = mData->upperBound(fromt);
  QCPCurveDataMap::iterator itEnd = mData->upperBound(tot);
  while (it != itEnd)
    it = mData->erase(it);
}
void QCPCurve::removeData (double t)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at curve parameter t. If the position is not known with absolute precision, consider using removeData(double fromt, double tot) with a small fuzziness interval around the suspected position, depeding on the precision with which the curve parameter is known.
See also
addData, clearData
Definition at line 18739 of file qcustomplot.cpp.
References mData.
{ mData->remove(t); }
void QCPCurve::removeDataAfter (double t)
Removes all data points with curve parameter t greater than t.
See also
addData, clearData
Definition at line 18701 of file qcustomplot.cpp.
References mData.
                                       {
  if (mData->isEmpty())
    return;
  QCPCurveDataMap::iterator it = mData->upperBound(t);
  while (it != mData->end())
    it = mData->erase(it);
}
void QCPCurve::removeDataBefore (double t)
Removes all data points with curve parameter t smaller than t.
See also
addData, clearData
Definition at line 18691 of file qcustomplot.cpp.
References mData.
                                        {
  QCPCurveDataMap::iterator it = mData->begin();
  while (it != mData->end() && it.key() < t)
    it = mData->erase(it);
}
QCPScatterStyle QCPCurve::scatterStyle () const [inline]
Definition at line 3085 of file qcustomplot.h.
{ return mScatterStyle; }
double QCPCurve::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 18748 of file qcustomplot.cpp.
References mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, and pointDistance().
                                                     {
  Q_UNUSED(details)
  if ((onlySelectable && !mSelectable) || mData->isEmpty())
    return -1;
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return -1;
  }
  if (mKeyAxis.data()->axisRect()->rect().contains(pos.toPoint()))
    return pointDistance(pos);
  else
    return -1;
}
void QCPCurve::setData (QCPCurveDataMap * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 18535 of file qcustomplot.cpp.
References data(), and mData.
                                                       {
  if (mData == data) {
    qDebug() << Q_FUNC_INFO
             << "The data pointer is already in (and owned by) this plottable"
             << reinterpret_cast<quintptr>(data);
    return;
  }
  if (copy) {
    *mData = *data;
  } else {
    delete mData;
    mData = data;
  }
}
void QCPCurve::setData (const QVector< double > & t, const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in t, key and value tuples. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 18558 of file qcustomplot.cpp.
References i, mData, n, and QCPCurveData::t.
                                                     {
  mData->clear();
  int n = t.size();
  n = qMin(n, key.size());
  n = qMin(n, value.size());
  QCPCurveData newData;
  for (int i = 0; i < n; ++i) {
    newData.t = t[i];
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.t, newData);
  }
}
void QCPCurve::setData (const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided key and value pairs. The t parameter of each data point will be set to the integer index of the respective key/value pair.
Definition at line 18580 of file qcustomplot.cpp.
References i, mData, n, and QCPCurveData::t.
                                                     {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  QCPCurveData newData;
  for (int i = 0; i < n; ++i) {
    newData.t =
        i; // no t vector given, so we assign t the index of the key/value pair
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.t, newData);
  }
}
void QCPCurve::setLineStyle (QCPCurve::LineStyle style)
Sets how the single data points are connected in the plot or how they are represented visually apart from the scatter symbol. For scatter-only plots, set style to lsNone and setScatterStyle to the desired scatter style.
See also
setScatterStyle
Definition at line 18616 of file qcustomplot.cpp.
References mLineStyle.
Referenced by QCPCurve().
{ mLineStyle = style; }
void QCPCurve::setScatterStyle (const QCPScatterStyle & style)
Sets the visual appearance of single data points in the plot. If set to QCPScatterStyle::ssNone, no scatter points are drawn (e.g. for line-only plots with appropriate line style).
See also
QCPScatterStyle, setLineStyle
Definition at line 18603 of file qcustomplot.cpp.
References mScatterStyle.
Referenced by QCPCurve().
                                                           {
  mScatterStyle = style;
}
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 3157 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 3156 of file qcustomplot.h.
Member Data Documentation
QCPCurveDataMap* QCPCurve::mData [protected]
Definition at line 3115 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getCurveData(), getKeyRange(), getValueRange(), pointDistance(), QCPCurve(), removeData(), removeDataAfter(), removeDataBefore(), selectTest(), setData(), and ~QCPCurve().
LineStyle QCPCurve::mLineStyle [protected]
Definition at line 3117 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), and setLineStyle().
QCPScatterStyle QCPCurve::mScatterStyle [protected]
Definition at line 3116 of file qcustomplot.h.
Referenced by draw(), drawLegendIcon(), drawScatterPlot(), getCurveData(), and setScatterStyle().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp