Vision::Enhance Class Reference
#include <Enhance.h>
Public Types
enum EnhanceOperation { _AdaptiveContrastStretch,
_Blur,
_HistogramEqualization
 }
Public Member Functions
Enhance ()
Enhance (const Mat &src)
Enhance (const Mat &src, Mat &dst, uint8_t kernelsize=9, float factor=1.0, EnhanceOperation operation=_Blur)
Enhance (const Enhance &rhs)
~Enhance ()
Enhance & operator= (Enhance rhs)
void AdaptiveContrastStretch (uint8_t kernelsize, float factor, bool chain=false)
void AdaptiveContrastStretch (const Mat &src, Mat &dst, uint8_t kernelsize, float factor)
void Blur (uint8_t kernelsize, bool chain=false)
void Blur (const Mat &src, Mat &dst, uint8_t kernelsize)
void HistogramEqualization (bool chain=false)
void HistogramEqualization (const Mat &src, Mat &dst)
Private Member Functions
void CalculateSumOfNeighboringPixels (uchar *O, int i, int hKsize, int nCols, uint32_t &sum)
float CalculateStdOfNeighboringPixels (uchar *O, int i, int hKsize, int nCols, int noNeighboursPix, float mean)
Additional Inherited Members
Detailed Description
Definition at line 18 of file Enhance.h.
Member Enumeration Documentation
enum Vision::Enhance::EnhanceOperation
Enumerator indicating the requested enhancement operation
Enumerator
_AdaptiveContrastStretch
 custom adaptive contrast stretch operation
_Blur
 Blur operation
_HistogramEqualization
 Histogram equalization
Definition at line 27 of file Enhance.h.
                        {
    _AdaptiveContrastStretch,
    _Blur,
    _HistogramEqualization
  };
Constructor & Destructor Documentation
Enhance::Enhance ()
Constructor
Definition at line 15 of file Enhance.cpp.
{}
Enhance::Enhance (const Mat & src)
Constructor
Parameters
src cv::Mat source image
Definition at line 20 of file Enhance.cpp.
References Vision::ImageProcessing::OriginalImg, and Vision::ImageProcessing::ProcessedImg.
                               {
  OriginalImg = src;
  ProcessedImg.create(OriginalImg.size(), CV_8UC1);
}
Vision::Enhance::Enhance (const Mat & src, Mat & dst, uint8_t kernelsize = 9, float factor = 1.0, EnhanceOperation operation = _Blur)
Enhance::Enhance (const Enhance & rhs)
Definition at line 25 of file Enhance.cpp.
References Vision::ImageProcessing::OriginalImg, Vision::ImageProcessing::ProcessedImg, and Vision::ImageProcessing::TempImg.
                                   {
  this->OriginalImg = rhs.OriginalImg;
  this->ProcessedImg = rhs.OriginalImg;
  this->TempImg = rhs.TempImg;
}
Enhance::~Enhance ()
Dec-constructor
Definition at line 60 of file Enhance.cpp.
{}
Member Function Documentation
void Vision::Enhance::AdaptiveContrastStretch (uint8_t kernelsize, float factor, bool chain = false)
Referenced by SoilAnalyzer::Sample::PrepImg(), and SoilAnalyzer::Sample::SegmentParticles().
void Vision::Enhance::AdaptiveContrastStretch (const Mat & src, Mat & dst, uint8_t kernelsize, float factor)
void Vision::Enhance::Blur (uint8_t kernelsize, bool chain = false)
Referenced by SoilAnalyzer::Sample::PrepImg(), and SoilAnalyzer::Sample::SegmentParticles().
void Vision::Enhance::Blur (const Mat & src, Mat & dst, uint8_t kernelsize)
float Enhance::CalculateStdOfNeighboringPixels (uchar * O, int i, int hKsize, int nCols, int noNeighboursPix, float mean) [private]
Calculate the standard deviation of the neighboring pixels
Parameters
O uchar pointer to the current pixel of the original image
i current counter
hKsize half the kernelsize
nCols total number of columns
noNeighboursPix total number of neighboring pixels
mean mean value of the neighboring pixels
Returns
standard deviation
Definition at line 80 of file Enhance.cpp.
References SoilMath::fastPow(), j, and SoilMath::quick_pow2().
                                                           {
  uint32_t sum_dev = 0.0;
  float Std = 0.0;
  sum_dev = 0.0;
  Std = 0.0;
  for (int j = -hKsize; j < hKsize; j++) {
    for (int k = -hKsize; k < hKsize; k++) {
      // sum_dev += pow((O[i + j * nCols + k] - mean), 2);
      sum_dev += SoilMath::quick_pow2((O[i + j * nCols + k] - mean));
    }
  }
  // Std = sqrt(sum_dev / noNeighboursPix);
  Std = SoilMath::fastPow((static_cast<double>(sum_dev) / noNeighboursPix), 2);
  return Std;
}
void Enhance::CalculateSumOfNeighboringPixels (uchar * O, int i, int hKsize, int nCols, uint32_t & sum) [private]
Calculate the sum of the neighboring pixels
Parameters
O uchar pointer to the current pixel of the original image
i current counter
hKsize half the kernelsize
nCols total number of columns
sum Total sum of the neighboringpixels
Definition at line 105 of file Enhance.cpp.
References j.
                                                                        {
  for (int j = -hKsize; j < hKsize; j++) {
    for (int k = -hKsize; k < hKsize; k++) {
      sum += O[i + j * nCols + k];
    }
  }
}
void Enhance::HistogramEqualization (bool chain = false)
Stretches the image using a histogram
Parameters
chain use the results from the previous operation default value = false;
Definition at line 277 of file Enhance.cpp.
References CHAIN_PROCESS, EMPTY_CHECK, i, SoilMath::Stats< T1, T2, T3 >::max, SoilMath::Stats< T1, T2, T3 >::min, Vision::ImageProcessing::OriginalImg, and Vision::ImageProcessing::ProcessedImg.
                                              {
  // Exception handling
  EMPTY_CHECK(OriginalImg);
  CV_Assert(OriginalImg.depth() != sizeof(uchar));
  // Make the pointers to the Data
  uchar *O;
  CHAIN_PROCESS(chain, O, uchar);
  uchar *P = ProcessedImg.data;
  // Calculate the statics of the whole image
  ucharStat_t imgStats(O, OriginalImg.rows, OriginalImg.cols);
  float sFact;
  if (imgStats.min != imgStats.max) {
    sFact = 255.0f / (imgStats.max - imgStats.min);
  } else {
    sFact = 1.0f;
  }
  uint32_t i = 256;
  uchar LUT_changeValue[256];
  while (i-- > 0) {
    LUT_changeValue[i] = (uchar)(((float)(i)*sFact) + 0.5f);
  }
  O = OriginalImg.data;
  i = OriginalImg.cols * OriginalImg.rows + 1;
  while (i-- > 0) {
    *P++ = LUT_changeValue[*O++ - imgStats.min];
  }
}
void Vision::Enhance::HistogramEqualization (const Mat & src, Mat & dst)
Enhance & Enhance::operator= (Enhance rhs)
Definition at line 62 of file Enhance.cpp.
References Vision::ImageProcessing::OriginalImg, Vision::ImageProcessing::ProcessedImg, and Vision::ImageProcessing::TempImg.
                                       {
  if (&rhs != this) {
    this->OriginalImg = rhs.OriginalImg;
    this->ProcessedImg = rhs.ProcessedImg;
    this->TempImg = rhs.ProcessedImg;
  }
  return *this;
}
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilVision/Enhance.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilVision/Enhance.cpp