QCPItemEllipse Class Reference
An ellipse.
#include <qcustomplot.h>
Public Member Functions
QCPItemEllipse (QCustomPlot *parentPlot)
virtual ~QCPItemEllipse ()
QPen pen () const
QPen selectedPen () const
QBrush brush () const
QBrush selectedBrush () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setBrush (const QBrush &brush)
void setSelectedBrush (const QBrush &brush)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const topLeftRim
QCPItemAnchor *const top
QCPItemAnchor *const topRightRim
QCPItemAnchor *const right
QCPItemAnchor *const bottomRightRim
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeftRim
QCPItemAnchor *const left
QCPItemAnchor *const center
Protected Types
enum AnchorIndex {
*
aiTopLeftRim,
aiTop,
aiTopRightRim,
aiRight,
*
aiBottomRightRim,
aiBottom,
aiBottomLeftRim,
aiLeft,
*
aiCenter
 }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
QBrush mainBrush () const
Protected Attributes
QPen mPen
QPen mSelectedPen
QBrush mBrush
QBrush mSelectedBrush
Additional Inherited Members
Detailed Description
An ellipse.
 anchors, solid blue discs are positions."
It has two positions, topLeft and bottomRight, which define the rect the ellipse will be drawn in.
Definition at line 3990 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemEllipse::AnchorIndex [protected]
Enumerator
aiTopLeftRim
aiTop
aiTopRightRim
aiRight
aiBottomRightRim
aiBottom
aiBottomLeftRim
aiLeft
aiCenter
Definition at line 4031 of file qcustomplot.h.
                   {
    aiTopLeftRim,
    aiTop,
    aiTopRightRim,
    aiRight,
    aiBottomRightRim,
    aiBottom,
    aiBottomLeftRim,
    aiLeft,
    aiCenter
  };
Constructor & Destructor Documentation
QCPItemEllipse::QCPItemEllipse (QCustomPlot * parentPlot)
Creates an ellipse item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 25049 of file qcustomplot.cpp.
References bottomRight, setBrush(), QCPItemPosition::setCoords(), setPen(), setSelectedBrush(), setSelectedPen(), and topLeft.
    : QCPAbstractItem(parentPlot),
      topLeft(createPosition(QLatin1String("topLeft"))),
      bottomRight(createPosition(QLatin1String("bottomRight"))),
      topLeftRim(createAnchor(QLatin1String("topLeftRim"),
      aiTopLeftRim)),
      top(createAnchor(QLatin1String("top"), aiTop)),
      topRightRim(createAnchor(QLatin1String("topRightRim"),
      aiTopRightRim)),
      right(createAnchor(QLatin1String("right"), aiRight)),
      bottomRightRim(
          createAnchor(QLatin1String("bottomRightRim"),
      aiBottomRightRim)),
      bottom(createAnchor(QLatin1String("bottom"), aiBottom)),
      bottomLeftRim(
          createAnchor(QLatin1String("bottomLeftRim"),
      aiBottomLeftRim)),
      left(createAnchor(QLatin1String("left"), aiLeft)),
      center(createAnchor(QLatin1String("center"), aiCenter)) {
  topLeft->setCoords(0, 1);
  bottomRight->setCoords(1, 0);
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue, 2));
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
}
QCPItemEllipse::~QCPItemEllipse () [virtual]
Definition at line 25073 of file qcustomplot.cpp.
{}
Member Function Documentation
QPointF QCPItemEllipse::anchorPixelPoint (int anchorId) const [protected], [virtual]
Reimplemented from QCPAbstractItem.
Definition at line 25166 of file qcustomplot.cpp.
References aiBottom, aiBottomLeftRim, aiBottomRightRim, aiCenter, aiLeft, aiRight, aiTop, aiTopLeftRim, aiTopRightRim, bottomRight, QCPItemPosition::pixelPoint(), rect, and topLeft.
                                                           {
  QRectF rect = QRectF(topLeft->pixelPoint(), bottomRight->
      pixelPoint());
  switch (anchorId) {
  case aiTopLeftRim:
    return rect.center() + (rect.topLeft() - rect.center()) * 1 / qSqrt(2);
  case aiTop:
    return (rect.topLeft() + rect.topRight()) * 0.5;
  case aiTopRightRim:
    return rect.center() + (rect.topRight() - rect.center()) * 1 / qSqrt(2);
  case aiRight:
    return (rect.topRight() + rect.bottomRight()) * 0.5;
  case aiBottomRightRim:
    return rect.center() + (rect.bottomRight() - rect.center()) * 1 / qSqrt(2);
  case aiBottom:
    return (rect.bottomLeft() + rect.bottomRight()) * 0.5;
  case aiBottomLeftRim:
    return rect.center() + (rect.bottomLeft() - rect.center()) * 1 / qSqrt(2);
  case aiLeft:
    return (rect.topLeft() + rect.bottomLeft()) * 0.5;
  case aiCenter:
    return (rect.topLeft() + rect.bottomRight()) * 0.5;
  }
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
QBrush QCPItemEllipse::brush () const [inline]
Definition at line 4005 of file qcustomplot.h.
Referenced by setBrush(), and setSelectedBrush().
{ return mBrush; }
void QCPItemEllipse::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractItem.
Definition at line 25138 of file qcustomplot.cpp.
References bottomRight, QCPAbstractItem::clipRect(), mainBrush(), mainPen(), QCPItemPosition::pixelPoint(), QCPPainter::setPen(), QCPLayerable::setVisible(), and topLeft.
                                             {
  QPointF p1 = topLeft->pixelPoint();
  QPointF p2 = bottomRight->pixelPoint();
  if (p1.toPoint() == p2.toPoint())
    return;
  QRectF ellipseRect = QRectF(p1, p2).normalized();
  QRect clip = clipRect().adjusted(-mainPen().widthF(), -mainPen().widthF(),
                                   mainPen().widthF(), mainPen().widthF());
  if (ellipseRect.intersects(
          clip)) // only draw if bounding rect of ellipse is visible in cliprect
  {
    painter->setPen(mainPen());
    painter->setBrush(mainBrush());
#ifdef __EXCEPTIONS
    try // drawEllipse sometimes throws exceptions if ellipse is too big
    {
#endif
      painter->drawEllipse(ellipseRect);
#ifdef __EXCEPTIONS
    } catch (...) {
      qDebug() << Q_FUNC_INFO << "Item too large for memory, setting invisible";
      setVisible(false);
    }
#endif
  }
}
QBrush QCPItemEllipse::mainBrush () const [protected]
Definition at line 25207 of file qcustomplot.cpp.
References mBrush, QCPAbstractItem::mSelected, and mSelectedBrush.
Referenced by draw().
                                       {
  return mSelected ? mSelectedBrush : mBrush;
}
QPen QCPItemEllipse::mainPen () const [protected]
Definition at line 25199 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{ return mSelected ? mSelectedPen : mPen; }
QPen QCPItemEllipse::pen () const [inline]
Definition at line 4003 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QBrush QCPItemEllipse::selectedBrush () const [inline]
Definition at line 4006 of file qcustomplot.h.
{ return mSelectedBrush; }
QPen QCPItemEllipse::selectedPen () const [inline]
Definition at line 4004 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemEllipse::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 25110 of file qcustomplot.cpp.
References bottomRight, c, center, mBrush, QCPLayerable::mParentPlot, QCPAbstractItem::mSelectable, QCPItemPosition::pixelPoint(), QCustomPlot::selectionTolerance(), topLeft, x, and y.
                                                           {
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  double result = -1;
  QPointF p1 = topLeft->pixelPoint();
  QPointF p2 = bottomRight->pixelPoint();
  QPointF center((p1 + p2) / 2.0);
  double a = qAbs(p1.x() - p2.x()) / 2.0;
  double b = qAbs(p1.y() - p2.y()) / 2.0;
  double x = pos.x() - center.x();
  double y = pos.y() - center.y();
  // distance to border:
  double c = 1.0 / qSqrt(x * x / (a * a) + y * y / (b * b));
  result = qAbs(c - 1) * qSqrt(x * x + y * y);
  // filled ellipse, allow click inside to count as hit:
  if (result > mParentPlot->selectionTolerance() * 0.99 &&
      mBrush.style() != Qt::NoBrush && mBrush.color().alpha() != 0) {
    if (x * x / (a * a) + y * y / (b * b) <= 1)
      result = mParentPlot->selectionTolerance() * 0.99;
  }
  return result;
}
void QCPItemEllipse::setBrush (const QBrush & brush)
Sets the brush that will be used to fill the ellipse. To disable filling, set brush to Qt::NoBrush.
See also
setSelectedBrush, setPen
Definition at line 25096 of file qcustomplot.cpp.
References brush(), and mBrush.
Referenced by QCPItemEllipse().
{ mBrush = brush; }
void QCPItemEllipse::setPen (const QPen & pen)
Sets the pen that will be used to draw the line of the ellipse
See also
setSelectedPen, setBrush
Definition at line 25080 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemEllipse().
{ mPen = pen; }
void QCPItemEllipse::setSelectedBrush (const QBrush & brush)
Sets the brush that will be used to fill the ellipse when selected. To disable filling, set brush to Qt::NoBrush.
See also
setBrush
Definition at line 25105 of file qcustomplot.cpp.
References brush(), and mSelectedBrush.
Referenced by QCPItemEllipse().
                                                         {
  mSelectedBrush = brush;
}
void QCPItemEllipse::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the line of the ellipse when selected
See also
setPen, setSelected
Definition at line 25087 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemEllipse().
{ mSelectedPen = pen; }
Member Data Documentation
QCPItemAnchor* const QCPItemEllipse::bottom
Definition at line 4025 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::bottomLeftRim
Definition at line 4026 of file qcustomplot.h.
QCPItemPosition* const QCPItemEllipse::bottomRight
Definition at line 4019 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemEllipse(), and selectTest().
QCPItemAnchor* const QCPItemEllipse::bottomRightRim
Definition at line 4024 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::center
Definition at line 4028 of file qcustomplot.h.
Referenced by selectTest().
QCPItemAnchor* const QCPItemEllipse::left
Definition at line 4027 of file qcustomplot.h.
QBrush QCPItemEllipse::mBrush [protected]
Definition at line 4045 of file qcustomplot.h.
Referenced by mainBrush(), selectTest(), and setBrush().
QPen QCPItemEllipse::mPen [protected]
Definition at line 4044 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QBrush QCPItemEllipse::mSelectedBrush [protected]
Definition at line 4045 of file qcustomplot.h.
Referenced by mainBrush(), and setSelectedBrush().
QPen QCPItemEllipse::mSelectedPen [protected]
Definition at line 4044 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
QCPItemAnchor* const QCPItemEllipse::right
Definition at line 4023 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::top
Definition at line 4021 of file qcustomplot.h.
QCPItemPosition* const QCPItemEllipse::topLeft
Definition at line 4018 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemEllipse(), and selectTest().
QCPItemAnchor* const QCPItemEllipse::topLeftRim
Definition at line 4020 of file qcustomplot.h.
QCPItemAnchor* const QCPItemEllipse::topRightRim
Definition at line 4022 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp