VSAGUI Class Reference
#include <vsagui.h>
Public Member Functions
VSAGUI (QWidget *parent=0)
~VSAGUI ()
Private Slots
void on_SnapshotButton_clicked ()
void on_actionSave_triggered ()
void on_actionLoad_triggered ()
void on_AnalyzeButton_clicked ()
void on_actionNew_triggered ()
void on_actionImport_triggered ()
void on_actionExport_triggered ()
void on_actionSegmentation_Settings_triggered ()
void on_actionSave_Settings_triggered ()
void on_actionLoad_Settings_triggered ()
void on_actionRestore_Default_triggered ()
void on_SegmentButton_clicked ()
void on_verticalSlider_sliderReleased ()
void on_OffsetSlider_valueChanged (int value)
void on_OffsetSlider_sliderReleased ()
void on_actionHardware_Settings_triggered ()
Private Member Functions
void on_vision_update (float prog, string statusText)
void LoadSample ()
void SetMatToMainView (cv::Mat &img)
Private Attributes
Ui::VSAGUI * ui
QErrorMessage * errorMessageDialog
VisionSettings * settingWindow
HardwareSettings * hsetttingWindow
SoilAnalyzer::SoilSettings * sSettings
boost::signals2::connection finished_sig
boost::signals2::connection progress_sig
boost::signals2::connection visionprogress_seg
SoilAnalyzer::Sample * SoilSample = nullptr
SoilMath::NN * NeuralNet = nullptr
cv::Mat * OrigImg
QProgressBar * progressBar = nullptr
QLabel * statusLabel = nullptr
bool runFromBBB = false
bool Segmented = false
std::vector< std::string > webCams
Detailed Description
Definition at line 52 of file vsagui.h.
Constructor & Destructor Documentation
VSAGUI::VSAGUI (QWidget * parent = 0) [explicit]
Definition at line 11 of file vsagui.cpp.
References Hardware::Microscope::AvailableCams(), Hardware::Microscope::connect_Finished(), SoilAnalyzer::Sample::connect_Progress(), Hardware::Microscope::connect_Progress(), errorMessageDialog, finished_sig, Hardware::Microscope::GetFrame(), Hardware::Microscope::GetHDRFrame(), SoilAnalyzer::SoilSettings::HDRframes, Hardware::Microscope::IsOpened(), SoilAnalyzer::SoilSettings::LoadSettings(), SoilMath::NN::LoadState(), NeuralNet, on_vision_update(), Hardware::Microscope::openCam(), SoilAnalyzer::Sample::OriginalImage, progress_sig, progressBar, runFromBBB, SetMatToMainView(), SoilSample, sSettings, statusLabel, SoilAnalyzer::SoilSettings::thresholdOffsetValue, and ui.
                              : QMainWindow(parent), ui(new Ui::VSAGUI) {
  // Determine if the program is run from an ARM (BBB) device
  struct utsname unameData;
  uname(&unameData);
  std::string arch = static_cast<std::string>(unameData.machine);
  if (arch.find("armv7l") != string::npos) {
    runFromBBB = true;
  }
  // Startup the UI
  ui->setupUi(this);
  SoilSample = new SoilAnalyzer::Sample;
  SoilSample->connect_Progress(
      boost::bind(&VSAGUI::on_vision_update, this, _1, _2));
  NeuralNet = new SoilMath::NN;
  NeuralNet->LoadState("NeuralNet/Default.NN");
  sSettings = new SoilAnalyzer::SoilSettings;
  sSettings->LoadSettings("Settings/Default.ini");
  ui->OffsetSlider->setValue(sSettings->thresholdOffsetValue);
  // Init the status bar
  progressBar = new QProgressBar(ui->statusBar);
  progressBar->setAlignment(Qt::AlignLeft);
  progressBar->setMaximumSize(640, 19);
  ui->statusBar->addWidget(progressBar);
  progressBar->setValue(0);
  statusLabel = new QLabel(ui->statusBar);
  statusLabel->setAlignment(Qt::AlignRight);
  statusLabel->setMinimumSize(600, 19);
  statusLabel->setMaximumSize(600, 19);
  ui->statusBar->addWidget(statusLabel);
  statusLabel->setText(tr("First Grab"));
  // Get HDR snapshot of the sample or normal shot when HDR grab faulters or
  // test image if normal grab falters
  Hardware::Microscope microscope;
  finished_sig = microscope.connect_Finished([&]() {
    SetMatToMainView(SoilSample->OriginalImage);
    this->statusLabel->setText(tr("New Image Grabbed"));
  });
  progress_sig = microscope.connect_Progress(
      [&](int &prog) { this->progressBar->setValue(prog); });
  try {
    if (microscope.IsOpened()) {
      microscope.GetHDRFrame(SoilSample->OriginalImage,
      sSettings->HDRframes);
    }
  } catch (Hardware::Exception::MicroscopeNotFoundException
       &em) {
    try {
      errorMessageDialog->showMessage(
          tr("Microscope not found switching to first default Cam!"));
      if (microscope.AvailableCams().size() > 0) {
        microscope.openCam(0);
      }
    } catch (Hardware::Exception::MicroscopeNotFoundException
       &em2) {
      // display error dialog no cam found and show default test image
      errorMessageDialog->showMessage(
          tr("Microscope not found switching to test image!"));
      SoilSample->OriginalImage = cv::imread("/Images/SoilSample1.png");
    }
  } catch (Hardware::Exception::CouldNotGrabImageException &
      ei) {
    // HDRFrame not working switching to normal grab
    try {
      errorMessageDialog->showMessage(
          tr("HDR Grab failed switching to normal grab!"));
      microscope.GetFrame(SoilSample->OriginalImage);
    } catch (Hardware::Exception::CouldNotGrabImageException
       &ei2) {
      // show default test image and error dialog
      errorMessageDialog->showMessage(
          tr("Normal Grab failed switching to test image!"));
      SoilSample->OriginalImage = cv::imread("/Images/SoilSample1.png");
    }
  }
}
VSAGUI::~VSAGUI ()
Definition at line 96 of file vsagui.cpp.
References ui.
{ delete ui; }
Member Function Documentation
void VSAGUI::LoadSample () [private]
void VSAGUI::on_actionExport_triggered () [private], [slot]
Definition at line 172 of file vsagui.cpp.
References NeuralNet, and SoilMath::NN::SaveState().
                                       {
  QString fn = QFileDialog::getSaveFileName(
      this, tr("Export Neural Network"), tr("/home/"),
      tr("Neural Net (*.NN);;All Files (*)"));
  if (!fn.isEmpty())
    ;
  {
    if (!fn.contains(tr(".NN"))) {
      fn.append(tr(".NN"));
    }
    std::string filename = fn.toStdString();
    NeuralNet->SaveState(filename);
  }
}
void VSAGUI::on_actionHardware_Settings_triggered () [private], [slot]
Definition at line 241 of file vsagui.cpp.
References hsetttingWindow, and sSettings.
                                                  {
  hsetttingWindow = new HardwareSettings(0,
      sSettings);
  hsetttingWindow->exec();
}
void VSAGUI::on_actionImport_triggered () [private], [slot]
Definition at line 160 of file vsagui.cpp.
References SoilMath::NN::LoadState(), and NeuralNet.
                                       {
  QString fn = QFileDialog::getOpenFileName(
      this, tr("Import Neural Network"), tr("/home/"),
      tr("Neural Net (*.NN);;All Files (*)"));
  if (!fn.isEmpty())
    ;
  {
    std::string filename = fn.toStdString();
    NeuralNet->LoadState(filename);
  }
}
void VSAGUI::on_actionLoad_Settings_triggered () [private], [slot]
Definition at line 207 of file vsagui.cpp.
References SoilAnalyzer::SoilSettings::LoadSettings(), and sSettings.
                                              {
  QString fn =
      QFileDialog::getOpenFileName(this, tr("Load Settings"), tr("/home/"),
                                   tr("Settings (*.ini);;All Files (*)"));
  if (!fn.isEmpty())
    ;
  {
    std::string filename = fn.toStdString();
    sSettings->LoadSettings(filename);
  }
}
void VSAGUI::on_actionLoad_triggered () [private], [slot]
Definition at line 133 of file vsagui.cpp.
References SoilAnalyzer::Sample::connect_Progress(), SoilAnalyzer::Sample::Load(), on_vision_update(), SoilAnalyzer::Sample::OriginalImage, SetMatToMainView(), and SoilSample.
                                     {
  QString fn = QFileDialog::getOpenFileName(
      this, tr("Load Soil Sample"), tr("/home/"),
      tr("Soil Samples (*.VSS);; Soil Particles (*.VPS);; All Files (*)"));
  if (!fn.isEmpty() && fn.contains(tr("VSS")))
    ;
  {
    delete SoilSample;
    SoilSample = new SoilAnalyzer::Sample;
    std::string filename = fn.toStdString();
    SoilSample->Load(filename);
    SoilSample->connect_Progress(
        boost::bind(&VSAGUI::on_vision_update, this, _1, _2));
    SetMatToMainView(SoilSample->OriginalImage);
  }
}
void VSAGUI::on_actionNew_triggered () [private], [slot]
Definition at line 152 of file vsagui.cpp.
References SoilAnalyzer::Sample::connect_Progress(), on_SnapshotButton_clicked(), on_vision_update(), and SoilSample.
                                    {
  delete SoilSample;
  SoilSample = new SoilAnalyzer::Sample;
  SoilSample->connect_Progress(
      boost::bind(&VSAGUI::on_vision_update, this, _1, _2));
  on_SnapshotButton_clicked();
}
void VSAGUI::on_actionRestore_Default_triggered () [private], [slot]
Definition at line 219 of file vsagui.cpp.
References SoilAnalyzer::SoilSettings::LoadSettings(), and sSettings.
                                                {
  std::string filename = "Settings/Default.ini";
  sSettings->LoadSettings(filename);
}
void VSAGUI::on_actionSave_Settings_triggered () [private], [slot]
Definition at line 192 of file vsagui.cpp.
References SoilAnalyzer::SoilSettings::SaveSettings(), and sSettings.
                                              {
  QString fn =
      QFileDialog::getSaveFileName(this, tr("Save Settings"), tr("/home/"),
                                   tr("Settings (*.ini);;All Files (*)"));
  if (!fn.isEmpty())
    ;
  {
    if (!fn.contains(tr(".ini"))) {
      fn.append(tr(".ini"));
    }
    std::string filename = fn.toStdString();
    sSettings->SaveSettings(filename);
  }
}
void VSAGUI::on_actionSave_triggered () [private], [slot]
Definition at line 120 of file vsagui.cpp.
References SoilAnalyzer::Sample::Save(), and SoilSample.
                                     {
  QString fn = QFileDialog::getSaveFileName(
      this, tr("Save Soil Sample"), tr("/home/"),
      tr("Soil Samples (*.VSS);; Soil Particles (*.VPS);; All Files (*)"));
  if (!fn.isEmpty()) {
    if (!fn.contains(tr(".VSS"))) {
      fn.append(tr(".VSS"));
    }
    std::string filename = fn.toStdString();
    SoilSample->Save(filename);
  }
}
void VSAGUI::on_actionSegmentation_Settings_triggered () [private], [slot]
Definition at line 187 of file vsagui.cpp.
References settingWindow, and sSettings.
                                                      {
  settingWindow = new VisionSettings(0, sSettings);
  settingWindow->exec();
}
void VSAGUI::on_AnalyzeButton_clicked () [private], [slot]
Definition at line 150 of file vsagui.cpp.
References SoilAnalyzer::Sample::Analyse(), NeuralNet, and SoilSample.
{ SoilSample->Analyse(*NeuralNet); }
void VSAGUI::on_OffsetSlider_sliderReleased () [private], [slot]
Definition at line 239 of file vsagui.cpp.
{}
void VSAGUI::on_OffsetSlider_valueChanged (int value) [private], [slot]
Definition at line 235 of file vsagui.cpp.
References sSettings, SoilAnalyzer::SoilSettings::thresholdOffsetValue, and ui.
                                                   {
  sSettings->thresholdOffsetValue = ui->OffsetSlider->value();
}
void VSAGUI::on_SegmentButton_clicked () [private], [slot]
Definition at line 224 of file vsagui.cpp.
References SoilAnalyzer::Sample::PrepImg(), SoilAnalyzer::Soil::RGB, SetMatToMainView(), SoilSample, and sSettings.
                                      {
  SoilSample->PrepImg(sSettings);
  SetMatToMainView(SoilSample->RGB);
}
void VSAGUI::on_SnapshotButton_clicked () [private], [slot]
Definition at line 98 of file vsagui.cpp.
References Hardware::Microscope::connect_Finished(), SoilAnalyzer::Sample::connect_Progress(), Hardware::Microscope::connect_Progress(), finished_sig, Hardware::Microscope::GetHDRFrame(), SoilAnalyzer::SoilSettings::HDRframes, on_vision_update(), SoilAnalyzer::Sample::OriginalImage, progress_sig, progressBar, SetMatToMainView(), SoilSample, sSettings, and statusLabel.
Referenced by on_actionNew_triggered().
                                       {
  Hardware::Microscope microscope;
  delete SoilSample;
  SoilSample = new SoilAnalyzer::Sample;
  SoilSample->connect_Progress(
      boost::bind(&VSAGUI::on_vision_update, this, _1, _2));
  this->statusLabel->setText(tr("Grabbing new Image!"));
  finished_sig = microscope.connect_Finished([&]() {
    SetMatToMainView(SoilSample->OriginalImage);
    this->statusLabel->setText(tr("New Image Grabbed"));
  });
  progress_sig = microscope.connect_Progress(
      [&](int &prog) { this->progressBar->setValue(prog); });
  microscope.GetHDRFrame(SoilSample->OriginalImage,
      sSettings->HDRframes);
}
void VSAGUI::on_verticalSlider_sliderReleased () [private], [slot]
Definition at line 229 of file vsagui.cpp.
References SoilAnalyzer::Sample::imgPrepped, SoilAnalyzer::Sample::PrepImg(), SoilSample, sSettings, SoilAnalyzer::SoilSettings::thresholdOffsetValue, and ui.
                                              {
  sSettings->thresholdOffsetValue = ui->OffsetSlider->value();
  if (SoilSample->imgPrepped) {
    SoilSample->PrepImg(sSettings);
  }
}
void VSAGUI::on_vision_update (float prog, string statusText) [private]
Definition at line 114 of file vsagui.cpp.
References progressBar, and statusLabel.
Referenced by on_actionLoad_triggered(), on_actionNew_triggered(), on_SnapshotButton_clicked(), and VSAGUI().
                                                           {
  int progress = prog * 100;
  this->progressBar->setValue(progress);
  this->statusLabel->setText(tr(statusText.c_str()));
}
void VSAGUI::SetMatToMainView (cv::Mat & img) [private]
Definition at line 88 of file vsagui.cpp.
References OpenCVQT::Mat2QImage(), and ui.
Referenced by on_actionLoad_triggered(), on_SegmentButton_clicked(), on_SnapshotButton_clicked(), and VSAGUI().
                                        {
  QImage *qOrigImg = new QImage(OpenCVQT::Mat2QImage(img));
  QPixmap *qOrigPix = new QPixmap(QPixmap::fromImage(*qOrigImg));
  ui->MainImg->clear();
  ui->MainImg->setPixmap(*qOrigPix);
  ui->MainImg->show();
}
Member Data Documentation
QErrorMessage* VSAGUI::errorMessageDialog [private]
Definition at line 95 of file vsagui.h.
Referenced by VSAGUI().
boost::signals2::connection VSAGUI::finished_sig [private]
Definition at line 101 of file vsagui.h.
Referenced by on_SnapshotButton_clicked(), and VSAGUI().
HardwareSettings* VSAGUI::hsetttingWindow [private]
Definition at line 97 of file vsagui.h.
Referenced by on_actionHardware_Settings_triggered().
SoilMath::NN* VSAGUI::NeuralNet = nullptr [private]
Definition at line 108 of file vsagui.h.
Referenced by on_actionExport_triggered(), on_actionImport_triggered(), on_AnalyzeButton_clicked(), and VSAGUI().
cv::Mat* VSAGUI::OrigImg [private]
Definition at line 110 of file vsagui.h.
boost::signals2::connection VSAGUI::progress_sig [private]
Definition at line 102 of file vsagui.h.
Referenced by on_SnapshotButton_clicked(), and VSAGUI().
QProgressBar* VSAGUI::progressBar = nullptr [private]
Definition at line 111 of file vsagui.h.
Referenced by on_SnapshotButton_clicked(), on_vision_update(), and VSAGUI().
bool VSAGUI::runFromBBB = false [private]
Definition at line 114 of file vsagui.h.
Referenced by VSAGUI().
bool VSAGUI::Segmented = false [private]
Definition at line 115 of file vsagui.h.
VisionSettings* VSAGUI::settingWindow [private]
Definition at line 96 of file vsagui.h.
Referenced by on_actionSegmentation_Settings_triggered().
SoilAnalyzer::Sample* VSAGUI::SoilSample = nullptr [private]
Definition at line 107 of file vsagui.h.
Referenced by on_actionLoad_triggered(), on_actionNew_triggered(), on_actionSave_triggered(), on_AnalyzeButton_clicked(), on_SegmentButton_clicked(), on_SnapshotButton_clicked(), on_verticalSlider_sliderReleased(), and VSAGUI().
SoilAnalyzer::SoilSettings* VSAGUI::sSettings [private]
Definition at line 99 of file vsagui.h.
Referenced by on_actionHardware_Settings_triggered(), on_actionLoad_Settings_triggered(), on_actionRestore_Default_triggered(), on_actionSave_Settings_triggered(), on_actionSegmentation_Settings_triggered(), on_OffsetSlider_valueChanged(), on_SegmentButton_clicked(), on_SnapshotButton_clicked(), on_verticalSlider_sliderReleased(), and VSAGUI().
QLabel* VSAGUI::statusLabel = nullptr [private]
Definition at line 112 of file vsagui.h.
Referenced by on_SnapshotButton_clicked(), on_vision_update(), and VSAGUI().
Ui::VSAGUI* VSAGUI::ui [private]
Definition at line 94 of file vsagui.h.
Referenced by on_OffsetSlider_valueChanged(), on_verticalSlider_sliderReleased(), SetMatToMainView(), VSAGUI(), and ~VSAGUI().
boost::signals2::connection VSAGUI::visionprogress_seg [private]
Definition at line 103 of file vsagui.h.
std::vector<std::string> VSAGUI::webCams [private]
Definition at line 118 of file vsagui.h.
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/vsagui.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/vsagui.cpp