Hardware::BBB Class Reference
#include <BBB.h>
Public Member Functions
BBB ()
~BBB ()
Public Attributes
int debounceTime
Protected Member Functions
bool DirectoryExist (const string &path)
bool CapeLoaded (const string &shield)
string Read (const string &path)
void Write (const string &path, const string &value)
template<typename T >
string NumberToString (T Number)
template<typename T >
T StringToNumber (string Text)
Protected Attributes
bool threadRunning
pthread_t thread
CallbackType callbackFunction
Detailed Description
Definition at line 30 of file BBB.h.
Constructor & Destructor Documentation
BBB::BBB ()
Constructor
Definition at line 6 of file BBB.cpp.
References callbackFunction, debounceTime, thread, and threadRunning.
    {
        threadRunning = false;
        callbackFunction = NULL;
        debounceTime = 0;
        thread = (pthread_t)NULL;
    }
BBB::~BBB ()
De-constructor
Definition at line 15 of file BBB.cpp.
{ }
Member Function Documentation
bool BBB::CapeLoaded (const string & shield) [protected]
Checks if a cape is loaded in the file /sys/devices/bone_capemgr.9/slots
Parameters
shield a const search string which is a (part) of the shield name
Returns
true if the search string is found otherwise false
Definition at line 59 of file BBB.cpp.
References SLOTS.
Referenced by Hardware::eQEP::eQEP(), and Hardware::PWM::PWM().
    {
        bool shieldFound = false;
        ifstream fs;
        fs.open(SLOTS);
        if (!fs.is_open()) { throw Exception::GPIOReadException("Can't open SLOTS"); }
        string line;
        while (getline(fs, line))
        {
            if (line.find(shield) != string::npos) { shieldFound = true; break; }
        }
        fs.close();
        return shieldFound;
    }
bool BBB::DirectoryExist (const string & path) [protected]
Checks if a directory exist
Returns
true if the directory exists and false if not
Definition at line 48 of file BBB.cpp.
Referenced by Hardware::GPIO::isExported().
    {
        struct stat st;
        if (stat((char *)path.c_str(), &st) != 0) { return false; }
        return true;
    }
template<typename T > string Hardware::BBB::NumberToString (T Number) [inline], [protected]
Converts a number to a string
Parameters
Number as typename
Returns
the number as a string
Definition at line 53 of file BBB.h.
        {
            ostringstream ss;
            ss << Number;
            return ss.str();
        };
string BBB::Read (const string & path) [protected]
Reads the first line from a file
Parameters
path constant string pointing towards the file
Returns
this first line
Definition at line 21 of file BBB.cpp.
Referenced by Hardware::ADC::GetCurrentValue(), Hardware::PWM::PWM(), Hardware::GPIO::ReadsDirection(), Hardware::GPIO::ReadsEdge(), Hardware::GPIO::ReadsValue(), Hardware::ADC::SetMaxIntensity(), Hardware::ADC::SetMinIntensity(), and Hardware::ADC::WaitForValueChange().
    {
        ifstream fs;
        fs.open(path.c_str());
        if (!fs.is_open()) { throw Exception::GPIOReadException(("Can't open: " + path).c_str()); }
        string input;
        getline(fs, input);
        fs.close();
        return input;
    }
template<typename T > T Hardware::BBB::StringToNumber (string Text) [inline], [protected]
Converts a string to a number
Parameters
Text the string that needs to be converted
Returns
the number as typename
Definition at line 64 of file BBB.h.
        {
            stringstream ss(Text);
            T result;
            return ss >> result ? result : 0;
        };
void BBB::Write (const string & path, const string & value) [protected]
Writes a value to a file
Parameters
path a constant string pointing towards the file
value a constant string which should be written in the file
Definition at line 36 of file BBB.cpp.
Referenced by Hardware::eQEP::eQEP(), Hardware::GPIO::ExportPin(), Hardware::PWM::PWM(), Hardware::PWM::SetDuty(), Hardware::PWM::SetPeriod(), Hardware::PWM::SetPolarity(), Hardware::PWM::SetRun(), Hardware::GPIO::UnexportPin(), Hardware::GPIO::WritesDirection(), Hardware::GPIO::WritesEdge(), and Hardware::GPIO::WritesValue().
    {
        ofstream fs;
        fs.open(path.c_str());
        if (!fs.is_open()){ throw Exception::GPIOReadException(("Can't open: " + path).c_str()); }
        fs << value;
        fs.close();
    }
Member Data Documentation
CallbackType Hardware::BBB::callbackFunction [protected]
the callbakcfunction
Definition at line 41 of file BBB.h.
Referenced by BBB(), Hardware::threadedPollADC(), Hardware::threadedPolleqep(), Hardware::threadedPollGPIO(), Hardware::GPIO::WaitForEdge(), Hardware::eQEP::WaitForPositionChange(), and Hardware::ADC::WaitForValueChange().
int Hardware::BBB::debounceTime
debounce time for a button in milliseconds
Definition at line 33 of file BBB.h.
Referenced by BBB(), Hardware::threadedPolleqep(), and Hardware::threadedPollGPIO().
pthread_t Hardware::BBB::thread [protected]
The thread
Definition at line 40 of file BBB.h.
Referenced by BBB(), Hardware::GPIO::WaitForEdge(), Hardware::eQEP::WaitForPositionChange(), and Hardware::ADC::WaitForValueChange().
bool Hardware::BBB::threadRunning [protected]
used to stop the thread
Definition at line 39 of file BBB.h.
Referenced by BBB(), Hardware::threadedPollADC(), Hardware::threadedPolleqep(), Hardware::threadedPollGPIO(), Hardware::GPIO::WaitForEdge(), Hardware::eQEP::WaitForPositionChange(), Hardware::eQEP::WaitForPositionChangeCancel(), and Hardware::ADC::WaitForValueChange().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/BBB.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/BBB.cpp