QCPLineEnding Class Reference
Handles the different ending decorations for line-like items.
#include <qcustomplot.h>
Public Types
enum EndingStyle {
*
esNone,
esFlatArrow,
esSpikeArrow,
esLineArrow,
*
esDisc,
esSquare,
esDiamond,
esBar,
*
esHalfBar,
esSkewedBar
 }
Public Member Functions
QCPLineEnding ()
QCPLineEnding (EndingStyle style, double width=8, double length=10, bool inverted=false)
EndingStyle style () const
double width () const
double length () const
bool inverted () const
void setStyle (EndingStyle style)
void setWidth (double width)
void setLength (double length)
void setInverted (bool inverted)
double boundingDistance () const
double realLength () const
void draw (QCPPainter *painter, const QVector2D &pos, const QVector2D &dir) const
void draw (QCPPainter *painter, const QVector2D &pos, double angle) const
Protected Attributes
EndingStyle mStyle
double mWidth
double mLength
bool mInverted
Detailed Description
Handles the different ending decorations for line-like items.
 For every ending a line-like item has, an instance of this class exists. For example, QCPItemLine has two endings which can be set with QCPItemLine::setHead and QCPItemLine::setTail.
The styles themselves are defined via the enum QCPLineEnding::EndingStyle. Most decorations can be modified regarding width and length, see setWidth and setLength. The direction of the ending decoration (e.g. direction an arrow is pointing) is controlled by the line-like item. For example, when both endings of a QCPItemLine are set to be arrows, they will point to opposite directions, e.g. `outward`. This can be changed by setInverted, which would make the respective arrow point inward.
Note that due to the overloaded QCPLineEnding constructor, you may directly specify a QCPLineEnding::EndingStyle where actually a QCPLineEnding is expected, e.g.
Definition at line 1015 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPLineEnding::EndingStyle
Defines the type of ending decoration for line-like items, e.g. an arrow.
The width and length of these decorations can be controlled with the functions setWidth and setLength. Some decorations like esDisc, esSquare, esDiamond and esBar only support a width, the length property is ignored.
See also
QCPItemLine::setHead, QCPItemLine::setTail, QCPItemCurve::setHead, QCPItemCurve::setTail, QCPAxis::setLowerEnding, QCPAxis::setUpperEnding
Enumerator
esNone
 No ending decoration.
esFlatArrow
 A filled arrow head with a straight/flat back (a triangle)
esSpikeArrow
 A filled arrow head with an indented back.
esLineArrow
 A non-filled arrow head with open back.
esDisc
 A filled circle.
esSquare
 A filled square.
esDiamond
 A filled diamond (45° rotated square)
esBar
 A bar perpendicular to the line.
esHalfBar
 A bar perpendicular to the line, pointing out to only one side (to which side can be changed with setInverted)
esSkewedBar
 A bar that is skewed (skew controllable via setLength)
Definition at line 1033 of file qcustomplot.h.
                   {
    esNone
    ,
    esFlatArrow
    ,
    esSpikeArrow
    ,
    esLineArrow
    ,
    esDisc
    ,
    esSquare
    ,
    esDiamond
    ,
    esBar
    ,
    esHalfBar
    ,
    esSkewedBar
  };
Constructor & Destructor Documentation
QCPLineEnding::QCPLineEnding ()
Creates a QCPLineEnding instance with default values (style esNone).
Definition at line 3689 of file qcustomplot.cpp.
    : mStyle(esNone), mWidth(8), mLength(10), mInverted(false) {}
QCPLineEnding::QCPLineEnding (QCPLineEnding::EndingStyle style, double width = 8, double length = 10, bool inverted = false)
Creates a QCPLineEnding instance with the specified values.
Definition at line 3695 of file qcustomplot.cpp.
    : mStyle(style), mWidth(width), mLength(length),
      mInverted(inverted) {}
Member Function Documentation
double QCPLineEnding::boundingDistance () const
Definition at line 3751 of file qcustomplot.cpp.
References esBar, esDiamond, esDisc, esFlatArrow, esHalfBar, esLineArrow, esNone, esSkewedBar, esSpikeArrow, esSquare, mLength, mStyle, and mWidth.
Referenced by QCPItemLine::draw().
                                             {
  switch (mStyle) {
  case esNone:
    return 0;
  case esFlatArrow:
  case esSpikeArrow:
  case esLineArrow:
  case esSkewedBar:
    return qSqrt(mWidth * mWidth +
                 mLength * mLength); // items that have width and length
  case esDisc:
  case esSquare:
  case esDiamond:
  case esBar:
  case esHalfBar:
    return mWidth * 1.42; // items that only have a width -> width*sqrt(2)
  }
  return 0;
}
void QCPLineEnding::draw (QCPPainter * painter, const QVector2D & pos, const QVector2D & dir) const
Definition at line 3818 of file qcustomplot.cpp.
References QCPPainter::drawLine(), esBar, esDiamond, esDisc, esFlatArrow, esHalfBar, esLineArrow, esNone, esSkewedBar, esSpikeArrow, esSquare, mInverted, mLength, QCPPainter::modes(), mStyle, mWidth, QCPPainter::pmNonCosmetic, and QCPPainter::setPen().
Referenced by draw(), QCPAxisPainterPrivate::draw(), QCPItemLine::draw(), and QCPItemCurve::draw().
                                                     {
  if (mStyle == esNone)
    return;
  QVector2D lengthVec(dir.normalized());
  if (lengthVec.isNull())
    lengthVec = QVector2D(1, 0);
  QVector2D widthVec(-lengthVec.y(), lengthVec.x());
  lengthVec *= (float)(mLength * (mInverted ? -1 : 1));
  widthVec *= (float)(mWidth * 0.5 * (mInverted ? -1 : 1));
  QPen penBackup = painter->pen();
  QBrush brushBackup = painter->brush();
  QPen miterPen = penBackup;
  miterPen.setJoinStyle(Qt::MiterJoin); // to make arrow heads spikey
  QBrush brush(painter->pen().color(), Qt::SolidPattern);
  switch (mStyle) {
  case esNone:
    break;
  case esFlatArrow: {
    QPointF points[3] = {pos.toPointF(),
                         (pos - lengthVec + widthVec).toPointF(),
                         (pos - lengthVec - widthVec).toPointF()};
    painter->setPen(miterPen);
    painter->setBrush(brush);
    painter->drawConvexPolygon(points, 3);
    painter->setBrush(brushBackup);
    painter->setPen(penBackup);
    break;
  }
  case esSpikeArrow: {
    QPointF points[4] = {pos.toPointF(),
                         (pos - lengthVec + widthVec).toPointF(),
                         (pos - lengthVec * 0.8f).toPointF(),
                         (pos - lengthVec - widthVec).toPointF()};
    painter->setPen(miterPen);
    painter->setBrush(brush);
    painter->drawConvexPolygon(points, 4);
    painter->setBrush(brushBackup);
    painter->setPen(penBackup);
    break;
  }
  case esLineArrow: {
    QPointF points[3] = {(pos - lengthVec + widthVec).toPointF(),
                         pos.toPointF(),
                         (pos - lengthVec - widthVec).toPointF()};
    painter->setPen(miterPen);
    painter->drawPolyline(points, 3);
    painter->setPen(penBackup);
    break;
  }
  case esDisc: {
    painter->setBrush(brush);
    painter->drawEllipse(pos.toPointF(), mWidth * 0.5, mWidth * 0.5);
    painter->setBrush(brushBackup);
    break;
  }
  case esSquare: {
    QVector2D widthVecPerp(-widthVec.y(), widthVec.x());
    QPointF points[4] = {(pos - widthVecPerp + widthVec).toPointF(),
                         (pos - widthVecPerp - widthVec).toPointF(),
                         (pos + widthVecPerp - widthVec).toPointF(),
                         (pos + widthVecPerp + widthVec).toPointF()};
    painter->setPen(miterPen);
    painter->setBrush(brush);
    painter->drawConvexPolygon(points, 4);
    painter->setBrush(brushBackup);
    painter->setPen(penBackup);
    break;
  }
  case esDiamond: {
    QVector2D widthVecPerp(-widthVec.y(), widthVec.x());
    QPointF points[4] = {
        (pos - widthVecPerp).toPointF(), (pos - widthVec).toPointF(),
        (pos + widthVecPerp).toPointF(), (pos + widthVec).toPointF()};
    painter->setPen(miterPen);
    painter->setBrush(brush);
    painter->drawConvexPolygon(points, 4);
    painter->setBrush(brushBackup);
    painter->setPen(penBackup);
    break;
  }
  case esBar: {
    painter->drawLine((pos + widthVec).toPointF(), (pos - widthVec).toPointF());
    break;
  }
  case esHalfBar: {
    painter->drawLine((pos + widthVec).toPointF(), pos.toPointF());
    break;
  }
  case esSkewedBar: {
    if (qFuzzyIsNull(painter->pen().widthF()) &&
        !painter->modes().testFlag(QCPPainter::pmNonCosmetic)) {
      // if drawing with cosmetic pen (perfectly thin stroke, happens only in
      // vector exports), draw bar exactly on tip of line
      painter->drawLine(
          (pos + widthVec + lengthVec * 0.2f * (mInverted ? -1 : 1)).toPointF(),
          (pos - widthVec - lengthVec * 0.2f * (mInverted ? -1 : 1))
              .toPointF());
    } else {
      // if drawing with thick (non-cosmetic) pen, shift bar a little in line
      // direction to prevent line from sticking through bar slightly
      painter->drawLine(
          (pos + widthVec + lengthVec * 0.2f * (mInverted ? -1 : 1) +
           dir.normalized() * qMax(1.0f, (float)painter->pen().widthF()) * 0.5f)
              .toPointF(),
          (pos - widthVec - lengthVec * 0.2f * (mInverted ? -1 : 1) +
           dir.normalized() * qMax(1.0f, (float)painter->pen().widthF()) * 0.5f)
              .toPointF());
    }
    break;
  }
  }
}
void QCPLineEnding::draw (QCPPainter * painter, const QVector2D & pos, double angle) const
Definition at line 3940 of file qcustomplot.cpp.
References draw().
                                             {
  draw(painter, pos, QVector2D(qCos(angle), qSin(angle)));
}
bool QCPLineEnding::inverted () const [inline]
Definition at line 1064 of file qcustomplot.h.
Referenced by QCPAxisPainterPrivate::draw(), and setInverted().
{ return mInverted; }
double QCPLineEnding::length () const [inline]
Definition at line 1063 of file qcustomplot.h.
Referenced by setLength().
{ return mLength; }
double QCPLineEnding::realLength () const
Starting from the origin of this line ending (which is style specific), returns the length covered by the line ending symbol, in backward direction.
For example, the esSpikeArrow has a shorter real length than a esFlatArrow, even if both have the same setLength value, because the spike arrow has an inward curved back, which reduces the length along its center axis (the drawing origin for arrows is at the tip).
This function is used for precise, style specific placement of line endings, for example in QCPAxes.
Definition at line 3789 of file qcustomplot.cpp.
References esBar, esDiamond, esDisc, esFlatArrow, esHalfBar, esLineArrow, esNone, esSkewedBar, esSpikeArrow, esSquare, mLength, mStyle, and mWidth.
Referenced by QCPAxisPainterPrivate::draw().
                                       {
  switch (mStyle) {
  case esNone:
  case esLineArrow:
  case esSkewedBar:
  case esBar:
  case esHalfBar:
    return 0;
  case esFlatArrow:
    return mLength;
  case esDisc:
  case esSquare:
  case esDiamond:
    return mWidth * 0.5;
  case esSpikeArrow:
    return mLength * 0.8;
  }
  return 0;
}
void QCPLineEnding::setInverted (bool inverted)
Sets whether the ending decoration shall be inverted. For example, an arrow decoration will point inward when inverted is set to true.
Note that also the width direction is inverted. For symmetrical ending styles like arrows or discs, this doesn't make a difference. However, asymmetric styles like esHalfBar are affected by it, which can be used to control to which side the half bar points to.
Definition at line 3736 of file qcustomplot.cpp.
References inverted(), and mInverted.
{ mInverted = inverted; }
void QCPLineEnding::setLength (double length)
Sets the length of the ending decoration, if the style supports it. On arrows, for example, the length defines the size in pointing direction.
See also
setWidth
Definition at line 3722 of file qcustomplot.cpp.
References length(), and mLength.
{ mLength = length; }
void QCPLineEnding::setStyle (QCPLineEnding::EndingStyle style)
Sets the style of the ending decoration.
Definition at line 3702 of file qcustomplot.cpp.
References mStyle, and style().
                                                           {
  mStyle = style;
}
void QCPLineEnding::setWidth (double width)
Sets the width of the ending decoration, if the style supports it. On arrows, for example, the width defines the size perpendicular to the arrow's pointing direction.
See also
setLength
Definition at line 3713 of file qcustomplot.cpp.
References mWidth, and width().
{ mWidth = width; }
EndingStyle QCPLineEnding::style () const [inline]
Definition at line 1061 of file qcustomplot.h.
Referenced by QCPAxisPainterPrivate::draw(), QCPItemLine::draw(), QCPItemCurve::draw(), and setStyle().
{ return mStyle; }
double QCPLineEnding::width () const [inline]
Definition at line 1062 of file qcustomplot.h.
Referenced by setWidth().
{ return mWidth; }
Member Data Documentation
bool QCPLineEnding::mInverted [protected]
Definition at line 1083 of file qcustomplot.h.
Referenced by draw(), and setInverted().
double QCPLineEnding::mLength [protected]
Definition at line 1082 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), realLength(), and setLength().
EndingStyle QCPLineEnding::mStyle [protected]
Definition at line 1081 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), realLength(), and setStyle().
double QCPLineEnding::mWidth [protected]
Definition at line 1082 of file qcustomplot.h.
Referenced by boundingDistance(), draw(), realLength(), and setWidth().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp