QParticleSelector Class Reference
#include <qparticleselector.h>
Public Slots
void setValue (int newValue)
Signals
void valueChanged (int newValue)
Public Member Functions
QParticleSelector (QWidget *parent=0)
~QParticleSelector ()
void setDisabled (bool value, int currentClass=1)
Private Slots
void on_pb_1_clicked (bool checked)
void on_pb_2_clicked (bool checked)
void on_pb_3_clicked (bool checked)
void on_pb_4_clicked (bool checked)
void on_pb_5_clicked (bool checked)
void on_pb_6_clicked (bool checked)
void on_pb_7_clicked (bool checked)
void on_pb_8_clicked (bool checked)
void on_pb_9_clicked (bool checked)
void on_pb_10_clicked (bool checked)
void on_pb_11_clicked (bool checked)
void on_pb_12_clicked (bool checked)
void on_pb_13_clicked (bool checked)
void on_pb_14_clicked (bool checked)
void on_pb_15_clicked (bool checked)
void on_pb_16_clicked (bool checked)
void on_pb_17_clicked (bool checked)
void on_pb_18_clicked (bool checked)
Private Attributes
QVector< QPushButton * > btns
Ui::QParticleSelector * ui
Detailed Description
Definition at line 11 of file qparticleselector.h.
Constructor & Destructor Documentation
QParticleSelector::QParticleSelector (QWidget * parent = 0) [explicit]
Definition at line 4 of file qparticleselector.cpp.
References btns, and ui.
QParticleSelector::~QParticleSelector ()
Definition at line 27 of file qparticleselector.cpp.
References btns, and ui.
Member Function Documentation
void QParticleSelector::on_pb_10_clicked (bool checked) [private], [slot]
Definition at line 104 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_11_clicked (bool checked) [private], [slot]
Definition at line 110 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_12_clicked (bool checked) [private], [slot]
Definition at line 116 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_13_clicked (bool checked) [private], [slot]
Definition at line 122 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_14_clicked (bool checked) [private], [slot]
Definition at line 128 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_15_clicked (bool checked) [private], [slot]
Definition at line 134 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_16_clicked (bool checked) [private], [slot]
Definition at line 140 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_17_clicked (bool checked) [private], [slot]
Definition at line 146 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_18_clicked (bool checked) [private], [slot]
Definition at line 152 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_1_clicked (bool checked) [private], [slot]
Definition at line 50 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_2_clicked (bool checked) [private], [slot]
Definition at line 56 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_3_clicked (bool checked) [private], [slot]
Definition at line 62 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_4_clicked (bool checked) [private], [slot]
Definition at line 68 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_5_clicked (bool checked) [private], [slot]
Definition at line 74 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_6_clicked (bool checked) [private], [slot]
Definition at line 80 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_7_clicked (bool checked) [private], [slot]
Definition at line 86 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_8_clicked (bool checked) [private], [slot]
Definition at line 92 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::on_pb_9_clicked (bool checked) [private], [slot]
Definition at line 98 of file qparticleselector.cpp.
References valueChanged().
void QParticleSelector::setDisabled (bool value, int currentClass = 1)
Definition at line 39 of file qparticleselector.cpp.
References btns.
void QParticleSelector::setValue (int newValue) [slot]
Definition at line 35 of file qparticleselector.cpp.
References btns.
void QParticleSelector::valueChanged (int newValue) [signal]
Referenced by on_pb_10_clicked(), on_pb_11_clicked(), on_pb_12_clicked(), on_pb_13_clicked(), on_pb_14_clicked(), on_pb_15_clicked(), on_pb_16_clicked(), on_pb_17_clicked(), on_pb_18_clicked(), on_pb_1_clicked(), on_pb_2_clicked(), on_pb_3_clicked(), on_pb_4_clicked(), on_pb_5_clicked(), on_pb_6_clicked(), on_pb_7_clicked(), on_pb_8_clicked(), and on_pb_9_clicked().
Member Data Documentation
QVector<QPushButton *> QParticleSelector::btns [private]
Definition at line 65 of file qparticleselector.h.
Referenced by QParticleSelector(), setDisabled(), setValue(), and ~QParticleSelector().
Ui::QParticleSelector* QParticleSelector::ui [private]
Definition at line 66 of file qparticleselector.h.
Referenced by QParticleSelector(), and ~QParticleSelector().
The documentation for this class was generated from the following files:
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/QParticleSelector/qparticleselector.h
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/QParticleSelector/qparticleselector.cpp