Hardware::Microscope Class Reference
#include <Microscope.h>
Classes
struct _CustomData
struct Cam_t
struct Control_t
struct Resolution_t
Public Types
enum Arch { ARM,
X64
 }
enum PixelFormat { YUYV,
MJPG,
GREY
 }
typedef std::vector< Control_t > Controls_t
typedef struct Hardware::Microscope::_CustomData CustomData
Public Slots
void on_imageretrieved ()
Signals
void imageretrieved ()
Public Member Functions
Microscope ()
Microscope (const Microscope &rhs)
~Microscope ()
Microscope operator= (Microscope const &rhs)
bool IsOpened ()
bool openCam (Cam_t *cam)
bool openCam (int &cam)
bool openCam (std::string &cam)
bool closeCam (Cam_t *cam)
void GetFrame (cv::Mat &dst)
void GetGstreamFrame (cv::Mat &dst)
void GetHDRFrame (cv::Mat &dst, uint32_t noframes=3)
Control_t * GetControl (const std::string name)
void SetControl (Control_t *control)
Cam_t * FindCam (std::string cam)
Cam_t * FindCam (int cam)
void SendImageRetrieved ()
Public Attributes
std::vector< Cam_t > AvailableCams
Cam_t * SelectedCam = nullptr
Arch RunEnv
cv::Mat lastFrame
Private Member Functions
void getResolutions (Cam_t &currentCam, int FormatType)
std::vector< Cam_t > GetAvailableCams ()
Arch GetCurrentArchitecture ()
Static Private Member Functions
static void new_buffer (GstElement *sink, CustomData *data)
Private Attributes
bool openedUptheCam = false
cv::VideoCapture * cap = nullptr
std::vector< cv::Mat > HDRframes
int fd
Detailed Description
Definition at line 49 of file Microscope.h.
Member Typedef Documentation
typedef std::vector<Control_t> Hardware::Microscope::Controls_t
Definition at line 103 of file Microscope.h.
typedef struct Hardware::Microscope::_CustomData Hardware::Microscope::CustomData
Member Enumeration Documentation
enum Hardware::Microscope::Arch
Enumerator
ARM
X64
Definition at line 53 of file Microscope.h.
enum Hardware::Microscope::PixelFormat
Enumerator
YUYV
MJPG
GREY
Definition at line 55 of file Microscope.h.
Constructor & Destructor Documentation
Microscope::Microscope ()
Definition at line 12 of file Microscope.cpp.
References AvailableCams, GetAvailableCams(), GetCurrentArchitecture(), imageretrieved(), on_imageretrieved(), and RunEnv.
Microscope::Microscope (const Microscope & rhs)
Definition at line 21 of file Microscope.cpp.
References AvailableCams, cap, fd, HDRframes, imageretrieved(), on_imageretrieved(), RunEnv, and SelectedCam.
Microscope::~Microscope ()
Definition at line 32 of file Microscope.cpp.
References cap.
Member Function Documentation
bool Microscope::closeCam (Cam_t * cam)
Definition at line 311 of file Microscope.cpp.
References openedUptheCam, Hardware::Microscope::Cam_t::Pipe, and Hardware::Microscope::_CustomData::pipeline.
Referenced by GetFrame(), and openCam().
Cam_t* Hardware::Microscope::FindCam (std::string cam)
Referenced by openCam().
Microscope::Cam_t * Microscope::FindCam (int cam)
Definition at line 293 of file Microscope.cpp.
References AvailableCams.
std::vector< Microscope::Cam_t > Microscope::GetAvailableCams () [private]
Definition at line 47 of file Microscope.cpp.
References Hardware::Microscope::Cam_t::Controls, Hardware::Microscope::Control_t::current_value, Hardware::Microscope::Control_t::default_value, Hardware::Microscope::Cam_t::devString, EXCEPTION_NOCAMS, EXCEPTION_NOCAMS_NR, EXCEPTION_QUERY, EXCEPTION_QUERY_NR, Hardware::Microscope::Cam_t::fd, getResolutions(), Hardware::Microscope::Control_t::ID, Hardware::Microscope::Cam_t::ID, Hardware::Microscope::Control_t::maximum, Hardware::Microscope::Control_t::minimum, Hardware::Microscope::Control_t::name, Hardware::Microscope::Cam_t::Name, and Hardware::Microscope::Control_t::step.
Referenced by Microscope().
Microscope::Control_t * Microscope::GetControl (const std::string name)
Definition at line 364 of file Microscope.cpp.
References Hardware::Microscope::Cam_t::Controls, and SelectedCam.
Referenced by GetHDRFrame().
Microscope::Arch Microscope::GetCurrentArchitecture () [private]
Definition at line 34 of file Microscope.cpp.
Referenced by Microscope().
void Microscope::GetFrame (cv::Mat & dst)
Definition at line 319 of file Microscope.cpp.
References closeCam(), imageretrieved(), IsOpened(), lastFrame, openCam(), Hardware::Microscope::Cam_t::Pipe, Hardware::Microscope::_CustomData::pipeline, and SelectedCam.
Referenced by GetHDRFrame().
void Hardware::Microscope::GetGstreamFrame (cv::Mat & dst)
void Microscope::GetHDRFrame (cv::Mat & dst, uint32_t noframes = 3)
Definition at line 333 of file Microscope.cpp.
References Hardware::Microscope::Control_t::current_value, GetControl(), GetFrame(), HDRframes, Hardware::Microscope::Control_t::maximum, and Hardware::Microscope::Control_t::minimum.
void Microscope::getResolutions (Cam_t & currentCam, int FormatType) [private]
Definition at line 123 of file Microscope.cpp.
References Hardware::Microscope::Cam_t::fd, Hardware::Microscope::Resolution_t::format, Hardware::Microscope::Resolution_t::Height, Hardware::Microscope::Resolution_t::ID, Hardware::Microscope::Cam_t::Resolutions, and Hardware::Microscope::Resolution_t::Width.
Referenced by GetAvailableCams().
void Hardware::Microscope::imageretrieved () [signal]
Referenced by GetFrame(), Microscope(), and SendImageRetrieved().
bool Microscope::IsOpened ()
Definition at line 165 of file Microscope.cpp.
References openedUptheCam.
Referenced by GetFrame().
void Microscope::new_buffer (GstElement * sink, CustomData * data) [static], [private]
Definition at line 413 of file Microscope.cpp.
References Hardware::Microscope::_CustomData::currentMicroscope, Hardware::Microscope::Resolution_t::Height, lastFrame, SelectedCam, Hardware::Microscope::Cam_t::SelectedResolution, SendImageRetrieved(), and Hardware::Microscope::Resolution_t::Width.
Referenced by openCam().
void Microscope::on_imageretrieved () [slot]
Definition at line 331 of file Microscope.cpp.
Referenced by Microscope().
bool Microscope::openCam (Cam_t * cam)
Definition at line 167 of file Microscope.cpp.
References AvailableCams, Hardware::Microscope::_CustomData::bayer, Hardware::Microscope::_CustomData::bus, Hardware::Microscope::_CustomData::caps, Hardware::Microscope::_CustomData::capsfilter, closeCam(), Hardware::Microscope::_CustomData::colorspace, Hardware::Microscope::Cam_t::Controls, Hardware::Microscope::_CustomData::convert, Hardware::Microscope::_CustomData::currentMicroscope, Hardware::Microscope::Cam_t::devString, EXCEPTION_GSTREAM_ELEM_EXCEPTION, EXCEPTION_GSTREAM_ELEM_EXCEPTION_NR, EXCEPTION_GSTREAM_INIT_EXCEPTION, EXCEPTION_GSTREAM_INIT_EXCEPTION_NR, Hardware::Microscope::Resolution_t::format, Hardware::Microscope::Resolution_t::Height, Hardware::Microscope::Cam_t::Name, new_buffer(), openedUptheCam, Hardware::Microscope::Cam_t::Pipe, Hardware::Microscope::_CustomData::pipeline, Hardware::Microscope::_CustomData::queue, SelectedCam, Hardware::Microscope::Cam_t::SelectedResolution, SetControl(), Hardware::Microscope::_CustomData::sink, Hardware::Microscope::_CustomData::source, Hardware::Microscope::_CustomData::tiscolorize, Hardware::Microscope::_CustomData::tisvideobuffer, and Hardware::Microscope::Resolution_t::Width.
Referenced by GetFrame(), and openCam().
bool Microscope::openCam (int & cam)
Definition at line 291 of file Microscope.cpp.
References FindCam(), and openCam().
bool Microscope::openCam (std::string & cam)
Definition at line 289 of file Microscope.cpp.
References FindCam(), and openCam().
Microscope Hardware::Microscope::operator= (Microscope const & rhs)
void Microscope::SendImageRetrieved ()
Definition at line 411 of file Microscope.cpp.
References imageretrieved().
Referenced by new_buffer().
void Microscope::SetControl (Control_t * control)
Definition at line 374 of file Microscope.cpp.
References Hardware::Microscope::Control_t::current_value, Hardware::Microscope::Cam_t::devString, EXCEPTION_CTRL_NOT_FOUND, EXCEPTION_CTRL_NOT_FOUND_NR, EXCEPTION_NOCAMS, EXCEPTION_NOCAMS_NR, EXCEPTION_QUERY, EXCEPTION_QUERY_NR, Hardware::Microscope::Cam_t::fd, Hardware::Microscope::Control_t::ID, and SelectedCam.
Referenced by openCam().
Member Data Documentation
std::vector<Cam_t> Hardware::Microscope::AvailableCams
Definition at line 148 of file Microscope.h.
Referenced by FindCam(), Microscope(), and openCam().
cv::VideoCapture* Hardware::Microscope::cap = nullptr [private]
Definition at line 189 of file Microscope.h.
Referenced by Microscope(), and ~Microscope().
int Hardware::Microscope::fd [private]
Definition at line 195 of file Microscope.h.
Referenced by Microscope().
std::vector<cv::Mat> Hardware::Microscope::HDRframes [private]
Definition at line 191 of file Microscope.h.
Referenced by GetHDRFrame(), and Microscope().
cv::Mat Hardware::Microscope::lastFrame
Definition at line 175 of file Microscope.h.
Referenced by GetFrame(), and new_buffer().
bool Hardware::Microscope::openedUptheCam = false [private]
Definition at line 188 of file Microscope.h.
Referenced by closeCam(), IsOpened(), and openCam().
Arch Hardware::Microscope::RunEnv
Definition at line 150 of file Microscope.h.
Referenced by Microscope().
Cam_t* Hardware::Microscope::SelectedCam = nullptr
Definition at line 149 of file Microscope.h.
Referenced by GetControl(), GetFrame(), Microscope(), new_buffer(), openCam(), and SetControl().
The documentation for this class was generated from the following files:
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/SoilHardware/Microscope.h
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/SoilHardware/Microscope.cpp