SoilMath::PSD Class Reference
#include <psd.h>
Public Member Functions
PSD ()
PSD (double *data, uint32_t nodata, double *binranges, uint32_t nobins, uint32_t endbin)
Private Member Functions
uint32_t DetBin (float value)
void BasicCalculatePSD ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Detailed Description
Definition at line 14 of file psd.h.
Constructor & Destructor Documentation
SoilMath::PSD::PSD () [inline]
Definition at line 62 of file psd.h.
SoilMath::PSD::PSD (double * data, uint32_t nodata, double * binranges, uint32_t nobins, uint32_t endbin) [inline]
Definition at line 64 of file psd.h.
References BasicCalculatePSD(), SoilMath::Stats< double, double, long double >::BinRanges, SoilMath::Stats< double, double, long double >::Cols, SoilMath::Stats< double, double, long double >::Data, and SoilMath::Stats< double, double, long double >::Rows.
Member Function Documentation
void SoilMath::PSD::BasicCalculatePSD () [inline], [private]
Definition at line 27 of file psd.h.
References SoilMath::Stats< double, double, long double >::bins, SoilMath::Stats< double, double, long double >::Calculated, SoilMath::Stats< double, double, long double >::Cols, SoilMath::Stats< double, double, long double >::Data, DetBin(), SoilMath::Stats< double, double, long double >::getCFD(), SoilMath::Stats< double, double, long double >::max, SoilMath::Stats< double, double, long double >::Mean, SoilMath::Stats< double, double, long double >::min, SoilMath::Stats< double, double, long double >::n, SoilMath::Stats< double, double, long double >::Range, SoilMath::Stats< double, double, long double >::Rows, SoilMath::Stats< double, double, long double >::Std, and SoilMath::Stats< double, double, long double >::Sum.
Referenced by PSD().
uint32_t SoilMath::PSD::DetBin (float value) [inline], [private]
Definition at line 16 of file psd.h.
References SoilMath::Stats< double, double, long double >::BinRanges, and SoilMath::Stats< double, double, long double >::noBins.
Referenced by BasicCalculatePSD().
template<class Archive > void SoilMath::PSD::serialize (Archive & ar, const unsigned int version) [inline], [private]
Definition at line 54 of file psd.h.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Definition at line 51 of file psd.h.
The documentation for this class was generated from the following file:
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/SoilMath/psd.h