QCPBarsGroup Class Reference
Groups multiple QCPBars together so they appear side by side.
#include <qcustomplot.h>
Public Types
enum SpacingType { stAbsolute,
stAxisRectRatio,
stPlotCoords
 }
Public Member Functions
QCPBarsGroup (QCustomPlot *parentPlot)
~QCPBarsGroup ()
SpacingType spacingType () const
double spacing () const
void setSpacingType (SpacingType spacingType)
void setSpacing (double spacing)
QList< QCPBars * > bars () const
QCPBars * bars (int index) const
int size () const
bool isEmpty () const
void clear ()
bool contains (QCPBars *bars) const
void append (QCPBars *bars)
void insert (int i, QCPBars *bars)
void remove (QCPBars *bars)
Protected Member Functions
void registerBars (QCPBars *bars)
void unregisterBars (QCPBars *bars)
double keyPixelOffset (const QCPBars *bars, double keyCoord)
double getPixelSpacing (const QCPBars *bars, double keyCoord)
Protected Attributes
QCustomPlot * mParentPlot
SpacingType mSpacingType
double mSpacing
QList< QCPBars * > mBars
Friends
class QCPBars
Detailed Description
Groups multiple QCPBars together so they appear side by side.
When showing multiple QCPBars in one plot which have bars at identical keys, it may be desirable to have them appearing next to each other at each key. This is what adding the respective QCPBars plottables to a QCPBarsGroup achieves. (An alternative approach is to stack them on top of each other, see QCPBars::moveAbove.)
Usage
To add a QCPBars plottable to the group, create a new group and then add the respective bars intances:
Alternatively to appending to the group like shown above, you can also set the group on the QCPBars plottable via QCPBars::setBarsGroup.
The spacing between the bars can be configured via setSpacingType and setSpacing. The bars in this group appear in the plot in the order they were appended. To insert a bars plottable at a certain index position, or to reposition a bars plottable which is already in the group, use insert.
To remove specific bars from the group, use either remove or call QCPBars::setBarsGroup(0) on the respective bars plottable.
To clear the entire group, call clear, or simply delete the group.
Example
The image above is generated with the following code:
Definition at line 3162 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPBarsGroup::SpacingType
Defines the ways the spacing between bars in the group can be specified. Thus it defines what the number passed to setSpacing actually means.
See also
setSpacingType, setSpacing
Enumerator
stAbsolute
 Bar spacing is in absolute pixels.
stAxisRectRatio
 Bar spacing is given by a fraction of the axis rect size
stPlotCoords
 Bar spacing is in key coordinates and thus scales with the key axis range
Definition at line 3176 of file qcustomplot.h.
                   {
    stAbsolute
    ,
    stAxisRectRatio
    ,
    stPlotCoords
  };
Constructor & Destructor Documentation
QCPBarsGroup::QCPBarsGroup (QCustomPlot * parentPlot)
Constructs a new bars group for the specified QCustomPlot instance.
Definition at line 20226 of file qcustomplot.cpp.
    : QObject(parentPlot), mParentPlot(parentPlot), mSpacingType(
      stAbsolute),
      mSpacing(4) {}
QCPBarsGroup::~QCPBarsGroup ()
Definition at line 20230 of file qcustomplot.cpp.
References clear().
{ clear(); }
Member Function Documentation
void QCPBarsGroup::append (QCPBars * bars)
Adds the specified bars plottable to this group. Alternatively, you can also use QCPBars::setBarsGroup on the bars instance.
See also
insert, remove
Definition at line 20289 of file qcustomplot.cpp.
References bars(), mBars, and QCPBars::setBarsGroup().
                                       {
  if (!bars) {
    qDebug() << Q_FUNC_INFO << "bars is 0";
    return;
  }
  if (!mBars.contains(bars))
    bars->setBarsGroup(this);
  else
    qDebug() << Q_FUNC_INFO << "bars plottable is already in this bars group:"
             << reinterpret_cast<quintptr>(bars);
}
QList< QCPBars * > QCPBarsGroup::bars () const [inline]
Returns all bars currently in this group.
See also
bars(int index)
Definition at line 3197 of file qcustomplot.h.
Referenced by append(), clear(), keyPixelOffset(), and remove().
{ return mBars; }
QCPBars * QCPBarsGroup::bars (int index) const
Returns the QCPBars instance with the specified index in this group. If no such QCPBars exists, returns 0.
See also
bars(), size
Definition at line 20261 of file qcustomplot.cpp.
References mBars.
                                           {
  if (index >= 0 && index < mBars.size()) {
    return mBars.at(index);
  } else {
    qDebug() << Q_FUNC_INFO << "index out of bounds:" << index;
    return 0;
  }
}
void QCPBarsGroup::clear ()
Removes all QCPBars plottables from this group.
See also
isEmpty
Definition at line 20275 of file qcustomplot.cpp.
References bars(), mBars, and QCPBars::setBarsGroup().
Referenced by ~QCPBarsGroup().
                         {
  foreach (
      QCPBars *bars,
      mBars) // since foreach takes a copy, removing bars in the loop is okay
    bars->setBarsGroup(0); // removes itself via removeBars
}
bool QCPBarsGroup::contains (QCPBars * bars) const [inline]
Returns whether the specified bars plottable is part of this group.
Definition at line 3202 of file qcustomplot.h.
{ return mBars.contains(bars); }
double QCPBarsGroup::getPixelSpacing (const QCPBars * bars, double keyCoord) [protected]
Definition at line 20482 of file qcustomplot.cpp.
References QCPAxis::axisRect(), QCPAxis::coordToPixel(), QCPAxisRect::height(), QCPAbstractPlottable::keyAxis(), mSpacing, mSpacingType, QCPAxis::orientation(), stAbsolute, stAxisRectRatio, stPlotCoords, and QCPAxisRect::width().
Referenced by keyPixelOffset().
                                                                         {
  switch (mSpacingType) {
  case stAbsolute: {
    return mSpacing;
  }
  case stAxisRectRatio: {
    if (bars->keyAxis()->orientation() == Qt::Horizontal)
      return bars->keyAxis()->axisRect()->width() * mSpacing;
    else
      return bars->keyAxis()->axisRect()->height() *
      mSpacing;
  }
  case stPlotCoords: {
    double keyPixel = bars->keyAxis()->coordToPixel(keyCoord);
    return bars->keyAxis()->coordToPixel(keyCoord + mSpacing) - keyPixel;
  }
  }
  return 0;
}
void QCPBarsGroup::insert (int i, QCPBars * bars)
Inserts the specified bars plottable into this group at the specified index position i. This gives you full control over the ordering of the bars.
bars may already be part of this group. In that case, bars is just moved to the new index position.
See also
append, remove
Definition at line 20313 of file qcustomplot.cpp.
References mBars, and QCPBars::setBarsGroup().
                                              {
  if (!bars) {
    qDebug() << Q_FUNC_INFO << "bars is 0";
    return;
  }
  // first append to bars list normally:
  if (!mBars.contains(bars))
    bars->setBarsGroup(this);
  // then move to according position:
  mBars.move(mBars.indexOf(bars), qBound(0, i, mBars.size() - 1));
}
bool QCPBarsGroup::isEmpty () const [inline]
Returns whether this bars group is empty.
See also
size
Definition at line 3200 of file qcustomplot.h.
{ return mBars.isEmpty(); }
double QCPBarsGroup::keyPixelOffset (const QCPBars * bars, double keyCoord) [protected]
Definition at line 20375 of file qcustomplot.cpp.
References QCPBars::barBelow(), bars(), getPixelSpacing(), i, and mBars.
Referenced by QCPBars::getBarPolygon(), and QCPBars::getKeyRange().
                                                                        {
  // find list of all base bars in case some mBars are stacked:
  QList<const QCPBars *> baseBars;
  foreach (const QCPBars *b, mBars) {
    while (b->barBelow())
      b = b->barBelow();
    if (!baseBars.contains(b))
      baseBars.append(b);
  }
  // find base bar this "bars" is stacked on:
  const QCPBars *thisBase = bars;
  while (thisBase->barBelow())
    thisBase = thisBase->barBelow();
  // determine key pixel offset of this base bars considering all other base
  // bars in this barsgroup:
  double result = 0;
  int index = baseBars.indexOf(thisBase);
  if (index >= 0) {
    int startIndex;
    double lowerPixelWidth, upperPixelWidth;
    if (baseBars.size() % 2 == 1 &&
        index ==
            (baseBars.size() - 1) /
                2) // is center bar (int division on purpose)
    {
      return result;
    } else if (index <
               (baseBars.size() - 1) / 2.0) // bar is to the left of center
    {
      if (baseBars.size() % 2 == 0) // even number of bars
      {
        startIndex = baseBars.size() / 2 - 1;
        result -= getPixelSpacing(baseBars.at(startIndex), keyCoord) *
                  0.5; // half of middle spacing
      } else // uneven number of bars
      {
        startIndex = (baseBars.size() - 1) / 2 - 1;
        baseBars.at((baseBars.size() - 1) / 2)
            ->getPixelWidth(keyCoord, lowerPixelWidth, upperPixelWidth);
        result -=
            qAbs(upperPixelWidth - lowerPixelWidth) * 0.5; // half of center bar
        result -= getPixelSpacing(baseBars.at((baseBars.size() - 1) / 2),
                                  keyCoord); // center bar spacing
      }
      for (
          int i = startIndex; i > index;
          --i) // add widths and spacings of bars in between center and our bars
      {
        baseBars.at(i)
            ->getPixelWidth(keyCoord, lowerPixelWidth, upperPixelWidth);
        result -= qAbs(upperPixelWidth - lowerPixelWidth);
        result -= getPixelSpacing(baseBars.at(i), keyCoord);
      }
      // finally half of our bars width:
      baseBars.at(index)
          ->getPixelWidth(keyCoord, lowerPixelWidth, upperPixelWidth);
      result -= qAbs(upperPixelWidth - lowerPixelWidth) * 0.5;
    } else // bar is to the right of center
    {
      if (baseBars.size() % 2 == 0) // even number of bars
      {
        startIndex = baseBars.size() / 2;
        result += getPixelSpacing(baseBars.at(startIndex), keyCoord) *
                  0.5; // half of middle spacing
      } else // uneven number of bars
      {
        startIndex = (baseBars.size() - 1) / 2 + 1;
        baseBars.at((baseBars.size() - 1) / 2)
            ->getPixelWidth(keyCoord, lowerPixelWidth, upperPixelWidth);
        result +=
            qAbs(upperPixelWidth - lowerPixelWidth) * 0.5; // half of center bar
        result += getPixelSpacing(baseBars.at((baseBars.size() - 1) / 2),
                                  keyCoord); // center bar spacing
      }
      for (
          int i = startIndex; i < index;
          ++i) // add widths and spacings of bars in between center and our bars
      {
        baseBars.at(i)
            ->getPixelWidth(keyCoord, lowerPixelWidth, upperPixelWidth);
        result += qAbs(upperPixelWidth - lowerPixelWidth);
        result += getPixelSpacing(baseBars.at(i), keyCoord);
      }
      // finally half of our bars width:
      baseBars.at(index)
          ->getPixelWidth(keyCoord, lowerPixelWidth, upperPixelWidth);
      result += qAbs(upperPixelWidth - lowerPixelWidth) * 0.5;
    }
  }
  return result;
}
void QCPBarsGroup::registerBars (QCPBars * bars) [protected]
Definition at line 20352 of file qcustomplot.cpp.
References mBars.
Referenced by QCPBars::setBarsGroup().
                                             {
  if (!mBars.contains(bars))
    mBars.append(bars);
}
void QCPBarsGroup::remove (QCPBars * bars)
Removes the specified bars plottable from this group.
See also
contains, clear
Definition at line 20331 of file qcustomplot.cpp.
References bars(), mBars, and QCPBars::setBarsGroup().
                                       {
  if (!bars) {
    qDebug() << Q_FUNC_INFO << "bars is 0";
    return;
  }
  if (mBars.contains(bars))
    bars->setBarsGroup(0);
  else
    qDebug() << Q_FUNC_INFO << "bars plottable is not in this bars group:"
             << reinterpret_cast<quintptr>(bars);
}
void QCPBarsGroup::setSpacing (double spacing)
Sets the spacing between adjacent bars. What the number passed as spacing actually means, is defined by the current SpacingType, which can be set with setSpacingType.
See also
setSpacingType
Definition at line 20252 of file qcustomplot.cpp.
References mSpacing, and spacing().
{ mSpacing = spacing; }
void QCPBarsGroup::setSpacingType (SpacingType spacingType)
Sets how the spacing between adjacent bars is interpreted. See SpacingType.
The actual spacing can then be specified with setSpacing.
See also
setSpacing
Definition at line 20240 of file qcustomplot.cpp.
References mSpacingType, and spacingType().
                                                         {
  mSpacingType = spacingType;
}
int QCPBarsGroup::size () const [inline]
Returns the number of QCPBars plottables that are part of this group.
Definition at line 3199 of file qcustomplot.h.
{ return mBars.size(); }
double QCPBarsGroup::spacing () const [inline]
Definition at line 3190 of file qcustomplot.h.
Referenced by setSpacing().
{ return mSpacing; }
SpacingType QCPBarsGroup::spacingType () const [inline]
Definition at line 3189 of file qcustomplot.h.
Referenced by setSpacingType().
{ return mSpacingType; }
void QCPBarsGroup::unregisterBars (QCPBars * bars) [protected]
Definition at line 20365 of file qcustomplot.cpp.
References mBars.
Referenced by QCPBars::setBarsGroup().
{ mBars.removeOne(bars); }
Friends And Related Function Documentation
friend class QCPBars [friend]
Definition at line 3225 of file qcustomplot.h.
Member Data Documentation
QList<QCPBars *> QCPBarsGroup::mBars [protected]
Definition at line 3212 of file qcustomplot.h.
Referenced by append(), bars(), clear(), insert(), keyPixelOffset(), registerBars(), remove(), and unregisterBars().
QCustomPlot* QCPBarsGroup::mParentPlot [protected]
Definition at line 3209 of file qcustomplot.h.
double QCPBarsGroup::mSpacing [protected]
Definition at line 3211 of file qcustomplot.h.
Referenced by getPixelSpacing(), and setSpacing().
SpacingType QCPBarsGroup::mSpacingType [protected]
Definition at line 3210 of file qcustomplot.h.
Referenced by getPixelSpacing(), and setSpacingType().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp