QCPLayer Class Reference
A layer that may contain objects, to control the rendering order.
#include <qcustomplot.h>
Public Member Functions
QCPLayer (QCustomPlot *parentPlot, const QString &layerName)
~QCPLayer ()
QCustomPlot * parentPlot () const
QString name () const
int index () const
QList< QCPLayerable * > children () const
bool visible () const
void setVisible (bool visible)
Protected Member Functions
void addChild (QCPLayerable *layerable, bool prepend)
void removeChild (QCPLayerable *layerable)
Protected Attributes
QCustomPlot * mParentPlot
QString mName
int mIndex
QList< QCPLayerable * > mChildren
bool mVisible
Friends
class QCustomPlot
class QCPLayerable
Detailed Description
A layer that may contain objects, to control the rendering order.
The Layering system of QCustomPlot is the mechanism to control the rendering order of the elements inside the plot.
It is based on the two classes QCPLayer and QCPLayerable. QCustomPlot holds an ordered list of one or more instances of QCPLayer (see QCustomPlot::addLayer, QCustomPlot::layer, QCustomPlot::moveLayer, etc.). When replotting, QCustomPlot goes through the list of layers bottom to top and successively draws the layerables of the layers.
A QCPLayer contains an ordered list of QCPLayerable instances. QCPLayerable is an abstract base class from which almost all visible objects derive, like axes, grids, graphs, items, etc.
Initially, QCustomPlot has five layers: `background`, `grid`, `main`, `axes` and `legend` (in that order). The top two layers `axes` and `legend` contain the default axes and legend, so they will be drawn on top. In the middle, there is the `main` layer. It is initially empty and set as the current layer (see QCustomPlot::setCurrentLayer). This means, all new plottables, items etc. are created on this layer by default. Then comes the `grid` layer which contains the QCPGrid instances (which belong tightly to QCPAxis, see QCPAxis::grid). The Axis rect background shall be drawn behind everything else, thus the default QCPAxisRect instance is placed on the `background` layer. Of course, the layer affiliation of the individual objects can be changed as required (QCPLayerable::setLayer).
Controlling the ordering of objects is easy: Create a new layer in the position you want it to be, e.g. above `main`, with QCustomPlot::addLayer. Then set the current layer with QCustomPlot::setCurrentLayer to that new layer and finally create the objects normally. They will be placed on the new layer automatically, due to the current layer setting. Alternatively you could have also ignored the current layer setting and just moved the objects with QCPLayerable::setLayer to the desired layer after creating them.
It is also possible to move whole layers. For example, If you want the grid to be shown in front of all plottables/items on the `main` layer, just move it above `main` with QCustomPlot::moveLayer.
The rendering order within one layer is simply by order of creation or insertion. The item created last (or added last to the layer), is drawn on top of all other objects on that layer.
When a layer is deleted, the objects on it are not deleted with it, but fall on the layer below the deleted layer, see QCustomPlot::removeLayer.
Definition at line 479 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPLayer::QCPLayer (QCustomPlot * parentPlot, const QString & layerName)
Creates a new QCPLayer instance.
Normally you shouldn't directly instantiate layers, use QCustomPlot::addLayer instead.
Warning
It is not checked that layerName is actually a unique layer name in parentPlot. This check is only performed by QCustomPlot::addLayer.
Definition at line 775 of file qcustomplot.cpp.
    : QObject(parentPlot), mParentPlot(parentPlot), mName(layerName),
      mIndex(-1), // will be set to a proper value by the QCustomPlot layer
                  // creation function
      mVisible(true) {
  // Note: no need to make sure layerName is unique, because layer
  // management is done with QCustomPlot functions.
}
QCPLayer::~QCPLayer ()
Definition at line 784 of file qcustomplot.cpp.
References QCustomPlot::currentLayer(), mChildren, and mParentPlot.
                    {
  // If child layerables are still on this layer, detach them, so they don't try
  // to reach back to this
  // then invalid layer once they get deleted/moved themselves. This only
  // happens when layers are deleted
  // directly, like in the QCustomPlot destructor. (The regular layer removal
  // procedure for the user is to
  // call QCustomPlot::removeLayer, which moves all layerables off this layer
  // before deleting it.)
  while (!mChildren.isEmpty())
    mChildren.last()->setLayer(
        0); // removes itself from mChildren via removeChild()
  if (mParentPlot->currentLayer() == this)
    qDebug() << Q_FUNC_INFO << "The parent plot's mCurrentLayer will be a "
                               "dangling pointer. Should have been set to a "
                               "valid layer or 0 beforehand.";
}
Member Function Documentation
void QCPLayer::addChild (QCPLayerable * layerable, bool prepend) [protected]
Definition at line 829 of file qcustomplot.cpp.
References mChildren.
Referenced by QCPLayerable::moveToLayer().
                                                             {
  if (!mChildren.contains(layerable)) {
    if (prepend)
      mChildren.prepend(layerable);
    else
      mChildren.append(layerable);
  } else
    qDebug() << Q_FUNC_INFO << "layerable is already child of this layer"
             << reinterpret_cast<quintptr>(layerable);
}
QList< QCPLayerable * > QCPLayer::children () const [inline]
Returns a list of all layerables on this layer. The order corresponds to the rendering order: layerables with higher indices are drawn above layerables with lower indices.
Definition at line 496 of file qcustomplot.h.
Referenced by QCustomPlot::deselectAll(), QCustomPlot::draw(), QCustomPlot::mouseReleaseEvent(), and QCustomPlot::removeLayer().
{ return mChildren; }
int QCPLayer::index () const [inline]
Returns the index this layer has in the QCustomPlot. The index is the integer number by which this layer can be accessed via QCustomPlot::layer.
Layers with higher indices will be drawn above layers with lower indices.
Definition at line 495 of file qcustomplot.h.
Referenced by QCustomPlot::addLayer(), QCustomPlot::moveLayer(), and QCustomPlot::removeLayer().
{ return mIndex; }
QString QCPLayer::name () const [inline]
Definition at line 494 of file qcustomplot.h.
Referenced by QCustomPlot::layer(), and QCPLayerable::moveToLayer().
{ return mName; }
QCustomPlot* QCPLayer::parentPlot () const [inline]
Definition at line 493 of file qcustomplot.h.
Referenced by QCPLayerable::moveToLayer().
{ return mParentPlot; }
void QCPLayer::removeChild (QCPLayerable * layerable) [protected]
Definition at line 850 of file qcustomplot.cpp.
References mChildren.
Referenced by QCPLayerable::moveToLayer(), and QCPLayerable::~QCPLayerable().
                                                  {
  if (!mChildren.removeOne(layerable))
    qDebug() << Q_FUNC_INFO << "layerable is not child of this layer"
             << reinterpret_cast<quintptr>(layerable);
}
void QCPLayer::setVisible (bool visible)
Sets whether this layer is visible or not. If visible is set to false, all layerables on this layer will be invisible.
This function doesn't change the visibility property of the layerables (QCPLayerable::setVisible), but the QCPLayerable::realVisibility of each layerable takes the visibility of the parent layer into account.
Definition at line 814 of file qcustomplot.cpp.
References mVisible, and visible().
{ mVisible = visible; }
bool QCPLayer::visible () const [inline]
Definition at line 497 of file qcustomplot.h.
Referenced by QCPLayerable::realVisibility(), and setVisible().
{ return mVisible; }
Friends And Related Function Documentation
friend class QCPLayerable [friend]
Definition at line 518 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 517 of file qcustomplot.h.
Member Data Documentation
QList<QCPLayerable *> QCPLayer::mChildren [protected]
Definition at line 507 of file qcustomplot.h.
Referenced by addChild(), removeChild(), and ~QCPLayer().
int QCPLayer::mIndex [protected]
Definition at line 506 of file qcustomplot.h.
QString QCPLayer::mName [protected]
Definition at line 505 of file qcustomplot.h.
QCustomPlot* QCPLayer::mParentPlot [protected]
Definition at line 504 of file qcustomplot.h.
Referenced by ~QCPLayer().
bool QCPLayer::mVisible [protected]
Definition at line 508 of file qcustomplot.h.
Referenced by setVisible().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp