QCPAbstractItem Class Reference
The abstract base class for all items in a plot.
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Public Member Functions
QCPAbstractItem (QCustomPlot *parentPlot)
virtual ~QCPAbstractItem ()
bool clipToAxisRect () const
QCPAxisRect * clipAxisRect () const
bool selectable () const
bool selected () const
void setClipToAxisRect (bool clip)
void setClipAxisRect (QCPAxisRect *rect)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const =0
QList< QCPItemPosition * > positions () const
QList< QCPItemAnchor * > anchors () const
QCPItemPosition * position (const QString &name) const
QCPItemAnchor * anchor (const QString &name) const
bool hasAnchor (const QString &name) const
Protected Member Functions
virtual QCP::Interaction selectionCategory () const
virtual QRect clipRect () const
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)=0
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
virtual QPointF anchorPixelPoint (int anchorId) const
double distSqrToLine (const QPointF &start, const QPointF &end, const QPointF &point) const
double rectSelectTest (const QRectF &rect, const QPointF &pos, bool filledRect) const
QCPItemPosition * createPosition (const QString &name)
QCPItemAnchor * createAnchor (const QString &name, int anchorId)
Protected Attributes
bool mClipToAxisRect
QPointer< QCPAxisRect > mClipAxisRect
QList< QCPItemPosition * > mPositions
QList< QCPItemAnchor * > mAnchors
bool mSelectable
bool mSelected
Friends
class QCustomPlot
class QCPItemAnchor
Detailed Description
The abstract base class for all items in a plot.
In QCustomPlot, items are supplemental graphical elements that are neither plottables (QCPAbstractPlottable) nor axes (QCPAxis). While plottables are always tied to two axes and thus plot coordinates, items can also be placed in absolute coordinates independent of any axes. Each specific item has at least one QCPItemPosition member which controls the positioning. Some items are defined by more than one coordinate and thus have two or more QCPItemPosition members (For example, QCPItemRect has topLeft and bottomRight).
This abstract base class defines a very basic interface like visibility and clipping. Since this class is abstract, it can't be instantiated. Use one of the subclasses or create a subclass yourself to create new items.
The built-in items are:
QCPItemLine A line defined by a start and an end point. May have different ending styles on each side (e.g. arrows).
QCPItemStraightLine A straight line defined by a start and a direction point. Unlike QCPItemLine, the straight line is infinitely long and has no endings.
QCPItemCurve A curve defined by start, end and two intermediate control points. May have different ending styles on each side (e.g. arrows).
QCPItemRect A rectangle
QCPItemEllipse An ellipse
QCPItemPixmap An arbitrary pixmap
QCPItemText A text label
QCPItemBracket A bracket which may be used to reference/highlight certain parts in the plot.
QCPItemTracer An item that can be attached to a QCPGraph and sticks to its data points, given a key coordinate.
Clipping
Items are by default clipped to the main axis rect (they are only visible inside the axis rect). To make an item visible outside that axis rect, disable clipping via setClipToAxisRect(false).
On the other hand if you want the item to be clipped to a different axis rect, specify it via setClipAxisRect. This clipAxisRect property of an item is only used for clipping behaviour, and in principle is independent of the coordinate axes the item might be tied to via its position members (QCPItemPosition::setAxes). However, it is common that the axis rect for clipping also contains the axes used for the item positions.
Using items
First you instantiate the item you want to use and add it to the plot:
by default, the positions of the item are bound to the x- and y-Axis of the plot. So we can just set the plot coordinates where the line should start/end:
If we don't want the line to be positioned in plot coordinates but a different coordinate system, e.g. absolute pixel positions on the QCustomPlot surface, we need to change the position type like this:
Then we can set the coordinates, this time in pixels:
and make the line visible on the entire QCustomPlot, by disabling clipping to the axis rect:
 For more advanced plots, it is even possible to set different types and parent anchors per X/Y coordinate of an item position, using for example QCPItemPosition::setTypeX or QCPItemPosition::setParentAnchorX. For details, see the documentation of QCPItemPosition.
Creating own items
To create an own item, you implement a subclass of QCPAbstractItem. These are the pure virtual functions, you must implement:
selectTest
draw
See the documentation of those functions for what they need to do.
Allowing the item to be positioned
As mentioned, item positions are represented by QCPItemPosition members. Let's assume the new item shall have only one point as its position (as opposed to two like a rect or multiple like a polygon). You then add a public member of type QCPItemPosition like so:
QCPItemPosition * const myPosition;
the const makes sure the pointer itself can't be modified from the user of your new item (the QCPItemPosition instance it points to, can be modified, of course). The initialization of this pointer is made easy with the createPosition function. Just assign the return value of this function to each QCPItemPosition in the constructor of your item. createPosition takes a string which is the name of the position, typically this is identical to the variable name. For example, the constructor of QCPItemExample could look like this:
QCPItemExample::QCPItemExample(QCustomPlot *parentPlot) :
  QCPAbstractItem(parentPlot),
  myPosition(createPosition("myPosition"))
{
  // other constructor code
}
The draw function
To give your item a visual representation, reimplement the draw function and use the passed QCPPainter to draw the item. You can retrieve the item position in pixel coordinates from the position member(s) via QCPItemPosition::pixelPoint.
To optimize performance you should calculate a bounding rect first (don't forget to take the pen width into account), check whether it intersects the clipRect, and only draw the item at all if this is the case.
The selectTest function
Your implementation of the selectTest function may use the helpers distSqrToLine and rectSelectTest. With these, the implementation of the selection test becomes significantly simpler for most items. See the documentation of selectTest for what the function parameters mean and what the function should return.
Providing anchors
Providing anchors (QCPItemAnchor) starts off like adding a position. First you create a public member, e.g.
QCPItemAnchor * const bottom;
and create it in the constructor with the createAnchor function, assigning it a name and an anchor id (an integer enumerating all anchors on the item, you may create an own enum for this). Since anchors can be placed anywhere, relative to the item's position(s), your item needs to provide the position of every anchor with the reimplementation of the anchorPixelPoint(int anchorId) function.
In essence the QCPItemAnchor is merely an intermediary that itself asks your item for the pixel position when anything attached to the anchor needs to know the coordinates.
Definition at line 1607 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPAbstractItem::QCPAbstractItem (QCustomPlot * parentPlot)
Base class constructor which initializes base class members.
Definition at line 8338 of file qcustomplot.cpp.
References QCustomPlot::axisRects(), setClipAxisRect(), and setClipToAxisRect().
                                                        :
  QCPLayerable(parentPlot),
  mClipToAxisRect(false),
  mSelectable(true),
  mSelected(false)
{
  QList<QCPAxisRect*> rects = parentPlot->axisRects();
  if (rects.size() > 0)
  {
    setClipToAxisRect(true);
    setClipAxisRect(rects.first());
  }
}
QCPAbstractItem::~QCPAbstractItem () [virtual]
Definition at line 8352 of file qcustomplot.cpp.
References mAnchors.
{
  // don't delete mPositions because every position is also an anchor and thus in mAnchors
  qDeleteAll(mAnchors);
}
Member Function Documentation
QCPItemAnchor * QCPAbstractItem::anchor (const QString & name) const
Returns the QCPItemAnchor with the specified name. If this item doesn't have an anchor by that name, returns 0.
This function provides an alternative way to access item anchors. Normally, you access anchors direcly by their member pointers (which typically have the same variable name as name).
See also
anchors, position
Definition at line 8462 of file qcustomplot.cpp.
References i, and mAnchors.
{
  for (int i=0; i<mAnchors.size(); ++i)
  {
    if (mAnchors.at(i)->name() == name)
      return mAnchors.at(i);
  }
  qDebug() << Q_FUNC_INFO << "anchor with name not found:" << name;
  return 0;
}
QPointF QCPAbstractItem::anchorPixelPoint (int anchorId) const [protected], [virtual]
Reimplemented in QCPItemBracket, QCPItemPixmap, QCPItemEllipse, QCPItemText, and QCPItemRect.
Definition at line 8610 of file qcustomplot.cpp.
Referenced by QCPItemAnchor::pixelPoint().
{
  qDebug() << Q_FUNC_INFO << "called on item which shouldn't have any anchors (this method not
       reimplemented). anchorId" << anchorId;
  return QPointF();
}
QList< QCPItemAnchor * > QCPAbstractItem::anchors () const [inline]
Returns all anchors of the item in a list. Note that since a position (QCPItemPosition) is always also an anchor, the list will also contain the positions of this item.
See also
positions, anchor
Definition at line 1637 of file qcustomplot.h.
{ return mAnchors; }
void QCPAbstractItem::applyDefaultAntialiasingHint (QCPPainter * painter) const [protected], [virtual]
Implements QCPLayerable.
Definition at line 8521 of file qcustomplot.cpp.
References QCP::aeItems, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
{
  applyAntialiasingHint(painter, mAntialiased,
      QCP::aeItems);
}
QCPAxisRect * QCPAbstractItem::clipAxisRect () const
Definition at line 8359 of file qcustomplot.cpp.
References mClipAxisRect.
{
  return mClipAxisRect.data();
}
QRect QCPAbstractItem::clipRect () const [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 8500 of file qcustomplot.cpp.
References mClipAxisRect, mClipToAxisRect, QCPLayerable::mParentPlot, and QCustomPlot::viewport().
Referenced by QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemCurve::draw(), QCPItemRect::draw(), QCPItemText::draw(), QCPItemEllipse::draw(), QCPItemPixmap::draw(), QCPItemTracer::draw(), QCPItemBracket::draw(), QCustomPlot::itemAt(), and QCPItemTracer::selectTest().
{
  if (mClipToAxisRect && mClipAxisRect)
    return mClipAxisRect.data()->rect();
  else
    return mParentPlot->viewport();
}
bool QCPAbstractItem::clipToAxisRect () const [inline]
Definition at line 1621 of file qcustomplot.h.
Referenced by QCustomPlot::itemAt().
{ return mClipToAxisRect; }
QCPItemAnchor * QCPAbstractItem::createAnchor (const QString & name, int anchorId) [protected]
Definition at line 8664 of file qcustomplot.cpp.
References hasAnchor(), mAnchors, QCPLayerable::mParentPlot, and QCPItemAnchor.
{
  if (hasAnchor(name))
    qDebug() << Q_FUNC_INFO << "anchor/position with name exists already:" << name;
  QCPItemAnchor *newAnchor = new QCPItemAnchor(
      mParentPlot, this, name, anchorId);
  mAnchors.append(newAnchor);
  return newAnchor;
}
QCPItemPosition * QCPAbstractItem::createPosition (const QString & name) [protected]
Definition at line 8630 of file qcustomplot.cpp.
References QCustomPlot::axisRect(), hasAnchor(), mAnchors, QCPLayerable::mParentPlot, mPositions, QCPItemPosition::ptPlotCoords, QCPItemPosition::setAxes(), QCPItemPosition::setAxisRect(), QCPItemPosition::setCoords(), QCPItemPosition::setType(), QCustomPlot::xAxis, and QCustomPlot::yAxis.
{
  if (hasAnchor(name))
    qDebug() << Q_FUNC_INFO << "anchor/position with name exists already:" << name;
  QCPItemPosition *newPosition = new QCPItemPosition(
      mParentPlot, this, name);
  mPositions.append(newPosition);
  mAnchors.append(newPosition); // every position is also an anchor
  newPosition->setAxes(mParentPlot->xAxis, mParentPlot->
      yAxis);
  newPosition->setType(QCPItemPosition::ptPlotCoords);
  if (mParentPlot->axisRect())
    newPosition->setAxisRect(mParentPlot->axisRect());
  newPosition->setCoords(0, 0);
  return newPosition;
}
void QCPAbstractItem::deselectEvent (bool * selectionStateChanged) [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 8688 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
{
  if (mSelectable)
  {
    bool selBefore = mSelected;
    setSelected(false);
    if (selectionStateChanged)
      *selectionStateChanged = mSelected != selBefore;
  }
}
double QCPAbstractItem::distSqrToLine (const QPointF & start, const QPointF & end, const QPointF & point) const [protected]
Definition at line 8538 of file qcustomplot.cpp.
Referenced by rectSelectTest(), QCPItemLine::selectTest(), QCPItemCurve::selectTest(), QCPItemTracer::selectTest(), and QCPItemBracket::selectTest().
{
  QVector2D a(start);
  QVector2D b(end);
  QVector2D p(point);
  QVector2D v(b-a);
  
  double vLengthSqr = v.lengthSquared();
  if (!qFuzzyIsNull(vLengthSqr))
  {
    double mu = QVector2D::dotProduct(p-a, v)/vLengthSqr;
    if (mu < 0)
      return (a-p).lengthSquared();
    else if (mu > 1)
      return (b-p).lengthSquared();
    else
      return ((a + mu*v)-p).lengthSquared();
  } else
    return (a-p).lengthSquared();
}
void QCPAbstractItem::draw (QCPPainter * painter) [protected], [pure virtual]
Implements QCPLayerable.
Implemented in QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, and QCPItemStraightLine.
bool QCPAbstractItem::hasAnchor (const QString & name) const
Returns whether this item has an anchor with the specified name.
Note that you can check for positions with this function, too. This is because every position is also an anchor (QCPItemPosition inherits from QCPItemAnchor).
See also
anchor, position
Definition at line 8481 of file qcustomplot.cpp.
References i, and mAnchors.
Referenced by createAnchor(), and createPosition().
{
  for (int i=0; i<mAnchors.size(); ++i)
  {
    if (mAnchors.at(i)->name() == name)
      return true;
  }
  return false;
}
QCPItemPosition * QCPAbstractItem::position (const QString & name) const
Returns the QCPItemPosition with the specified name. If this item doesn't have a position by that name, returns 0.
This function provides an alternative way to access item positions. Normally, you access positions direcly by their member pointers (which typically have the same variable name as name).
See also
positions, anchor
Definition at line 8441 of file qcustomplot.cpp.
References i, and mPositions.
{
  for (int i=0; i<mPositions.size(); ++i)
  {
    if (mPositions.at(i)->name() == name)
      return mPositions.at(i);
  }
  qDebug() << Q_FUNC_INFO << "position with name not found:" << name;
  return 0;
}
QList< QCPItemPosition * > QCPAbstractItem::positions () const [inline]
Returns all positions of the item in a list.
See also
anchors, position
Definition at line 1636 of file qcustomplot.h.
{ return mPositions; }
double QCPAbstractItem::rectSelectTest (const QRectF & rect, const QPointF & pos, bool filledRect) const [protected]
Definition at line 8574 of file qcustomplot.cpp.
References distSqrToLine(), i, QCPLayerable::mParentPlot, and QCustomPlot::selectionTolerance().
Referenced by QCPItemRect::selectTest(), QCPItemText::selectTest(), QCPItemPixmap::selectTest(), and QCPItemTracer::selectTest().
{
  double result = -1;
  // distance to border:
  QList<QLineF> lines;
  lines << QLineF(rect.topLeft(), rect.topRight()) << QLineF(rect.bottomLeft(),
      rect.bottomRight())
        << QLineF(rect.topLeft(), rect.bottomLeft()) << QLineF(rect.topRight(),
      rect.bottomRight());
  double minDistSqr = std::numeric_limits<double>::max();
  for (int i=0; i<lines.size(); ++i)
  {
    double distSqr = distSqrToLine(lines.at(i).p1(), lines.at(i).p2(), pos);
    if (distSqr < minDistSqr)
      minDistSqr = distSqr;
  }
  result = qSqrt(minDistSqr);
  
  // filled rect, allow click inside to count as hit:
  if (filledRect && result > mParentPlot->selectionTolerance()*0.99)
  {
    if (rect.contains(pos))
      result = mParentPlot->selectionTolerance()*0.99;
  }
  return result;
}
bool QCPAbstractItem::selectable () const [inline]
Definition at line 1623 of file qcustomplot.h.
Referenced by QCustomPlot::itemAt(), and setSelectable().
{ return mSelectable; }
void QCPAbstractItem::selectableChanged (bool selectable) [signal]
Referenced by setSelectable().
bool QCPAbstractItem::selected () const [inline]
Definition at line 1624 of file qcustomplot.h.
Referenced by QCustomPlot::selectedItems(), and setSelected().
{ return mSelected; }
void QCPAbstractItem::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 8674 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
{
  Q_UNUSED(event)
  Q_UNUSED(details)
  if (mSelectable)
  {
    bool selBefore = mSelected;
    setSelected(additive ? !mSelected : true);
    if (selectionStateChanged)
      *selectionStateChanged = mSelected != selBefore;
  }
}
QCP::Interaction QCPAbstractItem::selectionCategory () const [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 8700 of file qcustomplot.cpp.
References QCP::iSelectItems.
{
  return QCP::iSelectItems;
}
void QCPAbstractItem::selectionChanged (bool selected) [signal]
This signal is emitted when the selection state of this item has changed, either by user interaction or by a direct call to setSelected.
Referenced by setSelected().
virtual double QCPAbstractItem::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [pure virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Reimplemented from QCPLayerable.
Implemented in QCPItemBracket, QCPItemTracer, QCPItemPixmap, QCPItemEllipse, QCPItemText, QCPItemRect, QCPItemCurve, QCPItemLine, and QCPItemStraightLine.
Referenced by QCustomPlot::itemAt().
void QCPAbstractItem::setClipAxisRect (QCPAxisRect * rect)
Sets the clip axis rect. It defines the rect that will be used to clip the item when setClipToAxisRect is set to true.
See also
setClipToAxisRect
Definition at line 8383 of file qcustomplot.cpp.
References mClipAxisRect, mClipToAxisRect, rect, and QCPLayerable::setParentLayerable().
Referenced by QCPAbstractItem().
{
  mClipAxisRect = rect;
  if (mClipToAxisRect)
    setParentLayerable(mClipAxisRect.data());
}
void QCPAbstractItem::setClipToAxisRect (bool clip)
Sets whether the item shall be clipped to an axis rect or whether it shall be visible on the entire QCustomPlot. The axis rect can be set with setClipAxisRect.
See also
setClipAxisRect
Definition at line 8370 of file qcustomplot.cpp.
References mClipAxisRect, mClipToAxisRect, and QCPLayerable::setParentLayerable().
Referenced by QCPAbstractItem().
{
  mClipToAxisRect = clip;
  if (mClipToAxisRect)
    setParentLayerable(mClipAxisRect.data());
}
void QCPAbstractItem::setSelectable (bool selectable)
Sets whether the user can (de-)select this item by clicking on the QCustomPlot surface. (When QCustomPlot::setInteractions contains QCustomPlot::iSelectItems.)
However, even when selectable was set to false, it is possible to set the selection manually, by calling setSelected.
See also
QCustomPlot::setInteractions, setSelected
Definition at line 8399 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
{
  if (mSelectable != selectable)
  {
    mSelectable = selectable;
    emit selectableChanged(mSelectable);
  }
}
void QCPAbstractItem::setSelected (bool selected)
Sets whether this item is selected or not. When selected, it might use a different visual appearance (e.g. pen and brush), this depends on the specific item though.
The entire selection mechanism for items is handled automatically when QCustomPlot::setInteractions contains QCustomPlot::iSelectItems. You only need to call this function when you wish to change the selection state manually.
This function can change the selection state even when setSelectable was set to false.
emits the selectionChanged signal when selected is different from the previous selection state.
See also
setSelectable, selectTest
Definition at line 8422 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), and selectEvent().
{
  if (mSelected != selected)
  {
    mSelected = selected;
    emit selectionChanged(mSelected);
  }
}
Friends And Related Function Documentation
friend class QCPItemAnchor [friend]
Definition at line 1676 of file qcustomplot.h.
Referenced by createAnchor().
friend class QCustomPlot [friend]
Definition at line 1675 of file qcustomplot.h.
Member Data Documentation
QList<QCPItemAnchor*> QCPAbstractItem::mAnchors [protected]
Definition at line 1651 of file qcustomplot.h.
Referenced by anchor(), createAnchor(), createPosition(), hasAnchor(), and ~QCPAbstractItem().
QPointer<QCPAxisRect> QCPAbstractItem::mClipAxisRect [protected]
Definition at line 1649 of file qcustomplot.h.
Referenced by clipAxisRect(), clipRect(), setClipAxisRect(), and setClipToAxisRect().
bool QCPAbstractItem::mClipToAxisRect [protected]
Definition at line 1648 of file qcustomplot.h.
Referenced by clipRect(), setClipAxisRect(), and setClipToAxisRect().
QList<QCPItemPosition*> QCPAbstractItem::mPositions [protected]
Definition at line 1650 of file qcustomplot.h.
Referenced by createPosition(), and position().
bool QCPAbstractItem::mSelectable [protected]
Definition at line 1652 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), QCPItemStraightLine::selectTest(), QCPItemLine::selectTest(), QCPItemCurve::selectTest(), QCPItemRect::selectTest(), QCPItemText::selectTest(), QCPItemEllipse::selectTest(), QCPItemPixmap::selectTest(), QCPItemTracer::selectTest(), QCPItemBracket::selectTest(), and setSelectable().
bool QCPAbstractItem::mSelected [protected]
Definition at line 1652 of file qcustomplot.h.
Referenced by deselectEvent(), QCPItemRect::mainBrush(), QCPItemText::mainBrush(), QCPItemEllipse::mainBrush(), QCPItemTracer::mainBrush(), QCPItemText::mainColor(), QCPItemText::mainFont(), QCPItemStraightLine::mainPen(), QCPItemLine::mainPen(), QCPItemCurve::mainPen(), QCPItemRect::mainPen(), QCPItemText::mainPen(), QCPItemEllipse::mainPen(), QCPItemPixmap::mainPen(), QCPItemTracer::mainPen(), QCPItemBracket::mainPen(), selectEvent(), and setSelected().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp