Hardware::PWM Class Reference
#include <PWM.h>
Public Types
enum Pin { P8_13,
P8_19,
P9_14,
P9_16
 }
enum Run { On = 1,
Off = 0
 }
enum Polarity { Normal = 1,
Inverted = 0
 }
Public Member Functions
uint8_t GetPixelValue ()
void SetPixelValue (uint8_t value)
Set the output as a corresponding uint8_t value
float GetIntensity ()
void SetIntensity (float value)
Set the intensity level as percentage
int GetPeriod ()
void SetPeriod (int value)
Set the period of the signal
int GetDuty ()
void SetDuty (int value)
Set the duty of the signal
void SetIntensity ()
Run GetRun ()
void SetRun (Run value)
Run the signal
Polarity GetPolarity ()
void SetPolarity (Polarity value)
Set the polarity
PWM (Pin pin)
Constructeur
~PWM ()
Public Attributes
Pin pin
Private Member Functions
void calcIntensity ()
Calculate the current intensity
string FindPath (string value)
Find the current PWM path in the OCP.3 directory
Private Attributes
int period
int duty
float intensity
uint8_t pixelvalue
Run run
Polarity polarity
string basepath
string dutypath
string periodpath
string runpath
string polaritypath
Additional Inherited Members
Detailed Description
Definition at line 30 of file PWM.h.
Member Enumeration Documentation
enum Hardware::PWM::Pin
Enumerator
P8_13
P8_19
P9_14
P9_16
Definition at line 32 of file PWM.h.
  { P8_13,
    P8_19,
    P9_14,
    P9_16 };
enum Hardware::PWM::Polarity
Enumerator
Normal
Inverted
Definition at line 40 of file PWM.h.
  { Normal = 1,
    Inverted = 0 };
enum Hardware::PWM::Run
Enumerator
On
Off
Definition at line 37 of file PWM.h.
  { On = 1,
    Off = 0 };
Constructor & Destructor Documentation
Hardware::PWM::PWM (Pin pin)
Constructeur
Parameters
pin Pin
Definition at line 15 of file PWM.cpp.
References basepath, calcIntensity(), Hardware::BBB::CapeLoaded(), duty, dutypath, FindPath(), OCP_PATH, P8_13, P8_13_CAPE, P8_13_CAPE_LOAD, P8_13_FIND, P8_19, P8_19_CAPE, P8_19_CAPE_LOAD, P8_19_FIND, P9_14, P9_14_CAPE, P9_14_CAPE_LOAD, P9_14_FIND, P9_16, P9_16_CAPE, P9_16_CAPE_LOAD, P9_16_FIND, period, periodpath, pin, polarity, polaritypath, PWM_CAPE, Hardware::BBB::Read(), run, runpath, SLOTS, and Hardware::BBB::Write().
                {
  this->pin = pin;
  // Check if PWM cape is loaded, if not load it
  if (!CapeLoaded(PWM_CAPE)) {
    Write(SLOTS, PWM_CAPE);
  }
  // Init the pin
  basepath = OCP_PATH;
  switch (pin) {
  case Hardware::PWM::P8_13:
    if (!CapeLoaded(P8_13_CAPE)) {
      Write(SLOTS, P8_13_CAPE_LOAD);
    }
    basepath.append(FindPath(P8_13_FIND));
    break;
  case Hardware::PWM::P8_19:
    if (!CapeLoaded(P8_19_CAPE)) {
      Write(SLOTS, P8_19_CAPE_LOAD);
    }
    basepath.append(FindPath(P8_19_FIND));
    break;
  case Hardware::PWM::P9_14:
    if (!CapeLoaded(P9_14_CAPE)) {
      Write(SLOTS, P9_14_CAPE_LOAD);
    }
    basepath.append(FindPath(P9_14_FIND));
    break;
  case Hardware::PWM::P9_16:
    if (!CapeLoaded(P9_16_CAPE)) {
      Write(SLOTS, P9_16_CAPE_LOAD);
    }
    basepath.append(FindPath(P9_16_FIND));
    break;
  }
  // Get the working paths
  dutypath = basepath + "/duty";
  periodpath = basepath + "/period";
  runpath = basepath + "/run";
  polaritypath = basepath + "/polarity";
  // Give Linux time to setup directory structure;
  usleep(250000);
  // Read current values
  period = StringToNumber<int>(Read(periodpath));
  duty = StringToNumber<int>(Read(dutypath));
  run = static_cast<Run>(StringToNumber<int>(Read(runpath)));
  polarity = static_cast<Polarity>(StringToNumber<int>(Read(
      polaritypath)));
  // calculate the current intensity
  calcIntensity();
}
Hardware::PWM::~PWM ()
Definition at line 71 of file PWM.cpp.
{}
Member Function Documentation
void Hardware::PWM::calcIntensity () [private]
Calculate the current intensity
Definition at line 76 of file PWM.cpp.
References duty, intensity, Normal, period, and polarity.
Referenced by PWM(), SetDuty(), and SetPeriod().
                        {
  if (polarity == Normal) {
    if (duty == 0) {
      intensity = 0.0f;
    } else {
      intensity = (float)period / (float)duty;
    }
  } else {
    if (period == 0) {
      intensity = 0.0f;
    } else {
      intensity = (float)duty / (float)period;
    }
  }
}
string Hardware::PWM::FindPath (string value) [private]
Find the current PWM path in the OCP.3 directory
Parameters
value part a the path name
Returns
Returns the first found value
Definition at line 167 of file PWM.cpp.
References OCP_PATH.
Referenced by PWM().
                                 {
  auto dir = opendir(OCP_PATH);
  auto entity = readdir(dir);
  while (entity != NULL) {
    if (entity->d_type == DT_DIR) {
      string str = static_cast<string>(entity->d_name);
      if (str.find(value) != string::npos) {
        return str;
      }
    }
    entity = readdir(dir);
  }
  return "";
}
int Hardware::PWM::GetDuty () [inline]
Definition at line 55 of file PWM.h.
References duty.
{ return duty; };
float Hardware::PWM::GetIntensity () [inline]
Definition at line 49 of file PWM.h.
References intensity.
{ return intensity; };
int Hardware::PWM::GetPeriod () [inline]
Definition at line 52 of file PWM.h.
References period.
{ return period; };
uint8_t Hardware::PWM::GetPixelValue () [inline]
Definition at line 46 of file PWM.h.
References pixelvalue.
{ return pixelvalue; }
Polarity Hardware::PWM::GetPolarity () [inline]
Definition at line 62 of file PWM.h.
References polarity.
{ return polarity; };
Run Hardware::PWM::GetRun () [inline]
Definition at line 59 of file PWM.h.
References run.
{ return run; };
void Hardware::PWM::SetDuty (int value)
Set the duty of the signal
Parameters
value duty : int
Definition at line 132 of file PWM.cpp.
References calcIntensity(), duty, dutypath, and Hardware::BBB::Write().
Referenced by SetIntensity(), and SetPixelValue().
                           {
  string valstr = NumberToString<int>(value);
  Write(dutypath, valstr);
  duty = value;
  calcIntensity();
}
void Hardware::PWM::SetIntensity (float value)
Set the intensity level as percentage
Parameters
value floating value multipication factor
Definition at line 96 of file PWM.cpp.
References duty, Normal, period, polarity, SetDuty(), and SetPeriod().
                                  {
  if (polarity == Normal) {
    SetDuty(static_cast<int>((value * duty) + 0.5));
  } else {
    SetPeriod(static_cast<int>((value * period) + 0.5));
  }
}
void Hardware::PWM::SetIntensity ()
void Hardware::PWM::SetPeriod (int value)
Set the period of the signal
Parameters
value period : int
Definition at line 120 of file PWM.cpp.
References calcIntensity(), period, periodpath, and Hardware::BBB::Write().
Referenced by SetIntensity(), and SetPixelValue().
                             {
  string valstr = NumberToString<int>(value);
  Write(periodpath, valstr);
  period = value;
  calcIntensity();
}
void Hardware::PWM::SetPixelValue (uint8_t value)
Set the output as a corresponding uint8_t value
Parameters
value pixel value 0-255
Definition at line 108 of file PWM.cpp.
References period, pixelvalue, SetDuty(), and SetPeriod().
                                     {
  if (period != 255) {
    SetPeriod(255);
  }
  SetDuty(255 - value);
  pixelvalue = value;
}
void Hardware::PWM::SetPolarity (Polarity value)
Set the polarity
Parameters
value Normal or Inverted signal
Definition at line 155 of file PWM.cpp.
References polarity, runpath, and Hardware::BBB::Write().
                                    {
  int valInt = static_cast<int>(value);
  string valstr = NumberToString<int>(valInt);
  Write(runpath, valstr);
  polarity = value;
}
void Hardware::PWM::SetRun (Run value)
Run the signal
Parameters
value On or Off
Definition at line 144 of file PWM.cpp.
References run, runpath, and Hardware::BBB::Write().
                          {
  int valInt = static_cast<int>(value);
  string valstr = NumberToString<int>(valInt);
  Write(runpath, valstr);
  run = value;
}
Member Data Documentation
string Hardware::PWM::basepath [private]
Definition at line 76 of file PWM.h.
Referenced by PWM().
int Hardware::PWM::duty [private]
Definition at line 70 of file PWM.h.
Referenced by calcIntensity(), GetDuty(), PWM(), SetDuty(), and SetIntensity().
string Hardware::PWM::dutypath [private]
Definition at line 77 of file PWM.h.
Referenced by PWM(), and SetDuty().
float Hardware::PWM::intensity [private]
Definition at line 71 of file PWM.h.
Referenced by calcIntensity(), and GetIntensity().
int Hardware::PWM::period [private]
Definition at line 69 of file PWM.h.
Referenced by calcIntensity(), GetPeriod(), PWM(), SetIntensity(), SetPeriod(), and SetPixelValue().
string Hardware::PWM::periodpath [private]
Definition at line 78 of file PWM.h.
Referenced by PWM(), and SetPeriod().
Pin Hardware::PWM::pin
Definition at line 44 of file PWM.h.
Referenced by PWM().
uint8_t Hardware::PWM::pixelvalue [private]
Definition at line 72 of file PWM.h.
Referenced by GetPixelValue(), and SetPixelValue().
Polarity Hardware::PWM::polarity [private]
Definition at line 74 of file PWM.h.
Referenced by calcIntensity(), GetPolarity(), PWM(), SetIntensity(), and SetPolarity().
string Hardware::PWM::polaritypath [private]
Definition at line 80 of file PWM.h.
Referenced by PWM().
Run Hardware::PWM::run [private]
Definition at line 73 of file PWM.h.
Referenced by GetRun(), PWM(), and SetRun().
string Hardware::PWM::runpath [private]
Definition at line 79 of file PWM.h.
Referenced by PWM(), SetPolarity(), and SetRun().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/PWM.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/PWM.cpp