QCPColorGradient Class Reference
Defines a color gradient for use with e.g. QCPColorMap.
#include <qcustomplot.h>
Public Types
enum ColorInterpolation { ciRGB,
ciHSV
 }
enum GradientPreset {
*
gpGrayscale,
gpHot,
gpCold,
gpNight,
*
gpCandy,
gpGeography,
gpIon,
gpThermal,
*
gpPolar,
gpSpectrum,
gpJet,
gpHues
 }
Public Member Functions
QCPColorGradient (GradientPreset preset=gpCold)
bool operator== (const QCPColorGradient &other) const
bool operator!= (const QCPColorGradient &other) const
int levelCount () const
QMap< double, QColor > colorStops () const
ColorInterpolation colorInterpolation () const
bool periodic () const
void setLevelCount (int n)
void setColorStops (const QMap< double, QColor > &colorStops)
void setColorStopAt (double position, const QColor &color)
void setColorInterpolation (ColorInterpolation interpolation)
void setPeriodic (bool enabled)
void colorize (const double *data, const QCPRange &range, QRgb *scanLine, int n, int dataIndexFactor=1, bool logarithmic=false)
QRgb color (double position, const QCPRange &range, bool logarithmic=false)
void loadPreset (GradientPreset preset)
void clearColorStops ()
QCPColorGradient inverted () const
Protected Member Functions
void updateColorBuffer ()
Protected Attributes
int mLevelCount
QMap< double, QColor > mColorStops
ColorInterpolation mColorInterpolation
bool mPeriodic
QVector< QRgb > mColorBuffer
bool mColorBufferInvalidated
Detailed Description
Defines a color gradient for use with e.g. QCPColorMap.
This class describes a color gradient which can be used to encode data with color. For example, QCPColorMap and QCPColorScale have setGradient methods which take an instance of this class. Colors are set with setColorStopAt(double position, const QColor &color) with a position from 0 to 1. In between these defined color positions, the color will be interpolated linearly either in RGB or HSV space, see setColorInterpolation.
Alternatively, load one of the preset color gradients shown in the image below, with loadPreset, or by directly specifying the preset in the constructor.
The fact that the ructor allows directly converting a GradientPreset to a QCPColorGradient, you can also directly pass GradientPreset to all the setGradient methods, e.g.:
qcpcolorgradient-setgradient
The total number of levels used in the gradient can be set with setLevelCount. Whether the color gradient shall be applied periodically (wrapping around) to data values that lie outside the data range specified on the plottable instance can be controlled with setPeriodic.
Definition at line 2189 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPColorGradient::ColorInterpolation
Defines the color spaces in which color interpolation between gradient stops can be performed.
See also
setColorInterpolation
Enumerator
ciRGB
 Color channels red, green and blue are linearly interpolated.
ciHSV
 Color channels hue, saturation and value are linearly interpolated (The hue is interpolated over the shortest angle distance)
Definition at line 2198 of file qcustomplot.h.
                          {
    ciRGB
    ,
    ciHSV
  };
enum QCPColorGradient::GradientPreset
Defines the available presets that can be loaded with loadPreset. See the documentation there for an image of the presets.
Enumerator
gpGrayscale
 Continuous lightness from black to white (suited for non-biased data representation)
gpHot
 Continuous lightness from black over firey colors to white (suited for non-biased data representation)
gpCold
 Continuous lightness from black over icey colors to white (suited for non-biased data representation)
gpNight
 Continuous lightness from black over weak blueish colors to white (suited for non-biased data representation)
gpCandy
 Blue over pink to white.
gpGeography
 Colors suitable to represent different elevations on geographical maps
gpIon
 Half hue spectrum from black over purple to blue and finally green (creates banding illusion but allows more precise magnitude estimates)
gpThermal
 Colors suitable for thermal imaging, ranging from dark blue over purple to orange, yellow and white
gpPolar
 Colors suitable to emphasize polarity around the center, with blue for negative, black in the middle and red for positive values
gpSpectrum
 An approximation of the visible light spectrum (creates banding illusion but allows more precise magnitude estimates)
gpJet
 Hue variation similar to a spectrum, often used in numerical visualization (creates banding illusion but allows more precise magnitude estimates)
gpHues
 Full hue cycle, with highest and lowest color red (suitable for periodic data, such as angles and phases, see setPeriodic)
Definition at line 2212 of file qcustomplot.h.
                      {
    gpGrayscale
    ,
    gpHot
    ,
    gpCold
    ,
    gpNight
    ,
    gpCandy
    ,
    gpGeography
    ,
    gpIon
    ,
    gpThermal
    ,
    gpPolar
    ,
    gpSpectrum
    ,
    gpJet
    ,
    gpHues
  };
Constructor & Destructor Documentation
QCPColorGradient::QCPColorGradient (GradientPreset preset = gpCold)
Constructs a new QCPColorGradient initialized with the colors and color interpolation according to preset.
The color level count is initialized to 350.
Definition at line 12352 of file qcustomplot.cpp.
References loadPreset(), mColorBuffer, and mLevelCount.
    : mLevelCount(350), mColorInterpolation(ciRGB),
      mPeriodic(false),
      mColorBufferInvalidated(true) {
  mColorBuffer.fill(qRgb(0, 0, 0), mLevelCount);
  loadPreset(preset);
}
Member Function Documentation
void QCPColorGradient::clearColorStops ()
Clears all color stops.
See also
setColorStops, setColorStopAt
Definition at line 12689 of file qcustomplot.cpp.
References mColorBufferInvalidated, and mColorStops.
Referenced by inverted(), and loadPreset().
                                       {
  mColorStops.clear();
  mColorBufferInvalidated = true;
}
QRgb QCPColorGradient::color (double position, const QCPRange & range, bool logarithmic = false)
Definition at line 12550 of file qcustomplot.cpp.
References QCPRange::lower, mColorBuffer, mColorBufferInvalidated, mLevelCount, mPeriodic, QCPRange::size(), updateColorBuffer(), and QCPRange::upper.
Referenced by QCPColorScaleAxisRectPrivate::updateGradientImage().
                                               {
  // If you change something here, make sure to also adapt ::colorize()
  if (mColorBufferInvalidated)
    updateColorBuffer();
  int index = 0;
  if (!logarithmic)
    index = (position - range.lower) * (mLevelCount - 1) / range.
      size();
  else
    index = qLn(position / range.lower) / qLn(range.upper / range.
      lower) *
            (mLevelCount - 1);
  if (mPeriodic) {
    index = index % mLevelCount;
    if (index < 0)
      index += mLevelCount;
  } else {
    if (index < 0)
      index = 0;
    else if (index >= mLevelCount)
      index = mLevelCount - 1;
  }
  return mColorBuffer.at(index);
}
ColorInterpolation QCPColorGradient::colorInterpolation () const [inline]
Definition at line 2262 of file qcustomplot.h.
{ return mColorInterpolation; }
void QCPColorGradient::colorize (const double * data, const QCPRange & range, QRgb * scanLine, int n, int dataIndexFactor = 1, bool logarithmic = false)
This method is used to quickly convert a data array to colors. The colors will be output in the array scanLine. Both data and scanLine must have the length n when passed to this function. The data range that shall be used for mapping the data value to the gradient is passed in range. logarithmic indicates whether the data values shall be mapped to colors logarithmically.
if data actually contains 2D-data linearized via [row*columnCount + column], you can set dataIndexFactor to columnCount to convert a column instead of a row of the data array, in scanLine. scanLine will remain a regular (1D) array. This works because data is addressed data[i*dataIndexFactor].
Definition at line 12475 of file qcustomplot.cpp.
References i, QCPRange::lower, mColorBuffer, mColorBufferInvalidated, mLevelCount, mPeriodic, n, QCPRange::size(), updateColorBuffer(), and QCPRange::upper.
Referenced by QCPColorScaleAxisRectPrivate::updateGradientImage(), and QCPColorMap::updateMapImage().
                                                  {
  // If you change something here, make sure to also adapt ::color()
  if (!data) {
    qDebug() << Q_FUNC_INFO << "null pointer given as data";
    return;
  }
  if (!scanLine) {
    qDebug() << Q_FUNC_INFO << "null pointer given as scanLine";
    return;
  }
  if (mColorBufferInvalidated)
    updateColorBuffer();
  if (!logarithmic) {
    const double posToIndexFactor = (mLevelCount - 1) / range.size();
    if (mPeriodic) {
      for (int i = 0; i < n; ++i) {
        int index = (int)((data[dataIndexFactor * i] - range.lower) *
                          posToIndexFactor) %
                    mLevelCount;
        if (index < 0)
          index += mLevelCount;
        scanLine[i] = mColorBuffer.at(index);
      }
    } else {
      for (int i = 0; i < n; ++i) {
        int index =
            (data[dataIndexFactor * i] - range.lower) * posToIndexFactor;
        if (index < 0)
          index = 0;
        else if (index >= mLevelCount)
          index = mLevelCount - 1;
        scanLine[i] = mColorBuffer.at(index);
      }
    }
  } else // logarithmic == true
  {
    if (mPeriodic) {
      for (int i = 0; i < n; ++i) {
        int index = (int)(qLn(data[dataIndexFactor * i] / range.lower) /
                          qLn(range.upper / range.lower) * (
      mLevelCount - 1)) %
                    mLevelCount;
        if (index < 0)
          index += mLevelCount;
        scanLine[i] = mColorBuffer.at(index);
      }
    } else {
      for (int i = 0; i < n; ++i) {
        int index = qLn(data[dataIndexFactor * i] / range.lower) /
                    qLn(range.upper / range.lower) * (mLevelCount - 1);
        if (index < 0)
          index = 0;
        else if (index >= mLevelCount)
          index = mLevelCount - 1;
        scanLine[i] = mColorBuffer.at(index);
      }
    }
  }
}
QMap<double, QColor> QCPColorGradient::colorStops () const [inline]
Definition at line 2261 of file qcustomplot.h.
Referenced by setColorStops().
{ return mColorStops; }
QCPColorGradient QCPColorGradient::inverted () const
Returns an inverted gradient. The inverted gradient has all properties as this QCPColorGradient, but the order of the color stops is inverted.
See also
setColorStops, setColorStopAt
Definition at line 12701 of file qcustomplot.cpp.
References clearColorStops(), mColorStops, and setColorStopAt().
                                                  {
  QCPColorGradient result(*this);
  result.clearColorStops();
  for (QMap<double, QColor>::const_iterator it = mColorStops.constBegin();
       it != mColorStops.constEnd(); ++it)
    result.setColorStopAt(1.0 - it.key(), it.value());
  return result;
}
int QCPColorGradient::levelCount () const [inline]
Definition at line 2260 of file qcustomplot.h.
Referenced by QCPColorScaleAxisRectPrivate::updateGradientImage().
{ return mLevelCount; }
void QCPColorGradient::loadPreset (GradientPreset preset)
Clears the current color stops and loads the specified preset. A preset consists of predefined color stops and the corresponding color interpolation method.
The available presets are:
Definition at line 12582 of file qcustomplot.cpp.
References ciHSV, ciRGB, clearColorStops(), gpCandy, gpCold, gpGeography, gpGrayscale, gpHot, gpHues, gpIon, gpJet, gpNight, gpPolar, gpSpectrum, gpThermal, setColorInterpolation(), and setColorStopAt().
Referenced by QCPColorGradient().
                                                       {
  clearColorStops();
  switch (preset) {
  case gpGrayscale:
    setColorInterpolation(ciRGB);
    setColorStopAt(0, Qt::black);
    setColorStopAt(1, Qt::white);
    break;
  case gpHot:
    setColorInterpolation(ciRGB);
    setColorStopAt(0, QColor(50, 0, 0));
    setColorStopAt(0.2, QColor(180, 10, 0));
    setColorStopAt(0.4, QColor(245, 50, 0));
    setColorStopAt(0.6, QColor(255, 150, 10));
    setColorStopAt(0.8, QColor(255, 255, 50));
    setColorStopAt(1, QColor(255, 255, 255));
    break;
  case gpCold:
    setColorInterpolation(ciRGB);
    setColorStopAt(0, QColor(0, 0, 50));
    setColorStopAt(0.2, QColor(0, 10, 180));
    setColorStopAt(0.4, QColor(0, 50, 245));
    setColorStopAt(0.6, QColor(10, 150, 255));
    setColorStopAt(0.8, QColor(50, 255, 255));
    setColorStopAt(1, QColor(255, 255, 255));
    break;
  case gpNight:
    setColorInterpolation(ciHSV);
    setColorStopAt(0, QColor(10, 20, 30));
    setColorStopAt(1, QColor(250, 255, 250));
    break;
  case gpCandy:
    setColorInterpolation(ciHSV);
    setColorStopAt(0, QColor(0, 0, 255));
    setColorStopAt(1, QColor(255, 250, 250));
    break;
  case gpGeography:
    setColorInterpolation(ciRGB);
    setColorStopAt(0, QColor(70, 170, 210));
    setColorStopAt(0.20, QColor(90, 160, 180));
    setColorStopAt(0.25, QColor(45, 130, 175));
    setColorStopAt(0.30, QColor(100, 140, 125));
    setColorStopAt(0.5, QColor(100, 140, 100));
    setColorStopAt(0.6, QColor(130, 145, 120));
    setColorStopAt(0.7, QColor(140, 130, 120));
    setColorStopAt(0.9, QColor(180, 190, 190));
    setColorStopAt(1, QColor(210, 210, 230));
    break;
  case gpIon:
    setColorInterpolation(ciHSV);
    setColorStopAt(0, QColor(50, 10, 10));
    setColorStopAt(0.45, QColor(0, 0, 255));
    setColorStopAt(0.8, QColor(0, 255, 255));
    setColorStopAt(1, QColor(0, 255, 0));
    break;
  case gpThermal:
    setColorInterpolation(ciRGB);
    setColorStopAt(0, QColor(0, 0, 50));
    setColorStopAt(0.15, QColor(20, 0, 120));
    setColorStopAt(0.33, QColor(200, 30, 140));
    setColorStopAt(0.6, QColor(255, 100, 0));
    setColorStopAt(0.85, QColor(255, 255, 40));
    setColorStopAt(1, QColor(255, 255, 255));
    break;
  case gpPolar:
    setColorInterpolation(ciRGB);
    setColorStopAt(0, QColor(50, 255, 255));
    setColorStopAt(0.18, QColor(10, 70, 255));
    setColorStopAt(0.28, QColor(10, 10, 190));
    setColorStopAt(0.5, QColor(0, 0, 0));
    setColorStopAt(0.72, QColor(190, 10, 10));
    setColorStopAt(0.82, QColor(255, 70, 10));
    setColorStopAt(1, QColor(255, 255, 50));
    break;
  case gpSpectrum:
    setColorInterpolation(ciHSV);
    setColorStopAt(0, QColor(50, 0, 50));
    setColorStopAt(0.15, QColor(0, 0, 255));
    setColorStopAt(0.35, QColor(0, 255, 255));
    setColorStopAt(0.6, QColor(255, 255, 0));
    setColorStopAt(0.75, QColor(255, 30, 0));
    setColorStopAt(1, QColor(50, 0, 0));
    break;
  case gpJet:
    setColorInterpolation(ciRGB);
    setColorStopAt(0, QColor(0, 0, 100));
    setColorStopAt(0.15, QColor(0, 50, 255));
    setColorStopAt(0.35, QColor(0, 255, 255));
    setColorStopAt(0.65, QColor(255, 255, 0));
    setColorStopAt(0.85, QColor(255, 30, 0));
    setColorStopAt(1, QColor(100, 0, 0));
    break;
  case gpHues:
    setColorInterpolation(ciHSV);
    setColorStopAt(0, QColor(255, 0, 0));
    setColorStopAt(1.0 / 3.0, QColor(0, 0, 255));
    setColorStopAt(2.0 / 3.0, QColor(0, 255, 0));
    setColorStopAt(1, QColor(255, 0, 0));
    break;
  }
}
bool QCPColorGradient::operator!= (const QCPColorGradient & other) const [inline]
Definition at line 2255 of file qcustomplot.h.
                                                       {
    return !(*this == other);
  }
bool QCPColorGradient::operator== (const QCPColorGradient & other) const
Definition at line 12360 of file qcustomplot.cpp.
References mColorInterpolation, mColorStops, mLevelCount, and mPeriodic.
                                                                     {
  return ((other.mLevelCount == this->mLevelCount) &&
          (other.mColorInterpolation == this->mColorInterpolation) &&
          (other.mPeriodic == this->mPeriodic) &&
          (other.mColorStops == this->mColorStops));
}
bool QCPColorGradient::periodic () const [inline]
Definition at line 2263 of file qcustomplot.h.
{ return mPeriodic; }
void QCPColorGradient::setColorInterpolation (QCPColorGradient::ColorInterpolation interpolation)
Sets whether the colors in between the configured color stops (see setColorStopAt) shall be interpolated linearly in RGB or in HSV color space.
For example, a sweep in RGB space from red to green will have a muddy brown intermediate color, whereas in HSV space the intermediate color is yellow.
Definition at line 12425 of file qcustomplot.cpp.
References mColorBufferInvalidated, and mColorInterpolation.
Referenced by loadPreset().
                                                      {
  if (interpolation != mColorInterpolation) {
    mColorInterpolation = interpolation;
    mColorBufferInvalidated = true;
  }
}
void QCPColorGradient::setColorStopAt (double position, const QColor & color)
Sets the color the gradient will have at the specified position (from 0 to 1). In between these color stops, the color is interpolated according to setColorInterpolation.
See also
setColorStops, clearColorStops
Definition at line 12411 of file qcustomplot.cpp.
References mColorBufferInvalidated, and mColorStops.
Referenced by inverted(), and loadPreset().
                                                                          {
  mColorStops.insert(position, color);
  mColorBufferInvalidated = true;
}
void QCPColorGradient::setColorStops (const QMap< double, QColor > & colorStops)
Sets at which positions from 0 to 1 which color shall occur. The positions are the keys, the colors are the values of the passed QMap colorStops. In between these color stops, the color is interpolated according to setColorInterpolation.
A more convenient way to create a custom gradient may be to clear all color stops with clearColorStops and then adding them one by one with setColorStopAt.
See also
clearColorStops
Definition at line 12398 of file qcustomplot.cpp.
References colorStops(), mColorBufferInvalidated, and mColorStops.
                                                                           {
  mColorStops = colorStops;
  mColorBufferInvalidated = true;
}
void QCPColorGradient::setLevelCount (int n)
Sets the number of discretization levels of the color gradient to n. The default is 350 which is typically enough to create a smooth appearance.
Definition at line 12374 of file qcustomplot.cpp.
References mColorBufferInvalidated, mLevelCount, and n.
                                          {
  if (n < 2) {
    qDebug() << Q_FUNC_INFO << "n must be greater or equal 2 but was" << n;
    n = 2;
  }
  if (n != mLevelCount) {
    mLevelCount = n;
    mColorBufferInvalidated = true;
  }
}
void QCPColorGradient::setPeriodic (bool enabled)
Sets whether data points that are outside the configured data range (e.g. QCPColorMap::setDataRange) are colored by periodically repeating the color gradient or whether they all have the same color, corresponding to the respective gradient boundary color.
As shown in the image above, gradients that have the same start and end color are especially suitable for a periodic gradient mapping, since they produce smooth color transitions throughout the color map. A preset that has this property is gpHues.
In practice, using periodic color gradients makes sense when the data corresponds to a periodic dimension, such as an angle or a phase. If this is not the case, the color encoding might become ambiguous, because multiple different data values are shown as the same color.
Definition at line 12454 of file qcustomplot.cpp.
References mPeriodic.
{ mPeriodic = enabled; }
void QCPColorGradient::updateColorBuffer () [protected]
Definition at line 12717 of file qcustomplot.cpp.
References ciHSV, ciRGB, i, mColorBuffer, mColorBufferInvalidated, mColorInterpolation, mColorStops, and mLevelCount.
Referenced by color(), and colorize().
                                         {
  if (mColorBuffer.size() != mLevelCount)
    mColorBuffer.resize(mLevelCount);
  if (mColorStops.size() > 1) {
    double indexToPosFactor = 1.0 / (double)(mLevelCount - 1);
    for (int i = 0; i < mLevelCount; ++i) {
      double position = i * indexToPosFactor;
      QMap<double, QColor>::const_iterator it =
          mColorStops.lowerBound(position);
      if (it == mColorStops.constEnd()) // position is on or after last stop,
                                        // use color of last stop
      {
        mColorBuffer[i] = (it - 1).value().rgb();
      } else if (it == mColorStops.constBegin()) // position is on or before
                                                 // first stop, use color of
                                                 // first stop
      {
        mColorBuffer[i] = it.value().rgb();
      } else // position is in between stops (or on an intermediate stop),
             // interpolate color
      {
        QMap<double, QColor>::const_iterator high = it;
        QMap<double, QColor>::const_iterator low = it - 1;
        double t = (position - low.key()) /
                   (high.key() - low.key()); // interpolation factor 0..1
        switch (mColorInterpolation) {
        case ciRGB: {
          mColorBuffer[i] =
              qRgb((1 - t) * low.value().red() + t * high.value().red(),
                   (1 - t) * low.value().green() + t * high.value().green(),
                   (1 - t) * low.value().blue() + t * high.value().blue());
          break;
        }
        case ciHSV: {
          QColor lowHsv = low.value().toHsv();
          QColor highHsv = high.value().toHsv();
          double hue = 0;
          double hueDiff = highHsv.hueF() - lowHsv.hueF();
          if (hueDiff > 0.5)
            hue = lowHsv.hueF() - t * (1.0 - hueDiff);
          else if (hueDiff < -0.5)
            hue = lowHsv.hueF() + t * (1.0 + hueDiff);
          else
            hue = lowHsv.hueF() + t * hueDiff;
          if (hue < 0)
            hue += 1.0;
          else if (hue >= 1.0)
            hue -= 1.0;
          mColorBuffer[i] =
              QColor::fromHsvF(
                  hue,
                  (1 - t) * lowHsv.saturationF() + t * highHsv.saturationF(),
                  (1 - t) * lowHsv.valueF() + t * highHsv.valueF()).rgb();
          break;
        }
        }
      }
    }
  } else if (mColorStops.size() == 1) {
    mColorBuffer.fill(mColorStops.constBegin().value().rgb());
  } else // mColorStops is empty, fill color buffer with black
  {
    mColorBuffer.fill(qRgb(0, 0, 0));
  }
  mColorBufferInvalidated = false;
}
Member Data Documentation
QVector<QRgb> QCPColorGradient::mColorBuffer [protected]
Definition at line 2290 of file qcustomplot.h.
Referenced by color(), colorize(), QCPColorGradient(), and updateColorBuffer().
bool QCPColorGradient::mColorBufferInvalidated [protected]
Definition at line 2291 of file qcustomplot.h.
Referenced by clearColorStops(), color(), colorize(), setColorInterpolation(), setColorStopAt(), setColorStops(), setLevelCount(), and updateColorBuffer().
ColorInterpolation QCPColorGradient::mColorInterpolation [protected]
Definition at line 2286 of file qcustomplot.h.
Referenced by operator==(), setColorInterpolation(), and updateColorBuffer().
QMap<double, QColor> QCPColorGradient::mColorStops [protected]
Definition at line 2285 of file qcustomplot.h.
Referenced by clearColorStops(), inverted(), operator==(), setColorStopAt(), setColorStops(), and updateColorBuffer().
int QCPColorGradient::mLevelCount [protected]
Definition at line 2284 of file qcustomplot.h.
Referenced by color(), colorize(), operator==(), QCPColorGradient(), setLevelCount(), and updateColorBuffer().
bool QCPColorGradient::mPeriodic [protected]
Definition at line 2287 of file qcustomplot.h.
Referenced by color(), colorize(), operator==(), and setPeriodic().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp