Hardware::eQEP Class Reference
#include <eqep.h>
Public Types
enum eQEP_Mode { eQEP_Mode_Absolute = 0,
eQEP_Mode_Relative = 1,
eQEP_Mode_Error = 2
 }
Public Member Functions
eQEP (std::string _path, eQEP_Mode _mode)
void set_position (int32_t position)
int32_t get_position (bool _poll=true)
int WaitForPositionChange (CallbackType callback)
void WaitForPositionChangeCancel ()
void set_period (uint64_t period)
uint64_t get_period ()
void set_mode (eQEP_Mode mode)
eQEP_Mode get_mode ()
Private Attributes
std::string path
Friends
void * threadedPolleqep (void *value)
Additional Inherited Members
Detailed Description
Definition at line 40 of file eqep.h.
Member Enumeration Documentation
enum Hardware::eQEP::eQEP_Mode
Enumerator
eQEP_Mode_Absolute
eQEP_Mode_Relative
eQEP_Mode_Error
Definition at line 47 of file eqep.h.
        {
            // Absolute positioning mode
            eQEP_Mode_Absolute = 0,
            // Relative positioning mode
            eQEP_Mode_Relative = 1,
            // Error flag
            eQEP_Mode_Error = 2,
        } eQEP_Mode;
Constructor & Destructor Documentation
Hardware::eQEP::eQEP (std::string _path, eQEP::eQEP_Mode _mode)
Definition at line 40 of file eqep.cpp.
References Hardware::BBB::CapeLoaded(), eQEP0, eQEP1, eQEP2, set_mode(), set_position(), SLOTS, and Hardware::BBB::Write().
        : path(_path)
    {
        if (_path == eQEP0)
        {
            if (!CapeLoaded("bone_eqep0")) { Write(SLOTS, "bone_eqep0"); }
        }
        else if (_path == eQEP1)
        {
            if (!CapeLoaded("bone_eqep1")) { Write(SLOTS, "bone_eqep1"); }
        }
        else if (_path == eQEP2)
        {
            if (!CapeLoaded("bone_eqep2b")) { Write(SLOTS, "bone_eqep2b"); }
        }
        // Set the mode of the hardware
        this->set_mode(_mode);
        // Reset the position
        this->set_position(0);
    }
Member Function Documentation
eQEP::eQEP_Mode Hardware::eQEP::get_mode ()
Definition at line 226 of file eqep.cpp.
References eQEP_Mode_Error, and path.
    {
        // Open the file representing the position
        FILE *fp = fopen((this->path + "/mode").c_str(), "r");
        // Check that we opened the file correctly
        if (fp == NULL)
        {
            // Error, break out
            std::cerr << "[eQEP " << this->path << "] Unable to open mode for read" << std::endl;
            return eQEP::eQEP_Mode_Error;
        }
        // Write the desired value to the file
        eQEP::eQEP_Mode mode;
        fscanf(fp, "%u", (unsigned int*)&mode);
        // Commit changes
        fclose(fp);
        // Return the mode
        return mode;
    }
uint64_t Hardware::eQEP::get_period ()
Definition at line 201 of file eqep.cpp.
References path.
    {
        // Open the file representing the position
        FILE *fp = fopen((this->path + "/period").c_str(), "r");
        // Check that we opened the file correctly
        if (fp == NULL)
        {
            // Error, break out
            std::cerr << "[eQEP " << this->path << "] Unable to open period for read" << std::endl;
            return 0;
        }
        // Write the desired value to the file
        uint64_t period = 0;
        fscanf(fp, "%llu", &period);
        // Commit changes
        fclose(fp);
        // Return the period
        return period;
    }
int32_t Hardware::eQEP::get_position (bool _poll = true)
Definition at line 140 of file eqep.cpp.
References path.
Referenced by Hardware::threadedPolleqep().
    {
        // Position temporary variable
        int32_t position;
        char dummy;
        struct pollfd ufd;
        // Do we want to poll?
        if (_poll)
        {
            // Open a connection to the attribute file.
            if ((ufd.fd = open((this->path + "/position").c_str(), O_RDWR)) < 0)
            {
                // Error, break out
                std::cerr << "[eQEP " << this->path << "] unable to open position for polling" <<
      std::endl;
                return 0;
            }
            // Dummy read
            read(ufd.fd, &dummy, 1);
            // Poll the port
            ufd.events = (short)EPOLLET;
            if (poll(&ufd, 1, -1) < 0)
            {
                // Error, break out
                std::cerr << "[eQEP " << this->path << "] Error occurred whilst polling" << std::endl;
                close(ufd.fd);
                return 0;
            }
        }
        // Read the position
        FILE *fp = fopen((this->path + "/position").c_str(), "r");
        // Check that we opened the file correctly
        if (fp == NULL)
        {
            // Error, break out
            std::cerr << "[eQEP " << this->path << "] Unable to open position for read" << std::endl;
            close(ufd.fd);
            return 0;
        }
        // Write the desired value to the file
        fscanf(fp, "%d", &position);
        // Commit changes
        fclose(fp);
        // If we were polling, close the polling file
        if (_poll)
        {
            close(ufd.fd);
        }
        // Return the position
        return position;
    }
void Hardware::eQEP::set_mode (eQEP::eQEP_Mode _mode)
Definition at line 106 of file eqep.cpp.
References path.
Referenced by eQEP().
    {
        // Open the file representing the position
        FILE *fp = fopen((this->path + "/mode").c_str(), "w");
        // Check that we opened the file correctly
        if (fp == NULL)
        {
            // Error, break out
            std::cerr << "[eQEP " << this->path << "] Unable to open mode for write" << std::endl;
            return;
        }
        // Write the desired value to the file
        fprintf(fp, "%u\n", _mode);
        // Commit changes
        fclose(fp);
    }
void Hardware::eQEP::set_period (uint64_t period)
Definition at line 85 of file eqep.cpp.
References path.
Referenced by Hardware::EC12P::EC12P().
    {
        // Open the file representing the position
        FILE *fp = fopen((this->path + "/period").c_str(), "w");
        // Check that we opened the file correctly
        if (fp == NULL)
        {
            // Error, break out
            std::cerr << "[eQEP " << this->path << "] Unable to open period for write" << std::endl;
            return;
        }
        // Write the desired value to the file
        fprintf(fp, "%llu\n", period);
        // Commit changes
        fclose(fp);
    }
void Hardware::eQEP::set_position (int32_t position)
Definition at line 64 of file eqep.cpp.
References path.
Referenced by eQEP().
    {
        // Open the file representing the position
        FILE *fp = fopen((this->path + "/position").c_str(), "w");
        // Check that we opened the file correctly
        if (fp == NULL)
        {
            // Error, break out
            std::cerr << "[eQEP " << this->path << "] Unable to open position for write" << std::endl;
            return;
        }
        // Write the desired value to the file
        fprintf(fp, "%d\n", position);
        // Commit changes
        fclose(fp);
    }
int Hardware::eQEP::WaitForPositionChange (CallbackType callback)
Definition at line 126 of file eqep.cpp.
References Hardware::BBB::callbackFunction, Hardware::BBB::thread, threadedPolleqep, and Hardware::BBB::threadRunning.
    {
        threadRunning = true;
        callbackFunction = callback;
        if (pthread_create(&this->thread, NULL, &threadedPolleqep, static_cast<void*>
      (this)))
        {
            threadRunning = false;
            throw Exception::FailedToCreateGPIOPollingThreadException();
        }
        return 0;
    }
void Hardware::eQEP::WaitForPositionChangeCancel () [inline]
Definition at line 70 of file eqep.h.
References Hardware::BBB::threadRunning.
{ this->threadRunning = false; }
Friends And Related Function Documentation
void* threadedPolleqep (void * value) [friend]
Definition at line 250 of file eqep.cpp.
Referenced by WaitForPositionChange().
    {
        eQEP *eqep = static_cast<eQEP*>(value);
        while (eqep->threadRunning)
        {
            eqep->callbackFunction(eqep->get_position(true));
            usleep(eqep->debounceTime * 1000);
        }
        return 0;
    }
Member Data Documentation
std::string Hardware::eQEP::path [private]
Definition at line 44 of file eqep.h.
Referenced by get_mode(), get_period(), get_position(), set_mode(), set_period(), and set_position().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/eqep.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/eqep.cpp