SoilMath_Test Class Reference
Public Member Functions
SoilMath_Test ()
Private Slots
void testCase_Stats_BigNoDiscrete ()
void testCase_Stats_Shifted ()
void testCase_Mat_Stats ()
void testCase_Mat_Stats_Mask ()
void testCase_benchmark_roundcast ()
void testCase_benchmark_float2intround ()
void testCase_quickPow ()
void testCase_fastPow ()
void testCase_normalPow ()
Private Attributes
uint32_t count = 0
Detailed Description
Definition at line 20 of file tst_soilmath_test.cpp.
Constructor & Destructor Documentation
SoilMath_Test::SoilMath_Test ()
Definition at line 45 of file tst_soilmath_test.cpp.
{
}
Member Function Documentation
void SoilMath_Test::testCase_benchmark_float2intround () [private], [slot]
Definition at line 147 of file tst_soilmath_test.cpp.
References SoilMath::float2intRound().
{
    float testf = 254.5;
    QBENCHMARK
    {
        SoilMath::float2intRound(testf);
    }
}
void SoilMath_Test::testCase_benchmark_roundcast () [private], [slot]
Definition at line 137 of file tst_soilmath_test.cpp.
{
    float testf = 254.5;
    QBENCHMARK
    {
        static_cast<int>(std::round(testf));
    }
}
void SoilMath_Test::testCase_fastPow () [private], [slot]
Definition at line 171 of file tst_soilmath_test.cpp.
References SoilMath::fastPow(), i, and QCLOSE_COMPARE.
{
    for (int i = 1; i < 256; i++)
    {
       QCLOSE_COMPARE(SoilMath::fastPow(i, 2), std::pow(
      i, 2), 0.1);
    }
    QBENCHMARK
    {
        SoilMath::fastPow(127, 2);
    }
}
void SoilMath_Test::testCase_Mat_Stats () [private], [slot]
Definition at line 103 of file tst_soilmath_test.cpp.
References actualHistBean, actualMaxBean, actualMeanBean, actualminBean, actualStdBean, actualSumBean, SoilMath::Stats< T1, T2, T3 >::bins, SoilMath::Stats< T1, T2, T3 >::max, SoilMath::Stats< T1, T2, T3 >::Mean, SoilMath::Stats< T1, T2, T3 >::min, QCLOSE_COMPARE, QCOMPARE_RANGE, SoilMath::Stats< T1, T2, T3 >::Std, and SoilMath::Stats< T1, T2, T3 >::Sum.
{
    cv::Mat beans = cv::imread("Images/beans.ppm",0);
    ucharStat_t Test((uchar *)beans.data, beans.cols, beans.rows);
    QCLOSE_COMPARE(Test.Mean, actualMeanBean, 0.001);
    QCOMPARE_RANGE(Test.bins, actualHistBean, 256, uint32_t);
    QCOMPARE(Test.min, actualminBean);
    QCOMPARE(Test.max, actualMaxBean);
    QCLOSE_COMPARE(Test.Std, actualStdBean, 0.01);
    QCOMPARE((uint64_t)Test.Sum, (uint64_t)actualSumBean);
    QBENCHMARK
    {
        ucharStat_t TestBench((uchar *)beans.data, beans.cols, beans.rows);
    }
}
void SoilMath_Test::testCase_Mat_Stats_Mask () [private], [slot]
Definition at line 120 of file tst_soilmath_test.cpp.
References actualHistBeanMask, actualMaxBeanMask, actualminBeanMask, actualStdBeanMask, actualSumBeanMask, acutalMeanBeanMask, SoilMath::Stats< T1, T2, T3 >::bins, mask, SoilMath::Stats< T1, T2, T3 >::max, SoilMath::Stats< T1, T2, T3 >::Mean, SoilMath::Stats< T1, T2, T3 >::min, QCLOSE_COMPARE, QCOMPARE_RANGE, SoilMath::Stats< T1, T2, T3 >::Std, and SoilMath::Stats< T1, T2, T3 >::Sum.
{
    cv::Mat beans = cv::imread("Images/beans.ppm",0);
    cv::Mat mask = cv::imread("Images/beansmask.ppm",0);
    ucharStat_t Test((uchar *)beans.data, beans.cols, beans.rows, (
      uchar *)mask.data);
    QCLOSE_COMPARE(Test.Mean, acutalMeanBeanMask, 0.001);
    QCOMPARE_RANGE(Test.bins, actualHistBeanMask, 256, uint32_t);
    QCOMPARE(Test.min, actualminBeanMask);
    QCOMPARE(Test.max, actualMaxBeanMask);
    QCOMPARE((uint64_t)Test.Sum, (uint64_t)actualSumBeanMask);
    QCLOSE_COMPARE(Test.Std, actualStdBeanMask, 0.01);
    QBENCHMARK
    {
        ucharStat_t TestBench((uchar *)beans.data, beans.cols, beans.rows, (
      uchar *)mask.data);
    }
}
void SoilMath_Test::testCase_normalPow () [private], [slot]
Definition at line 184 of file tst_soilmath_test.cpp.
{
    QBENCHMARK
    {
        std::pow(127, 2);
    }
}
void SoilMath_Test::testCase_quickPow () [private], [slot]
Definition at line 158 of file tst_soilmath_test.cpp.
References i, QCLOSE_COMPARE, and SoilMath::quick_pow2().
{
    for (int i = -255; i < 256; i++)
    {
        QCLOSE_COMPARE(SoilMath::quick_pow2(i), std::pow(
      i, 2), 0.0001);
    }
    QBENCHMARK
    {
        SoilMath::quick_pow2(127);
    }
}
void SoilMath_Test::testCase_Stats_BigNoDiscrete () [private], [slot]
Definition at line 49 of file tst_soilmath_test.cpp.
References SoilMath::Stats< T1, T2, T3 >::bins, count, histTestResult, i, j, SoilMath::Stats< T1, T2, T3 >::max, maxTestResult, SoilMath::Stats< T1, T2, T3 >::Mean, meanTestResult, SoilMath::Stats< T1, T2, T3 >::min, minTestResult, SoilMath::Stats< T1, T2, T3 >::n, nTestResult, QCLOSE_COMPARE, QCOMPARE_RANGE, SoilMath::Stats< T1, T2, T3 >::Range, rangeTestResult, SoilMath::Stats< T1, T2, T3 >::Std, stdTestResult, SoilMath::Stats< T1, T2, T3 >::Sum, sumTestResult, and testMatrix.
{
    uint16_t *BigNoTestMatrix = new uint16_t[40000];
    uint32_t count = 0;
    for (uint32_t i = 0; i < 200; i++)
    {
        for (uint32_t j = 0; j < 200; j++)
        {
            BigNoTestMatrix[count++] = testMatrix[i][j] * 10;
        }
    }
    uint16Stat_t Test(BigNoTestMatrix, 200, 200);
    QCOMPARE_RANGE(Test.bins, histTestResult, 255, uint32_t);
    QCLOSE_COMPARE(Test.Mean, meanTestResult * 10, 0.01);
    QCOMPARE(Test.n, nTestResult);
    QCOMPARE((uint64_t)Test.Sum, (uint64_t)(sumTestResult * 10));
    QCOMPARE((uint32_t)Test.min, (uint32_t)(minTestResult * 10));
    QCOMPARE((uint32_t)Test.max, (uint32_t)(maxTestResult * 10));
    QCOMPARE((uint32_t)Test.Range, (uint32_t)(rangeTestResult * 10));
    QCLOSE_COMPARE(Test.Std, stdTestResult * 10, 0.025);
    delete[] BigNoTestMatrix;
}
void SoilMath_Test::testCase_Stats_Shifted () [private], [slot]
Definition at line 75 of file tst_soilmath_test.cpp.
References SoilMath::Stats< T1, T2, T3 >::bins, count, histTestResult, i, j, SoilMath::Stats< T1, T2, T3 >::Mean, meanTestResult, SoilMath::Stats< T1, T2, T3 >::n, nTestResult, QCLOSE_COMPARE, QCOMPARE_RANGE, SoilMath::Stats< T1, T2, T3 >::Std, stdTestResult, and testMatrix.
{
    uint16_t *BigNoTestMatrix = new uint16_t[40000];
    uint32_t count = 0;
    for (uint32_t i = 0; i < 200; i++)
    {
        for (uint32_t j = 0; j < 200; j++)
        {
            BigNoTestMatrix[count++] = testMatrix[i][j] + 10;
        }
    }
    uint32_t *histTestResultShifted = new uint32_t[266] {};
    for (uint32_t i = 10; i < 266; i++)
    {
        histTestResultShifted[i] = histTestResult[i - 10];
    }
    uint16Stat_t Test(BigNoTestMatrix, 200, 200, 266, 0, 265);
    QCOMPARE_RANGE(Test.bins, histTestResultShifted, 266, uint32_t);
    QCLOSE_COMPARE(Test.Mean, meanTestResult + 10, 0.01);
    QCOMPARE(Test.n, nTestResult);
    QCLOSE_COMPARE(Test.Std, stdTestResult, 0.025);
    delete[] BigNoTestMatrix;
}
Member Data Documentation
uint32_t SoilMath_Test::count = 0 [private]
Definition at line 42 of file tst_soilmath_test.cpp.
Referenced by testCase_Stats_BigNoDiscrete(), and testCase_Stats_Shifted().
The documentation for this class was generated from the following file:
/home/peer23peer/VisionSoilAnalyzer/src/Tests/SoilMath_Test/tst_soilmath_test.cpp