QCPItemBracket Class Reference
A bracket for referencing/highlighting certain parts in the plot.
#include <qcustomplot.h>
Public Types
enum BracketStyle { bsSquare,
bsRound,
bsCurly,
bsCalligraphic
 }
Public Member Functions
QCPItemBracket (QCustomPlot *parentPlot)
virtual ~QCPItemBracket ()
QPen pen () const
QPen selectedPen () const
double length () const
BracketStyle style () const
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
void setLength (double length)
void setStyle (BracketStyle style)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Attributes
QCPItemPosition *const left
QCPItemPosition *const right
QCPItemAnchor *const center
Protected Types
enum AnchorIndex { aiCenter
 }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
QPen mainPen () const
Protected Attributes
QPen mPen
QPen mSelectedPen
double mLength
BracketStyle mStyle
Additional Inherited Members
Detailed Description
A bracket for referencing/highlighting certain parts in the plot.
 anchors, solid blue discs are positions."
It has two positions, left and right, which define the span of the bracket. If left is actually farther to the left than right, the bracket is opened to the bottom, as shown in the example image.
The bracket supports multiple styles via setStyle. The length, i.e. how far the bracket stretches away from the embraced span, can be controlled with setLength.
Demonstrating the effect of different values for setLength, for styles bsCalligraphic and bsSquare. Anchors and positions are displayed for reference.
It provides an anchor center, to allow connection of other items, e.g. an arrow (QCPItemLine or QCPItemCurve) or a text label (QCPItemText), to the bracket.
Definition at line 4215 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemBracket::AnchorIndex [protected]
Enumerator
aiCenter
Definition at line 4260 of file qcustomplot.h.
{ aiCenter };
enum QCPItemBracket::BracketStyle
Enumerator
bsSquare
 A brace with angled edges.
bsRound
 A brace with round edges.
bsCurly
 A curly brace.
bsCalligraphic
 A curly brace with varying stroke width giving a calligraphic impression
Definition at line 4224 of file qcustomplot.h.
                    {
    bsSquare
    ,
    bsRound
    ,
    bsCurly
    ,
    bsCalligraphic
  };
Constructor & Destructor Documentation
QCPItemBracket::QCPItemBracket (QCustomPlot * parentPlot)
Creates a bracket item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 25860 of file qcustomplot.cpp.
References bsCalligraphic, left, right, QCPItemPosition::setCoords(), setLength(), setPen(), setSelectedPen(), and setStyle().
    : QCPAbstractItem(parentPlot), left(createPosition(QLatin1String("left
      "))),
      right(createPosition(QLatin1String("right"))),
      center(createAnchor(QLatin1String("center"), aiCenter)) {
  left->setCoords(0, 0);
  right->setCoords(1, 1);
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue, 2));
  setLength(8);
  setStyle(bsCalligraphic);
}
QCPItemBracket::~QCPItemBracket () [virtual]
Definition at line 25873 of file qcustomplot.cpp.
{}
Member Function Documentation
QPointF QCPItemBracket::anchorPixelPoint (int anchorId) const [protected], [virtual]
Reimplemented from QCPAbstractItem.
Definition at line 26049 of file qcustomplot.cpp.
References aiCenter, left, mLength, QCPItemPosition::pixelPoint(), and right.
                                                           {
  QVector2D leftVec(left->pixelPoint());
  QVector2D rightVec(right->pixelPoint());
  if (leftVec.toPoint() == rightVec.toPoint())
    return leftVec.toPointF();
  QVector2D widthVec = (rightVec - leftVec) * 0.5f;
  QVector2D lengthVec(-widthVec.y(), widthVec.x());
  lengthVec = lengthVec.normalized() * mLength;
  QVector2D centerVec = (rightVec + leftVec) * 0.5f - lengthVec;
  switch (anchorId) {
  case aiCenter:
    return centerVec.toPointF();
  }
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
void QCPItemBracket::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractItem.
Definition at line 25967 of file qcustomplot.cpp.
References bsCalligraphic, bsCurly, bsRound, bsSquare, QCPAbstractItem::clipRect(), QCPPainter::drawLine(), left, mainPen(), mLength, mStyle, QCPItemPosition::pixelPoint(), right, and QCPPainter::setPen().
                                             {
  QVector2D leftVec(left->pixelPoint());
  QVector2D rightVec(right->pixelPoint());
  if (leftVec.toPoint() == rightVec.toPoint())
    return;
  QVector2D widthVec = (rightVec - leftVec) * 0.5f;
  QVector2D lengthVec(-widthVec.y(), widthVec.x());
  lengthVec = lengthVec.normalized() * mLength;
  QVector2D centerVec = (rightVec + leftVec) * 0.5f - lengthVec;
  QPolygon boundingPoly;
  boundingPoly << leftVec.toPoint() << rightVec.toPoint()
               << (rightVec - lengthVec).toPoint()
               << (leftVec - lengthVec).toPoint();
  QRect clip = clipRect().adjusted(-mainPen().widthF(), -mainPen().widthF(),
                                   mainPen().widthF(), mainPen().widthF());
  if (clip.intersects(boundingPoly.boundingRect())) {
    painter->setPen(mainPen());
    switch (mStyle) {
    case bsSquare: {
      painter->drawLine((centerVec + widthVec).toPointF(),
                        (centerVec - widthVec).toPointF());
      painter->drawLine((centerVec + widthVec).toPointF(),
                        (centerVec + widthVec + lengthVec).toPointF());
      painter->drawLine((centerVec - widthVec).toPointF(),
                        (centerVec - widthVec + lengthVec).toPointF());
      break;
    }
    case bsRound: {
      painter->setBrush(Qt::NoBrush);
      QPainterPath path;
      path.moveTo((centerVec + widthVec + lengthVec).toPointF());
      path.cubicTo((centerVec + widthVec).toPointF(),
                   (centerVec + widthVec).toPointF(), centerVec.toPointF());
      path.cubicTo((centerVec - widthVec).toPointF(),
                   (centerVec - widthVec).toPointF(),
                   (centerVec - widthVec + lengthVec).toPointF());
      painter->drawPath(path);
      break;
    }
    case bsCurly: {
      painter->setBrush(Qt::NoBrush);
      QPainterPath path;
      path.moveTo((centerVec + widthVec + lengthVec).toPointF());
      path.cubicTo((centerVec + widthVec - lengthVec * 0.8f).toPointF(),
                   (centerVec + 0.4f * widthVec + lengthVec).toPointF(),
                   centerVec.toPointF());
      path.cubicTo((centerVec - 0.4f * widthVec + lengthVec).toPointF(),
                   (centerVec - widthVec - lengthVec * 0.8f).toPointF(),
                   (centerVec - widthVec + lengthVec).toPointF());
      painter->drawPath(path);
      break;
    }
    case bsCalligraphic: {
      painter->setPen(Qt::NoPen);
      painter->setBrush(QBrush(mainPen().color()));
      QPainterPath path;
      path.moveTo((centerVec + widthVec + lengthVec).toPointF());
      path.cubicTo((centerVec + widthVec - lengthVec * 0.8f).toPointF(),
                   (centerVec + 0.4f * widthVec + 0.8f * lengthVec).toPointF(),
                   centerVec.toPointF());
      path.cubicTo((centerVec - 0.4f * widthVec + 0.8f * lengthVec).toPointF(),
                   (centerVec - widthVec - lengthVec * 0.8f).toPointF(),
                   (centerVec - widthVec + lengthVec).toPointF());
      path.cubicTo((centerVec - widthVec - lengthVec * 0.5f).toPointF(),
                   (centerVec - 0.2f * widthVec + 1.2f * lengthVec).toPointF(),
                   (centerVec + lengthVec * 0.2f).toPointF());
      path.cubicTo((centerVec + 0.2f * widthVec + 1.2f * lengthVec).toPointF(),
                   (centerVec + widthVec - lengthVec * 0.5f).toPointF(),
                   (centerVec + widthVec + lengthVec).toPointF());
      painter->drawPath(path);
      break;
    }
    }
  }
}
double QCPItemBracket::length () const [inline]
Definition at line 4241 of file qcustomplot.h.
Referenced by setLength().
{ return mLength; }
QPen QCPItemBracket::mainPen () const [protected]
Definition at line 26073 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{ return mSelected ? mSelectedPen : mPen; }
QPen QCPItemBracket::pen () const [inline]
Definition at line 4239 of file qcustomplot.h.
Referenced by setPen(), and setSelectedPen().
{ return mPen; }
QPen QCPItemBracket::selectedPen () const [inline]
Definition at line 4240 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemBracket::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 25919 of file qcustomplot.cpp.
References bsCalligraphic, bsCurly, bsRound, bsSquare, c, QCPAbstractItem::distSqrToLine(), left, mLength, QCPAbstractItem::mSelectable, mStyle, QCPItemPosition::pixelPoint(), and right.
                                                           {
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  QVector2D leftVec(left->pixelPoint());
  QVector2D rightVec(right->pixelPoint());
  if (leftVec.toPoint() == rightVec.toPoint())
    return -1;
  QVector2D widthVec = (rightVec - leftVec) * 0.5f;
  QVector2D lengthVec(-widthVec.y(), widthVec.x());
  lengthVec = lengthVec.normalized() * mLength;
  QVector2D centerVec = (rightVec + leftVec) * 0.5f - lengthVec;
  switch (mStyle) {
  case QCPItemBracket::bsSquare:
  case QCPItemBracket::bsRound: {
    double a = distSqrToLine((centerVec - widthVec).toPointF(),
                             (centerVec + widthVec).toPointF(), pos);
    double b = distSqrToLine((centerVec - widthVec + lengthVec).toPointF(),
                             (centerVec - widthVec).toPointF(), pos);
    double c = distSqrToLine((centerVec + widthVec + lengthVec).toPointF(),
                             (centerVec + widthVec).toPointF(), pos);
    return qSqrt(qMin(qMin(a, b), c));
  }
  case QCPItemBracket::bsCurly:
  case QCPItemBracket::bsCalligraphic: {
    double a = distSqrToLine(
        (centerVec - widthVec * 0.75f + lengthVec * 0.15f).toPointF(),
        (centerVec + lengthVec * 0.3f).toPointF(), pos);
    double b = distSqrToLine(
        (centerVec - widthVec + lengthVec * 0.7f).toPointF(),
        (centerVec - widthVec * 0.75f + lengthVec * 0.15f).toPointF(), pos);
    double c = distSqrToLine(
        (centerVec + widthVec * 0.75f + lengthVec * 0.15f).toPointF(),
        (centerVec + lengthVec * 0.3f).toPointF(), pos);
    double d = distSqrToLine(
        (centerVec + widthVec + lengthVec * 0.7f).toPointF(),
        (centerVec + widthVec * 0.75f + lengthVec * 0.15f).toPointF(), pos);
    return qSqrt(qMin(qMin(a, b), qMin(c, d)));
  }
  }
  return -1;
}
void QCPItemBracket::setLength (double length)
Sets the length in pixels how far the bracket extends in the direction towards the embraced span of the bracket (i.e. perpendicular to the left-right-direction)
Demonstrating the effect of different values for setLength, for styles bsCalligraphic and bsSquare. Anchors and positions are displayed for reference.
Definition at line 25907 of file qcustomplot.cpp.
References length(), and mLength.
Referenced by QCPItemBracket().
{ mLength = length; }
void QCPItemBracket::setPen (const QPen & pen)
Sets the pen that will be used to draw the bracket.
Note that when the style is bsCalligraphic, only the color will be taken from the pen, the stroke and width are ignored. To change the apparent stroke width of a calligraphic bracket, use setLength, which has a similar effect.
See also
setSelectedPen
Definition at line 25886 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemBracket().
{ mPen = pen; }
void QCPItemBracket::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw the bracket when selected
See also
setPen, setSelected
Definition at line 25893 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemBracket().
{ mSelectedPen = pen; }
void QCPItemBracket::setStyle (QCPItemBracket::BracketStyle style)
Sets the style of the bracket, i.e. the shape/visual appearance.
See also
setPen
Definition at line 25914 of file qcustomplot.cpp.
References mStyle, and style().
Referenced by QCPItemBracket().
                                                              {
  mStyle = style;
}
BracketStyle QCPItemBracket::style () const [inline]
Definition at line 4242 of file qcustomplot.h.
Referenced by setStyle().
{ return mStyle; }
Member Data Documentation
QCPItemAnchor* const QCPItemBracket::center
Definition at line 4256 of file qcustomplot.h.
QCPItemPosition* const QCPItemBracket::left
Definition at line 4254 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemBracket(), and selectTest().
double QCPItemBracket::mLength [protected]
Definition at line 4262 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), selectTest(), and setLength().
QPen QCPItemBracket::mPen [protected]
Definition at line 4261 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPen QCPItemBracket::mSelectedPen [protected]
Definition at line 4261 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
BracketStyle QCPItemBracket::mStyle [protected]
Definition at line 4263 of file qcustomplot.h.
Referenced by draw(), selectTest(), and setStyle().
QCPItemPosition* const QCPItemBracket::right
Definition at line 4255 of file qcustomplot.h.
Referenced by anchorPixelPoint(), draw(), QCPItemBracket(), and selectTest().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp