DialogNN Class Reference
#include <dialognn.h>
Public Member Functions
DialogNN (QWidget *parent=0, SoilMath::NN *neuralnet=nullptr, SoilAnalyzer::SoilSettings *settings=nullptr, DialogSettings *settingWindow=nullptr)
~DialogNN ()
Private Slots
void on_pushButton_Settings_clicked ()
void on_learnErrorUpdate (double newError)
void on_pushButton_SelectSamples_clicked ()
void on_pushButton_Learn_clicked ()
void on_pushButton_SaveNN_clicked ()
void on_pushButton_OpenNN_clicked ()
void on_actionAbort_triggered ()
Private Member Functions
void setupErrorGraph ()
void makeLearnVectors (InputLearnVector_t &input, OutputLearnVector_t &output)
Private Attributes
Ui::DialogNN * ui
DialogSettings * SettingsWindow = nullptr
SoilMath::NN * NeuralNet = nullptr
SoilAnalyzer::SoilSettings * Settings = nullptr
QVector< double > currentError
QVector< double > errorTicks
double currentGeneration = 0
QStringList fn
Detailed Description
Definition at line 15 of file dialognn.h.
Constructor & Destructor Documentation
DialogNN::DialogNN (QWidget * parent = 0, SoilMath::NN * neuralnet = nullptr, SoilAnalyzer::SoilSettings * settings = nullptr, DialogSettings * settingWindow = nullptr) [explicit]
Definition at line 4 of file dialognn.cpp.
References NeuralNet, on_learnErrorUpdate(), Settings, SettingsWindow, setupErrorGraph(), and ui.
DialogNN::~DialogNN ()
Definition at line 42 of file dialognn.cpp.
References ui.
Member Function Documentation
void DialogNN::makeLearnVectors (InputLearnVector_t & input, OutputLearnVector_t & output) [private]
Definition at line 97 of file dialognn.cpp.
References fn, SoilMath::NN::GetInputNeurons(), SoilMath::NN::GetOutputNeurons(), SoilAnalyzer::Sample::Load(), SoilMath::makeOutput(), NeuralNet, Predict_struct::OutputNeurons, and SoilAnalyzer::Sample::ParticlePopulation.
Referenced by on_pushButton_Learn_clicked().
void DialogNN::on_actionAbort_triggered () [private], [slot]
Definition at line 147 of file dialognn.cpp.
References SoilMath::NN::EndErrorUsedByGA, NeuralNet, and ui.
void DialogNN::on_learnErrorUpdate (double newError) [private], [slot]
Definition at line 50 of file dialognn.cpp.
References currentGeneration, and ui.
Referenced by DialogNN(), and on_pushButton_OpenNN_clicked().
void DialogNN::on_pushButton_Learn_clicked () [private], [slot]
Definition at line 86 of file dialognn.cpp.
References fn, SoilMath::NN::GetInputNeurons(), SoilMath::NN::Learn(), makeLearnVectors(), NeuralNet, and setupErrorGraph().
void DialogNN::on_pushButton_OpenNN_clicked () [private], [slot]
Definition at line 130 of file dialognn.cpp.
References fn, SoilMath::NN::LoadState(), NeuralNet, on_learnErrorUpdate(), SoilAnalyzer::SoilSettings::SampleFolder, and Settings.
void DialogNN::on_pushButton_SaveNN_clicked () [private], [slot]
Definition at line 118 of file dialognn.cpp.
References fn, NeuralNet, SoilAnalyzer::SoilSettings::NNFolder, SoilMath::NN::SaveState(), and Settings.
void DialogNN::on_pushButton_SelectSamples_clicked () [private], [slot]
Definition at line 75 of file dialognn.cpp.
References fn, SoilAnalyzer::SoilSettings::SampleFolder, and Settings.
void DialogNN::on_pushButton_Settings_clicked () [private], [slot]
Definition at line 44 of file dialognn.cpp.
References DialogSettings::openTab(), SettingsWindow, and setupErrorGraph().
void DialogNN::setupErrorGraph () [private]
Definition at line 58 of file dialognn.cpp.
References SoilMath::NN::EndErrorUsedByGA, errorTicks, SoilMath::NN::MaxGenUsedByGA, NeuralNet, and ui.
Referenced by DialogNN(), on_pushButton_Learn_clicked(), and on_pushButton_Settings_clicked().
Member Data Documentation
QVector<double> DialogNN::currentError [private]
Definition at line 48 of file dialognn.h.
double DialogNN::currentGeneration = 0 [private]
Definition at line 50 of file dialognn.h.
Referenced by on_learnErrorUpdate().
QVector<double> DialogNN::errorTicks [private]
Definition at line 49 of file dialognn.h.
Referenced by setupErrorGraph().
QStringList DialogNN::fn [private]
Definition at line 51 of file dialognn.h.
Referenced by makeLearnVectors(), on_pushButton_Learn_clicked(), on_pushButton_OpenNN_clicked(), on_pushButton_SaveNN_clicked(), and on_pushButton_SelectSamples_clicked().
SoilMath::NN* DialogNN::NeuralNet = nullptr [private]
Definition at line 42 of file dialognn.h.
Referenced by DialogNN(), makeLearnVectors(), on_actionAbort_triggered(), on_pushButton_Learn_clicked(), on_pushButton_OpenNN_clicked(), on_pushButton_SaveNN_clicked(), and setupErrorGraph().
SoilAnalyzer::SoilSettings* DialogNN::Settings = nullptr [private]
Definition at line 43 of file dialognn.h.
Referenced by DialogNN(), on_pushButton_OpenNN_clicked(), on_pushButton_SaveNN_clicked(), and on_pushButton_SelectSamples_clicked().
DialogSettings* DialogNN::SettingsWindow = nullptr [private]
Definition at line 41 of file dialognn.h.
Referenced by DialogNN(), and on_pushButton_Settings_clicked().
Ui::DialogNN* DialogNN::ui [private]
Definition at line 40 of file dialognn.h.
Referenced by DialogNN(), on_actionAbort_triggered(), on_learnErrorUpdate(), setupErrorGraph(), and ~DialogNN().
The documentation for this class was generated from the following files:
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/VSA/dialognn.h
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/VSA/dialognn.cpp