SoilAnalyzer::Analyzer Class Reference
#include <analyzer.h>
Classes
struct Image_t
Public Types
typedef std::vector< Image_t > Images_t
Signals
void on_progressUpdate (int value)
void on_maxProgressUpdate (int value)
void on_AnalysisFinished ()
Public Member Functions
Analyzer (Images_t *snapshots, Sample *results, SoilSettings *settings)
Analyzer::Analyzer.
void Analyse ()
Analyzer::Analyse.
void Analyse (Images_t *snapshots, Sample *results, SoilSettings *settings)
float CalibrateSI (float SI, cv::Mat &img)
Public Attributes
bool PredictShape = true
float CurrentSIfactor = 0.0111915
bool SIfactorDet = false
Images_t * Snapshots = nullptr
SoilSettings * Settings = nullptr
Sample * Results
uint32_t MaxProgress = STARTING_ESTIMATE_PROGRESS
SoilMath::NN NeuralNet
Private Member Functions
void CalcMaxProgress ()
Analyzer::CalcMaxProgress.
void CalcMaxProgressAnalyze ()
void PrepImages ()
Analyzer::PrepImages.
void GetBW (std::vector< cv::Mat > &images, std::vector< cv::Mat > &BWvector)
Analyzer::GetBW.
void GetBW (cv::Mat &img, cv::Mat &BW)
Analyzer::GetBW.
void GetEnhancedInt (Images_t *snapshots, std::vector< cv::Mat > &intensityVector)
void GetEnhancedInt (cv::Mat &img, cv::Mat &intensity)
void GetParticles (std::vector< cv::Mat > &BW, Images_t *snapshots, Particle::ParticleVector_t &partPopulation)
Analyzer::GetParticles.
void GetParticlesFromBlobList (Vision::Segment::BlobList_t &bloblist, Image_t *snapshot, Particle::ParticleVector_t &partPopulation)
Analyzer::GetParticlesFromBlobList.
void CleanUpMatVector (std::vector< cv::Mat > &mv)
void CleanUpMatVector (Images_t *mv)
Analyzer::CleanUpMatVector.
void GetFFD (Particle::ParticleVector_t &particalPopulation)
Analyzer::GetFFD.
void GetPrediction (Particle::ParticleVector_t &particlePopulation)
Analyzer::GetPrediction.
Private Attributes
uint32_t currentProgress = 0
uint32_t currentParticleID = 0
double BinRanges [15]
SoilMath::FFT fft
Detailed Description
Definition at line 32 of file analyzer.h.
Member Typedef Documentation
typedef std::vector<Image_t> SoilAnalyzer::Analyzer::Images_t
Definition at line 45 of file analyzer.h.
Constructor & Destructor Documentation
SoilAnalyzer::Analyzer::Analyzer (Images_t * snapshots, Sample * results, SoilSettings * settings = nullptr)
Analyzer::Analyzer.
Parameters
snapshots
results
settings
Definition at line 18 of file analyzer.cpp.
References SoilMath::NN::LoadState(), NeuralNet, SoilAnalyzer::SoilSettings::NNlocation, Results, Settings, and Snapshots.
Member Function Documentation
void SoilAnalyzer::Analyzer::Analyse ()
Analyzer::Analyse.
Definition at line 65 of file analyzer.cpp.
References SoilAnalyzer::Sample::Angularity, BinRanges, CalcMaxProgress(), currentProgress, SoilAnalyzer::Sample::GetAngularityVector(), GetFFD(), GetPrediction(), SoilAnalyzer::Sample::GetPSDVector(), SoilAnalyzer::Sample::GetRoundnessVector(), SoilAnalyzer::Sample::IsLoadedFromDisk, SoilAnalyzer::Sample::isPreparedForAnalysis, on_AnalysisFinished(), on_progressUpdate(), SoilAnalyzer::Sample::ParticlePopulation, PredictShape, SoilAnalyzer::SoilSettings::PredictTheShape, PrepImages(), SoilAnalyzer::Sample::PSD, Results, SoilAnalyzer::Sample::Roundness, and Settings.
Referenced by Analyse(), VSAMainWindow::on_actionNewSample_triggered(), VSAMainWindow::on_Classification_changed(), and VSAMainWindow::on_particle_deleted().
void SoilAnalyzer::Analyzer::Analyse (Images_t * snapshots, Sample * results, SoilSettings * settings)
Definition at line 54 of file analyzer.cpp.
References Analyse(), Results, Settings, and Snapshots.
void SoilAnalyzer::Analyzer::CalcMaxProgress () [private]
Analyzer::CalcMaxProgress.
Definition at line 112 of file analyzer.cpp.
References SoilAnalyzer::SoilSettings::fillHoles, SoilAnalyzer::SoilSettings::ignorePartialBorderParticles, MaxProgress, SoilAnalyzer::SoilSettings::morphFilterType, Vision::MorphologicalFilter::NONE, on_maxProgressUpdate(), Settings, Snapshots, SoilAnalyzer::SoilSettings::useAdaptiveContrast, and SoilAnalyzer::SoilSettings::useBlur.
Referenced by Analyse().
void SoilAnalyzer::Analyzer::CalcMaxProgressAnalyze () [private]
Definition at line 136 of file analyzer.cpp.
References MaxProgress, on_maxProgressUpdate(), SoilAnalyzer::Sample::ParticlePopulation, Results, and STARTING_ESTIMATE_PROGRESS.
float SoilAnalyzer::Analyzer::CalibrateSI (float SI, cv::Mat & img)
Definition at line 388 of file analyzer.cpp.
References Vision::Segment::BlobList, Vision::Conversion::Convert(), Vision::Segment::ConvertToBW(), CurrentSIfactor, Vision::Segment::Dark, Vision::Segment::GetBlobList(), Vision::Conversion::Intensity, Vision::ImageProcessing::ProcessedImg, and Vision::Conversion::RGB.
Referenced by VSAMainWindow::on_actionCalibrate_triggered().
void SoilAnalyzer::Analyzer::CleanUpMatVector (std::vector< cv::Mat > & mv) [private]
Referenced by PrepImages().
void SoilAnalyzer::Analyzer::CleanUpMatVector (Images_t * mv) [private]
Analyzer::CleanUpMatVector.
Parameters
mv
Definition at line 101 of file analyzer.cpp.
void SoilAnalyzer::Analyzer::GetBW (std::vector< cv::Mat > & images, std::vector< cv::Mat > & BWvector) [private]
Analyzer::GetBW.
Parameters
images
BWvector
Definition at line 222 of file analyzer.cpp.
Referenced by PrepImages().
void SoilAnalyzer::Analyzer::GetBW (cv::Mat & img, cv::Mat & BW) [private]
Analyzer::GetBW.
Parameters
img
BW
Definition at line 236 of file analyzer.cpp.
References Vision::MorphologicalFilter::CLOSE, currentProgress, Vision::MorphologicalFilter::DILATE, Vision::MorphologicalFilter::ERODE, SoilAnalyzer::SoilSettings::fillHoles, Vision::Segment::FillHoles(), SoilAnalyzer::SoilSettings::filterMaskSize, SoilAnalyzer::SoilSettings::ignorePartialBorderParticles, SoilAnalyzer::SoilSettings::morphFilterType, Vision::MorphologicalFilter::NONE, on_progressUpdate(), Vision::MorphologicalFilter::OPEN, Vision::ImageProcessing::ProcessedImg, Vision::Segment::RemoveBorderBlobs(), Settings, SHOW_DEBUG_IMG, Vision::Segment::sigma, SoilAnalyzer::SoilSettings::sigmaFactor, SoilAnalyzer::SoilSettings::thresholdOffsetValue, and SoilAnalyzer::SoilSettings::typeOfObjectsSegmented.
void SoilAnalyzer::Analyzer::GetEnhancedInt (Images_t * snapshots, std::vector< cv::Mat > & intensityVector) [private]
Referenced by PrepImages().
void SoilAnalyzer::Analyzer::GetEnhancedInt (cv::Mat & img, cv::Mat & intensity) [private]
void SoilAnalyzer::Analyzer::GetFFD (Particle::ParticleVector_t & particalPopulation) [private]
Analyzer::GetFFD.
Parameters
particalPopulation
Definition at line 350 of file analyzer.cpp.
References currentProgress, EXCEPTION_NO_CONTOUR_FOUND_NR, fft, SoilMath::FFT::GetDescriptors(), SoilMath::Exception::MathException::id(), and on_progressUpdate().
Referenced by Analyse().
void SoilAnalyzer::Analyzer::GetParticles (std::vector< cv::Mat > & BW, Images_t * snapshots, Particle::ParticleVector_t & partPopulation) [private]
Analyzer::GetParticles.
Parameters
BW
snapshots
partPopulation
Definition at line 303 of file analyzer.cpp.
References Vision::Segment::BlobList, currentProgress, Vision::Segment::GetBlobList(), GetParticlesFromBlobList(), and on_progressUpdate().
Referenced by PrepImages().
void SoilAnalyzer::Analyzer::GetParticlesFromBlobList (Vision::Segment::BlobList_t & bloblist, Image_t * snapshot, Particle::ParticleVector_t & partPopulation) [private]
Analyzer::GetParticlesFromBlobList.
Parameters
bloblist
snapshot
edge
partPopulation
Definition at line 322 of file analyzer.cpp.
References SoilAnalyzer::Particle::BW, currentParticleID, SoilAnalyzer::Particle::Eccentricty, SoilAnalyzer::Particle::Edge, SoilAnalyzer::Analyzer::Image_t::FrontLight, Vision::Segment::GetEdgesEroding(), Vision::ImageProcessing::getOrientented(), SoilAnalyzer::Particle::ID, SoilAnalyzer::Particle::isPreparedForAnalysis, SoilAnalyzer::Particle::PixelArea, Vision::ImageProcessing::ProcessedImg, SoilAnalyzer::Particle::RGB, Vision::ImageProcessing::RotateImg(), SoilAnalyzer::Particle::SetRoundness(), SoilAnalyzer::Analyzer::Image_t::SIPixelFactor, and SoilAnalyzer::Particle::SIPixelFactor.
Referenced by GetParticles().
void SoilAnalyzer::Analyzer::GetPrediction (Particle::ParticleVector_t & particlePopulation) [private]
Analyzer::GetPrediction.
Parameters
particlePopulation
Definition at line 373 of file analyzer.cpp.
References SoilMath::NN::GetInputNeurons(), NeuralNet, and SoilMath::NN::Predict().
Referenced by Analyse().
void SoilAnalyzer::Analyzer::on_AnalysisFinished () [signal]
Referenced by Analyse().
void SoilAnalyzer::Analyzer::on_maxProgressUpdate (int value) [signal]
Referenced by CalcMaxProgress(), and CalcMaxProgressAnalyze().
void SoilAnalyzer::Analyzer::on_progressUpdate (int value) [signal]
Referenced by Analyse(), GetBW(), GetFFD(), and GetParticles().
void SoilAnalyzer::Analyzer::PrepImages () [private]
Analyzer::PrepImages.
Definition at line 33 of file analyzer.cpp.
References CleanUpMatVector(), EXCEPTION_NO_SNAPSHOTS, EXCEPTION_NO_SNAPSHOTS_NR, GetBW(), GetEnhancedInt(), GetParticles(), SoilAnalyzer::Sample::isPreparedForAnalysis, SoilAnalyzer::Sample::ParticlePopulation, Results, and Snapshots.
Referenced by Analyse().
Member Data Documentation
double SoilAnalyzer::Analyzer::BinRanges[15] [private]
Initial value:
{0.0, 0.038, 0.045, 0.063, 0.075, 0.09, 0.125, 0.18,
                      0.25, 0.355, 0.5, 0.71, 1.0, 1.4, 2.0}
Definition at line 69 of file analyzer.h.
Referenced by Analyse().
uint32_t SoilAnalyzer::Analyzer::currentParticleID = 0 [private]
Definition at line 68 of file analyzer.h.
Referenced by GetParticlesFromBlobList().
uint32_t SoilAnalyzer::Analyzer::currentProgress = 0 [private]
Definition at line 67 of file analyzer.h.
Referenced by Analyse(), GetBW(), GetFFD(), and GetParticles().
float SoilAnalyzer::Analyzer::CurrentSIfactor = 0.0111915
Definition at line 37 of file analyzer.h.
Referenced by CalibrateSI(), and VSAMainWindow::TakeSnapShots().
SoilMath::FFT SoilAnalyzer::Analyzer::fft [private]
Definition at line 72 of file analyzer.h.
Referenced by GetFFD().
uint32_t SoilAnalyzer::Analyzer::MaxProgress = STARTING_ESTIMATE_PROGRESS
Definition at line 57 of file analyzer.h.
Referenced by CalcMaxProgress(), CalcMaxProgressAnalyze(), and VSAMainWindow::VSAMainWindow().
SoilMath::NN SoilAnalyzer::Analyzer::NeuralNet
Definition at line 59 of file analyzer.h.
Referenced by Analyzer(), GetPrediction(), VSAMainWindow::on_actionNeuralNet_triggered(), and VSAMainWindow::VSAMainWindow().
bool SoilAnalyzer::Analyzer::PredictShape = true
Definition at line 36 of file analyzer.h.
Referenced by Analyse(), and VSAMainWindow::on_actionUseLearning_toggled().
Sample* SoilAnalyzer::Analyzer::Results
Definition at line 49 of file analyzer.h.
Referenced by Analyse(), Analyzer(), CalcMaxProgressAnalyze(), VSAMainWindow::on_actionLoadSample_triggered(), and PrepImages().
SoilSettings* SoilAnalyzer::Analyzer::Settings = nullptr
Definition at line 47 of file analyzer.h.
Referenced by Analyse(), Analyzer(), CalcMaxProgress(), and GetBW().
bool SoilAnalyzer::Analyzer::SIfactorDet = false
Definition at line 38 of file analyzer.h.
Referenced by VSAMainWindow::TakeSnapShots().
Images_t* SoilAnalyzer::Analyzer::Snapshots = nullptr
Definition at line 46 of file analyzer.h.
Referenced by Analyse(), Analyzer(), CalcMaxProgress(), and PrepImages().
The documentation for this class was generated from the following files:
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/SoilAnalyzer/analyzer.h
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/SoilAnalyzer/analyzer.cpp