QCPItemPixmap Class Reference
An arbitrary pixmap.
#include <qcustomplot.h>
Public Member Functions
QCPItemPixmap (QCustomPlot *parentPlot)
virtual ~QCPItemPixmap ()
QPixmap pixmap () const
bool scaled () const
Qt::AspectRatioMode aspectRatioMode () const
Qt::TransformationMode transformationMode () const
QPen pen () const
QPen selectedPen () const
void setPixmap (const QPixmap &pixmap)
void setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio, Qt::TransformationMode transformationMode=Qt::SmoothTransformation)
void setPen (const QPen &pen)
void setSelectedPen (const QPen &pen)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Public Attributes
QCPItemPosition *const topLeft
QCPItemPosition *const bottomRight
QCPItemAnchor *const top
QCPItemAnchor *const topRight
QCPItemAnchor *const right
QCPItemAnchor *const bottom
QCPItemAnchor *const bottomLeft
QCPItemAnchor *const left
Protected Types
enum AnchorIndex {
*
aiTop,
aiTopRight,
aiRight,
aiBottom,
*
aiBottomLeft,
aiLeft
 }
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual QPointF anchorPixelPoint (int anchorId) const
void updateScaledPixmap (QRect finalRect=QRect(), bool flipHorz=false, bool flipVert=false)
QRect getFinalRect (bool *flippedHorz=0, bool *flippedVert=0) const
QPen mainPen () const
Protected Attributes
QPixmap mPixmap
QPixmap mScaledPixmap
bool mScaled
Qt::AspectRatioMode mAspectRatioMode
Qt::TransformationMode mTransformationMode
QPen mPen
QPen mSelectedPen
Additional Inherited Members
Detailed Description
An arbitrary pixmap.
 anchors, solid blue discs are positions."
It has two positions, topLeft and bottomRight, which define the rectangle the pixmap will be drawn in. Depending on the scale setting (setScaled), the pixmap will be either scaled to fit the rectangle or be drawn aligned to the topLeft position.
If scaling is enabled and topLeft is further to the bottom/right than bottomRight (as shown on the right side of the example image), the pixmap will be flipped in the respective orientations.
Definition at line 4056 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemPixmap::AnchorIndex [protected]
Enumerator
aiTop
aiTopRight
aiRight
aiBottom
aiBottomLeft
aiLeft
Definition at line 4102 of file qcustomplot.h.
                   {
    aiTop,
    aiTopRight,
    aiRight,
    aiBottom,
    aiBottomLeft,
    aiLeft
  };
Constructor & Destructor Documentation
QCPItemPixmap::QCPItemPixmap (QCustomPlot * parentPlot)
Creates a rectangle item and sets default values.
The constructed item can be added to the plot with QCustomPlot::addItem.
Definition at line 25239 of file qcustomplot.cpp.
References bottomRight, QCPItemPosition::setCoords(), setPen(), setScaled(), setSelectedPen(), and topLeft.
    : QCPAbstractItem(parentPlot),
      topLeft(createPosition(QLatin1String("topLeft"))),
      bottomRight(createPosition(QLatin1String("bottomRight"))),
      top(createAnchor(QLatin1String("top"), aiTop)),
      topRight(createAnchor(QLatin1String("topRight"),
      aiTopRight)),
      right(createAnchor(QLatin1String("right"), aiRight)),
      bottom(createAnchor(QLatin1String("bottom"), aiBottom)),
      bottomLeft(createAnchor(QLatin1String("bottomLeft"),
      aiBottomLeft)),
      left(createAnchor(QLatin1String("left"), aiLeft)) {
  topLeft->setCoords(0, 1);
  bottomRight->setCoords(1, 0);
  setPen(Qt::NoPen);
  setSelectedPen(QPen(Qt::blue));
  setScaled(false, Qt::KeepAspectRatio, Qt::SmoothTransformation);
}
QCPItemPixmap::~QCPItemPixmap () [virtual]
Definition at line 25257 of file qcustomplot.cpp.
{}
Member Function Documentation
QPointF QCPItemPixmap::anchorPixelPoint (int anchorId) const [protected], [virtual]
Reimplemented from QCPAbstractItem.
Definition at line 25326 of file qcustomplot.cpp.
References aiBottom, aiBottomLeft, aiLeft, aiRight, aiTop, aiTopRight, getFinalRect(), and rect.
                                                          {
  bool flipHorz;
  bool flipVert;
  QRect rect = getFinalRect(&flipHorz, &flipVert);
  // we actually want denormal rects (negative width/height) here, so restore
  // the flipped state:
  if (flipHorz)
    rect.adjust(rect.width(), 0, -rect.width(), 0);
  if (flipVert)
    rect.adjust(0, rect.height(), 0, -rect.height());
  switch (anchorId) {
  case aiTop:
    return (rect.topLeft() + rect.topRight()) * 0.5;
  case aiTopRight:
    return rect.topRight();
  case aiRight:
    return (rect.topRight() + rect.bottomRight()) * 0.5;
  case aiBottom:
    return (rect.bottomLeft() + rect.bottomRight()) * 0.5;
  case aiBottomLeft:
    return rect.bottomLeft();
  case aiLeft:
    return (rect.topLeft() + rect.bottomLeft()) * 0.5;
    ;
  }
  qDebug() << Q_FUNC_INFO << "invalid anchorId" << anchorId;
  return QPointF();
}
Qt::AspectRatioMode QCPItemPixmap::aspectRatioMode () const [inline]
Definition at line 4073 of file qcustomplot.h.
Referenced by setScaled().
{ return mAspectRatioMode; }
void QCPItemPixmap::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractItem.
Definition at line 25307 of file qcustomplot.cpp.
References QCPAbstractItem::clipRect(), getFinalRect(), mainPen(), mPixmap, mScaled, mScaledPixmap, pen(), rect, QCPPainter::setPen(), and updateScaledPixmap().
                                            {
  bool flipHorz = false;
  bool flipVert = false;
  QRect rect = getFinalRect(&flipHorz, &flipVert);
  double clipPad = mainPen().style() == Qt::NoPen ? 0 : mainPen().widthF();
  QRect boundingRect = rect.adjusted(-clipPad, -clipPad, clipPad, clipPad);
  if (boundingRect.intersects(clipRect())) {
    updateScaledPixmap(rect, flipHorz, flipVert);
    painter->drawPixmap(rect.topLeft(), mScaled ? mScaledPixmap :
      mPixmap);
    QPen pen = mainPen();
    if (pen.style() != Qt::NoPen) {
      painter->setPen(pen);
      painter->setBrush(Qt::NoBrush);
      painter->drawRect(rect);
    }
  }
}
QRect QCPItemPixmap::getFinalRect (bool * flippedHorz = 0, bool * flippedVert = 0) const [protected]
Definition at line 25415 of file qcustomplot.cpp.
References bottomRight, mAspectRatioMode, mPixmap, mScaled, QCPItemPosition::pixelPoint(), and topLeft.
Referenced by anchorPixelPoint(), draw(), selectTest(), and updateScaledPixmap().
                                                                            {
  QRect result;
  bool flipHorz = false;
  bool flipVert = false;
  QPoint p1 = topLeft->pixelPoint().toPoint();
  QPoint p2 = bottomRight->pixelPoint().toPoint();
  if (p1 == p2)
    return QRect(p1, QSize(0, 0));
  if (mScaled) {
    QSize newSize = QSize(p2.x() - p1.x(), p2.y() - p1.y());
    QPoint topLeft = p1;
    if (newSize.width() < 0) {
      flipHorz = true;
      newSize.rwidth() *= -1;
      topLeft.setX(p2.x());
    }
    if (newSize.height() < 0) {
      flipVert = true;
      newSize.rheight() *= -1;
      topLeft.setY(p2.y());
    }
    QSize scaledSize = mPixmap.size();
    scaledSize.scale(newSize, mAspectRatioMode);
    result = QRect(topLeft, scaledSize);
  } else {
    result = QRect(p1, mPixmap.size());
  }
  if (flippedHorz)
    *flippedHorz = flipHorz;
  if (flippedVert)
    *flippedVert = flipVert;
  return result;
}
QPen QCPItemPixmap::mainPen () const [protected]
Definition at line 25455 of file qcustomplot.cpp.
References mPen, QCPAbstractItem::mSelected, and mSelectedPen.
Referenced by draw().
{ return mSelected ? mSelectedPen : mPen; }
QPen QCPItemPixmap::pen () const [inline]
Definition at line 4077 of file qcustomplot.h.
Referenced by draw(), setPen(), and setSelectedPen().
{ return mPen; }
QPixmap QCPItemPixmap::pixmap () const [inline]
Definition at line 4071 of file qcustomplot.h.
Referenced by setPixmap().
{ return mPixmap; }
bool QCPItemPixmap::scaled () const [inline]
Definition at line 4072 of file qcustomplot.h.
Referenced by setScaled().
{ return mScaled; }
QPen QCPItemPixmap::selectedPen () const [inline]
Definition at line 4078 of file qcustomplot.h.
{ return mSelectedPen; }
double QCPItemPixmap::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractItem.
Definition at line 25297 of file qcustomplot.cpp.
References getFinalRect(), QCPAbstractItem::mSelectable, and QCPAbstractItem::rectSelectTest().
                                                          {
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  return rectSelectTest(getFinalRect(), pos, true);
}
void QCPItemPixmap::setPen (const QPen & pen)
Sets the pen that will be used to draw a border around the pixmap.
See also
setSelectedPen, setBrush
Definition at line 25286 of file qcustomplot.cpp.
References mPen, and pen().
Referenced by QCPItemPixmap().
{ mPen = pen; }
void QCPItemPixmap::setPixmap (const QPixmap & pixmap)
Sets the pixmap that will be displayed.
Definition at line 25262 of file qcustomplot.cpp.
References mPixmap, and pixmap().
                                                   {
  mPixmap = pixmap;
  if (mPixmap.isNull())
    qDebug() << Q_FUNC_INFO << "pixmap is null";
}
void QCPItemPixmap::setScaled (bool scaled, Qt::AspectRatioMode aspectRatioMode = Qt::KeepAspectRatio, Qt::TransformationMode transformationMode = Qt::SmoothTransformation)
Sets whether the pixmap will be scaled to fit the rectangle defined by the topLeft and bottomRight positions.
Definition at line 25273 of file qcustomplot.cpp.
References aspectRatioMode(), mAspectRatioMode, mScaled, mTransformationMode, scaled(), transformationMode(), and updateScaledPixmap().
Referenced by QCPItemPixmap().
                                                                       {
  mScaled = scaled;
  mAspectRatioMode = aspectRatioMode;
  mTransformationMode = transformationMode;
  updateScaledPixmap();
}
void QCPItemPixmap::setSelectedPen (const QPen & pen)
Sets the pen that will be used to draw a border around the pixmap when selected
See also
setPen, setSelected
Definition at line 25294 of file qcustomplot.cpp.
References mSelectedPen, and pen().
Referenced by QCPItemPixmap().
{ mSelectedPen = pen; }
Qt::TransformationMode QCPItemPixmap::transformationMode () const [inline]
Definition at line 4074 of file qcustomplot.h.
Referenced by setScaled().
                                                  {
    return mTransformationMode;
  }
void QCPItemPixmap::updateScaledPixmap (QRect finalRect = QRect(), bool flipHorz = false, bool flipVert = false) [protected]
Definition at line 25375 of file qcustomplot.cpp.
References getFinalRect(), mAspectRatioMode, mPixmap, mScaled, mScaledPixmap, and mTransformationMode.
Referenced by draw(), and setScaled().
                                                      {
  if (mPixmap.isNull())
    return;
  if (mScaled) {
    if (finalRect.isNull())
      finalRect = getFinalRect(&flipHorz, &flipVert);
    if (finalRect.size() != mScaledPixmap.size()) {
      mScaledPixmap = mPixmap.scaled(finalRect.size(),
      mAspectRatioMode,
                                     mTransformationMode);
      if (flipHorz || flipVert)
        mScaledPixmap = QPixmap::fromImage(
            mScaledPixmap.toImage().mirrored(flipHorz, flipVert));
    }
  } else if (!mScaledPixmap.isNull())
    mScaledPixmap = QPixmap();
}
Member Data Documentation
QCPItemAnchor* const QCPItemPixmap::bottom
Definition at line 4097 of file qcustomplot.h.
QCPItemAnchor* const QCPItemPixmap::bottomLeft
Definition at line 4098 of file qcustomplot.h.
QCPItemPosition* const QCPItemPixmap::bottomRight
Definition at line 4093 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
QCPItemAnchor* const QCPItemPixmap::left
Definition at line 4099 of file qcustomplot.h.
Qt::AspectRatioMode QCPItemPixmap::mAspectRatioMode [protected]
Definition at line 4115 of file qcustomplot.h.
Referenced by getFinalRect(), setScaled(), and updateScaledPixmap().
QPen QCPItemPixmap::mPen [protected]
Definition at line 4117 of file qcustomplot.h.
Referenced by mainPen(), and setPen().
QPixmap QCPItemPixmap::mPixmap [protected]
Definition at line 4112 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setPixmap(), and updateScaledPixmap().
bool QCPItemPixmap::mScaled [protected]
Definition at line 4114 of file qcustomplot.h.
Referenced by draw(), getFinalRect(), setScaled(), and updateScaledPixmap().
QPixmap QCPItemPixmap::mScaledPixmap [protected]
Definition at line 4113 of file qcustomplot.h.
Referenced by draw(), and updateScaledPixmap().
QPen QCPItemPixmap::mSelectedPen [protected]
Definition at line 4117 of file qcustomplot.h.
Referenced by mainPen(), and setSelectedPen().
Qt::TransformationMode QCPItemPixmap::mTransformationMode [protected]
Definition at line 4116 of file qcustomplot.h.
Referenced by setScaled(), and updateScaledPixmap().
QCPItemAnchor* const QCPItemPixmap::right
Definition at line 4096 of file qcustomplot.h.
QCPItemAnchor* const QCPItemPixmap::top
Definition at line 4094 of file qcustomplot.h.
QCPItemPosition* const QCPItemPixmap::topLeft
Definition at line 4092 of file qcustomplot.h.
Referenced by getFinalRect(), and QCPItemPixmap().
QCPItemAnchor* const QCPItemPixmap::topRight
Definition at line 4095 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp