QCPPlotTitle Class Reference
A layout element displaying a plot title text.
#include <qcustomplot.h>
Signals
void selectionChanged (bool selected)
void selectableChanged (bool selectable)
Public Member Functions
QCPPlotTitle (QCustomPlot *parentPlot)
QCPPlotTitle (QCustomPlot *parentPlot, const QString &text)
QString text () const
QFont font () const
QColor textColor () const
QFont selectedFont () const
QColor selectedTextColor () const
bool selectable () const
bool selected () const
void setText (const QString &text)
void setFont (const QFont &font)
void setTextColor (const QColor &color)
void setSelectedFont (const QFont &font)
void setSelectedTextColor (const QColor &color)
Q_SLOT void setSelectable (bool selectable)
Q_SLOT void setSelected (bool selected)
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Protected Member Functions
virtual void applyDefaultAntialiasingHint (QCPPainter *painter) const
virtual void draw (QCPPainter *painter)
virtual QSize minimumSizeHint () const
virtual QSize maximumSizeHint () const
virtual void selectEvent (QMouseEvent *event, bool additive, const QVariant &details, bool *selectionStateChanged)
virtual void deselectEvent (bool *selectionStateChanged)
QFont mainFont () const
QColor mainTextColor () const
Protected Attributes
QString mText
QFont mFont
QColor mTextColor
QFont mSelectedFont
QColor mSelectedTextColor
QRect mTextBoundingRect
bool mSelectable
bool mSelected
Additional Inherited Members
Detailed Description
A layout element displaying a plot title text.
The text may be specified with setText, theformatting can be controlled with setFont and setTextColor.
A plot title can be added as follows:
 Since a plot title is a common requirement, QCustomPlot offers specialized selection signals for easy interaction with QCPPlotTitle. If a layout element of type QCPPlotTitle is clicked, the signal QCustomPlot::titleClick is emitted. A double click emits the QCustomPlot::titleDoubleClick signal.
Definition at line 2293 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPPlotTitle::QCPPlotTitle (QCustomPlot * parentPlot) [explicit]
Creates a new QCPPlotTitle instance and sets default values. The initial text is empty (setText).
To set the title text in the constructor, rather use QCPPlotTitle(QCustomPlot *parentPlot, const QString &text).
Definition at line 13507 of file qcustomplot.cpp.
References QCustomPlot::currentLayer(), mFont, mSelectedFont, QCPLayerable::setLayer(), and QCPLayoutElement::setMargins().
                                                  :
  QCPLayoutElement(parentPlot),
  mFont(QFont(QLatin1String("sans serif"), 13*1.5, QFont::Bold)),
  mTextColor(Qt::black),
  mSelectedFont(QFont(QLatin1String("sans serif"), 13*1.6, QFont::Bold)),
  mSelectedTextColor(Qt::blue),
  mSelectable(false),
  mSelected(false)
{
  if (parentPlot)
  {
    setLayer(parentPlot->currentLayer());
    mFont = QFont(parentPlot->font().family(), parentPlot->font().pointSize()*1.5, QFont::Bold);
    mSelectedFont = QFont(parentPlot->font().family(), parentPlot->font().pointSize()*1.6,
      QFont::Bold);
  }
  setMargins(QMargins(5, 5, 5, 0));
}
QCPPlotTitle::QCPPlotTitle (QCustomPlot * parentPlot, const QString & text) [explicit]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Creates a new QCPPlotTitle instance and sets default values. The initial text is set to text.
Definition at line 13529 of file qcustomplot.cpp.
References QCPLayerable::setLayer(), and QCPLayoutElement::setMargins().
                                                                       :
  QCPLayoutElement(parentPlot),
  mText(text),
  mFont(QFont(parentPlot->font().family(), parentPlot->font().pointSize()*1.5, QFont::Bold)),
  mTextColor(Qt::black),
  mSelectedFont(QFont(parentPlot->font().family(), parentPlot->font().pointSize()*1.6,
      QFont::Bold)),
  mSelectedTextColor(Qt::blue),
  mSelectable(false),
  mSelected(false)
{
  setLayer(QLatin1String("axes"));
  setMargins(QMargins(5, 5, 5, 0));
}
Member Function Documentation
void QCPPlotTitle::applyDefaultAntialiasingHint (QCPPainter * painter) const [protected], [virtual]
Reimplemented from QCPLayoutElement.
Definition at line 13625 of file qcustomplot.cpp.
References QCP::aeNone, QCPLayerable::applyAntialiasingHint(), and QCPLayerable::mAntialiased.
{
  applyAntialiasingHint(painter, mAntialiased,
      QCP::aeNone);
}
void QCPPlotTitle::deselectEvent (bool * selectionStateChanged) [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 13673 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
{
  if (mSelectable)
  {
    bool selBefore = mSelected;
    setSelected(false);
    if (selectionStateChanged)
      *selectionStateChanged = mSelected != selBefore;
  }
}
void QCPPlotTitle::draw (QCPPainter * painter) [protected], [virtual]
Reimplemented from QCPLayoutElement.
Definition at line 13631 of file qcustomplot.cpp.
References mainFont(), mainTextColor(), QCPLayoutElement::mRect, mText, mTextBoundingRect, and QCPPainter::setPen().
{
  painter->setFont(mainFont());
  painter->setPen(QPen(mainTextColor()));
  painter->drawText(mRect, Qt::AlignCenter, mText, &mTextBoundingRect);
}
QFont QCPPlotTitle::font () const [inline]
Definition at line 2311 of file qcustomplot.h.
Referenced by setFont(), and setSelectedFont().
{ return mFont; }
QFont QCPPlotTitle::mainFont () const [protected]
Definition at line 13702 of file qcustomplot.cpp.
References mFont, mSelected, and mSelectedFont.
Referenced by draw().
{
  return mSelected ? mSelectedFont : mFont;
}
QColor QCPPlotTitle::mainTextColor () const [protected]
Definition at line 13712 of file qcustomplot.cpp.
References mSelected, mSelectedTextColor, and mTextColor.
Referenced by draw().
{
  return mSelected ? mSelectedTextColor : mTextColor;
}
QSize QCPPlotTitle::maximumSizeHint () const [protected], [virtual]
Returns the maximum size this layout element (the inner rect) may be expanded to.
if a maximum size (setMaximumSize) was not set manually, parent layouts consult this function to determine the maximum allowed size of this layout element. (A manual maximum size is considered set if it is smaller than Qt's QWIDGETSIZE_MAX.)
Reimplemented from QCPLayoutElement.
Definition at line 13649 of file qcustomplot.cpp.
References mFont, QCPLayoutElement::mMargins, and mText.
{
  QFontMetrics metrics(mFont);
  QSize result = metrics.boundingRect(0, 0, 0, 0, Qt::AlignCenter, mText).size();
  result.rheight() += mMargins.top() + mMargins.bottom();
  result.setWidth(QWIDGETSIZE_MAX);
  return result;
}
QSize QCPPlotTitle::minimumSizeHint () const [protected], [virtual]
Returns the minimum size this layout element (the inner rect) may be compressed to.
if a minimum size (setMinimumSize) was not set manually, parent layouts consult this function to determine the minimum allowed size of this layout element. (A manual minimum size is considered set if it is non-zero.)
Reimplemented from QCPLayoutElement.
Definition at line 13639 of file qcustomplot.cpp.
References mFont, QCPLayoutElement::mMargins, and mText.
{
  QFontMetrics metrics(mFont);
  QSize result = metrics.boundingRect(0, 0, 0, 0, Qt::AlignCenter, mText).size();
  result.rwidth() += mMargins.left() + mMargins.right();
  result.rheight() += mMargins.top() + mMargins.bottom();
  return result;
}
bool QCPPlotTitle::selectable () const [inline]
Definition at line 2315 of file qcustomplot.h.
Referenced by setSelectable().
{ return mSelectable; }
void QCPPlotTitle::selectableChanged (bool selectable) [signal]
Referenced by setSelectable().
bool QCPPlotTitle::selected () const [inline]
Definition at line 2316 of file qcustomplot.h.
Referenced by setSelected().
{ return mSelected; }
QFont QCPPlotTitle::selectedFont () const [inline]
Definition at line 2313 of file qcustomplot.h.
{ return mSelectedFont; }
QColor QCPPlotTitle::selectedTextColor () const [inline]
Definition at line 2314 of file qcustomplot.h.
{ return mSelectedTextColor; }
void QCPPlotTitle::selectEvent (QMouseEvent * event, bool additive, const QVariant & details, bool * selectionStateChanged) [protected], [virtual]
Reimplemented from QCPLayerable.
Definition at line 13659 of file qcustomplot.cpp.
References mSelectable, mSelected, and setSelected().
{
  Q_UNUSED(event)
  Q_UNUSED(details)
  if (mSelectable)
  {
    bool selBefore = mSelected;
    setSelected(additive ? !mSelected : true);
    if (selectionStateChanged)
      *selectionStateChanged = mSelected != selBefore;
  }
}
void QCPPlotTitle::selectionChanged (bool selected) [signal]
This signal is emitted when the selection state has changed to selected, either by user interaction or by a direct call to setSelected.
See also
setSelected, setSelectable
Referenced by setSelected().
double QCPPlotTitle::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
Layout elements are sensitive to events inside their outer rect. If pos is within the outer rect, this method returns a value corresponding to 0.99 times the parent plot's selection tolerance. However, layout elements are not selectable by default. So if onlySelectable is true, -1.0 is returned.
See QCPLayerable::selectTest for a general explanation of this virtual method.
QCPLayoutElement subclasses may reimplement this method to provide more specific selection test behaviour.
Reimplemented from QCPLayoutElement.
Definition at line 13685 of file qcustomplot.cpp.
References QCPLayerable::mParentPlot, mSelectable, mTextBoundingRect, and QCustomPlot::selectionTolerance().
{
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  
  if (mTextBoundingRect.contains(pos.toPoint()))
    return mParentPlot->selectionTolerance()*0.99;
  else
    return -1;
}
void QCPPlotTitle::setFont (const QFont & font)
Sets the font of the title text.
See also
setTextColor, setSelectedFont
Definition at line 13558 of file qcustomplot.cpp.
References font(), and mFont.
{
  mFont = font;
}
void QCPPlotTitle::setSelectable (bool selectable)
Sets whether the user may select this plot title to selectable.
Note that even when selectable is set to false, the selection state may be changed programmatically via setSelected.
Definition at line 13599 of file qcustomplot.cpp.
References mSelectable, selectable(), and selectableChanged().
{
  if (mSelectable != selectable)
  {
    mSelectable = selectable;
    emit selectableChanged(mSelectable);
  }
}
void QCPPlotTitle::setSelected (bool selected)
Sets the selection state of this plot title to selected. If the selection has changed, selectionChanged is emitted.
Note that this function can change the selection state independently of the current setSelectable state.
Definition at line 13615 of file qcustomplot.cpp.
References mSelected, selected(), and selectionChanged().
Referenced by deselectEvent(), and selectEvent().
{
  if (mSelected != selected)
  {
    mSelected = selected;
    emit selectionChanged(mSelected);
  }
}
void QCPPlotTitle::setSelectedFont (const QFont & font)
Sets the font of the title text that will be used if the plot title is selected (setSelected).
See also
setFont
Definition at line 13578 of file qcustomplot.cpp.
References font(), and mSelectedFont.
{
  mSelectedFont = font;
}
void QCPPlotTitle::setSelectedTextColor (const QColor & color)
Sets the color of the title text that will be used if the plot title is selected (setSelected).
See also
setTextColor
Definition at line 13588 of file qcustomplot.cpp.
References mSelectedTextColor.
{
  mSelectedTextColor = color;
}
void QCPPlotTitle::setText (const QString & text)
Sets the text that will be displayed to text. Multiple lines can be created by insertion of `\n`.
See also
setFont, setTextColor
Definition at line 13548 of file qcustomplot.cpp.
References mText, and text().
{
  mText = text;
}
void QCPPlotTitle::setTextColor (const QColor & color)
Sets the color of the title text.
See also
setFont, setSelectedTextColor
Definition at line 13568 of file qcustomplot.cpp.
References mTextColor.
{
  mTextColor = color;
}
QString QCPPlotTitle::text () const [inline]
Definition at line 2310 of file qcustomplot.h.
Referenced by setText().
{ return mText; }
QColor QCPPlotTitle::textColor () const [inline]
Definition at line 2312 of file qcustomplot.h.
{ return mTextColor; }
Member Data Documentation
QFont QCPPlotTitle::mFont [protected]
Definition at line 2337 of file qcustomplot.h.
Referenced by mainFont(), maximumSizeHint(), minimumSizeHint(), QCPPlotTitle(), and setFont().
bool QCPPlotTitle::mSelectable [protected]
Definition at line 2342 of file qcustomplot.h.
Referenced by deselectEvent(), selectEvent(), selectTest(), and setSelectable().
bool QCPPlotTitle::mSelected [protected]
Definition at line 2342 of file qcustomplot.h.
Referenced by deselectEvent(), mainFont(), mainTextColor(), selectEvent(), and setSelected().
QFont QCPPlotTitle::mSelectedFont [protected]
Definition at line 2339 of file qcustomplot.h.
Referenced by mainFont(), QCPPlotTitle(), and setSelectedFont().
QColor QCPPlotTitle::mSelectedTextColor [protected]
Definition at line 2340 of file qcustomplot.h.
Referenced by mainTextColor(), and setSelectedTextColor().
QString QCPPlotTitle::mText [protected]
Definition at line 2336 of file qcustomplot.h.
Referenced by draw(), maximumSizeHint(), minimumSizeHint(), and setText().
QRect QCPPlotTitle::mTextBoundingRect [protected]
Definition at line 2341 of file qcustomplot.h.
Referenced by draw(), and selectTest().
QColor QCPPlotTitle::mTextColor [protected]
Definition at line 2338 of file qcustomplot.h.
Referenced by mainTextColor(), and setTextColor().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp