VSAMainWindow Class Reference
#include <vsamainwindow.h>
Public Member Functions
VSAMainWindow (QWidget *parent=0)
~VSAMainWindow ()
Private Slots
void on_actionSettings_triggered ()
void on_analyzer_finished ()
void on_actionNeuralNet_triggered ()
void on_actionNewSample_triggered ()
void on_actionSaveSample_triggered ()
void on_actionLoadSample_triggered ()
void on_actionUseLearning_toggled (bool arg1)
void on_actionCalibrate_triggered ()
void on_Classification_changed (int newValue)
void on_particle_deleted ()
void on_actionAutomatic_Shape_Pediction_triggered (bool checked)
void on_reset_graph (QMouseEvent *e)
void on_actionReport_Generator_triggered ()
void on_particleChanged (int newPart)
void on_PSD_contextMenuRequest (QPoint point)
void on_compare_against ()
void on_restore_PSD ()
Private Member Functions
void SetPSDgraph ()
void setRoundnessHistogram ()
void setAngularityHistogram ()
void setAmpgraph ()
void TakeSnapShots ()
Private Attributes
Ui::VSAMainWindow * ui
DialogSettings * settingsWindow = nullptr
DialogNN * nnWindow = nullptr
QProgressBar * Progress
QErrorMessage * CamError = nullptr
QMessageBox * SaveMeMessage = nullptr
QMessageBox * BacklightMessage = nullptr
QMessageBox * ShakeItBabyMessage = nullptr
QReportGenerator * ReportGenWindow = nullptr
SoilAnalyzer::SoilSettings * Settings = nullptr
Hardware::Microscope * Microscope = nullptr
SoilAnalyzer::Sample * Sample = nullptr
SoilAnalyzer::Analyzer * Analyzer = nullptr
SoilAnalyzer::Analyzer::Images_t * Images = nullptr
QCPBars * RoundnessBars = nullptr
QCPBars * AngularityBars = nullptr
std::vector< double > PSDTicks
QVector< QString > RoundnessCat = {`High`, `Medium`, `Low`}
std::vector< double > RoundnessTicks = {1, 2, 3}
QVector< QString > AngularityCat
std::vector< double > AngularityTicks = {1, 2, 3, 4, 5, 6}
bool ParticleDisplayerFilled = false
Detailed Description
Definition at line 27 of file vsamainwindow.h.
Constructor & Destructor Documentation
VSAMainWindow::VSAMainWindow (QWidget * parent = 0) [explicit]
Definition at line 4 of file vsamainwindow.cpp.
References Analyzer, AngularityBars, AngularityCat, AngularityTicks, BacklightMessage, CamError, SoilAnalyzer::SoilSettings::defaultWebcam, EXCEPTION_NOCAMS_NR, EXCEPTION_OPENCAM_NR, Hardware::Exception::MicroscopeException::id(), Images, SoilAnalyzer::SoilSettings::LoadSettings(), SoilAnalyzer::Analyzer::MaxProgress, SoilAnalyzer::Analyzer::NeuralNet, nnWindow, on_analyzer_finished(), on_Classification_changed(), on_particle_deleted(), on_particleChanged(), on_PSD_contextMenuRequest(), on_reset_graph(), SoilAnalyzer::SoilSettings::PredictTheShape, Progress, PSDTicks, RoundnessBars, RoundnessCat, RoundnessTicks, Sample, SaveMeMessage, SoilAnalyzer::SoilSettings::selectedResolution, Settings, settingsWindow, ShakeItBabyMessage, and ui.
VSAMainWindow::~VSAMainWindow ()
Definition at line 254 of file vsamainwindow.cpp.
References Analyzer, BacklightMessage, CamError, Images, Microscope, nnWindow, Sample, SaveMeMessage, Settings, settingsWindow, ShakeItBabyMessage, and ui.
Member Function Documentation
void VSAMainWindow::on_actionAutomatic_Shape_Pediction_triggered (bool checked) [private], [slot]
Definition at line 541 of file vsamainwindow.cpp.
References SoilAnalyzer::SoilSettings::PredictTheShape, and Settings.
void VSAMainWindow::on_actionCalibrate_triggered () [private], [slot]
Definition at line 516 of file vsamainwindow.cpp.
References Analyzer, and SoilAnalyzer::Analyzer::CalibrateSI().
Referenced by TakeSnapShots().
void VSAMainWindow::on_actionLoadSample_triggered () [private], [slot]
Definition at line 475 of file vsamainwindow.cpp.
References Analyzer, SoilAnalyzer::Sample::Angularity, SoilAnalyzer::Sample::ChangesSinceLastSave, SoilMath::Stats< T1, T2, T3 >::Data, SoilAnalyzer::Sample::GetAngularityVector(), SoilAnalyzer::Sample::GetPSDVector(), SoilAnalyzer::Sample::GetRoundnessVector(), Images, SoilAnalyzer::Sample::Load(), on_analyzer_finished(), ParticleDisplayerFilled, SoilAnalyzer::Sample::PSD, SoilAnalyzer::Analyzer::Results, SoilAnalyzer::Sample::Roundness, Sample, SoilAnalyzer::SoilSettings::SampleFolder, SaveMeMessage, Settings, and ui.
void VSAMainWindow::on_actionNeuralNet_triggered () [private], [slot]
Definition at line 353 of file vsamainwindow.cpp.
References Analyzer, SoilAnalyzer::Analyzer::NeuralNet, nnWindow, Settings, and settingsWindow.
void VSAMainWindow::on_actionNewSample_triggered () [private], [slot]
Definition at line 361 of file vsamainwindow.cpp.
References SoilAnalyzer::Analyzer::Analyse(), Analyzer, CamError, SoilAnalyzer::Sample::ChangesSinceLastSave, EXCEPTION_NO_SNAPSHOTS_NR, SoilAnalyzer::Exception::SoilAnalyzerException::id(), Images, SoilAnalyzer::Sample::ParticlePopulation, Sample, SaveMeMessage, Settings, TakeSnapShots(), and ui.
void VSAMainWindow::on_actionReport_Generator_triggered () [private], [slot]
Definition at line 552 of file vsamainwindow.cpp.
References ReportGenWindow, Sample, Settings, and ui.
void VSAMainWindow::on_actionSaveSample_triggered () [private], [slot]
Definition at line 460 of file vsamainwindow.cpp.
References SoilAnalyzer::Sample::ChangesSinceLastSave, SoilAnalyzer::Sample::IsLoadedFromDisk, Sample, SoilAnalyzer::SoilSettings::SampleFolder, SoilAnalyzer::Sample::Save(), and Settings.
void VSAMainWindow::on_actionSettings_triggered () [private], [slot]
Definition at line 270 of file vsamainwindow.cpp.
References DialogSettings::openTab(), and settingsWindow.
void VSAMainWindow::on_actionUseLearning_toggled (bool arg1) [private], [slot]
Definition at line 512 of file vsamainwindow.cpp.
References Analyzer, and SoilAnalyzer::Analyzer::PredictShape.
void VSAMainWindow::on_analyzer_finished () [private], [slot]
Definition at line 275 of file vsamainwindow.cpp.
References ParticleDisplayerFilled, SoilAnalyzer::Sample::ParticlePopulation, Sample, setAngularityHistogram(), SetPSDgraph(), setRoundnessHistogram(), and ui.
Referenced by on_actionLoadSample_triggered(), and VSAMainWindow().
void VSAMainWindow::on_Classification_changed (int newValue) [private], [slot]
Definition at line 522 of file vsamainwindow.cpp.
References SoilAnalyzer::Analyzer::Analyse(), Analyzer, SoilAnalyzer::Sample::ChangesSinceLastSave, SoilAnalyzer::Sample::ParticleChangedStateAngularity, SoilAnalyzer::Sample::ParticleChangedStateRoundness, Sample, and ui.
Referenced by VSAMainWindow().
void VSAMainWindow::on_compare_against () [private], [slot]
Definition at line 570 of file vsamainwindow.cpp.
References PSDTicks, SoilAnalyzer::SoilSettings::SampleFolder, Settings, and ui.
Referenced by on_PSD_contextMenuRequest().
void VSAMainWindow::on_particle_deleted () [private], [slot]
Definition at line 539 of file vsamainwindow.cpp.
References SoilAnalyzer::Analyzer::Analyse(), and Analyzer.
Referenced by VSAMainWindow().
void VSAMainWindow::on_particleChanged (int newPart) [private], [slot]
Definition at line 351 of file vsamainwindow.cpp.
References setAmpgraph().
Referenced by VSAMainWindow().
void VSAMainWindow::on_PSD_contextMenuRequest (QPoint point) [private], [slot]
Definition at line 561 of file vsamainwindow.cpp.
References on_compare_against(), on_restore_PSD(), and ui.
Referenced by VSAMainWindow().
void VSAMainWindow::on_reset_graph (QMouseEvent * e) [private], [slot]
Definition at line 545 of file vsamainwindow.cpp.
References ui.
Referenced by on_restore_PSD(), and VSAMainWindow().
void VSAMainWindow::on_restore_PSD () [private], [slot]
Definition at line 628 of file vsamainwindow.cpp.
References on_reset_graph(), and ui.
Referenced by on_PSD_contextMenuRequest().
void VSAMainWindow::setAmpgraph () [private]
Definition at line 339 of file vsamainwindow.cpp.
References ui.
Referenced by on_particleChanged().
void VSAMainWindow::setAngularityHistogram () [private]
Definition at line 315 of file vsamainwindow.cpp.
References SoilAnalyzer::Sample::Angularity, AngularityBars, AngularityTicks, SoilMath::Stats< T1, T2, T3 >::bins, SoilMath::Stats< T1, T2, T3 >::HighestPDF, SoilMath::Stats< T1, T2, T3 >::Mean, Sample, and ui.
Referenced by on_analyzer_finished().
void VSAMainWindow::SetPSDgraph () [private]
Definition at line 285 of file vsamainwindow.cpp.
References SoilMath::Stats< T1, T2, T3 >::CFD, SoilAnalyzer::Sample::PSD, PSDTicks, Sample, and ui.
Referenced by on_analyzer_finished().
void VSAMainWindow::setRoundnessHistogram () [private]
Definition at line 291 of file vsamainwindow.cpp.
References SoilMath::Stats< T1, T2, T3 >::bins, SoilMath::Stats< T1, T2, T3 >::HighestPDF, SoilMath::Stats< T1, T2, T3 >::Mean, SoilAnalyzer::Sample::Roundness, RoundnessBars, RoundnessTicks, Sample, and ui.
Referenced by on_analyzer_finished().
void VSAMainWindow::TakeSnapShots () [private]
Definition at line 391 of file vsamainwindow.cpp.
References Analyzer, SoilAnalyzer::Analyzer::Image_t::BackLight, BacklightMessage, SoilAnalyzer::Analyzer::CurrentSIfactor, SoilAnalyzer::Analyzer::Image_t::FrontLight, SoilAnalyzer::SoilSettings::HDRframes, Images, on_actionCalibrate_triggered(), Settings, ShakeItBabyMessage, SoilAnalyzer::Analyzer::SIfactorDet, SoilAnalyzer::Analyzer::Image_t::SIPixelFactor, SoilAnalyzer::SoilSettings::StandardNumberOfShots, SoilAnalyzer::SoilSettings::useBacklightProjection, and SoilAnalyzer::SoilSettings::useHDR.
Referenced by on_actionNewSample_triggered().
Member Data Documentation
SoilAnalyzer::Analyzer* VSAMainWindow::Analyzer = nullptr [private]
Definition at line 83 of file vsamainwindow.h.
Referenced by on_actionCalibrate_triggered(), on_actionLoadSample_triggered(), on_actionNeuralNet_triggered(), on_actionNewSample_triggered(), on_actionUseLearning_toggled(), on_Classification_changed(), on_particle_deleted(), TakeSnapShots(), VSAMainWindow(), and ~VSAMainWindow().
QCPBars* VSAMainWindow::AngularityBars = nullptr [private]
Definition at line 86 of file vsamainwindow.h.
Referenced by setAngularityHistogram(), and VSAMainWindow().
QVector<QString> VSAMainWindow::AngularityCat [private]
Initial value:
= {"Very Angular", "Angular", "Sub Angular",
                                    "Sub Rounded", "Rounded", "Well Rounded"}
Definition at line 92 of file vsamainwindow.h.
Referenced by VSAMainWindow().
std::vector<double> VSAMainWindow::AngularityTicks = {1, 2, 3, 4, 5, 6} [private]
Definition at line 94 of file vsamainwindow.h.
Referenced by setAngularityHistogram(), and VSAMainWindow().
QMessageBox* VSAMainWindow::BacklightMessage = nullptr [private]
Definition at line 76 of file vsamainwindow.h.
Referenced by TakeSnapShots(), VSAMainWindow(), and ~VSAMainWindow().
QErrorMessage* VSAMainWindow::CamError = nullptr [private]
Definition at line 74 of file vsamainwindow.h.
Referenced by on_actionNewSample_triggered(), VSAMainWindow(), and ~VSAMainWindow().
SoilAnalyzer::Analyzer::Images_t* VSAMainWindow::Images = nullptr [private]
Definition at line 84 of file vsamainwindow.h.
Referenced by on_actionLoadSample_triggered(), on_actionNewSample_triggered(), TakeSnapShots(), VSAMainWindow(), and ~VSAMainWindow().
Hardware::Microscope* VSAMainWindow::Microscope = nullptr [private]
Definition at line 81 of file vsamainwindow.h.
Referenced by ~VSAMainWindow().
DialogNN* VSAMainWindow::nnWindow = nullptr [private]
Definition at line 72 of file vsamainwindow.h.
Referenced by on_actionNeuralNet_triggered(), VSAMainWindow(), and ~VSAMainWindow().
bool VSAMainWindow::ParticleDisplayerFilled = false [private]
Definition at line 96 of file vsamainwindow.h.
Referenced by on_actionLoadSample_triggered(), and on_analyzer_finished().
QProgressBar* VSAMainWindow::Progress [private]
Definition at line 73 of file vsamainwindow.h.
Referenced by VSAMainWindow().
std::vector<double> VSAMainWindow::PSDTicks [private]
Initial value:
= {0.0, 0.038, 0.045, 0.063, 0.075,
                              0.09, 0.125, 0.18, 0.25, 0.355,
                              0.5, 0.71, 1.0, 1.4, 2.0}
Definition at line 87 of file vsamainwindow.h.
Referenced by on_compare_against(), SetPSDgraph(), and VSAMainWindow().
QReportGenerator* VSAMainWindow::ReportGenWindow = nullptr [private]
Definition at line 78 of file vsamainwindow.h.
Referenced by on_actionReport_Generator_triggered().
QCPBars* VSAMainWindow::RoundnessBars = nullptr [private]
Definition at line 85 of file vsamainwindow.h.
Referenced by setRoundnessHistogram(), and VSAMainWindow().
QVector<QString> VSAMainWindow::RoundnessCat = {`High`, `Medium`, `Low`} [private]
Definition at line 90 of file vsamainwindow.h.
Referenced by VSAMainWindow().
std::vector<double> VSAMainWindow::RoundnessTicks = {1, 2, 3} [private]
Definition at line 91 of file vsamainwindow.h.
Referenced by setRoundnessHistogram(), and VSAMainWindow().
SoilAnalyzer::Sample* VSAMainWindow::Sample = nullptr [private]
Definition at line 82 of file vsamainwindow.h.
Referenced by on_actionLoadSample_triggered(), on_actionNewSample_triggered(), on_actionReport_Generator_triggered(), on_actionSaveSample_triggered(), on_analyzer_finished(), on_Classification_changed(), setAngularityHistogram(), SetPSDgraph(), setRoundnessHistogram(), VSAMainWindow(), and ~VSAMainWindow().
QMessageBox* VSAMainWindow::SaveMeMessage = nullptr [private]
Definition at line 75 of file vsamainwindow.h.
Referenced by on_actionLoadSample_triggered(), on_actionNewSample_triggered(), VSAMainWindow(), and ~VSAMainWindow().
SoilAnalyzer::SoilSettings* VSAMainWindow::Settings = nullptr [private]
Definition at line 80 of file vsamainwindow.h.
Referenced by on_actionAutomatic_Shape_Pediction_triggered(), on_actionLoadSample_triggered(), on_actionNeuralNet_triggered(), on_actionNewSample_triggered(), on_actionReport_Generator_triggered(), on_actionSaveSample_triggered(), on_compare_against(), TakeSnapShots(), VSAMainWindow(), and ~VSAMainWindow().
DialogSettings* VSAMainWindow::settingsWindow = nullptr [private]
Definition at line 71 of file vsamainwindow.h.
Referenced by on_actionNeuralNet_triggered(), on_actionSettings_triggered(), VSAMainWindow(), and ~VSAMainWindow().
QMessageBox* VSAMainWindow::ShakeItBabyMessage = nullptr [private]
Definition at line 77 of file vsamainwindow.h.
Referenced by TakeSnapShots(), VSAMainWindow(), and ~VSAMainWindow().
Ui::VSAMainWindow* VSAMainWindow::ui [private]
Definition at line 70 of file vsamainwindow.h.
Referenced by on_actionLoadSample_triggered(), on_actionNewSample_triggered(), on_actionReport_Generator_triggered(), on_analyzer_finished(), on_Classification_changed(), on_compare_against(), on_PSD_contextMenuRequest(), on_reset_graph(), on_restore_PSD(), setAmpgraph(), setAngularityHistogram(), SetPSDgraph(), setRoundnessHistogram(), VSAMainWindow(), and ~VSAMainWindow().
The documentation for this class was generated from the following files:
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/VSA/vsamainwindow.h
/home/peer23peer/programmingspace/VSA/VisionSoilAnalyzer/src/VSA/vsamainwindow.cpp