QCPBars Class Reference
A plottable representing a bar chart in a plot.
#include <qcustomplot.h>
Public Types
enum WidthType { wtAbsolute,
wtAxisRectRatio,
wtPlotCoords
 }
Public Member Functions
QCPBars (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPBars ()
double width () const
WidthType widthType () const
QCPBarsGroup * barsGroup () const
double baseValue () const
QCPBars * barBelow () const
QCPBars * barAbove () const
QCPBarDataMap * data () const
void setWidth (double width)
void setWidthType (WidthType widthType)
void setBarsGroup (QCPBarsGroup *barsGroup)
void setBaseValue (double baseValue)
void setData (QCPBarDataMap *data, bool copy=false)
void setData (const QVector< double > &key, const QVector< double > &value)
void moveBelow (QCPBars *bars)
void moveAbove (QCPBars *bars)
void addData (const QCPBarDataMap &dataMap)
void addData (const QCPBarData &data)
void addData (double key, double value)
void addData (const QVector< double > &keys, const QVector< double > &values)
void removeDataBefore (double key)
void removeDataAfter (double key)
void removeData (double fromKey, double toKey)
void removeData (double key)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
void getVisibleDataBounds (QCPBarDataMap::const_iterator &lower, QCPBarDataMap::const_iterator &upperEnd) const
QPolygonF getBarPolygon (double key, double value) const
void getPixelWidth (double key, double &lower, double &upper) const
double getStackedBaseValue (double key, bool positive) const
Static Protected Member Functions
static void connectBars (QCPBars *lower, QCPBars *upper)
Protected Attributes
QCPBarDataMap * mData
double mWidth
WidthType mWidthType
QCPBarsGroup * mBarsGroup
double mBaseValue
QPointer< QCPBars > mBarBelow
QPointer< QCPBars > mBarAbove
Friends
class QCustomPlot
class QCPLegend
class QCPBarsGroup
Additional Inherited Members
Detailed Description
A plottable representing a bar chart in a plot.
To plot data, assign it with the setData or addData functions.
Changing the appearance
The appearance of the bars is determined by the pen and the brush (setPen, setBrush). The width of the individual bars can be controlled with setWidthType and setWidth.
Bar charts are stackable. This means, two QCPBars plottables can be placed on top of each other (see QCPBars::moveAbove). So when two bars are at the same key position, they will appear stacked.
If you would like to group multiple QCPBars plottables together so they appear side by side as shown below, use QCPBarsGroup.
Usage
Like all data representing objects in QCustomPlot, the QCPBars is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance:
add it to the customPlot with QCustomPlot::addPlottable:
and then modify the properties of the newly created plottable, e.g.:
Definition at line 3248 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPBars::WidthType
Defines the ways the width of the bar can be specified. Thus it defines what the number passed to setWidth actually means.
See also
setWidthType, setWidth
Enumerator
wtAbsolute
 Bar width is in absolute pixels.
wtAxisRectRatio
 Bar width is given by a fraction of the axis rect size.
wtPlotCoords
 Bar width is in key coordinates and thus scales with the key axis range
Definition at line 3266 of file qcustomplot.h.
                 {
    wtAbsolute
    ,
    wtAxisRectRatio
    ,
    wtPlotCoords
  };
Constructor & Destructor Documentation
QCPBars::QCPBars (QCPAxis * keyAxis, QCPAxis * valueAxis) [explicit]
Constructs a bar chart which uses keyAxis as its key axis (`x`) and valueAxis as its value axis (`y`). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPBars can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the bar chart.
Definition at line 20603 of file qcustomplot.cpp.
References QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, QCPAbstractPlottable::mSelectedBrush, and QCPAbstractPlottable::mSelectedPen.
    : QCPAbstractPlottable(keyAxis, valueAxis), mData(new
      QCPBarDataMap),
      mWidth(0.75), mWidthType(wtPlotCoords),
      mBarsGroup(0), mBaseValue(0) {
  // modify inherited properties from abstract plottable:
  mPen.setColor(Qt::blue);
  mPen.setStyle(Qt::SolidLine);
  mBrush.setColor(QColor(40, 50, 255, 30));
  mBrush.setStyle(Qt::SolidPattern);
  mSelectedPen = mPen;
  mSelectedPen.setWidthF(2.5);
  mSelectedPen.setColor(QColor(80, 80, 255)); // lighter than Qt::blue of mPen
  mSelectedBrush = mBrush;
}
QCPBars::~QCPBars () [virtual]
Definition at line 20617 of file qcustomplot.cpp.
References connectBars(), mBarAbove, mBarBelow, mData, and setBarsGroup().
                  {
  setBarsGroup(0);
  if (mBarBelow || mBarAbove)
    connectBars(mBarBelow.data(),
                mBarAbove.data()); // take this bar out of any stacking
  delete mData;
}
Member Function Documentation
void QCPBars::addData (const QCPBarDataMap & dataMap)
Adds the provided data points in dataMap to the current data.
See also
removeData
Definition at line 20811 of file qcustomplot.cpp.
References mData.
{ mData->unite(dataMap); }
void QCPBars::addData (const QCPBarData & data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
See also
removeData
Definition at line 20817 of file qcustomplot.cpp.
References QCPBarData::key, and mData.
                                            {
  mData->insertMulti(data.key, data);
}
void QCPBars::addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value tuple to the current data
See also
removeData
Definition at line 20826 of file qcustomplot.cpp.
References QCPBarData::key, mData, and QCPBarData::value.
                                              {
  QCPBarData newData;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.key, newData);
}
void QCPBars::addData (const QVector< double > & keys, const QVector< double > & values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value tuples to the current data.
See also
removeData
Definition at line 20838 of file qcustomplot.cpp.
References i, QCPBarData::key, mData, and n.
                                                     {
  int n = keys.size();
  n = qMin(n, values.size());
  QCPBarData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = keys[i];
    newData.value = values[i];
    mData->insertMulti(newData.key, newData);
  }
}
QCPBars * QCPBars::barAbove () const [inline]
Returns the bars plottable that is directly above this bars plottable. If there is no such plottable, returns 0.
See also
barBelow, moveBelow, moveAbove
Definition at line 3285 of file qcustomplot.h.
References data().
{ return mBarAbove.data(); }
QCPBars * QCPBars::barBelow () const [inline]
Returns the bars plottable that is directly below this bars plottable. If there is no such plottable, returns 0.
See also
barAbove, moveBelow, moveAbove
Definition at line 3284 of file qcustomplot.h.
References data().
Referenced by QCPBarsGroup::keyPixelOffset().
{ return mBarBelow.data(); }
QCPBarsGroup* QCPBars::barsGroup () const [inline]
Definition at line 3282 of file qcustomplot.h.
Referenced by setBarsGroup().
{ return mBarsGroup; }
double QCPBars::baseValue () const [inline]
Definition at line 3283 of file qcustomplot.h.
Referenced by setBaseValue().
{ return mBaseValue; }
void QCPBars::clearData () [virtual]
Removes all data points.
See also
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 20907 of file qcustomplot.cpp.
References mData.
{ mData->clear(); }
void QCPBars::connectBars (QCPBars * lower, QCPBars * upper) [static], [protected]
Definition at line 21206 of file qcustomplot.cpp.
References mBarAbove, and mBarBelow.
Referenced by moveAbove(), moveBelow(), and ~QCPBars().
                                                        {
  if (!lower && !upper)
    return;
  if (!lower) // disconnect upper at bottom
  {
    // disconnect old bar below upper:
    if (upper->mBarBelow && upper->mBarBelow.data()->mBarAbove.data() == upper)
      upper->mBarBelow.data()->mBarAbove = 0;
    upper->mBarBelow = 0;
  } else if (!upper) // disconnect lower at top
  {
    // disconnect old bar above lower:
    if (lower->mBarAbove && lower->mBarAbove.data()->mBarBelow.data() == lower)
      lower->mBarAbove.data()->mBarBelow = 0;
    lower->mBarAbove = 0;
  } else // connect lower and upper
  {
    // disconnect old bar above lower:
    if (lower->mBarAbove && lower->mBarAbove.data()->mBarBelow.data() == lower)
      lower->mBarAbove.data()->mBarBelow = 0;
    // disconnect old bar below upper:
    if (upper->mBarBelow && upper->mBarBelow.data()->mBarAbove.data() == upper)
      upper->mBarBelow.data()->mBarAbove = 0;
    lower->mBarAbove = upper;
    upper->mBarBelow = lower;
  }
}
QCPBarDataMap* QCPBars::data () const [inline]
Definition at line 3286 of file qcustomplot.h.
Referenced by barAbove(), barBelow(), and setData().
{ return mData; }
void QCPBars::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 20933 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), getBarPolygon(), getVisibleDataBounds(), QCP::isInvalidData(), QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAbstractPlottable::name(), and QCPPainter::setPen().
                                      {
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  if (mData->isEmpty())
    return;
  QCPBarDataMap::const_iterator it, lower, upperEnd;
  getVisibleDataBounds(lower, upperEnd);
  for (it = lower; it != upperEnd; ++it) {
// check data validity if flag set:
#ifdef QCUSTOMPLOT_CHECK_DATA
    if (QCP::isInvalidData(it.value().key, it.value().value))
      qDebug() << Q_FUNC_INFO << "Data point at" << it.key()
               << "of drawn range invalid."
               << "Plottable name:" << name();
#endif
    QPolygonF barPolygon = getBarPolygon(it.key(), it.value().value);
    // draw bar fill:
    if (mainBrush().style() != Qt::NoBrush &&
        mainBrush().color().alpha() != 0) {
      applyFillAntialiasingHint(painter);
      painter->setPen(Qt::NoPen);
      painter->setBrush(mainBrush());
      painter->drawPolygon(barPolygon);
    }
    // draw bar line:
    if (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0) {
      applyDefaultAntialiasingHint(painter);
      painter->setPen(mainPen());
      painter->setBrush(Qt::NoBrush);
      painter->drawPolyline(barPolygon);
    }
  }
}
void QCPBars::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 20971 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, and QCPPainter::setPen().
                                                                          {
  // draw filled rect:
  applyDefaultAntialiasingHint(painter);
  painter->setBrush(mBrush);
  painter->setPen(mPen);
  QRectF r = QRectF(0, 0, rect.width() * 0.67, rect.height() * 0.67);
  r.moveCenter(rect.center());
  painter->drawRect(r);
}
QPolygonF QCPBars::getBarPolygon (double key, double value) const [protected]
Definition at line 21076 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPixelWidth(), getStackedBaseValue(), QCPAbstractPlottable::keyAxis(), QCPBarsGroup::keyPixelOffset(), mBarsGroup, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by draw(), getVisibleDataBounds(), and selectTest().
                                                               {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return QPolygonF();
  }
  QPolygonF result;
  double lowerPixelWidth, upperPixelWidth;
  getPixelWidth(key, lowerPixelWidth, upperPixelWidth);
  double base = getStackedBaseValue(key, value >= 0);
  double basePixel = valueAxis->coordToPixel(base);
  double valuePixel = valueAxis->coordToPixel(base + value);
  double keyPixel = keyAxis->coordToPixel(key);
  if (mBarsGroup)
    keyPixel += mBarsGroup->keyPixelOffset(this, key);
  if (keyAxis->orientation() == Qt::Horizontal) {
    result << QPointF(keyPixel + lowerPixelWidth, basePixel);
    result << QPointF(keyPixel + lowerPixelWidth, valuePixel);
    result << QPointF(keyPixel + upperPixelWidth, valuePixel);
    result << QPointF(keyPixel + upperPixelWidth, basePixel);
  } else {
    result << QPointF(basePixel, keyPixel + lowerPixelWidth);
    result << QPointF(valuePixel, keyPixel + lowerPixelWidth);
    result << QPointF(valuePixel, keyPixel + upperPixelWidth);
    result << QPointF(basePixel, keyPixel + upperPixelWidth);
  }
  return result;
}
QCPRange QCPBars::getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 21236 of file qcustomplot.cpp.
References getPixelWidth(), QCPBarsGroup::keyPixelOffset(), QCPRange::lower, mBarsGroup, mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
                                                                             {
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  double current;
  QCPBarDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd()) {
    current = it.value().key;
    if (inSignDomain == sdBoth || (inSignDomain == sdNegative && current < 0) ||
        (inSignDomain == sdPositive && current > 0)) {
      if (current < range.lower || !haveLower) {
        range.lower = current;
        haveLower = true;
      }
      if (current > range.upper || !haveUpper) {
        range.upper = current;
        haveUpper = true;
      }
    }
    ++it;
  }
  // determine exact range of bars by including bar width and barsgroup offset:
  if (haveLower && mKeyAxis) {
    double lowerPixelWidth, upperPixelWidth, keyPixel;
    getPixelWidth(range.lower, lowerPixelWidth, upperPixelWidth);
    keyPixel = mKeyAxis.data()->coordToPixel(range.lower) + lowerPixelWidth;
    if (mBarsGroup)
      keyPixel += mBarsGroup->keyPixelOffset(this, range.
      lower);
    range.lower = mKeyAxis.data()->pixelToCoord(keyPixel);
  }
  if (haveUpper && mKeyAxis) {
    double lowerPixelWidth, upperPixelWidth, keyPixel;
    getPixelWidth(range.upper, lowerPixelWidth, upperPixelWidth);
    keyPixel = mKeyAxis.data()->coordToPixel(range.upper) + upperPixelWidth;
    if (mBarsGroup)
      keyPixel += mBarsGroup->keyPixelOffset(this, range.
      upper);
    range.upper = mKeyAxis.data()->pixelToCoord(keyPixel);
  }
  foundRange = haveLower && haveUpper;
  return range;
}
void QCPBars::getPixelWidth (double key, double & lower, double & upper) const [protected]
Definition at line 21119 of file qcustomplot.cpp.
References QCPAbstractPlottable::mKeyAxis, mWidth, mWidthType, wtAbsolute, wtAxisRectRatio, and wtPlotCoords.
Referenced by getBarPolygon(), and getKeyRange().
                                                                          {
  switch (mWidthType) {
  case wtAbsolute: {
    upper = mWidth * 0.5;
    lower = -upper;
    if (mKeyAxis && (mKeyAxis.data()->rangeReversed() ^
                     (mKeyAxis.data()->orientation() == Qt::Vertical)))
      qSwap(lower, upper);
    break;
  }
  case wtAxisRectRatio: {
    if (mKeyAxis && mKeyAxis.data()->axisRect()) {
      if (mKeyAxis.data()->orientation() == Qt::Horizontal)
        upper = mKeyAxis.data()->axisRect()->width() * mWidth * 0.5;
      else
        upper = mKeyAxis.data()->axisRect()->height() * mWidth * 0.5;
      lower = -upper;
      if (mKeyAxis && (mKeyAxis.data()->rangeReversed() ^
                       (mKeyAxis.data()->orientation() == Qt::Vertical)))
        qSwap(lower, upper);
    } else
      qDebug() << Q_FUNC_INFO << "No key axis or axis rect defined";
    break;
  }
  case wtPlotCoords: {
    if (mKeyAxis) {
      double keyPixel = mKeyAxis.data()->coordToPixel(key);
      upper = mKeyAxis.data()->coordToPixel(key + mWidth * 0.5) - keyPixel;
      lower = mKeyAxis.data()->coordToPixel(key - mWidth * 0.5) - keyPixel;
      // no need to qSwap(lower, higher) when range reversed, because
      // higher/lower are gained by
      // coordinate transform which includes range direction
    } else
      qDebug() << Q_FUNC_INFO << "No key axis defined";
    break;
  }
  }
}
double QCPBars::getStackedBaseValue (double key, bool positive) const [protected]
Definition at line 21170 of file qcustomplot.cpp.
References mBarBelow, and mBaseValue.
Referenced by getBarPolygon(), and getValueRange().
                                                                   {
  if (mBarBelow) {
    double max = 0; // don't use mBaseValue here because only base value of
                    // bottom-most bar has meaning in a bar stack
    // find bars of mBarBelow that are approximately at key and find largest
    // one:
    double epsilon =
        qAbs(key) *
        1e-6; // should be safe even when changed to use float at some point
    if (key == 0)
      epsilon = 1e-6;
    QCPBarDataMap::const_iterator it =
        mBarBelow.data()->mData->lowerBound(key - epsilon);
    QCPBarDataMap::const_iterator itEnd =
        mBarBelow.data()->mData->upperBound(key + epsilon);
    while (it != itEnd) {
      if ((positive && it.value().value > max) ||
          (!positive && it.value().value < max))
        max = it.value().value;
      ++it;
    }
    // recurse down the bar-stack to find the total height:
    return max + mBarBelow.data()->getStackedBaseValue(key, positive);
  } else
    return mBaseValue;
}
QCPRange QCPBars::getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 21280 of file qcustomplot.cpp.
References getStackedBaseValue(), QCPRange::lower, mBaseValue, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
                                                               {
  QCPRange range;
  range.lower = mBaseValue;
  range.upper = mBaseValue;
  bool haveLower = true; // set to true, because baseValue should always be
                         // visible in bar charts
  bool haveUpper = true; // set to true, because baseValue should always be
                         // visible in bar charts
  double current;
  QCPBarDataMap::const_iterator it = mData->constBegin();
  while (it != mData->constEnd()) {
    current = it.value().value +
              getStackedBaseValue(it.value().key, it.value().value >= 0);
    if (inSignDomain == sdBoth || (inSignDomain == sdNegative && current < 0) ||
        (inSignDomain == sdPositive && current > 0)) {
      if (current < range.lower || !haveLower) {
        range.lower = current;
        haveLower = true;
      }
      if (current > range.upper || !haveUpper) {
        range.upper = current;
        haveUpper = true;
      }
    }
    ++it;
  }
  foundRange =
      true; // return true because bar charts always have the 0-line visible
  return range;
}
void QCPBars::getVisibleDataBounds (QCPBarDataMap::const_iterator & lower, QCPBarDataMap::const_iterator & upperEnd) const [protected]
Definition at line 21001 of file qcustomplot.cpp.
References getBarPolygon(), mData, and QCPAbstractPlottable::mKeyAxis.
Referenced by draw().
                                                 {
  if (!mKeyAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key axis";
    return;
  }
  if (mData->isEmpty()) {
    lower = mData->constEnd();
    upperEnd = mData->constEnd();
    return;
  }
  // get visible data range as QMap iterators
  lower = mData->lowerBound(mKeyAxis.data()->range().lower);
  upperEnd = mData->upperBound(mKeyAxis.data()->range().upper);
  double lowerPixelBound =
      mKeyAxis.data()->coordToPixel(mKeyAxis.data()->range().lower);
  double upperPixelBound =
      mKeyAxis.data()->coordToPixel(mKeyAxis.data()->range().upper);
  bool isVisible = false;
  // walk left from lbound to find lower bar that actually is completely outside
  // visible pixel range:
  QCPBarDataMap::const_iterator it = lower;
  while (it != mData->constBegin()) {
    --it;
    QRectF barBounds =
        getBarPolygon(it.value().key, it.value().value).boundingRect();
    if (mKeyAxis.data()->orientation() == Qt::Horizontal)
      isVisible = ((!mKeyAxis.data()->rangeReversed() &&
                    barBounds.right() >= lowerPixelBound) ||
                   (mKeyAxis.data()->rangeReversed() &&
                    barBounds.left() <= lowerPixelBound));
    else // keyaxis is vertical
      isVisible = ((!mKeyAxis.data()->rangeReversed() &&
                    barBounds.top() <= lowerPixelBound) ||
                   (mKeyAxis.data()->rangeReversed() &&
                    barBounds.bottom() >= lowerPixelBound));
    if (isVisible)
      lower = it;
    else
      break;
  }
  // walk right from ubound to find upper bar that actually is completely
  // outside visible pixel range:
  it = upperEnd;
  while (it != mData->constEnd()) {
    QRectF barBounds = getBarPolygon(upperEnd.value().key,
                                     upperEnd.value().value).boundingRect();
    if (mKeyAxis.data()->orientation() == Qt::Horizontal)
      isVisible = ((!mKeyAxis.data()->rangeReversed() &&
                    barBounds.left() <= upperPixelBound) ||
                   (mKeyAxis.data()->rangeReversed() &&
                    barBounds.right() >= upperPixelBound));
    else // keyaxis is vertical
      isVisible = ((!mKeyAxis.data()->rangeReversed() &&
                    barBounds.bottom() >= upperPixelBound) ||
                   (mKeyAxis.data()->rangeReversed() &&
                    barBounds.top() <= upperPixelBound));
    if (isVisible)
      upperEnd = it + 1;
    else
      break;
    ++it;
  }
}
void QCPBars::moveAbove (QCPBars * bars)
Moves this bars plottable above bars. In other words, the bars of this plottable will appear above the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object below itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See also
moveBelow, barBelow, barAbove
Definition at line 20786 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
                                     {
  if (bars == this)
    return;
  if (bars && (bars->keyAxis() != mKeyAxis.data() ||
               bars->valueAxis() != mValueAxis.data())) {
    qDebug() << Q_FUNC_INFO << "passed QCPBars* doesn't have same key and "
                               "value axis as this QCPBars";
    return;
  }
  // remove from stacking:
  connectBars(
      mBarBelow.data(),
      mBarAbove.data()); // Note: also works if one (or both) of them is 0
  // if new bar given, insert this bar above it:
  if (bars) {
    if (bars->mBarAbove)
      connectBars(this, bars->mBarAbove.data());
    connectBars(bars, this);
  }
}
void QCPBars::moveBelow (QCPBars * bars)
Moves this bars plottable below bars. In other words, the bars of this plottable will appear below the bars of bars. The move target bars must use the same key and value axis as this plottable.
Inserting into and removing from existing bar stacking is handled gracefully. If bars already has a bars object below itself, this bars object is inserted between the two. If this bars object is already between two other bars, the two other bars will be stacked on top of each other after the operation.
To remove this bars plottable from any stacking, set bars to 0.
See also
moveBelow, barAbove, barBelow
Definition at line 20746 of file qcustomplot.cpp.
References connectBars(), QCPAbstractPlottable::keyAxis(), mBarAbove, mBarBelow, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::valueAxis().
                                     {
  if (bars == this)
    return;
  if (bars && (bars->keyAxis() != mKeyAxis.data() ||
               bars->valueAxis() != mValueAxis.data())) {
    qDebug() << Q_FUNC_INFO << "passed QCPBars* doesn't have same key and "
                               "value axis as this QCPBars";
    return;
  }
  // remove from stacking:
  connectBars(
      mBarBelow.data(),
      mBarAbove.data()); // Note: also works if one (or both) of them is 0
  // if new bar given, insert this bar below it:
  if (bars) {
    if (bars->mBarBelow)
      connectBars(bars->mBarBelow.data(), this);
    connectBars(this, bars);
  }
}
void QCPBars::removeData (double fromKey, double toKey)
Removes all data points with key between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key).
See also
addData, clearData
Definition at line 20881 of file qcustomplot.cpp.
References mData.
                                                     {
  if (fromKey >= toKey || mData->isEmpty())
    return;
  QCPBarDataMap::iterator it = mData->upperBound(fromKey);
  QCPBarDataMap::iterator itEnd = mData->upperBound(toKey);
  while (it != itEnd)
    it = mData->erase(it);
}
void QCPBars::removeData (double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known.
See also
addData, clearData
Definition at line 20901 of file qcustomplot.cpp.
References mData.
{ mData->remove(key); }
void QCPBars::removeDataAfter (double key)
Removes all data points with key greater than key.
See also
addData, clearData
Definition at line 20864 of file qcustomplot.cpp.
References mData.
                                        {
  if (mData->isEmpty())
    return;
  QCPBarDataMap::iterator it = mData->upperBound(key);
  while (it != mData->end())
    it = mData->erase(it);
}
void QCPBars::removeDataBefore (double key)
Removes all data points with key smaller than key.
See also
addData, clearData
Definition at line 20854 of file qcustomplot.cpp.
References mData.
                                         {
  QCPBarDataMap::iterator it = mData->begin();
  while (it != mData->end() && it.key() < key)
    it = mData->erase(it);
}
double QCPBars::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 20910 of file qcustomplot.cpp.
References getBarPolygon(), mData, QCPAbstractPlottable::mKeyAxis, QCPLayerable::mParentPlot, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, and QCustomPlot::selectionTolerance().
                                                    {
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return -1;
  }
  if (mKeyAxis.data()->axisRect()->rect().contains(pos.toPoint())) {
    QCPBarDataMap::ConstIterator it;
    for (it = mData->constBegin(); it != mData->constEnd(); ++it) {
      if (getBarPolygon(it.value().key, it.value().value)
              .boundingRect()
              .contains(pos))
        return mParentPlot->selectionTolerance() * 0.99;
    }
  }
  return -1;
}
void QCPBars::setBarsGroup (QCPBarsGroup * barsGroup)
Sets to which QCPBarsGroup this QCPBars instance belongs to. Alternatively, you can also use QCPBarsGroup::append.
To remove this QCPBars from any group, set barsGroup to 0.
Definition at line 20655 of file qcustomplot.cpp.
References barsGroup(), mBarsGroup, QCPBarsGroup::registerBars(), and QCPBarsGroup::unregisterBars().
Referenced by QCPBarsGroup::append(), QCPBarsGroup::clear(), QCPBarsGroup::insert(), QCPBarsGroup::remove(), and ~QCPBars().
                                                  {
  // deregister at old group:
  if (mBarsGroup)
    mBarsGroup->unregisterBars(this);
  mBarsGroup = barsGroup;
  // register at new group:
  if (mBarsGroup)
    mBarsGroup->registerBars(this);
}
void QCPBars::setBaseValue (double baseValue)
Sets the base value of this bars plottable.
The base value defines where on the value coordinate the bars start. How far the bars extend from the base value is given by their individual value data. For example, if the base value is set to 1, a bar with data value 2 will have its lowest point at value coordinate 1 and highest point at 3.
For stacked bars, only the base value of the bottom-most QCPBars has meaning.
The default base value is 0.
Definition at line 20680 of file qcustomplot.cpp.
References baseValue(), and mBaseValue.
{ mBaseValue = baseValue; }
void QCPBars::setData (QCPBarDataMap * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, data points in data will only be copied. if false, the plottable takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 20691 of file qcustomplot.cpp.
References data(), and mData.
                                                    {
  if (mData == data) {
    qDebug() << Q_FUNC_INFO
             << "The data pointer is already in (and owned by) this plottable"
             << reinterpret_cast<quintptr>(data);
    return;
  }
  if (copy) {
    *mData = *data;
  } else {
    delete mData;
    mData = data;
  }
}
void QCPBars::setData (const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value tuples. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 20714 of file qcustomplot.cpp.
References i, QCPBarData::key, mData, and n.
                                                    {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  QCPBarData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.key, newData);
  }
}
void QCPBars::setWidth (double width)
Sets the width of the bars.
How the number passed as width is interpreted (e.g. screen pixels, plot coordinates,...), depends on the currently set width type, see setWidthType and WidthType.
Definition at line 20633 of file qcustomplot.cpp.
References mWidth, and width().
{ mWidth = width; }
void QCPBars::setWidthType (QCPBars::WidthType widthType)
Sets how the width of the bars is defined. See the documentation of WidthType for an explanation of the possible values for widthType.
The default value is wtPlotCoords.
See also
setWidth
Definition at line 20644 of file qcustomplot.cpp.
References mWidthType, and widthType().
                                                     {
  mWidthType = widthType;
}
double QCPBars::width () const [inline]
Definition at line 3280 of file qcustomplot.h.
Referenced by setWidth().
{ return mWidth; }
WidthType QCPBars::widthType () const [inline]
Definition at line 3281 of file qcustomplot.h.
Referenced by setWidthType().
{ return mWidthType; }
Friends And Related Function Documentation
friend class QCPBarsGroup [friend]
Definition at line 3340 of file qcustomplot.h.
friend class QCPLegend [friend]
Definition at line 3339 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 3338 of file qcustomplot.h.
Member Data Documentation
QPointer<QCPBars> QCPBars::mBarAbove [protected]
Definition at line 3320 of file qcustomplot.h.
Referenced by connectBars(), moveAbove(), moveBelow(), and ~QCPBars().
QPointer<QCPBars> QCPBars::mBarBelow [protected]
Definition at line 3320 of file qcustomplot.h.
Referenced by connectBars(), getStackedBaseValue(), moveAbove(), moveBelow(), and ~QCPBars().
QCPBarsGroup* QCPBars::mBarsGroup [protected]
Definition at line 3318 of file qcustomplot.h.
Referenced by getBarPolygon(), getKeyRange(), and setBarsGroup().
double QCPBars::mBaseValue [protected]
Definition at line 3319 of file qcustomplot.h.
Referenced by getStackedBaseValue(), getValueRange(), and setBaseValue().
QCPBarDataMap* QCPBars::mData [protected]
Definition at line 3315 of file qcustomplot.h.
Referenced by addData(), clearData(), draw(), getKeyRange(), getValueRange(), getVisibleDataBounds(), removeData(), removeDataAfter(), removeDataBefore(), selectTest(), setData(), and ~QCPBars().
double QCPBars::mWidth [protected]
Definition at line 3316 of file qcustomplot.h.
Referenced by getPixelWidth(), and setWidth().
WidthType QCPBars::mWidthType [protected]
Definition at line 3317 of file qcustomplot.h.
Referenced by getPixelWidth(), and setWidthType().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp