Hardware::EC12P Class Reference
#include <EC12P.h>
Public Types
enum Color {
*
Red,
Pink,
Blue,
SkyBlue,
*
Green,
Yellow,
White,
None
 }
Public Member Functions
EC12P ()
~EC12P ()
void SetPixelColor (Color value)
Color GetPixelColor ()
void RainbowLoop (int sleepperiod)
void StopRainbowLoop ()
Public Attributes
eQEP Rotary { eQEP2, eQEP::eQEP_Mode_Absolute }
GPIO Button { 68 }
Private Attributes
Color PixelColor
GPIO R { 31 }
GPIO B { 48 }
GPIO G { 51 }
pthread_t thread
bool threadRunning
int sleepperiod
Friends
void * colorLoop (void *value)
Detailed Description
Definition at line 17 of file EC12P.h.
Member Enumeration Documentation
enum Hardware::EC12P::Color
Enumerator indicating the color of the encoder shaft
Enumerator
Red
 Red
Pink
 Pink
Blue
 Blue
SkyBlue
 SkyBlue
Green
 Green
Yellow
 Yellow
White
 White
None
 Off
Definition at line 24 of file EC12P.h.
        {
            Red,
            Pink,
            Blue,
            SkyBlue,
            Green,
            Yellow,
            White,
            None
        };
Constructor & Destructor Documentation
EC12P::EC12P ()
Constructor
Definition at line 6 of file EC12P.cpp.
References Button, G, Hardware::GPIO::Input, None, Hardware::GPIO::Output, R, Hardware::GPIO::Rising, Rotary, Hardware::eQEP::set_period(), Hardware::GPIO::SetDirection(), Hardware::GPIO::SetEdge(), SetPixelColor(), and threadRunning.
    {
        // Init Rotary button
        Button.SetDirection(GPIO::Input);
        Button.SetEdge(GPIO::Rising);
        
        // Init Encoder
        Rotary.set_period(100000000L);
        // Init Encoder color
        R.SetDirection(GPIO::Output);
        B.SetDirection(GPIO::Output);
        G.SetDirection(GPIO::Output);
        SetPixelColor(None);
        threadRunning = false;
    }
EC12P::~EC12P ()
De-constructor
Definition at line 25 of file EC12P.cpp.
{ }
Member Function Documentation
Color Hardware::EC12P::GetPixelColor () [inline]
Definition at line 37 of file EC12P.h.
{ return PixelColor; };
void EC12P::RainbowLoop (int sleepperiod)
Loops through all the colors except of as a thread
Definition at line 79 of file EC12P.cpp.
References colorLoop, sleepperiod, thread, and threadRunning.
    {
        this->sleepperiod = sleepperiod;
        this->threadRunning = true;
        if (pthread_create(&thread, NULL, colorLoop, this)) { throw
      Exception::FailedToCreateThreadException(); }
    }
void EC12P::SetPixelColor (Color value)
Set the shaft color
Parameters
value as Color enumerator
Definition at line 30 of file EC12P.cpp.
References Blue, G, Green, Hardware::GPIO::High, Hardware::GPIO::Low, None, Pink, PixelColor, R, Red, Hardware::GPIO::SetValue(), SkyBlue, White, and Yellow.
Referenced by Hardware::colorLoop(), and EC12P().
    {
        switch (value)
        {
        case Hardware::EC12P::Red:
            R.SetValue(GPIO::High);
            B.SetValue(GPIO::Low);
            G.SetValue(GPIO::Low);
            break;
        case Hardware::EC12P::Pink:
            R.SetValue(GPIO::High);
            B.SetValue(GPIO::High);
            G.SetValue(GPIO::Low);
            break;
        case Hardware::EC12P::Blue:
            R.SetValue(GPIO::Low);
            B.SetValue(GPIO::High);
            G.SetValue(GPIO::Low);
            break;
        case Hardware::EC12P::SkyBlue:
            R.SetValue(GPIO::Low);
            B.SetValue(GPIO::High);
            G.SetValue(GPIO::High);
            break;
        case Hardware::EC12P::Green:
            R.SetValue(GPIO::Low);
            B.SetValue(GPIO::Low);
            G.SetValue(GPIO::High);
            break;
        case Hardware::EC12P::Yellow:
            R.SetValue(GPIO::High);
            B.SetValue(GPIO::Low);
            G.SetValue(GPIO::High);
            break;
        case Hardware::EC12P::White:
            R.SetValue(GPIO::High);
            B.SetValue(GPIO::High);
            G.SetValue(GPIO::High);
            break;
        case Hardware::EC12P::None:
            R.SetValue(GPIO::Low);
            B.SetValue(GPIO::Low);
            G.SetValue(GPIO::Low);
            break;
        }
        PixelColor = value;
    }
void Hardware::EC12P::StopRainbowLoop () [inline]
Definition at line 40 of file EC12P.h.
{ threadRunning = false; };
Friends And Related Function Documentation
void* colorLoop (void * value) [friend]
The thread function that runs trough all the colors
Definition at line 87 of file EC12P.cpp.
Referenced by RainbowLoop().
    {
        int i = 0;
        EC12P *ec12p = static_cast<EC12P*>(value);
        EC12P::Color pcolor;
        while (ec12p->threadRunning)
        {
            pcolor = static_cast<EC12P::Color>(i);
            ec12p->SetPixelColor(pcolor);
            usleep(ec12p->sleepperiod);
            i++;
            if (i == 6) { i = 0; }
        }
        return ec12p;
    }
Member Data Documentation
GPIO Hardware::EC12P::B { 48 } [private]
Blue LED
Definition at line 49 of file EC12P.h.
GPIO Hardware::EC12P::Button { 68 }
The pushbutton
Definition at line 43 of file EC12P.h.
Referenced by EC12P().
GPIO Hardware::EC12P::G { 51 } [private]
Green LED
Definition at line 50 of file EC12P.h.
Referenced by EC12P(), and SetPixelColor().
Color Hardware::EC12P::PixelColor [private]
Current shaft color
Definition at line 46 of file EC12P.h.
Referenced by SetPixelColor().
GPIO Hardware::EC12P::R { 31 } [private]
Red LED
Definition at line 48 of file EC12P.h.
Referenced by EC12P(), and SetPixelColor().
eQEP Hardware::EC12P::Rotary { eQEP2, eQEP::eQEP_Mode_Absolute }
The encoder
Definition at line 42 of file EC12P.h.
Referenced by EC12P().
int Hardware::EC12P::sleepperiod [private]
Sleep period
Definition at line 54 of file EC12P.h.
Referenced by Hardware::colorLoop(), and RainbowLoop().
pthread_t Hardware::EC12P::thread [private]
the thread
Definition at line 52 of file EC12P.h.
Referenced by RainbowLoop().
bool Hardware::EC12P::threadRunning [private]
Bool used to stop the thread
Definition at line 53 of file EC12P.h.
Referenced by Hardware::colorLoop(), EC12P(), and RainbowLoop().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/EC12P.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilHardware/EC12P.cpp