QCPMarginGroup Class Reference
A margin group allows synchronization of margin sides if working with multiple layout elements.
#include <qcustomplot.h>
Public Member Functions
QCPMarginGroup (QCustomPlot *parentPlot)
~QCPMarginGroup ()
QList< QCPLayoutElement * > elements (QCP::MarginSide side) const
bool isEmpty () const
void clear ()
Protected Member Functions
int commonMargin (QCP::MarginSide side) const
void addChild (QCP::MarginSide side, QCPLayoutElement *element)
void removeChild (QCP::MarginSide side, QCPLayoutElement *element)
Protected Attributes
QCustomPlot * mParentPlot
QHash< QCP::MarginSide, QList< QCPLayoutElement * > > mChildren
Friends
class QCPLayoutElement
Detailed Description
A margin group allows synchronization of margin sides if working with multiple layout elements.
QCPMarginGroup allows you to tie a margin side of two or more layout elements together, such that they will all have the same size, based on the largest required margin in the group.
 In certain situations it is desirable that margins at specific sides are synchronized across layout elements. For example, if one QCPAxisRect is below another one in a grid layout, it will provide a cleaner look to the user if the left and right margins of the two axis rects are of the same size. The left axis of the top axis rect will then be at the same horizontal position as the left axis of the lower axis rect, making them appear aligned. The same applies for the right axes. This is what QCPMarginGroup makes possible.
To add/remove a specific side of a layout element to/from a margin group, use the QCPLayoutElement::setMarginGroup method. To completely break apart the margin group, either call clear, or just delete the margin group.
Example
First create a margin group:
qcpmargingroup-creation-1 Then set this group on the layout element sides:
qcpmargingroup-creation-2 Here, we've used the first two axis rects of the plot and synchronized their left margins with each other and their right margins with each other.
Definition at line 725 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPMarginGroup::QCPMarginGroup (QCustomPlot * parentPlot)
Creates a new QCPMarginGroup instance in parentPlot.
Definition at line 1682 of file qcustomplot.cpp.
References mChildren, QCP::msBottom, QCP::msLeft, QCP::msRight, and QCP::msTop.
    : QObject(parentPlot), mParentPlot(parentPlot) {
  mChildren.insert(QCP::msLeft, QList<QCPLayoutElement *>());
  mChildren.insert(QCP::msRight, QList<QCPLayoutElement *>());
  mChildren.insert(QCP::msTop, QList<QCPLayoutElement *>());
  mChildren.insert(QCP::msBottom, QList<QCPLayoutElement *>());
}
QCPMarginGroup::~QCPMarginGroup ()
Definition at line 1690 of file qcustomplot.cpp.
References clear().
{ clear(); }
Member Function Documentation
void QCPMarginGroup::addChild (QCP::MarginSide side, QCPLayoutElement * element) [protected]
Definition at line 1760 of file qcustomplot.cpp.
References mChildren.
Referenced by QCPLayoutElement::setMarginGroup().
                                                                           {
  if (!mChildren[side].contains(element))
    mChildren[side].append(element);
  else
    qDebug() << Q_FUNC_INFO
             << "element is already child of this margin group side"
             << reinterpret_cast<quintptr>(element);
}
void QCPMarginGroup::clear ()
Clears this margin group. The synchronization of the margin sides that use this margin group is lifted and they will use their individual margin sizes again.
Definition at line 1712 of file qcustomplot.cpp.
References elements(), i, and mChildren.
Referenced by ~QCPMarginGroup().
                           {
  // make all children remove themselves from this margin group:
  QHashIterator<QCP::MarginSide, QList<QCPLayoutElement *>> it(mChildren);
  while (it.hasNext()) {
    it.next();
    const QList<QCPLayoutElement *> elements = it.value();
    for (int i = elements.size() - 1; i >= 0; --i)
      elements.at(i)->setMarginGroup(
          it.key(), 0); // removes itself from mChildren via removeChild
  }
}
int QCPMarginGroup::commonMargin (QCP::MarginSide side) const [protected]
Definition at line 1737 of file qcustomplot.cpp.
References elements(), QCP::getMarginValue(), i, m, and mChildren.
                                                         {
  // query all automatic margins of the layout elements in this margin group
  // side and find maximum:
  int result = 0;
  const QList<QCPLayoutElement *> elements = mChildren.value(side);
  for (int i = 0; i < elements.size(); ++i) {
    if (!elements.at(i)->autoMargins().testFlag(side))
      continue;
    int m = qMax(elements.at(i)->calculateAutoMargin(side),
                 QCP::getMarginValue(elements.at(i)->minimumMargins(), side));
    if (m > result)
      result = m;
  }
  return result;
}
QList< QCPLayoutElement * > QCPMarginGroup::elements (QCP::MarginSide side) const [inline]
const
Returns a list of all layout elements that have their margin side associated with this margin group.
Definition at line 732 of file qcustomplot.h.
Referenced by clear(), and commonMargin().
                                                               {
    return mChildren.value(side);
  }
bool QCPMarginGroup::isEmpty () const
Returns whether this margin group is empty. If this function returns true, no layout elements use this margin group to synchronize margin sides.
Definition at line 1697 of file qcustomplot.cpp.
References mChildren.
                                   {
  QHashIterator<QCP::MarginSide, QList<QCPLayoutElement *>> it(mChildren);
  while (it.hasNext()) {
    it.next();
    if (!it.value().isEmpty())
      return false;
  }
  return true;
}
void QCPMarginGroup::removeChild (QCP::MarginSide side, QCPLayoutElement * element) [protected]
Definition at line 1776 of file qcustomplot.cpp.
References mChildren.
Referenced by QCPLayoutElement::setMarginGroup().
                                                            {
  if (!mChildren[side].removeOne(element))
    qDebug() << Q_FUNC_INFO << "element is not child of this margin group side"
             << reinterpret_cast<quintptr>(element);
}
Friends And Related Function Documentation
friend class QCPLayoutElement [friend]
Definition at line 751 of file qcustomplot.h.
Member Data Documentation
QHash<QCP::MarginSide, QList<QCPLayoutElement *> > QCPMarginGroup::mChildren [protected]
Definition at line 741 of file qcustomplot.h.
Referenced by addChild(), clear(), commonMargin(), isEmpty(), QCPMarginGroup(), and removeChild().
QCustomPlot* QCPMarginGroup::mParentPlot [protected]
Definition at line 740 of file qcustomplot.h.
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp