QCPColorMap Class Reference
A plottable representing a two-dimensional color map in a plot.
#include <qcustomplot.h>
Signals
void dataRangeChanged (QCPRange newRange)
void dataScaleTypeChanged (QCPAxis::ScaleType scaleType)
void gradientChanged (QCPColorGradient newGradient)
Public Member Functions
QCPColorMap (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPColorMap ()
QCPColorMapData * data () const
QCPRange dataRange () const
QCPAxis::ScaleType dataScaleType () const
bool interpolate () const
bool tightBoundary () const
QCPColorGradient gradient () const
QCPColorScale * colorScale () const
void setData (QCPColorMapData *data, bool copy=false)
Q_SLOT void setDataRange (const QCPRange &dataRange)
Q_SLOT void setDataScaleType (QCPAxis::ScaleType scaleType)
Q_SLOT void setGradient (const QCPColorGradient &gradient)
void setInterpolate (bool enabled)
void setTightBoundary (bool enabled)
void setColorScale (QCPColorScale *colorScale)
void rescaleDataRange (bool recalculateDataBounds=false)
Q_SLOT void updateLegendIcon (Qt::TransformationMode transformMode=Qt::SmoothTransformation, const QSize &thumbSize=QSize(32, 18))
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Protected Member Functions
virtual void updateMapImage ()
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
Protected Attributes
QCPRange mDataRange
QCPAxis::ScaleType mDataScaleType
QCPColorMapData * mMapData
QCPColorGradient mGradient
bool mInterpolate
bool mTightBoundary
QPointer< QCPColorScale > mColorScale
QImage mMapImage
QImage mUndersampledMapImage
QPixmap mLegendIcon
bool mMapImageInvalidated
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a two-dimensional color map in a plot.
The data is stored in the class QCPColorMapData, which can be accessed via the data() method.
A color map has three dimensions to represent a data point: The key dimension, the value dimension and the data dimension. As with other plottables such as graphs, key and value correspond to two orthogonal axes on the QCustomPlot surface that you specify in the QColorMap constructor. The data dimension however is encoded as the color of the point at (key, value).
Set the number of points (or cells) in the key/value dimension via QCPColorMapData::setSize. The plot coordinate range over which these points will be displayed is specified via QCPColorMapData::setRange. The first cell will be centered on the lower range boundary and the last cell will be centered on the upper range boundary. The data can be set by either accessing the cells directly with QCPColorMapData::setCell or by addressing the cells via their plot coordinates with QCPColorMapData::setData. If possible, you should prefer setCell, since it doesn't need to do any coordinate transformation and thus performs a bit better.
The cell with index (0, 0) is at the bottom left, if the color map uses normal (i.e. not reversed) key and value axes.
To show the user which colors correspond to which data values, a QCPColorScale is typically placed to the right of the axis rect. See the documentation there for details on how to add and use a color scale.
Changing the appearance
The central part of the appearance is the color gradient, which can be specified via setGradient. See the documentation of QCPColorGradient for details on configuring a color gradient.
The data range that is mapped to the colors of the gradient can be specified with setDataRange. To make the data range encompass the whole data set minimum to maximum, call rescaleDataRange.
Usage
Like all data representing objects in QCustomPlot, the QCPColorMap is a plottable (QCPAbstractPlottable). So the plottable-interface of QCustomPlot applies (QCustomPlot::plottable, QCustomPlot::addPlottable, QCustomPlot::removePlottable, etc.)
Usually, you first create an instance and add it to the customPlot:
and then modify the properties of the newly created color map, e.g.:
Note
The QCPColorMap always displays the data at equal key/value intervals, even if the key or value axis is set to a logarithmic scaling. If you want to use QCPColorMap with logarithmic axes, you shouldn't use the QCPColorMapData::setData method as it uses a linear transformation to determine the cell index. Rather directly access the cell index with QCPColorMapData::setCell.
Definition at line 3481 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPColorMap::QCPColorMap (QCPAxis * keyAxis, QCPAxis * valueAxis) [explicit]
Constructs a color map with the specified keyAxis and valueAxis.
The constructed QCPColorMap can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the color map.
Definition at line 22345 of file qcustomplot.cpp.
    : QCPAbstractPlottable(keyAxis, valueAxis),
      mDataScaleType(QCPAxis::stLinear),
      mMapData(new QCPColorMapData(10, 10, QCPRange(0, 5),
      QCPRange(0, 5))),
      mInterpolate(true), mTightBoundary(false),
      mMapImageInvalidated(true) {}
QCPColorMap::~QCPColorMap () [virtual]
Definition at line 22351 of file qcustomplot.cpp.
References mMapData.
{ delete mMapData; }
Member Function Documentation
void QCPColorMap::clearData () [virtual]
Clears the colormap data by calling QCPColorMapData::clear() on the internal data. This also resizes the map to 0x0 cells.
Implements QCPAbstractPlottable.
Definition at line 22617 of file qcustomplot.cpp.
References QCPColorMapData::clear(), and mMapData.
{ mMapData->clear(); }
QCPColorScale* QCPColorMap::colorScale () const [inline]
Definition at line 3505 of file qcustomplot.h.
Referenced by setColorScale().
{ return mColorScale.data(); }
QCPColorMapData * QCPColorMap::data () const [inline]
Returns a pointer to the internal data storage of type QCPColorMapData. Access this to modify data points (cells) and the color map key/value range.
See also
setData
Definition at line 3499 of file qcustomplot.h.
Referenced by setData(), and updateLegendIcon().
{ return mMapData; }
QCPRange QCPColorMap::dataRange () const [inline]
Definition at line 3500 of file qcustomplot.h.
{ return mDataRange; }
void QCPColorMap::dataRangeChanged (QCPRange newRange) [signal]
This signal is emitted when the data range changes.
See also
setDataRange
Referenced by setColorScale(), and setDataRange().
QCPAxis::ScaleType QCPColorMap::dataScaleType () const [inline]
Definition at line 3501 of file qcustomplot.h.
{ return mDataScaleType; }
void QCPColorMap::dataScaleTypeChanged (QCPAxis::ScaleType scaleType) [signal]
This signal is emitted when the data scale type changes.
See also
setDataScaleType
Referenced by setColorScale(), and setDataScaleType().
void QCPColorMap::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 22767 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPColorMapData::isEmpty(), QCPAbstractPlottable::keyAxis(), QCPColorMapData::keyRange(), QCPColorMapData::keySize(), QCPRange::lower, QCPColorMapData::mDataModified, mInterpolate, QCPAbstractPlottable::mKeyAxis, mMapData, mMapImage, mMapImageInvalidated, QCPPainter::modes(), mTightBoundary, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPPainter::pmVectorized, updateMapImage(), QCPRange::upper, QCPAbstractPlottable::valueAxis(), QCPColorMapData::valueRange(), and QCPColorMapData::valueSize().
                                          {
  if (mMapData->isEmpty())
    return;
  if (!mKeyAxis || !mValueAxis)
    return;
  applyDefaultAntialiasingHint(painter);
  if (mMapData->mDataModified || mMapImageInvalidated)
    updateMapImage();
  // use buffer if painting vectorized (PDF):
  bool useBuffer = painter->modes().testFlag(QCPPainter::pmVectorized);
  QCPPainter *localPainter = painter; // will be redirected to paint on
                                      // mapBuffer if painting vectorized
  QRectF mapBufferTarget; // the rect in absolute widget coordinates where the
                          // visible map portion/buffer will end up in
  QPixmap mapBuffer;
  double mapBufferPixelRatio =
      3; // factor by which DPI is increased in embedded bitmaps
  if (useBuffer) {
    mapBufferTarget = painter->clipRegion().boundingRect();
    mapBuffer =
        QPixmap((mapBufferTarget.size() * mapBufferPixelRatio).toSize());
    mapBuffer.fill(Qt::transparent);
    localPainter = new QCPPainter(&mapBuffer);
    localPainter->scale(mapBufferPixelRatio, mapBufferPixelRatio);
    localPainter->translate(-mapBufferTarget.topLeft());
  }
  QRectF imageRect =
      QRectF(coordsToPixels(mMapData->keyRange().
      lower,
                            mMapData->valueRange().lower),
             coordsToPixels(mMapData->keyRange().
      upper,
                            mMapData->valueRange().upper)).normalized();
  // extend imageRect to contain outer halves/quarters of bordering/cornering
  // pixels (cells are centered on map range boundary):
  double halfCellWidth = 0; // in pixels
  double halfCellHeight = 0; // in pixels
  if (keyAxis()->orientation() == Qt::Horizontal) {
    if (mMapData->keySize() > 1)
      halfCellWidth =
          0.5 * imageRect.width() / (double)(mMapData->keySize() - 1);
    if (mMapData->valueSize() > 1)
      halfCellHeight =
          0.5 * imageRect.height() / (double)(mMapData->valueSize() - 1);
  } else // keyAxis orientation is Qt::Vertical
  {
    if (mMapData->keySize() > 1)
      halfCellHeight =
          0.5 * imageRect.height() / (double)(mMapData->keySize() - 1);
    if (mMapData->valueSize() > 1)
      halfCellWidth =
          0.5 * imageRect.width() / (double)(mMapData->valueSize() - 1);
  }
  imageRect.adjust(-halfCellWidth, -halfCellHeight, halfCellWidth,
                   halfCellHeight);
  bool mirrorX =
      (keyAxis()->orientation() == Qt::Horizontal ? keyAxis() :
      valueAxis())
          ->rangeReversed();
  bool mirrorY =
      (valueAxis()->orientation() == Qt::Vertical ?
      valueAxis() : keyAxis())
          ->rangeReversed();
  bool smoothBackup =
      localPainter->renderHints().testFlag(QPainter::SmoothPixmapTransform);
  localPainter->setRenderHint(QPainter::SmoothPixmapTransform, mInterpolate);
  QRegion clipBackup;
  if (mTightBoundary) {
    clipBackup = localPainter->clipRegion();
    QRectF tightClipRect =
        QRectF(coordsToPixels(mMapData->keyRange().
      lower,
                              mMapData->valueRange().lower),
               coordsToPixels(mMapData->keyRange().
      upper,
                              mMapData->valueRange().upper)).normalized();
    localPainter->setClipRect(tightClipRect, Qt::IntersectClip);
  }
  localPainter->drawImage(imageRect, mMapImage.mirrored(mirrorX, mirrorY));
  if (mTightBoundary)
    localPainter->setClipRegion(clipBackup);
  localPainter->setRenderHint(QPainter::SmoothPixmapTransform, smoothBackup);
  if (useBuffer) // localPainter painted to mapBuffer, so now draw buffer with
                 // original painter
  {
    delete localPainter;
    painter->drawPixmap(mapBufferTarget.toRect(), mapBuffer);
  }
}
void QCPColorMap::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 22856 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), and mLegendIcon.
                                                           {
  applyDefaultAntialiasingHint(painter);
  // draw map thumbnail:
  if (!mLegendIcon.isNull()) {
    QPixmap scaledIcon = mLegendIcon.scaled(
        rect.size().toSize(), Qt::KeepAspectRatio, Qt::FastTransformation);
    QRectF iconRect = QRectF(0, 0, scaledIcon.width(), scaledIcon.height());
    iconRect.moveCenter(rect.center());
    painter->drawPixmap(iconRect.topLeft(), scaledIcon);
  }
  /*
  // draw frame:
  painter->setBrush(Qt::NoBrush);
  painter->setPen(Qt::black);
  painter->drawRect(rect.adjusted(1, 1, 0, 0));
  */
}
QCPRange QCPColorMap::getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 22876 of file qcustomplot.cpp.
References QCPColorMapData::keyRange(), QCPRange::lower, mMapData, QCPRange::normalize(), QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
                                                                 {
  foundRange = true;
  QCPRange result = mMapData->keyRange();
  result.normalize();
  if (inSignDomain == QCPAbstractPlottable::sdPositive) {
    if (result.lower <= 0 && result.upper > 0)
      result.lower = result.upper * 1e-3;
    else if (result.lower <= 0 && result.upper <= 0)
      foundRange = false;
  } else if (inSignDomain == QCPAbstractPlottable::sdNegative) {
    if (result.upper >= 0 && result.lower < 0)
      result.upper = result.lower * 1e-3;
    else if (result.upper >= 0 && result.lower >= 0)
      foundRange = false;
  }
  return result;
}
QCPRange QCPColorMap::getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 22896 of file qcustomplot.cpp.
References QCPRange::lower, mMapData, QCPRange::normalize(), QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPRange::upper, and QCPColorMapData::valueRange().
                                                                   {
  foundRange = true;
  QCPRange result = mMapData->valueRange();
  result.normalize();
  if (inSignDomain == QCPAbstractPlottable::sdPositive) {
    if (result.lower <= 0 && result.upper > 0)
      result.lower = result.upper * 1e-3;
    else if (result.lower <= 0 && result.upper <= 0)
      foundRange = false;
  } else if (inSignDomain == QCPAbstractPlottable::sdNegative) {
    if (result.upper >= 0 && result.lower < 0)
      result.upper = result.lower * 1e-3;
    else if (result.upper >= 0 && result.lower >= 0)
      foundRange = false;
  }
  return result;
}
QCPColorGradient QCPColorMap::gradient () const [inline]
Definition at line 3504 of file qcustomplot.h.
Referenced by setGradient().
{ return mGradient; }
void QCPColorMap::gradientChanged (QCPColorGradient newGradient) [signal]
This signal is emitted when the gradient changes.
See also
setGradient
Referenced by setColorScale(), and setGradient().
bool QCPColorMap::interpolate () const [inline]
Definition at line 3502 of file qcustomplot.h.
{ return mInterpolate; }
void QCPColorMap::rescaleDataRange (bool recalculateDataBounds = false)
Sets the data range (setDataRange) to span the minimum and maximum values that occur in the current data set. This corresponds to the rescaleKeyAxis or rescaleValueAxis methods, only for the third data dimension of the color map.
The minimum and maximum values of the data set are buffered in the internal QCPColorMapData instance (data). As data is updated via its QCPColorMapData::setCell or QCPColorMapData::setData, the buffered minimum and maximum values are updated, too. For performance reasons, however, they are only updated in an expanding fashion. So the buffered maximum can only increase and the buffered minimum can only decrease. In consequence, changes to the data that actually lower the maximum of the data set (by overwriting the cell holding the current maximum with a smaller value), aren't recognized and the buffered maximum overestimates the true maximum of the data set. The same happens for the buffered minimum. To recalculate the true minimum and maximum by explicitly looking at each cell, the method QCPColorMapData::recalculateDataBounds can be used. For convenience, setting the parameter recalculateDataBounds calls this method before setting the data range to the buffered minimum and maximum.
See also
setDataRange
Definition at line 22566 of file qcustomplot.cpp.
References QCPColorMapData::dataBounds(), mMapData, QCPColorMapData::recalculateDataBounds(), and setDataRange().
                                                             {
  if (recalculateDataBounds)
    mMapData->recalculateDataBounds();
  setDataRange(mMapData->dataBounds());
}
double QCPColorMap::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 22620 of file qcustomplot.cpp.
References QCPRange::contains(), QCPColorMapData::keyRange(), QCPAbstractPlottable::mKeyAxis, mMapData, QCPLayerable::mParentPlot, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, QCPAbstractPlottable::pixelsToCoords(), QCustomPlot::selectionTolerance(), and QCPColorMapData::valueRange().
                                                        {
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return -1;
  }
  if (mKeyAxis.data()->axisRect()->rect().contains(pos.toPoint())) {
    double posKey, posValue;
    pixelsToCoords(pos, posKey, posValue);
    if (mMapData->keyRange().contains(posKey) &&
        mMapData->valueRange().contains(posValue))
      return mParentPlot->selectionTolerance() * 0.99;
  }
  return -1;
}
void QCPColorMap::setColorScale (QCPColorScale * colorScale)
Associates the color scale colorScale with this color map.
This means that both the color scale and the color map synchronize their gradient, data range and data scale type (setGradient, setDataRange, setDataScaleType). Multiple color maps can be associated with one single color scale. This causes the color maps to also synchronize those properties, via the mutual color scale.
This function causes the color map to adopt the current color gradient, data range and data scale type of colorScale. After this call, you may change these properties at either the color map or the color scale, and the setting will be applied to both.
Pass 0 as colorScale to disconnect the color scale from this color map again.
Definition at line 22495 of file qcustomplot.cpp.
References colorScale(), dataRangeChanged(), dataScaleTypeChanged(), gradientChanged(), mColorScale, setDataRange(), setDataScaleType(), and setGradient().
                                                         {
  if (mColorScale) // unconnect signals from old color scale
  {
    disconnect(this, SIGNAL(dataRangeChanged(QCPRange)),
      mColorScale.data(),
               SLOT(setDataRange(QCPRange)));
    disconnect(this, SIGNAL(dataScaleTypeChanged(
      QCPAxis::ScaleType)),
               mColorScale.data(), SLOT(setDataScaleType(
      QCPAxis::ScaleType)));
    disconnect(this, SIGNAL(gradientChanged(QCPColorGradient)),
               mColorScale.data(), SLOT(setGradient(
      QCPColorGradient)));
    disconnect(mColorScale.data(), SIGNAL(dataRangeChanged(
      QCPRange)), this,
               SLOT(setDataRange(QCPRange)));
    disconnect(mColorScale.data(), SIGNAL(gradientChanged(
      QCPColorGradient)),
               this, SLOT(setGradient(QCPColorGradient)));
    disconnect(mColorScale.data(),
               SIGNAL(dataScaleTypeChanged(
      QCPAxis::ScaleType)), this,
               SLOT(setDataScaleType(QCPAxis::ScaleType)));
  }
  mColorScale = colorScale;
  if (mColorScale) // connect signals to new color scale
  {
    setGradient(mColorScale.data()->gradient());
    setDataRange(mColorScale.data()->dataRange());
    setDataScaleType(mColorScale.data()->dataScaleType());
    connect(this, SIGNAL(dataRangeChanged(QCPRange)),
      mColorScale.data(),
            SLOT(setDataRange(QCPRange)));
    connect(this, SIGNAL(dataScaleTypeChanged(
      QCPAxis::ScaleType)),
            mColorScale.data(), SLOT(setDataScaleType(
      QCPAxis::ScaleType)));
    connect(this, SIGNAL(gradientChanged(QCPColorGradient)),
      mColorScale.data(),
            SLOT(setGradient(QCPColorGradient)));
    connect(mColorScale.data(), SIGNAL(dataRangeChanged(
      QCPRange)), this,
            SLOT(setDataRange(QCPRange)));
    connect(mColorScale.data(), SIGNAL(gradientChanged(
      QCPColorGradient)), this,
            SLOT(setGradient(QCPColorGradient)));
    connect(mColorScale.data(),
            SIGNAL(dataScaleTypeChanged(QCPAxis::ScaleType)), this,
            SLOT(setDataScaleType(QCPAxis::ScaleType)));
  }
}
void QCPColorMap::setData (QCPColorMapData * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, the data object will only be copied. if false, the color map takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Definition at line 22362 of file qcustomplot.cpp.
References data(), mMapData, and mMapImageInvalidated.
                                                          {
  if (mMapData == data) {
    qDebug() << Q_FUNC_INFO
             << "The data pointer is already in (and owned by) this plottable"
             << reinterpret_cast<quintptr>(data);
    return;
  }
  if (copy) {
    *mMapData = *data;
  } else {
    delete mMapData;
    mMapData = data;
  }
  mMapImageInvalidated = true;
}
void QCPColorMap::setDataRange (const QCPRange & dataRange)
Sets the data range of this color map to dataRange. The data range defines which data values are mapped to the color gradient.
To make the data range span the full range of the data set, use rescaleDataRange.
See also
QCPColorScale::setDataRange
Definition at line 22388 of file qcustomplot.cpp.
References dataRangeChanged(), QCPRange::lower, mDataRange, mDataScaleType, mMapImageInvalidated, QCPRange::sanitizedForLinScale(), QCPRange::sanitizedForLogScale(), QCPAxis::stLogarithmic, QCPRange::upper, and QCPRange::validRange().
Referenced by rescaleDataRange(), setColorScale(), and setDataScaleType().
                                                        {
  if (!QCPRange::validRange(dataRange))
    return;
  if (mDataRange.lower != dataRange.lower ||
      mDataRange.upper != dataRange.upper) {
    if (mDataScaleType == QCPAxis::stLogarithmic)
      mDataRange = dataRange.sanitizedForLogScale();
    else
      mDataRange = dataRange.sanitizedForLinScale();
    mMapImageInvalidated = true;
    emit dataRangeChanged(mDataRange);
  }
}
void QCPColorMap::setDataScaleType (QCPAxis::ScaleType scaleType)
Sets whether the data is correlated with the color gradient linearly or logarithmically.
See also
QCPColorScale::setDataScaleType
Definition at line 22408 of file qcustomplot.cpp.
References dataScaleTypeChanged(), mDataRange, mDataScaleType, mMapImageInvalidated, QCPRange::sanitizedForLogScale(), setDataRange(), and QCPAxis::stLogarithmic.
Referenced by setColorScale().
                                                             {
  if (mDataScaleType != scaleType) {
    mDataScaleType = scaleType;
    mMapImageInvalidated = true;
    emit dataScaleTypeChanged(mDataScaleType);
    if (mDataScaleType == QCPAxis::stLogarithmic)
      setDataRange(mDataRange.sanitizedForLogScale());
  }
}
void QCPColorMap::setGradient (const QCPColorGradient & gradient)
Sets the color gradient that is used to represent the data. For more details on how to create an own gradient or use one of the preset gradients, see QCPColorGradient.
The colors defined by the gradient will be used to represent data values in the currently set data range, see setDataRange. Data points that are outside this data range will either be colored uniformly with the respective gradient boundary color, or the gradient will repeat, depending on QCPColorGradient::setPeriodic.
See also
QCPColorScale::setGradient
Definition at line 22433 of file qcustomplot.cpp.
References gradient(), gradientChanged(), mGradient, and mMapImageInvalidated.
Referenced by setColorScale().
                                                              {
  if (mGradient != gradient) {
    mGradient = gradient;
    mMapImageInvalidated = true;
    emit gradientChanged(mGradient);
  }
}
void QCPColorMap::setInterpolate (bool enabled)
Sets whether the color map image shall use bicubic interpolation when displaying the color map shrinked or expanded, and not at a 1:1 pixel-to-data scale.
 and without interpolation enabled"
Definition at line 22449 of file qcustomplot.cpp.
References mInterpolate, and mMapImageInvalidated.
                                             {
  mInterpolate = enabled;
  mMapImageInvalidated =
      true; // because oversampling factors might need to change
}
void QCPColorMap::setTightBoundary (bool enabled)
Sets whether the outer most data rows and columns are clipped to the specified key and value range (see QCPColorMapData::setKeyRange, QCPColorMapData::setValueRange).
if enabled is set to false, the data points at the border of the color map are drawn with the same width and height as all other data points. Since the data points are represented by rectangles of one color centered on the data coordinate, this means that the shown color map extends by half a data point over the specified key/value range in each direction.
 enabled and disabled"
Definition at line 22473 of file qcustomplot.cpp.
References mTightBoundary.
{ mTightBoundary = enabled; }
bool QCPColorMap::tightBoundary () const [inline]
Definition at line 3503 of file qcustomplot.h.
{ return mTightBoundary; }
void QCPColorMap::updateLegendIcon (Qt::TransformationMode transformMode = Qt::SmoothTransformation, const QSize & thumbSize = QSize(32, 18))
Takes the current appearance of the color map and updates the legend icon, which is used to represent this color map in the legend (see QCPLegend).
The transformMode specifies whether the rescaling is done by a faster, low quality image scaling algorithm (Qt::FastTransformation) or by a slower, higher quality algorithm (Qt::SmoothTransformation).
The current color map appearance is scaled down to thumbSize. Ideally, this should be equal to the size of the legend icon (see QCPLegend::setIconSize). If it isn't exactly the configured legend icon size, the thumb will be rescaled during drawing of the legend item.
See also
setDataRange
Definition at line 22592 of file qcustomplot.cpp.
References data(), QCPColorMapData::isEmpty(), QCPAbstractPlottable::keyAxis(), mLegendIcon, mMapImage, QCPAxis::orientation(), updateMapImage(), and QCPAbstractPlottable::valueAxis().
                                                           {
  if (mMapImage.isNull() && !data()->isEmpty())
    updateMapImage(); // try to update map image if it's null (happens if no
                      // draw has happened yet)
  if (!mMapImage.isNull()) // might still be null, e.g. if data is empty, so
                           // check here again
  {
    bool mirrorX =
        (keyAxis()->orientation() == Qt::Horizontal ? keyAxis() :
      valueAxis())
            ->rangeReversed();
    bool mirrorY =
        (valueAxis()->orientation() == Qt::Vertical ?
      valueAxis() : keyAxis())
            ->rangeReversed();
    mLegendIcon = QPixmap::fromImage(mMapImage.mirrored(mirrorX, mirrorY))
                      .scaled(thumbSize, Qt::KeepAspectRatio, transformMode);
  }
}
void QCPColorMap::updateMapImage () [protected], [virtual]
Definition at line 22661 of file qcustomplot.cpp.
References QCPColorGradient::colorize(), QCPColorMapData::isEmpty(), QCPAbstractPlottable::keyAxis(), QCPColorMapData::keySize(), QCPColorMapData::mData, QCPColorMapData::mDataModified, mDataRange, mDataScaleType, mGradient, mInterpolate, QCPAbstractPlottable::mKeyAxis, mMapData, mMapImage, mMapImageInvalidated, mUndersampledMapImage, QCPAxis::orientation(), QCPAxis::stLogarithmic, and QCPColorMapData::valueSize().
Referenced by draw(), and updateLegendIcon().
                                 {
  QCPAxis *keyAxis = mKeyAxis.data();
  if (!keyAxis)
    return;
  if (mMapData->isEmpty())
    return;
  const int keySize = mMapData->keySize();
  const int valueSize = mMapData->valueSize();
  int keyOversamplingFactor =
      mInterpolate
          ? 1
          : (int)(1.0 + 100.0 / (double)keySize); // make mMapImage have at
                                                  // least size 100, factor
                                                  // becomes 1 if size > 200 or
                                                  // interpolation is on
  int valueOversamplingFactor =
      mInterpolate
          ? 1
          : (int)(1.0 + 100.0 / (double)valueSize); // make mMapImage have at
                                                    // least size 100, factor
                                                    // becomes 1 if size > 200
                                                    // or interpolation is on
  // resize mMapImage to correct dimensions including possible oversampling
  // factors, according to key/value axes orientation:
  if (keyAxis->orientation() == Qt::Horizontal &&
      (mMapImage.width() != keySize * keyOversamplingFactor ||
       mMapImage.height() != valueSize * valueOversamplingFactor))
    mMapImage = QImage(QSize(keySize * keyOversamplingFactor,
                             valueSize * valueOversamplingFactor),
                       QImage::Format_RGB32);
  else if (keyAxis->orientation() == Qt::Vertical &&
           (mMapImage.width() != valueSize * valueOversamplingFactor ||
            mMapImage.height() != keySize * keyOversamplingFactor))
    mMapImage = QImage(QSize(valueSize * valueOversamplingFactor,
                             keySize * keyOversamplingFactor),
                       QImage::Format_RGB32);
  QImage *localMapImage = &mMapImage; // this is the image on which the
                                      // colorization operates. Either the final
                                      // mMapImage, or if we need oversampling,
                                      // mUndersampledMapImage
  if (keyOversamplingFactor > 1 || valueOversamplingFactor > 1) {
    // resize undersampled map image to actual key/value cell sizes:
    if (keyAxis->orientation() == Qt::Horizontal &&
        (mUndersampledMapImage.width() != keySize ||
         mUndersampledMapImage.height() != valueSize))
      mUndersampledMapImage =
          QImage(QSize(keySize, valueSize), QImage::Format_RGB32);
    else if (keyAxis->orientation() == Qt::Vertical &&
             (mUndersampledMapImage.width() != valueSize ||
              mUndersampledMapImage.height() != keySize))
      mUndersampledMapImage =
          QImage(QSize(valueSize, keySize), QImage::Format_RGB32);
    localMapImage = &mUndersampledMapImage; // make the colorization run on the
                                            // undersampled image
  } else if (!mUndersampledMapImage.isNull())
    mUndersampledMapImage = QImage(); // don't need oversampling mechanism
                                      // anymore (map size has changed) but
                                      // mUndersampledMapImage still has nonzero
                                      // size, free it
  const double *rawData = mMapData->mData;
  if (keyAxis->orientation() == Qt::Horizontal) {
    const int lineCount = valueSize;
    const int rowCount = keySize;
    for (int line = 0; line < lineCount; ++line) {
      QRgb *pixels = reinterpret_cast<QRgb *>(localMapImage->scanLine(
          lineCount - 1 - line)); // invert scanline index because QImage counts
                                  // scanlines from top, but our vertical index
                                  // counts from bottom (mathematical coordinate
                                  // system)
      mGradient.colorize(rawData + line * rowCount, mDataRange, pixels,
                         rowCount, 1, mDataScaleType ==
      QCPAxis::stLogarithmic);
    }
  } else // keyAxis->orientation() == Qt::Vertical
  {
    const int lineCount = keySize;
    const int rowCount = valueSize;
    for (int line = 0; line < lineCount; ++line) {
      QRgb *pixels = reinterpret_cast<QRgb *>(localMapImage->scanLine(
          lineCount - 1 - line)); // invert scanline index because QImage counts
                                  // scanlines from top, but our vertical index
                                  // counts from bottom (mathematical coordinate
                                  // system)
      mGradient.colorize(rawData + line, mDataRange, pixels, rowCount,
                         lineCount, mDataScaleType ==
      QCPAxis::stLogarithmic);
    }
  }
  if (keyOversamplingFactor > 1 || valueOversamplingFactor > 1) {
    if (keyAxis->orientation() == Qt::Horizontal)
      mMapImage = mUndersampledMapImage.scaled(
          keySize * keyOversamplingFactor, valueSize * valueOversamplingFactor,
          Qt::IgnoreAspectRatio, Qt::FastTransformation);
    else
      mMapImage = mUndersampledMapImage.scaled(
          valueSize * valueOversamplingFactor, keySize * keyOversamplingFactor,
          Qt::IgnoreAspectRatio, Qt::FastTransformation);
  }
  mMapData->mDataModified = false;
  mMapImageInvalidated = false;
}
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 3558 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 3557 of file qcustomplot.h.
Member Data Documentation
QPointer<QCPColorScale> QCPColorMap::mColorScale [protected]
Definition at line 3540 of file qcustomplot.h.
Referenced by setColorScale().
QCPRange QCPColorMap::mDataRange [protected]
Definition at line 3534 of file qcustomplot.h.
Referenced by setDataRange(), setDataScaleType(), and updateMapImage().
QCPAxis::ScaleType QCPColorMap::mDataScaleType [protected]
Definition at line 3535 of file qcustomplot.h.
Referenced by setDataRange(), setDataScaleType(), and updateMapImage().
QCPColorGradient QCPColorMap::mGradient [protected]
Definition at line 3537 of file qcustomplot.h.
Referenced by setGradient(), and updateMapImage().
bool QCPColorMap::mInterpolate [protected]
Definition at line 3538 of file qcustomplot.h.
Referenced by draw(), setInterpolate(), and updateMapImage().
QPixmap QCPColorMap::mLegendIcon [protected]
Definition at line 3543 of file qcustomplot.h.
Referenced by drawLegendIcon(), and updateLegendIcon().
QCPColorMapData* QCPColorMap::mMapData [protected]
Definition at line 3536 of file qcustomplot.h.
Referenced by clearData(), draw(), getKeyRange(), getValueRange(), rescaleDataRange(), selectTest(), setData(), updateMapImage(), and ~QCPColorMap().
QImage QCPColorMap::mMapImage [protected]
Definition at line 3542 of file qcustomplot.h.
Referenced by draw(), updateLegendIcon(), and updateMapImage().
bool QCPColorMap::mMapImageInvalidated [protected]
Definition at line 3544 of file qcustomplot.h.
Referenced by draw(), setData(), setDataRange(), setDataScaleType(), setGradient(), setInterpolate(), and updateMapImage().
bool QCPColorMap::mTightBoundary [protected]
Definition at line 3539 of file qcustomplot.h.
Referenced by draw(), and setTightBoundary().
QImage QCPColorMap::mUndersampledMapImage [protected]
Definition at line 3542 of file qcustomplot.h.
Referenced by updateMapImage().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp