QCPPainter Class Reference
QPainter subclass used internally.
#include <qcustomplot.h>
Public Types
enum PainterMode { pmDefault = 0x00,
pmVectorized = 0x01,
pmNoCaching = 0x02,
pmNonCosmetic = 0x04
 }
Public Member Functions
QCPPainter ()
QCPPainter (QPaintDevice *device)
~QCPPainter ()
bool antialiasing () const
PainterModes modes () const
void setAntialiasing (bool enabled)
void setMode (PainterMode mode, bool enabled=true)
void setModes (PainterModes modes)
bool begin (QPaintDevice *device)
void setPen (const QPen &pen)
void setPen (const QColor &color)
void setPen (Qt::PenStyle penStyle)
void drawLine (const QLineF &line)
void drawLine (const QPointF &p1, const QPointF &p2)
void save ()
void restore ()
void makeNonCosmetic ()
Protected Attributes
PainterModes mModes
bool mIsAntialiasing
QStack< bool > mAntialiasingStack
Detailed Description
QPainter subclass used internally.
This QPainter subclass is used to provide some extended functionality e.g. for tweaking position consistency between antialiased and non-antialiased painting. Further it provides workarounds for QPainter quirks.
Warning
This class intentionally hides non-virtual functions of QPainter, e.g. setPen, save and restore. So while it is possible to pass a QCPPainter instance to a function that expects a QPainter pointer, some of the workarounds and tweaks will be unavailable to the function (because it will call the base class implementations of the functions actually hidden by QCPPainter).
Definition at line 312 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPPainter::PainterMode
Defines special modes the painter can operate in. They disable or enable certain subsets of features/fixes/workarounds, depending on whether they are wanted on the respective output device.
Enumerator
pmDefault
 0x00 Default mode for painting on screen devices
pmVectorized
 0x01 Mode for vectorized painting (e.g. PDF export). For example, this prevents some antialiasing fixes.
pmNoCaching
 0x02 Mode for all sorts of exports (e.g. PNG, PDF,...). For example, this prevents using cached pixmap labels
pmNonCosmetic
 0x04 Turns pen widths 0 to 1, i.e. disables cosmetic pens. (A cosmetic pen is always drawn with width 1 pixel in the vector image/pdf viewer, independent of zoom.)
Definition at line 320 of file qcustomplot.h.
                   { pmDefault = 0x00
                     ,pmVectorized = 0x01
                     ,pmNoCaching = 0x02
                     ,pmNonCosmetic = 0x04
                   };
Constructor & Destructor Documentation
QCPPainter::QCPPainter ()
Creates a new QCPPainter instance and sets default values
Definition at line 50 of file qcustomplot.cpp.
                       :
  QPainter(),
  mModes(pmDefault),
  mIsAntialiasing(false)
{
  // don't setRenderHint(QPainter::NonCosmeticDefautPen) here, because painter isn't active yet and
  // a call to begin() will follow
}
QCPPainter::QCPPainter (QPaintDevice * device)
Creates a new QCPPainter instance on the specified paint device and sets default values. Just like the analogous QPainter constructor, begins painting on device immediately.
Like begin, this method sets QPainter::NonCosmeticDefaultPen in Qt versions before Qt5.
Definition at line 65 of file qcustomplot.cpp.
                                           :
  QPainter(device),
  mModes(pmDefault),
  mIsAntialiasing(false)
{
#if QT_VERSION < QT_VERSION_CHECK(5, 0, 0) // before Qt5, default pens used to be cosmetic if
       NonCosmeticDefaultPen flag isn't set. So we set it to get consistency across Qt versions.
  if (isActive())
    setRenderHint(QPainter::NonCosmeticDefaultPen);
#endif
}
QCPPainter::~QCPPainter ()
Definition at line 76 of file qcustomplot.cpp.
{
}
Member Function Documentation
bool QCPPainter::antialiasing () const [inline]
Definition at line 333 of file qcustomplot.h.
Referenced by QCPAxisPainterPrivate::draw().
{ return testRenderHint(QPainter::Antialiasing); }
bool QCPPainter::begin (QPaintDevice * device)
Sets the QPainter::NonCosmeticDefaultPen in Qt versions before Qt5 after beginning painting on device. This is necessary to get cosmetic pen consistency across Qt versions, because since Qt5, all pens are non-cosmetic by default, and in Qt4 this render hint must be set to get that behaviour.
The Constructor QCPPainter(QPaintDevice *device) which directly starts painting also sets the render hint as appropriate.
Note
this function hides the non-virtual base class implementation.
Definition at line 179 of file qcustomplot.cpp.
Referenced by QCustomPlot::replot(), QCustomPlot::savePdf(), and QCustomPlot::toPixmap().
{
  bool result = QPainter::begin(device);
#if QT_VERSION < QT_VERSION_CHECK(5, 0, 0) // before Qt5, default pens used to be cosmetic if
       NonCosmeticDefaultPen flag isn't set. So we set it to get consistency across Qt versions.
  if (result)
    setRenderHint(QPainter::NonCosmeticDefaultPen);
#endif
  return result;
}
void QCPPainter::drawLine (const QLineF & line)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Works around a Qt bug introduced with Qt 4.8 which makes drawing QLineF unpredictable when antialiasing is disabled. Thus when antialiasing is disabled, it rounds the line to integer coordinates and then passes it to the original drawLine.
Note
this function hides the non-virtual base class implementation.
Definition at line 129 of file qcustomplot.cpp.
References mIsAntialiasing, mModes, and pmVectorized.
Referenced by QCPLineEnding::draw(), QCPAxisPainterPrivate::draw(), QCPCurve::draw(), QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemTracer::draw(), QCPItemBracket::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawError(), QCPGrid::drawGridLines(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPFinancial::drawLegendIcon(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawMedian(), QCPFinancial::drawOhlcPlot(), QCPScatterStyle::drawShape(), QCPGrid::drawSubGridLines(), and QCPStatisticalBox::drawWhiskers().
{
  if (mIsAntialiasing || mModes.testFlag(pmVectorized))
    QPainter::drawLine(line);
  else
    QPainter::drawLine(line.toLine());
}
void QCPPainter::drawLine (const QPointF & p1, const QPointF & p2) [inline]
Definition at line 347 of file qcustomplot.h.
References drawLine().
Referenced by drawLine().
{drawLine(QLineF(p1, p2));}
void QCPPainter::makeNonCosmetic ()
Changes the pen width to 1 if it currently is 0. This function is called in the setPen overrides when the pmNonCosmetic mode is set.
Definition at line 237 of file qcustomplot.cpp.
Referenced by setPen().
{
  if (qFuzzyIsNull(pen().widthF()))
  {
    QPen p = pen();
    p.setWidth(1);
    QPainter::setPen(p);
  }
}
PainterModes QCPPainter::modes () const [inline]
Definition at line 334 of file qcustomplot.h.
Referenced by QCPLineEnding::draw(), QCPCurve::draw(), QCPColorMap::draw(), QCPGraph::drawLinePlot(), QCPAxisPainterPrivate::placeTickLabel(), and setModes().
{ return mModes; }
void QCPPainter::restore ()
Restores the painter (see QPainter::restore). Since QCPPainter adds some new internal state to QPainter, the save/restore functions are reimplemented to also save/restore those members.
Note
this function hides the non-virtual base class implementation.
See also
save
Definition at line 224 of file qcustomplot.cpp.
References mAntialiasingStack, and mIsAntialiasing.
Referenced by QCustomPlot::draw(), QCPPlottableLegendItem::draw(), and QCPStatisticalBox::draw().
{
  if (!mAntialiasingStack.isEmpty())
    mIsAntialiasing = mAntialiasingStack.pop();
  else
    qDebug() << Q_FUNC_INFO << "Unbalanced save/restore";
  QPainter::restore();
}
void QCPPainter::save ()
Saves the painter (see QPainter::save). Since QCPPainter adds some new internal state to QPainter, the save/restore functions are reimplemented to also save/restore those members.
Note
this function hides the non-virtual base class implementation.
See also
restore
Definition at line 210 of file qcustomplot.cpp.
References mAntialiasingStack, and mIsAntialiasing.
Referenced by QCustomPlot::draw(), QCPPlottableLegendItem::draw(), and QCPStatisticalBox::draw().
{
  mAntialiasingStack.push(mIsAntialiasing);
  QPainter::save();
}
void QCPPainter::setAntialiasing (bool enabled)
Sets whether painting uses antialiasing or not. Use this method instead of using setRenderHint with QPainter::Antialiasing directly, as it allows QCPPainter to regain pixel exactness between antialiased and non-antialiased painting (Since Qt < 5.0 uses slightly different coordinate systems for AA/Non-AA painting).
Definition at line 143 of file qcustomplot.cpp.
References mIsAntialiasing, mModes, and pmVectorized.
Referenced by QCPLayerable::applyAntialiasingHint(), QCPAxisRect::applyDefaultAntialiasingHint(), QCPColorScale::applyDefaultAntialiasingHint(), QCPAxisPainterPrivate::draw(), and QCPFinancial::drawLegendIcon().
{
  setRenderHint(QPainter::Antialiasing, enabled);
  if (mIsAntialiasing != enabled)
  {
    mIsAntialiasing = enabled;
    if (!mModes.testFlag(pmVectorized)) // antialiasing half-pixel shift only needed for
       rasterized outputs
    {
      if (mIsAntialiasing)
        translate(0.5, 0.5);
      else
        translate(-0.5, -0.5);
    }
  }
}
void QCPPainter::setMode (QCPPainter::PainterMode mode, bool enabled = true)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the mode of the painter. This controls whether the painter shall adjust its fixes/workarounds optimized for certain output devices.
Definition at line 194 of file qcustomplot.cpp.
References mModes.
Referenced by QCustomPlot::savePdf(), QCustomPlot::toPainter(), and QCustomPlot::toPixmap().
{
  if (!enabled && mModes.testFlag(mode))
    mModes &= ~mode;
  else if (enabled && !mModes.testFlag(mode))
    mModes |= mode;
}
void QCPPainter::setModes (PainterModes modes)
Sets the mode of the painter. This controls whether the painter shall adjust its fixes/workarounds optimized for certain output devices.
Definition at line 163 of file qcustomplot.cpp.
References mModes, and modes().
{
  mModes = modes;
}
void QCPPainter::setPen (const QPen & pen)
Sets the pen of the painter and applies certain fixes to it, depending on the mode of this QCPPainter.
Note
this function hides the non-virtual base class implementation.
Definition at line 86 of file qcustomplot.cpp.
References makeNonCosmetic(), mModes, and pmNonCosmetic.
Referenced by QCPScatterStyle::applyTo(), QCPLineEnding::draw(), QCPAxisPainterPrivate::draw(), QCPPlottableLegendItem::draw(), QCPLegend::draw(), QCPPlotTitle::draw(), QCPCurve::draw(), QCPBars::draw(), QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemCurve::draw(), QCPItemRect::draw(), QCPItemText::draw(), QCPItemEllipse::draw(), QCPItemPixmap::draw(), QCPItemTracer::draw(), QCPItemBracket::draw(), QCPFinancial::drawCandlestickPlot(), QCPGraph::drawFill(), QCPGrid::drawGridLines(), QCPGraph::drawImpulsePlot(), QCPGraph::drawLegendIcon(), QCPCurve::drawLegendIcon(), QCPBars::drawLegendIcon(), QCPStatisticalBox::drawLegendIcon(), QCPFinancial::drawLegendIcon(), QCPGraph::drawLinePlot(), QCPStatisticalBox::drawMedian(), QCPFinancial::drawOhlcPlot(), QCPStatisticalBox::drawQuartileBox(), QCPGraph::drawScatterPlot(), QCPGrid::drawSubGridLines(), QCPStatisticalBox::drawWhiskers(), and QCPAxisPainterPrivate::placeTickLabel().
{
  QPainter::setPen(pen);
  if (mModes.testFlag(pmNonCosmetic))
    makeNonCosmetic();
}
void QCPPainter::setPen (const QColor & color)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the pen (by color) of the painter and applies certain fixes to it, depending on the mode of this QCPPainter.
Note
this function hides the non-virtual base class implementation.
Definition at line 100 of file qcustomplot.cpp.
References makeNonCosmetic(), mModes, and pmNonCosmetic.
{
  QPainter::setPen(color);
  if (mModes.testFlag(pmNonCosmetic))
    makeNonCosmetic();
}
void QCPPainter::setPen (Qt::PenStyle penStyle)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the pen (by style) of the painter and applies certain fixes to it, depending on the mode of this QCPPainter.
Note
this function hides the non-virtual base class implementation.
Definition at line 114 of file qcustomplot.cpp.
References makeNonCosmetic(), mModes, and pmNonCosmetic.
{
  QPainter::setPen(penStyle);
  if (mModes.testFlag(pmNonCosmetic))
    makeNonCosmetic();
}
Member Data Documentation
QStack<bool> QCPPainter::mAntialiasingStack [protected]
Definition at line 360 of file qcustomplot.h.
Referenced by restore(), and save().
bool QCPPainter::mIsAntialiasing [protected]
Definition at line 357 of file qcustomplot.h.
Referenced by drawLine(), restore(), save(), and setAntialiasing().
PainterModes QCPPainter::mModes [protected]
Definition at line 356 of file qcustomplot.h.
Referenced by drawLine(), setAntialiasing(), setMode(), setModes(), and setPen().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp