QCPStatisticalBox Class Reference
A plottable representing a single statistical box in a plot.
#include <qcustomplot.h>
Public Member Functions
QCPStatisticalBox (QCPAxis *keyAxis, QCPAxis *valueAxis)
double key () const
double minimum () const
double lowerQuartile () const
double median () const
double upperQuartile () const
double maximum () const
QVector< double > outliers () const
double width () const
double whiskerWidth () const
QPen whiskerPen () const
QPen whiskerBarPen () const
QPen medianPen () const
QCPScatterStyle outlierStyle () const
void setKey (double key)
void setMinimum (double value)
void setLowerQuartile (double value)
void setMedian (double value)
void setUpperQuartile (double value)
void setMaximum (double value)
void setOutliers (const QVector< double > &values)
void setData (double key, double minimum, double lowerQuartile, double median, double upperQuartile, double maximum)
void setWidth (double width)
void setWhiskerWidth (double width)
void setWhiskerPen (const QPen &pen)
void setWhiskerBarPen (const QPen &pen)
void setMedianPen (const QPen &pen)
void setOutlierStyle (const QCPScatterStyle &style)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual void drawQuartileBox (QCPPainter *painter, QRectF *quartileBox=0) const
virtual void drawMedian (QCPPainter *painter) const
virtual void drawWhiskers (QCPPainter *painter) const
virtual void drawOutliers (QCPPainter *painter) const
Protected Attributes
QVector< double > mOutliers
double mKey
double mMinimum
double mLowerQuartile
double mMedian
double mUpperQuartile
double mMaximum
double mWidth
double mWhiskerWidth
QPen mWhiskerPen
QPen mWhiskerBarPen
QPen mMedianPen
QCPScatterStyle mOutlierStyle
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a single statistical box in a plot.
To plot data, assign it with the individual parameter functions or use setData to set all parameters at once. The individual functions are:
setMinimum
setLowerQuartile
setMedian
setUpperQuartile
setMaximum
Additionally you can define a list of outliers, drawn as scatter datapoints:
setOutliers
Changing the appearance
The appearance of the box itself is controlled via setPen and setBrush. You may change the width of the box with setWidth in plot coordinates (not pixels).
Analog functions exist for the minimum/maximum-whiskers: setWhiskerPen, setWhiskerBarPen, setWhiskerWidth. The whisker width is the width of the bar at the top (maximum) and bottom (minimum).
The median indicator line has its own pen, setMedianPen.
If the whisker backbone pen is changed, make sure to set the capStyle to Qt::FlatCap. Else, the backbone line might exceed the whisker bars by a few pixels due to the pen cap being not perfectly flat.
The Outlier data points are drawn as normal scatter points. Their look can be controlled with setOutlierStyle
Usage
Like all data representing objects in QCustomPlot, the QCPStatisticalBox is a plottable. Usually, you first create an instance and add it to the customPlot:
qcpstatisticalbox-creation-1 and then modify the properties of the newly created plottable, e.g.:
qcpstatisticalbox-creation-2
Definition at line 3345 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPStatisticalBox::QCPStatisticalBox (QCPAxis * keyAxis, QCPAxis * valueAxis) [explicit]
Constructs a statistical box which uses keyAxis as its key axis (`x`) and valueAxis as its value axis (`y`). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed statistical box can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the statistical box.
Definition at line 21385 of file qcustomplot.cpp.
References QCPAbstractPlottable::setBrush(), setMedianPen(), setOutlierStyle(), QCPAbstractPlottable::setPen(), QCPAbstractPlottable::setSelectedBrush(), QCPAbstractPlottable::setSelectedPen(), setWhiskerBarPen(), setWhiskerPen(), setWhiskerWidth(), setWidth(), and QCPScatterStyle::ssCircle.
    : QCPAbstractPlottable(keyAxis, valueAxis), mKey(0),
      mMinimum(0),
      mLowerQuartile(0), mMedian(0), mUpperQuartile(0),
      mMaximum(0) {
  setOutlierStyle(QCPScatterStyle(
      QCPScatterStyle::ssCircle, Qt::blue, 6));
  setWhiskerWidth(0.2);
  setWidth(0.5);
  setPen(QPen(Qt::black));
  setSelectedPen(QPen(Qt::blue, 2.5));
  setMedianPen(QPen(Qt::black, 3, Qt::SolidLine, Qt::FlatCap));
  setWhiskerPen(QPen(Qt::black, 0, Qt::DashLine, Qt::FlatCap));
  setWhiskerBarPen(QPen(Qt::black));
  setBrush(Qt::NoBrush);
  setSelectedBrush(Qt::NoBrush);
}
Member Function Documentation
void QCPStatisticalBox::clearData () [virtual]
Clears all data in the plottable.
Implements QCPAbstractPlottable.
Definition at line 21547 of file qcustomplot.cpp.
References setKey(), setLowerQuartile(), setMaximum(), setMedian(), setMinimum(), setOutliers(), and setUpperQuartile().
                                  {
  setOutliers(QVector<double>());
  setKey(0);
  setMinimum(0);
  setLowerQuartile(0);
  setMedian(0);
  setUpperQuartile(0);
  setMaximum(0);
}
void QCPStatisticalBox::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 21586 of file qcustomplot.cpp.
References drawMedian(), drawOutliers(), drawQuartileBox(), drawWhiskers(), i, QCP::isInvalidData(), mKey, QCPAbstractPlottable::mKeyAxis, mLowerQuartile, mMaximum, mMedian, mMinimum, mOutliers, mUpperQuartile, QCPAbstractPlottable::mValueAxis, QCPAbstractPlottable::name(), QCPPainter::restore(), and QCPPainter::save().
                                                {
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
// check data validity if flag set:
#ifdef QCUSTOMPLOT_CHECK_DATA
  if (QCP::isInvalidData(mKey, mMedian) ||
      QCP::isInvalidData(mLowerQuartile,
      mUpperQuartile) ||
      QCP::isInvalidData(mMinimum, mMaximum))
    qDebug() << Q_FUNC_INFO << "Data point at" << mKey
             << "of drawn range has invalid data."
             << "Plottable name:" << name();
  for (int i = 0; i < mOutliers.size(); ++i)
    if (QCP::isInvalidData(mOutliers.at(i)))
      qDebug() << Q_FUNC_INFO << "Data point outlier at" << mKey
               << "of drawn range invalid."
               << "Plottable name:" << name();
#endif
  QRectF quartileBox;
  drawQuartileBox(painter, &quartileBox);
  painter->save();
  painter->setClipRect(quartileBox, Qt::IntersectClip);
  drawMedian(painter);
  painter->restore();
  drawWhiskers(painter);
  drawOutliers(painter);
}
void QCPStatisticalBox::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 21620 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::mBrush, QCPAbstractPlottable::mPen, and QCPPainter::setPen().
                                                                 {
  // draw filled rect:
  applyDefaultAntialiasingHint(painter);
  painter->setPen(mPen);
  painter->setBrush(mBrush);
  QRectF r = QRectF(0, 0, rect.width() * 0.67, rect.height() * 0.67);
  r.moveCenter(rect.center());
  painter->drawRect(r);
}
void QCPStatisticalBox::drawMedian (QCPPainter * painter) const [protected], [virtual]
Definition at line 21656 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPPainter::drawLine(), mKey, mMedian, mMedianPen, mWidth, and QCPPainter::setPen().
Referenced by draw().
                                                            {
  QLineF medianLine;
  medianLine.setP1(coordsToPixels(mKey - mWidth * 0.5,
      mMedian));
  medianLine.setP2(coordsToPixels(mKey + mWidth * 0.5,
      mMedian));
  applyDefaultAntialiasingHint(painter);
  painter->setPen(mMedianPen);
  painter->drawLine(medianLine);
}
void QCPStatisticalBox::drawOutliers (QCPPainter * painter) const [protected], [virtual]
Definition at line 21692 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPScatterStyle::applyTo(), QCPAbstractPlottable::coordsToPixels(), QCPScatterStyle::drawShape(), i, mKey, mOutliers, mOutlierStyle, and QCPAbstractPlottable::mPen.
Referenced by draw().
                                                              {
  applyScattersAntialiasingHint(painter);
  mOutlierStyle.applyTo(painter, mPen);
  for (int i = 0; i < mOutliers.size(); ++i)
    mOutlierStyle.drawShape(painter, coordsToPixels(
      mKey, mOutliers.at(i)));
}
void QCPStatisticalBox::drawQuartileBox (QCPPainter * painter, QRectF * quartileBox = 0) const [protected], [virtual]
Definition at line 21639 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::mainBrush(), QCPAbstractPlottable::mainPen(), mKey, mLowerQuartile, mUpperQuartile, mWidth, and QCPPainter::setPen().
Referenced by draw().
                                                                   {
  QRectF box;
  box.setTopLeft(coordsToPixels(mKey - mWidth * 0.5,
      mUpperQuartile));
  box.setBottomRight(coordsToPixels(mKey + mWidth * 0.5,
      mLowerQuartile));
  applyDefaultAntialiasingHint(painter);
  painter->setPen(mainPen());
  painter->setBrush(mainBrush());
  painter->drawRect(box);
  if (quartileBox)
    *quartileBox = box;
}
void QCPStatisticalBox::drawWhiskers (QCPPainter * painter) const [protected], [virtual]
Definition at line 21669 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyErrorBarsAntialiasingHint(), QCPAbstractPlottable::coordsToPixels(), QCPPainter::drawLine(), mKey, mLowerQuartile, mMaximum, mMinimum, mUpperQuartile, mWhiskerBarPen, mWhiskerPen, mWhiskerWidth, and QCPPainter::setPen().
Referenced by draw().
                                                              {
  QLineF backboneMin, backboneMax, barMin, barMax;
  backboneMax.setPoints(coordsToPixels(mKey, mUpperQuartile),
                        coordsToPixels(mKey, mMaximum));
  backboneMin.setPoints(coordsToPixels(mKey, mLowerQuartile),
                        coordsToPixels(mKey, mMinimum));
  barMax.setPoints(coordsToPixels(mKey - mWhiskerWidth * 0.5,
      mMaximum),
                   coordsToPixels(mKey + mWhiskerWidth * 0.5,
      mMaximum));
  barMin.setPoints(coordsToPixels(mKey - mWhiskerWidth * 0.5,
      mMinimum),
                   coordsToPixels(mKey + mWhiskerWidth * 0.5,
      mMinimum));
  applyErrorBarsAntialiasingHint(painter);
  painter->setPen(mWhiskerPen);
  painter->drawLine(backboneMin);
  painter->drawLine(backboneMax);
  painter->setPen(mWhiskerBarPen);
  painter->drawLine(barMin);
  painter->drawLine(barMax);
}
QCPRange QCPStatisticalBox::getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 21700 of file qcustomplot.cpp.
References mKey, mWidth, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, and QCPAbstractPlottable::sdPositive.
                                                                       {
  foundRange = true;
  if (inSignDomain == sdBoth) {
    return QCPRange(mKey - mWidth * 0.5, mKey + mWidth * 0.5);
  } else if (inSignDomain == sdNegative) {
    if (mKey + mWidth * 0.5 < 0)
      return QCPRange(mKey - mWidth * 0.5, mKey + mWidth * 0.5);
    else if (mKey < 0)
      return QCPRange(mKey - mWidth * 0.5, mKey);
    else {
      foundRange = false;
      return QCPRange();
    }
  } else if (inSignDomain == sdPositive) {
    if (mKey - mWidth * 0.5 > 0)
      return QCPRange(mKey - mWidth * 0.5, mKey + mWidth * 0.5);
    else if (mKey > 0)
      return QCPRange(mKey, mKey + mWidth * 0.5);
    else {
      foundRange = false;
      return QCPRange();
    }
  }
  foundRange = false;
  return QCPRange();
}
QCPRange QCPStatisticalBox::getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 21729 of file qcustomplot.cpp.
References i, mLowerQuartile, mMaximum, mMedian, mMinimum, mOutliers, mUpperQuartile, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, and QCPAbstractPlottable::sdPositive.
                                                                         {
  QVector<double> values; // values that must be considered (i.e. all outliers
                          // and the five box-parameters)
  values.reserve(mOutliers.size() + 5);
  values << mMaximum << mUpperQuartile << mMedian <<
      mLowerQuartile << mMinimum;
  values << mOutliers;
  // go through values and find the ones in legal range:
  bool haveUpper = false;
  bool haveLower = false;
  double upper = 0;
  double lower = 0;
  for (int i = 0; i < values.size(); ++i) {
    if ((inSignDomain == sdNegative && values.at(i) < 0) ||
        (inSignDomain == sdPositive && values.at(i) > 0) ||
        (inSignDomain == sdBoth)) {
      if (values.at(i) > upper || !haveUpper) {
        upper = values.at(i);
        haveUpper = true;
      }
      if (values.at(i) < lower || !haveLower) {
        lower = values.at(i);
        haveLower = true;
      }
    }
  }
  // return the bounds if we found some sensible values:
  if (haveLower && haveUpper) {
    foundRange = true;
    return QCPRange(lower, upper);
  } else // might happen if all values are in other sign domain
  {
    foundRange = false;
    return QCPRange();
  }
}
double QCPStatisticalBox::key () const [inline]
Definition at line 3367 of file qcustomplot.h.
Referenced by setKey().
{ return mKey; }
double QCPStatisticalBox::lowerQuartile () const [inline]
Definition at line 3369 of file qcustomplot.h.
{ return mLowerQuartile; }
double QCPStatisticalBox::maximum () const [inline]
Definition at line 3372 of file qcustomplot.h.
{ return mMaximum; }
double QCPStatisticalBox::median () const [inline]
Definition at line 3370 of file qcustomplot.h.
{ return mMedian; }
QPen QCPStatisticalBox::medianPen () const [inline]
Definition at line 3378 of file qcustomplot.h.
{ return mMedianPen; }
double QCPStatisticalBox::minimum () const [inline]
Definition at line 3368 of file qcustomplot.h.
{ return mMinimum; }
QVector<double> QCPStatisticalBox::outliers () const [inline]
Definition at line 3373 of file qcustomplot.h.
{ return mOutliers; }
QCPScatterStyle QCPStatisticalBox::outlierStyle () const [inline]
Definition at line 3379 of file qcustomplot.h.
{ return mOutlierStyle; }
double QCPStatisticalBox::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 21558 of file qcustomplot.cpp.
References QCPRange::contains(), mKey, QCPAbstractPlottable::mKeyAxis, mLowerQuartile, mMaximum, mMinimum, QCPLayerable::mParentPlot, QCPAbstractPlottable::mSelectable, mUpperQuartile, QCPAbstractPlottable::mValueAxis, mWidth, QCPAbstractPlottable::pixelsToCoords(), and QCustomPlot::selectionTolerance().
                                                              {
  Q_UNUSED(details)
  if (onlySelectable && !mSelectable)
    return -1;
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return -1;
  }
  if (mKeyAxis.data()->axisRect()->rect().contains(pos.toPoint())) {
    double posKey, posValue;
    pixelsToCoords(pos, posKey, posValue);
    // quartile box:
    QCPRange keyRange(mKey - mWidth * 0.5, mKey + mWidth * 0.5);
    QCPRange valueRange(mLowerQuartile, mUpperQuartile);
    if (keyRange.contains(posKey) && valueRange.contains(posValue))
      return mParentPlot->selectionTolerance() * 0.99;
    // min/max whiskers:
    if (QCPRange(mMinimum, mMaximum).contains(posValue))
      return qAbs(mKeyAxis.data()->coordToPixel(mKey) -
                  mKeyAxis.data()->coordToPixel(posKey));
  }
  return -1;
}
void QCPStatisticalBox::setData (double key, double minimum, double lowerQuartile, double median, double upperQuartile, double maximum)
Sets all parameters of the statistical box plot at once.
See also
setKey, setMinimum, setLowerQuartile, setMedian, setUpperQuartile, setMaximum
Definition at line 21482 of file qcustomplot.cpp.
References setKey(), setLowerQuartile(), setMaximum(), setMedian(), setMinimum(), and setUpperQuartile().
                                                                      {
  setKey(key);
  setMinimum(minimum);
  setLowerQuartile(lowerQuartile);
  setMedian(median);
  setUpperQuartile(upperQuartile);
  setMaximum(maximum);
}
void QCPStatisticalBox::setKey (double key)
Sets the key coordinate of the statistical box.
Definition at line 21404 of file qcustomplot.cpp.
References key(), and mKey.
Referenced by clearData(), and setData().
{ mKey = key; }
void QCPStatisticalBox::setLowerQuartile (double value)
Sets the parameter `lower Quartile` of the statistical box plot. This is the lower end of the box. The lower and the upper quartiles are the two statistical quartiles around the median of the sample, they contain 50% of the sample data.
See also
setUpperQuartile, setPen, setBrush, setWidth
Definition at line 21425 of file qcustomplot.cpp.
References mLowerQuartile.
Referenced by clearData(), and setData().
                                                     {
  mLowerQuartile = value;
}
void QCPStatisticalBox::setMaximum (double value)
Sets the parameter `maximum` of the statistical box plot. This is the position of the upper whisker, typically the maximum measurement of the sample that's not considered an outlier.
See also
setMinimum, setWhiskerPen, setWhiskerBarPen, setWhiskerWidth
Definition at line 21461 of file qcustomplot.cpp.
References mMaximum.
Referenced by clearData(), and setData().
{ mMaximum = value; }
void QCPStatisticalBox::setMedian (double value)
Sets the parameter `median` of the statistical box plot. This is the value of the median mark inside the quartile box. The median separates the sample data in half (50% of the sample data is below/above the median).
See also
setMedianPen
Definition at line 21438 of file qcustomplot.cpp.
References mMedian.
Referenced by clearData(), and setData().
{ mMedian = value; }
void QCPStatisticalBox::setMedianPen (const QPen & pen)
Sets the pen used for drawing the median indicator line inside the statistical box.
Definition at line 21535 of file qcustomplot.cpp.
References mMedianPen, and QCPAbstractPlottable::pen().
Referenced by QCPStatisticalBox().
{ mMedianPen = pen; }
void QCPStatisticalBox::setMinimum (double value)
Sets the parameter `minimum` of the statistical box plot. This is the position of the lower whisker, typically the minimum measurement of the sample that's not considered an outlier.
See also
setMaximum, setWhiskerPen, setWhiskerBarPen, setWhiskerWidth
Definition at line 21414 of file qcustomplot.cpp.
References mMinimum.
Referenced by clearData(), and setData().
{ mMinimum = value; }
void QCPStatisticalBox::setOutliers (const QVector< double > & values)
Sets a vector of outlier values that will be drawn as scatters. Any data points in the sample that are not within the whiskers (setMinimum, setMaximum) should be considered outliers and displayed as such.
See also
setOutlierStyle
Definition at line 21472 of file qcustomplot.cpp.
References mOutliers.
Referenced by clearData().
                                                                 {
  mOutliers = values;
}
void QCPStatisticalBox::setOutlierStyle (const QCPScatterStyle & style)
Sets the appearance of the outlier data points.
See also
setOutliers
Definition at line 21542 of file qcustomplot.cpp.
References mOutlierStyle.
Referenced by QCPStatisticalBox().
                                                                    {
  mOutlierStyle = style;
}
void QCPStatisticalBox::setUpperQuartile (double value)
Sets the parameter `upper Quartile` of the statistical box plot. This is the upper end of the box. The lower and the upper quartiles are the two statistical quartiles around the median of the sample, they contain 50% of the sample data.
See also
setLowerQuartile, setPen, setBrush, setWidth
Definition at line 21449 of file qcustomplot.cpp.
References mUpperQuartile.
Referenced by clearData(), and setData().
                                                     {
  mUpperQuartile = value;
}
void QCPStatisticalBox::setWhiskerBarPen (const QPen & pen)
Sets the pen used for drawing the whisker bars (Those are the lines parallel to the key axis at each end of the whisker backbone).
See also
setWhiskerPen
Definition at line 21527 of file qcustomplot.cpp.
References mWhiskerBarPen, and QCPAbstractPlottable::pen().
Referenced by QCPStatisticalBox().
                                                        {
  mWhiskerBarPen = pen;
}
void QCPStatisticalBox::setWhiskerPen (const QPen & pen)
Sets the pen used for drawing the whisker backbone (That's the line parallel to the value axis).
Make sure to set the pen capStyle to Qt::FlatCap to prevent the whisker backbone from reaching a few pixels past the whisker bars, when using a non-zero pen width.
See also
setWhiskerBarPen
Definition at line 21518 of file qcustomplot.cpp.
References mWhiskerPen, and QCPAbstractPlottable::pen().
Referenced by QCPStatisticalBox().
{ mWhiskerPen = pen; }
void QCPStatisticalBox::setWhiskerWidth (double width)
Sets the width of the whiskers (setMinimum, setMaximum) in key coordinates.
See also
setWidth
Definition at line 21506 of file qcustomplot.cpp.
References mWhiskerWidth, and width().
Referenced by QCPStatisticalBox().
{ mWhiskerWidth = width; }
void QCPStatisticalBox::setWidth (double width)
Sets the width of the box in key coordinates.
See also
setWhiskerWidth
Definition at line 21498 of file qcustomplot.cpp.
References mWidth, and width().
Referenced by QCPStatisticalBox().
{ mWidth = width; }
double QCPStatisticalBox::upperQuartile () const [inline]
Definition at line 3371 of file qcustomplot.h.
{ return mUpperQuartile; }
QPen QCPStatisticalBox::whiskerBarPen () const [inline]
Definition at line 3377 of file qcustomplot.h.
{ return mWhiskerBarPen; }
QPen QCPStatisticalBox::whiskerPen () const [inline]
Definition at line 3376 of file qcustomplot.h.
{ return mWhiskerPen; }
double QCPStatisticalBox::whiskerWidth () const [inline]
Definition at line 3375 of file qcustomplot.h.
{ return mWhiskerWidth; }
double QCPStatisticalBox::width () const [inline]
Definition at line 3374 of file qcustomplot.h.
Referenced by setWhiskerWidth(), and setWidth().
{ return mWidth; }
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 3428 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 3427 of file qcustomplot.h.
Member Data Documentation
double QCPStatisticalBox::mKey [protected]
Definition at line 3406 of file qcustomplot.h.
Referenced by draw(), drawMedian(), drawOutliers(), drawQuartileBox(), drawWhiskers(), getKeyRange(), selectTest(), and setKey().
double QCPStatisticalBox::mLowerQuartile [protected]
Definition at line 3406 of file qcustomplot.h.
Referenced by draw(), drawQuartileBox(), drawWhiskers(), getValueRange(), selectTest(), and setLowerQuartile().
double QCPStatisticalBox::mMaximum [protected]
Definition at line 3406 of file qcustomplot.h.
Referenced by draw(), drawWhiskers(), getValueRange(), selectTest(), and setMaximum().
double QCPStatisticalBox::mMedian [protected]
Definition at line 3406 of file qcustomplot.h.
Referenced by draw(), drawMedian(), getValueRange(), and setMedian().
QPen QCPStatisticalBox::mMedianPen [protected]
Definition at line 3409 of file qcustomplot.h.
Referenced by drawMedian(), and setMedianPen().
double QCPStatisticalBox::mMinimum [protected]
Definition at line 3406 of file qcustomplot.h.
Referenced by draw(), drawWhiskers(), getValueRange(), selectTest(), and setMinimum().
QVector<double> QCPStatisticalBox::mOutliers [protected]
Definition at line 3405 of file qcustomplot.h.
Referenced by draw(), drawOutliers(), getValueRange(), and setOutliers().
QCPScatterStyle QCPStatisticalBox::mOutlierStyle [protected]
Definition at line 3410 of file qcustomplot.h.
Referenced by drawOutliers(), and setOutlierStyle().
double QCPStatisticalBox::mUpperQuartile [protected]
Definition at line 3406 of file qcustomplot.h.
Referenced by draw(), drawQuartileBox(), drawWhiskers(), getValueRange(), selectTest(), and setUpperQuartile().
QPen QCPStatisticalBox::mWhiskerBarPen [protected]
Definition at line 3409 of file qcustomplot.h.
Referenced by drawWhiskers(), and setWhiskerBarPen().
QPen QCPStatisticalBox::mWhiskerPen [protected]
Definition at line 3409 of file qcustomplot.h.
Referenced by drawWhiskers(), and setWhiskerPen().
double QCPStatisticalBox::mWhiskerWidth [protected]
Definition at line 3408 of file qcustomplot.h.
Referenced by drawWhiskers(), and setWhiskerWidth().
double QCPStatisticalBox::mWidth [protected]
Definition at line 3407 of file qcustomplot.h.
Referenced by drawMedian(), drawQuartileBox(), getKeyRange(), selectTest(), and setWidth().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp