QCPLayoutGrid Class Reference
A layout that arranges child elements in a grid.
#include <qcustomplot.h>
Public Member Functions
QCPLayoutGrid ()
virtual ~QCPLayoutGrid ()
int rowCount () const
int columnCount () const
QList< double > columnStretchFactors () const
QList< double > rowStretchFactors () const
int columnSpacing () const
int rowSpacing () const
void setColumnStretchFactor (int column, double factor)
void setColumnStretchFactors (const QList< double > &factors)
void setRowStretchFactor (int row, double factor)
void setRowStretchFactors (const QList< double > &factors)
void setColumnSpacing (int pixels)
void setRowSpacing (int pixels)
virtual void updateLayout ()
virtual int elementCount () const
virtual QCPLayoutElement * elementAt (int index) const
virtual QCPLayoutElement * takeAt (int index)
virtual bool take (QCPLayoutElement *element)
virtual QList< QCPLayoutElement * > elements (bool recursive) const
virtual void simplify ()
virtual QSize minimumSizeHint () const
virtual QSize maximumSizeHint () const
QCPLayoutElement * element (int row, int column) const
bool addElement (int row, int column, QCPLayoutElement *element)
bool hasElement (int row, int column)
void expandTo (int newRowCount, int newColumnCount)
void insertRow (int newIndex)
void insertColumn (int newIndex)
Protected Member Functions
void getMinimumRowColSizes (QVector< int > *minColWidths, QVector< int > *minRowHeights) const
void getMaximumRowColSizes (QVector< int > *maxColWidths, QVector< int > *maxRowHeights) const
Protected Attributes
QList< QList< QCPLayoutElement * > > mElements
QList< double > mColumnStretchFactors
QList< double > mRowStretchFactors
int mColumnSpacing
int mRowSpacing
Additional Inherited Members
Detailed Description
A layout that arranges child elements in a grid.
Elements are laid out in a grid with configurable stretch factors (setColumnStretchFactor, setRowStretchFactor) and spacing (setColumnSpacing, setRowSpacing).
Elements can be added to cells via addElement. The grid is expanded if the specified row or column doesn't exist yet. Whether a cell contains a valid layout element can be checked with hasElement, that element can be retrieved with element. If rows and columns that only have empty cells shall be removed, call simplify. Removal of elements is either done by just adding the element to a different layout or by using the QCPLayout interface take or remove.
Row and column insertion can be performed with insertRow and insertColumn.
Definition at line 894 of file qcustomplot.h.
Constructor & Destructor Documentation
QCPLayoutGrid::QCPLayoutGrid () [explicit]
Creates an instance of QCPLayoutGrid and sets default values.
Definition at line 2766 of file qcustomplot.cpp.
: mColumnSpacing(5), mRowSpacing(5) {}
QCPLayoutGrid::~QCPLayoutGrid () [virtual]
Definition at line 2768 of file qcustomplot.cpp.
References QCPLayout::clear().
                              {
  // clear all child layout elements. This is important because only the
  // specific layouts know how
  // to handle removing elements (clear calls virtual removeAt method to do
  // that).
  clear();
}
Member Function Documentation
bool QCPLayoutGrid::addElement (int row, int column, QCPLayoutElement * element)
Adds the element to cell with row and column. If element is already in a layout, it is first removed from there. If row or column don't exist yet, the layout is expanded accordingly.
Returns true if the element was added successfully, i.e. if the cell at row and column didn't already have an element.
See also
element, hasElement, take, remove
Definition at line 2835 of file qcustomplot.cpp.
References QCPLayout::adoptElement(), element(), expandTo(), hasElement(), QCPLayoutElement::layout(), mElements, and QCPLayout::take().
Referenced by QCPLegend::addItem(), and QCustomPlot::QCustomPlot().
                                                                             {
  if (element) {
    if (!hasElement(row, column)) {
      if (element->layout()) // remove from old layout first
        element->layout()->take(element);
      expandTo(row + 1, column + 1);
      mElements[row][column] = element;
      adoptElement(element);
      return true;
    } else
      qDebug() << Q_FUNC_INFO
               << "There is already an element in the specified row/column:"
               << row << column;
  } else
    qDebug() << Q_FUNC_INFO << "Can't add null element to row/column:" << row
             << column;
  return false;
}
int QCPLayoutGrid::columnCount () const
Returns the number of columns in the layout.
See also
rowCount
Definition at line 2815 of file qcustomplot.cpp.
References mElements.
Referenced by elementAt(), elementCount(), elements(), expandTo(), getMaximumRowColSizes(), getMinimumRowColSizes(), hasElement(), insertColumn(), insertRow(), maximumSizeHint(), minimumSizeHint(), setColumnStretchFactor(), simplify(), takeAt(), and updateLayout().
                                     {
  if (mElements.size() > 0)
    return mElements.first().size();
  else
    return 0;
}
int QCPLayoutGrid::columnSpacing () const [inline]
Definition at line 915 of file qcustomplot.h.
{ return mColumnSpacing; }
QList<double> QCPLayoutGrid::columnStretchFactors () const [inline]
Definition at line 913 of file qcustomplot.h.
{ return mColumnStretchFactors; }
QCPLayoutElement * QCPLayoutGrid::element (int row, int column) const
Returns the element in the cell in row and column.
Returns 0 if either the row/column is invalid or if the cell is empty. In those cases, a qDebug message is printed. To check whether a cell exists and isn't empty, use hasElement.
See also
addElement, hasElement
Definition at line 2786 of file qcustomplot.cpp.
References mElements.
Referenced by addElement(), and take().
                                                                  {
  if (row >= 0 && row < mElements.size()) {
    if (column >= 0 && column < mElements.first().size()) {
      if (QCPLayoutElement *result = mElements.at(row).at(column))
        return result;
      else
        qDebug() << Q_FUNC_INFO << "Requested cell is empty. Row:" << row
                 << "Column:" << column;
    } else
      qDebug() << Q_FUNC_INFO << "Invalid column. Row:" << row
               << "Column:" << column;
  } else
    qDebug() << Q_FUNC_INFO << "Invalid row. Row:" << row
             << "Column:" << column;
  return 0;
}
QCPLayoutElement * QCPLayoutGrid::elementAt (int index) const [virtual]
Returns the element in the cell with the given index. If index is invalid, returns 0.
Note that even if index is valid, the respective cell may be empty in some layouts (e.g. QCPLayoutGrid), so this function may return 0 in those cases. You may use this function to check whether a cell is empty or not.
See also
elements, elementCount, takeAt
Implements QCPLayout.
Definition at line 3115 of file qcustomplot.cpp.
References columnCount(), elementCount(), and mElements.
Referenced by QCPLegend::item(), take(), and takeAt().
                                                          {
  if (index >= 0 && index < elementCount())
    return mElements.at(index / columnCount()).at(index %
      columnCount());
  else
    return 0;
}
int QCPLayoutGrid::elementCount () const [virtual]
Returns the number of elements/cells in the layout.
See also
elements, elementAt
Implements QCPLayout.
Definition at line 3112 of file qcustomplot.cpp.
References columnCount(), and rowCount().
Referenced by elementAt(), QCPLegend::itemCount(), and take().
{ return rowCount() * columnCount(); }
QList< QCPLayoutElement * > QCPLayoutGrid::elements (bool recursive) const [virtual]
Returns a list of all child elements in this layout element. If recursive is true, all sub-child elements are included in the list, too.
Warning
There may be entries with value 0 in the returned list. (For example, QCPLayoutGrid may have empty cells which yield 0 at the respective index.)
Reimplemented from QCPLayout.
Definition at line 3150 of file qcustomplot.cpp.
References c, columnCount(), i, mElements, and rowCount().
                                                                      {
  QList<QCPLayoutElement *> result;
  int colC = columnCount();
  int rowC = rowCount();
#if QT_VERSION >= QT_VERSION_CHECK(4, 7, 0)
  result.reserve(colC * rowC);
#endif
  for (int row = 0; row < rowC; ++row) {
    for (int col = 0; col < colC; ++col) {
      result.append(mElements.at(row).at(col));
    }
  }
  if (recursive) {
    int c = result.size();
    for (int i = 0; i < c; ++i) {
      if (result.at(i))
        result << result.at(i)->elements(recursive);
    }
  }
  return result;
}
void QCPLayoutGrid::expandTo (int newRowCount, int newColumnCount)
Expands the layout to have newRowCount rows and newColumnCount columns. So the last valid row index will be newRowCount-1, the last valid column index will be newColumnCount-1.
If the current column/row count is already larger or equal to newColumnCount/newRowCount, this function does nothing in that dimension.
Newly created cells are empty, new rows and columns have the stretch factor 1.
Note that upon a call to addElement, the layout is expanded automatically to contain the specified row and column, using this function.
See also
simplify
Definition at line 3008 of file qcustomplot.cpp.
References columnCount(), i, mColumnStretchFactors, mElements, mRowStretchFactors, and rowCount().
Referenced by addElement(), insertColumn(), and insertRow().
                                                                {
  // add rows as necessary:
  while (rowCount() < newRowCount) {
    mElements.append(QList<QCPLayoutElement *>());
    mRowStretchFactors.append(1);
  }
  // go through rows and expand columns as necessary:
  int newColCount = qMax(columnCount(), newColumnCount);
  for (int i = 0; i < rowCount(); ++i) {
    while (mElements.at(i).size() < newColCount)
      mElements[i].append(0);
  }
  while (mColumnStretchFactors.size() < newColCount)
    mColumnStretchFactors.append(1);
}
void QCPLayoutGrid::getMaximumRowColSizes (QVector< int > * maxColWidths, QVector< int > * maxRowHeights) const [protected]
Definition at line 3296 of file qcustomplot.cpp.
References columnCount(), mElements, and rowCount().
Referenced by maximumSizeHint(), and updateLayout().
                                                                             {
  *maxColWidths = QVector<int>(columnCount(), QWIDGETSIZE_MAX);
  *maxRowHeights = QVector<int>(rowCount(), QWIDGETSIZE_MAX);
  for (int row = 0; row < rowCount(); ++row) {
    for (int col = 0; col < columnCount(); ++col) {
      if (mElements.at(row).at(col)) {
        QSize maxHint = mElements.at(row).at(col)->maximumSizeHint();
        QSize max = mElements.at(row).at(col)->maximumSize();
        QSize final(
            max.width() < QWIDGETSIZE_MAX ? max.width() : maxHint.width(),
            max.height() < QWIDGETSIZE_MAX ? max.height() : maxHint.height());
        if (maxColWidths->at(col) > final.width())
          (*maxColWidths)[col] = final.width();
        if (maxRowHeights->at(row) > final.height())
          (*maxRowHeights)[row] = final.height();
      }
    }
  }
}
void QCPLayoutGrid::getMinimumRowColSizes (QVector< int > * minColWidths, QVector< int > * minRowHeights) const [protected]
Definition at line 3261 of file qcustomplot.cpp.
References columnCount(), mElements, and rowCount().
Referenced by minimumSizeHint(), and updateLayout().
                                                                             {
  *minColWidths = QVector<int>(columnCount(), 0);
  *minRowHeights = QVector<int>(rowCount(), 0);
  for (int row = 0; row < rowCount(); ++row) {
    for (int col = 0; col < columnCount(); ++col) {
      if (mElements.at(row).at(col)) {
        QSize minHint = mElements.at(row).at(col)->minimumSizeHint();
        QSize min = mElements.at(row).at(col)->minimumSize();
        QSize final(min.width() > 0 ? min.width() : minHint.width(),
                    min.height() > 0 ? min.height() : minHint.height());
        if (minColWidths->at(col) < final.width())
          (*minColWidths)[col] = final.width();
        if (minRowHeights->at(row) < final.height())
          (*minRowHeights)[row] = final.height();
      }
    }
  }
}
bool QCPLayoutGrid::hasElement (int row, int column)
Returns whether the cell at row and column exists and contains a valid element, i.e. isn't empty.
See also
element
Definition at line 2861 of file qcustomplot.cpp.
References columnCount(), mElements, and rowCount().
Referenced by addElement().
                                                  {
  if (row >= 0 && row < rowCount() && column >= 0 && column <
      columnCount())
    return mElements.at(row).at(column);
  else
    return false;
}
void QCPLayoutGrid::insertColumn (int newIndex)
Inserts a new column with empty cells at the column index newIndex. Valid values for newIndex range from 0 (inserts a row at the left) to rowCount (appends a row at the right).
See also
insertRow
Definition at line 3061 of file qcustomplot.cpp.
References columnCount(), expandTo(), mColumnStretchFactors, mElements, and rowCount().
                                             {
  if (mElements.isEmpty() ||
      mElements.first()
          .isEmpty()) // if grid is completely empty, add first cell
  {
    expandTo(1, 1);
    return;
  }
  if (newIndex < 0)
    newIndex = 0;
  if (newIndex > columnCount())
    newIndex = columnCount();
  mColumnStretchFactors.insert(newIndex, 1);
  for (int row = 0; row < rowCount(); ++row)
    mElements[row].insert(newIndex, (QCPLayoutElement *)0);
}
void QCPLayoutGrid::insertRow (int newIndex)
Inserts a new row with empty cells at the row index newIndex. Valid values for newIndex range from 0 (inserts a row at the top) to rowCount (appends a row at the bottom).
See also
insertColumn
Definition at line 3032 of file qcustomplot.cpp.
References columnCount(), expandTo(), mElements, mRowStretchFactors, and rowCount().
                                          {
  if (mElements.isEmpty() ||
      mElements.first()
          .isEmpty()) // if grid is completely empty, add first cell
  {
    expandTo(1, 1);
    return;
  }
  if (newIndex < 0)
    newIndex = 0;
  if (newIndex > rowCount())
    newIndex = rowCount();
  mRowStretchFactors.insert(newIndex, 1);
  QList<QCPLayoutElement *> newRow;
  for (int col = 0; col < columnCount(); ++col)
    newRow.append((QCPLayoutElement *)0);
  mElements.insert(newIndex, newRow);
}
QSize QCPLayoutGrid::maximumSizeHint () const [virtual]
Returns the maximum size this layout element (the inner rect) may be expanded to.
if a maximum size (setMaximumSize) was not set manually, parent layouts consult this function to determine the maximum allowed size of this layout element. (A manual maximum size is considered set if it is smaller than Qt's QWIDGETSIZE_MAX.)
Reimplemented from QCPLayoutElement.
Definition at line 3230 of file qcustomplot.cpp.
References columnCount(), getMaximumRowColSizes(), i, mColumnSpacing, QCPLayoutElement::mMargins, mRowSpacing, and rowCount().
                                           {
  QVector<int> maxColWidths, maxRowHeights;
  getMaximumRowColSizes(&maxColWidths, &maxRowHeights);
  QSize result(0, 0);
  for (int i = 0; i < maxColWidths.size(); ++i)
    result.setWidth(qMin(result.width() + maxColWidths.at(i), QWIDGETSIZE_MAX));
  for (int i = 0; i < maxRowHeights.size(); ++i)
    result.setHeight(
        qMin(result.height() + maxRowHeights.at(i), QWIDGETSIZE_MAX));
  result.rwidth() += qMax(0, columnCount() - 1) * mColumnSpacing +
                     mMargins.left() + mMargins.right();
  result.rheight() += qMax(0, rowCount() - 1) * mRowSpacing +
      mMargins.top() +
                      mMargins.bottom();
  return result;
}
QSize QCPLayoutGrid::minimumSizeHint () const [virtual]
Returns the minimum size this layout element (the inner rect) may be compressed to.
if a minimum size (setMinimumSize) was not set manually, parent layouts consult this function to determine the minimum allowed size of this layout element. (A manual minimum size is considered set if it is non-zero.)
Reimplemented from QCPLayoutElement.
Definition at line 3214 of file qcustomplot.cpp.
References columnCount(), getMinimumRowColSizes(), i, mColumnSpacing, QCPLayoutElement::mMargins, mRowSpacing, and rowCount().
Referenced by QCustomPlot::minimumSizeHint(), and QCustomPlot::sizeHint().
                                           {
  QVector<int> minColWidths, minRowHeights;
  getMinimumRowColSizes(&minColWidths, &minRowHeights);
  QSize result(0, 0);
  for (int i = 0; i < minColWidths.size(); ++i)
    result.rwidth() += minColWidths.at(i);
  for (int i = 0; i < minRowHeights.size(); ++i)
    result.rheight() += minRowHeights.at(i);
  result.rwidth() += qMax(0, columnCount() - 1) * mColumnSpacing +
                     mMargins.left() + mMargins.right();
  result.rheight() += qMax(0, rowCount() - 1) * mRowSpacing +
      mMargins.top() +
                      mMargins.bottom();
  return result;
}
int QCPLayoutGrid::rowCount () const
Returns the number of rows in the layout.
See also
columnCount
Definition at line 2808 of file qcustomplot.cpp.
References mElements.
Referenced by QCPLegend::addItem(), elementCount(), elements(), expandTo(), getMaximumRowColSizes(), getMinimumRowColSizes(), hasElement(), insertColumn(), insertRow(), maximumSizeHint(), minimumSizeHint(), setRowStretchFactor(), simplify(), and updateLayout().
{ return mElements.size(); }
int QCPLayoutGrid::rowSpacing () const [inline]
Definition at line 916 of file qcustomplot.h.
{ return mRowSpacing; }
QList<double> QCPLayoutGrid::rowStretchFactors () const [inline]
Definition at line 914 of file qcustomplot.h.
{ return mRowStretchFactors; }
void QCPLayoutGrid::setColumnSpacing (int pixels)
Sets the gap that is left blank between columns to pixels.
See also
setRowSpacing
Definition at line 2981 of file qcustomplot.cpp.
References mColumnSpacing.
Referenced by QCPLegend::QCPLegend().
{ mColumnSpacing = pixels; }
void QCPLayoutGrid::setColumnStretchFactor (int column, double factor)
Sets the stretch factor of column.
Stretch factors control the relative sizes of rows and columns. Cells will not be resized beyond their minimum and maximum widths/heights (QCPLayoutElement::setMinimumSize, QCPLayoutElement::setMaximumSize), regardless of the stretch factor.
The default stretch factor of newly created rows/columns is 1.
See also
setColumnStretchFactors, setRowStretchFactor
Definition at line 2881 of file qcustomplot.cpp.
References columnCount(), and mColumnStretchFactors.
                                                                    {
  if (column >= 0 && column < columnCount()) {
    if (factor > 0)
      mColumnStretchFactors[column] = factor;
    else
      qDebug() << Q_FUNC_INFO
               << "Invalid stretch factor, must be positive:" << factor;
  } else
    qDebug() << Q_FUNC_INFO << "Invalid column:" << column;
}
void QCPLayoutGrid::setColumnStretchFactors (const QList< double > & factors)
Sets the stretch factors of all columns. factors must have the size columnCount.
Stretch factors control the relative sizes of rows and columns. Cells will not be resized beyond their minimum and maximum widths/heights (QCPLayoutElement::setMinimumSize, QCPLayoutElement::setMaximumSize), regardless of the stretch factor.
The default stretch factor of newly created rows/columns is 1.
See also
setColumnStretchFactor, setRowStretchFactors
Definition at line 2906 of file qcustomplot.cpp.
References i, and mColumnStretchFactors.
                                                                        {
  if (factors.size() == mColumnStretchFactors.size()) {
    mColumnStretchFactors = factors;
    for (int i = 0; i < mColumnStretchFactors.size(); ++i) {
      if (mColumnStretchFactors.at(i) <= 0) {
        qDebug() << Q_FUNC_INFO << "Invalid stretch factor, must be positive:"
                 << mColumnStretchFactors.at(i);
        mColumnStretchFactors[i] = 1;
      }
    }
  } else
    qDebug() << Q_FUNC_INFO
             << "Column count not equal to passed stretch factor count:"
             << factors;
}
void QCPLayoutGrid::setRowSpacing (int pixels)
Sets the gap that is left blank between rows to pixels.
See also
setColumnSpacing
Definition at line 2988 of file qcustomplot.cpp.
References mRowSpacing.
Referenced by QCPLegend::QCPLegend().
{ mRowSpacing = pixels; }
void QCPLayoutGrid::setRowStretchFactor (int row, double factor)
Sets the stretch factor of row.
Stretch factors control the relative sizes of rows and columns. Cells will not be resized beyond their minimum and maximum widths/heights (QCPLayoutElement::setMinimumSize, QCPLayoutElement::setMaximumSize), regardless of the stretch factor.
The default stretch factor of newly created rows/columns is 1.
See also
setColumnStretchFactors, setRowStretchFactor
Definition at line 2935 of file qcustomplot.cpp.
References mRowStretchFactors, and rowCount().
                                                              {
  if (row >= 0 && row < rowCount()) {
    if (factor > 0)
      mRowStretchFactors[row] = factor;
    else
      qDebug() << Q_FUNC_INFO
               << "Invalid stretch factor, must be positive:" << factor;
  } else
    qDebug() << Q_FUNC_INFO << "Invalid row:" << row;
}
void QCPLayoutGrid::setRowStretchFactors (const QList< double > & factors)
Sets the stretch factors of all rows. factors must have the size rowCount.
Stretch factors control the relative sizes of rows and columns. Cells will not be resized beyond their minimum and maximum widths/heights (QCPLayoutElement::setMinimumSize, QCPLayoutElement::setMaximumSize), regardless of the stretch factor.
The default stretch factor of newly created rows/columns is 1.
See also
setRowStretchFactor, setColumnStretchFactors
Definition at line 2960 of file qcustomplot.cpp.
References i, and mRowStretchFactors.
                                                                     {
  if (factors.size() == mRowStretchFactors.size()) {
    mRowStretchFactors = factors;
    for (int i = 0; i < mRowStretchFactors.size(); ++i) {
      if (mRowStretchFactors.at(i) <= 0) {
        qDebug() << Q_FUNC_INFO << "Invalid stretch factor, must be positive:"
                 << mRowStretchFactors.at(i);
        mRowStretchFactors[i] = 1;
      }
    }
  } else
    qDebug() << Q_FUNC_INFO
             << "Row count not equal to passed stretch factor count:"
             << factors;
}
void QCPLayoutGrid::simplify () [virtual]
Simplifies the layout by collapsing rows and columns which only contain empty cells.
Reimplemented from QCPLayout.
Definition at line 3176 of file qcustomplot.cpp.
References columnCount(), mColumnStretchFactors, mElements, mRowStretchFactors, QCPLayout::removeAt(), and rowCount().
Referenced by QCPLegend::removeItem().
                             {
  // remove rows with only empty cells:
  for (int row = rowCount() - 1; row >= 0; --row) {
    bool hasElements = false;
    for (int col = 0; col < columnCount(); ++col) {
      if (mElements.at(row).at(col)) {
        hasElements = true;
        break;
      }
    }
    if (!hasElements) {
      mRowStretchFactors.removeAt(row);
      mElements.removeAt(row);
      if (mElements.isEmpty()) // removed last element, also remove stretch
                               // factor (wouldn't happen below because also
                               // columnCount changed to 0 now)
        mColumnStretchFactors.clear();
    }
  }
  // remove columns with only empty cells:
  for (int col = columnCount() - 1; col >= 0; --col) {
    bool hasElements = false;
    for (int row = 0; row < rowCount(); ++row) {
      if (mElements.at(row).at(col)) {
        hasElements = true;
        break;
      }
    }
    if (!hasElements) {
      mColumnStretchFactors.removeAt(col);
      for (int row = 0; row < rowCount(); ++row)
        mElements[row].removeAt(col);
    }
  }
}
bool QCPLayoutGrid::take (QCPLayoutElement * element) [virtual]
Removes the specified element from the layout and returns true on success.
If the element isn't in this layout, returns false.
Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify.
See also
takeAt
Implements QCPLayout.
Definition at line 3135 of file qcustomplot.cpp.
References element(), elementAt(), elementCount(), i, and takeAt().
                                                  {
  if (element) {
    for (int i = 0; i < elementCount(); ++i) {
      if (elementAt(i) == element) {
        takeAt(i);
        return true;
      }
    }
    qDebug() << Q_FUNC_INFO << "Element not in this layout, couldn't take";
  } else
    qDebug() << Q_FUNC_INFO << "Can't take null element";
  return false;
}
QCPLayoutElement * QCPLayoutGrid::takeAt (int index) [virtual]
Removes the element with the given index from the layout and returns it.
If the index is invalid or the cell with that index is empty, returns 0.
Note that some layouts don't remove the respective cell right away but leave an empty cell after successful removal of the layout element. To collapse empty cells, use simplify.
See also
elementAt, take
Implements QCPLayout.
Definition at line 3123 of file qcustomplot.cpp.
References columnCount(), elementAt(), mElements, and QCPLayout::releaseElement().
Referenced by take().
                                                 {
  if (QCPLayoutElement *el = elementAt(index)) {
    releaseElement(el);
    mElements[index / columnCount()][index % columnCount()] = 0;
    return el;
  } else {
    qDebug() << Q_FUNC_INFO << "Attempt to take invalid index:" << index;
    return 0;
  }
}
void QCPLayoutGrid::updateLayout () [virtual]
Reimplemented from QCPLayout.
Definition at line 3081 of file qcustomplot.cpp.
References columnCount(), getMaximumRowColSizes(), getMinimumRowColSizes(), QCPLayout::getSectionSizes(), mColumnSpacing, mColumnStretchFactors, mElements, QCPLayoutElement::mRect, mRowSpacing, mRowStretchFactors, and rowCount().
                                 {
  QVector<int> minColWidths, minRowHeights, maxColWidths, maxRowHeights;
  getMinimumRowColSizes(&minColWidths, &minRowHeights);
  getMaximumRowColSizes(&maxColWidths, &maxRowHeights);
  int totalRowSpacing = (rowCount() - 1) * mRowSpacing;
  int totalColSpacing = (columnCount() - 1) * mColumnSpacing;
  QVector<int> colWidths = getSectionSizes(maxColWidths, minColWidths,
                                           mColumnStretchFactors.toVector(),
                                           mRect.width() - totalColSpacing);
  QVector<int> rowHeights = getSectionSizes(maxRowHeights, minRowHeights,
                                            mRowStretchFactors.toVector(),
                                            mRect.height() - totalRowSpacing);
  // go through cells and set rects accordingly:
  int yOffset = mRect.top();
  for (int row = 0; row < rowCount(); ++row) {
    if (row > 0)
      yOffset += rowHeights.at(row - 1) + mRowSpacing;
    int xOffset = mRect.left();
    for (int col = 0; col < columnCount(); ++col) {
      if (col > 0)
        xOffset += colWidths.at(col - 1) + mColumnSpacing;
      if (mElements.at(row).at(col))
        mElements.at(row).at(col)->setOuterRect(
            QRect(xOffset, yOffset, colWidths.at(col), rowHeights.at(row)));
    }
  }
}
Member Data Documentation
int QCPLayoutGrid::mColumnSpacing [protected]
Definition at line 950 of file qcustomplot.h.
Referenced by maximumSizeHint(), minimumSizeHint(), setColumnSpacing(), and updateLayout().
QList<double> QCPLayoutGrid::mColumnStretchFactors [protected]
Definition at line 948 of file qcustomplot.h.
Referenced by expandTo(), insertColumn(), setColumnStretchFactor(), setColumnStretchFactors(), simplify(), and updateLayout().
QList<QList<QCPLayoutElement *> > QCPLayoutGrid::mElements [protected]
Definition at line 947 of file qcustomplot.h.
Referenced by addElement(), columnCount(), element(), elementAt(), elements(), expandTo(), getMaximumRowColSizes(), getMinimumRowColSizes(), hasElement(), insertColumn(), insertRow(), rowCount(), simplify(), takeAt(), and updateLayout().
int QCPLayoutGrid::mRowSpacing [protected]
Definition at line 950 of file qcustomplot.h.
Referenced by maximumSizeHint(), minimumSizeHint(), setRowSpacing(), and updateLayout().
QList<double> QCPLayoutGrid::mRowStretchFactors [protected]
Definition at line 949 of file qcustomplot.h.
Referenced by expandTo(), insertRow(), setRowStretchFactor(), setRowStretchFactors(), simplify(), and updateLayout().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp