SoilMath::FFT Class Reference
Fast Fourier Transform class.
#include <FFT.h>
Public Member Functions
FFT ()
Standard constructor.
~FFT ()
Standard deconstructor.
ComplexVect_t GetDescriptors (const cv::Mat &img)
Transforming the img to the frequency domain and returning the Fourier Descriptors.
Private Member Functions
ComplexVect_t Contour2Complex (const cv::Mat &img, float centerCol, float centerRow)
Contour2Complex a private function which translates a continous contour image to a vector of complex values. The contour is found using a depth first search with extension list. The alghorithm is based upon MIT opencourseware 6-034-artificial-intelligence lecture 4
iContour_t Neighbors (uchar *O, int pixel, uint32_t columns, uint32_t rows)
Neighbors a private function returning the neighboring pixels which belong to a contour.
void fft (ComplexArray_t &CA)
fft a private function calculating the Fast Fourier Transform let $ m $ be an integer and let $ N=2^m $ also $ CA=[x_0,\ldots,x_{N-1}] $ is an $ N $ dimensional complex vector let $ \omega=\exp({-2\pi i\over N}) $ then $ c_k={\frac{1}{N}}\sum_{j=0}^{j=N-1}CA_j\omega^{jk} $
void ifft (ComplexArray_t &CA)
ifft
Private Attributes
ComplexVect_t fftDescriptors
ComplexVect_t complexcontour
cv::Mat Img
Detailed Description
Fast Fourier Transform class.
Use this class to transform a black and white blob presented as a cv::Mat with values 0 or 1 to a vector of complex values representing the Fourier Descriptors.
Definition at line 31 of file FFT.h.
Constructor & Destructor Documentation
SoilMath::FFT::FFT ()
Standard constructor.
Definition at line 11 of file FFT.cpp.
{}
SoilMath::FFT::~FFT ()
Standard deconstructor.
Definition at line 13 of file FFT.cpp.
{}
Member Function Documentation
ComplexVect_t SoilMath::FFT::Contour2Complex (const cv::Mat & img, float centerCol, float centerRow) [private]
Contour2Complex a private function which translates a continous contour image to a vector of complex values. The contour is found using a depth first search with extension list. The alghorithm is based upon MIT opencourseware 6-034-artificial-intelligence lecture 4
Parameters
img contour in the form of a cv::Mat type CV_8UC1. Which should consist of a continous contour. $ \{ img \in \mathbb{Z} | 0 \leq img \leq 1 \} $
centerCol centre of the contour X value
centerRow centre of the contour Y value
Returns
a vector with complex values, represing the contour as a function
Definition at line 64 of file FFT.cpp.
References i, j, and Neighbors().
Referenced by GetDescriptors().
                                                    {
  uchar *O = img.data;
  uint32_t pEnd = img.cols * img.rows;
  std::deque<std::deque<uint32_t>> sCont;
  std::deque<uint32_t> eList;
  // Initialize the queue
  for (uint32_t i = 0; i < pEnd; i++) {
    if (O[i] == 1) {
      std::deque<uint32_t> tmpQ;
      tmpQ.push_back(i);
      sCont.push_back(tmpQ);
      break;
    }
  }
  if (sCont.front().size() < 1) {
    throw Exception::MathException("No contour found in image!");
  } // Exception handling
  uint32_t prev = -1;
  // Extend path on queue
  for (uint32_t i = sCont.front().front(); i < pEnd;) {
    iContour_t nBors =
        Neighbors(O, i, img.cols, img.rows); // find neighboring pixels
    std::deque<uint32_t> cQ = sCont.front(); // store first queue;
    sCont.erase(sCont.begin()); // erase first queue from beginning
    if (cQ.size() > 1) {
      prev = cQ.size() - 2;
    } else {
      prev = 0;
    }
    // Loop through each neighbor
    for (uint32_t j = 0; j < nBors.size(); j++) {
      if (nBors[j] != cQ[prev]) // No backtracking
      {
        if (nBors[j] == cQ.front() && cQ.size() > 8) {
          i = pEnd;
        } // Back at first node
        if (std::find(eList.begin(), eList.end(), nBors[j]) ==
            eList.end()) // Check if this current route is extended elsewhere
        {
          std::deque<uint32_t> nQ = cQ;
          nQ.push_back(nBors[j]); // Add the neighbor to the queue
          sCont.push_front(nQ); // add the sequence to the front of the queue
        }
      }
    }
    if (nBors.size() > 2) {
      eList.push_back(i);
    } // if there are multiple choices put current node in extension List
    if (i != pEnd) {
      i = sCont.front().back();
    } // If it isn't the end set i to the last node of the first queue
    if (sCont.size() == 0) {
      throw Exception::MathException(
          "No continuous contour found, or less then 8 pixels long!");
    }
  }
  // convert the first queue to a complex normalized vector
  Complex_t cPoint;
  ComplexVect_t contour;
  float col = 0.0;
  // Normalize and convert the complex function
  for_each(
      sCont.front().begin(), sCont.front().end(),
      [&img, &cPoint, &contour, &centerCol, &centerRow, &col](uint32_t &e) {
        col = (float)((e % img.cols) - centerCol);
        if (col == 0.0) {
          cPoint.real(1.0);
        } else {
          cPoint.real((float)(col / centerCol));
        }
        cPoint.imag((float)((floorf(e / img.cols) - centerRow) / centerRow));
        contour.push_back(cPoint);
      });
  return contour;
}
void SoilMath::FFT::fft (ComplexArray_t & CA) [private]
fft a private function calculating the Fast Fourier Transform let $ m $ be an integer and let $ N=2^m $ also $ CA=[x_0,\ldots,x_{N-1}] $ is an $ N $ dimensional complex vector let $ \omega=\exp({-2\pi i\over N}) $ then $ c_k={\frac{1}{N}}\sum_{j=0}^{j=N-1}CA_j\omega^{jk} $
Parameters
CA a $ CA=[x_0,\ldots,x_{N-1}] $ is an $ N $ dimensional complex vector
Definition at line 148 of file FFT.cpp.
Referenced by GetDescriptors(), and ifft().
                                {
  const size_t N = CA.size();
  if (N <= 1) {
    return;
  }
  ComplexArray_t even = CA[std::slice(0, N / 2, 2)];
  ComplexArray_t odd = CA[std::slice(1, N / 2, 2)];
  fft(even);
  fft(odd);
  for (size_t k = 0; k < N / 2; ++k) {
    Complex_t ct = std::polar(1.0, -2 * M_PI * k / N) * odd[k];
    CA[k] = even[k] + ct;
    CA[k + N / 2] = even[k] - ct;
  }
}
ComplexVect_t SoilMath::FFT::GetDescriptors (const cv::Mat & img)
Transforming the img to the frequency domain and returning the Fourier Descriptors.
Parameters
img contour in the form of a cv::Mat type CV_8UC1. Which should consist of a continous contour. $ \{ img \in \mathbb{Z} | 0 \leq img \leq 1 \} $
Returns
a vector with complex values, represing the contour in the frequency domain, expressed as Fourier Descriptors
Definition at line 15 of file FFT.cpp.
References complexcontour, Contour2Complex(), fft(), fftDescriptors, and i.
Referenced by SoilAnalyzer::Particle::Analyze(), and BOOST_AUTO_TEST_CASE().
                                                  {
  if (!fftDescriptors.empty()) {
    return fftDescriptors;
  }
  complexcontour = Contour2Complex(img, img.cols / 2, img.rows / 2);
  // Supplement the vector of complex numbers so that N = 2^m
  uint32_t N = complexcontour.size();
  double logN = log(static_cast<double>(N)) / log(2.0);
  if (floor(logN) != logN) {
    // Get the next power of 2
    double nextLogN = floor(logN + 1.0);
    N = static_cast<uint32_t>(pow(2, nextLogN));
    uint32_t i = complexcontour.size();
    // Append the vector with zeros
    while (i++ < N) {
      complexcontour.push_back(Complex_t(0.0, 0.0));
    }
  }
  ComplexArray_t ca(complexcontour.data(),
      complexcontour.size());
  fft(ca);
  fftDescriptors.assign(std::begin(ca), std::end(ca));
  return fftDescriptors;
}
void SoilMath::FFT::ifft (ComplexArray_t & CA) [private]
ifft
Parameters
CA
Definition at line 168 of file FFT.cpp.
References fft().
                                 {
  CA = CA.apply(std::conj);
  fft(CA);
  CA = CA.apply(std::conj);
  CA /= CA.size();
}
iContour_t SoilMath::FFT::Neighbors (uchar * O, int pixel, uint32_t columns, uint32_t rows) [private]
Neighbors a private function returning the neighboring pixels which belong to a contour.
Parameters
O uchar pointer to the data
pixel current counter
columns total number of columns
rows total number of rows
Returns
Definition at line 43 of file FFT.cpp.
References count, and i.
Referenced by Contour2Complex().
                                         {
  long int LUT_nBore[8] = {-columns + 1, -columns, -columns - 1, -1,
                           columns - 1, columns, 1 + columns, 1};
  iContour_t neighbors;
  uint32_t pEnd = rows * columns;
  uint32_t count = 0;
  for (uint32_t i = 0; i < 8; i++) {
    count = pixel + LUT_nBore[i];
    while (count >= pEnd && i < 8) {
      count = pixel + LUT_nBore[++i];
    }
    if (i >= 8) {
      break;
    }
    if (O[count] == 1)
      neighbors.push_back(count);
  }
  return neighbors;
}
Member Data Documentation
ComplexVect_t SoilMath::FFT::complexcontour [private]
Vector with complex values which represent the contour
Definition at line 59 of file FFT.h.
Referenced by GetDescriptors().
ComplexVect_t SoilMath::FFT::fftDescriptors [private]
Vector with complex values which represent the descriptors
Definition at line 56 of file FFT.h.
Referenced by GetDescriptors().
cv::Mat SoilMath::FFT::Img [private]
Img which will be analysed
Definition at line 61 of file FFT.h.
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/SoilMath/FFT.h
/home/peer23peer/VisionSoilAnalyzer/src/SoilMath/FFT.cpp