QCPItemPosition Class Reference
Manages the position of an item.
#include <qcustomplot.h>
Public Types
enum PositionType { ptAbsolute,
ptViewportRatio,
ptAxisRectRatio,
ptPlotCoords
 }
Public Member Functions
QCPItemPosition (QCustomPlot *parentPlot, QCPAbstractItem *parentItem, const QString name)
virtual ~QCPItemPosition ()
PositionType type () const
PositionType typeX () const
PositionType typeY () const
QCPItemAnchor * parentAnchor () const
QCPItemAnchor * parentAnchorX () const
QCPItemAnchor * parentAnchorY () const
double key () const
double value () const
QPointF coords () const
QCPAxis * keyAxis () const
QCPAxis * valueAxis () const
QCPAxisRect * axisRect () const
virtual QPointF pixelPoint () const
void setType (PositionType type)
void setTypeX (PositionType type)
void setTypeY (PositionType type)
bool setParentAnchor (QCPItemAnchor *parentAnchor, bool keepPixelPosition=false)
bool setParentAnchorX (QCPItemAnchor *parentAnchor, bool keepPixelPosition=false)
bool setParentAnchorY (QCPItemAnchor *parentAnchor, bool keepPixelPosition=false)
void setCoords (double key, double value)
void setCoords (const QPointF &coords)
void setAxes (QCPAxis *keyAxis, QCPAxis *valueAxis)
void setAxisRect (QCPAxisRect *axisRect)
void setPixelPoint (const QPointF &pixelPoint)
Protected Member Functions
virtual QCPItemPosition * toQCPItemPosition ()
Protected Attributes
PositionType mPositionTypeX
PositionType mPositionTypeY
QPointer< QCPAxis > mKeyAxis
QPointer< QCPAxis > mValueAxis
QPointer< QCPAxisRect > mAxisRect
double mKey
double mValue
QCPItemAnchor * mParentAnchorX
QCPItemAnchor * mParentAnchorY
Detailed Description
Manages the position of an item.
Every item has at least one public QCPItemPosition member pointer which provides ways to position the item on the QCustomPlot surface. Some items have multiple positions, for example QCPItemRect has two: topLeft and bottomRight.
QCPItemPosition has a type (PositionType) that can be set with setType. This type defines how coordinates passed to setCoords are to be interpreted, e.g. as absolute pixel coordinates, as plot coordinates of certain axes, etc. For more advanced plots it is also possible to assign different types per X/Y coordinate of the position (see setTypeX, setTypeY). This way an item could be positioned at a fixed pixel distance from the top in the Y direction, while following a plot coordinate in the X direction.
A QCPItemPosition may have a parent QCPItemAnchor, see setParentAnchor. This way you can tie multiple items together. If the QCPItemPosition has a parent, its coordinates (setCoords) are considered to be absolute pixels in the reference frame of the parent anchor, where (0, 0) means directly ontop of the parent anchor. For example, You could attach the start position of a QCPItemLine to the bottom anchor of a QCPItemText to make the starting point of the line always be centered under the text label, no matter where the text is moved to. For more advanced plots, it is possible to assign different parent anchors per X/Y coordinate of the position, see setParentAnchorX, setParentAnchorY. This way an item could follow another item in the X direction but stay at a fixed position in the Y direction. Or even follow item A in X, and item B in Y.
Note that every QCPItemPosition inherits from QCPItemAnchor and thus can itself be used as parent anchor for other positions.
To set the apparent pixel position on the QCustomPlot surface directly, use setPixelPoint. This works no matter what type this QCPItemPosition is or what parent-child situation it is in, as setPixelPoint transforms the coordinates appropriately, to make the position appear at the specified pixel values.
Definition at line 1762 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPItemPosition::PositionType
Defines the ways an item position can be specified. Thus it defines what the numbers passed to setCoords actually mean.
See also
setType
Enumerator
ptAbsolute
 Static positioning in pixels, starting from the top left corner of the viewport/widget.
ptViewportRatio
 Static positioning given by a fraction of the viewport size. For example, if you call setCoords(0, 0), the position will be at the top left corner of the viewport/widget. setCoords(1, 1) will be at the bottom right corner, setCoords(0.5, 0) will be horizontally centered and vertically at the top of the viewport/widget, etc.
ptAxisRectRatio
 Static positioning given by a fraction of the axis rect size (see setAxisRect). For example, if you call setCoords(0, 0), the position will be at the top left corner of the axis rect. setCoords(1, 1) will be at the bottom right corner, setCoords(0.5, 0) will be horizontally centered and vertically at the top of the axis rect, etc. You can also go beyond the axis rect by providing negative coordinates or coordinates larger than 1.
ptPlotCoords
 Dynamic positioning at a plot coordinate defined by two axes (see setAxes).
Definition at line 1771 of file qcustomplot.h.
                    {
    ptAbsolute
    ,
    ptViewportRatio
    ,
    ptAxisRectRatio
    ,
    ptPlotCoords
  };
Constructor & Destructor Documentation
QCPItemPosition::QCPItemPosition (QCustomPlot * parentPlot, QCPAbstractItem * parentItem, const QString name)
Creates a new QCPItemPosition. You shouldn't create QCPItemPosition instances directly, even if you want to make a new item subclass. Use QCPAbstractItem::createPosition instead, as explained in the subclassing section of the QCPAbstractItem documentation.
Definition at line 8399 of file qcustomplot.cpp.
    : QCPItemAnchor(parentPlot, parentItem, name),
      mPositionTypeX(ptAbsolute),
      mPositionTypeY(ptAbsolute), mKey(0), mValue(0),
      mParentAnchorX(0),
      mParentAnchorY(0) {}
QCPItemPosition::~QCPItemPosition () [virtual]
Definition at line 8406 of file qcustomplot.cpp.
References QCPItemAnchor::mChildrenX, QCPItemAnchor::mChildrenY, mParentAnchorX, mParentAnchorY, parentAnchorX(), parentAnchorY(), QCPItemAnchor::removeChildX(), QCPItemAnchor::removeChildY(), setParentAnchorX(), and setParentAnchorY().
                                  {
  // unregister as parent at children:
  // Note: this is done in ~QCPItemAnchor again, but it's important
  // QCPItemPosition does it itself, because only then
  // the setParentAnchor(0) call the correct QCPItemPosition::pixelPoint
  // function instead of QCPItemAnchor::pixelPoint
  foreach (QCPItemPosition *child, mChildrenX.toList()) {
    if (child->parentAnchorX() == this)
      child->setParentAnchorX(0); // this acts back on this anchor and child
                                  // removes itself from mChildrenX
  }
  foreach (QCPItemPosition *child, mChildrenY.toList()) {
    if (child->parentAnchorY() == this)
      child->setParentAnchorY(0); // this acts back on this anchor and child
                                  // removes itself from mChildrenY
  }
  // unregister as child in parent:
  if (mParentAnchorX)
    mParentAnchorX->removeChildX(this);
  if (mParentAnchorY)
    mParentAnchorY->removeChildY(this);
}
Member Function Documentation
QCPAxisRect * QCPItemPosition::axisRect () const
Definition at line 8431 of file qcustomplot.cpp.
References mAxisRect.
Referenced by setAxisRect().
{ return mAxisRect.data(); }
QPointF QCPItemPosition::coords () const [inline]
Definition at line 1807 of file qcustomplot.h.
Referenced by setParentAnchorX(), and setParentAnchorY().
{ return QPointF(mKey, mValue); }
double QCPItemPosition::key () const [inline]
Definition at line 1805 of file qcustomplot.h.
Referenced by setCoords().
{ return mKey; }
QCPAxis* QCPItemPosition::keyAxis () const [inline]
Definition at line 1808 of file qcustomplot.h.
Referenced by setAxes().
{ return mKeyAxis.data(); }
QCPItemAnchor * QCPItemPosition::parentAnchor () const [inline]
Returns the current parent anchor.
If different parent anchors were set for X and Y (setParentAnchorX, setParentAnchorY), this method returns the parent anchor of the Y coordinate. In that case rather use parentAnchorX() and parentAnchorY().
See also
setParentAnchor
Definition at line 1802 of file qcustomplot.h.
Referenced by setParentAnchorX(), and setParentAnchorY().
{ return parentAnchorX(); }
QCPItemAnchor* QCPItemPosition::parentAnchorX () const [inline]
Definition at line 1803 of file qcustomplot.h.
Referenced by QCPItemAnchor::~QCPItemAnchor(), and ~QCPItemPosition().
{ return mParentAnchorX; }
QCPItemAnchor* QCPItemPosition::parentAnchorY () const [inline]
Definition at line 1804 of file qcustomplot.h.
Referenced by QCPItemAnchor::~QCPItemAnchor(), and ~QCPItemPosition().
{ return mParentAnchorY; }
QPointF QCPItemPosition::pixelPoint () const [virtual]
Returns the final absolute pixel position of the QCPItemPosition on the QCustomPlot surface. It includes all effects of type (setType) and possible parent anchors (setParentAnchor).
See also
setPixelPoint
Reimplemented from QCPItemAnchor.
Definition at line 8762 of file qcustomplot.cpp.
References mAxisRect, mKey, mKeyAxis, mParentAnchorX, mParentAnchorY, QCPItemAnchor::mParentPlot, mPositionTypeX, mPositionTypeY, mValue, mValueAxis, QCPItemAnchor::pixelPoint(), ptAbsolute, ptAxisRectRatio, ptPlotCoords, ptViewportRatio, and QCustomPlot::viewport().
Referenced by QCPItemRect::anchorPixelPoint(), QCPItemText::anchorPixelPoint(), QCPItemEllipse::anchorPixelPoint(), QCPItemBracket::anchorPixelPoint(), QCPItemStraightLine::draw(), QCPItemLine::draw(), QCPItemCurve::draw(), QCPItemRect::draw(), QCPItemText::draw(), QCPItemEllipse::draw(), QCPItemTracer::draw(), QCPItemBracket::draw(), QCPItemPixmap::getFinalRect(), QCPItemStraightLine::selectTest(), QCPItemLine::selectTest(), QCPItemCurve::selectTest(), QCPItemRect::selectTest(), QCPItemText::selectTest(), QCPItemEllipse::selectTest(), QCPItemTracer::selectTest(), QCPItemBracket::selectTest(), setParentAnchorX(), setParentAnchorY(), setTypeX(), and setTypeY().
                                          {
  QPointF result;
  // determine X:
  switch (mPositionTypeX) {
  case ptAbsolute: {
    result.rx() = mKey;
    if (mParentAnchorX)
      result.rx() += mParentAnchorX->pixelPoint().x();
    break;
  }
  case ptViewportRatio: {
    result.rx() = mKey * mParentPlot->viewport().width();
    if (mParentAnchorX)
      result.rx() += mParentAnchorX->pixelPoint().x();
    else
      result.rx() += mParentPlot->viewport().left();
    break;
  }
  case ptAxisRectRatio: {
    if (mAxisRect) {
      result.rx() = mKey * mAxisRect.data()->width();
      if (mParentAnchorX)
        result.rx() += mParentAnchorX->pixelPoint().x();
      else
        result.rx() += mAxisRect.data()->left();
    } else
      qDebug() << Q_FUNC_INFO << "Item position type x is ptAxisRectRatio, but "
                                 "no axis rect was defined";
    break;
  }
  case ptPlotCoords: {
    if (mKeyAxis && mKeyAxis.data()->orientation() == Qt::Horizontal)
      result.rx() = mKeyAxis.data()->coordToPixel(mKey);
    else if (mValueAxis && mValueAxis.data()->orientation() == Qt::Horizontal)
      result.rx() = mValueAxis.data()->coordToPixel(mValue);
    else
      qDebug()
          << Q_FUNC_INFO
          << "Item position type x is ptPlotCoords, but no axes were defined";
    break;
  }
  }
  // determine Y:
  switch (mPositionTypeY) {
  case ptAbsolute: {
    result.ry() = mValue;
    if (mParentAnchorY)
      result.ry() += mParentAnchorY->pixelPoint().y();
    break;
  }
  case ptViewportRatio: {
    result.ry() = mValue * mParentPlot->viewport().height();
    if (mParentAnchorY)
      result.ry() += mParentAnchorY->pixelPoint().y();
    else
      result.ry() += mParentPlot->viewport().top();
    break;
  }
  case ptAxisRectRatio: {
    if (mAxisRect) {
      result.ry() = mValue * mAxisRect.data()->height();
      if (mParentAnchorY)
        result.ry() += mParentAnchorY->pixelPoint().y();
      else
        result.ry() += mAxisRect.data()->top();
    } else
      qDebug() << Q_FUNC_INFO << "Item position type y is ptAxisRectRatio, but "
                                 "no axis rect was defined";
    break;
  }
  case ptPlotCoords: {
    if (mKeyAxis && mKeyAxis.data()->orientation() == Qt::Vertical)
      result.ry() = mKeyAxis.data()->coordToPixel(mKey);
    else if (mValueAxis && mValueAxis.data()->orientation() == Qt::Vertical)
      result.ry() = mValueAxis.data()->coordToPixel(mValue);
    else
      qDebug()
          << Q_FUNC_INFO
          << "Item position type y is ptPlotCoords, but no axes were defined";
    break;
  }
  }
  return result;
}
void QCPItemPosition::setAxes (QCPAxis * keyAxis, QCPAxis * valueAxis)
When setType is ptPlotCoords, this function may be used to specify the axes the coordinates set with setCoords relate to. By default they are set to the initial xAxis and yAxis of the QCustomPlot.
Definition at line 8857 of file qcustomplot.cpp.
References keyAxis(), mKeyAxis, mValueAxis, and valueAxis().
Referenced by QCPAbstractItem::createPosition(), and QCPItemTracer::setGraph().
                                                                  {
  mKeyAxis = keyAxis;
  mValueAxis = valueAxis;
}
void QCPItemPosition::setAxisRect (QCPAxisRect * axisRect)
When setType is ptAxisRectRatio, this function may be used to specify the axis rect the coordinates set with setCoords relate to. By default this is set to the main axis rect of the QCustomPlot.
Definition at line 8869 of file qcustomplot.cpp.
References axisRect(), and mAxisRect.
Referenced by QCPAbstractItem::createPosition().
                                                       {
  mAxisRect = axisRect;
}
void QCPItemPosition::setCoords (double key, double value)
Sets the coordinates of this QCPItemPosition. What the coordinates mean, is defined by the type (setType, setTypeX, setTypeY).
For example, if the type is ptAbsolute, key and value mean the x and y pixel position on the QCustomPlot surface. In that case the origin (0, 0) is in the top left corner of the QCustomPlot viewport. If the type is ptPlotCoords, key and value mean a point in the plot coordinate system defined by the axes set by setAxes. By default those are the QCustomPlot's xAxis and yAxis. See the documentation of setType for other available coordinate types and their meaning.
If different types were configured for X and Y (setTypeX, setTypeY), key and value must also be provided in the different coordinate systems. Here, the X type refers to key, and the Y type refers to value.
See also
setPixelPoint
Definition at line 8739 of file qcustomplot.cpp.
References key(), mKey, mValue, and value().
Referenced by QCPAbstractItem::createPosition(), QCPItemBracket::QCPItemBracket(), QCPItemCurve::QCPItemCurve(), QCPItemEllipse::QCPItemEllipse(), QCPItemLine::QCPItemLine(), QCPItemPixmap::QCPItemPixmap(), QCPItemRect::QCPItemRect(), QCPItemStraightLine::QCPItemStraightLine(), QCPItemText::QCPItemText(), QCPItemTracer::QCPItemTracer(), setCoords(), setParentAnchorX(), setParentAnchorY(), setPixelPoint(), and QCPItemTracer::updatePosition().
                                                        {
  mKey = key;
  mValue = value;
}
void QCPItemPosition::setCoords (const QPointF & pos)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Sets the coordinates as a QPointF pos where pos.x has the meaning of key and pos.y the meaning of value of the setCoords(double key, double value) method.
Definition at line 8750 of file qcustomplot.cpp.
References setCoords().
                                                  {
  setCoords(pos.x(), pos.y());
}
bool QCPItemPosition::setParentAnchor (QCPItemAnchor * parentAnchor, bool keepPixelPosition = false)
Sets the parent of this QCPItemPosition to parentAnchor. This means the position will now follow any position changes of the anchor. The local coordinate system of positions with a parent anchor always is absolute pixels, with (0, 0) being exactly on top of the parent anchor. (Hence the type shouldn't be set to ptPlotCoords for positions with parent anchors.)
if keepPixelPosition is true, the current pixel position of the QCPItemPosition is preserved during reparenting. If it's set to false, the coordinates are set to (0, 0), i.e. the position will be exactly on top of the parent anchor.
To remove this QCPItemPosition from any parent anchor, set parentAnchor to 0.
If the QCPItemPosition previously had no parent and the type is ptPlotCoords, the type is set to ptAbsolute, to keep the position in a valid state.
This method sets the parent anchor for both X and Y directions. It is also possible to set different parents for X and Y, see setParentAnchorX, setParentAnchorY.
Definition at line 8569 of file qcustomplot.cpp.
References setParentAnchorX(), and setParentAnchorY().
                                                              {
  bool successX = setParentAnchorX(parentAnchor, keepPixelPosition);
  bool successY = setParentAnchorY(parentAnchor, keepPixelPosition);
  return successX && successY;
}
bool QCPItemPosition::setParentAnchorX (QCPItemAnchor * parentAnchor, bool keepPixelPosition = false)
This method sets the parent anchor of the X coordinate to parentAnchor.
For a detailed description of what a parent anchor is, see the documentation of setParentAnchor.
See also
setParentAnchor, setParentAnchorY
Definition at line 8584 of file qcustomplot.cpp.
References QCPItemAnchor::addChildX(), coords(), mParentAnchorX, QCPItemAnchor::mParentItem, mPositionTypeX, parentAnchor(), pixelPoint(), ptAbsolute, ptPlotCoords, QCPItemAnchor::removeChildX(), setCoords(), setPixelPoint(), setTypeX(), QCPItemAnchor::toQCPItemPosition(), and y.
Referenced by setParentAnchor(), QCPItemAnchor::~QCPItemAnchor(), and ~QCPItemPosition().
                                                               {
  // make sure self is not assigned as parent:
  if (parentAnchor == this) {
    qDebug() << Q_FUNC_INFO << "can't set self as parent anchor"
             << reinterpret_cast<quintptr>(parentAnchor);
    return false;
  }
  // make sure no recursive parent-child-relationships are created:
  QCPItemAnchor *currentParent = parentAnchor;
  while (currentParent) {
    if (QCPItemPosition *currentParentPos =
            currentParent->toQCPItemPosition()) {
      // is a QCPItemPosition, might have further parent, so keep iterating
      if (currentParentPos == this) {
        qDebug() << Q_FUNC_INFO
                 << "can't create recursive parent-child-relationship"
                 << reinterpret_cast<quintptr>(parentAnchor);
        return false;
      }
      currentParent = currentParentPos->parentAnchorX();
    } else {
      // is a QCPItemAnchor, can't have further parent. Now make sure the parent
      // items aren't the
      // same, to prevent a position being child of an anchor which itself
      // depends on the position,
      // because they're both on the same item:
      if (currentParent->mParentItem == mParentItem) {
        qDebug() << Q_FUNC_INFO << "can't set parent to be an anchor which "
                                   "itself depends on this position"
                 << reinterpret_cast<quintptr>(parentAnchor);
        return false;
      }
      break;
    }
  }
  // if previously no parent set and PosType is still ptPlotCoords, set to
  // ptAbsolute:
  if (!mParentAnchorX && mPositionTypeX ==
      ptPlotCoords)
    setTypeX(ptAbsolute);
  // save pixel position:
  QPointF pixelP;
  if (keepPixelPosition)
    pixelP = pixelPoint();
  // unregister at current parent anchor:
  if (mParentAnchorX)
    mParentAnchorX->removeChildX(this);
  // register at new parent anchor:
  if (parentAnchor)
    parentAnchor->addChildX(this);
  mParentAnchorX = parentAnchor;
  // restore pixel position under new parent:
  if (keepPixelPosition)
    setPixelPoint(pixelP);
  else
    setCoords(0, coords().y());
  return true;
}
bool QCPItemPosition::setParentAnchorY (QCPItemAnchor * parentAnchor, bool keepPixelPosition = false)
This method sets the parent anchor of the Y coordinate to parentAnchor.
For a detailed description of what a parent anchor is, see the documentation of setParentAnchor.
See also
setParentAnchor, setParentAnchorX
Definition at line 8653 of file qcustomplot.cpp.
References QCPItemAnchor::addChildY(), coords(), mParentAnchorY, QCPItemAnchor::mParentItem, mPositionTypeY, parentAnchor(), pixelPoint(), ptAbsolute, ptPlotCoords, QCPItemAnchor::removeChildY(), setCoords(), setPixelPoint(), setTypeY(), QCPItemAnchor::toQCPItemPosition(), and x.
Referenced by setParentAnchor(), QCPItemAnchor::~QCPItemAnchor(), and ~QCPItemPosition().
                                                               {
  // make sure self is not assigned as parent:
  if (parentAnchor == this) {
    qDebug() << Q_FUNC_INFO << "can't set self as parent anchor"
             << reinterpret_cast<quintptr>(parentAnchor);
    return false;
  }
  // make sure no recursive parent-child-relationships are created:
  QCPItemAnchor *currentParent = parentAnchor;
  while (currentParent) {
    if (QCPItemPosition *currentParentPos =
            currentParent->toQCPItemPosition()) {
      // is a QCPItemPosition, might have further parent, so keep iterating
      if (currentParentPos == this) {
        qDebug() << Q_FUNC_INFO
                 << "can't create recursive parent-child-relationship"
                 << reinterpret_cast<quintptr>(parentAnchor);
        return false;
      }
      currentParent = currentParentPos->parentAnchorY();
    } else {
      // is a QCPItemAnchor, can't have further parent. Now make sure the parent
      // items aren't the
      // same, to prevent a position being child of an anchor which itself
      // depends on the position,
      // because they're both on the same item:
      if (currentParent->mParentItem == mParentItem) {
        qDebug() << Q_FUNC_INFO << "can't set parent to be an anchor which "
                                   "itself depends on this position"
                 << reinterpret_cast<quintptr>(parentAnchor);
        return false;
      }
      break;
    }
  }
  // if previously no parent set and PosType is still ptPlotCoords, set to
  // ptAbsolute:
  if (!mParentAnchorY && mPositionTypeY ==
      ptPlotCoords)
    setTypeY(ptAbsolute);
  // save pixel position:
  QPointF pixelP;
  if (keepPixelPosition)
    pixelP = pixelPoint();
  // unregister at current parent anchor:
  if (mParentAnchorY)
    mParentAnchorY->removeChildY(this);
  // register at new parent anchor:
  if (parentAnchor)
    parentAnchor->addChildY(this);
  mParentAnchorY = parentAnchor;
  // restore pixel position under new parent:
  if (keepPixelPosition)
    setPixelPoint(pixelP);
  else
    setCoords(coords().x(), 0);
  return true;
}
void QCPItemPosition::setPixelPoint (const QPointF & pixelPoint)
Sets the apparent pixel position. This works no matter what type (setType) this QCPItemPosition is or what parent-child situation it is in, as coordinates are transformed appropriately, to make the position finally appear at the specified pixel values.
Only if the type is ptAbsolute and no parent anchor is set, this function's effect is identical to that of setCoords.
See also
pixelPoint, setCoords
Definition at line 8887 of file qcustomplot.cpp.
References mAxisRect, mKeyAxis, mParentAnchorX, mParentAnchorY, QCPItemAnchor::mParentPlot, mPositionTypeX, mPositionTypeY, mValueAxis, QCPItemAnchor::pixelPoint(), ptAbsolute, ptAxisRectRatio, ptPlotCoords, ptViewportRatio, setCoords(), QCustomPlot::viewport(), x, and y.
Referenced by setParentAnchorX(), setParentAnchorY(), setTypeX(), and setTypeY().
                                                             {
  double x = pixelPoint.x();
  double y = pixelPoint.y();
  switch (mPositionTypeX) {
  case ptAbsolute: {
    if (mParentAnchorX)
      x -= mParentAnchorX->pixelPoint().x();
    break;
  }
  case ptViewportRatio: {
    if (mParentAnchorX)
      x -= mParentAnchorX->pixelPoint().x();
    else
      x -= mParentPlot->viewport().left();
    x /= (double)mParentPlot->viewport().width();
    break;
  }
  case ptAxisRectRatio: {
    if (mAxisRect) {
      if (mParentAnchorX)
        x -= mParentAnchorX->pixelPoint().x();
      else
        x -= mAxisRect.data()->left();
      x /= (double)mAxisRect.data()->width();
    } else
      qDebug() << Q_FUNC_INFO << "Item position type x is ptAxisRectRatio, but "
                                 "no axis rect was defined";
    break;
  }
  case ptPlotCoords: {
    if (mKeyAxis && mKeyAxis.data()->orientation() == Qt::Horizontal)
      x = mKeyAxis.data()->pixelToCoord(x);
    else if (mValueAxis && mValueAxis.data()->orientation() == Qt::Horizontal)
      y = mValueAxis.data()->pixelToCoord(x);
    else
      qDebug()
          << Q_FUNC_INFO
          << "Item position type x is ptPlotCoords, but no axes were defined";
    break;
  }
  }
  switch (mPositionTypeY) {
  case ptAbsolute: {
    if (mParentAnchorY)
      y -= mParentAnchorY->pixelPoint().y();
    break;
  }
  case ptViewportRatio: {
    if (mParentAnchorY)
      y -= mParentAnchorY->pixelPoint().y();
    else
      y -= mParentPlot->viewport().top();
    y /= (double)mParentPlot->viewport().height();
    break;
  }
  case ptAxisRectRatio: {
    if (mAxisRect) {
      if (mParentAnchorY)
        y -= mParentAnchorY->pixelPoint().y();
      else
        y -= mAxisRect.data()->top();
      y /= (double)mAxisRect.data()->height();
    } else
      qDebug() << Q_FUNC_INFO << "Item position type y is ptAxisRectRatio, but "
                                 "no axis rect was defined";
    break;
  }
  case ptPlotCoords: {
    if (mKeyAxis && mKeyAxis.data()->orientation() == Qt::Vertical)
      x = mKeyAxis.data()->pixelToCoord(y);
    else if (mValueAxis && mValueAxis.data()->orientation() == Qt::Vertical)
      y = mValueAxis.data()->pixelToCoord(y);
    else
      qDebug()
          << Q_FUNC_INFO
          << "Item position type y is ptPlotCoords, but no axes were defined";
    break;
  }
  }
  setCoords(x, y);
}
void QCPItemPosition::setType (QCPItemPosition::PositionType type)
Sets the type of the position. The type defines how the coordinates passed to setCoords should be handled and how the QCPItemPosition should behave in the plot.
The possible values for type can be separated in two main categories:
The position is regarded as a point in plot coordinates. This corresponds to ptPlotCoords and requires two axes that define the plot coordinate system. They can be specified with setAxes. By default, the QCustomPlot's x- and yAxis are used.
The position is fixed on the QCustomPlot surface, i.e. independent of axis ranges. This corresponds to all other types, i.e. ptAbsolute, ptViewportRatio and ptAxisRectRatio. They differ only in the way the absolute position is described, see the documentation of PositionType for details. For ptAxisRectRatio, note that you can specify the axis rect with setAxisRect. By default this is set to the main axis rect.
Note that the position type ptPlotCoords is only available (and sensible) when the position has no parent anchor (setParentAnchor).
If the type is changed, the apparent pixel position on the plot is preserved. This means the coordinates as retrieved with coords() and set with setCoords may change in the process.
This method sets the type for both X and Y directions. It is also possible to set different types for X and Y, see setTypeX, setTypeY.
Definition at line 8470 of file qcustomplot.cpp.
References setTypeX(), and setTypeY().
Referenced by QCPAbstractItem::createPosition(), and QCPItemTracer::setGraph().
                                                              {
  setTypeX(type);
  setTypeY(type);
}
void QCPItemPosition::setTypeX (QCPItemPosition::PositionType type)
This method sets the position type of the X coordinate to type.
For a detailed description of what a position type is, see the documentation of setType.
See also
setType, setTypeY
Definition at line 8483 of file qcustomplot.cpp.
References mAxisRect, mKeyAxis, mPositionTypeX, mValueAxis, pixelPoint(), ptAxisRectRatio, ptPlotCoords, setPixelPoint(), and type().
Referenced by setParentAnchorX(), and setType().
                                                               {
  if (mPositionTypeX != type) {
    // if switching from or to coordinate type that isn't valid (e.g. because
    // axes or axis rect
    // were deleted), don't try to recover the pixelPoint() because it would
    // output a qDebug warning.
    bool retainPixelPosition = true;
    if ((mPositionTypeX == ptPlotCoords || type ==
      ptPlotCoords) &&
        (!mKeyAxis || !mValueAxis))
      retainPixelPosition = false;
    if ((mPositionTypeX == ptAxisRectRatio || type ==
      ptAxisRectRatio) &&
        (!mAxisRect))
      retainPixelPosition = false;
    QPointF pixel;
    if (retainPixelPosition)
      pixel = pixelPoint();
    mPositionTypeX = type;
    if (retainPixelPosition)
      setPixelPoint(pixel);
  }
}
void QCPItemPosition::setTypeY (QCPItemPosition::PositionType type)
This method sets the position type of the Y coordinate to type.
For a detailed description of what a position type is, see the documentation of setType.
See also
setType, setTypeX
Definition at line 8516 of file qcustomplot.cpp.
References mAxisRect, mKeyAxis, mPositionTypeY, mValueAxis, pixelPoint(), ptAxisRectRatio, ptPlotCoords, setPixelPoint(), and type().
Referenced by setParentAnchorY(), and setType().
                                                               {
  if (mPositionTypeY != type) {
    // if switching from or to coordinate type that isn't valid (e.g. because
    // axes or axis rect
    // were deleted), don't try to recover the pixelPoint() because it would
    // output a qDebug warning.
    bool retainPixelPosition = true;
    if ((mPositionTypeY == ptPlotCoords || type ==
      ptPlotCoords) &&
        (!mKeyAxis || !mValueAxis))
      retainPixelPosition = false;
    if ((mPositionTypeY == ptAxisRectRatio || type ==
      ptAxisRectRatio) &&
        (!mAxisRect))
      retainPixelPosition = false;
    QPointF pixel;
    if (retainPixelPosition)
      pixel = pixelPoint();
    mPositionTypeY = type;
    if (retainPixelPosition)
      setPixelPoint(pixel);
  }
}
virtual QCPItemPosition* QCPItemPosition::toQCPItemPosition () [inline], [protected], [virtual]
Returns 0 if this instance is merely a QCPItemAnchor, and a valid pointer of type QCPItemPosition* if it actually is a QCPItemPosition (which is a subclass of QCPItemAnchor).
This safe downcast functionality could also be achieved with a dynamic_cast. However, QCustomPlot avoids dynamic_cast to work with projects that don't have RTTI support enabled (e.g. -fno-rtti flag with gcc compiler).
Reimplemented from QCPItemAnchor.
Definition at line 1838 of file qcustomplot.h.
{ return this; }
QCPItemPosition::PositionType * QCPItemPosition::type () const [inline]
Returns the current position type.
If different types were set for X and Y (setTypeX, setTypeY), this method returns the type of the X coordinate. In that case rather use typeX() and typeY().
See also
setType
Definition at line 1799 of file qcustomplot.h.
Referenced by setTypeX(), and setTypeY().
{ return typeX(); }
PositionType QCPItemPosition::typeX () const [inline]
Definition at line 1800 of file qcustomplot.h.
{ return mPositionTypeX; }
PositionType QCPItemPosition::typeY () const [inline]
Definition at line 1801 of file qcustomplot.h.
{ return mPositionTypeY; }
double QCPItemPosition::value () const [inline]
Definition at line 1806 of file qcustomplot.h.
Referenced by setCoords().
{ return mValue; }
QCPAxis* QCPItemPosition::valueAxis () const [inline]
Definition at line 1809 of file qcustomplot.h.
Referenced by setAxes().
{ return mValueAxis.data(); }
Member Data Documentation
QPointer<QCPAxisRect> QCPItemPosition::mAxisRect [protected]
Definition at line 1833 of file qcustomplot.h.
Referenced by axisRect(), pixelPoint(), setAxisRect(), setPixelPoint(), setTypeX(), and setTypeY().
double QCPItemPosition::mKey [protected]
Definition at line 1834 of file qcustomplot.h.
Referenced by pixelPoint(), and setCoords().
QPointer<QCPAxis> QCPItemPosition::mKeyAxis [protected]
Definition at line 1832 of file qcustomplot.h.
Referenced by pixelPoint(), setAxes(), setPixelPoint(), setTypeX(), and setTypeY().
QCPItemAnchor* QCPItemPosition::mParentAnchorX [protected]
Definition at line 1835 of file qcustomplot.h.
Referenced by pixelPoint(), setParentAnchorX(), setPixelPoint(), and ~QCPItemPosition().
QCPItemAnchor * QCPItemPosition::mParentAnchorY [protected]
Definition at line 1835 of file qcustomplot.h.
Referenced by pixelPoint(), setParentAnchorY(), setPixelPoint(), and ~QCPItemPosition().
PositionType QCPItemPosition::mPositionTypeX [protected]
Definition at line 1831 of file qcustomplot.h.
Referenced by pixelPoint(), setParentAnchorX(), setPixelPoint(), and setTypeX().
PositionType QCPItemPosition::mPositionTypeY [protected]
Definition at line 1831 of file qcustomplot.h.
Referenced by pixelPoint(), setParentAnchorY(), setPixelPoint(), and setTypeY().
double QCPItemPosition::mValue [protected]
Definition at line 1834 of file qcustomplot.h.
Referenced by pixelPoint(), and setCoords().
QPointer<QCPAxis> QCPItemPosition::mValueAxis [protected]
Definition at line 1832 of file qcustomplot.h.
Referenced by pixelPoint(), setAxes(), setPixelPoint(), setTypeX(), and setTypeY().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp