QCPGraph Class Reference
A plottable representing a graph in a plot.
#include <qcustomplot.h>
Public Types
enum LineStyle {
*
lsNone,
lsLine,
lsStepLeft,
lsStepRight,
*
lsStepCenter,
lsImpulse
 }
enum ErrorType { etNone,
etKey,
etValue,
etBoth
 }
Public Member Functions
QCPGraph (QCPAxis *keyAxis, QCPAxis *valueAxis)
virtual ~QCPGraph ()
QCPDataMap * data () const
LineStyle lineStyle () const
QCPScatterStyle scatterStyle () const
ErrorType errorType () const
QPen errorPen () const
double errorBarSize () const
bool errorBarSkipSymbol () const
QCPGraph * channelFillGraph () const
bool adaptiveSampling () const
void setData (QCPDataMap *data, bool copy=false)
void setData (const QVector< double > &key, const QVector< double > &value)
void setDataKeyError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError)
void setDataKeyError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus)
void setDataValueError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueError)
void setDataValueError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
void setDataBothError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyError, const QVector< double > &valueError)
void setDataBothError (const QVector< double > &key, const QVector< double > &value, const QVector< double > &keyErrorMinus, const QVector< double > &keyErrorPlus, const QVector< double > &valueErrorMinus, const QVector< double > &valueErrorPlus)
void setLineStyle (LineStyle ls)
void setScatterStyle (const QCPScatterStyle &style)
void setErrorType (ErrorType errorType)
void setErrorPen (const QPen &pen)
void setErrorBarSize (double size)
void setErrorBarSkipSymbol (bool enabled)
void setChannelFillGraph (QCPGraph *targetGraph)
void setAdaptiveSampling (bool enabled)
void addData (const QCPDataMap &dataMap)
void addData (const QCPData &data)
void addData (double key, double value)
void addData (const QVector< double > &keys, const QVector< double > &values)
void removeDataBefore (double key)
void removeDataAfter (double key)
void removeData (double fromKey, double toKey)
void removeData (double key)
virtual void clearData ()
virtual double selectTest (const QPointF &pos, bool onlySelectable, QVariant *details=0) const
void rescaleAxes (bool onlyEnlarge, bool includeErrorBars) const
void rescaleKeyAxis (bool onlyEnlarge, bool includeErrorBars) const
void rescaleValueAxis (bool onlyEnlarge, bool includeErrorBars) const
Protected Member Functions
virtual void draw (QCPPainter *painter)
virtual void drawLegendIcon (QCPPainter *painter, const QRectF &rect) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain=sdBoth) const
virtual QCPRange getKeyRange (bool &foundRange, SignDomain inSignDomain, bool includeErrors) const
virtual QCPRange getValueRange (bool &foundRange, SignDomain inSignDomain, bool includeErrors) const
virtual void drawFill (QCPPainter *painter, QVector< QPointF > *lineData) const
virtual void drawScatterPlot (QCPPainter *painter, QVector< QCPData > *scatterData) const
virtual void drawLinePlot (QCPPainter *painter, QVector< QPointF > *lineData) const
virtual void drawImpulsePlot (QCPPainter *painter, QVector< QPointF > *lineData) const
void getPreparedData (QVector< QCPData > *lineData, QVector< QCPData > *scatterData) const
void getPlotData (QVector< QPointF > *lineData, QVector< QCPData > *scatterData) const
void getScatterPlotData (QVector< QCPData > *scatterData) const
void getLinePlotData (QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
void getStepLeftPlotData (QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
void getStepRightPlotData (QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
void getStepCenterPlotData (QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
void getImpulsePlotData (QVector< QPointF > *linePixelData, QVector< QCPData > *scatterData) const
void drawError (QCPPainter *painter, double x, double y, const QCPData &data) const
void getVisibleDataBounds (QCPDataMap::const_iterator &lower, QCPDataMap::const_iterator &upper) const
int countDataInBounds (const QCPDataMap::const_iterator &lower, const QCPDataMap::const_iterator &upper, int maxCount) const
void addFillBasePoints (QVector< QPointF > *lineData) const
void removeFillBasePoints (QVector< QPointF > *lineData) const
QPointF lowerFillBasePoint (double lowerKey) const
QPointF upperFillBasePoint (double upperKey) const
const QPolygonF getChannelFillPolygon (const QVector< QPointF > *lineData) const
int findIndexBelowX (const QVector< QPointF > *data, double x) const
int findIndexAboveX (const QVector< QPointF > *data, double x) const
int findIndexBelowY (const QVector< QPointF > *data, double y) const
int findIndexAboveY (const QVector< QPointF > *data, double y) const
double pointDistance (const QPointF &pixelPoint) const
Protected Attributes
QCPDataMap * mData
QPen mErrorPen
LineStyle mLineStyle
QCPScatterStyle mScatterStyle
ErrorType mErrorType
double mErrorBarSize
bool mErrorBarSkipSymbol
QPointer< QCPGraph > mChannelFillGraph
bool mAdaptiveSampling
Friends
class QCustomPlot
class QCPLegend
Additional Inherited Members
Detailed Description
A plottable representing a graph in a plot.
Usually QCustomPlot creates graphs internally via QCustomPlot::addGraph and the resulting instance is accessed via QCustomPlot::graph.
To plot data, assign it with the setData or addData functions. Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap.
Graphs are used to display single-valued data. Single-valued means that there should only be one data point per unique key coordinate. In other words, the graph can't have loops. If you do want to plot non-single-valued curves, rather use the QCPCurve plottable.
Gaps in the graph line can be created by adding data points with NaN as value (qQNaN() or std::numeric_limits<double>::quiet_NaN()) in between the two data points that shall be separated.
Changing the appearance
The appearance of the graph is mainly determined by the line style, scatter style, brush and pen of the graph (setLineStyle, setScatterStyle, setBrush, setPen).
Filling under or between graphs
QCPGraph knows two types of fills: Normal graph fills towards the zero-value-line parallel to the key axis of the graph, and fills between two graphs, called channel fills. To enable a fill, just set a brush with setBrush which is neither Qt::NoBrush nor fully transparent.
By default, a normal fill towards the zero-value-line will be drawn. To set up a channel fill between this graph and another one, call setChannelFillGraph with the other graph as parameter.
See also
QCustomPlot::addGraph, QCustomPlot::graph
Definition at line 2831 of file qcustomplot.h.
Member Enumeration Documentation
enum QCPGraph::ErrorType
Defines what kind of error bars are drawn for each data point
Enumerator
etNone
 No error bars are shown.
etKey
 Error bars for the key dimension of the data point are shown.
etValue
 Error bars for the value dimension of the data point are shown.
etBoth
 Error bars for both key and value dimensions of the data point are shown
Definition at line 2878 of file qcustomplot.h.
                 {
    etNone
    ,
    etKey
    ,
    etValue
    ,
    etBoth
  };
enum QCPGraph::LineStyle
Defines how the graph's line is represented visually in the plot. The line is drawn with the current pen of the graph (setPen).
See also
setLineStyle
Enumerator
lsNone
 with symbols according to the scatter style, see setScatterStyle) data points are not connected with any lines (e.g. data only represented
lsLine
 data points are connected by a straight line
lsStepLeft
 line is drawn as steps where the step height is the value of the left data point
lsStepRight
 line is drawn as steps where the step height is the value of the right data point
lsStepCenter
 line is drawn as steps where the step is in between two data points
lsImpulse
 each data point is represented by a line parallel to the value axis, which reaches from the data point to the zero-value-line
Definition at line 2854 of file qcustomplot.h.
                 {
    lsNone
    ,
    lsLine
    ,
    lsStepLeft
    ,
    lsStepRight
    ,
    lsStepCenter
    ,
    lsImpulse
  };
Constructor & Destructor Documentation
QCPGraph::QCPGraph (QCPAxis * keyAxis, QCPAxis * valueAxis) [explicit]
Constructs a graph which uses keyAxis as its key axis (`x`) and valueAxis as its value axis (`y`). keyAxis and valueAxis must reside in the same QCustomPlot instance and not have the same orientation. If either of these restrictions is violated, a corresponding message is printed to the debug output (qDebug), the construction is not aborted, though.
The constructed QCPGraph can be added to the plot with QCustomPlot::addPlottable, QCustomPlot then takes ownership of the graph.
To directly create a graph inside a plot, you can also use the simpler QCustomPlot::addGraph function.
Definition at line 15837 of file qcustomplot.cpp.
References etNone, lsLine, mData, setAdaptiveSampling(), QCPAbstractPlottable::setBrush(), setChannelFillGraph(), setErrorBarSize(), setErrorBarSkipSymbol(), setErrorPen(), setErrorType(), setLineStyle(), QCPAbstractPlottable::setPen(), QCPAbstractPlottable::setSelectedBrush(), and QCPAbstractPlottable::setSelectedPen().
    : QCPAbstractPlottable(keyAxis, valueAxis) {
  mData = new QCPDataMap;
  setPen(QPen(Qt::blue, 0));
  setErrorPen(QPen(Qt::black));
  setBrush(Qt::NoBrush);
  setSelectedPen(QPen(QColor(80, 80, 255), 2.5));
  setSelectedBrush(Qt::NoBrush);
  setLineStyle(lsLine);
  setErrorType(etNone);
  setErrorBarSize(6);
  setErrorBarSkipSymbol(true);
  setChannelFillGraph(0);
  setAdaptiveSampling(true);
}
QCPGraph::~QCPGraph () [virtual]
Definition at line 15855 of file qcustomplot.cpp.
References mData.
{ delete mData; }
Member Function Documentation
bool QCPGraph::adaptiveSampling () const [inline]
Definition at line 2902 of file qcustomplot.h.
{ return mAdaptiveSampling; }
void QCPGraph::addData (const QCPDataMap & dataMap)
Adds the provided data points in dataMap to the current data.
Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap.
See also
removeData
Definition at line 16253 of file qcustomplot.cpp.
References mData.
{ mData->unite(dataMap); }
void QCPGraph::addData (const QCPData & data)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point in data to the current data.
Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap.
See also
removeData
Definition at line 16264 of file qcustomplot.cpp.
References QCPData::key, and mData.
                                          {
  mData->insertMulti(data.key, data);
}
void QCPGraph::addData (double key, double value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided single data point as key and value pair to the current data.
Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap.
See also
removeData
Definition at line 16278 of file qcustomplot.cpp.
References QCPData::key, mData, and QCPData::value.
                                               {
  QCPData newData;
  newData.key = key;
  newData.value = value;
  mData->insertMulti(newData.key, newData);
}
void QCPGraph::addData (const QVector< double > & keys, const QVector< double > & values)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Adds the provided data points as key and value pairs to the current data.
Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap.
See also
removeData
Definition at line 16295 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                      {
  int n = qMin(keys.size(), values.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = keys[i];
    newData.value = values[i];
    mData->insertMulti(newData.key, newData);
  }
}
void QCPGraph::addFillBasePoints (QVector< QPointF > * lineData) const [protected]
Definition at line 17655 of file qcustomplot.cpp.
References lowerFillBasePoint(), QCPAbstractPlottable::mKeyAxis, and upperFillBasePoint().
Referenced by drawFill().
                                                                 {
  if (!mKeyAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key axis";
    return;
  }
  // append points that close the polygon fill at the key axis:
  if (mKeyAxis.data()->orientation() == Qt::Vertical) {
    *lineData << upperFillBasePoint(lineData->last().y());
    *lineData << lowerFillBasePoint(lineData->first().y());
  } else {
    *lineData << upperFillBasePoint(lineData->last().x());
    *lineData << lowerFillBasePoint(lineData->first().x());
  }
}
QCPGraph* QCPGraph::channelFillGraph () const [inline]
Definition at line 2901 of file qcustomplot.h.
References data().
{ return mChannelFillGraph.data(); }
void QCPGraph::clearData () [virtual]
Removes all data points.
See also
removeData, removeDataAfter, removeDataBefore
Implements QCPAbstractPlottable.
Definition at line 16361 of file qcustomplot.cpp.
References mData.
{ mData->clear(); }
int QCPGraph::countDataInBounds (const QCPDataMap::const_iterator & lower, const QCPDataMap::const_iterator & upper, int maxCount) const [protected]
Definition at line 17619 of file qcustomplot.cpp.
References count, and mData.
Referenced by getPreparedData().
                                                    {
  if (upper == mData->constEnd() && lower == mData->constEnd())
    return 0;
  QCPDataMap::const_iterator it = lower;
  int count = 1;
  while (it != upper && count < maxCount) {
    ++it;
    ++count;
  }
  return count;
}
QCPDataMap * QCPGraph::data () const [inline]
Returns a pointer to the internal data storage of type QCPDataMap. You may use it to directly manipulate the data, which may be more convenient and faster than using the regular setData or addData methods, in certain situations.
Definition at line 2894 of file qcustomplot.h.
Referenced by channelFillGraph(), setData(), and QCPItemTracer::updatePosition().
{ return mData; }
void QCPGraph::draw (QCPPainter * painter) [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 16473 of file qcustomplot.cpp.
References drawFill(), drawImpulsePlot(), drawLinePlot(), drawScatterPlot(), getPlotData(), QCP::isInvalidData(), QCPScatterStyle::isNone(), lsImpulse, lsNone, mData, QCPAbstractPlottable::mKeyAxis, mLineStyle, mScatterStyle, QCPAbstractPlottable::mValueAxis, and QCPAbstractPlottable::name().
                                       {
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  if (mKeyAxis.data()->range().size() <= 0 || mData->isEmpty())
    return;
  if (mLineStyle == lsNone && mScatterStyle.isNone())
    return;
  // allocate line and (if necessary) point vectors:
  QVector<QPointF> *lineData = new QVector<QPointF>;
  QVector<QCPData> *scatterData = 0;
  if (!mScatterStyle.isNone())
    scatterData = new QVector<QCPData>;
  // fill vectors with data appropriate to plot style:
  getPlotData(lineData, scatterData);
// check data validity if flag set:
#ifdef QCUSTOMPLOT_CHECK_DATA
  QCPDataMap::const_iterator it;
  for (it = mData->constBegin(); it != mData->constEnd(); ++it) {
    if (QCP::isInvalidData(it.value().key, it.value().value) ||
        QCP::isInvalidData(it.value().keyErrorPlus, it.value().keyErrorMinus) ||
        QCP::isInvalidData(it.value().valueErrorPlus,
                           it.value().valueErrorPlus))
      qDebug() << Q_FUNC_INFO << "Data point at" << it.key() << "invalid."
               << "Plottable name:" << name();
  }
#endif
  // draw fill of graph:
  drawFill(painter, lineData);
  // draw line:
  if (mLineStyle == lsImpulse)
    drawImpulsePlot(painter, lineData);
  else if (mLineStyle != lsNone)
    drawLinePlot(painter,
                 lineData); // also step plots can be drawn as a line plot
  // draw scatters:
  if (scatterData)
    drawScatterPlot(painter, scatterData);
  // free allocated line and point vectors:
  delete lineData;
  if (scatterData)
    delete scatterData;
}
void QCPGraph::drawError (QCPPainter * painter, double x, double y, const QCPData & data) const [protected]
Definition at line 17458 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), QCPPainter::drawLine(), etBoth, etKey, etValue, QCPData::key, QCPAbstractPlottable::keyAxis(), QCPData::keyErrorMinus, QCPData::keyErrorPlus, mErrorBarSize, mErrorBarSkipSymbol, mErrorType, QCPAbstractPlottable::mKeyAxis, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::rangeReversed(), QCPScatterStyle::size(), QCPData::value, QCPAbstractPlottable::valueAxis(), QCPData::valueErrorMinus, and QCPData::valueErrorPlus.
Referenced by drawScatterPlot().
                                                    {
  if (qIsNaN(data.value))
    return;
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  double a, b; // positions of error bar bounds in pixels
  double barWidthHalf = mErrorBarSize * 0.5;
  double skipSymbolMargin = mScatterStyle.size(); // pixels left blank per side,
                                                  // when mErrorBarSkipSymbol is
                                                  // true
  if (keyAxis->orientation() == Qt::Vertical) {
    // draw key error vertically and value error horizontally
    if (mErrorType == etKey || mErrorType == etBoth) {
      a = keyAxis->coordToPixel(data.key - data.keyErrorMinus);
      b = keyAxis->coordToPixel(data.key + data.keyErrorPlus);
      if (keyAxis->rangeReversed())
        qSwap(a, b);
      // draw spine:
      if (mErrorBarSkipSymbol) {
        if (a - y > skipSymbolMargin) // don't draw spine if error is so small
                                      // it's within skipSymbolmargin
          painter->drawLine(QLineF(x, a, x, y + skipSymbolMargin));
        if (y - b > skipSymbolMargin)
          painter->drawLine(QLineF(x, y - skipSymbolMargin, x, b));
      } else
        painter->drawLine(QLineF(x, a, x, b));
      // draw handles:
      painter->drawLine(QLineF(x - barWidthHalf, a, x + barWidthHalf, a));
      painter->drawLine(QLineF(x - barWidthHalf, b, x + barWidthHalf, b));
    }
    if (mErrorType == etValue || mErrorType == etBoth) {
      a = valueAxis->coordToPixel(data.value - data.
      valueErrorMinus);
      b = valueAxis->coordToPixel(data.value + data.
      valueErrorPlus);
      if (valueAxis->rangeReversed())
        qSwap(a, b);
      // draw spine:
      if (mErrorBarSkipSymbol) {
        if (x - a > skipSymbolMargin) // don't draw spine if error is so small
                                      // it's within skipSymbolmargin
          painter->drawLine(QLineF(a, y, x - skipSymbolMargin, y));
        if (b - x > skipSymbolMargin)
          painter->drawLine(QLineF(x + skipSymbolMargin, y, b, y));
      } else
        painter->drawLine(QLineF(a, y, b, y));
      // draw handles:
      painter->drawLine(QLineF(a, y - barWidthHalf, a, y + barWidthHalf));
      painter->drawLine(QLineF(b, y - barWidthHalf, b, y + barWidthHalf));
    }
  } else // mKeyAxis->orientation() is Qt::Horizontal
  {
    // draw value error vertically and key error horizontally
    if (mErrorType == etKey || mErrorType == etBoth) {
      a = keyAxis->coordToPixel(data.key - data.keyErrorMinus);
      b = keyAxis->coordToPixel(data.key + data.keyErrorPlus);
      if (keyAxis->rangeReversed())
        qSwap(a, b);
      // draw spine:
      if (mErrorBarSkipSymbol) {
        if (x - a > skipSymbolMargin) // don't draw spine if error is so small
                                      // it's within skipSymbolmargin
          painter->drawLine(QLineF(a, y, x - skipSymbolMargin, y));
        if (b - x > skipSymbolMargin)
          painter->drawLine(QLineF(x + skipSymbolMargin, y, b, y));
      } else
        painter->drawLine(QLineF(a, y, b, y));
      // draw handles:
      painter->drawLine(QLineF(a, y - barWidthHalf, a, y + barWidthHalf));
      painter->drawLine(QLineF(b, y - barWidthHalf, b, y + barWidthHalf));
    }
    if (mErrorType == etValue || mErrorType == etBoth) {
      a = valueAxis->coordToPixel(data.value - data.
      valueErrorMinus);
      b = valueAxis->coordToPixel(data.value + data.
      valueErrorPlus);
      if (valueAxis->rangeReversed())
        qSwap(a, b);
      // draw spine:
      if (mErrorBarSkipSymbol) {
        if (a - y > skipSymbolMargin) // don't draw spine if error is so small
                                      // it's within skipSymbolmargin
          painter->drawLine(QLineF(x, a, x, y + skipSymbolMargin));
        if (y - b > skipSymbolMargin)
          painter->drawLine(QLineF(x, y - skipSymbolMargin, x, b));
      } else
        painter->drawLine(QLineF(x, a, x, b));
      // draw handles:
      painter->drawLine(QLineF(x - barWidthHalf, a, x + barWidthHalf, a));
      painter->drawLine(QLineF(x - barWidthHalf, b, x + barWidthHalf, b));
    }
  }
}
void QCPGraph::drawFill (QCPPainter * painter, QVector< QPointF > * lineData) const [protected], [virtual]
Definition at line 16960 of file qcustomplot.cpp.
References addFillBasePoints(), QCPAbstractPlottable::applyFillAntialiasingHint(), getChannelFillPolygon(), lsImpulse, QCPAbstractPlottable::mainBrush(), mChannelFillGraph, mLineStyle, removeFillBasePoints(), and QCPPainter::setPen().
Referenced by draw().
                                                                             {
  if (mLineStyle == lsImpulse)
    return; // fill doesn't make sense for impulse plot
  if (mainBrush().style() == Qt::NoBrush || mainBrush().color().alpha() == 0)
    return;
  applyFillAntialiasingHint(painter);
  if (!mChannelFillGraph) {
    // draw base fill under graph, fill goes all the way to the zero-value-line:
    addFillBasePoints(lineData);
    painter->setPen(Qt::NoPen);
    painter->setBrush(mainBrush());
    painter->drawPolygon(QPolygonF(*lineData));
    removeFillBasePoints(lineData);
  } else {
    // draw channel fill between this graph and mChannelFillGraph:
    painter->setPen(Qt::NoPen);
    painter->setBrush(mainBrush());
    painter->drawPolygon(getChannelFillPolygon(lineData));
  }
}
void QCPGraph::drawImpulsePlot (QCPPainter * painter, QVector< QPointF > * lineData) const [protected], [virtual]
Definition at line 17131 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::mainPen(), QCPAbstractPlottable::pen(), and QCPPainter::setPen().
Referenced by draw().
                                                                 {
  // draw impulses:
  if (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0) {
    applyDefaultAntialiasingHint(painter);
    QPen pen = mainPen();
    pen.setCapStyle(
        Qt::FlatCap); // so impulse line doesn't reach beyond zero-line
    painter->setPen(pen);
    painter->setBrush(Qt::NoBrush);
    painter->drawLines(*lineData);
  }
}
void QCPGraph::drawLegendIcon (QCPPainter * painter, const QRectF & rect) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 16526 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPAbstractPlottable::applyFillAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPScatterStyle::applyTo(), QCPPainter::drawLine(), QCPScatterStyle::drawShape(), QCPScatterStyle::isNone(), lsNone, QCPAbstractPlottable::mBrush, mLineStyle, QCPAbstractPlottable::mPen, mScatterStyle, QCPScatterStyle::pixmap(), QCPPainter::setPen(), QCPScatterStyle::setPixmap(), QCPScatterStyle::shape(), and QCPScatterStyle::ssPixmap.
                                                                           {
  // draw fill:
  if (mBrush.style() != Qt::NoBrush) {
    applyFillAntialiasingHint(painter);
    painter->fillRect(QRectF(rect.left(), rect.top() + rect.height() / 2.0,
                             rect.width(), rect.height() / 3.0),
                      mBrush);
  }
  // draw line vertically centered:
  if (mLineStyle != lsNone) {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mPen);
    painter->drawLine(
        QLineF(rect.left(), rect.top() + rect.height() / 2.0, rect.right() + 5,
               rect.top() + rect.height() / 2.0)); // +5 on x2 else last segment
                                                   // is missing from
                                                   // dashed/dotted pens
  }
  // draw scatter symbol:
  if (!mScatterStyle.isNone()) {
    applyScattersAntialiasingHint(painter);
    // scale scatter pixmap if it's too large to fit in legend icon rect:
    if (mScatterStyle.shape() == QCPScatterStyle::ssPixmap &&
        (mScatterStyle.pixmap().size().width() > rect.width() ||
         mScatterStyle.pixmap().size().height() > rect.height())) {
      QCPScatterStyle scaledStyle(mScatterStyle);
      scaledStyle.setPixmap(scaledStyle.pixmap().scaled(
          rect.size().toSize(), Qt::KeepAspectRatio, Qt::SmoothTransformation));
      scaledStyle.applyTo(painter, mPen);
      scaledStyle.drawShape(painter, QRectF(rect).center());
    } else {
      mScatterStyle.applyTo(painter, mPen);
      mScatterStyle.drawShape(painter, QRectF(rect).center());
    }
  }
}
void QCPGraph::drawLinePlot (QCPPainter * painter, QVector< QPointF > * lineData) const [protected], [virtual]
Definition at line 17051 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyDefaultAntialiasingHint(), QCPPainter::drawLine(), i, QCPAbstractPlottable::mainPen(), QCPPainter::modes(), QCPLayerable::mParentPlot, QCP::phFastPolylines, QCustomPlot::plottingHints(), QCPPainter::pmNoCaching, QCPPainter::pmVectorized, and QCPPainter::setPen().
Referenced by draw().
                                                              {
  // draw line of graph:
  if (mainPen().style() != Qt::NoPen && mainPen().color().alpha() != 0) {
    applyDefaultAntialiasingHint(painter);
    painter->setPen(mainPen());
    painter->setBrush(Qt::NoBrush);
    /* Draws polyline in batches, currently not used:
    int p = 0;
    while (p < lineData->size())
    {
      int batch = qMin(25, lineData->size()-p);
      if (p != 0)
      {
        ++batch;
        --p; // to draw the connection lines between two batches
      }
      painter->drawPolyline(lineData->constData()+p, batch);
      p += batch;
    }
    */
    // if drawing solid line and not in PDF, use much faster line drawing
    // instead of polyline:
    if (mParentPlot->plottingHints().testFlag(
      QCP::phFastPolylines) &&
        painter->pen().style() == Qt::SolidLine &&
        !painter->modes().testFlag(QCPPainter::pmVectorized) &&
        !painter->modes().testFlag(QCPPainter::pmNoCaching)) {
      int i = 0;
      bool lastIsNan = false;
      const int lineDataSize = lineData->size();
      while (i < lineDataSize &&
             (qIsNaN(lineData->at(i).y()) ||
              qIsNaN(lineData->at(i).x()))) // make sure first point is not NaN
        ++i;
      ++i; // because drawing works in 1 point retrospect
      while (i < lineDataSize) {
        if (!qIsNaN(lineData->at(i).y()) &&
            !qIsNaN(lineData->at(i).x())) // NaNs create a gap in the line
        {
          if (!lastIsNan)
            painter->drawLine(lineData->at(i - 1), lineData->at(i));
          else
            lastIsNan = false;
        } else
          lastIsNan = true;
        ++i;
      }
    } else {
      int segmentStart = 0;
      int i = 0;
      const int lineDataSize = lineData->size();
      while (i < lineDataSize) {
        if (qIsNaN(lineData->at(i).y()) ||
            qIsNaN(lineData->at(i).x())) // NaNs create a gap in the line
        {
          painter->drawPolyline(lineData->constData() + segmentStart,
                                i - segmentStart); // i, because we don't want
                                                   // to include the current NaN
                                                   // point
          segmentStart = i + 1;
        }
        ++i;
      }
      // draw last segment:
      painter->drawPolyline(lineData->constData() + segmentStart,
                            lineDataSize - segmentStart);
    }
  }
}
void QCPGraph::drawScatterPlot (QCPPainter * painter, QVector< QCPData > * scatterData) const [protected], [virtual]
Definition at line 16994 of file qcustomplot.cpp.
References QCPAbstractPlottable::applyErrorBarsAntialiasingHint(), QCPAbstractPlottable::applyScattersAntialiasingHint(), QCPScatterStyle::applyTo(), QCPAxis::coordToPixel(), drawError(), QCPScatterStyle::drawShape(), etNone, i, QCPAbstractPlottable::keyAxis(), mErrorPen, mErrorType, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mPen, mScatterStyle, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPPainter::setPen(), and QCPAbstractPlottable::valueAxis().
Referenced by draw().
                                                                    {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  // draw error bars:
  if (mErrorType != etNone) {
    applyErrorBarsAntialiasingHint(painter);
    painter->setPen(mErrorPen);
    if (keyAxis->orientation() == Qt::Vertical) {
      for (int i = 0; i < scatterData->size(); ++i)
        drawError(painter, valueAxis->coordToPixel(scatterData->at(
      i).value),
                  keyAxis->coordToPixel(scatterData->at(i).key),
                  scatterData->at(i));
    } else {
      for (int i = 0; i < scatterData->size(); ++i)
        drawError(painter, keyAxis->coordToPixel(scatterData->at(
      i).key),
                  valueAxis->coordToPixel(scatterData->at(i).value),
                  scatterData->at(i));
    }
  }
  // draw scatter point symbols:
  applyScattersAntialiasingHint(painter);
  mScatterStyle.applyTo(painter, mPen);
  if (keyAxis->orientation() == Qt::Vertical) {
    for (int i = 0; i < scatterData->size(); ++i)
      if (!qIsNaN(scatterData->at(i).value))
        mScatterStyle.drawShape(
            painter, valueAxis->coordToPixel(scatterData->at(i).value),
            keyAxis->coordToPixel(scatterData->at(i).key));
  } else {
    for (int i = 0; i < scatterData->size(); ++i)
      if (!qIsNaN(scatterData->at(i).value))
        mScatterStyle.drawShape(
            painter, keyAxis->coordToPixel(scatterData->at(i).key),
            valueAxis->coordToPixel(scatterData->at(i).value));
  }
}
double QCPGraph::errorBarSize () const [inline]
Definition at line 2899 of file qcustomplot.h.
{ return mErrorBarSize; }
bool QCPGraph::errorBarSkipSymbol () const [inline]
Definition at line 2900 of file qcustomplot.h.
{ return mErrorBarSkipSymbol; }
QPen QCPGraph::errorPen () const [inline]
Definition at line 2898 of file qcustomplot.h.
{ return mErrorPen; }
ErrorType QCPGraph::errorType () const [inline]
Definition at line 2897 of file qcustomplot.h.
Referenced by setErrorType().
{ return mErrorType; }
int QCPGraph::findIndexAboveX (const QVector< QPointF > * data, double x) const [protected]
Definition at line 18032 of file qcustomplot.cpp.
References i, and x.
Referenced by getChannelFillPolygon().
                                                                          {
  for (int i = data->size() - 1; i >= 0; --i) {
    if (data->at(i).x() < x) {
      if (i < data->size() - 1)
        return i + 1;
      else
        return data->size() - 1;
    }
  }
  return -1;
}
int QCPGraph::findIndexAboveY (const QVector< QPointF > * data, double y) const [protected]
Definition at line 18074 of file qcustomplot.cpp.
References i, and y.
Referenced by getChannelFillPolygon().
                                                                          {
  for (int i = 0; i < data->size(); ++i) {
    if (data->at(i).y() < y) {
      if (i > 0)
        return i - 1;
      else
        return 0;
    }
  }
  return -1;
}
int QCPGraph::findIndexBelowX (const QVector< QPointF > * data, double x) const [protected]
Definition at line 18053 of file qcustomplot.cpp.
References i, and x.
Referenced by getChannelFillPolygon().
                                                                          {
  for (int i = 0; i < data->size(); ++i) {
    if (data->at(i).x() > x) {
      if (i > 0)
        return i - 1;
      else
        return 0;
    }
  }
  return -1;
}
int QCPGraph::findIndexBelowY (const QVector< QPointF > * data, double y) const [protected]
Definition at line 18172 of file qcustomplot.cpp.
References i, and y.
Referenced by getChannelFillPolygon().
                                                                          {
  for (int i = data->size() - 1; i >= 0; --i) {
    if (data->at(i).y() > y) {
      if (i < data->size() - 1)
        return i + 1;
      else
        return data->size() - 1;
    }
  }
  return -1;
}
const QPolygonF QCPGraph::getChannelFillPolygon (const QVector< QPointF > * lineData) const [protected]
Definition at line 17841 of file qcustomplot.cpp.
References findIndexAboveX(), findIndexAboveY(), findIndexBelowX(), findIndexBelowY(), i, QCPAbstractPlottable::keyAxis(), mChannelFillGraph, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by drawFill().
                                                                      {
  if (!mChannelFillGraph)
    return QPolygonF();
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return QPolygonF();
  }
  if (!mChannelFillGraph.data()->mKeyAxis) {
    qDebug() << Q_FUNC_INFO << "channel fill target key axis invalid";
    return QPolygonF();
  }
  if (mChannelFillGraph.data()->mKeyAxis.data()->orientation() !=
      keyAxis->orientation())
    return QPolygonF(); // don't have same axis orientation, can't fill that
                        // (Note: if keyAxis fits, valueAxis will fit too,
                        // because it's always orthogonal to keyAxis)
  if (lineData->isEmpty())
    return QPolygonF();
  QVector<QPointF> otherData;
  mChannelFillGraph.data()->getPlotData(&otherData, 0);
  if (otherData.isEmpty())
    return QPolygonF();
  QVector<QPointF> thisData;
  thisData.reserve(lineData->size() + otherData.size()); // because we will join
                                                         // both vectors at end
                                                         // of this function
  for (int i = 0; i < lineData->size(); ++i) // don't use the vector<<(vector),
                                             // it squeezes internally, which
                                             // ruins the performance tuning
                                             // with reserve()
    thisData << lineData->at(i);
  // pointers to be able to swap them, depending which data range needs
  // cropping:
  QVector<QPointF> *staticData = &thisData;
  QVector<QPointF> *croppedData = &otherData;
  // crop both vectors to ranges in which the keys overlap (which coord is key,
  // depends on axisType):
  if (keyAxis->orientation() == Qt::Horizontal) {
    // x is key
    // if an axis range is reversed, the data point keys will be descending.
    // Reverse them, since following algorithm assumes ascending keys:
    if (staticData->first().x() > staticData->last().x()) {
      int size = staticData->size();
      for (int i = 0; i < size / 2; ++i)
        qSwap((*staticData)[i], (*staticData)[size - 1 - i]);
    }
    if (croppedData->first().x() > croppedData->last().x()) {
      int size = croppedData->size();
      for (int i = 0; i < size / 2; ++i)
        qSwap((*croppedData)[i], (*croppedData)[size - 1 - i]);
    }
    // crop lower bound:
    if (staticData->first().x() <
        croppedData->first().x()) // other one must be cropped
      qSwap(staticData, croppedData);
    int lowBound = findIndexBelowX(croppedData, staticData->first().x());
    if (lowBound == -1)
      return QPolygonF(); // key ranges have no overlap
    croppedData->remove(0, lowBound);
    // set lowest point of cropped data to fit exactly key position of first
    // static data
    // point via linear interpolation:
    if (croppedData->size() < 2)
      return QPolygonF(); // need at least two points for interpolation
    double slope;
    if (croppedData->at(1).x() - croppedData->at(0).x() != 0)
      slope = (croppedData->at(1).y() - croppedData->at(0).y()) /
              (croppedData->at(1).x() - croppedData->at(0).x());
    else
      slope = 0;
    (*croppedData)[0].setY(
        croppedData->at(0).y() +
        slope * (staticData->first().x() - croppedData->at(0).x()));
    (*croppedData)[0].setX(staticData->first().x());
    // crop upper bound:
    if (staticData->last().x() >
        croppedData->last().x()) // other one must be cropped
      qSwap(staticData, croppedData);
    int highBound = findIndexAboveX(croppedData, staticData->last().x());
    if (highBound == -1)
      return QPolygonF(); // key ranges have no overlap
    croppedData->remove(highBound + 1, croppedData->size() - (highBound + 1));
    // set highest point of cropped data to fit exactly key position of last
    // static data
    // point via linear interpolation:
    if (croppedData->size() < 2)
      return QPolygonF(); // need at least two points for interpolation
    int li = croppedData->size() - 1; // last index
    if (croppedData->at(li).x() - croppedData->at(li - 1).x() != 0)
      slope = (croppedData->at(li).y() - croppedData->at(li - 1).y()) /
              (croppedData->at(li).x() - croppedData->at(li - 1).x());
    else
      slope = 0;
    (*croppedData)[li].setY(
        croppedData->at(li - 1).y() +
        slope * (staticData->last().x() - croppedData->at(li - 1).x()));
    (*croppedData)[li].setX(staticData->last().x());
  } else // mKeyAxis->orientation() == Qt::Vertical
  {
    // y is key
    // similar to "x is key" but switched x,y. Further, lower/upper meaning is
    // inverted compared to x,
    // because in pixel coordinates, y increases from top to bottom, not bottom
    // to top like data coordinate.
    // if an axis range is reversed, the data point keys will be descending.
    // Reverse them, since following algorithm assumes ascending keys:
    if (staticData->first().y() < staticData->last().y()) {
      int size = staticData->size();
      for (int i = 0; i < size / 2; ++i)
        qSwap((*staticData)[i], (*staticData)[size - 1 - i]);
    }
    if (croppedData->first().y() < croppedData->last().y()) {
      int size = croppedData->size();
      for (int i = 0; i < size / 2; ++i)
        qSwap((*croppedData)[i], (*croppedData)[size - 1 - i]);
    }
    // crop lower bound:
    if (staticData->first().y() >
        croppedData->first().y()) // other one must be cropped
      qSwap(staticData, croppedData);
    int lowBound = findIndexAboveY(croppedData, staticData->first().y());
    if (lowBound == -1)
      return QPolygonF(); // key ranges have no overlap
    croppedData->remove(0, lowBound);
    // set lowest point of cropped data to fit exactly key position of first
    // static data
    // point via linear interpolation:
    if (croppedData->size() < 2)
      return QPolygonF(); // need at least two points for interpolation
    double slope;
    if (croppedData->at(1).y() - croppedData->at(0).y() !=
        0) // avoid division by zero in step plots
      slope = (croppedData->at(1).x() - croppedData->at(0).x()) /
              (croppedData->at(1).y() - croppedData->at(0).y());
    else
      slope = 0;
    (*croppedData)[0].setX(
        croppedData->at(0).x() +
        slope * (staticData->first().y() - croppedData->at(0).y()));
    (*croppedData)[0].setY(staticData->first().y());
    // crop upper bound:
    if (staticData->last().y() <
        croppedData->last().y()) // other one must be cropped
      qSwap(staticData, croppedData);
    int highBound = findIndexBelowY(croppedData, staticData->last().y());
    if (highBound == -1)
      return QPolygonF(); // key ranges have no overlap
    croppedData->remove(highBound + 1, croppedData->size() - (highBound + 1));
    // set highest point of cropped data to fit exactly key position of last
    // static data
    // point via linear interpolation:
    if (croppedData->size() < 2)
      return QPolygonF(); // need at least two points for interpolation
    int li = croppedData->size() - 1; // last index
    if (croppedData->at(li).y() - croppedData->at(li - 1).y() !=
        0) // avoid division by zero in step plots
      slope = (croppedData->at(li).x() - croppedData->at(li - 1).x()) /
              (croppedData->at(li).y() - croppedData->at(li - 1).y());
    else
      slope = 0;
    (*croppedData)[li].setX(
        croppedData->at(li - 1).x() +
        slope * (staticData->last().y() - croppedData->at(li - 1).y()));
    (*croppedData)[li].setY(staticData->last().y());
  }
  // return joined:
  for (int i = otherData.size() - 1; i >= 0;
       --i) // insert reversed, otherwise the polygon will be twisted
    thisData << otherData.at(i);
  return QPolygonF(thisData);
}
void QCPGraph::getImpulsePlotData (QVector< QPointF > * linePixelData, QVector< QCPData > * scatterData) const [protected]
Definition at line 16897 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPreparedData(), i, QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by getPlotData().
                                                                       {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  if (!linePixelData) {
    qDebug() << Q_FUNC_INFO << "null pointer passed as linePixelData";
    return;
  }
  QVector<QCPData> lineData;
  getPreparedData(&lineData, scatterData);
  linePixelData->resize(
      lineData.size() *
      2); // no need to reserve 2 extra points because impulse plot has no fill
  // transform lineData points to pixels:
  if (keyAxis->orientation() == Qt::Vertical) {
    double zeroPointX = valueAxis->coordToPixel(0);
    double key;
    for (int i = 0; i < lineData.size(); ++i) {
      key = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 0].setX(zeroPointX);
      (*linePixelData)[i * 2 + 0].setY(key);
      (*linePixelData)[i * 2 + 1].setX(
          valueAxis->coordToPixel(lineData.at(i).value));
      (*linePixelData)[i * 2 + 1].setY(key);
    }
  } else // key axis is horizontal
  {
    double zeroPointY = valueAxis->coordToPixel(0);
    double key;
    for (int i = 0; i < lineData.size(); ++i) {
      key = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 0].setX(key);
      (*linePixelData)[i * 2 + 0].setY(zeroPointY);
      (*linePixelData)[i * 2 + 1].setX(key);
      (*linePixelData)[i * 2 + 1].setY(
          valueAxis->coordToPixel(lineData.at(i).value));
    }
  }
}
QCPRange QCPGraph::getKeyRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 18185 of file qcustomplot.cpp.
Referenced by rescaleKeyAxis().
                                                              {
  // just call the specialized version which takes an additional argument
  // whether error bars
  // should also be taken into consideration for range calculation. We set this
  // to true here.
  return getKeyRange(foundRange, inSignDomain, true);
}
QCPRange QCPGraph::getKeyRange (bool & foundRange, SignDomain inSignDomain, bool includeErrors) const [protected], [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to specify whether the error bars should be included in the range calculation.
See also
getKeyRange(bool &foundRange, SignDomain inSignDomain)
Definition at line 18211 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
                                                         {
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  double current, currentErrorMinus, currentErrorPlus;
  if (inSignDomain == sdBoth) // range may be anywhere
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd()) {
      if (!qIsNaN(it.value().value)) {
        current = it.value().key;
        currentErrorMinus = (includeErrors ? it.value().keyErrorMinus : 0);
        currentErrorPlus = (includeErrors ? it.value().keyErrorPlus : 0);
        if (current - currentErrorMinus < range.lower || !haveLower) {
          range.lower = current - currentErrorMinus;
          haveLower = true;
        }
        if (current + currentErrorPlus > range.upper || !haveUpper) {
          range.upper = current + currentErrorPlus;
          haveUpper = true;
        }
      }
      ++it;
    }
  } else if (inSignDomain ==
             sdNegative) // range may only be in the negative sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd()) {
      if (!qIsNaN(it.value().value)) {
        current = it.value().key;
        currentErrorMinus = (includeErrors ? it.value().keyErrorMinus : 0);
        currentErrorPlus = (includeErrors ? it.value().keyErrorPlus : 0);
        if ((current - currentErrorMinus < range.lower || !haveLower) &&
            current - currentErrorMinus < 0) {
          range.lower = current - currentErrorMinus;
          haveLower = true;
        }
        if ((current + currentErrorPlus > range.upper || !haveUpper) &&
            current + currentErrorPlus < 0) {
          range.upper = current + currentErrorPlus;
          haveUpper = true;
        }
        if (includeErrors) // in case point is in valid sign domain but errobars
                           // stretch beyond it, we still want to geht that
                           // point.
        {
          if ((current < range.lower || !haveLower) && current < 0) {
            range.lower = current;
            haveLower = true;
          }
          if ((current > range.upper || !haveUpper) && current < 0) {
            range.upper = current;
            haveUpper = true;
          }
        }
      }
      ++it;
    }
  } else if (inSignDomain ==
             sdPositive) // range may only be in the positive sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd()) {
      if (!qIsNaN(it.value().value)) {
        current = it.value().key;
        currentErrorMinus = (includeErrors ? it.value().keyErrorMinus : 0);
        currentErrorPlus = (includeErrors ? it.value().keyErrorPlus : 0);
        if ((current - currentErrorMinus < range.lower || !haveLower) &&
            current - currentErrorMinus > 0) {
          range.lower = current - currentErrorMinus;
          haveLower = true;
        }
        if ((current + currentErrorPlus > range.upper || !haveUpper) &&
            current + currentErrorPlus > 0) {
          range.upper = current + currentErrorPlus;
          haveUpper = true;
        }
        if (includeErrors) // in case point is in valid sign domain but errobars
                           // stretch beyond it, we still want to get that
                           // point.
        {
          if ((current < range.lower || !haveLower) && current > 0) {
            range.lower = current;
            haveLower = true;
          }
          if ((current > range.upper || !haveUpper) && current > 0) {
            range.upper = current;
            haveUpper = true;
          }
        }
      }
      ++it;
    }
  }
  foundRange = haveLower && haveUpper;
  return range;
}
void QCPGraph::getLinePlotData (QVector< QPointF > * linePixelData, QVector< QCPData > * scatterData) const [protected]
Definition at line 16648 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPreparedData(), i, QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by getPlotData().
                                                                    {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  if (!linePixelData) {
    qDebug() << Q_FUNC_INFO << "null pointer passed as linePixelData";
    return;
  }
  QVector<QCPData> lineData;
  getPreparedData(&lineData, scatterData);
  linePixelData->reserve(lineData.size() + 2); // added 2 to reserve memory for
                                               // lower/upper fill base points
                                               // that might be needed for fill
  linePixelData->resize(lineData.size());
  // transform lineData points to pixels:
  if (keyAxis->orientation() == Qt::Vertical) {
    for (int i = 0; i < lineData.size(); ++i) {
      (*linePixelData)[i].setX(valueAxis->coordToPixel(lineData.at(
      i).value));
      (*linePixelData)[i].setY(keyAxis->coordToPixel(lineData.at(i).key));
    }
  } else // key axis is horizontal
  {
    for (int i = 0; i < lineData.size(); ++i) {
      (*linePixelData)[i].setX(keyAxis->coordToPixel(lineData.at(i).key));
      (*linePixelData)[i].setY(valueAxis->coordToPixel(lineData.at(
      i).value));
    }
  }
}
void QCPGraph::getPlotData (QVector< QPointF > * lineData, QVector< QCPData > * scatterData) const [protected]
Definition at line 16590 of file qcustomplot.cpp.
References getImpulsePlotData(), getLinePlotData(), getScatterPlotData(), getStepCenterPlotData(), getStepLeftPlotData(), getStepRightPlotData(), lsImpulse, lsLine, lsNone, lsStepCenter, lsStepLeft, lsStepRight, and mLineStyle.
Referenced by draw(), and pointDistance().
                                                                {
  switch (mLineStyle) {
  case lsNone:
    getScatterPlotData(scatterData);
    break;
  case lsLine:
    getLinePlotData(lineData, scatterData);
    break;
  case lsStepLeft:
    getStepLeftPlotData(lineData, scatterData);
    break;
  case lsStepRight:
    getStepRightPlotData(lineData, scatterData);
    break;
  case lsStepCenter:
    getStepCenterPlotData(lineData, scatterData);
    break;
  case lsImpulse:
    getImpulsePlotData(lineData, scatterData);
    break;
  }
}
void QCPGraph::getPreparedData (QVector< QCPData > * lineData, QVector< QCPData > * scatterData) const [protected]
Definition at line 17162 of file qcustomplot.cpp.
References c, QCPAxis::coordToPixel(), countDataInBounds(), getVisibleDataBounds(), QCPAbstractPlottable::keyAxis(), QCPRange::lower, mAdaptiveSampling, mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::pixelToCoord(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxis::scaleType(), QCPAxis::stLogarithmic, QCPRange::upper, and QCPAbstractPlottable::valueAxis().
Referenced by getImpulsePlotData(), getLinePlotData(), getScatterPlotData(), getStepCenterPlotData(), getStepLeftPlotData(), and getStepRightPlotData().
                                                                    {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  // get visible data range:
  QCPDataMap::const_iterator lower, upper; // note that upper is the actual
                                           // upper point, and not 1 step after
                                           // the upper point
  getVisibleDataBounds(lower, upper);
  if (lower == mData->constEnd() || upper == mData->constEnd())
    return;
  // count points in visible range, taking into account that we only need to
  // count to the limit maxCount if using adaptive sampling:
  int maxCount = std::numeric_limits<int>::max();
  if (mAdaptiveSampling) {
    int keyPixelSpan = qAbs(keyAxis->coordToPixel(lower.key()) -
                            keyAxis->coordToPixel(upper.key()));
    maxCount = 2 * keyPixelSpan + 2;
  }
  int dataCount = countDataInBounds(lower, upper, maxCount);
  if (mAdaptiveSampling && dataCount >= maxCount) // use adaptive sampling only
                                                  // if there are at least two
                                                  // points per pixel on average
  {
    if (lineData) {
      QCPDataMap::const_iterator it = lower;
      QCPDataMap::const_iterator upperEnd = upper + 1;
      double minValue = it.value().value;
      double maxValue = it.value().value;
      QCPDataMap::const_iterator currentIntervalFirstPoint = it;
      int reversedFactor =
          keyAxis->rangeReversed() != (keyAxis->orientation() == Qt::Vertical)
              ? -1
              : 1; // is used to calculate keyEpsilon pixel into the correct
                   // direction
      int reversedRound =
          keyAxis->rangeReversed() != (keyAxis->orientation() == Qt::Vertical)
              ? 1
              : 0; // is used to switch between floor (normal) and ceil
                   // (reversed) rounding of currentIntervalStartKey
      double currentIntervalStartKey = keyAxis->pixelToCoord(
          (int)(keyAxis->coordToPixel(lower.key()) + reversedRound));
      double lastIntervalEndKey = currentIntervalStartKey;
      double keyEpsilon = qAbs(
          currentIntervalStartKey -
          keyAxis->pixelToCoord(keyAxis->coordToPixel(currentIntervalStartKey) +
                                1.0 * reversedFactor)); // interval of one pixel
                                                        // on screen when mapped
                                                        // to plot key
                                                        // coordinates
      bool keyEpsilonVariable =
          keyAxis->scaleType() ==
          QCPAxis::stLogarithmic; // indicates whether keyEpsilon needs to be
                                  // updated after every interval (for log axes)
      int intervalDataCount = 1;
      ++it; // advance iterator to second data point because adaptive sampling
            // works in 1 point retrospect
      while (it != upperEnd) {
        if (it.key() < currentIntervalStartKey +
                           keyEpsilon) // data point is still within same pixel,
                                       // so skip it and expand value span of
                                       // this cluster if necessary
        {
          if (it.value().value < minValue)
            minValue = it.value().value;
          else if (it.value().value > maxValue)
            maxValue = it.value().value;
          ++intervalDataCount;
        } else // new pixel interval started
        {
          if (intervalDataCount >= 2) // last pixel had multiple data points,
                                      // consolidate them to a cluster
          {
            if (lastIntervalEndKey <
                currentIntervalStartKey - keyEpsilon) // last point is further
                                                      // away, so first point of
                                                      // this cluster must be at
                                                      // a real data point
              lineData->append(
                  QCPData(currentIntervalStartKey + keyEpsilon * 0.2,
                          currentIntervalFirstPoint.value().value));
            lineData->append(
                QCPData(currentIntervalStartKey + keyEpsilon * 0.25, minValue));
            lineData->append(
                QCPData(currentIntervalStartKey + keyEpsilon * 0.75, maxValue));
            if (it.key() > currentIntervalStartKey +
                               keyEpsilon * 2) // new pixel started further away
                                               // from previous cluster, so make
                                               // sure the last point of the
                                               // cluster is at a real data
                                               // point
              lineData->append(
                  QCPData(currentIntervalStartKey + keyEpsilon * 0.8,
                          (it - 1).value().value));
          } else
            lineData->append(QCPData(currentIntervalFirstPoint.key(),
                                     currentIntervalFirstPoint.value().value));
          lastIntervalEndKey = (it - 1).value().key;
          minValue = it.value().value;
          maxValue = it.value().value;
          currentIntervalFirstPoint = it;
          currentIntervalStartKey = keyAxis->pixelToCoord(
              (int)(keyAxis->coordToPixel(it.key()) + reversedRound));
          if (keyEpsilonVariable)
            keyEpsilon =
                qAbs(currentIntervalStartKey -
                     keyAxis->pixelToCoord(
                         keyAxis->coordToPixel(currentIntervalStartKey) +
                         1.0 * reversedFactor));
          intervalDataCount = 1;
        }
        ++it;
      }
      // handle last interval:
      if (intervalDataCount >= 2) // last pixel had multiple data points,
                                  // consolidate them to a cluster
      {
        if (lastIntervalEndKey <
            currentIntervalStartKey - keyEpsilon) // last point wasn't a
                                                  // cluster, so first point of
                                                  // this cluster must be at a
                                                  // real data point
          lineData->append(QCPData(currentIntervalStartKey + keyEpsilon * 0.2,
                                   currentIntervalFirstPoint.value().value));
        lineData->append(
            QCPData(currentIntervalStartKey + keyEpsilon * 0.25, minValue));
        lineData->append(
            QCPData(currentIntervalStartKey + keyEpsilon * 0.75, maxValue));
      } else
        lineData->append(QCPData(currentIntervalFirstPoint.key(),
                                 currentIntervalFirstPoint.value().value));
    }
    if (scatterData) {
      double valueMaxRange = valueAxis->range().upper;
      double valueMinRange = valueAxis->range().lower;
      QCPDataMap::const_iterator it = lower;
      QCPDataMap::const_iterator upperEnd = upper + 1;
      double minValue = it.value().value;
      double maxValue = it.value().value;
      QCPDataMap::const_iterator minValueIt = it;
      QCPDataMap::const_iterator maxValueIt = it;
      QCPDataMap::const_iterator currentIntervalStart = it;
      int reversedFactor =
          keyAxis->rangeReversed() ? -1 : 1; // is used to calculate keyEpsilon
                                             // pixel into the correct direction
      int reversedRound =
          keyAxis->rangeReversed() ? 1 : 0; // is used to switch between floor
                                            // (normal) and ceil (reversed)
                                            // rounding of
                                            // currentIntervalStartKey
      double currentIntervalStartKey = keyAxis->pixelToCoord(
          (int)(keyAxis->coordToPixel(lower.key()) + reversedRound));
      double keyEpsilon = qAbs(
          currentIntervalStartKey -
          keyAxis->pixelToCoord(keyAxis->coordToPixel(currentIntervalStartKey) +
                                1.0 * reversedFactor)); // interval of one pixel
                                                        // on screen when mapped
                                                        // to plot key
                                                        // coordinates
      bool keyEpsilonVariable =
          keyAxis->scaleType() ==
          QCPAxis::stLogarithmic; // indicates whether keyEpsilon needs to be
                                  // updated after every interval (for log axes)
      int intervalDataCount = 1;
      ++it; // advance iterator to second data point because adaptive sampling
            // works in 1 point retrospect
      while (it != upperEnd) {
        if (it.key() < currentIntervalStartKey +
                           keyEpsilon) // data point is still within same pixel,
                                       // so skip it and expand value span of
                                       // this pixel if necessary
        {
          if (it.value().value < minValue && it.value().value > valueMinRange &&
              it.value().value < valueMaxRange) {
            minValue = it.value().value;
            minValueIt = it;
          } else if (it.value().value > maxValue &&
                     it.value().value > valueMinRange &&
                     it.value().value < valueMaxRange) {
            maxValue = it.value().value;
            maxValueIt = it;
          }
          ++intervalDataCount;
        } else // new pixel started
        {
          if (intervalDataCount >=
              2) // last pixel had multiple data points, consolidate them
          {
            // determine value pixel span and add as many points in interval to
            // maintain certain vertical data density (this is specific to
            // scatter plot):
            double valuePixelSpan = qAbs(valueAxis->coordToPixel(minValue) -
                                         valueAxis->coordToPixel(maxValue));
            int dataModulo =
                qMax(1, qRound(intervalDataCount /
                               (valuePixelSpan / 4.0))); // approximately every
                                                         // 4 value pixels one
                                                         // data point on
                                                         // average
            QCPDataMap::const_iterator intervalIt = currentIntervalStart;
            int c = 0;
            while (intervalIt != it) {
              if ((c % dataModulo == 0 || intervalIt == minValueIt ||
                   intervalIt == maxValueIt) &&
                  intervalIt.value().value > valueMinRange &&
                  intervalIt.value().value < valueMaxRange)
                scatterData->append(intervalIt.value());
              ++c;
              ++intervalIt;
            }
          } else if (currentIntervalStart.value().value > valueMinRange &&
                     currentIntervalStart.value().value < valueMaxRange)
            scatterData->append(currentIntervalStart.value());
          minValue = it.value().value;
          maxValue = it.value().value;
          currentIntervalStart = it;
          currentIntervalStartKey = keyAxis->pixelToCoord(
              (int)(keyAxis->coordToPixel(it.key()) + reversedRound));
          if (keyEpsilonVariable)
            keyEpsilon =
                qAbs(currentIntervalStartKey -
                     keyAxis->pixelToCoord(
                         keyAxis->coordToPixel(currentIntervalStartKey) +
                         1.0 * reversedFactor));
          intervalDataCount = 1;
        }
        ++it;
      }
      // handle last interval:
      if (intervalDataCount >=
          2) // last pixel had multiple data points, consolidate them
      {
        // determine value pixel span and add as many points in interval to
        // maintain certain vertical data density (this is specific to scatter
        // plot):
        double valuePixelSpan = qAbs(valueAxis->coordToPixel(minValue) -
                                     valueAxis->coordToPixel(maxValue));
        int dataModulo =
            qMax(1, qRound(intervalDataCount /
                           (valuePixelSpan / 4.0))); // approximately every 4
                                                     // value pixels one data
                                                     // point on average
        QCPDataMap::const_iterator intervalIt = currentIntervalStart;
        int c = 0;
        while (intervalIt != it) {
          if ((c % dataModulo == 0 || intervalIt == minValueIt ||
               intervalIt == maxValueIt) &&
              intervalIt.value().value > valueMinRange &&
              intervalIt.value().value < valueMaxRange)
            scatterData->append(intervalIt.value());
          ++c;
          ++intervalIt;
        }
      } else if (currentIntervalStart.value().value > valueMinRange &&
                 currentIntervalStart.value().value < valueMaxRange)
        scatterData->append(currentIntervalStart.value());
    }
  } else // don't use adaptive sampling algorithm, transfer points one-to-one
         // from the map into the output parameters
  {
    QVector<QCPData> *dataVector = 0;
    if (lineData)
      dataVector = lineData;
    else if (scatterData)
      dataVector = scatterData;
    if (dataVector) {
      QCPDataMap::const_iterator it = lower;
      QCPDataMap::const_iterator upperEnd = upper + 1;
      dataVector->reserve(dataCount + 2); // +2 for possible fill end points
      while (it != upperEnd) {
        dataVector->append(it.value());
        ++it;
      }
    }
    if (lineData && scatterData)
      *scatterData = *dataVector;
  }
}
void QCPGraph::getScatterPlotData (QVector< QCPData > * scatterData) const [protected]
Definition at line 16629 of file qcustomplot.cpp.
References getPreparedData().
Referenced by getPlotData(), and pointDistance().
                                                                     {
  getPreparedData(0, scatterData);
}
void QCPGraph::getStepCenterPlotData (QVector< QPointF > * linePixelData, QVector< QCPData > * scatterData) const [protected]
Definition at line 16824 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPreparedData(), i, QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by getPlotData().
                                                                          {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  if (!linePixelData) {
    qDebug() << Q_FUNC_INFO << "null pointer passed as lineData";
    return;
  }
  QVector<QCPData> lineData;
  getPreparedData(&lineData, scatterData);
  linePixelData->reserve(lineData.size() * 2 + 2); // added 2 to reserve memory
                                                   // for lower/upper fill base
                                                   // points that might be
                                                   // needed for fill
  linePixelData->resize(lineData.size() * 2);
  // calculate steps from lineData and transform to pixel coordinates:
  if (keyAxis->orientation() == Qt::Vertical) {
    double lastKey = keyAxis->coordToPixel(lineData.first().key);
    double lastValue = valueAxis->coordToPixel(lineData.first().value);
    double key;
    (*linePixelData)[0].setX(lastValue);
    (*linePixelData)[0].setY(lastKey);
    for (int i = 1; i < lineData.size(); ++i) {
      key = (keyAxis->coordToPixel(lineData.at(i).key) + lastKey) * 0.5;
      (*linePixelData)[i * 2 - 1].setX(lastValue);
      (*linePixelData)[i * 2 - 1].setY(key);
      lastValue = valueAxis->coordToPixel(lineData.at(i).value);
      lastKey = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 0].setX(lastValue);
      (*linePixelData)[i * 2 + 0].setY(key);
    }
    (*linePixelData)[lineData.size() * 2 - 1].setX(lastValue);
    (*linePixelData)[lineData.size() * 2 - 1].setY(lastKey);
  } else // key axis is horizontal
  {
    double lastKey = keyAxis->coordToPixel(lineData.first().key);
    double lastValue = valueAxis->coordToPixel(lineData.first().value);
    double key;
    (*linePixelData)[0].setX(lastKey);
    (*linePixelData)[0].setY(lastValue);
    for (int i = 1; i < lineData.size(); ++i) {
      key = (keyAxis->coordToPixel(lineData.at(i).key) + lastKey) * 0.5;
      (*linePixelData)[i * 2 - 1].setX(key);
      (*linePixelData)[i * 2 - 1].setY(lastValue);
      lastValue = valueAxis->coordToPixel(lineData.at(i).value);
      lastKey = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 0].setX(key);
      (*linePixelData)[i * 2 + 0].setY(lastValue);
    }
    (*linePixelData)[lineData.size() * 2 - 1].setX(lastKey);
    (*linePixelData)[lineData.size() * 2 - 1].setY(lastValue);
  }
}
void QCPGraph::getStepLeftPlotData (QVector< QPointF > * linePixelData, QVector< QCPData > * scatterData) const [protected]
Definition at line 16698 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPreparedData(), i, QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by getPlotData().
                                                                        {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  if (!linePixelData) {
    qDebug() << Q_FUNC_INFO << "null pointer passed as lineData";
    return;
  }
  QVector<QCPData> lineData;
  getPreparedData(&lineData, scatterData);
  linePixelData->reserve(lineData.size() * 2 + 2); // added 2 to reserve memory
                                                   // for lower/upper fill base
                                                   // points that might be
                                                   // needed for fill
  linePixelData->resize(lineData.size() * 2);
  // calculate steps from lineData and transform to pixel coordinates:
  if (keyAxis->orientation() == Qt::Vertical) {
    double lastValue = valueAxis->coordToPixel(lineData.first().value);
    double key;
    for (int i = 0; i < lineData.size(); ++i) {
      key = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 0].setX(lastValue);
      (*linePixelData)[i * 2 + 0].setY(key);
      lastValue = valueAxis->coordToPixel(lineData.at(i).value);
      (*linePixelData)[i * 2 + 1].setX(lastValue);
      (*linePixelData)[i * 2 + 1].setY(key);
    }
  } else // key axis is horizontal
  {
    double lastValue = valueAxis->coordToPixel(lineData.first().value);
    double key;
    for (int i = 0; i < lineData.size(); ++i) {
      key = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 0].setX(key);
      (*linePixelData)[i * 2 + 0].setY(lastValue);
      lastValue = valueAxis->coordToPixel(lineData.at(i).value);
      (*linePixelData)[i * 2 + 1].setX(key);
      (*linePixelData)[i * 2 + 1].setY(lastValue);
    }
  }
}
void QCPGraph::getStepRightPlotData (QVector< QPointF > * linePixelData, QVector< QCPData > * scatterData) const [protected]
Definition at line 16761 of file qcustomplot.cpp.
References QCPAxis::coordToPixel(), getPreparedData(), i, QCPAbstractPlottable::keyAxis(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), and QCPAbstractPlottable::valueAxis().
Referenced by getPlotData().
                                                                         {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return;
  }
  if (!linePixelData) {
    qDebug() << Q_FUNC_INFO << "null pointer passed as lineData";
    return;
  }
  QVector<QCPData> lineData;
  getPreparedData(&lineData, scatterData);
  linePixelData->reserve(lineData.size() * 2 + 2); // added 2 to reserve memory
                                                   // for lower/upper fill base
                                                   // points that might be
                                                   // needed for fill
  linePixelData->resize(lineData.size() * 2);
  // calculate steps from lineData and transform to pixel coordinates:
  if (keyAxis->orientation() == Qt::Vertical) {
    double lastKey = keyAxis->coordToPixel(lineData.first().key);
    double value;
    for (int i = 0; i < lineData.size(); ++i) {
      value = valueAxis->coordToPixel(lineData.at(i).value);
      (*linePixelData)[i * 2 + 0].setX(value);
      (*linePixelData)[i * 2 + 0].setY(lastKey);
      lastKey = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 1].setX(value);
      (*linePixelData)[i * 2 + 1].setY(lastKey);
    }
  } else // key axis is horizontal
  {
    double lastKey = keyAxis->coordToPixel(lineData.first().key);
    double value;
    for (int i = 0; i < lineData.size(); ++i) {
      value = valueAxis->coordToPixel(lineData.at(i).value);
      (*linePixelData)[i * 2 + 0].setX(lastKey);
      (*linePixelData)[i * 2 + 0].setY(value);
      lastKey = keyAxis->coordToPixel(lineData.at(i).key);
      (*linePixelData)[i * 2 + 1].setX(lastKey);
      (*linePixelData)[i * 2 + 1].setY(value);
    }
  }
}
QCPRange QCPGraph::getValueRange (bool & foundRange, SignDomain inSignDomain = sdBoth) const [protected], [virtual]
Implements QCPAbstractPlottable.
Definition at line 18195 of file qcustomplot.cpp.
Referenced by rescaleValueAxis().
                                                                {
  // just call the specialized version which takes an additional argument
  // whether error bars
  // should also be taken into consideration for range calculation. We set this
  // to true here.
  return getValueRange(foundRange, inSignDomain, true);
}
QCPRange QCPGraph::getValueRange (bool & foundRange, SignDomain inSignDomain, bool includeErrors) const [protected], [virtual]
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to specify whether the error bars should be included in the range calculation.
See also
getValueRange(bool &foundRange, SignDomain inSignDomain)
Definition at line 18321 of file qcustomplot.cpp.
References QCPRange::lower, mData, QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, and QCPRange::upper.
                                                           {
  QCPRange range;
  bool haveLower = false;
  bool haveUpper = false;
  double current, currentErrorMinus, currentErrorPlus;
  if (inSignDomain == sdBoth) // range may be anywhere
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd()) {
      current = it.value().value;
      if (!qIsNaN(current)) {
        currentErrorMinus = (includeErrors ? it.value().valueErrorMinus : 0);
        currentErrorPlus = (includeErrors ? it.value().valueErrorPlus : 0);
        if (current - currentErrorMinus < range.lower || !haveLower) {
          range.lower = current - currentErrorMinus;
          haveLower = true;
        }
        if (current + currentErrorPlus > range.upper || !haveUpper) {
          range.upper = current + currentErrorPlus;
          haveUpper = true;
        }
      }
      ++it;
    }
  } else if (inSignDomain ==
             sdNegative) // range may only be in the negative sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd()) {
      current = it.value().value;
      if (!qIsNaN(current)) {
        currentErrorMinus = (includeErrors ? it.value().valueErrorMinus : 0);
        currentErrorPlus = (includeErrors ? it.value().valueErrorPlus : 0);
        if ((current - currentErrorMinus < range.lower || !haveLower) &&
            current - currentErrorMinus < 0) {
          range.lower = current - currentErrorMinus;
          haveLower = true;
        }
        if ((current + currentErrorPlus > range.upper || !haveUpper) &&
            current + currentErrorPlus < 0) {
          range.upper = current + currentErrorPlus;
          haveUpper = true;
        }
        if (includeErrors) // in case point is in valid sign domain but errobars
                           // stretch beyond it, we still want to get that
                           // point.
        {
          if ((current < range.lower || !haveLower) && current < 0) {
            range.lower = current;
            haveLower = true;
          }
          if ((current > range.upper || !haveUpper) && current < 0) {
            range.upper = current;
            haveUpper = true;
          }
        }
      }
      ++it;
    }
  } else if (inSignDomain ==
             sdPositive) // range may only be in the positive sign domain
  {
    QCPDataMap::const_iterator it = mData->constBegin();
    while (it != mData->constEnd()) {
      current = it.value().value;
      if (!qIsNaN(current)) {
        currentErrorMinus = (includeErrors ? it.value().valueErrorMinus : 0);
        currentErrorPlus = (includeErrors ? it.value().valueErrorPlus : 0);
        if ((current - currentErrorMinus < range.lower || !haveLower) &&
            current - currentErrorMinus > 0) {
          range.lower = current - currentErrorMinus;
          haveLower = true;
        }
        if ((current + currentErrorPlus > range.upper || !haveUpper) &&
            current + currentErrorPlus > 0) {
          range.upper = current + currentErrorPlus;
          haveUpper = true;
        }
        if (includeErrors) // in case point is in valid sign domain but errobars
                           // stretch beyond it, we still want to geht that
                           // point.
        {
          if ((current < range.lower || !haveLower) && current > 0) {
            range.lower = current;
            haveLower = true;
          }
          if ((current > range.upper || !haveUpper) && current > 0) {
            range.upper = current;
            haveUpper = true;
          }
        }
      }
      ++it;
    }
  }
  foundRange = haveLower && haveUpper;
  return range;
}
void QCPGraph::getVisibleDataBounds (QCPDataMap::const_iterator & lower, QCPDataMap::const_iterator & upper) const [protected]
Definition at line 17573 of file qcustomplot.cpp.
References mData, and QCPAbstractPlottable::mKeyAxis.
Referenced by getPreparedData().
                                                                           {
  if (!mKeyAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key axis";
    return;
  }
  if (mData->isEmpty()) {
    lower = mData->constEnd();
    upper = mData->constEnd();
    return;
  }
  // get visible data range as QMap iterators
  QCPDataMap::const_iterator lbound =
      mData->lowerBound(mKeyAxis.data()->range().lower);
  QCPDataMap::const_iterator ubound =
      mData->upperBound(mKeyAxis.data()->range().upper);
  bool lowoutlier = lbound != mData->constBegin(); // indicates whether there
                                                   // exist points below axis
                                                   // range
  bool highoutlier =
      ubound !=
      mData
          ->constEnd(); // indicates whether there exist points above axis range
  lower = (lowoutlier ? lbound - 1
                      : lbound); // data point range that will be actually drawn
  upper = (highoutlier
               ? ubound
               : ubound - 1); // data point range that will be actually drawn
}
LineStyle QCPGraph::lineStyle () const [inline]
Definition at line 2895 of file qcustomplot.h.
{ return mLineStyle; }
QPointF QCPGraph::lowerFillBasePoint (double lowerKey) const [protected]
Definition at line 17702 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::axisRect(), QCPAxis::axisType(), QCPAxisRect::bottom(), QCPAxis::coordToPixel(), QCPAbstractPlottable::keyAxis(), QCPAxisRect::left(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxisRect::right(), QCPAxis::scaleType(), QCPAxis::stLinear, QCPAxisRect::top(), QCPRange::upper, and QCPAbstractPlottable::valueAxis().
Referenced by addFillBasePoints().
                                                          {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return QPointF();
  }
  QPointF point;
  if (valueAxis->scaleType() == QCPAxis::stLinear) {
    if (keyAxis->axisType() == QCPAxis::atLeft) {
      point.setX(valueAxis->coordToPixel(0));
      point.setY(lowerKey);
    } else if (keyAxis->axisType() == QCPAxis::atRight) {
      point.setX(valueAxis->coordToPixel(0));
      point.setY(lowerKey);
    } else if (keyAxis->axisType() == QCPAxis::atTop) {
      point.setX(lowerKey);
      point.setY(valueAxis->coordToPixel(0));
    } else if (keyAxis->axisType() == QCPAxis::atBottom) {
      point.setX(lowerKey);
      point.setY(valueAxis->coordToPixel(0));
    }
  } else // valueAxis->mScaleType == QCPAxis::stLogarithmic
  {
    // In logarithmic scaling we can't just draw to value zero so we just fill
    // all the way
    // to the axis which is in the direction towards zero
    if (keyAxis->orientation() == Qt::Vertical) {
      if ((valueAxis->range().upper < 0 && !valueAxis->rangeReversed()) ||
          (valueAxis->range().upper > 0 &&
           valueAxis->rangeReversed())) // if range is negative, zero is on
                                        // opposite side of key axis
        point.setX(keyAxis->axisRect()->right());
      else
        point.setX(keyAxis->axisRect()->left());
      point.setY(lowerKey);
    } else if (keyAxis->axisType() == QCPAxis::atTop ||
               keyAxis->axisType() == QCPAxis::atBottom) {
      point.setX(lowerKey);
      if ((valueAxis->range().upper < 0 && !valueAxis->rangeReversed()) ||
          (valueAxis->range().upper > 0 &&
           valueAxis->rangeReversed())) // if range is negative, zero is on
                                        // opposite side of key axis
        point.setY(keyAxis->axisRect()->top());
      else
        point.setY(keyAxis->axisRect()->bottom());
    }
  }
  return point;
}
double QCPGraph::pointDistance (const QPointF & pixelPoint) const [protected]
Definition at line 18099 of file qcustomplot.cpp.
References QCPAbstractPlottable::coordsToPixels(), QCPAbstractPlottable::distSqrToLine(), getPlotData(), getScatterPlotData(), i, QCPScatterStyle::isNone(), lsImpulse, lsNone, mData, mLineStyle, and mScatterStyle.
Referenced by selectTest().
                                                              {
  if (mData->isEmpty())
    return -1.0;
  if (mLineStyle == lsNone && mScatterStyle.isNone())
    return -1.0;
  // calculate minimum distances to graph representation:
  if (mLineStyle == lsNone) {
    // no line displayed, only calculate distance to scatter points:
    QVector<QCPData> scatterData;
    getScatterPlotData(&scatterData);
    if (scatterData.size() > 0) {
      double minDistSqr = std::numeric_limits<double>::max();
      for (int i = 0; i < scatterData.size(); ++i) {
        double currentDistSqr =
            QVector2D(
                coordsToPixels(scatterData.at(i).key, scatterData.at(
      i).value) -
                pixelPoint).lengthSquared();
        if (currentDistSqr < minDistSqr)
          minDistSqr = currentDistSqr;
      }
      return qSqrt(minDistSqr);
    } else // no data available in view to calculate distance to
      return -1.0;
  } else {
    // line displayed, calculate distance to line segments:
    QVector<QPointF> lineData;
    getPlotData(
        &lineData,
        0); // unlike with getScatterPlotData we get pixel coordinates here
    if (lineData.size() >
        1) // at least one line segment, compare distance to line segments
    {
      double minDistSqr = std::numeric_limits<double>::max();
      if (mLineStyle == lsImpulse) {
        // impulse plot differs from other line styles in that the lineData
        // points are only pairwise connected:
        for (int i = 0; i < lineData.size() - 1; i += 2) // iterate pairs
        {
          double currentDistSqr =
              distSqrToLine(lineData.at(i), lineData.at(i + 1), pixelPoint);
          if (currentDistSqr < minDistSqr)
            minDistSqr = currentDistSqr;
        }
      } else {
        // all other line plots (line and step) connect points directly:
        for (int i = 0; i < lineData.size() - 1; ++i) {
          double currentDistSqr =
              distSqrToLine(lineData.at(i), lineData.at(i + 1), pixelPoint);
          if (currentDistSqr < minDistSqr)
            minDistSqr = currentDistSqr;
        }
      }
      return qSqrt(minDistSqr);
    } else if (lineData.size() >
               0) // only single data point, calculate distance to that point
    {
      return QVector2D(lineData.at(0) - pixelPoint).length();
    } else // no data available in view to calculate distance to
      return -1.0;
  }
}
void QCPGraph::removeData (double fromKey, double toKey)
Removes all data points with keys between fromKey and toKey. if fromKey is greater or equal to toKey, the function does nothing. To remove a single data point with known key, use removeData(double key).
See also
addData, clearData
Definition at line 16336 of file qcustomplot.cpp.
References mData.
                                                      {
  if (fromKey >= toKey || mData->isEmpty())
    return;
  QCPDataMap::iterator it = mData->upperBound(fromKey);
  QCPDataMap::iterator itEnd = mData->upperBound(toKey);
  while (it != itEnd)
    it = mData->erase(it);
}
void QCPGraph::removeData (double key)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Removes a single data point at key. If the position is not known with absolute precision, consider using removeData(double fromKey, double toKey) with a small fuzziness interval around the suspected position, depeding on the precision with which the key is known.
See also
addData, clearData
Definition at line 16355 of file qcustomplot.cpp.
References mData.
{ mData->remove(key); }
void QCPGraph::removeDataAfter (double key)
Removes all data points with keys greater than key.
See also
addData, clearData
Definition at line 16320 of file qcustomplot.cpp.
References mData.
                                         {
  if (mData->isEmpty())
    return;
  QCPDataMap::iterator it = mData->upperBound(key);
  while (it != mData->end())
    it = mData->erase(it);
}
void QCPGraph::removeDataBefore (double key)
Removes all data points with keys smaller than key.
See also
addData, clearData
Definition at line 16310 of file qcustomplot.cpp.
References mData.
                                          {
  QCPDataMap::iterator it = mData->begin();
  while (it != mData->end() && it.key() < key)
    it = mData->erase(it);
}
void QCPGraph::removeFillBasePoints (QVector< QPointF > * lineData) const [protected]
Definition at line 17678 of file qcustomplot.cpp.
Referenced by drawFill().
                                                                    {
  lineData->remove(lineData->size() - 2, 2);
}
void QCPGraph::rescaleAxes (bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars are taken into consideration when determining the new axis range.
See also
rescaleKeyAxis, rescaleValueAxis, QCPAbstractPlottable::rescaleAxes, QCustomPlot::rescaleAxes
Definition at line 16389 of file qcustomplot.cpp.
References rescaleKeyAxis(), and rescaleValueAxis().
                                                                        {
  rescaleKeyAxis(onlyEnlarge, includeErrorBars);
  rescaleValueAxis(onlyEnlarge, includeErrorBars);
}
void QCPGraph::rescaleKeyAxis (bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars (of kind QCPGraph::etKey) are taken into consideration when determining the new axis range.
See also
rescaleAxes, QCPAbstractPlottable::rescaleKeyAxis
Definition at line 16402 of file qcustomplot.cpp.
References getKeyRange(), QCPAbstractPlottable::keyAxis(), QCPRange::lower, mData, QCPAbstractPlottable::mKeyAxis, QCPAxis::range(), QCPAxis::scaleType(), QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPAxis::setRange(), QCPAxis::stLogarithmic, and QCPRange::upper.
Referenced by rescaleAxes().
                                                                           {
  // this code is a copy of QCPAbstractPlottable::rescaleKeyAxis with the only
  // change
  // that getKeyRange is passed the includeErrorBars value.
  if (mData->isEmpty())
    return;
  QCPAxis *keyAxis = mKeyAxis.data();
  if (!keyAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key axis";
    return;
  }
  SignDomain signDomain = sdBoth;
  if (keyAxis->scaleType() == QCPAxis::stLogarithmic)
    signDomain = (keyAxis->range().upper < 0 ? sdNegative :
      sdPositive);
  bool foundRange;
  QCPRange newRange = getKeyRange(foundRange, signDomain, includeErrorBars);
  if (foundRange) {
    if (onlyEnlarge) {
      if (keyAxis->range().lower < newRange.lower)
        newRange.lower = keyAxis->range().lower;
      if (keyAxis->range().upper > newRange.upper)
        newRange.upper = keyAxis->range().upper;
    }
    keyAxis->setRange(newRange);
  }
}
void QCPGraph::rescaleValueAxis (bool onlyEnlarge, bool includeErrorBars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows to define whether error bars (of kind QCPGraph::etValue) are taken into consideration when determining the new axis range.
See also
rescaleAxes, QCPAbstractPlottable::rescaleValueAxis
Definition at line 16441 of file qcustomplot.cpp.
References getValueRange(), QCPRange::lower, mData, QCPAbstractPlottable::mValueAxis, QCPAxis::range(), QCPAxis::scaleType(), QCPAbstractPlottable::sdBoth, QCPAbstractPlottable::sdNegative, QCPAbstractPlottable::sdPositive, QCPAxis::setRange(), QCPAxis::stLogarithmic, QCPRange::upper, and QCPAbstractPlottable::valueAxis().
Referenced by rescaleAxes().
                                                                             {
  // this code is a copy of QCPAbstractPlottable::rescaleValueAxis with the only
  // change
  // is that getValueRange is passed the includeErrorBars value.
  if (mData->isEmpty())
    return;
  QCPAxis *valueAxis = mValueAxis.data();
  if (!valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid value axis";
    return;
  }
  SignDomain signDomain = sdBoth;
  if (valueAxis->scaleType() == QCPAxis::stLogarithmic)
    signDomain = (valueAxis->range().upper < 0 ? sdNegative :
      sdPositive);
  bool foundRange;
  QCPRange newRange = getValueRange(foundRange, signDomain, includeErrorBars);
  if (foundRange) {
    if (onlyEnlarge) {
      if (valueAxis->range().lower < newRange.lower)
        newRange.lower = valueAxis->range().lower;
      if (valueAxis->range().upper > newRange.upper)
        newRange.upper = valueAxis->range().upper;
    }
    valueAxis->setRange(newRange);
  }
}
QCPScatterStyle QCPGraph::scatterStyle () const [inline]
Definition at line 2896 of file qcustomplot.h.
{ return mScatterStyle; }
double QCPGraph::selectTest (const QPointF & pos, bool onlySelectable, QVariant * details = 0) const [virtual]
This function is used to decide whether a click hits a layerable object or not.
pos is a point in pixel coordinates on the QCustomPlot surface. This function returns the shortest pixel distance of this point to the object. If the object is either invisible or the distance couldn't be determined, -1.0 is returned. Further, if onlySelectable is true and the object is not selectable, -1.0 is returned, too.
If the object is represented not by single lines but by an area like a QCPItemText or the bars of a QCPBars plottable, a click inside the area should also be considered a hit. In these cases this function thus returns a constant value greater zero but still below the parent plot's selection tolerance. (typically the selectionTolerance multiplied by 0.99).
Providing a constant value for area objects allows selecting line objects even when they are obscured by such area objects, by clicking close to the lines (i.e. closer than 0.99*selectionTolerance).
The actual setting of the selection state is not done by this function. This is handled by the parent QCustomPlot when the mouseReleaseEvent occurs, and the finally selected object is notified via the selectEvent/deselectEvent methods.
details is an optional output parameter. Every layerable subclass may place any information in details. This information will be passed to selectEvent when the parent QCustomPlot decides on the basis of this selectTest call, that the object was successfully selected. The subsequent call to selectEvent will carry the details. This is useful for multi-part objects (like QCPAxis). This way, a possibly complex calculation to decide which part was clicked is only done once in selectTest. The result (i.e. the actually clicked part) can then be placed in details. So in the subsequent selectEvent, the decision which part was selected doesn't have to be done a second time for a single selection operation.
You may pass 0 as details to indicate that you are not interested in those selection details.
See also
selectEvent, deselectEvent, QCustomPlot::setInteractions
Implements QCPAbstractPlottable.
Definition at line 16364 of file qcustomplot.cpp.
References mData, QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mSelectable, QCPAbstractPlottable::mValueAxis, and pointDistance().
                                                     {
  Q_UNUSED(details)
  if ((onlySelectable && !mSelectable) || mData->isEmpty())
    return -1;
  if (!mKeyAxis || !mValueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return -1;
  }
  if (mKeyAxis.data()->axisRect()->rect().contains(pos.toPoint()))
    return pointDistance(pos);
  else
    return -1;
}
void QCPGraph::setAdaptiveSampling (bool enabled)
Sets whether adaptive sampling shall be used when plotting this graph. QCustomPlot's adaptive sampling technique can drastically improve the replot performance for graphs with a larger number of points (e.g. above 10,000), without notably changing the appearance of the graph.
By default, adaptive sampling is enabled. Even if enabled, QCustomPlot decides whether adaptive sampling shall actually be used on a per-graph basis. So leaving adaptive sampling enabled has no disadvantage in almost all cases.
 and with adaptive sampling"
As can be seen, line plots experience no visual degradation from adaptive sampling. Outliers are reproduced reliably, as well as the overall shape of the data set. The replot time reduces dramatically though. This allows QCustomPlot to display large amounts of data in realtime.
 without and with adaptive sampling"
Care must be taken when using high-density scatter plots in combination with adaptive sampling. The adaptive sampling algorithm treats scatter plots more carefully than line plots which still gives a significant reduction of replot times, but not quite as much as for line plots. This is because scatter plots inherently need more data points to be preserved in order to still resemble the original, non-adaptive-sampling plot. As shown above, the results still aren't quite identical, as banding occurs for the outer data points. This is in fact intentional, such that the boundaries of the data cloud stay visible to the viewer. How strong the banding appears, depends on the point density, i.e. the number of points in the plot.
For some situations with scatter plots it might thus be desirable to manually turn adaptive sampling off. For example, when saving the plot to disk. This can be achieved by setting enabled to false before issuing a command like QCustomPlot::savePng, and setting enabled back to true afterwards.
Definition at line 16240 of file qcustomplot.cpp.
References mAdaptiveSampling.
Referenced by QCPGraph().
                                               {
  mAdaptiveSampling = enabled;
}
void QCPGraph::setChannelFillGraph (QCPGraph * targetGraph)
Sets the target graph for filling the area between this graph and targetGraph with the current brush (setBrush).
When targetGraph is set to 0, a normal graph fill to the zero-value-line will be shown. To disable any filling, set the brush to Qt::NoBrush.
See also
setBrush
Definition at line 16172 of file qcustomplot.cpp.
References mChannelFillGraph, and QCPLayerable::mParentPlot.
Referenced by QCPGraph().
                                                        {
  // prevent setting channel target to this graph itself:
  if (targetGraph == this) {
    qDebug() << Q_FUNC_INFO << "targetGraph is this graph itself";
    mChannelFillGraph = 0;
    return;
  }
  // prevent setting channel target to a graph not in the plot:
  if (targetGraph && targetGraph->mParentPlot != mParentPlot) {
    qDebug() << Q_FUNC_INFO << "targetGraph not in same plot";
    mChannelFillGraph = 0;
    return;
  }
  mChannelFillGraph = targetGraph;
}
void QCPGraph::setData (QCPDataMap * data, bool copy = false)
Replaces the current data with the provided data.
If copy is set to true, data points in data will only be copied. if false, the graph takes ownership of the passed data and replaces the internal data pointer with it. This is significantly faster than copying for large datasets.
Alternatively, you can also access and modify the graph's data via the data method, which returns a pointer to the internal QCPDataMap.
Definition at line 15870 of file qcustomplot.cpp.
References data(), and mData.
                                                  {
  if (mData == data) {
    qDebug() << Q_FUNC_INFO
             << "The data pointer is already in (and owned by) this plottable"
             << reinterpret_cast<quintptr>(data);
    return;
  }
  if (copy) {
    *mData = *data;
  } else {
    delete mData;
    mData = data;
  }
}
void QCPGraph::setData (const QVector< double > & key, const QVector< double > & value)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Replaces the current data with the provided points in key and value pairs. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 15893 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                     {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    mData->insertMulti(newData.key, newData);
  }
}
void QCPGraph::setDataBothError (const QVector< double > & key, const QVector< double > & value, const QVector< double > & keyError, const QVector< double > & valueError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical key and value errors of the data points are set to the values in keyError and valueError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
For asymmetrical errors (plus different from minus), see the overloaded version of this function.
Definition at line 16040 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                                   {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueError.size());
  n = qMin(n, keyError.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyError[i];
    newData.keyErrorPlus = keyError[i];
    newData.valueErrorMinus = valueError[i];
    newData.valueErrorPlus = valueError[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataBothError (const QVector< double > & key, const QVector< double > & value, const QVector< double > & keyErrorMinus, const QVector< double > & keyErrorPlus, const QVector< double > & valueErrorMinus, const QVector< double > & valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative key and value errors of the data points are set to the values in keyErrorMinus and valueErrorMinus. The positive key and value errors are set to the values in keyErrorPlus valueErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 16074 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                                       {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueErrorMinus.size());
  n = qMin(n, valueErrorPlus.size());
  n = qMin(n, keyErrorMinus.size());
  n = qMin(n, keyErrorPlus.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyErrorMinus[i];
    newData.keyErrorPlus = keyErrorPlus[i];
    newData.valueErrorMinus = valueErrorMinus[i];
    newData.valueErrorPlus = valueErrorPlus[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataKeyError (const QVector< double > & key, const QVector< double > & value, const QVector< double > & keyError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical key error of the data points are set to the values in keyError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
For asymmetrical errors (plus different from minus), see the overloaded version of this function.
Definition at line 15979 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                                {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, keyError.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyError[i];
    newData.keyErrorPlus = keyError[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataKeyError (const QVector< double > & key, const QVector< double > & value, const QVector< double > & keyErrorMinus, const QVector< double > & keyErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative key error of the data points are set to the values in keyErrorMinus, the positive key error to keyErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 16008 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                                    {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, keyErrorMinus.size());
  n = qMin(n, keyErrorPlus.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    newData.keyErrorMinus = keyErrorMinus[i];
    newData.keyErrorPlus = keyErrorPlus[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataValueError (const QVector< double > & key, const QVector< double > & value, const QVector< double > & valueError)
Replaces the current data with the provided points in key and value pairs. Additionally the symmetrical value error of the data points are set to the values in valueError. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
For asymmetrical errors (plus different from minus), see the overloaded version of this function.
Definition at line 15919 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                                    {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueError.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    newData.valueErrorMinus = valueError[i];
    newData.valueErrorPlus = valueError[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setDataValueError (const QVector< double > & key, const QVector< double > & value, const QVector< double > & valueErrorMinus, const QVector< double > & valueErrorPlus)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Replaces the current data with the provided points in key and value pairs. Additionally the negative value error of the data points are set to the values in valueErrorMinus, the positive value error to valueErrorPlus. For error bars to show appropriately, see setErrorType. The provided vectors should have equal length. Else, the number of added points will be the size of the smallest vector.
Definition at line 15948 of file qcustomplot.cpp.
References i, QCPData::key, mData, and n.
                                                                        {
  mData->clear();
  int n = key.size();
  n = qMin(n, value.size());
  n = qMin(n, valueErrorMinus.size());
  n = qMin(n, valueErrorPlus.size());
  QCPData newData;
  for (int i = 0; i < n; ++i) {
    newData.key = key[i];
    newData.value = value[i];
    newData.valueErrorMinus = valueErrorMinus[i];
    newData.valueErrorPlus = valueErrorPlus[i];
    mData->insertMulti(key[i], newData);
  }
}
void QCPGraph::setErrorBarSize (double size)
Sets the width of the handles at both ends of an error bar in pixels.
Definition at line 16141 of file qcustomplot.cpp.
References mErrorBarSize.
Referenced by QCPGraph().
{ mErrorBarSize = size; }
void QCPGraph::setErrorBarSkipSymbol (bool enabled)
If enabled is set to true, the error bar will not be drawn as a solid line under the scatter symbol but leave some free space around the symbol.
This feature uses the current scatter size (QCPScatterStyle::setSize) to determine the size of the area to leave blank. So when drawing Pixmaps as scatter points (QCPScatterStyle::ssPixmap), the scatter size must be set manually to a value corresponding to the size of the Pixmap, if the error bars should leave gaps to its boundaries.
setErrorType, setErrorBarSize, setScatterStyle
Definition at line 16157 of file qcustomplot.cpp.
References mErrorBarSkipSymbol.
Referenced by QCPGraph().
                                                 {
  mErrorBarSkipSymbol = enabled;
}
void QCPGraph::setErrorPen (const QPen & pen)
Sets the pen with which the error bars will be drawn.
See also
setErrorBarSize, setErrorType
Definition at line 16136 of file qcustomplot.cpp.
References mErrorPen, and QCPAbstractPlottable::pen().
Referenced by QCPGraph().
{ mErrorPen = pen; }
void QCPGraph::setErrorType (ErrorType errorType)
Sets which kind of error bars (Key Error, Value Error or both) should be drawn on each data point. If you set errorType to something other than etNone, make sure to actually pass error data via the specific setData functions along with the data points (e.g. setDataValueError, setDataKeyError, setDataBothError).
See also
ErrorType
Definition at line 16130 of file qcustomplot.cpp.
References errorType(), and mErrorType.
Referenced by QCPGraph().
{ mErrorType = errorType; }
void QCPGraph::setLineStyle (LineStyle ls)
Sets how the single data points are connected in the plot. For scatter-only plots, set ls to lsNone and setScatterStyle to the desired scatter style.
See also
setScatterStyle
Definition at line 16106 of file qcustomplot.cpp.
References mLineStyle.
Referenced by QCPGraph().
{ mLineStyle = ls; }
void QCPGraph::setScatterStyle (const QCPScatterStyle & style)
Sets the visual appearance of single data points in the plot. If set to QCPScatterStyle::ssNone, no scatter points are drawn (e.g. for line-only-plots with appropriate line style).
See also
QCPScatterStyle, setLineStyle
Definition at line 16115 of file qcustomplot.cpp.
References mScatterStyle.
                                                           {
  mScatterStyle = style;
}
QPointF QCPGraph::upperFillBasePoint (double upperKey) const [protected]
Definition at line 17774 of file qcustomplot.cpp.
References QCPAxis::atBottom, QCPAxis::atLeft, QCPAxis::atRight, QCPAxis::atTop, QCPAxis::axisRect(), QCPAxis::axisType(), QCPAxisRect::bottom(), QCPAxis::coordToPixel(), QCPAbstractPlottable::keyAxis(), QCPAxisRect::left(), QCPAbstractPlottable::mKeyAxis, QCPAbstractPlottable::mValueAxis, QCPAxis::orientation(), QCPAxis::range(), QCPAxis::rangeReversed(), QCPAxisRect::right(), QCPAxis::scaleType(), QCPAxis::stLinear, QCPAxisRect::top(), QCPRange::upper, and QCPAbstractPlottable::valueAxis().
Referenced by addFillBasePoints().
                                                          {
  QCPAxis *keyAxis = mKeyAxis.data();
  QCPAxis *valueAxis = mValueAxis.data();
  if (!keyAxis || !valueAxis) {
    qDebug() << Q_FUNC_INFO << "invalid key or value axis";
    return QPointF();
  }
  QPointF point;
  if (valueAxis->scaleType() == QCPAxis::stLinear) {
    if (keyAxis->axisType() == QCPAxis::atLeft) {
      point.setX(valueAxis->coordToPixel(0));
      point.setY(upperKey);
    } else if (keyAxis->axisType() == QCPAxis::atRight) {
      point.setX(valueAxis->coordToPixel(0));
      point.setY(upperKey);
    } else if (keyAxis->axisType() == QCPAxis::atTop) {
      point.setX(upperKey);
      point.setY(valueAxis->coordToPixel(0));
    } else if (keyAxis->axisType() == QCPAxis::atBottom) {
      point.setX(upperKey);
      point.setY(valueAxis->coordToPixel(0));
    }
  } else // valueAxis->mScaleType == QCPAxis::stLogarithmic
  {
    // In logarithmic scaling we can't just draw to value 0 so we just fill all
    // the way
    // to the axis which is in the direction towards 0
    if (keyAxis->orientation() == Qt::Vertical) {
      if ((valueAxis->range().upper < 0 && !valueAxis->rangeReversed()) ||
          (valueAxis->range().upper > 0 &&
           valueAxis->rangeReversed())) // if range is negative, zero is on
                                        // opposite side of key axis
        point.setX(keyAxis->axisRect()->right());
      else
        point.setX(keyAxis->axisRect()->left());
      point.setY(upperKey);
    } else if (keyAxis->axisType() == QCPAxis::atTop ||
               keyAxis->axisType() == QCPAxis::atBottom) {
      point.setX(upperKey);
      if ((valueAxis->range().upper < 0 && !valueAxis->rangeReversed()) ||
          (valueAxis->range().upper > 0 &&
           valueAxis->rangeReversed())) // if range is negative, zero is on
                                        // opposite side of key axis
        point.setY(keyAxis->axisRect()->top());
      else
        point.setY(keyAxis->axisRect()->bottom());
    }
  }
  return point;
}
Friends And Related Function Documentation
friend class QCPLegend [friend]
Definition at line 3034 of file qcustomplot.h.
friend class QCustomPlot [friend]
Definition at line 3033 of file qcustomplot.h.
Member Data Documentation
bool QCPGraph::mAdaptiveSampling [protected]
Definition at line 2974 of file qcustomplot.h.
Referenced by getPreparedData(), and setAdaptiveSampling().
QPointer<QCPGraph> QCPGraph::mChannelFillGraph [protected]
Definition at line 2973 of file qcustomplot.h.
Referenced by drawFill(), getChannelFillPolygon(), and setChannelFillGraph().
QCPDataMap* QCPGraph::mData [protected]
Definition at line 2966 of file qcustomplot.h.
Referenced by addData(), clearData(), countDataInBounds(), draw(), getKeyRange(), getPreparedData(), getValueRange(), getVisibleDataBounds(), pointDistance(), QCPGraph(), removeData(), removeDataAfter(), removeDataBefore(), rescaleKeyAxis(), rescaleValueAxis(), selectTest(), setData(), setDataBothError(), setDataKeyError(), setDataValueError(), and ~QCPGraph().
double QCPGraph::mErrorBarSize [protected]
Definition at line 2971 of file qcustomplot.h.
Referenced by drawError(), and setErrorBarSize().
bool QCPGraph::mErrorBarSkipSymbol [protected]
Definition at line 2972 of file qcustomplot.h.
Referenced by drawError(), and setErrorBarSkipSymbol().
QPen QCPGraph::mErrorPen [protected]
Definition at line 2967 of file qcustomplot.h.
Referenced by drawScatterPlot(), and setErrorPen().
ErrorType QCPGraph::mErrorType [protected]
Definition at line 2970 of file qcustomplot.h.
Referenced by drawError(), drawScatterPlot(), and setErrorType().
LineStyle QCPGraph::mLineStyle [protected]
Definition at line 2968 of file qcustomplot.h.
Referenced by draw(), drawFill(), drawLegendIcon(), getPlotData(), pointDistance(), and setLineStyle().
QCPScatterStyle QCPGraph::mScatterStyle [protected]
Definition at line 2969 of file qcustomplot.h.
Referenced by draw(), drawError(), drawLegendIcon(), drawScatterPlot(), pointDistance(), and setScatterStyle().
The documentation for this class was generated from the following files:
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.h
/home/peer23peer/VisionSoilAnalyzer/src/VSAGUI/qcustomplot.cpp