Hardware Namespace Reference
Namespaces
 Exception
Classes
class ADC
class BBB
class EC12P
class eQEP
class GPIO
class Microscope
class PWM
class SoilCape
class USB
Typedefs
typedef int(* CallbackType) (int)
Functions
void * threadedPollADC (void *value)
void * colorLoop (void *value)
void * threadedPolleqep (void *value)
void * threadedPollGPIO (void *value)
Typedef Documentation
typedef int(* Hardware::CallbackType) (int)
CallbackType used to pass a function to a thread
Definition at line 28 of file BBB.h.
Function Documentation
void * Hardware::colorLoop (void * value)
The thread function that runs trough all the colors
Definition at line 87 of file EC12P.cpp.
References i, Hardware::EC12P::SetPixelColor(), Hardware::EC12P::sleepperiod, and Hardware::EC12P::threadRunning.
    {
        int i = 0;
        EC12P *ec12p = static_cast<EC12P*>(value);
        EC12P::Color pcolor;
        while (ec12p->threadRunning)
        {
            pcolor = static_cast<EC12P::Color>(i);
            ec12p->SetPixelColor(pcolor);
            usleep(ec12p->sleepperiod);
            i++;
            if (i == 6) { i = 0; }
        }
        return ec12p;
    }
void * Hardware::threadedPollADC (void * value)
friendly function to start the threading
Definition at line 116 of file ADC.cpp.
References Hardware::BBB::callbackFunction, Hardware::BBB::threadRunning, and Hardware::ADC::WaitForValueChange().
    {
        ADC *adc = static_cast<ADC*>(value);
        while (adc->threadRunning)
        {
            adc->callbackFunction(adc->WaitForValueChange());
            usleep(200000);
        }
    }
void * Hardware::threadedPolleqep (void * value)
Definition at line 250 of file eqep.cpp.
References Hardware::BBB::callbackFunction, Hardware::BBB::debounceTime, Hardware::eQEP::get_position(), and Hardware::BBB::threadRunning.
    {
        eQEP *eqep = static_cast<eQEP*>(value);
        while (eqep->threadRunning)
        {
            eqep->callbackFunction(eqep->get_position(true));
            usleep(eqep->debounceTime * 1000);
        }
        return 0;
    }
void * Hardware::threadedPollGPIO (void * value)
Definition at line 180 of file GPIO.cpp.
References Hardware::BBB::callbackFunction, Hardware::BBB::debounceTime, Hardware::BBB::threadRunning, and Hardware::GPIO::WaitForEdge().
    {
        GPIO *gpio = static_cast<GPIO*>(value);
        while (gpio->threadRunning)
        {
            gpio->callbackFunction(gpio->WaitForEdge());
            usleep(gpio->debounceTime * 1000);
        }
        return 0;
    }