var annotated =
[
    [ "boost", "namespaceboost.html", null ],
    [ "Hardware", "namespace_hardware.html", "namespace_hardware" ],
    [ "SoilAnalyzer", "namespace_soil_analyzer.html", "namespace_soil_analyzer" ],
    [ "SoilMath", "namespace_soil_math.html", "namespace_soil_math" ],
    [ "Vision", "namespace_vision.html", "namespace_vision" ],
    [ "ADC", "class_a_d_c.html", null ],
    [ "BBB", "class_b_b_b.html", null ],
    [ "ChannelMismatchException", "class_channel_mismatch_exception.html", null ],
    [ "Conversion", "class_conversion.html", null ],
    [ "ConversionNotSupportedException", "class_conversion_not_supported_exception.html", null ],
    [ "DialogNN", "class_dialog_n_n.html", "class_dialog_n_n" ],
    [ "DialogSettings", "class_dialog_settings.html", "class_dialog_settings" ],
    [ "EC12P", "class_e_c12_p.html", null ],
    [ "EmtpyImageException", "class_emtpy_image_exception.html", null ],
    [ "Enhance", "class_enhance.html", null ],
    [ "ImageProcessing", "class_image_processing.html", null ],
    [ "Microscope", "class_microscope.html", null ],
    [ "PixelValueOutOfBoundException", "class_pixel_value_out_of_bound_exception.html", null ],
    [ "PopMemberStruct", "struct_pop_member_struct.html", "struct_pop_member_struct" ],
    [ "Predict_struct", "struct_predict__struct.html", "struct_predict__struct" ],
    [ "QOpenCVQT", "class_q_open_c_v_q_t.html", "class_q_open_c_v_q_t" ],
    [ "QParticleDisplay", "class_q_particle_display.html", "class_q_particle_display" ],
    [ "QParticleSelector", "class_q_particle_selector.html", "class_q_particle_selector" ],
    [ "QReportGenerator", "class_q_report_generator.html", "class_q_report_generator" ],
    [ "Segment", "class_segment.html", null ],
    [ "VSAMainWindow", "class_v_s_a_main_window.html", "class_v_s_a_main_window" ],
    [ "WrongKernelSizeException", "class_wrong_kernel_size_exception.html", null ]
];